### ISSUE TITLE
Chess960 and movetime crash

### ISSUE THREAD

**Issue by bend86** [official-stockfish/Stockfish#1014]
When working with some chess960 positions, it crashes when a movetime is defined.
No problem with "go" wxithout options.

To reproduce:

setoption name UCI_Chess960 value true
position fen Bnknb2b/p1p4p/1p2p1p1/8/P1pq2P1/2N3B1/1PPP3P/R1K2Q2 b KQk a3 0 13
go movetime 5000

Tested with the stockfish 8 stable version and last dev build 230217, compiled with "make stockfish ARCH=x86-64-modern COMP=clang" on Centos 7 64

Thank you.

**Comment by lantonov** [comment]
Reproduced with dev build 230217, Win 32 version. Also with Brainfish latest but not with the variant Stockfish latest (variant SF runs normally)

**Comment by theo77186** [comment]
Can confirm the issue. Moreover, there is a perft mismatch issue with the variant SF (the mainline SF is probably the bugged one) starting to depth 3.

**Comment by tthsqe12** [comment]
Can also confirm. Also, the crash occurrs when computing a bishop/rook attack bb.

**Comment by lantonov** [comment]
asmFish / pedantFish in Window does not crash and runs normally in the above situation.

**Comment by tthsqe12** [comment]
asmfish does not follow the crash-on-malformed-input paradigm.

**Comment by zamar** [comment]
Is the FEN legal?

**Comment by lucasart** [comment]
Not an issue. FEN illegal. Shit in, shit out...
