### ISSUE TITLE
DistanceTable

### ISSUE THREAD

**Issue by GuardianRM** [official-stockfish/Stockfish#1031]
Good time of day.
There is an idea to try to add a distance table for pawns, such as

![distancetable](https://cloud.githubusercontent.com/assets/23148603/23854524/dab6f210-0802-11e7-8717-327e8684de3e.png)

This table can give corrections to all types of pawn structures. In perspective, this can replace options such as doubled, psqt(if to add initial points) and some other. The question is how much such a table can be useful and how it can be implemented. In the extended version, it can also be used for all types of interaction of pieces too. This can add new data and replace some existing bonuses.

**Comment by zamar** [comment]
Please use forum for this sort of discussions.

This tracker is for bugs only.
