### ISSUE TITLE
function "time_to_pick" not used

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#1042]
The function "time_to_pick" is initialized but never used.  Line 92 in search.cpp.

bool time_to_pick(Depth depth) const { return depth / ONE_PLY == 1 + level; }

**Comment by vondele** [comment]
search.cpp:      if (skill.enabled() && skill.time_to_pick(rootDepth))

**Comment by MichaelB7** [comment]
riddle solved - thx
