### ISSUE TITLE
SF not running at 100% cpu anymore

### ISSUE THREAD

**Issue by hero2017** [official-stockfish/Stockfish#1055]
I don't know when this started or whether it's because I enabled HT on my dual e5-2696v3 system but the last version I tried, and the latest version as well, CPU is always 88-90%. It should be 100%.

It's probably because of HT being enabled but I still shouldn't lose 10%. I tried H5, asmF and it's 100% all the time. I'm using Win'2016.

**Comment by MichaelB7** [comment]
That's not SF, there is something else going on in your setup.  Some other program in your system is grabbing the CPU cycles, might be background process, e.g, antivirus software, back software etc.  SF is program to go 100% CPU , but ONLY if the CPU is available to go 100%.   I do not have windows,but one starts SF with the start command "Start /high sf.exe" or  with it "Start /realtime  sf.exe" should run at near 100% ..and if it does , you know it's your system and it doesn't, you know it's your system :>).

**Comment by hero2017** [comment]
How do you know it's not SF? I've been using SF for many years now and I never had this problem before except when SF wasn't numa aware and HT was enabled. There's nothing else that's using the other 10%.  There's no other software installed on this system. Even if SF is running with /realtime I get 90% cpu usage. I can stop SF and run asmFish and there's no problem; asmF runs at 100% always.

**Comment by MichaelB7** [comment]
What you described is known issue with some version of Windows, i.e., NUMA will not work properly if there more than one processor group and many cores.  I take it you are trying to run 72 threads on your 36 core box is that correct?  You already familiar with this issue and the possible fix, why not provide all the information in your first post?   
https://github.com/syzygy1/Cfish/commit/403811a0c6435ecc7ecf0c43e42dfcb56261f39f

**Comment by hero2017** [comment]
My apologies. I had forgotten all about that thread. Yes I'm running 72 cores (HT on). I thought this was fixed in SF which is why I am mentioning it here but I guess it was only fixed in asmFish and cFish. It would be nice if this fix could be added to SF.

**Comment by nabildanial** [comment]
Stockfish is used to use 100% of the CPU when it was using yielding spinlocks, but IIRC it has now using sleeping threads. But don't quote me on that, I don't follow the development as close as I used to do.

**Comment by lucasart** [comment]
Not an issue. Please close.

**Comment by zamar** [comment]
Closed.
