### ISSUE TITLE
Get even more enjoyment by playing some chess variants please!

### ISSUE THREAD

**Issue by BudiKusasi** [official-stockfish/Stockfish#1057]
Let's engine to be able to play chess variant that substitute all materials, except King of course, with its paws equivalent.
That would be one side has no queen, rook knight, and bishop but instead has addition 32 pawns more added  to the original 8 pawns (so total 40 pawns)
Current source code is giving engine that will be crash to do that, i.e not capable of performing it at all... Many Thanks in advance.

**Comment by lantonov** [comment]
You are looking for the variant Stockfish which is at
https://github.com/ddugovic/Stockfish
The closest variant to what you describe is "horde"

**Comment by BudiKusasi** [comment]
I only want strongest engine asmfish to perform that horde chess variant, would you please take a look at asmfish bug, why it errors when running on that kind variant condition and configuration.
Note: Komodo do it flawlessly on than configuration/condition (but far weaker than asmfish)

**Comment by MichaelB7** [comment]
Good luck with that - not an issue for this team here.

**Comment by ddugovic** [comment]
Until recently Stockfish would allow a player to have more than 8 pawns; however [for performance reasons this changed](http://github.com/official-stockfish/Stockfish/commit/c076216a32f6952d443eeeaaaea24bed9ebafa12) and [an assertion was added](http://github.com/official-stockfish/Stockfish/commit/06eba14dc984dc793e959ff7a5de19e1a190112b).

**Comment by MichaelB7** [comment]
Ok - so I'm assuming you can that can be unasserted with a variant define ?

**Comment by ianfab** [comment]
The length of the piece lists would also have to be increased, because it currently is only 16. Furthermore, if there are pawns on the first rank (starting position is not clear to me yet from the description), a few more issues will arise in the evaluation and move generation of pawns.

**Comment by zamar** [comment]
This is a bug tracker. Feature requests are closed.
