### ISSUE TITLE
Movetime crash in Linux (not Windows) for illegal FEN [WONTFIX]

### ISSUE THREAD

**Issue by SeanColombo** [official-stockfish/Stockfish#1077]
I've noticed a specific illegal FEN string is able to crash Stockfish on Linux, but fails gracefully in Windows (eg: it gives a move). It appears from user reports that this happens for a number of strings (perhaps lots of illegal strings) in Linux.  I'm not sure whether the Windows or Linux behavior is the correct one.

The FEN string is illegal because there is a pawn in the 8th rank.

To reproduce:
```
ucinewgame
isready
readyok
position fen 2P5/8/8/3p4/4bK2/8/4k1p1/2Q5 w - - 12 81
go depth 3
```
On Windows this gives:
```
info depth 1 seldepth 1 multipv 1 score cp 580 nodes 53 nps 26500 tbhits 0 time 2 pv f4e5
info depth 2 seldepth 2 multipv 1 score cp 966 nodes 123 nps 61500 tbhits 0 time 2 pv f4e5 d5d4 e5e4
info depth 3 seldepth 3 multipv 1 score cp 966 nodes 192 nps 96000 tbhits 0 time 2 pv f4e5 d5d4 e5e4
bestmove f4e5 ponder d5d4
```
(the Windows test-case was done on Windows 10 with Stockfish 6 stable and Stockfish 8 stable. Same result in both cases)

On Linux this gives:
```
info depth 1 seldepth 1 multipv 1 score cp 599 nodes 50 nps 50000 tbhits 0 time 1 pv c1c5
Segmentation fault (core dumped)
```
(the Linux test-case was done with both Stockfish 6 stable and Stockfish 8 stable, giving the same results (crash after 1 info line - on Ubuntu)).

**Comment by ddugovic** [comment]
How did the pawn get to the 8th rank?  (Were you using a GUI?)

**Comment by SeanColombo** [comment]
@ddugovic it was in [Simply Chess](http://store.steampowered.com/app/312280/) and appears to be an error where the underlying state of the board got messed up.  I'll be fixing that in Simply Chess separately, but still wanted to report this crash to help Stockfish.

Do you happen to know what the intended behavior is for illegal FEN strings in Stockfish? If not, do you know where I could find documentation that would list what the intended results are?  If that doesn't exist, I'd recommend either an error message or handling it like Windows does and still returning a result.

**Comment by ddugovic** [comment]
Stockfish abides by the [UCI specification](http://wbec-ridderkerk.nl/html/UCIProtocol.html) which does not specify how to validate input.  Because there are engine competitions, ease of use takes a back seat to performance.

There do exist libraries such as [python-chess](http://github.com/niklasf/python-chess) which help immensely with ease of use.

**Comment by SeanColombo** [comment]
@ddugovic makes sense.

Since validation is something that would be done once rather than repeatedly, (presumably a few milliseconds each time a FEN position is loaded), do you think it would be desirable for any validation to be added?  Or would that performance-tax potentially be bad even when just loading boards (I'm not familiar with all of the Stockfish use-cases).

If validation seems useful, I'd be happy to help pulling in some validation and unit-tests (there are probably good tests out there in open source projects already) and try to get that running.

I don't need it urgently for Simply Chess (since I should be able to fix board positions & should also be able to handle crashes in AI agents), but I'd be happy to help solve this one small Stockfish crash if desired.

**Comment by ddugovic** [comment]
I'll defer to maintainers though #905 was last discussion of something quite similar.

BTW nicely done with Simply Chess, it's been months since I last played there but it was fun.

**Comment by SeanColombo** [comment]
@ddugovic w0rd. Do you think #905 means "that's not really a defect, we don't need to do that" or more along the lines of "don't make a PR, we don't want it?

Thanks for the kind words about Simply Chess! :) Glad to hear you enjoyed it!

**Comment by ddugovic** [comment]
@SeanColombo Probably both.  While there are assertions in `position.cpp`, those only sanitize when compiled with `debug=yes`, but that compile-time option isn't used for the stable builds you refer to so adding more assertions wouldn't help you.

**Comment by SeanColombo** [comment]
@ddugovic thanks for the insight. Sounds like it should be closed as WONTFIX.

**Comment by ddugovic** [comment]
@SeanColombo You're welcome and I agree, the potential for privilege escalation is scary.  On the other hand, it would first be necessary to compromise the GUI to send illegal FEN to Stockfish, and an intermediate layer such as [python-chess](http://github.com/niklasf/python-chess) or your GUI's FEN-validator (if any) could mitigate such an attack.
