### ISSUE TITLE
Stockfish can't a find win in the simple position

### ISSUE THREAD

**Issue by sovaz1997** [official-stockfish/Stockfish#1109]
Found a position that Stockfish can not solve even with a large hash (Stockfish last, from 08/05/2017). FEN: 7k/6R1/8/8/2P2P2/P7/pP6/3K3B w - - 0 1. a
But after Rh7+ the program instantly finds a win. The fact is that in the end, the queen is caught through a small number of moves. I already had experience in developing engines, I will also think about the problem.

**Comment by MichaelB7** [comment]
no problem here...

info depth 52 seldepth 32 multipv 1 score cp 0 nodes 291063810 nps 25371671 hashfull 258 tbhits 4577965 time 11472 pv g7g5 a2a1q d1c2 a1h1 a3a4 h1h2 c2b3 h2f4 g5d5 f4f3 b3b4 h8g7 a4a5 f3f2 b2b3 g7f6 c4c5 f2e1 b4b5 e1f1 b5b6 f1b1 d5d6 f6e5 a5a6 b1b3
...
info depth 53 seldepth 37 multipv 1 score cp 7 lowerbound nodes 498148193 nps 26593433 hashfull 411 tbhits 7908187 time 18732 pv g7h7
info depth 53 currmove g7h7 currmovenumber 1
...
info depth 53 seldepth 76 multipv 1 score cp 12839 nodes 2552998360 nps 26980452 hashfull 989 tbhits 26532566 time 94624 pv g7h7 h8g8 h1d5 g8h7 d5e4 h7g7 d1c1 g7f7 c4c5 a2a1q e4b1 f7e6 f4f5 e6d5 f5f6 d5e6 c5c6 e6d6 c6c7 d6c7 f6f7 c7d7 f7f8q d7e6 f8g8 e6f6 g8a2 f6g5 a2a1

**Comment by sovaz1997** [comment]
After h7h8+ Stockfish detects a winning position almost instantly:

position fen 7k/6R1/8/8/2P2P2/P7/pP6/3K3B w - - 0 1 moves g7h7
go infinite
info depth 1 seldepth 1 multipv 1 score cp -508 nodes 9 nps 4500 tbhits 0 time 2 pv h8h7
info depth 2 seldepth 2 multipv 1 score cp -496 nodes 65 nps 32500 tbhits 0 time 2 pv h8h7 h1e4 h7g7
info depth 3 seldepth 4 multipv 1 score cp 205 nodes 135 nps 45000 tbhits 0 time 3 pv h8h7 h1g2 a2a1q d1c2
info depth 4 seldepth 6 multipv 1 score cp 143 nodes 256 nps 85333 tbhits 0 time 3 pv h8h7 h1e4 h7g7 c4c5 a2a1q d1c2
info depth 5 seldepth 7 multipv 1 score cp 180 nodes 431 nps 143666 tbhits 0 time 3 pv h8h7 h1e4 h7g7 c4c5 a2a1q d1c2 a1e1
info depth 6 seldepth 8 multipv 1 score cp 263 nodes 2819 nps 469833 tbhits 0 time 6 pv h8h7 d1c2 a2a1q h1d5 h7g7 a3a4 a1a4 b2b3
info depth 7 seldepth 9 multipv 1 score cp 274 nodes 3706 nps 463250 tbhits 0 time 8 pv h8h7 h1e4 h7g7 d1c2 a2a1q e4d3 a1e1 b2b4 e1f2 c2c3 f2f4
info depth 8 seldepth 10 multipv 1 score cp 274 nodes 4701 nps 522333 tbhits 0 time 9 pv h8h7 h1e4 h7g7 d1c2 a2a1q e4d3 a1e1 b2b4 e1f2 c2c3
info depth 9 seldepth 14 multipv 1 score cp 257 nodes 6941 nps 578416 tbhits 0 time 12 pv h8h7 h1e4 h7g7 d1c2 a2a1q e4d3 g7f6 c4c5 a1e1 b2b4
info depth 10 seldepth 15 multipv 1 score cp 283 nodes 10474 nps 654625 tbhits 0 time 16 pv h8h7 h1e4 h7g7 d1c2 a2a1q e4d3 g7f6 c4c5 a1e1 b2b4 e1e3 a3a4 e3f4
info depth 11 seldepth 22 multipv 1 score cp 292 nodes 42344 nps 1008190 tbhits 0 time 42 pv h8h7 h1d5 a2a1q d1c2 h7g7 c4c5 a1f1 b2b4 f1f4 c2b3 f4e3 b3a4 g7f6
info depth 12 seldepth 22 multipv 1 score cp 285 nodes 48556 nps 971120 tbhits 0 time 50 pv h8h7 h1e4 h7g7 d1c2 a2a1q e4d3 g7f6 c4c5 a1e1 b2b4 e1f2 c2c3 f6e6 a3a4 f2f4
info depth 13 seldepth 23 multipv 1 score cp -11 nodes 99641 nps 1094956 tbhits 0 time 91 pv h8h7 h1e4 h7h6 d1c1 a2a1q e4b1 h6h5 c4c5 h5g4 c1c2 g4f5 c5c6 f5e6 f4f5 e6f6 c6c7
info depth 14 seldepth 23 multipv 1 score cp -19 nodes 112154 nps 1099549 tbhits 0 time 102 pv h8h7 h1e4 h7g7 d1c1 a2a1q e4b1 g7f6 c4c5 f6e6 f4f5 e6d5 f5f6 d5c4 f6f7 c4b3 f7f8q a1b2 c1d1 b2b1 d1e2 b1e4 e2f2
info depth 15 seldepth 36 multipv 1 score cp -58 nodes 159125 nps 1153079 tbhits 0 time 138 pv h8h7 h1e4 h7g7 d1c1 a2a1q e4b1 g7f6 c4c5 f6e6 f4f5 e6d5 f5f6 d5c4 f6f7 c4b3 f7f8q a1b2 c1d1 b2b1 d1d2 b1c2 d2e3 c2c3 e3e4 c3c4 e4e5 c4e2 e5d5 e2d3 d5c6
info depth 16 seldepth 36 multipv 1 score cp -56 nodes 173938 nps 1151907 tbhits 0 time 151 pv h8h7 h1e4 h7g7 d1c1 a2a1q e4b1 g7f6 c4c5 f6e6 f4f5 e6d5 f5f6 d5c4 f6f7 c4b3 f7f8q a1b2 c1d1 b2b1 d1d2 b1c2 d2e3 c2c3 e3e4 c3c4 e4e5 c4e2 e5d5 e2d3 d5e6 d3e4 e6d6 b3a3 d6c7 e4e5 c7b6
info depth 17 seldepth 45 multipv 1 score cp -208 nodes 326053 nps 1152130 tbhits 0 time 283 pv h8h7 h1e4 h7g7 d1c1 a2a1r c1c2 a1f1 b2b4 f1f4 e4d5 g7f6 b4b5 f6e5 a3a4 e5d4 a4a5 d4c5 c2b3 f4f8 b5b6 f8d8
info depth 18 seldepth 45 multipv 1 score cp -254 nodes 582911 nps 1129672 tbhits 0 time 516 pv h8h7 h1e4 h7g7 d1c1 a2a1r c1c2 a1f1 b2b4 f1f4 c2d3 g7f6 d3d4 f4f1 a3a4 f1a1 a4a5 f6e7 d4c5 e7d7 e4b7 d7c7 a5a6
info depth 19 seldepth 45 multipv 1 score cp -743 nodes 1742308 nps 1150038 hashfull 560 tbhits 0 time 1515 pv h8h7 h1e4 h7g7 d1c1 a2a1n b2b4 a1b3 c1c2 b3d4 c2d3 d4e6 b4b5 g7f7 b5b6 f7e7 b6b7 e6c5 d3d4 c5d7 c4c5 e7d8 c5c6 d7b8 f4f5 d8c7 f5f6 b8a6
info depth 20 seldepth 45 multipv 1 score cp -818 nodes 1992623 nps 1167324 hashfull 593 tbhits 0 time 1707 pv h8h7 h1e4 h7g7 d1c1 g7f6 e4b1 a2a1n b1a2 f6f5 c4c5 f5f4 c1b1 f4e5 b1a1 e5f6 b2b4 f6e7 a1b2 e7d8 a2d5 d8c8 b4b5 c8b8 a3a4
info depth 21 seldepth 45 multipv 1 score cp -886 nodes 2350901 nps 1189727 hashfull 627 tbhits 0 time 1976 pv h8h7 h1e4 h7g7 d1c1 a2a1n b2b4 a1b3 c1c2 b3d4 c2d3 d4e6 b4b5 e6f4 d3d4 g7f8 b5b6 f4e6 d4d5 f8e7 c4c5 e6c7 b6c7 e7d7 c5c6 d7c8 e4f5 c8c7 d5c5 c7d8 c5d6 d8e8 c6c7
info depth 22 seldepth 45 multipv 1 score cp -1002 nodes 2819647 nps 1206524 hashfull 682 tbhits 0 time 2337 pv h8h7 h1e4 h7g7 d1c1 a2a1n b2b4 a1b3 c1c2 b3d4 c2d3 d4e6 b4b5 e6c7 b5b6 c7a6 d3d4 g7f8 b6b7 f8e7 f4f5 a6b8 c4c5 e7e8 c5c6 b8a6 d4e5
info depth 23 seldepth 45 multipv 1 score cp -1131 nodes 3401797 nps 1221471 hashfull 727 tbhits 0 time 2785 pv h8g8 h1d5 g8f8 d1c2 a2a1q h7h1 a1a2 c2c3 f8e7 d5e4 e7d8 e4b1 a2a1 h1d1 d8c7 b1c2 a1d1 c2d1 c7d7 b2b4 d7e7 d1c2 e7d6 c2e4 d6c7 f4f5 c7b6 c4c5 b6c7
info depth 24 currmove h8h7 currmovenumber 2
info depth 24 seldepth 45 multipv 1 score cp -1175 upperbound nodes 3752176 nps 1229818 hashfull 755 tbhits 0 time 3051 pv h8g8 h1d5
info depth 24 currmove h8g8 currmovenumber 1
info depth 24 seldepth 45 multipv 1 score cp -1131 lowerbound nodes 3865479 nps 1232614 hashfull 767 tbhits 0 time 3136 pv h8g8
info depth 24 currmove h8g8 currmovenumber 1
info depth 24 currmove h8h7 currmovenumber 2
info depth 24 seldepth 45 multipv 1 score cp -1180 upperbound nodes 3884753 nps 1231300 hashfull 767 tbhits 0 time 3155 pv h8g8 h1d5
info depth 24 currmove h8g8 currmovenumber 1
info depth 24 currmove h8h7 currmovenumber 2
info depth 24 seldepth 45 multipv 1 score cp -1243 upperbound nodes 4020191 nps 1232053 hashfull 775 tbhits 0 time 3263 pv h8g8 h1d5
info depth 24 currmove h8g8 currmovenumber 1
info depth 24 seldepth 45 multipv 1 score cp -1159 lowerbound nodes 4081189 nps 1229644 hashfull 783 tbhits 0 time 3319 pv h8g8

**Comment by ddugovic** [comment]
@sovaz1997 Since you're so insistent... **_how_** is this position simple?

**Comment by sovaz1997** [comment]
It's simple for Stockfish already after the Rh8 + move. More than a minute goes to find the right move, but if this move is done, Stockfish instantly (!) Finds a win. There at the end of the variant the queen is locked and pawns go to the queens.

**Comment by ddugovic** [comment]
Certainly after the rook is offered _en prise_ the rest of the sequence is quite forcing and luckily for White the K+B+4P versus K+Q endgame is winning despite the Black king being "in the square" of all the White pawns and despite White's bishop being pinned.

I still don't understand why Black plays Kxh7.

**Comment by MichaelB7** [comment]
Kg8 then Bd5+ leads to mate

**Comment by ddugovic** [comment]
Ah, best play seems to be `1. Rh7+ Kg8 2. Bd5+ Kf8 3. f5 a1=Q 4. Kc2 Qf1 5. f6 Ke8 6. f7+ Ke7 7. f8=Q!+ Kxf8 8. Rf7+ Qxf7 9. Bxf7 Kxf7` and White wins; or best play involves Black playing some checks and the pawn promotes.

**Comment by zamar** [comment]
Not a bug
