### ISSUE TITLE
Request: add UCI option, "variety"

### ISSUE THREAD

**Issue by 0zymandia2** [official-stockfish/Stockfish#1131]
Komodo has offered this since version 10.4.

Kai Lassos did some testing with this option, and it looks like SF might benefit from it [even more than Komodo](http://www.talkchess.com/forum/viewtopic.php?p=709073#709073). It would be helpful to avoid doubles at hyper-bullet TCs.

Unless I missed something, this hasn't been brought up before.

**Comment by zamar** [comment]
Unfortunately the project does not accept feature requests.
