### ISSUE TITLE
does Vondele's data race patch go far enough?

### ISSUE THREAD

**Issue by tthsqe12** [official-stockfish/Stockfish#1156]
I understand some of the data races in this patch and can see that the patch fixes an academic issue and is basically useless on x86-64.
However, this brings me to the way the threads receive the position from the gui thread. It goes something like this:
1) gui thread sets its position
2) gui thread copies its position to thread0
3) gui thread then wakes up thread0
4) gui goes back to loop

On strongly ordered machines like x86 2)->3) is no problem for each thread. However, on weakly ordered machines like arm, isn't there no guarantee that each thread, after being woken up, is seeing the position that the GUI copied in 2)?

If the answer to this question is in fact that there is no guarantee, then would a atomic_thread_fence between 2) and 3) be sufficient?

**Comment by mcostalba** [comment]
To wake up thread0 a lock is taken in Thread::start_searching(), this ensures the fence:

https://stackoverflow.com/questions/11172922/does-stdmutex-create-a-fence
