### ISSUE TITLE
Different optimization flags for profile-use and profile-generate

### ISSUE THREAD

**Issue by beyondCritics** [official-stockfish/Stockfish#1164]
The flags used for "gcc-profile-make:"
https://github.com/official-stockfish/Stockfish/blob/master/src/Makefile#L533
are significantly different from those used for the final executable:
https://github.com/official-stockfish/Stockfish/blob/master/src/Makefile#L539
Obviously, this can distort generated statistics.

**Comment by beyondCritics** [comment]
I have tested the original makefile vs. one with identical optimization options using intel vtune on linux.
In the former case, i see several placwa, where curiously a branch is mispredicted 100% of the time.
The hot function _partial_insertion_sort_ has its loop mispredicted 68% of the time. With corrected options, this goes down to 28% (on my machine).

**Comment by lucasart** [comment]
good spot. so which flags are best, in your experience: gcc-profile-make or gcc-profile-use ?

**Comment by mstembera** [comment]
I think the flags being referred to are -fno-peel-loops and -fno-tracer.  Adding them to gcc-profile-make: results in nothing measurable for me.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1124320   1125502   -1182     
    StDev   16627     17454     4611      

p-value: 0.601
speedup: 0.001
```

Removing them from gcc-profile-use: results in over a 3% slowdown.
```
Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    1115266   1079672   35594     
    StDev   13630     14591     2433      

p-value: 0
speedup: -0.032
```
My platform: gcc 7.1.0, x86-64-modern, Win10-64,  mobile i7

What specific changes do you propose to the makefile?  I thought it was ok to collect all statistics and later select which ones to make use of and which to ignore.

**Comment by beyondCritics** [comment]
I simply propose to use the same flags for profiling and building.
BTW: You are using a script to conduct t-tests? If it is public available, could you give an URL? Thank you.

**Comment by mstembera** [comment]
I use Fishbench
https://github.com/zardav/FishBench

**Comment by mcostalba** [comment]
The way to approach this is to remove all low level flags and just use the general purpose ones like -O3.

**Comment by zamar** [comment]
Removed offending flags.
