### ISSUE TITLE
Hash file never saves.

### ISSUE THREAD

**Issue by hero2017** [official-stockfish/Stockfish#1190]
I started analyzing a position for the first time and after 3 mins I stopped the engine and clicked SavetoHash....the file never finishes creating. It's always 0 bytes and cannot be deleted. Hash was set to 4 GB and I waited up to 10 mins. It's saving to a fast SSD so it shouldn't even take 5 mins.

Can someone test it and see if they have the same problem using Aquarium 2017 (likely older version test will be fine too)?

**Comment by beyondCritics** [comment]
Stockfish is open source, anyone is entitled to make a fork, add any features he like and in turn control them. Hash saving is not part of official-stockfish, therefore your are at the wrong place here.

You could ask at http://talkchess.com

**Comment by hero2017** [comment]
No that's fine. I'll simply stick to SF based clones. I'll never ask SF of any features or mention bugs. They're too ignorant to users. Sorry, but that's been my experience with SF for I don't know how many years now. So I don't know why I bother trying to improve SF with suggestions. Waste of my time!

**Comment by beyondCritics** [comment]
You wasted _my_ time with your ignorant and completely superflous question. Rest assured, this was the last time i did that.
Furthermore, i am just a normal user like you are, keep that in mind.

**Comment by hero2017** [comment]
Why are you wasting your time answering such questions if you're just a normal user like me? This is a question for the SF team and its developers. Anyway, I'm glad you've wasted your time then. I guess we're even. Please do not try to answer when you have no real answer to people's questions.

You're officially on my ignore list from now on!

**Comment by mausalimi** [comment]
you did not come here with a suggestion, rather a bug report.
and that bug is in a feature that is not part of the official stockfish.
so yes, this was the wrong place.

**Comment by bftjoe** [comment]
asmfish might have this already. https://github.com/lantonov/asmFish/issues/69
