### ISSUE TITLE
[feature request] polyglot adapter

### ISSUE THREAD

**Issue by YouriAndropov** [official-stockfish/Stockfish#1195]
Hi all,

Could it be possible to put again (as in version 2) in stockfish code the polyglot adapter allowing native polyglot opening books management ?

**Comment by nabildanial** [comment]
Just use AsmFish. It supports Polyglot opening books, and much faster than official release anyways.

**Comment by lucasart** [comment]
No. It's the job of the GUI to play opening book moves on behalf of the engine.

**Comment by mcostalba** [comment]
Polyglot adapter is used in case teh engine manages opening books, but this is not the case with Stockfish. Some years ago it was decided that book handling should be up to the GUI and the engine should be book agnostic. In hindsight I think this was a good decision.

**Comment by YouriAndropov** [comment]
It should be the user's choice, not yours. That's my opinion.
