### ISSUE TITLE
A crash on iOS devices

### ISSUE THREAD

**Issue by Hengyu** [official-stockfish/Stockfish#1222]
To whom it may concern,

I am using the latest version of `Stockfish`. And I made some modification on `Stockfish` to make it compatible with iOS. I encountered a crash with the following game:
```
position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves g1f3 e7e6 g2g3 d7d5 f1g2 c7c5 d2d4 c5d4 e1g1 g8f6 c1f4 h7h6 f3d4 b8d7 d4f3 d8b6 d1c1 f8c5 b1c3 f6g4 c3d1 e6e5 f4d2 e5e4 f3e1 h6h5 c2c4 h5h4 c4d5 d7f6 e1c2 h4h3 g2h1 g4h2 g1h2 f6g4 h2g1 b6d6 d2f4
```

I havn't tested this on the other platforms. And can't tell whether it is a bug in `Stockfish` or some bugs in Xcode or my code. But I tested many other chess examples on my code, they work very well. 

~~Please close this issue if this crash is not caused by `Stockfish`. Thanks.~~
**Sorry, please close this issue. I just tested this game on my Mac with the compiled `Stockfish`. It works fine.**

**Comment by MichaelB7** [comment]
FYI, iOS is the iPhone OS, not the macOS used by  Macs.
