### ISSUE TITLE
ButterflyBoards assert triggers in VS17 

### ISSUE THREAD

**Issue by stuwph** [official-stockfish/Stockfish#1227]
VS17 **debug** 64bit, triggers an assert in movepick.h
when changing "Threads" higher as in ucioption.cpp defined

for example in console:
setoption name threads value 2
go 

compiled with ucioption.cpp     `o["Threads"]               << Option(1, 1, 512, on_threads);`

movepick.h `assert(abs(entry) <= 32 * D);`   <--- triggers

seems entry is not initialized in this case?

happens since commit **History code rewrite (#1122)**, May 26

**Comment by vondele** [comment]
@stuwph thanks for the report.

I have an idea, could you check what happens if you issue an ucinewgame after setting the number of threads? So

``` 
setoption name Threads value 2
ucinewgame
go depth 15
```

basically, verify that the assert triggers without ucinewgame, and does not trigger with ucinewgame.

**Comment by stuwph** [comment]
```
setoption name Threads value 2
ucinewgame
go depth 15
```
-> triggers

```
setoption name Threads value 2
go depth 15
```
-> does not

also a `Search::clear();
` in uci.cpp `void go(Position& pos, istringstream& is, StateListPtr& states)`
```
        else if (token == "perft")     is >> limits.perft;
        else if (token == "infinite")  limits.infinite = 1;
        else if (token == "ponder")    ponderMode = true;

    Search::clear(); // <--
    Threads.start_thinking(pos, states, limits, ponderMode);
  }
```
-> does not

**Comment by vondele** [comment]
@stuwph is the above comment correct, i.e. the assert triggers if ucinewgame is executed ? I'm expecting the inverse behavior.

**Comment by stuwph** [comment]
your expecting is right - changed comment to reverse

**Comment by vondele** [comment]
@stuwph can you check that current master (after commit https://github.com/official-stockfish/Stockfish/commit/e385f194e970f0675bd4c3509bca4a6c81b6df5e) doesn't suffer anymore from this problem, and close the bug report accordingly.

**Comment by stuwph** [comment]
issue solved

you are doing a lot of good things for stockfish
