### ISSUE TITLE
Use C++ exception upon signal 'stop'

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#1232]
I write here because of lack of a better place.

In the past  I have tried to remove all `if (stop) ...` kind of code scattered in the search and instead use a more elegant and general scheme based on exceptions. I tried this when SMP was implemented with YBWC and I failed. perhaps today with lazy SMP is easier...but I don't expect it to be trivial.

This is a possible sub-project for people interested in trying something different from the usual search/evaluation tweak.

Of course a possible implementation should:

- Simplify current code in an elegant and clean way (no hacks, no tricks)
- Be at least on par with current (do not regress)

**Comment by vondele** [comment]
possible patches discussed here https://github.com/official-stockfish/Stockfish/pull/1292
