### ISSUE TITLE
Support questions is full of spam 

### ISSUE THREAD

**Issue by bftjoe** [official-stockfish/Stockfish#1243]
Much spam at http://support.stockfishchess.org/discussions/questions

**Comment by MichaelB7** [comment]
Looks like we need to block spammers or maybe use CAPTCHA -> http://www.captcha.net
it's free.

**Comment by mcostalba** [comment]
Unrelated to SF development. Closing.

**Comment by bftjoe** [comment]
Okay, but the spam is still there and it's the official site of stockfish, no?

**Comment by bftjoe** [comment]
How is a site where the people ask questions about how stockfish works "unrelated to stockfish development"? Do you really do anything to keep the open issue count low?

**Comment by MichaelB7** [comment]
The way it’s being maintained is worthless - might as well shut it down.
