### ISSUE TITLE
Does this support perft?

### ISSUE THREAD

**Issue by sciencefyll** [official-stockfish/Stockfish#1251]
I'm looking for a engine which I can use to debug my own move generator.

**Comment by syzygy1** [comment]
Perft is supported. It even shows the node count per move.

For unclear reasons you now have to type "go perft 5" instead of the natural "perft 5" (as if perft was included in the UCI spec, which it is not).

**Comment by vondele** [comment]
@sciencefyll please close the issue, this is the bug tracker. Such questions belong in the mailing list.

**Comment by syzygy1** [comment]
They belong in the support forum, but that has been killed by spam (see the other issue).
