### ISSUE TITLE
Stockfish crashes with FEN r1bqkb1r/ppp2ppp/2np4/3P2N1/2BQ4/7P/PPP3P1/RNB4q w KQkq - 0 12

### ISSUE THREAD

**Issue by ngocdaothanh** [official-stockfish/Stockfish#1253]
Steps to reproduce:

* Download the latest version of Stockfish at https://github.com/official-stockfish/Stockfish.git
* Build: `make build ARCH=x86-64`
* Start Stockfish, and input: `position fen r1bqkb1r/ppp2ppp/2np4/3P2N1/2BQ4/7P/PPP3P1/RNB4q w KQkq - 0 12`
* Stockfish will crash.

**Comment by Nordlandia** [comment]
White king is missing in the FEN.
