### ISSUE TITLE
"Step 19." is missing in the comment of search.cpp

### ISSUE THREAD

**Issue by yaneurao** [official-stockfish/Stockfish#1258]
Sorry about trivial things ,"Step 19." is missing in the comment of search.cpp.

**Comment by tthsqe12** [comment]
you want to put YBWC back into the search?

**Comment by yaneurao** [comment]
I see. "Step 19." is where the comment for YBWC was written once. Now that we do not use YBWC, is not it okay to move forward after "Step 20."?
