### ISSUE TITLE
Search Depth Distribution Algorithm

### ISSUE THREAD

**Issue by omor1** [official-stockfish/Stockfish#1290]
Hello,

For a project, we are looking towards implementing distributed memory computation, using MPI or a similar library/framework.
As we are exploring Stockfish's codebase, we are consistently confused with the following lines:
```C++
/* search.cpp */
void Thread::search() {
  ...
  while (   (rootDepth += ONE_PLY) < DEPTH_MAX
         && !Threads.stop
         && !(Limits.depth && mainThread && rootDepth / ONE_PLY > Limits.depth))
  {
      // Distribute search depths across the threads
      if (idx)
      {
          int i = (idx - 1) % 20;
          if (((rootDepth / ONE_PLY + rootPos.game_ply() + skipPhase[i]) / skipSize[i]) % 2)
              continue;
      }
      ...
  }
  ...
}
```

This would *appear* to imply that Stockfish can only support up to 20 threads (or at least 20 threads that start out search at distinct depths). This is at odds with the statement (from the Readme):
>This version of Stockfish supports up to 512 cores.

Are we misunderstanding this code, or does Stockfish only distribute 20 distinct depths across threads and use some other parallel computation mechanism to scale to 512 cores? Would the current parallel computation mechanism scale across computation nodes (in a compute cluster), or is some other mechanism necessary (ignoring problems due to the hash tables no longer being shared)?

Lastly—assuming that we manage to get this working—would this be something that you would be interested in upstreaming?

Thanks!

**Comment by Ipmanchess** [comment]
I'm for sure interested to test it!

Good luck with your project..
Ipman.

**Comment by vondele** [comment]
The 20 doesn't imply it doesn't work with more cores, just that the heuristics on 'diversifying' the work of the threads is not more general. This is not necessarily a problem.

**Comment by omor1** [comment]
So suppose you're using 40 threads. Wouldn't thread 0 (main thread) and thread 20 start searching at the same depth and thus be duplicating work? Of course, they'll end up with somewhat different results, due to the effects of nondeterminism, but that still seems to me to be a limiting factor.

Or have I misunderstood?

**Comment by vondele** [comment]
well, thread 0 and 20 will start at the same depth, but search will diverge so quickly that it doesn't matter.... at least that is the idea. You could test by removing this ply skipping altogether, and it wouldn't loose more than, say, 10 elo. The basic lazySMP idea is that the gain is from sharing the TT.

That really doesn't imply it is optimal the way it currently is, and I sure would think it is a good (difficult!) project. In case you haven't read this yet, the following is interesting in this context http://www.talkchess.com/forum/viewtopic.php?t=64824

**Comment by omor1** [comment]
Thanks for that link—it was very informative!

So most of the gain is due to threads not searching the same state (due to the shared transposition table), which allows different threads' search trees to rapidly diverge, correct?
So to achieve the same benefit in a cluster (instead of a single SMP computer), data from the transposition table must be shared, as Peter Österlund described.

On a related note, a new version of his engine, [Texel 1.07](http://www.talkchess.com/forum/viewtopic.php?t=65339), was released about a month ago with cluster/MPI support. Since it's also GPLv3, I believe we should be free to use ideas from it in the Stockfish implementation?

**Comment by omor1** [comment]
Also, a further note—I don't think that Stockfish currently uses thread affinities to ensure that threads run on a particular core (for reasons such as e.g. cache reuse), as that correct? Using thread affinities would require going into pthreads (on POSIX) or whatever equivalent Windows API, which should be possible using `std::thread::native_handle()`.

**Comment by lucasart** [comment]
@omor1: a simple grep affinity will answer your question.

**Comment by omor1** [comment]
@lucasart my understanding is that thread affinities to cores are set on Windows, but not on POSIX platforms?

**Comment by Stefano80** [comment]
Is this an issue or a topic for the forum?

**Comment by vondele** [comment]
not an issue, so should be closed, AFAICT.

**Comment by omor1** [comment]
@Stefano80 @vondele @mcostalba I see that there's an actual forum, [FishCooking](https://groups.google.com/forum/?fromgroups=#!forum/fishcooking)—should I post over there instead?II hadn't seen the forum when I first posted here—sorry about that!

**Comment by Stefano80** [comment]
Yes, start a thread there.
