### ISSUE TITLE
30 Dec 2017: PVS-Studio, cppcheck errors and gcc warnings

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#1350]
**GCC 5.1.0 WARNINGS:**

syzygy/tbprobe.cpp: In function 'T {anonymous}::probe_table(const Position&, Tablebases::ProbeState*, Tablebases::WDLScore) [with E = {anonymous}::WDLEntry; T = Tablebases::WDLScore]':
syzygy/tbprobe.cpp:760:30: warning: array subscript is above array bounds [-Warray-bounds]
             if (d->pieces[i] == pieces[j])
                              ^
syzygy/tbprobe.cpp: In function 'int Tablebases::probe_dtz(Position&, Tablebases::ProbeState*)':
syzygy/tbprobe.cpp:760:30: warning: array subscript is above array bounds [-Warray-bounds]
             if (d->pieces[i] == pieces[j])
                              ^

**CPPCHECK:**

[Stockfish/src/psqt.cpp:112]: (error) Array index -2 is out of bounds.
      PieceValue[MG][~pc] = PieceValue[MG][pc];

[Stockfish/src/psqt.cpp:113]: (error) Array index -2 is out of bounds.
      PieceValue[EG][~pc] = PieceValue[EG][pc];

[Stockfish/src/psqt.cpp:121]: (error) Array index -1 is out of bounds.
          psq[~pc][~s] = -psq[pc][s];

[Stockfish/src/syzygy/tbprobe.cpp:415]: (error) Using 'memset' on struct that contains a 'std::atomic_bool'.
    memset(this, 0, sizeof(WDLEntry));

[Stockfish/src/syzygy/tbprobe.cpp:456]: (error) Using 'memset' on struct that contains a 'std::atomic_bool'.
    memset(this, 0, sizeof(DTZEntry));

**PVS-STUDIO:**

/home/dew/Stockfish/src/bitbase.cpp     127     err     V557 Array underrun is possible. The '~us' index is pointing beyond array bound.
            && (    distance(ksq[~us], psq + NORTH) > 1

/home/dew/Stockfish/src/bitbase.cpp     133     err     V557 Array underrun is possible. The '~us' index is pointing beyond array bound.
            && (  !(PseudoAttacks[KING][ksq[us]] & ~(PseudoAttacks[KING][ksq[~us]] | PawnAttacks[~us][psq]))

/home/dew/Stockfish/src/bitbase.cpp     134     err     V557 Array underrun is possible. The '~us' index is pointing beyond array bound.
                 || (PseudoAttacks[KING][ksq[us]] & psq & ~PseudoAttacks[KING][ksq[~us]])))

/home/dew/Stockfish/src/bitboard.h      215     err     V557 Array overrun is possible. The 'pawn_passed' function processes value '[-2..-1]'. Inspect the first argument. Check lines: 'bitboard.h:215', 'position.h:312', 'evaluate.cpp:808'.
  return PassedPawnMask[c][s];

/home/dew/Stockfish/src/movepick.cpp    70      err     V730 Not all members of a class are initialized inside the constructor. Consider inspecting: cur, endMoves, endBadCaptures, recaptureSquare, threshold, moves.
MovePicker::MovePicker(const Position& p, Move ttm, Depth d, const ButterflyHistory* mh,

/home/dew/Stockfish/src/search.cpp      554     err     V629 Consider inspecting the 'excludedMove << 16' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.
    posKey = pos.key() ^ Key(excludedMove << 16); // isn't a very good hash

/home/dew/Stockfish/src/ucioption.cpp   106     err     V730 Not all members of a class are initialized inside the constructor. Consider inspecting: idx.
Option::Option(const char* v, OnChange f) : type("string"), min(0), max(0), on_change(f)

/home/dew/Stockfish/src/ucioption.cpp   109     err     V730 Not all members of a class are initialized inside the constructor. Consider inspecting: idx.
Option::Option(bool v, OnChange f) : type("check"), min(0), max(0), on_change(f)

/home/dew/Stockfish/src/ucioption.cpp   112     err     V730 Not all members of a class are initialized inside the constructor. Consider inspecting: idx.
Option::Option(OnChange f) : type("button"), min(0), max(0), on_change(f)

/home/dew/Stockfish/src/ucioption.cpp   115     err     V730 Not all members of a class are initialized inside the constructor. Consider inspecting: idx.
Option::Option(int v, int minv, int maxv, OnChange f) : type("spin"), min(minv), max(maxv), on_change(f)

/home/dew/Stockfish/src/syzygy/tbprobe.cpp      759     err     V791 The initial value of the index in the nested loop equals 'i'. Perhaps, 'i + 1' should be used instead.
        for (int j = i; j < size; ++j)

**Comment by DU-jdto** [comment]
[Stockfish/src/psqt.cpp:112]: (error) Array index -2 is out of bounds.
PieceValue[MG][~pc] = PieceValue[MG][pc];

[Stockfish/src/psqt.cpp:113]: (error) Array index -2 is out of bounds.
PieceValue[EG][~pc] = PieceValue[EG][pc];

[Stockfish/src/psqt.cpp:121]: (error) Array index -1 is out of bounds.
psq[~pc][~s] = -psq[pc][s];

These three seem to just be it failing to recognize the ~ operator overloads.

**Comment by vondele** [comment]
- gcc 5.1.0 warnings seem spurious (note this version of gcc is EOL).
- afaict the cppcheck warning on the atomic_bool is also not correct (as an atomic_bool is trivially copyable, should be OK for memset).
- I guess also PVS-studio doesn't see the overload of the ~ hence the warnings.
- some warnings for partially initialized class members are correct, don't think they need fixing.

at first glance non of the warnings are a real issue.

**Comment by d3vv** [comment]
@vondele 

I didn't print warnings for checker cause there are of tone...
As for pvs-studio:

/home/dew/Stockfish/src/psqt.cpp             warn    V557 Array underrun is possible. The value of '~pc' index could reach -7.
/home/dew/Stockfish/src/psqt.cpp             warn    V557 Array underrun is possible. The value of '~pc' index could reach -7.
/home/dew/Stockfish/src/psqt.cpp             warn    V557 Array underrun is possible. The value of '~pc' index could reach -7.
/home/dew/Stockfish/src/psqt.cpp             warn    V557 Array underrun is possible. The value of '~s' index could reach -64.

**Comment by vondele** [comment]
@d3vv these all seem a bug in the tool used for checking. ~ is overloaded in the code (see types.h from line 355), and the tool seems to ignore that.

**Comment by d3vv** [comment]
@vondele It seems You know better cause as for me, it is too hard understand constexpr code from c++11 library for my mental abilities

**Comment by DU-jdto** [comment]
Look at what the overloads actually are. ~pc is the same as (pc ^ 8), and ~s is the same as (s ^ 56). It is mathematically impossible to get a negative result from a positive input to either, as neither 8 nor 56 have the msb set.

**Comment by d3vv** [comment]
I agree with both of you looking carefully. So it is olny warning for pvs-studio against cppcheck..
But I have one question - does it true to overide "butwise not" with "xor" instruction for intuitive transparent code?

**Comment by vondele** [comment]
actually some warnings also result with upcoming gcc (8.0), so would need fixing. There is partial overlap: 
```
syzygy/tbprobe.cpp: In constructor ‘{anonymous}::WDLEntry::WDLEntry(const string&)’:
syzygy/tbprobe.cpp:415:37: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct {anonymous}::WDLEntry’ with no trivial copy-assignment [-Wclass-memaccess]
     memset(this, 0, sizeof(WDLEntry));
                                     ^
syzygy/tbprobe.cpp:171:8: note: ‘struct {anonymous}::WDLEntry’ declared here
 struct WDLEntry : public TBEntry {
        ^~~~~~~~
syzygy/tbprobe.cpp: In constructor ‘{anonymous}::DTZEntry::DTZEntry(const {anonymous}::WDLEntry&)’:
syzygy/tbprobe.cpp:456:37: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct {anonymous}::DTZEntry’ with no trivial copy-assignment [-Wclass-memaccess]
     memset(this, 0, sizeof(DTZEntry));
                                     ^
syzygy/tbprobe.cpp:180:8: note: ‘struct {anonymous}::DTZEntry’ declared here
 struct DTZEntry : public TBEntry {
        ^~~~~~~~
position.cpp: In member function ‘Position& Position::set(const string&, bool, StateInfo*, Thread*)’:
position.cpp:203:40: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘class Position’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
   std::memset(this, 0, sizeof(Position));
                                        ^
In file included from position.cpp:31:
position.h:72:7: note: ‘class Position’ declared here
 class Position {
       ^~~~~~~~
```

**Comment by d3vv** [comment]
**7 Jan 2018 compile current sources with Visual Studio 2017:**

1>------ Rebuild All started: Project: Stockfish, Configuration: Release x64 ------
1>benchmark.cpp
1>bitbase.cpp
1>bitboard.cpp
1>endgame.cpp
1>evaluate.cpp
1>main.cpp
1>material.cpp
1>misc.cpp
1>movegen.cpp
1>movepick.cpp
1>pawns.cpp
1>position.cpp
1>evaluate.cpp(442): warning C4244: 'initializing': conversion from 'Bitboard' to 'int', possible loss of data
1>evaluate.cpp(855): note: see reference to function template instantiation 'Score `anonymous-namespace'::Evaluation<`anonymous-namespace'::Trace::NO_TRACE>::evaluate_king<WHITE>(void)' being compiled
1>evaluate.cpp(855): note: see reference to function template instantiation 'Score `anonymous-namespace'::Evaluation<`anonymous-namespace'::Trace::NO_TRACE>::evaluate_king<WHITE>(void)' being compiled
1>evaluate.cpp(817): note: while compiling class template member function 'Value `anonymous-namespace'::Evaluation<`anonymous-namespace'::Trace::NO_TRACE>::value(void)'
1>evaluate.cpp(902): note: see reference to function template instantiation 'Value `anonymous-namespace'::Evaluation<`anonymous-namespace'::Trace::NO_TRACE>::value(void)' being compiled
1>evaluate.cpp(902): note: see reference to class template instantiation '`anonymous-namespace'::Evaluation<`anonymous-namespace'::Trace::NO_TRACE>' being compiled
1>psqt.cpp
1>search.cpp
1>tbprobe.cpp
1>thread.cpp
1>timeman.cpp
1>tt.cpp
1>uci.cpp
1>search.cpp(1429): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>syzygy\tbprobe.cpp(542): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
1>syzygy\tbprobe.cpp(553): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>syzygy\tbprobe.cpp(588): warning C4244: '=': conversion from 'uint64_t' to '`anonymous-namespace'::Sym', possible loss of data
1>syzygy\tbprobe.cpp(1019): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>ucioption.cpp
1>Generating code
1>All 3547 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>Stockfish.vcxproj -> C:\msys64\home\dew\Stockfish\src\..\bin\Release\x64\Stockfish.exe
c:\msys64\home\dew\stockfish\src\bitbase.cpp(120): warning C6385: Reading invalid data from 'PawnAttacks[WHITE]':  the readable size is '512' bytes, but 'psq' bytes may be read.
c:\msys64\home\dew\stockfish\src\bitbase.cpp(133): warning C6385: Reading invalid data from 'PawnAttacks[~(us)]':  the readable size is '512' bytes, but 'psq' bytes may be read.
c:\msys64\home\dew\stockfish\src\bitboard.cpp(252): warning C6262: Function uses '82060' bytes of stack:  exceeds /analyze:stacksize '16384'.  Consider moving some data to heap.
c:\msys64\home\dew\stockfish\src\misc.cpp(255): warning C6011: Dereferencing NULL pointer 'ptr'. 
c:\msys64\home\dew\stockfish\src\misc.cpp(236): warning C6387: 'k32' could be '0':  this does not adhere to the specification for the function 'GetProcAddress'. 
c:\msys64\home\dew\stockfish\src\misc.cpp(304): warning C6387: 'k32' could be '0':  this does not adhere to the specification for the function 'GetProcAddress'. 
c:\msys64\home\dew\stockfish\src\search.cpp(1421): warning C6262: Function uses '22564' bytes of stack:  exceeds /analyze:stacksize '16384'.  Consider moving some data to heap.
c:\msys64\home\dew\stockfish\src\search.cpp(554): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
c:\msys64\home\dew\stockfish\src\syzygy\tbprobe.cpp(1577): warning C6001: Using uninitialized memory 'st'.
1>Done building project "Stockfish.vcxproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by snicolet** [comment]
As I understand it, the consensus is that the warning are buggy in PVS Studio.
We can fix the GCC warning with gcc 8 when they appear.
Closing for now.
