### ISSUE TITLE
Makefile suggestion for gcc builds

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#1355]
Why Stockfish didn't use safe optimization flags like -pipe in general and -march=native for personal arch and fishtest builds?

**Comment by vondele** [comment]
-march=native was tested a year ago and was no improvement:
http://tests.stockfishchess.org/tests/view/581595b50ebc5910626b9959

-pipe could bring a very small speed advantage in building SF, but if anything, it is very very small, so not worth the additional option.

feel free to close the issue if you think this answers your question.

**Comment by Ipmanchess** [comment]
I don't know if i can ask here..
Is it possible to make a avx512 compile for Skylake-X cpu.

Ipman.

**Comment by vondele** [comment]
you can use -march=native if you do the compile on that machine... not sure if SF in its current form would benefit from avx512. AFAICT it is not the typical vectorizable code avx512 targets.

**Comment by Ipmanchess** [comment]
Thank you..
I use for my i7 5960x this: make -f MakeFile profile-build ARCH=x86-64-bmi2 COMP=mingw
How it looks with using -march=native
Like this? : make -f MakeFile profile-build ARCH=-march=native COMP=mingw

**Comment by Ipmanchess** [comment]
In Cfish i see native in Makefile ,but not in Stockfish Makefile..
# native = yes/no     --- -march=native    --- Optimize for local CPU
### native
ifeq ($(native),yes)
	CFLAGS += -march=native
endif

**Comment by vondele** [comment]
indeed you would have to experiment yourself as in (for linux):
CXXFLAGS="-march=native" make -j ARCH=x86-64-bmi2 build
