### ISSUE TITLE
Time trouble

### ISSUE THREAD

**Issue by stas730** [official-stockfish/Stockfish#1357]
It looks like Stockfish can lose in time trouble. It's better to make less time = less analysis, even the first possible move.
Proof: https://lichess.org/qkx4XvNu

**Comment by ianfab** [comment]
Lichess/fishnet does not use Stockfish's time management but fixed time and depth limits independent from the time control, so you can not blame Stockfish for such time losses.

**Comment by stas730** [comment]
Invalid.
