### ISSUE TITLE
Stockfish: call for contributor's full name :-)

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#1380]
I am not really raising an issue, but rather (ab)using Github's "at sign" @ feature to reach the contributors of the project in the last two years for whom we don't know the family name. So if you are one of the people in the following list and would accept to have your name in the list of contributors in the upcoming Stockfish 9 release notes, please post us a comment in this Github thread or on the fishcooking forum thread there: https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/_FW_RIowarw

EDIT: list updated with the most current infos

@basepr1me
@ElbertoOne
@erbsenzaehler
@fanon
@fbv-sf
@gamander
@GuardianRM
@loco-loco
@theo77186

absimaldata
Ajith Chandy Jose (ajithcj)
Alain Savard (Rocky640)
Alexander Kure
Ali AlZhrani (Cooffe)
Andrew Grant (AndyGrant)
Andrey Neporada (nepal)
Andy Duplain
Aram Tumanian (atumanian)
Arjun Temurnikar
Auguste Pop
Balint Pfliegel
Ben Koshy (BKSpurgeon)
Bill Henry (VoyagerOne)
braich
Brian Sheppard (SapphireBrand)
Bryan Cross (crossbr)
Bujun Guo (noobpwnftw)
Chris Cain (ceebo)
Dan Schmidt
Daniel Dugovic (ddugovic)
Dariusz Orzechowski
David Zar
Daylen Yang (daylen)
DiscanX
Eelco de Groot
ElbertoOne
erbsenzaehler
Ernesto Gatti
Fabian Beuke (madnight)
Fabian Fichter (ianfab)
fanon
Fauzi Akram Dabat (FauziAkram)
Felix Wittmann
gamander
gguliash
Gian-Carlo Pascutto (gcp)
Gontran Lemaire (gonlem)
Goodkov Vasiliy Aleksandrovich (goodkov)
Gregor Cramer
GuardianRM
Günther Demetz (pb00067, pb00068)
Guy Vreuls (gvreuls)
Henri Wiechers
Hiraoka Takuya (HiraokaTakuya)
homoSapiensSapiens
Hongzhi Cheng
Ivan Ivec (IIvec)
Jacques B. (Timshel)
Jan Ondruš (hxim)
Jarrod Torriero (DU-jdto)
Jean-Francois Romang (jromang)
Jerry Donald Watson (jerrydonaldwatson)
Jonathan Calovski (Mysseno)
Joost VandeVondele (vondele)
Jörg Oster (joergoster)
Joseph Ellis (jhellis3)
Joseph R. Prostko
jundery
Justin Blanchard
Kelly Wilson
Ken Takusagawa
kinderchocolate
Kiran Panditrao (Krgp)
Kojirion
Leonardo Ljubičić (GM)
Leonid Pechenik (lp--)
Linus Arver
loco-loco
Luca Brivio (lucabrivio)
Lucas Braesch (lucasart)
Lyudmil Antonov (lantonov)
Matthew Lai (matthewlai)
Matthew Sullivan
Mark Tenzer (31m059)
Michael Byrne (MichaelB7)
Michael Stembera (mstembera)
Michael Chaly (Vizvezdenec)
Michel Van den Bergh (vdbergh)
Miguel Lahoz (miguel-l)
Mikael Bäckman (mbootsector)
Mike Whiteley (protonspring)
Miroslav Fontán (Hexik)
Moez Jellouli (MJZ1977)
Mohammed Li (tthsqe12)
Nathan Rugg (nmrugg)
Nicklas Persson (NicklasPersson)
Niklas Fiekas (niklasf)
Ondrej Mosnáček (WOnder93)
Oskar Werkelin Ahlin
Pablo Vazquez
Pascal Romaret
Pasquale Pigazzini (ppigazzini)
Patrick Jansen (mibere)
pellanda
Ralph Stößer (Ralph Stoesser)
Raminder Singh
renouve
Reuven Peleg
Richard Lloyd
Rodrigo Exterckötter Tjäder
Ron Britvich (Britvich)
Ronald de Man (syzygy1)
Ryan Schmitt
Ryan Takker
Sergei Antonov (saproj)
sf-x
shane31
Steinar Gunderson (sesse)
Stefan Geschwentner (locutus2)
Stefano Cardanobile (Stefano80)
Stéphane Nicolet (snicolet)
Thanar2
thaspel
Tom Vijlbrief (tomtor)
Torsten Franz (torfranz)
Uri Blass (uriblass)
Vince Negri

**Comment by pb00068** [comment]
I guess that @ajithcj full name is "Ajith Chandy Jose".

**Comment by ajithcj** [comment]
@pb00068  Gunther Demetz, Thanks. that's right!

**Comment by gvreuls** [comment]
I think @mbootsector and Andrew Grant (AndyGrant) are the same person.

**Comment by AndyGrant** [comment]
That would not be the case, @gvreuls

**Comment by gvreuls** [comment]
I guess I must have confused the both of you in TCEC chat, sorry!

**Comment by pb00068** [comment]
All I know is that @mbootsector's first name is Mikael

**Comment by mibere** [comment]
@mcostalba Is the updated list part of the SF 9 release?

**Comment by Rocky640** [comment]
You inserted a few contributors "honoris causae", it might be interesting, but this is quite subjective, and it will be easy to miss some. The sf community is quite large.

**Comment by hxim** [comment]
Hello my full name is Jan Ondruš

**Comment by DU-jdto** [comment]
My name is Jarrod Torriero.

**Comment by FauziAkram** [comment]
Will this list be introduced in stockfish files?

**Comment by Vizvezdenec** [comment]
I think that you at least should add @noobpwnftw there.
He is not only donating enormous amount of computing power that stimulates devs to seek for new ideas more rapidly, but he spotted numa bug which was corrupting sf play on windows numa machines by 10 elo, he solely debugged this issue https://github.com/official-stockfish/Stockfish/issues/1433
and debugged this old and annoying fishtest but https://github.com/glinscott/fishtest/issues/141 simultaneously spotting it origin - https://github.com/glinscott/fishtest/issues/145 .
I honestly think that his direct bugspotting and debugging contribution is important, not even talking about all that machines that he donates to fishtest.

**Comment by jhellis3** [comment]
Not a big deal but my name is misspelled:  Joseph Hellis should be Joseph Ellis.

**Comment by mbootsector** [comment]
Hi
My name is Mikael Bäckman.

**Comment by bunkbail** [comment]
Ron Britvich (Britvich)
Jean-Francois Romang (jromang)

**Comment by Vizvezdenec** [comment]
Since now I am the real contributor I guess I should be listed there ;)
My name is Michael Chaly

**Comment by Rocky640** [comment]
Steinar H. Gunderson (sesse)

**Comment by absimaldata** [comment]
Aditya (absimaldata)

**Comment by Vizvezdenec** [comment]
@SFisGOD

**Comment by Rocky640** [comment]
Jared Kish (SFisGOD)

**Comment by noobpwnftw** [comment]
Typo: Bujun Guo -> Bojun Guo :)

**Comment by snicolet** [comment]
@noobpwnftw Sorry for the typo, I will correct it as soon as possible

**Comment by Vizvezdenec** [comment]
@zenczykowski is now a contributor :)

**Comment by Vizvezdenec** [comment]
@vondele
I think this should be permanently opened :)
Also I think we should have @linrock listed in contributors list with his massive work on improving fishtest.

**Comment by vondele** [comment]
@Vizvezdenec we should add people to the authors at the first contribution... and try not to forget. 
@linrock is doing great work on fishtest, he was added to the fishtest author list early on.
