### ISSUE TITLE
Update Stockfish iPhone App

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#1383]
It’s still on the Stockfish version 2.13 , anyway we can update the engine?  The GUI is great , it’s just the engine that is getting a little long in the tooth. If there is a fee from Apple that is a hindrance  (for a developer account  - $99?), I would be willling to fund that expense - up to $100. If there are any takers- the source is available on Stockfish website I believe.

**Comment by snicolet** [comment]
I am using the Stockfish iPhone app too, and it is very nice indeed :-)

I forward your proposition to Tord Romstad (@romstad), as he is (among other things) the author of the App: maybe he can recompile it with Stockfish 9?

**Comment by student-t** [comment]
I've volunteered my time. https://github.com/student-t/Stockfish_iOS. It works on my phone.

**Comment by snicolet** [comment]
@student-t 
Thanks a lot, that was quick! 
I have an iPhone 4, eager to test it if possible :-)

**Comment by student-t** [comment]
The updated deployment target is 10.0 which means your iPhone 4 won’t work.
I will downgrade it and then upload to Apple so you can test it.

**Comment by MichaelB7** [comment]
This is awesome - but now how do I get it or install it?

**Comment by snicolet** [comment]
@student-t Any update on this subject? How is the rebuilding doing? :-)

**Comment by student-t** [comment]
@snicolet I thought I've sent you an email for the instructions? @MichaelB7 has received it. I sent to stephanenicoletsuriphone@gmail.com.

**Comment by MichaelB7** [comment]
I have been “testing” every day 😊,  using all the functions - there was one time where I could not move a piece as expected , tried to take a snapshot and realized my phone was misbehaving, rebooted and all Iowa’s well.  Seemed to be more of an iPhone issue than an app issue.

**Comment by MichaelB7** [comment]
...was well ....

**Comment by snicolet** [comment]
This email address I had never made public, but now Google has it indexed, OK :-)

Anyway I have now checked your invitation, and I can't test because testing requires IOS 8.
Maybe the final version will be IOS 7 compatible, then I will use it!

**Comment by MichaelB7** [comment]
So far Ted it's been working perfectly!. You will need to update the "about" screen item ;-)

**Comment by SuperGeroy** [comment]
The app compiles and works on my XCode 9.2 simulator for an iPhone 8. Thanks @student-t !
Do you have any links or resources on how to use the engine in a Swift project?

**Comment by student-t** [comment]
@SuperGeroy Swift is not recommended as it has poor support with C++.

**Comment by snicolet** [comment]
Not much activity in this thread, closing
