### ISSUE TITLE
[fixed] incorrect MultiPV implementation

### ISSUE THREAD

**Issue by syzygy1** [official-stockfish/Stockfish#1392]
It seems to me the new MultiPV logic is not correct, as it does not attempt to find the N best moves.

By doing less work obviously this new implementation does better at tests, but that is not the point of MultiPV. MultiPV should show, at each iteration, the PVs for the best N moves.

From the starting position with MultiPV = 2:
info depth 1 seldepth 1 multipv 1 score cp 112 nodes 20 nps 20000 tbhits 0 time 1 pv e2e4
info depth 1 seldepth 1 multipv 2 score cp 2 nodes 20 nps 20000 tbhits 0 time 1 pv a2a3
info depth 2 seldepth 1 multipv 1 score cp 112 nodes 48 nps 48000 tbhits 0 time 1 pv d2d4

a2a3?!

info depth 31 seldepth 40 multipv 1 score cp 49 nodes 328071854 nps 1883889 hashfull 999 tbhits 0 time 174146 pv d2d4 d7d5 c2c4 e7e6 g1f3 d5c4 e2e3 g8f6 f1c4 c7c5 e1g1 c5d4 e3d4 f8e7 b1c3 e8g8 f1e1 b8c6 a2a3 h7h6 c1f4 a7a6 a1c1 d8b6 c3a4 b6a7 f4e3 f6d5 a4c3 d5e3 f2e3 b7b5 c4d3 c8b7
info depth 31 seldepth 41 multipv 2 score cp 37 nodes 328071854 nps 1883889 hashfull 999 tbhits 0 time 174146 pv g1f3 d7d5 d2d4 c8f5 c2c4 e7e6 b1c3 b8c6 c1g5 f8e7 g5e7 c6e7 e2e3 g8f6 f1e2 c7c6 e1g1 e8g8 h2h3 d8c7 a1c1 a8d8 c4d5 e6d5 c3a4 f5e4 f3d2 e4g6 a4c5 b7b6 c5a6 c7b7 d1b3 h7h6

g1f3 the 2nd best move? Really?

**Comment by syzygy1** [comment]
OK, it seems g1f3 is probably pretty close to e2e4. Still, the logic seems incorrect.

**Comment by syzygy1** [comment]
MultiPV=10 from starting position:
info depth 1 seldepth 1 multipv 1 score cp 112 nodes 20 nps 20000 tbhits 0 time 1 pv e2e4
info depth 1 seldepth 1 multipv 2 score cp 100 nodes 20 nps 20000 tbhits 0 time 1 pv e2e3
info depth 1 seldepth 1 multipv 3 score cp 92 nodes 20 nps 20000 tbhits 0 time 1 pv d2d3
info depth 1 seldepth 1 multipv 4 score cp 42 nodes 20 nps 20000 tbhits 0 time 1 pv b2b3
info depth 1 seldepth 1 multipv 5 score cp 42 nodes 20 nps 20000 tbhits 0 time 1 pv g2g3
info depth 1 seldepth 1 multipv 6 score cp 29 nodes 20 nps 20000 tbhits 0 time 1 pv c2c3
info depth 1 seldepth 1 multipv 7 score cp 14 nodes 20 nps 20000 tbhits 0 time 1 pv a2a4
info depth 1 seldepth 1 multipv 8 score cp 11 nodes 20 nps 20000 tbhits 0 time 1 pv h2h3
info depth 1 seldepth 1 multipv 9 score cp 3 nodes 20 nps 20000 tbhits 0 time 1 pv f2f3
info depth 1 seldepth 1 multipv 10 score cp 2 nodes 20 nps 20000 tbhits 0 time 1 pv a2a3

This is not good.

info depth 6 seldepth 5 multipv 1 score cp 60 nodes 6413 nps 1603250 tbhits 0 time 4 pv e2e3 d7d5 d2d4 e7e6 g1f3
info depth 6 seldepth 3 multipv 2 score cp 39 nodes 6413 nps 1603250 tbhits 0 time 4 pv b2b3 e7e6 e2e4
info depth 6 seldepth 6 multipv 3 score cp 34 nodes 6413 nps 1603250 tbhits 0 time 4 pv d2d4 g8f6 c1f4 d7d5 e2e3 e7e6
info depth 6 seldepth 5 multipv 4 score cp 30 nodes 6413 nps 1603250 tbhits 0 time 4 pv g2g3 d7d5 d2d4 g8f6 g1f3
info depth 6 seldepth 6 multipv 5 score cp 25 nodes 6413 nps 1603250 tbhits 0 time 4 pv g1f3 d7d5 d2d4 g8f6 b1c3 e7e6
info depth 6 seldepth 6 multipv 6 score cp 23 nodes 6413 nps 1603250 tbhits 0 time 4 pv b1c3 d7d5 e2e3 d5d4 c3e4 e7e6
info depth 6 seldepth 6 multipv 7 score cp 15 nodes 6413 nps 1603250 tbhits 0 time 4 pv d2d3 d7d5
info depth 6 seldepth 6 multipv 8 score cp 12 nodes 6413 nps 1603250 tbhits 0 time 4 pv c2c3 e7e6 d2d4 d7d5 g1f3 g8f6
info depth 6 seldepth 6 multipv 9 score cp 11 nodes 6413 nps 1603250 tbhits 0 time 4 pv e2e4 d7d5 e4e5 e7e6 g1f3 f8c5
info depth 6 seldepth 6 multipv 10 score cp -6 nodes 6413 nps 1603250 tbhits 0 time 4 pv c2c4 d7d5 d2d4 e7e6 c4c5 g8f6

e2e3 is best?

nfo depth 10 seldepth 12 multipv 1 score cp 59 nodes 129687 nps 2126016 tbhits 0 time 61 pv e2e4
info depth 10 seldepth 11 multipv 2 score cp 41 nodes 129687 nps 2126016 tbhits 0 time 61 pv c2c4 d7d5 d2d4 e7e6 e2e3 b8c6 b1c3 f8b4 a2a3 b4c3 b2c3
info depth 10 seldepth 14 multipv 3 score cp 37 nodes 129687 nps 2126016 tbhits 0 time 61 pv c2c3 g8f6 d2d4 d7d5 c1f4 b8c6 b1d2 f6h5 e2e3 h5f4 e3f4
info depth 10 seldepth 10 multipv 4 score cp 29 nodes 129687 nps 2126016 tbhits 0 time 61 pv d2d4 g8f6 g1f3 d7d5 f3e5 c8d7 e2e3 e7e6 c1d2 b8c6
info depth 10 seldepth 12 multipv 5 score cp 28 nodes 129687 nps 2126016 tbhits 0 time 61 pv e2e3 g8f6 g1f3 d7d5 d2d4 e7e6 f3e5 c8d7 b1c3 b8c6
info depth 10 seldepth 10 multipv 6 score cp 28 nodes 129687 nps 2126016 tbhits 0 time 61 pv g1f3 d7d5 d2d4 e7e6 e2e3 c8d7 b1c3 g8f6 c1d2 b8c6
info depth 10 seldepth 11 multipv 7 score cp 18 nodes 129687 nps 2126016 tbhits 0 time 61 pv b1c3 d7d5 d2d4 e7e6 g1f3 g8f6 e2e3 c8d7 c1d2 f6e4 c3e4
info depth 10 seldepth 12 multipv 8 score cp 9 nodes 129687 nps 2126016 tbhits 0 time 61 pv a2a3 d7d5 d2d4 h7h6 b1c3 g8f6 c1f4 b8c6 e2e3 c8g4
info depth 10 seldepth 14 multipv 9 score cp -1 nodes 129687 nps 2126016 tbhits 0 time 61 pv b2b3 e7e5
info depth 10 seldepth 17 multipv 10 score cp -5 nodes 129687 nps 2126016 tbhits 0 time 61 pv d2d3 d7d5 d3d4 c7c5 e2e3 e7e6 b1c3 b8c6 d4c5 f8c5 g1f3

Where is the PV of e2e4?
c2c3 is better than d2d4?

I think we should revert this change.

**Comment by joergoster** [comment]
@syzygy1 Thanks for reporting. There is a bug that crept in from my first version to the one being merged!
I will provide a bugfix tomorrow.

Here the output with that fix included:
...
info depth 6 seldepth 6 multipv 1 score cp 34 nodes 6588 nps 941142 tbhits 0 time 7 pv b1c3 e7e6 e2e4 f8b4 d2d4 d7d5
info depth 6 seldepth 6 multipv 2 score cp 31 nodes 6588 nps 941142 tbhits 0 time 7 pv d2d4 g8f6 e2e3 d7d5 b1c3 e7e6
info depth 6 seldepth 6 multipv 3 score cp 31 nodes 6588 nps 941142 tbhits 0 time 7 pv e2e3 d7d5 d2d4 g8f6 b1c3 e7e6
info depth 6 seldepth 6 multipv 4 score cp 18 nodes 6588 nps 941142 tbhits 0 time 7 pv g1f3 d7d5 d2d4 g8f6 e2e3 c8g4
info depth 6 seldepth 6 multipv 5 score cp 12 nodes 6588 nps 941142 tbhits 0 time 7 pv c2c3 d7d5 d2d4 g8f6 g1f3 e7e6
info depth 6 seldepth 6 multipv 6 score cp 2 nodes 6588 nps 941142 tbhits 0 time 7 pv h2h3 g8f6 g1f3 d7d5 d2d4 e7e6
info depth 6 seldepth 6 multipv 7 score cp 2 nodes 6588 nps 941142 tbhits 0 time 7 pv d2d3 g8f6 c1g5 b8c6 g1f3 d7d5
info depth 6 seldepth 6 multipv 8 score cp -5 nodes 6588 nps 941142 tbhits 0 time 7 pv g2g3 b8c6 d2d4 d7d5 g1f3 g8f6
info depth 6 seldepth 6 multipv 9 score cp -14 nodes 6588 nps 941142 tbhits 0 time 7 pv h2h4 g8f6 d2d4 d7d5 g1f3 c8g4
info depth 6 seldepth 6 multipv 10 score cp -30 upperbound nodes 6588 nps 941142 tbhits 0 time 7 pv e2e4 d7d5 e4d5 d8d5 d2d4 g8f6

...

info depth 10 seldepth 13 multipv 1 score cp 82 nodes 137141 nps 1371410 tbhits 0 time 100 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5e6 g1e2 c7c6 d2d4 g8f6 c1f4 c8d7
info depth 10 seldepth 13 multipv 2 score cp 75 nodes 137141 nps 1371410 tbhits 0 time 100 pv b1c3 d7d5 d2d4 e7e6 e2e4 d5e4 c3e4 b8c6 g1f3 g8f6 e4c3
info depth 10 seldepth 12 multipv 3 score cp 28 nodes 137141 nps 1371410 tbhits 0 time 100 pv d2d4 g8f6 b1c3 d7d5 c1f4 c7c6 e2e3 b8d7 d1b1 e7e6 g1f3
info depth 10 seldepth 11 multipv 4 score cp 26 nodes 137141 nps 1371410 tbhits 0 time 100 pv c2c4 e7e6 g1f3 d7d5 c4d5 e6d5 d2d4 b8c6 e2e3 g8f6 b1c3
info depth 10 seldepth 13 multipv 5 score cp 25 nodes 137141 nps 1371410 tbhits 0 time 100 pv g1f3 g8f6 d2d4 d7d5 c1f4 e7e6 c2c3 f8e7 f3e5 e8g8 e2e3
info depth 10 seldepth 12 multipv 6 score cp 25 nodes 137141 nps 1371410 tbhits 0 time 100 pv c2c3 d7d5 d2d4 e7e6 c1f4 g8f6 g1f3 f8e7 f3e5 e8g8 e2e3
info depth 10 seldepth 11 multipv 7 score cp 16 nodes 137141 nps 1371410 tbhits 0 time 100 pv e2e3 d7d5 d2d4 g8f6 b1c3 e7e6 c1d2 f8e7 g1f3 e8g8 h2h3
info depth 10 seldepth 13 multipv 8 score cp 12 nodes 137141 nps 1371410 tbhits 0 time 100 pv h2h3 g8f6 d2d4 e7e6 g1f3 b8c6 c1f4 d7d5 e2e3 f8e7 b1c3 e8g8
info depth 10 seldepth 15 multipv 9 score cp -7 nodes 137141 nps 1371410 tbhits 0 time 100 pv d2d3 d7d5 g1f3 b8c6 c1f4 g8f6 d3d4 e7e6 e2e3 f8b4 c2c3 b4e7
info depth 10 seldepth 15 multipv 10 score cp -15 upperbound nodes 137141 nps 1371410 tbhits 0 time 100 pv h2h4 e7e5 e2e4 b8c6 g1f3 g8f6 d2d4 e5d4 f3d4 d7d5 d4c6
bestmove e2e4 ponder d7d5

**Comment by syzygy1** [comment]
Are you really sure the fixed version does what it is supposed to do?
In theory, the best N moves from the previous iteration may have to be replaced by N different moves in the next iteration. What you seem to be wanting to do is to search the first N-1 moves of the previous iteration fully and then to just search all remaining moves to find the best Nth move. But that is not enough.

Of course I haven't yet seen your fixed version.

**Comment by ChessMan3** [comment]
It's interesting that it passed the sprt. Maybe also need to check the fixed version? 
Too many patches were added without tests last year.

**Comment by syzygy1** [comment]
That e2e4 comes at spot 10 with a score of -30 at iteration 6 looks suspicious.

**Comment by joergoster** [comment]
@syzygy1 Yes, your description is accurate. The fix is we may not bring another move to the front while we are still searching the n-1 best moves.
What is enough and what is not enough, looks more like a design decision to me. I clearly prefer the 'old' way.

Alas, this whole discussion is futile since Stéphane already reverted.
I'm away now for the Super Bowl. :-)

**Comment by syzygy1** [comment]
The discussion is not futile since you can still submit your fixed version.

I personally don't think there can be much discussion on what MultiPV has to do at a minimum, which is to show the best N moves and their PVs. I am pretty sure any "old behaviour" achieved that minimum!

But there may still be a way to improve on the current MultiPV implementation. For example, if the Nth move you find is sorted to the kth position with k < N, you could continue to look for a move that is better than the move currently in Nth position. If you can't find one, then you're done.

**Comment by IIvec** [comment]
@joergoster : please, submit a fixed version.

**Comment by Hanamuke** [comment]
Pushed to the extreme, it would be easy to have a very strong multipv by just doing a single PV search and then returning random PVs for the other moves. Maybe there is a need for testing the quality of the other moves than the best one. The SPRT isn't even looking at the second best move so there definitly is a testing problem for multi pv patches. I don't how good of an idea it is, but one could do a SPRT test, but with a lower "Skill" setting, so that pick_best is used.

**Comment by syzygy1** [comment]
As long as we agree on what a multipv search "must" do, an SPRT can be useful to check that a new way of doing it is faster in the average case. (If it's faster, it will search deeper and therefore return better moves and play better.)

**Comment by snicolet** [comment]
I take the blame for not having checked the quality of the moves returned by the new MultiPV implementation before committing, Ronald's example was simple and illuminating in retrospect.

As a first approximation, the definition of MultiPV for me is to return the minimax score and the PV of the N best moves in the position, as if the alpha-beta algorithm had not been invented.

Thinking about a way to verify the quality of the set of moves, we could also patch the master so that it  systematically plays the second best move in multiPV=2 (in case the score is within a given distance from the best score, maybe), then organize a match between this patched master and the second best moves of the proposed implementation? And do also matches for the 3rd best moves, etc...

**Comment by syzygy1** [comment]
I think it is relatively simple. Multipv should return the N best moves with PVs at each iteration. The faster it does this, the better. Correctness can be checked by checking the logic of the code (and trying some positions). Speed can be checked, for example, by playing games where the engine plays the best moves. Quality of the other moves is not really a concern as long as they are the best moves that are returned by the same search<Pv>.

Since MultiPV is not the core goal of Stockfish, code simplicity should probably count heavily as well, even at the cost of some efficiency.

**Comment by Stefano80** [comment]
Hi @snicolet, I was thinking of the same idea for testing, but then I thought that this could become quite noisy, as there are many positions in which only one move is viable.

**Comment by snicolet** [comment]
I have changed the title of the issue to [fixed]... so that newcomers visiting the site don't believe the multiPV of SF9 is broken. But of course I leave the thread open for the moment to discuss the possible speed-up which may appear from Stefano's idea.

**Comment by joergoster** [comment]
@snicolet The bigger blame is on me, of course, for opening a PR for a buggy patch! Sorry for that.

@syzygy1 After re-reading this discussion http://www.talkchess.com/forum/viewtopic.php?t=60971 it looks like things aren't as trivial.
How to start a multiPV search? Does it make sense to start with a full PV search for every root move for the 1st iteration? Or even the 2nd, 3rd and 4th? Is this eventually even helpful for the current multiPV search?
At least for my patch, it seems mandatory to do it at least at the 1st iteration.

Another question is what aspiration window to use when the last of the PV lines has been reached? A narrower or a wider window? And why is the last PV line with my patch reported as 'upperbound' quite often. Another bug?

**Comment by syzygy1** [comment]
@joergoster
We could do a Pv search on each of the N best moves from the previous iteration with aspiration windows based on the scores from the last iteration. When we have found the N moves and PVs, we do a NonPv search of the remaining moves to verify that they are all worse than the Nth best move. If that search fails high, we will need to do an aspiration search to find the move that beats the Nth move (and then repeat the verification of the remaining moves with the new Nth best score if necessary).

I do not know if this is more efficient than what we do now!! But it will give all the information one could hope for (so probably it's less efficient :))

**Comment by joergoster** [comment]
@syzygy1 That's basically the idea of this patch, yet a bit simpler version. I do a full PV search for the N-1 best moves from the last iteration by simply skipping all other root moves in the moves loop. And only when the Nth best move is being searched I switch back to the standard PVS search.
```
          // In MultiPV mode we not only skip PV moves which have already been searched,
          // but also any other move until we have reached the last PV line.
          if (   thisThread->PVIdx + 1 < thisThread->multiPV
              && move != ttMove)
              continue;
```
The first condition can only be true if multiPV > 1, and the second condition ensures we skip all other moves but the PV move. (This works because ttMove is set to the PV move in line 558.)

Additionally, for this to work it's important to prevent a possible resorting in the aspiration loop until we have reached the Nth best move. (That was the missing part of the first version.)
```
              // Bring the best move to the front. It is critical that sorting
              // is done with a stable algorithm because all the values but the
              // first and eventually the new best one are set to -VALUE_INFINITE
              // and we want to keep the same order for all the moves except the
              // new PV that goes to the front. Note that in case of MultiPV
              // search the already searched PV lines are preserved.
              if (PVIdx + 1 == multiPV)
                  std::stable_sort(rootMoves.begin() + PVIdx, rootMoves.end());
```

What you describe seems to be what e.g. Texel is doing. So maybe there is room for improvement. But it already seems to be more efficient than what we're doing now.

@snicolet I hope this helps to better understand this patch.

**Comment by syzygy1** [comment]
So the problem I see with that approach is that (if you stop after the Nth search) you will often not get the best N moves.

**Comment by joergoster** [comment]
MultiPV = 3, go depth 18
position fen 4r1rk/p3qpp1/1pnp1n1p/5P2/P1PPP3/4Q2P/2BB2R1/6RK w - - 0 40

**master**
info depth 18 seldepth 33 multipv 1 score cp 171 nodes 5945819 nps 1410967 hashfull 995 tbhits 0 time 4214 pv e3f4 a7a5 c2b1 c6b4 g1e1 f6d7 d2c3 e8c8 f4f1 e7h4 e1e3 g8e8 g2g4 h4e7 e3g3 d7f6 g4g7 f6e4 b1e4 e7e4 h1g1 e8g8
info depth 18 seldepth 27 multipv 2 score cp 149 nodes 5945819 nps 1410967 hashfull 995 tbhits 0 time 4214 pv g1e1 f6d7 d2c3 e7h4 g2g4 h4d8 g4g1 d8h4 e1f1 h4e7 e3f2 a7a5 f1e1 e7d8 g1g2 c6b4 c2b1 d8c7
info depth 18 seldepth 32 multipv 3 score cp 143 nodes 5945819 nps 1410967 hashfull 995 tbhits 0 time 4214 pv g2e2 a7a5 c2b1 f6d7 d2c3 e7h4 e2g2 h4f6 e3f2 f6d8 g1e1 d8c7 f2g3 c6b4 e4e5 d6e5 f5f6 g7g5 d4e5 c7c4
bestmove e3f4 ponder a7a5

**patch**
info depth 18 seldepth 32 multipv 1 score cp 155 nodes 4386499 nps 1414543 hashfull 980 tbhits 0 time 3101 pv e3f4 c6d4 d2c3 f6h5 f4c1 d4f5 e4f5 e7e3 c1e3 e8e3 c3b2 e3h3 g2h2 h3h2 h1h2 g8e8 b2d4 e8e2 g1g2 e2g2 h2g2 h5f6 g2f3 h8g8 d4f6 g7f6 c2e4 h6h5 f3f4
info depth 18 seldepth 28 multipv 2 score cp 148 nodes 4386499 nps 1414543 hashfull 980 tbhits 0 time 3101 pv g1e1 e7c7 e1g1 c7e7 e3f4 c6d4 d2c3 f6h5 f4c1 d4f5 e4f5 e7e3 c1e3 e8e3 c3b2 e3h3 g2h2 h3h2 h1h2 g8e8 b2d4 f7f6 h2h3 e8e2 g1c1 e2d2 d4g1
info depth 18 seldepth 28 multipv 3 score cp 148 nodes 4386499 nps 1414543 hashfull 980 tbhits 0 time 3101 pv g2e2 c6a5 c2d3 d6d5 c4d5 a5b3 e3f4 b3d2 f4d2 e7a3 e4e5 f6d5 f5f6 g7g5 e5e6 d5c3 e6f7 c3e2 f7e8q g8e8 f6f7
bestmove e3f4 ponder c6d4

**Comment by joergoster** [comment]
startpos, MultiPV = 10

info depth 5 seldepth 5 multipv 1 score cp 63 nodes 4438 nps 887600 tbhits 0 time 5 pv b1c3 g8f6 d2d4 d7d5 g1f3
info depth 5 seldepth 5 multipv 2 score cp 60 nodes 4438 nps 887600 tbhits 0 time 5 pv d2d4 e7e6 g1f3 d7d5 e2e3
info depth 5 seldepth 5 multipv 3 score cp 60 nodes 4438 nps 887600 tbhits 0 time 5 pv e2e3 e7e6 d2d4 d7d5 g1f3
info depth 5 seldepth 5 multipv 4 score cp 60 nodes 4438 nps 887600 tbhits 0 time 5 pv g1f3 d7d5 d2d4 e7e6 e2e3
info depth 5 seldepth 5 multipv 5 score cp 45 nodes 4438 nps 887600 tbhits 0 time 5 pv d2d3 e7e6 g1f3 d7d5 c1g5
info depth 5 seldepth 5 multipv 6 score cp 43 nodes 4438 nps 887600 tbhits 0 time 5 pv c2c3 g8f6 d2d4 d7d5 g1f3
info depth 5 seldepth 5 multipv 7 score cp 25 nodes 4438 nps 887600 tbhits 0 time 5 pv h2h4 d7d5 d2d4 g8f6 g1f3
info depth 5 seldepth 5 multipv 8 score cp 24 nodes 4438 nps 887600 tbhits 0 time 5 pv c2c4 d7d5 d2d4 d5c4 c1g5
info depth 5 seldepth 5 multipv 9 score cp 23 nodes 4438 nps 887600 tbhits 0 time 5 pv b2b3 e7e6 d2d4 d7d5 g1f3
info depth 5 seldepth 5 multipv 10 score cp 19 nodes 4438 nps 887600 tbhits 0 time 5 pv a2a3 g8f6 g1f3 d7d5 d2d4

Oh wait, b1c3 best move? And where the heck is e2e4? ;-)
Me thinks there is a lot of randomness involved in a multiPV search ...

**Comment by syzygy1** [comment]
Then why not replace MultiPV with a random generator...

**Comment by joergoster** [comment]
@syzygy1 You like to comment on the shown MultiPV=10 search of the master?

**Comment by syzygy1** [comment]
No, I am familiar with the current MultiPV implementation and I know it is correct.

**Comment by IIvec** [comment]
I want to comment. This is depth 5. Please check this with at least depth 20. Thank you!

**Comment by joergoster** [comment]
@IIvec Yes, I know. But this was to demonstrate that also the current implementation cannot do what Ronald seems to be expecting from a MultiPV search. It simply takes some iterations to find the n-best moves.
Maybe 'randomness' was a bad choice of word in that regard.

**Comment by syzygy1** [comment]
MultiPV does what I expect it to do. At low iterations the results will not always be great. If you mean that some of the examples I gave earlier (also at lower depths) were not necessarily convincing in all respects (because of low depth), then I will admit that.

**Comment by Stefano80** [comment]
I was thinking, maybe the idea of testing multipv can indeed be tried out by using skill matches.

**Comment by Hanamuke** [comment]
Yeah that's what i had suggested too, it would make sense
