### ISSUE TITLE
Recommended contempt value against H6

### ISSUE THREAD

**Issue by Nordlandia** [official-stockfish/Stockfish#1399]
I guess default contempt value of +20 is a tad optimistic against near equal opponent.

I usually set contempt at zero for Houdini.  Not sure for SF.

**Comment by snicolet** [comment]
What would be nice is to organize two 10000 matches at VLTC against Houdini, and compare the results...

**Comment by Nordlandia** [comment]
10,000 games at VLT is very time consuming arrangement.. I's safe to conclude it's not good idea to underestimate H6 with default vallue.  Perhaps 5-10 is more appropriate value.

**Comment by IIvec** [comment]
I can run 2000 VLTC games against Houdini. We need 9 more persons...

**Comment by rohitrajiit** [comment]
In Stefan pohl test at 180+1 tc Contempt 15 was no regression against Houdini.
Contempt 20 was also non regression against master at similar tc.
So 20 should be safe in blitz.

**Comment by Nordlandia** [comment]
Maybe C=13 is okey starting value. In between value between 10 and 15.

**Comment by Vizvezdenec** [comment]
idk what is the point there, tbf.
There was a poll on fishcooking where the most votes were contempt=20 in premium stage of TCEC and contempt=7 for superfinal (if SF gets there).
So... ?

**Comment by Nordlandia** [comment]
7 + 20 / 2 = ~C=14 ✅

**Comment by snicolet** [comment]
Thanks Ivan to propose the 1000 games at VLTC time control against Houdini :-)
This discussion is interesting per se, but not really a technical issue on the code: it would be better placed in the fishcooking forum in my humble opinion, so I am closing the thread here for now.
