### ISSUE TITLE
Makefile option m

### ISSUE THREAD

**Issue by erbsenzaehler** [official-stockfish/Stockfish#1409]
Sorry, for the premature opening of this issue.

Since we are discussing Makefile option once again lately, I want to bring up the use of the option -mdynamic-no-pic on MacOS to attention. Right now I don't have access to a mac.

Maybe we could simplify the use of this option. See:

https://github.com/erbsenzaehler/Stockfish/commit/d9c7298ee542c7676f9f1a4c3e272754d43d59ec 

I do not know if this solution contains some pitfalls.

**Comment by MichaelB7** [comment]
None for the Mac.
