### ISSUE TITLE
How could we build Stockfish with Intel C++ compiler 11.1 pro

### ISSUE THREAD

**Issue by BudiKusasi** [official-stockfish/Stockfish#1444]
Is there a way to produce an windows executable of Stockfish engine from Intel c compiler version 11.1 professional. What variables should be set.. thanks in advance.

**Comment by Hanamuke** [comment]
make profile-build ARCH=x86-64-bmi2 COMP=icc COMPCXX=*your icc executable name*

should work according to the Makefile help (change ARCH parameter to x86-64-modern or x86-64 for older hardware.)

**Comment by snicolet** [comment]
Can anybody confirm that this works?

**Comment by MichaelB7** [comment]
current version is free for those on Linux and Github:
https://software.intel.com/en-us/parallel-studio-xe/choose-download#open-source-contributors

11.1 version is about 7 years old...

**Comment by snicolet** [comment]
Two workaround have been given, so I consider the issue closed.
