### ISSUE TITLE
Stockfish suggests king moves to same square it's on

### ISSUE THREAD

**Issue by timmyrs** [official-stockfish/Stockfish#1448]
In the position [`r2k3r/ppp2ppp/2p1bn2/8/4PB2/2N5/PPP2bPP/R1K2B1R w - - 0 10`](https://lichess.org/editor/r2k3r/ppp2ppp/2p1bn2/8/4PB2/2N5/PPP2bPP/R1K2B1R_w_-_-_0_10) Stockfish 9 suggested to play `c1c1` as white:

> bestmove c1c1 ponder f6d7

I use Windows 8.1 and Stockfish 9. Stockfish has been given a move time of 100 ms.

Does that mean it wants to resign? I could not find this in the UCI documentation.

I have had similar cases as white and black in different positions too.

**Comment by Rocky640** [comment]
Please provide the link where you downloaded your SF9, for windows or mac, x64 or x32, the exact sf exe name, and exact steps to reproduce the problem

**Comment by timmyrs** [comment]
Oh I just realised it might try to castle because I forgot to tell it that castling is no longer available.

**Comment by Rocky640** [comment]
The fen that you provided shows -
so it knows it cannot  castle. That does not explains the move c1c1

**Comment by timmyrs** [comment]
The FEN I provided was not the one the engine got. There was a different function in my code for that. :confused:
