### ISSUE TITLE
make.bat

### ISSUE THREAD

**Issue by maelic13** [official-stockfish/Stockfish#1455]
Inspired by make.bat from asmFish release, I rewrote it for Stockfish compiling. [Link here](https://drive.google.com/file/d/1C_5BEbkonlWYNq7eZcPU9gOvYoWOPRMN/view?usp=sharing).

It only works in case you have MinGW set up according to [support page](http://support.stockfishchess.org/kb/advanced-topics/compiling-stockfish-on-windows) and only for Windows.
It allows you to skip using command line - once you set up the compiler, you only download new SF source and put make.bat into the folder. Upon open, it asks you which exe you would like to compile and then do it saving it in the same directory into new folder Windows.

I am unsure if this is too helpful as you need to set up the compiler anyway and it is not universal since it works only for Windows but it saves me some annoying clicking and writing so I thought you could like it too. Feel free to give some advice how to make it more universal or without the need to set up MinGW.

**Comment by mcostalba** [comment]
@maelic13 care to explain what you mean by "annoying clicking and writing"?

Thanks.

P.S: In bash you have arrow up/down to traverse command history...

P.P.S This seems to me a largely redundant and broken-by-design attempt.

**Comment by maelic13** [comment]
@mcostalba - well, every time I wanted to compile myself, I would open the command line and write the commands to compile there. Maybe there indeed is an easier way to do so but I wanted to avoid having to do that by creating an automated way - now I double click make.bat and push 5 to compile for bmi2. The rest is done automatically and it gives me my compile nice and ready.
I am an beginning programmer so I probably don't see the bigger picture here - I just wanted to make my life a bit easier and thought others could appreciate it as well if it was included in Sf source to begin with. If I was mistaken, I am deeply sorry. You can delete the thread :)

**Comment by snicolet** [comment]
Closing for now
