### ISSUE TITLE
49. ...Rf8??

### ISSUE THREAD

**Issue by afontenot** [official-stockfish/Stockfish#1456]
Apologies in advance if this has been reported / discussed elsewhere. I've been looking at the [AlphaZero paper](https://arxiv.org/pdf/1712.01815.pdf) and noticed what seems to be some strange, possibly buggy behavior. 

In the third example game between AlphaZero and Stockfish 8 reported in the paper, Stockfish makes the move Rf8 as black on move 49. On my old, underpowered laptop Stockfish 8.2 quickly detects this as a losing move, likely a forced mate.

This would be okay if Rf8 was the best of the alternatives, but it doesn't seem to be. Stockfish on my laptop never suggests Rf8. It converges on Kf8 fairly quickly, and sticks with it after a couple hours of searching. Has anyone looked at whether Rf8 could be the result of a bug triggered by the AlphaZero team? It seems implausible to me that Stockfish would have made this move on such a high power machine if it was correctly functioning.

**Comment by Atahan-Turkoglu** [comment]
In addition

The best opening SF play against A0 is B40 Scilian Defence.
SF vs A0 : +9 =71 -20

And the worst opening SF play is C00 French Defence.
SF vs A0 : +0 =57 -43

**Comment by Vizvezdenec** [comment]
Is there any point to "solve issues" of an engine that is almost 1,5 years old?

**Comment by Vizvezdenec** [comment]
Also just daying - "issues" is made for some critical stuff that is related to coding/program, not "wow it doesn't see this move in this positions" - you have fishcooking forum for this, so pls close this issue and write it at fishcooking https://groups.google.com/forum/#!forum/fishcooking if you want.

**Comment by afontenot** [comment]
To be clear, my problem isn't that Stockfish doesn't see the move. I agree that wouldn't be relevant for a bug report. The issue is that I can't replicate the findings of AlphaZero; Stockfish makes a _much_ better move for me on a _much_ lower powered computer. If this is due to significant improvements in the engine between the AlphaZero version and current, then the issue I'm reporting has already been fixed. Fair enough. (This didn't occur to me as a real possibility - the paper was published less than 3 months ago.)

But I'm suspicious that the AlphaZero paper has uncovered some buggy behavior triggered by their testing environment.
