### ISSUE TITLE
Add Android build chain (makefile changes, NDK for Trevis CI, ...)

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#1457]
I see it would be possible to add android to Trevis CI, although not immediate:

Here few examples:

https://github.com/google/flatbuffers/blob/master/.travis.yml
https://github.com/googlesamples/android-ndk/blob/master/.travis.yml
https://github.com/leinardi/androidthings-pio/blob/master/.travis.yml

If someone volunteers to add this target to Trevis CI we would gain test coverage fo ran important but somewhat not easy to test platform.

**Comment by Nordlandia** [comment]
I can allocate 7 out of 8 cores on my Samsung Galaxy S8+ 

Speed is equilavent to mediocre 2-core laptop.

**Comment by mcostalba** [comment]
@Nordlandia very good. Did you change the Makefile? In which way?

**Comment by Nordlandia** [comment]
The idea here is to support android for fishtest framework. Is it technically feasible soon?

I can allocate my phone for fishtest framework once possible. 

I use DEX docking station with integrated fan.

**Comment by snicolet** [comment]
I changed the title of the issue to "Add Android build chain (makefile changes, NDK for Trevis CI, ...)" to make it a little bit more general, and also to be concentrate all the Android discussion in a single thread (for instance https://github.com/official-stockfish/Stockfish/issues/2380 was closely related).

**Comment by anonymous7002** [comment]
This conversation doesn't solve the problem.
I want to know how to compile stockfish for android too.

**Comment by anonymous7002** [comment]
I'm ready to do Makefile changes.

**Comment by anonymous7002** [comment]
I'm ready to do anything.

**Comment by vondele** [comment]
I'm centralizing all Android issues in https://github.com/official-stockfish/Stockfish/issues/2860 where some active testing is going on. It would be great to address the initial comment, i.e. have eventually Android integrated in our CI.
