### ISSUE TITLE
Change for tuning branch requested

### ISSUE THREAD

**Issue by Stefano80** [official-stockfish/Stockfish#1460]
In later times, the test framework has experienced some lag problems due to excess traffic from HTTP requests in tuning branches, see e.g.

https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/kA28W9fyCGQ 

There some improvements which can be done on the worker (see thread). One thing which could help reducing the size of the json sent back and forth is to only use short variable names for tuning parameters, or have it by default in the tuning branch.

For instance, it would be very cool if the TUNE macro would cut all variable names down to the first letter (+ maybe second to avoid conflicts) and replace the array syntax A[n][m] by A_n_m.

**Comment by Stefano80** [comment]
I also made an entry in the [spsa wiki](https://github.com/glinscott/fishtest/wiki/Creating-my-first-test#tuning-with-spsa) to suggest to use short variable names.

**Comment by snicolet** [comment]
Is it still an issue after the recent patches of the server?

**Comment by Stefano80** [comment]
It is not a real issue anymore. Closing.
