### ISSUE TITLE
Hourglass time control 

### ISSUE THREAD

**Issue by Nordlandia** [official-stockfish/Stockfish#1472]
Yesterday i imported top three engines inside CM 11 interface with the purpose of testing this time control. 
My observation is that neither support it natively. Is it possible that SF can be taught using this type of time format. 

Here is the ongoing thread on fishcooking forum -[https://groups.google.com/forum/#!topic/fishcooking/aApM0pJ8e2s]

**Comment by MichaelB7** [comment]
Do you what the logic is behind CM hour glass time control - my guess is that is it simply 1 move in xx or perhaps a very short base - day 10 second with an increment.  In any event , if either case is true you should be able pass the time control over to SF using the polyglot adapter I believe.

**Comment by Nordlandia** [comment]
By using polyglot adapter you can import uci engines into CM gui and test it our yourself.

**Comment by MichaelB7** [comment]
I cannot , on macOS , was just trying to give you some ideas

**Comment by Nordlandia** [comment]
Tutorial here - https://www.chess.com/forum/view/general/chessmaster-11-add-stockfish-or-other-uci-engines

**Comment by syzygy1** [comment]
UCI determines the timing parameters that SF receives. This cannot be changed. Perhaps the GUI can do something, but that is not a Stockfish issue.

**Comment by Nordlandia** [comment]
Based on reviewing time usage during games, my initially thought suggests hourglass is completely new for SF. Equivalent scenario is Chess960 for human players, - In its infancy.

**Comment by Nordlandia** [comment]
SF7 vs K11.3 in 2 minute hourglass available on youtube - https://youtu.be/9jwhRSziulc

**Comment by Nordlandia** [comment]
I PM'ed Stefan Meyer-Kahlen. He is the inventor of the UCI protocol. Maybe he will implement it.

It turns out UCI protocol has to be slightly modified for hourglass. 

UCI does not seem to let you have both X moves in Y minutes, then the res of the game W minute plus Z increment for each move"

**Comment by Nordlandia** [comment]
Stefan replied he will modify UCI protocol for hourglass once he got hime. He said it is on the "to-do list"

It might be implemented into Shredder gui as well.

**Comment by snicolet** [comment]
So the ball is in the UCI protocol design commission at the moment, closing
