### ISSUE TITLE
The timer should use 64 bits

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#1498]
From user "fischerandom" on the TCEC chat:

There is a bug in Stockfish 9 causing the output to be wrong after 2^31 milliseconds search. 
Here is a long run from the starting position:
````
info depth 64 seldepth 87 multipv 1 score cp 23 nodes 13928920239402
nps 0 tbhits 0 time -504995523 pv g1f3 d7d5 d2d4 g8f6 c2c4 d5c4 e2e3 e7e6
f1c4 c7c5 e1g1 b8c6 d4c5 d8d1 f1d1
f8c5 c4e2 e8g8 a2a3 c5e7 b2b4 f8d8 b1d2 b7b6 c1b2 c8b7 a1c1 a8c8 c1c2 c6e5
d1c1 c8c2 c1c2 e5f3 d2f3 a7a5 b4b5 e7c5 f3d4 d8c8 d4b3 c5d6 c2c8 b7c8 b3d2
c8b7 d2c4 d6c5 e2f3 b7d5 f3d5 e6d5 c4e5 a5a4 e5d3 f6e4 d3c5 e4c5 b2d4 c5e4
d4b6 e4d6 g2g4 d6b5 b6c5 b5c7 g1g2 c7e6 c5d6 g7g6
````

**Comment by fastgm** [comment]
See CFish https://github.com/syzygy1/Cfish/commit/54302a0a2ea77558c78697fba08b560d2133cb35

**Comment by snicolet** [comment]
Thanks, the commit you point to also references this talkchess thread: http://talkchess.com/forum/viewtopic.php?p=747757#747757

**Comment by snicolet** [comment]
Closing after a03e98dcd33c91c47e4a06282bfb582e582671b7 has been merged
