### ISSUE TITLE
Bare minimum SF

### ISSUE THREAD

**Issue by Stefano80** [official-stockfish/Stockfish#1541]
I have a question or proposal. On fishtest we are slowly paying off our technical debt and setting up meaningful CI via Travis.

One problem is that if we want to test the worker properly, we have to compile SF and so on. This takes some time. How much work would it be to create a maintain a stripped down branch of SF, without parts which can be easily removed lije syzygy, bitbases, endgame knowledge, psq? And would you be interested in it?

This would save a lot of compile time and decrease the threshold in writing tests for the fishtest framework.

**Comment by WOnder93** [comment]
Why maintaining a separate branch when this could be achived just by adding more options to the Makefile and using macros to conditionally leave out parts of the code from compilation.

Either way, I'm not sure if this would be very beneficial as the removed parts may interact with the other ones in various ways and leaving them out from compilation/testing might cause less bugs to be found early.

**Comment by Stefano80** [comment]
Hi thank you for the comments. Could you give me a makefile example?

**Comment by WOnder93** [comment]
I tried to implement such Makefile option for syzygy support and it turned out to be quite easy: https://github.com/official-stockfish/Stockfish/commit/4d7fb1142b234e9e68ac016d3cbb179099c8e89e

It adds a bit of ugliness to the code but OTOH it is now easy to identify parts of code that are related to TB support.

**Comment by snicolet** [comment]
On my Mac compiling Stockfish takes about 5 seconds:

````
make clean && smake
````

where smake is an alias to make, but using the -j 8 flag to enable parallel compiling:

````
alias smake  "make build ARCH=x86-64-modern -j 8"
````

**Comment by MichaelB7** [comment]
The “8” is not required.  “-j” will default to the number of cores available.

**Comment by vondele** [comment]
for a fast compile (but slow SF) disable optimization:
```
make -j ARCH=x86-64 optimize=no build
```
I certainly would not modify the code base for having something that compiles quickly.

**Comment by syzygy1** [comment]
If I understand you correctly, you just want a toy engine that compiles very quickly and understands the UCI protocol so it can be used to test fishtest. It is not important how well it plays or how close it is to SF master. There is no need for something up to date.

So you do not need a special "stripped" SF branch that is kept up to date with SF master. Maintaining such a branch would be a waste of time.

You also do not want adaptations to SF master and its Makefile to optionally compile a stripped-down version. Maintaining such adaptations would also be a waste of time (and the adaptations would needlessly slow down SF development by complicating the code).

@vondele's solution seems to be the simplest and to meet your needs.

**Comment by Stefano80** [comment]
@syzygy1 @vondele yes, Ronald, you understood me right and yes Joost I think your solution is good enough. I did not know about `-j` option.

One reason for not using another engine is that in fishtest it would be much more easier to use a test branch for something than to use a different repository and build process altogether. I leave it open until the weekend in case anybody has some brilliant idea and then will close it.

**Comment by syzygy1** [comment]
But it doesn't have to be an "official-stockfish" branch, right? At least, when I run a test it will be some SF branch in my SF repository against some other SF branch in my SF repository and "official-stockfish" is not involved.

So you could create a branch in your own SF repository and, if you want, remove half of SF in that branch (and more importantly, disable the -O options in the Makefile).
