### ISSUE TITLE
Regression tests for custom games

### ISSUE THREAD

**Issue by KeithCu** [official-stockfish/Stockfish#1550]
I created a custom game with 6 knights for white versus black with their knights taken away. I don't have a bug, Stockfish played well. It created some pretty positions along the way.

I wanted to thank you for building something robust enough to play well on both sides even though much of your analysis was unusable. There are many interesting variations of chess and I hope you can play even if it isn't a case you care about.

Here is the 6 Knights game: http://keithcu.com/6Knights.pgn Maybe you could throw it or others in your regression tests so it won't break in the future either? ;-)

**Comment by Hanamuke** [comment]
In my opinion, it wouldn't be acceptable to degrade regular play to play variants better, and it would be acceptable to degrade variants play strength to improve regular play. Any regression test on such variant would be purely informative. 
I watched the game, it was interesting, stockfish thought it was very advantageous from the start. Arguably neither side knew how to play this.
You might be interested to know that there is a stockfish fork designed to play some more famous variants, it is used by lichess for all the variants.
https://github.com/ddugovic/Stockfish

**Comment by KeithCu** [comment]
I don't care if the performance degrades as long as it doesn't crash or hang.

I checked out the fork. I hadn't seen any of the variations. Some look interesting, but I want to just use "standard" chess rules.

**Comment by Hanamuke** [comment]
It should be ok then, stockfish even supports chess960 natively.
