### ISSUE TITLE
Option to deactivate permanent brain during opponents turn for handicap matches

### ISSUE THREAD

**Issue by Nordlandia** [official-stockfish/Stockfish#1560]
Permanent brain handicap is something to use against weaker engines to compensate and make the match more fair in terms of overall forces in play on both sides. Is this possible for custom sf compile? if yes, then i will appreciate if one can compile such executable for me :)

See thread
https://groups.google.com/forum/#!topic/fishcooking/aErttX22j0o

**Comment by snicolet** [comment]
Please have a look at the "ponder" option of Stockfish, this is what you are looking for.

**Comment by Nordlandia** [comment]
Does not work in Fritz GUI. I intend to use engine cloud for two computer match.

**Comment by Nordlandia** [comment]
As long SF can't use ponder during opponents turn then everything is fine. Ponder can be selected to be used by selecting checkbox in Fritz engine match, that mean both use ponder.

**Comment by joergoster** [comment]
This is solely a problem of the GUI! The GUI must send 'go ponder' and 'ponderhit' if the expected move was indeed played to switch from the ponder search into normal seach mode. Fritz simply doesn't support different ponder modes for two engines. And no, checking 'Ponder' box for one engine and not for the other won't help here.
Use Cutechess-GUI instead. Not sure if Winboard supports it.

**Comment by Nordlandia** [comment]
@joergoster: turning on/off ponder for selected engine is a requested feature for CuteChess-GUI but it turns out to be complicated to be implemented.

**Comment by lantonov** [comment]
In Winboard, one can turn off ponder from several places like
![image](https://user-images.githubusercontent.com/6498222/39228071-c69a5904-4864-11e8-8093-b3d63df8cbc6.png)
and
![image](https://user-images.githubusercontent.com/6498222/39228112-f1b059a4-4864-11e8-936c-c39519807915.png)
