### ISSUE TITLE
a question about hash on excludemove exist

### ISSUE THREAD

**Issue by cirebonb** [official-stockfish/Stockfish#1582]
why u do this-->  posKey = pos.key() ^ Key(excludedMove << 16); 
tte = TT.probe(posKey, ttHit);

when  u do this--> if (!excludedMove)
tte->save(posKey, value_to_tt(bestValue, ss->ply),

I dont understand, im beginer. thank you.

**Comment by snicolet** [comment]
There are some more `tte->save(posKey, ...)` in lines 667, 709 and 827 of search.cpp

**Comment by cirebonb** [comment]
667=for TB ok
709=for static eval ok
both allready did in caller function. right?
827? will found also 1165

**Comment by cirebonb** [comment]
I think singular extension search in sf only for improving good moves hystory, and collect more node in case we drop rbeta, it never use ttmove as 1st move to search. may be I missed something? thanks for ur answer snicolet.
