### ISSUE TITLE
7.53 eval in a equal position

### ISSUE THREAD

**Issue by AMN3I** [official-stockfish/Stockfish#1613]
At TCEC s12 in the game with Jonny 
After moves:1. g3 e5 2. Nf3 d6 3. Bg2 Nf6 4. d3 Be7 5. O-O O-O 6. c4 c6 7. Nc3 Nbd7 8. e4 Re8 9. Be3 a6 10. a4
 
Stockfish gave a +7.53 advantage. After Jonny move, the eval come to -0.40.
I think Stockfish is having problems with the evaluation.

**Comment by AndyGrant** [comment]
That was a search on the end position of a PV. Nothing is wrong.

**Comment by AMN3I** [comment]
I don't think it's normal for a Stockfish variation in a equal position to have +7.53 at the end

**Comment by AndyGrant** [comment]
You don't understand what the +7.53 eval came from. A different version of stockfish took the final position from the stockfish playing in TCEC's PV for the 10th move.

From this position the analysis Stockfish ran a search, and came up with a +7.53 eval.

There is absolutely nothing wrong with that.

**Comment by syzygy1** [comment]
@AMN3I 
Your link doesn't seem to be pointing to anything useful, and you are not giving us a legal position in FEN format for which you have personally checked that an up to date Stockfish acts weird on it.

**Comment by AMN3I** [comment]
I deleted the link now.

**Comment by syzygy1** [comment]
But I guess you cannot actually reproduce the problem? (I cannot.) Something which cannot be reproduced cannot be fixed (if it is broken at all).

I don't know what you were seeing, but (as @AndyGrant suggests) it was probably not Stockfish actually misevaluating a position but more something comparable to an operator error.
