### ISSUE TITLE
Clang: Profile build broken 

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#167]
Profile build broken with Clang after commit 46d5fff01fbeafdf82

Tested with Clang 3.5 on Ubuntu 14.04

Steps to reproduce:

make clean
make profile-build debug=yes optimize=yes ARCH=x86-64-modern COMP=clang

**Comment by zamar** [comment]
Ignore for SF6

**Comment by mstembera** [comment]
https://github.com/official-stockfish/Stockfish/pull/237
should address this.

**Comment by mstembera** [comment]
Still does not work w/ clang 3.6.2.  Tested under Ubuntu 15.10.

**Comment by erbsenzaehler** [comment]
#169 did work for me with clang 3.7 under both Fedora and Arch, although the speed gain is rather disappointing. 20 runs of bench give:
                                    nodes     nps         stdev
./stockfish-clang          7597031 2528014 5509
./stockfish-clang-pgo  7597031 2567219 40755
./stockfish-gcc            7597031 2567397 41261
./stockfish-gcc-pgo     7597031 2785470 8146

**Comment by erbsenzaehler** [comment]
I did test the solution presented here on a freshly installed Ubuntu 1604 and did get a speedup. I needed a symlink for llvm-profdata pointing at llvm-profdata-3.8.

**Comment by MichaelB7** [comment]
What happens when you type : 

"llvm-profdata show -version" 

on the command line?

mac output:
  LLVM (http://llvm.org/):
  LLVM version 3.9.0
  Optimized build.
  Default target: x86_64-apple-darwin16.1.0
  Host CPU: westmere

Second question - is that what you expected - is the LLVM version in sync with the clang version?

**Comment by mcostalba** [comment]
```
$ llvm-profdata show -version
llvm-profdata: command not found
```
