### ISSUE TITLE
3-fold lines clogging TT with high depths

### ISSUE THREAD

**Issue by noobpwnftw** [official-stockfish/Stockfish#1673]
Symptom:
There has been a problem with aggressive pruning that made the search tend to fall back to 3-fold lines when it cannot find better alternatives and eventually break out into a lost position by an unexpected opponent move.

When you analyze the position without pre-existing hash(maybe from previous searches before making that move), it will discover the correct move fairly quickly. 
Also, there is an approach is often used to solve puzzles: make the correct move manually and go back, however, it does not always work, I suspect that it is the same problem. Supposedly it should solve by higher depth(thus less pruning at root) not by manual intervention.

My observation is that in these scenarios, the early searches tend to prune more on those lines and resolve them in 3-folds, which gave almost free depth later on, to a point that even with less pruning the search is unlikely to break those loops.

I can try to not store repetitions in TT, or reduce their depths before getting saved in TT, but I guess it would result in lose of ELO.

Starting this discussion to see if there may be a better solution.

**Comment by crossbr** [comment]
I can also attest to this problem. An example can be seen in the 2.2 trillion node search results for move 48. f7-f6, as I described in fishcooking [here](https://groups.google.com/d/msg/fishcooking/SWa9vEl4yig/pjKj45B3DAAJ).

**Comment by NKONSTANTAKIS** [comment]
This sounds like it might be the cause for this problematic behavior. 
3r2k1/pBr5/Pp2pq1p/3bRP2/3P3p/8/3R2P1/3Q2K1 b - - 2 48
Here SF couldn't see the win because it was tripping in perpetuals, but it was long ago, could you check with SFdev?

The whole discussion (unresolved)
https://groups.google.com/forum/#!topic/fishcooking/IIbpt8dEXKs

I'm wondering if the full cycle detection patch (with no progress key) can solve it.

**Comment by vondele** [comment]
The patch tested here (two yellows, slight elo gain estimated):

http://tests.stockfishchess.org/tests/view/5b7e53fc0ebc5902bdbb2a82 (stc)
http://tests.stockfishchess.org/tests/view/5b7ea7510ebc5902bdbb3060 (ltc)

seems to fix some of these notorious 3-fold FENs, but is not strong enough to be committed.

**Comment by NKONSTANTAKIS** [comment]
@snicolet You agree with vondele or maybe its commitable as a bugfix? If not we are still searching for another solution I guess.

**Comment by noobpwnftw** [comment]
Looks like this has been addressed by https://github.com/official-stockfish/Stockfish/commit/97d2cc9a9c1c4b6ff1b470676fa18c7fc6509886, closing.
