### ISSUE TITLE
Passing pawns

### ISSUE THREAD

**Issue by agmilk** [official-stockfish/Stockfish#1704]
why Stockfish has not learned to protect a 100% passing pawn 7r/P2KB3/8/3B4/5k2/8/8/8 w - -

![stockfish](https://user-images.githubusercontent.com/41733295/43257047-57ace3f2-90d7-11e8-904a-569adc220789.jpg)

**Comment by Vizvezdenec** [comment]
because it still wins with 2 bishops vs naked king?

**Comment by agmilk** [comment]
The main thing is not two bishops, but the very FACT of inability to protect passing pawns in the simplest positions

**Comment by Rocky640** [comment]
Thank you for this interesting observation which might lead to some improvements.
a7-a8Q is M20 but Bd5b7 is M12 and SF seems blind to this possibiity, even with multipv

But this is not technically a bug. Such reports should be made here instead.
https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

**Comment by agmilk** [comment]
multipv does not work correctly. Only Stockfish does not solve this simple position.

**Comment by snicolet** [comment]
What is exactly the problem if Stockfish shows a mate in 18 instead of a mate in 12 ?  Maybe she will find the mate in 12 with more time?

**Comment by MichaelB7** [comment]
SF found the mate-in-12 on machine in 60 seconds - about 2.4 billion nodes.

**Comment by agmilk** [comment]
the cost of the pawn on the penultimate line should be increased. SF needs to protect a passing pawn.

**Comment by snicolet** [comment]
You should learn C++


See how useless this kind of comments are ? :-)

**Comment by agmilk** [comment]
Why does not Stockfish understand such simple positions? 2K2N2/1P6/8/4b3/8/1B6/4k3/8 w - - 
![stockfish](https://user-images.githubusercontent.com/41733295/43580037-af4fc9fa-965c-11e8-8653-da6182255bc3.jpg)

**Comment by snicolet** [comment]
She does.

It would more interesting if you showed us a position where there is a winning move and she plays a losing or a drawing move.

**Comment by MichaelB7** [comment]
@agmilk   First the tone of you question carries an attitude - along the lines of why is SF is so dumb and the inference is also that the solution should be easy.   Well the solution is easy , when you have tablebase mate , you let the tablebases take over - they have perfect knowledge to secure the win or draw.  If you would like to help - then help , submit code , donate pc time - but it is no help when sit you back on your throne and ask jackass type questions.

**Comment by joergoster** [comment]
This happens because we assign a big winning score to king and winning material vs a lone king (KXK endgame), but not vs a king with a minor piece or rook left. This causes the search to prefer lines leading to KXK endgames.
For those interested in a possible solution, see https://github.com/joergoster/Stockfish/commit/d051e2d74a18466a5e9fb2d92a609a267b04f55b

@MichaelB7 Of course, with more time the search will finally resolve this. But I prefer a smarter search. ;-)

**Comment by Rocky640** [comment]
Very interesting @joergoster !

Current master passed pawn evaluation is fine indeed and was not the culprit.
Moreover, the LazyEvaluation threshold kicks in in the 2 positions.

However current master has no problem to find the 1.Ne6 and 2.Nc7 maneuver in this position
2K2N2/1P6/8/4b3/8/1B6/4k1nn/6nn w - - 0 1 

So as @joergoster this is mainly a matter of huge discrepancy between scores, and even more with mate scores

However I wonder if it would be a good idea to disable LazyEvaluation if 
Options["UCI_AnalyseMode"] is true

**Comment by agmilk** [comment]
Rocky640 yes, disable LazyEvaluation is very good idea. +10 ELO minimum.
