### ISSUE TITLE
Dead position detection

### ISSUE THREAD

**Issue by stas730** [official-stockfish/Stockfish#1728]
Detect dead positions like 4k3/8/8/p2p2p1/P2P2P1/8/8/4K3 w - -

**Comment by snicolet** [comment]
Thanks for the advice.

Please note that directly opening a pull request with such advices is not the recommend way to improve Stockfish, as we usually prefer code changes backed up by tests. You may want to read https://github.com/glinscott/fishtest/wiki/Creating-my-first-test to learn the best to contribute to the project :-)
