### ISSUE TITLE
Possible Optimization for Amd CPUs

### ISSUE THREAD

**Issue by CoffeeOne** [official-stockfish/Stockfish#1759]
I open this issue for a short discussion.
Normally for a compilation for an Amd Cpu is done with ARCH=x86-64-modern.
Actually it is super easy to speed up the compilation a little bit when g++ is used, simply by injecting `march=native` (at least with a modern version of gcc).

I verified on Windows (msys2, gcc 8.2) CPU AMD FX-9590:
On a standard compilation, a lot of `bsfq` and `bsrq` assembly instructions are created.
After injecting `-march=native` there are (almost all) gone:
the bsfq instructions are replaced with `tzcntq`
and instead of the bsrq instructions, `lzcntq` is used.
tzcnt and lzcnt are faster than bsf and bsr.
Only one:
```
./search.s:9291:        bsrq    %r8, %r8
```
remains with march=native.

Please note that lzcnt is available already on very old Amd CPUs like a Phenom II or Opteron 8439SE, so even those would gain speed from adding native.

On the other hand, I am not sure, if the Makefile of stockfish should be changed. Adding `march=native` per default would damage cross compiling (the build I created with the FX-9590 CPU does not run e.g. on a Xeon E7-4870 CPU, which uses "modern", too).
So we could introduce an option to active native (default off), but in my opinion the makefile is already messy, and would be messed up even more.
Moreover it is very easy to inject native by everybody, it is even possible without changing the `Makefile`.

**Comment by erbsenzaehler** [comment]
Cfish has a command line switch in its makefile to enable the -march=native flag. Default is off

https://github.com/syzygy1/Cfish/blob/master/src/Makefile#L343-L346

**Comment by CoffeeOne** [comment]
@snicolet Do you think a pull-request (to introduce a switch "native") makes sense?
