### ISSUE TITLE
Display of Multiple Variations unstable

### ISSUE THREAD

**Issue by rackbrain** [official-stockfish/Stockfish#1791]
The manner in which multiple variations are displayed when communicated to a GUI has changed within the last 10 days. In this case I am using a Scid vs. PC version 4.19 that has remained unchanged since March 2018.
For version Stockfish 9 and all development versions up to and including 21 October 2018, if for example the MV is set to two, the best two lines are continually displayed while Stockfish analyses to a greater depth.
For versions 25 October 2018 and 27 October 2018, at various intervals during analysis one of the variation lines disappears from view then later reappears. I have not been able to precisely identify at what point this happens.
This may seem trivial but it is extremely annoying if one is trying to record two possible variations in the pgn at a certain depth. Please check and revert to the GUI communication method within Stockfish 21 October 2018 and previous versions.

**Comment by rackbrain** [comment]
I noticed today that analysis lines disappear when the depth is reduced, so this similar to Issue #1787.
What is the reason for the closing of this issue? Do the developers intend to leave this situation unchanged or make suitable modifications?

**Comment by pb00068** [comment]
I See the issue still Open and we will fix the Problems surely.

**Comment by vondele** [comment]
OK, please close the issue.
