### ISSUE TITLE
Blocked Rook

### ISSUE THREAD

**Issue by tomitank** [official-stockfish/Stockfish#1793]
I think this is wrong:
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L386

If the King on E file, then the King side Rook is blocked? This is not correct.

This will be better:
`if ((kf < FILE_E && file_of(s) < kf) || (kf > FILE_E && file_of(s) > kf))`

**Comment by Rocky640** [comment]
Best place to discuss questions about the code would be on the fishcooking forum
https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

Like any evaluation term, this rook penalty will apply correctly in most of the cases, and in some cases, it  will not apply so well.

But nothing is wrong in the original line of code
It once was more complicated than this, but unnecessary complexity was simplified away.
`                if ((kf < FILE_E) == (file_of(s) < kf))`
 
This expression is true if
e) king on file e and the rook is on e, f, g or h 
f) king on file f and the rook is on f, g or h 
g) king on file g and the rook is on g or h 
h) king on file h and the rook is on  h 

Now looking at the queen side
d) king on file d and the rook is on c b or a
c)  king on file c and the rook is on b or a
b) king on file b and the rook is on a

Logic is a bit different, but the penalty almost never apply on the queenside.

Testing for your expression would need to pass SPRT[0, 5] at STC and LTC, which will not happen 
`if ((kf < FILE_E && file_of(s) < kf) || (kf > FILE_E && file_of(s) > kf))`

Testing for exclusion of same file on king side (but not on queenside) could be tested SPRT[0, 4]
`if ((kf < FILE_E) ==(file_of(s) <= kf)`

But consider a position with Kh8, Rh7 g7 h6, I think we can safely say the rook is trapped.
It would be weird to consider trapped if Kg8, Rh7 g7 h6 but not for Kh8, Rh7 g7 h6
In any case, a few moves will be needed to untangle that rook, and a TrappedRook penalty is well deserved.

**Comment by tomitank** [comment]
Hi!

> Best place to discuss questions about the code would be on the fishcooking forum
> https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

I'm sorry, I did not know.

> This expression is true if
> e) king on file e and the rook is on e, f, g or h

That's exactly what I meant. I see, it does not make a big (elo) difference, but it's not correct.

> Testing for exclusion of same file on king side (but not on queenside) could be tested SPRT[0, 4]
> if ((kf < FILE_E) ==(file_of(s) <= kf)

Yeah, that's a good idea. Similar to Senpai 2.0

Here is another idea, which deals with both things:
```
if (!pos.can_castle(Us) && (kf < FILE_E) == (file_of(s) <= kf))
{
    score -= TrappedRook - make_score(mob * 22, 0);
}
```

Only the "returned (to file e)" King is blocking the rook on king side.

**Comment by Rocky640** [comment]
> it's not correct
I disagree.

Really, I don't know many positions with a Ke8, a Rh8 and a Re7 with mob < 4,
and if it happens, this Re7 to get there have probably a mob 3 and in this ase the small penalty S(22, 0) might even make sense. 

Sorry, but fixing a problem which is not one by slowing down the code will not improve SF.

However, feel free to run your own test. See https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

**Comment by tomitank** [comment]
> Sorry, but fixing a problem which is not one by slowing down the code will not improve SF.

Would you explain this? I'm sorry but I do not understand

I don't want to argue, but it must run at the same speed. (Maybe even faster)

```
            else if (mob <= 3)
            {
                File kf = file_of(pos.square<KING>(Us));
                if ((kf < FILE_E) == (file_of(s) <= kf) && !pos.can_castle(Us))
                {
                    score -= TrappedRook - make_score(mob * 22, 0);
                }
            }
```

pos.can_castle(Us) was here, but now it is not necessary.:
https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp#L387

**Comment by tomitank** [comment]
Obviously, the parameters must be tune.

**Comment by Rocky640** [comment]
OK, I misread your code. I did not looked at your L387, which I assumed was identical to master,

Yet I believe current code to be fine.
a) there is a value to score a trapped rook even if king can castle (this is an incentive to castle)
   In sf code,  pos.can_castle just means we still have some castling rights, not that you can castle on the   next move. It also does not tell you if castling would be a wise thing to do.
b) I believe there is a value to penalize a rook on same file as king, which your code doesn't address.
    As I said above, it would be weird to consider trapped if Kg8, Rh7 g7 h6 but not for Kh8, Rh7 g7 h6

I tell you these things from experience, from my test and also test I have seen by a few other people. Something which was true 2 years ago might be different nowadays. 

I will be glad if you prove me wrong.
So feel free to run your own experiments and draw your own conclusions.

See https://github.com/glinscott/fishtest/wiki/Creating-my-first-test
