### ISSUE TITLE
Testing resource usage and guidelines

### ISSUE THREAD

**Issue by Alayan-stk-2** [official-stockfish/Stockfish#1805]
Recent discussions, including around #1802 and #1804, but also from the fishcooking forum, show that the current testing rules are not satisfactory.

First, a disclaimer : I write this as an informed outsider. I don't have the insight of a long time contributor, but I have followed with attention the recent events and want to see SF improve. I also think a github issue is a better place to discuss it than a google group thread. It directly affects SF's development.

What is wrong ?

- Unclear guidelines about LTC use for the results of LTC tuning (no explicit exception to the STC pass, which creates arguments)
- Lack of confidence in STC results. STC is supposed to act as a filter so that testing resources are only used at LTC for promising patches. The recent 2 PR which failed at STC but succeeded at [0,5] in LTC indicates that the likelihood of ELO-gainers being rejected can be significant. If a LTC+ elo-gainer has not a 5% likelihood but e.g. a 10% or 15% likelihood to be rejected at STC because of some time-scaling effects, then the filter is poor. Some patches have exhibited the reverse issue, passing multiple times at STC while failing multiple time at LTC.
- Lack of confidence in LTC results. The 2 PR which have failed at STC but succeeded at LTC are now being retested again at LTC. There is no resources saved when a test has to be ran twice to reassure everyone that it is really good.

And on the topic of wasted resources on fishtest, I would add : 
- Multiple interdependent tuning running at the same time. PawnFormationTune ? 500K 20+0.2 games. 8X8 king PSQT ? 150K LTC. Piece value tuning ? 120K LTC. King pawn eval tuning ? 768K (!!) LTC. One of those being merged could make the value of one of the other inappropriate, or at least much less optimal than it could have been if done serially (tune, test, merge, tune, test, merge). Even if tuning is run at low priority, hundreds of thousands of LTC games potentially wasted is questionable.
- Lots of variations around a random small tweak which fail STC again and again, succeed by luck, and then fail LTC.

I don't have all the answers, but SF's team should analyze the situation (gather some data where needed), formulate potential improvements, and test them for validation.

Here are some suggestions : 
- Analyze how the resources are currently used. How much go to STC tests ? To LTC tests ? To LTC tunes ? How often is it just idling ? Also breakdowns based on the type of change (value tweak, minor variation, or more original innovation) and on successful results. Use this data to help deciding on the best course of action.
- Analyze the quality of the STC filter. In theory if the scaling was perfect, it would reject 95% of bad patches ~~and accept 95% of good patches~~ (actually no : small elo gainer have a high likelihood of being rejected). For patches tested both at STC and LTC (mostly STC green, but also some STC reds), what are the results in practice ?
- Clarify in the guidelines that LTC tuning don't need to pass STC to be tested at LTC. Tuning for 150K LTC games and not investing say 50K LTC to verify the result because of a 30K STC fail doesn't make sense.
- Add something in the guidelines against multiple tuning of significantly related values in several parallel tuning sessions. Leave some leeway for situations where the resource usage in fishtest is low, guidelines are here to guide, not to be followed to the letter even when it doesn't make sense.
- Try to integrate quickly tuning patches once they have been confirmed to work to not stall further tuning.
- If the analysis of the STC filter proves it is much worse than the 95%/95% rate, decide how to improve it. Having a less stringent ELO interval for the test would allow more good patches to pass at the cost of more bad patches passing (and higher resource usage at LTC), having a longer STC would allow more good patches to pass and less bad patches to pass at the cost of increased resource usage for STC (but some less at LTC). The new numbers would have to be tested to confirm that they do improve the filter's quality enough to make them worthwhile.
- Increase confidence of LTC tests. This should be better than always doubting if a patch is not a regression and sometimes running twice the same LTC tests, though it will consume more resources.
- Establish guidelines to allow the TC and confidence policies to evolve more easily over time depending on available testing resources and other considerations. It is almost certain than even if things were fixed now, similar concerns will arise in the future. Having a way to deal with them by better assessing the real needs of the project rather than yielding to some people shouting their emotions, be they in the pro-change or anti-change crowd, would be great.
- Finally, and this last suggestion is much less informed than the other ones (this is my subjective inclination, which might be very wrong :slightly_smiling_face: ), I am personally interested to see what additional testing at a longer TC like 120+1.2 can bring, even at a fixed game number and only on LTC successful patches. The more SF improves its ELO, the more a shallow depth search becomes limited, and that sort of test could help to get a better understanding of the situation.

**Comment by Alayan-stk-2** [comment]
Some data on yellow/green STC tests with a corresponding fully completed [0,4] or [0,5] LTC test since around 22 october (oldest taken into account is space4a, most recent kngMobTable1) : 
- 4 yellow STC -> 1 yellow LTC, 3 red LTC
- 34 green STC -> 4 green LTC, 11 yellow LTC, 19 red LTC

There are only two ways to interpret these numbers, which can be combined. The first one is that a large majority of tests passing STC at green are false positive. The second one is that STC green/red is a poor indicator of LTC green/red.

During the period after the submission of the first STC test which got a LTC accounted for in my stats, there was 695 STC tests at [0,4] or [0,5]. The expected average number of false positive, assuming all the patches were elo neutral, would be 34, with a significant random variance (there is a 5% chance to have <=25 false positive and 5% to have >=45 with such a sample size).

Due to the small sample size, it's not possible to conclude if STC is a good enough filter. It's clear, however, that doing 20 random variations of a random tweak is behind a huge amount of tests (enough so that it's likely that one of the passing green STC+LTC in that period was a false positive), and that they can't be run directly at LTC.

The patches passing LTC and failing STC are the most worrying, but because it has only been attempted in rare cases (LTC tuning), the sample size is extremely small.

**Comment by ddugovic** [comment]
Perhaps if attempting 20 random variations of a random tweak (or if re-doing a test), increase the confidence level with each test to avoid [false positives](https://www.xkcd.com/882/).

Regarding test quality, I'd appreciate if someone could code review https://github.com/zamar/spsa/pull/6 because under Elo, a draw is a meaningful result and yet right now (without this PR) drawn games are being ignored/discarded.

**Comment by snicolet** [comment]
The discussion seems to have moved to https://github.com/official-stockfish/Stockfish/issues/1805, so I am closing this issue for now.
