### ISSUE TITLE
Stockfish does not see mate in 9 fast enough

### ISSUE THREAD

**Issue by Karlon** [official-stockfish/Stockfish#182]
In this position; 3r4/4r2k/3p1p1b/2n1p1pQ/2B1b3/P3B1PP/2PR1P2/3R2K1 w - - 0 34

At first, Stockfish decided to actually play for a *DRAW* when there's a clear mate in 9! It was not until 15 minutes, when SF decided to choose Bxg5 (which is the right move and can mate black in just 9 moves, or less)

This problem effects time management adversely.

**Comment by Karlon** [comment]
Correction: I made a typo, it took 5 minutes, not 15.

**Comment by Karlon** [comment]
But still, 5 minutes is quite a lot. It was a simple and a pristine move, which SF should have chosen quickly rather than pondering for a long period.

**Comment by nabildanial** [comment]
These things are not bug-related issue, so please don't post them here. If you need a mate solver version of Stockfish, you can find it here 
https://github.com/jhellis3/Stockfish/tree/mate_finder

Or disabling null move and futility pruning can help tactical positions a lot. You can see the patch here
https://github.com/nabildanial/Stockfish/tree/no_null_move_futility

Of course, as lucasart already pointed it out, doing these things can affect ELO.

**Comment by Karlon** [comment]
Nabil, thanks for sharing these wonderful patches but they still don't help in finding tactical/positional sacrifices in complex positions, they just ignore them. I am looking for a patch that could potentially solve the problems listed here; https://github.com/official-stockfish/Stockfish/issues/180

**Comment by mcostalba** [comment]
You are just looking for spamming the issue list!

And wth me we are already 3 people trying to explain you that this list is
NOT for report this kind of things.

Please report your stuff on the fishtest forum. This list is only for bugs
report. Where bug it does not mean SF does not do what you want in your
preferred position.

Closed again!
