### ISSUE TITLE
Unable to find out correct Candidate move Qg4

### ISSUE THREAD

**Issue by walchandwarik** [official-stockfish/Stockfish#1832]
In the position 
r1b1k2r/5ppp/p3p3/2BpP3/P7/2P5/5PPP/qN1Q1RK1 w kq - 0 2

accurate move is Qg4. But even at depth 30, SF is not able to find the same.

**Comment by MichaelB7** [comment]
With the fen posted, Qb3 or Qd2 are easily the two best moves.  Perhaps there is a copy and paste error with the fen posted?

r1b1k2r/5ppp/p3p3/2BpP3/P7/2P5/5PPP/qN1Q1RK1 w kq - 0 2
```
dep	score	nodes	time	(not shown:  tbhits	knps	seldep)
 30	+8.93 	2.60G	1:38.19	Qb3 Bd7 Na3 Qxf1+ Kxf1 f6 exf6 gxf6 Qb7 Rc8 Bb4 h5 Qxa6 Kf7 Nb5 Kg6 Qd6 Bxb5+ axb5 Rh7 Qg3+ Kh6 Qe3+ Kg6 b6 Re8 Qg3+ Kh6 Qd6 Rb7 Qc6 Reb8 Bc5 Kg7 Qxe6 Rf7 Bd4 Kg6 Ke2 Rff8 Kd3 Kh7 Qf5+ Kh6 Bc5 
 30	+8.36 	2.73G	1:42.97	Qd2 Ra7 Na3 Qxf1+ Kxf1 Rd7 Qd4 g6 Bd6 f5 exf6 Kf7 Be5 Rf8 Nc2 Kg8 Qb6 Rb7 Qc6 Kf7 Nd4 h6 Qc5 Kg8 Nc6 Bd7 Qe7 Bxc6 Qxe6+ Rff7 Qxc6 Kh7 Qxd5 Rfd7 Qe6 Rb1+ Ke2 Rbb7 Qxa6 Rb2+ Kf3 
 30	+6.06 	2.76G	1:44.00	Qg4 Rb8 Nd2 Qxc3 Bd6 g6 Bxb8 Qxd2 Bd6 h6 Qf3 f5 exf6 Rh7 h4 Qb2 h5 gxh5 Qxh5+ Rf7 Be7 Qc2 Qxh6 Qh7 Qf4 Rxe7 fxe7 Kxe7 Qg5+ Ke8 Re1 d4 Qf6 d3 Rc1 Qb7 Qh8+ Kd7 Qg7+ Ke8 Qg8+ Kd7 Rd1 Ke7 Qg7+ Ke8 Qg6+ Ke7 Rxd3 
```

**Comment by walchandwarik** [comment]
Dear sir,
There is no error with FEN.
Eval to candidate Qg4 seems lower than other two alternatives. But after Rb8 the only reply from opponents, please verify the boost in eval by two fold.

Regards,

**Comment by MichaelB7** [comment]
It would be helpful if you could provide the winning line is that is better than Qb3 or Qd2.  Just as an observation, the game is won regardless of which of the 3 lines is played. Ultimately the position, while it may be a meaningful position to you, it is not the type of position that will attract a lot of followers to correct even if the Qg4 was found to be best.  More folks would be interested in the position if SF play a drawing or losing line when there is winning line that is missed.  This is all volunteer work, no one her gets paid , so one must present a convincing issue to get somebody else to work on it , of course you are free to work on the solution yourself which is often  the ideal solution.
