### ISSUE TITLE
crash on a specific position

### ISSUE THREAD

**Issue by tidynail** [official-stockfish/Stockfish#1836]
Hi there,

On Windows 10, both stockfish_8_x64.exe and stockfish_9_x64.exe crash on the following position.

position fen 8/pp5p/kqp5/2P1Br2/5Pb1/P1NQ4/1P4PP/2K2BbR w - - 0 1
go infinite
->crash right away

**Comment by Vizvezdenec** [comment]
because this position has white to move and black king is in check?

**Comment by tidynail** [comment]
Oh, you're right. Thanks for the quick feedback.
I close this issue, as it is an illegal position.
