### ISSUE TITLE
Modification to the fishtest page

### ISSUE THREAD

**Issue by FauziAkram** [official-stockfish/Stockfish#1865]
Hello dears,

Can we implement a system of filters in the main page of fishtest, so we can play around with the filters, and find exactly the tests that we need.

Criteria that might be used for the filters:
-Type of test (Sprt/Spsa/Num of games)
-Color (White, Red, Yellow, Green)
-Time Control (Stc/Ltc/Other)
-SPRT bounds ( [-3,1]/[0,4]/[0,5]/other)
-Number of games (from: X / to: Y)

**Comment by Vizvezdenec** [comment]
This will be useful to surf for for example "good" parameter tweaks to make big combo patches of them.
Once in 2/3 months there is always some combo patch passing but it requires quite a lot of deep digging into fishtest and a lot of effort. With this functionality it will get 50 times easier.
Also if we will soon have SPRT bounds changes it will be really useful for searching for "almost passed" patches to see if they will pass new SPRT (see discussion there basically approved by both maintainers https://github.com/official-stockfish/Stockfish/issues/1859 ).
