### ISSUE TITLE
Add SSE2 Bit Instruction to Makefile

### ISSUE THREAD

**Issue by Spill-The-Tea** [official-stockfish/Stockfish#1879]
Something like this should be sufficient:

ifeq ($(ARCH),x86-64-sse2)
arch = x86_64
bits = 64
prefetch = yes
popcnt = yes
sse2 = yes
pext = yes
endif

**Comment by Hanamuke** [comment]
SSE2 is enable by default on 64-bit, and i'm not aware of any 32-bit processor that has SSE2.

**Comment by Hanamuke** [comment]
You can use EXTRACXXFLAGS = -msse2 to test if you get a different binary.

**Comment by Fanael** [comment]
> i'm not aware of any 32-bit processor that has SSE2

The are some, but there aren't that many of them: early Pentium 4 (in fact, SSE2 was also called Willamette New Instructions back in the day, Willamette being the codename of the first rendition of Pentium 4), all Pentium M, the two or so Atoms that are 32-bit only and a bunch of embedded VIA x86 CPUs based on the Esther core. Anything older doesn't have SSE2, anything newer is 64-bit.
