### ISSUE TITLE
Improving the Readme

### ISSUE THREAD

**Issue by erbsenzaehler** [official-stockfish/Stockfish#1890]
I tried to improve the Readme because many people in my local chess club do not understand some of the uci options properly. Starting point of this was Cfish's Readme, some internet resources and the code itself.

Not being a native speaker I ask for a review and some suggestions along the line.

https://github.com/erbsenzaehler/Stockfish/commit/90b0cc7d1d855c8a9933ae3dbc02cb1771557581

**Comment by mcostalba** [comment]
Thanks for this, could you please open a PR instead of an issue? Thanks.
