### ISSUE TITLE
ARCH=x86-64

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#1901]
ARCH=x86-64 has no -msse3 flag

But only a few "non-modern" 64-bit CPU types has no SSE3 support

Could it possible to include "-msse3" for "ARCH=x86-64" and do "ARCH=x86-64-old" w/o SSE3 (like ARCH=x86-32-old)?

**Comment by mcostalba** [comment]
This is not an issue, eventually open a PR reporting imporved speed.
