### ISSUE TITLE
SSSE3 popcount

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#1902]
Most of "non-modern"(ARCH=x86-64 - before 4.2 SSE) CPU 64-bit has SSSE3 support (preSSE4, not SSE3)
Could it possible to implement fast func popcnt64() for such hardware? simple example:

```
const __m128i Z = _mm_set1_epi8(0x0);
const __m128i M = _mm_set1_epi8(0xF);
const __m128i K = _mm_setr_epi8(0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4);

uint64_t BitCount(const uint8_t * src, size_t size)
{
    __m128i _sum = _mm_setzero_si128();
    for (size_t i = 0; i < size; i += 32)
    {
        __m128i _src = _mm_loadu_si128((__m128i*)(src + i));
        _sum = _mm_add_epi64(_sum, _mm_sad_epu8(Z, _mm_shuffle_epi8(K, _mm_and_si128(_src, M))));
        _sum = _mm_add_epi64(_sum, _mm_sad_epu8(Z, _mm_shuffle_epi8(K, _mm_and_si128(_mm_srli_epi16(_src, 4), M))));
    }
    return _sum.m128i_u64[0] + _sum.m128i_u64[1];
}
```

Optimized sources:
https://github.com/WojciechMula/sse-popcount/blob/master/popcnt-sse-lookup.cpp

All about popcount on various platforms:

https://github.com/WojciechMula/sse-popcount

Acknowledgments:

http://0x80.pl/articles/sse-popcount.html

**Comment by noobpwnftw** [comment]
Modern compilers should already have those intrinsic functions built-in and with good quality.

**Comment by d3vv** [comment]
this is not true

**Comment by d3vv** [comment]
more over if we have no support SSSE3 wile building for ARCH=x86-64 there is no such code into binaries as well

**Comment by Hanamuke** [comment]
Replying for the few issues you opened : you can test and prove mesurable speed gains  with https://github.com/zardav/FishBench

**Comment by d3vv** [comment]
@Hanamuke Why do I need to use Windows for tests if this strange .NET app only run standard stockfish bench arg and subtracts one number from another?

**Comment by Hanamuke** [comment]
I actually meant to link this tool my bad
https://github.com/hazzl/pyshbench
