### ISSUE TITLE
Makefile option COMP=mingw with additional LDFLAGS produced -static flag twice

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#1908]
for example:

LDFLAGS="" make -j build ARCH=x86-64-modern COMP=mingw

`g++ -o stockfish.exe benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o   -static  -static`

**Comment by d3vv** [comment]
triple for pgo: 

LDFLAGS="" make -j profile-build ARCH=x86-64-modern COMP=mingw

`g++ -o stockfish.exe benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o   -static  -static -lgcov -static`

**Comment by snicolet** [comment]
What does the g++ compiler documentation says in case of duplicate options on the command line?

**Comment by mcostalba** [comment]
Indeed I don't see this as an issue (repeated options are correctly handled by the compiler). Eventually an esthetic one, but IMO it doesn't worth an effort.
