### ISSUE TITLE
Rebase the cluster branch

### ISSUE THREAD

**Issue by WOnder93** [official-stockfish/Stockfish#1909]
After merging PR #1905, the cluster branch now contains duplicate commits from master. To make the history simpler, it would be nice to rebase the whole branch on master, removing merge commits and the duplicates (all this is in fact done automagically by `git rebase`, all that's needed is to resolve conflicts).

I have pushed a rebased cluster branch [here](https://github.com/WOnder93/Stockfish/commits/cluster). I produced it by simply checking out the current cluster branch and running `git rebase master`, resolving conflicts along the way. At the end, I verified that the result differs from the current cluster branch only by the changes from the new master commits (there has been one new commit since the last sync).

To update the official repo's cluster branch to the rebased one, someone with push permissions has to do the following:
```bash
# Assuming a 'cluster' branch already exists in the local repo and the remote
# for official repo is named 'origin'.  
git remote add WOnder93 https://github.com/WOnder93/Stockfish
git fetch WOnder93
# reset the local branch to the rebased one:
git checkout cluster
git reset --hard WOnder93/cluster
# force push the new branch to GitHub:
git push --force origin cluster
```

**Comment by snicolet** [comment]
Thanks, will look at it!

**Comment by vondele** [comment]
Thanks, looks good to me.

**Comment by snicolet** [comment]
OK, so I have downloaded cluster Ondrej's branch locally, rebased it one more on latest master branch (after commit "Improve the Readme") and force-pushed it on official-stockfish as the official cluster branch.

This means that the history of the cluster branch on official-stockfish should now be clean.

@vondele @noobpwnftw  To get the cleaned branch locally as your cluster branch and restart developing from there, you may want to use the following commands:

git fetch official
git checkout cluster
git reset --hard official/cluster

@WOnder93 Thanks!

**Comment by vondele** [comment]
yes, will also reopen the other pr as based on this branch.

issue can be closed IMO.
