### ISSUE TITLE
ARMv8

### ISSUE THREAD

**Issue by lucasart** [official-stockfish/Stockfish#191]
This is a reminder that we need to think about ARMv8 (64-bit ARM), ideally before releasing SF6. We need to use hardware (through compiler intrinsics if possible) for:
* prefetch
* lsb/msb
* popcount

Does anyone have experience with Android NDK and an ARMv8 device to run some tests?

**Comment by zamar** [comment]
Unfortunately no one has voluntereed for this task.

Ignore for SF6.

**Comment by mcostalba** [comment]
Do we really need to keep it open? It is not a bug, simply it is a (possibly) missing optimization through platform specific code. 

BTW adding platform specific code is something we usually do not endorse, so I don't see why this is an issue.

**Comment by zamar** [comment]
It's fine for me to close this.

This is a feature request, not a bug.

**Comment by zamar** [comment]
Closed.
