### ISSUE TITLE
Suggestion: GPL--> LGPL license for an engine

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#1934]
Else this engine would be forced out from commercial GUIs, like Chessmaster 9k, which is sad.
I think engine can stay free, but not force GUIs.

NOTE: it may be possible to merely 'invoke' the engine from commercial GUI (via UCI; preventing GPL), but this is possible only on the PC, while mobile platforms may need better integration for a single package to be installed and run as a single executable.

I suggest to change license of the chess engine from GPL to LGPL or BSD.

**Comment by noobpwnftw** [comment]
Is the code GUI derived from the engine? If not, then it does not bother them.
Only their modifications on the engine needs to be in GPL, everything else does not apply.

**Comment by Technologov** [comment]
>Is the code GUI derived from the engine? If not, then it does not bother them.
If it is linked together, then judges can see the GUI as a "derivative work", as defined by the GPL and copyright law.

**Comment by vdbergh** [comment]
It is perfectly possible (and legal) to use the regular SF binary on Android (compiled for the platform of course) and invoke it via pipes. This is precisely what Chess for Android does (which is closed source).
