### ISSUE TITLE
Better policy on tuning runs

### ISSUE THREAD

**Issue by Alayan-stk-2** [official-stockfish/Stockfish#1956]
This is more of a "how to use fishtest" issue, but like with the SPRT bounds discussion, I think this is the better place to discuss it.

Tuning runs at fishtest are quite resource intensive. As with normal SPRT runs, the final result is often a failure. But there is a big difference between a hopeless and useless tuning run, and one which might succeed.

I have done quite my share of tuning runs not succeeding to improve SF, and at least this has allowed me to learn and differentiate them.

There are a few potential pitfalls for a tuning run:
- The tuning is for new eval terms, and adding them just doesn't improve SF no matter their value. This is often hard to identify, if the base idea is not obviously bad.
- The tuning is for many parameters at once, and random changes tends to dominate and there is no convergence. This happens when the parameters change during SPSA do influence game results, while which parameter change favored losses/wins can't be identified because they're so many. A typical example is PSQT tuning: http://tests.stockfishchess.org/tests/view/5c30cc840ebc596a450c0530
- The tuning has not enough variance of the tuned values to influence the results of the tuning game above random fishtest noise. This results in tuned parameters barely moving at all. This is a common error, and these tuning runs are a total waste of resources. An egregious example is the recent singular tunes: we have two identical tunes except for significantly different starting values, and neither have values moving in any significant way after using 15K LTC games each (http://tests.stockfishchess.org/tests/view/5c409a820ebc5902bb5d029a and http://tests.stockfishchess.org/tests/view/5c40996b0ebc5902bb5d0282). These are a complete waste.

Point 2 and 3 can be improved on.

I edited the fishtest wiki to add some information on when these issues usually happens and how to avoid them (higher ck to avoid the "non moving value" issue, lower to limit the "random change" one ; trying to tune less parameters at once also works for the "random change" one).

I think we should also have more awareness of these issues among people having the power to approve and modify runs, with **an official policy of stopping any tuning run exhibiting the "non moving values" symptom after a few thousands games** and informing people when it looks like their tuning run suffers from the "excessive random change" issue.

**Comment by xoto10** [comment]
The non-moving issue can also be addressed by using a lower value for A
when creating the test.  This has the advantage that only one value needs
to be changed rather than the many ck values, and the cut-and-paste from
the output of ./stockfish can still be used.
Nowadays I tend to use a mixture of setting wide ranges in the code (which
causes a larger ck to be generated) and/or using a lower value for A, e.g.
perhaps 2500 instead of the default 5000.

Regarding the singular tunes, they are very slow, so the impact is
relatively small, and last time I looked the one starting from all 40's
looked like it might reach the starting values of the other test by the
time it finishes, so the lack of movement may simply be that the current
values are optimal.

**Comment by Alayan-stk-2** [comment]
> The non-moving issue can also be addressed by using a lower value for A when creating the test. This has the advantage that only one value needs to be changed rather than the many ck values, and the cut-and-paste from the output of ./stockfish can still be used.

If this works too, then this can be a better way to avoid this issue.

> Regarding the singular tunes, they are very slow, so the impact is relatively small, and last time I looked the one starting from all 40's looked like it might reach the starting values of the other test by the time it finishes, so the lack of movement may simply be that the current values are optimal.

Look again. The one starting from the 40s is not at all moving towards the other one, with values after 15K games being 41.01 ; 40.14 ; 41.22 ; 40.21 ; 40.35 ; 40.68 ; 40.03 ; 39.87 ; 40.99 ; 40.78 ; 38.34 ; 39.88 ; 40.23, all those starting from 40. The decimals changes are basically meaningless.

**Comment by xoto10** [comment]
>
>
> If this works too, then this can be a better way to avoid this issue.
>
Yes. I used to routinely use an A value around 2500/3000 with the normal
procedure described in the "my first test" page. Perhaps a bit higher or
lower if I thought appropriate. There may be an argument for changing the
default, say to 3000.

>
> Look again. The one starting from the 40s is not at all moving towards the
> other one, with values after 15K games being 41.01 ; 40.14 ; 41.22 ; 40.21
> ; 40.35 ; 40.68 ; 40.03 ; 39.87 ; 40.99 ; 40.78 ; 38.34 ; 39.88 ; 40.23,
> all those starting from 40.
>
True. I obviously misread or didn't remember correctly when replying to
you. That one could be stopped.

>

**Comment by mcostalba** [comment]
It is an interesting tpic, but is not a SF issue.
