### ISSUE TITLE
GCC: Warnings with syzygy

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#196]
I have this warnings when building with gcc

syzygy/tbprobe.cpp: In function ‘int probe_ab(Position&, int, int, int_)’:
syzygy/tbprobe.cpp:204:14: warning: array subscript is above array bounds [-Warray-bounds]
         p[i++] = pop_lsb(&bb) ^ mirror;
              ^
syzygy/tbprobe.cpp:204:14: warning: array subscript is above array bounds [-Warray-bounds]
syzygy/tbprobe.cpp: In function ‘int Tablebases::probe_dtz(Position&, int_)’:
syzygy/tbprobe.cpp:314:14: warning: array subscript is above array bounds [-Warray-bounds]
         p[i++] = pop_lsb(&bb) ^ mirror;
              ^
syzygy/tbprobe.cpp:314:14: warning: array subscript is above array bounds [-Warray-bounds]

**Comment by glinscott** [comment]
Which compiler?

**Comment by matthewlai** [comment]
I also get that.

Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

**Comment by mcostalba** [comment]
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by joergoster** [comment]
I only get that when compiling with debug=yes.
gcc version 4.9.2 (Ubuntu 4.9.2-0ubuntu1~14.04)

**Comment by zamar** [comment]
gcc is known to suffer from false positives in this area... especially with -O3

**Comment by zamar** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56273

**Comment by mcostalba** [comment]
Thanks for the link. Sadly it seems they simply don't care (after a failed
first attempt) to fix it.

**Comment by zamar** [comment]
Ignore for SF6.

syzygy implementation will be worked on during SF7 anyway.

**Comment by zamar** [comment]
Good news. They have fixed the bug in the gcc5 branch :)

**Comment by Kingdefender** [comment]
Hi all,

This just for the record, I have recently installed the latest MinGW and, as reported by Felix on FishCooking also, it seems the issue is not fixed/back again, at least with current Stockfish master, you get the same warning. My version of GCC:
C:\>GCC --version
GCC (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.

Eelco

**Comment by zamar** [comment]
Still unfixed gcc bug:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59124

**Comment by vondele** [comment]
this issue can now be closed. 

What about making gcc's -Werror (all warnings are error) part of the makefile now ?

**Comment by lantonov** [comment]
With Marco's syzygy rewrite and gcc-6.1.0 I no longer get this warning

**Comment by mcostalba** [comment]
Fixed by https://github.com/official-stockfish/Stockfish/commit/c0bb0415394179e9c771

**Comment by mstembera** [comment]
I get these warnings under MSVC w/ the new C++ syzygy implementation.
tbprobe.cpp(536): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
tbprobe.cpp(547): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
tbprobe.cpp(582): warning C4244: '=': conversion from 'uint64_t' to '`anonymous-namespace'::Sym', possible loss of data
tbprobe.cpp(983): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
tbprobe.cpp(1010): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data

**Comment by mcostalba** [comment]
Thanks for reporting. I knew them also by looking at Travis ci output after
each commit.

I don't plan to fix them because they are wrong (gcc and clang don't report
them)  and the fix if is a bunch of casts it is very ugly too.

If you are able to fix them without using casts then it's ok.
