### ISSUE TITLE
Warning with profile building

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#197]
The hack in Makefile to workaround a gcc 4.7 bug when profiling:

# Deleting corrupt ucioption.gc* profile files is necessary to avoid an 
# "internal compiler error" for gcc versions 4.7.x
	@rm -f ucioption.gc*

Yields to this warning:

g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -fbranch-probabilities -ansi -pedantic -Wno-long-long -Wextra -Wshadow -g -O3 -DIS_64BIT -msse -DUSE_BSFQ -msse3 -mpopcnt -DUSE_POPCNT   -c -o ucioption.o ucioption.cpp
ucioption.cpp: In function ‘_Tp* __gnu_cxx::new_allocator<_Tp>::allocate(__gnu_cxx::new_allocator<_Tp>::size_type, const void*) [with _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, UCI::Option> >; __gnu_cxx::new_allocator<_Tp>::pointer = std::_Rb_tree_node<std::pair<const std::basic_string<char>, UCI::Option> >*; __gnu_cxx::new_allocator<_Tp>::size_type = long unsigned int]’:
ucioption.cpp:160:1: note: file /home/marco/Documents/Stockfish/src/ucioption.gcda not found, execution counts estimated
 } // namespace UCI

**Comment by zamar** [comment]
Once we stop using gcc 4.7, the hack can be removed, and this warning will disappear.

Unfortunately currently 4.7 produces the fastest binaries for us.

**Comment by mcostalba** [comment]
After SF 6 release I want to port upstream my C++11 branch and candidate it
to replace current one for SF 7.

If everything goes as expected: no regression and good portability across
compilers, we won't need this hack anymore because gcc 4.7 will be
obsoleted out.

**Comment by zamar** [comment]
Ignore for SF6.

If we have enough compilers supporting C++11 standard, we can consider switching to C++11 for SF7.

**Comment by mstembera** [comment]
https://github.com/official-stockfish/Stockfish/pull/237
should address this.

**Comment by zamar** [comment]
Resolved by #237, closing.
