### ISSUE TITLE
Implement "Prisoners' Chess" variant

### ISSUE THREAD

**Issue by lucrus73** [official-stockfish/Stockfish#1976]
Hello,

I'd like to fork SF in order to implement "Prisoners' Chess" variant (PC from now on), which is a FIDE chess variant I invented two years ago, and that I usually play. 

[Here is the description](https://www.chess.com/forum/view/chess960-chess-variants/prisoners-chess) of PC, which follows exactly the same rules as FIDE chess, except how the final scoring is computed.

Now I could go ahead, fork SF and try implementing my scoring rules, but I don't know SF code at all and I feel like I better ask a simple opinion from you devs beforehand: do you think implementing PC is reasonably feasable with SF? Is there a common "evaluate chessboard" function of sorts I can use as a hook to imlement PC, like it were a generic minimax algorithm?  

Thanks in advance for any support.

**Comment by lucrus73** [comment]
> What you cannot do easily is make Stockfish aware that it is playing a tournament and that it needs or doesn't needs points. By nature a chess engine only receives a position and looks for the best move, it doesn't even know it is playing a game.

Yes, I was expecting that. However I think I could work around that limitation by implementing the tournament semantics in the GUI only, and adding a UCI option in PC that sets the target score for a "good" checkmate: the rest is up to the GUI, and completely optional as far as the GUI offers the user a way to set that parameter value. Maybe it won't be very handy, but it will be at least possible to play. 

The mated_in function then strives to reach that minimum score, so mating moves that do not reach it will have a lower score than others.

Do you agree?

**Comment by ianfab** [comment]
If you just add your final score multiplied by a number larger than 128 (`MAX_PLY`) to the mate score, then via the alpha-beta search SF would implicitly aim for the mate with the biggest score in the fewest number of moves. `VALUE_NONE`, `VALUE_INFINITE` and `UCI::value` should be adjusted accordingly, so that mate detection and mate distance calculation still work properly.

**Comment by lucrus73** [comment]
@ianfab I'm not sure I fully understand your hints, but I suspect they'll become clear after I look at the code. Thanks anyway.

Another question: are there any conditions that make SF resign a game? I ask because resigning is not allowed in PC.

**Comment by ianfab** [comment]
@lucrus73 The internal score for mates is `VALUE_MATE - mate_distance_in_ply` (`-VALUE_MATE + mate_distance_in_ply` for the losing side; see `mate_in`/`mated_in`), so by maximizing the score SF aims for the shortest mate. If you change it to something like `VALUE_MATE + prisoner_score * 200 - mate_distance_in_ply`, SF should always prefer a higher prisoner score over a shorter mate, but still go for the shortest mate that achieves the maximum possible prisoner score. The values and methods I mentioned before rely on the above mate score formula, so they would need to be adjusted to not break other things.

The UCI protocol does not support resigning, neither does SF, so there should not be any issue with that.

**Comment by lucrus73** [comment]
Ok so here is [the PC fork](https://github.com/lucrus73/Prisoners-Chess), just in case anyone wants to send PRs...
Thanks for your help. I'm not closing this issue yet, because I plan to ask here if I need more help, but if you prefer I ask somewhere else just tell me and I close this.

**Comment by lucrus73** [comment]
I've noticed that `VALUE_NONE` is 32002, while `VALUE_INFINITE` is 32001. I assume `VALUE_INFINITE` should be a value greater than any possibile board value, in centipawns, and `VALUE_NONE` is just `VALUE_INFINITE+1`, right?
Assuming I'm right, in PC case, following your hints, the max mate value would be

`VALUE_MATE + max_value_prisoner_mate * (MAX_PLY + 1) - mate_distance_in_ply`

where `max_value_prisoner_mate` would be the value of a mate where the loosing player has all the starting pieces, plus all the pawns promoted to queens. Whether a player with that material can actually be mated is to prove, but here it's easier to consider a upper bound of the worst case, instead of finding the worst case itself. Maybe I could take the Fool's mate instead as a reasonable upper bound, but I prefer to play it safe for now.

So `max_value_prisoner_mate` is 1 (king) + 81 (9*9 queens) + 10 (5*2 rooks) + 6 (3*2 bishops) + 6 (3*2 knights) = 104.

In turn,  `max_value_prisoner_mate` * (MAX_PLY + 1) = 104 * 129 = 13416.

Am I safe if I add 13416 to both `VALUE_NONE` and `VALUE_INFINITE`?

**Comment by Hanamuke** [comment]
I'd say no because eval is coded on 16 bits in the transposition table. On the other hand, maybe it'd be safe to decrease VALUE_MATE. I don't have a clear solution

**Comment by lucrus73** [comment]
I see two choices here. 

1) I use Fool's mate as upper bound, so we have

`max_value_prisoner_mate` * (MAX_PLY + 1) = 33 * 129 = 4257

and maybe reducing `VALUE_MATE` by 4257 units is safer than reducing it by 13416.

2) refactor the transposition table to store 32 bits values. Is that possible at all, or are the 16 bits values enforced by the UCI protocol or anything similar?

**Comment by joergoster** [comment]
@lucrus73 This caught my interest!

Here https://github.com/joergoster/Stockfish/commits/PrisonerChess you can find my initial implementation. Most likely there are some bugs ...

Note: UCI command 'go mate x' doesn't work correctly with this version.
Not sure about 'Mate distance pruning', but there seems to be a bug. Testing a fix currently.

Please share your experiences!

**Comment by lucrus73** [comment]
@joergoster While working on my fork, I think I realized distance pruning does not make sense in PC, at least in some cases. I'm not much experienced in the algorithm, but I know that a PC game could well result in a higher score only avoiding short path checkmates that involve capturing a opponent's piece. If distance pruning is what I understand it is, i.e. an optimization that avoids looking at longer paths when you have a shorter one to checkmate, then it's not to be used in PC. But I'm not sure I understand it correctly.

In my working copy I commented out [these lines](https://github.com/official-stockfish/Stockfish/blob/3302349662f8c0b01946cd9d62ac087685c0c816/src/search.cpp#L612-L615), mostly because we can't assume our score will be lower than other mating paths.

**Comment by joergoster** [comment]
@lucrus73 I just pushed some more commits to my branch. Mate distance pruning should still work as intended, hopefully. Mates with a greater number of prisoners are scored higher than those with a smaller number of prisoners.
Please let me know any issues you're encountering.
