### ISSUE TITLE
Why is position value supposed to be 0 valued 2.7 to 3

### ISSUE THREAD

**Issue by abdulbadii** [official-stockfish/Stockfish#1977]
This is the FEN position I like to watch playing nearly hundred times on Arena gui.

kbbbnrbr/pppnnnpp/8/8/8/8/PPNNPPPP/RQ1BBRRK w - - 0 1 

Its value is about 0 or even slightly less from white point, but why is it valued about 2.7 to 3.
It's proved to be supposedly 0 value when the same 2 duplicate engine playing tournament tenth times gave 50-50, which tells nevertheless that engine decisions in further continuation is correct.
Where is the code lines that could reduce this 2.7-3 to be less toward 0 and/or be more reasonable ? great clue and useful guide will be higly appreciated.. thanks before

**Comment by joergoster** [comment]
@abdulbadii Apart from White being ahead in material, this is not a legal chess position.
Please also note, this is not the correct place to post this kind of stuff which is mainly meant to report issues with the code. Better place is the forum.
