### ISSUE TITLE
Crash when white king is missing

### ISSUE THREAD

**Issue by GSPP** [official-stockfish/Stockfish#1978]
I just incorrectly set up a position in Arena. The white king was missing. This causes Stockfish (`stockfish_19012917_x64_modern`) to crash. Is this expected behavior? Maybe a more benign error should result instead.

    6r1/5p1k/4b2P/4P1P1/8/8/8/2Q5 w - - 0 1

**Comment by ianfab** [comment]
This is expected. The GUI is responsible for not sending invalid input to the engine, because for invalid input the engine's behavior is not defined, which can include crashing.

**Comment by mcostalba** [comment]
This is not an issue, input is expected to be corrcet. Closing.
