### ISSUE TITLE
uiThread required to avoid data race?

### ISSUE THREAD

**Issue by niklasf** [official-stockfish/Stockfish#1990]
For context: I am currently [porting](https://github.com/niklasf/stockfish.wasm) Stockfish to WebAssembly, where creating pthreads, even idle ones, is very expensive. This brought my attention to `uiThread`, which (as far as I can tell) is just a dummy and only ever sleeps.

---

It was introduced in bdeda52efd55c97d0f5da908267c01f973371e5d and appears to be used only once:

https://github.com/official-stockfish/Stockfish/blob/651450023619ddea590f301f040286151004df66/src/uci.cpp#L194-L196

In particular it is not used here (**intentionally?**):
https://github.com/official-stockfish/Stockfish/blob/651450023619ddea590f301f040286151004df66/src/uci.cpp#L70

If we just need any dummy thread, can't we just use `Threads.main()` also the first time and get rid of `uiThread`?

If not, how about not actually instanciating an unsed OS thread? No worries if this is too annoying - I can easily patch this in my WASM port.

**Comment by Hanamuke** [comment]
My feeling is that you could. Maybe you could try editing the c++ code, see if it still work, and open a PR, you don't need a test on fishtest for that.

**Comment by niklasf** [comment]
Rejected PR for reference: #1995

**Comment by niklasf** [comment]
@mcostalba Can you please explain to what conclusion you came?

Should `uiThread` be removed (#1995), or is there a data race by using `Thread.main()` in `position()`, or is there a third option that I am missing?

**Comment by mcostalba** [comment]
Oooops :-)

**Comment by niklasf** [comment]
@snicolet What's the conclusion?
