### ISSUE TITLE
Is it advantageous to make a "LcFish"?

### ISSUE THREAD

**Issue by Silver-Fang** [official-stockfish/Stockfish#2012]
SF runs on CPU and Lc0 runs on GPU. Is it possible to make full use of both PUs by combining the two engines - LcFish? Or is it advantageous?

**Comment by MichaelB7** [comment]
It will be - it’s just a matter of time - for now that will be best of both worlds.   I would extend the NN move coming from the GPU in the AB search on the CPU and not reduce ( prune)  any of top 3 moves coming from NN in the AB search ( just as a starting point - but I do not know how to begin coding that - but somebody smarter than me will figure that out). We already know the GPU can talk to the A/B. I would use  the A//B CPU as the master ( makes final decision ) and the NN GPU as the slave - proivide info on best x moves to the A/B CPU engine  to extend and not prune.

**Comment by NKONSTANTAKIS** [comment]
This try seems successful, reports of outperforming other engines at Lichess.
http://talkchess.com/forum3/viewtopic.php?f=2&t=69958

**Comment by Silver-Fang** [comment]
@NKONSTANTAKIS Well this is a cooperation between processes of Lc0 and SF. It may be a valuable trial but ultimately we'll need concept-level integration. Come on, genius developers!

**Comment by ddugovic** [comment]
I wonder if you could somehow add Leela nodes to https://github.com/official-stockfish/Stockfish/tree/cluster ...

**Comment by TesseractA** [comment]
In some positions leela doesn't need to evaluate with a complicated evaluation function to put an evaluation number in the searched position. I can imagine the benefits of using a hand-written evaluation function like stockfish's for such things. There is already indeed a project that is attempting to solve the complication of having two engines running at the same time in progress, and can be found here: https://github.com/killerducky/lc0/wiki/LeelaFish

**Comment by mcostalba** [comment]
For this kind of discussion it is better to use the forum, and nyhow it seems a dead thread at this point. So closing it.
