### ISSUE TITLE
King recaptures and king danger

### ISSUE THREAD

**Issue by Alayan-stk-2** [official-stockfish/Stockfish#2016]
Someone has found this very interesting position where SF blunder massively until it reaches about depth 25-26 (which is more than what is typically reached at fishtest LTC !) : 2b2rk1/5ppp/2p3r1/p1Np4/7q/4B3/PPP1NPP1/R2Q2K1 w - -

SF wants Qd1d2, which is completely losing. The correct move is Qd1d4.

If Qd1d2, then black answers with Rxg2! ; then either the king flees (and the a1 rook is soon lost) or worse it recaptures on d2 (and then it is mate in 6 moves).

But the issue isn't limited to thinking that Rxg2 is bad because of SEE. Once put in front of the position after Rxg2, SF thinks for a significant depth that Kxg2 is completely winning : it first think that Qg4 is black's best answer (this queen check is completely losing). When it considers the correct Bh3, it still thinks for a non-negligible depth it's a draw !

Some output : 
```
info depth 12 seldepth 6 multipv 1 score cp 0 nodes 1020 nps 340000 tbhits 0 time 3 pv g1g2 c8h3 g2h2 h3g4 h2g2
info depth 13 seldepth 6 multipv 1 score cp 0 nodes 1461 nps 487000 tbhits 0 time 3 pv g1g2 c8h3 g2h2 h3g4 h2g2
info depth 14 seldepth 23 multipv 1 score cp -1080 nodes 84319 nps 2107975 tbhits 0 time 40 pv g1f1 h4h1 e2g1 h1g1 f1e2 g1a1 d2a5 c8g4 e2d3 a1b2 a5c3 b2a2 c5b3 a2a6 d3d2 g2h2 c3c5 f7f6 b3d4
```

Obviously, black's path to the win is very narrow in the Rxg2 Kxg2 line (one wrong move and white wins) but it's visually obvious that the king safety is awful. SF's evaluation _do_ understand that the king safety sucks but because it is up two knights for 2 pawns, the material advantage dominates the king safety in the overall evaluation and hence SF prunes instead of searching the line deeper.

One possible idea to improve on such positions without tanking overall performance is to do search extension/reduce pruning on lines where the position is seen as good despite a king danger lopsided against SF.

Thoughts ?

**Comment by Alayan-stk-2** [comment]
A potential idea would be to do a quiescence-like search when a side has advantage despite kingDanger above a certain value (1500 or so looks like a reasonable threshold, at least it is reached in the above example in moves following the rook sac) to make sure the king can escape the threat, but search.cpp code is quite obscure for me and using an eval term there doesn't seem trivial either.

**Comment by Alayan-stk-2** [comment]
The latest shock SF loss in the rapid no book bonus against Leela is again a demonstration of the very issue pointed out here.

A FEN showing SF's blindness : r2q1rk1/3nbppB/b2p4/3Pp1P1/pp6/4BQ1P/PPPN1P2/2KR2R1 b - -

SF blundered the previous move by allowing the Bxh7! winning sac.

Running homefish on this FEN (no TB), it thinks black is completely winning until depth 25, then at depth 26 it has a huge serie of fail lows resulting in it giving it +2.2 (winning white advantage).

Hence, on previous moves, it prunes the Bxh7 reply by white.

After Kxh7, as long as SF thinks black is winning, it predicts white's best response to be Rg1g4. It's only after significant time that it checks Qf3h5 more thoroughly and discovers it is completely winning for white.

Rg1g4 lets the pressure down, and the Bxh7 sac becomes entirely pointless. In contrast, Qf3h5 checks black's king and followed by Rg1g4 and Rg4h4 puts a tremendous pressure on SF's kingside, forcing it to counter-sac to not get mated immediately and giving white a winning endgame.

A quiescence-like search based on king danger should spot Qf3h5 instead of Rg1g4 much sooner.

**Comment by noobpwnftw** [comment]
Such problems will always be there, as long as we are pruning. Question is how often do they happen? If we are to include such "quiescence-like search", does it prove the extra effort is worthwhile overall? There is only one way to find out.

**Comment by Octavio1994** [comment]
Hello dude, I don't have such problem...
![stockfish](https://user-images.githubusercontent.com/45187526/54254265-c9e0df00-4518-11e9-967c-c5a455d515c6.png)

**Comment by Octavio1994** [comment]
Hello friend, I don't have such problem; I agree about what you say in this commit but if you want to know more intersting information please contact me.  I also made a similar commit few weeks ago and got no reply...
![54254265-c9e0df00-4518-11e9-967c-c5a455d515c6](https://user-images.githubusercontent.com/45187526/54255561-40cca680-451e-11e9-9243-50b2e0717491.png)

**Comment by MichaelB7** [comment]
On the first position, curr-dev SF does not consider Qd2 at all in single core mode with 256 MB hash( this was the 4/3/19 version):
```
dep	score	nodes	time	(not shown:  tbhits	knps	seldep)
 29	+1.66 	70.3M  	0:44.39	c3 Re8 Qa4 Qf6 Nf4 Rg4 f3 Rh4 Nxd5 Rxa4 Nxf6+ gxf6 Nxa4 Rxe3 Rd1 Kg7 Kf2 Re5 c4 Bf5 Rd6 Re6 Rd8 h5 a3 Re5 b4 h4 Nc5 h3 gxh3 Bxh3 Nd3 Rg5 Ke3 axb4 axb4 
 29	+1.58!	69.4M  	0:43.83	c3! 
 29	+1.46?	67.7M  	0:42.85	c3 Re8? 
 29	+1.61?	65.3M  	0:41.31	c3 Re8? 
 29	+1.70?	64.6M  	0:40.91	c3 Re8? 
 28	+1.79 	63.4M  	0:40.15	c3 Re8 Qa4 Qf6 Nf4 Rg4 f3 Rh4 Nxd5 Rxa4 Nxf6+ gxf6 Nxa4 Rxe3 Rd1 Kg7 Kf2 Re5 c4 Be6 b3 Bf5 Rd8 h6 Ra8 Bg6 Ra6 Re6 Rxa5 Rd6 Ra6 h5 Kg3 Rd2 Rxc6 h4+ Kh3 
 28	+1.80!	62.5M  	0:39.61	c3! 
 28	+1.58?	52.8M  	0:33.44	c3 Re8? 
 28	+1.72?	46.0M  	0:29.18	c3 Re8? 
 28	+1.82?	45.6M  	0:28.96	c3 Re8? 
 27	+1.91 	43.1M  	0:27.40	c3 Re8 Qd2 Bh3 g3 Qh5 Nd4 Bf5 Re1 Qg4 Nxf5 Qxf5 Bd4 Ra8 Nd3 Re6 Nf4 Rxe1+ Qxe1 a4 Qe7 Rb8 Ng2 Qb1+ Kh2 Qe4 Qg5 f6 Bxf6 
 27	+1.92!	39.4M  	0:25.02	c3! 
 27	+1.73!	37.6M  	0:23.89	c3! 
 27	+1.59?	36.7M  	0:23.27	c3 Re8? 
 27	+1.77!	35.8M  	0:22.73	c3! 
 26	+1.68 	31.7M  	0:20.10	c3 Re8 Qd4 Rg4 Qd2 Bf5 Re1 h5 a3 Bc8 Nd3 Ba6 Ng3 Bxd3 Qxd3 Re6 Qd1 g6 Bd4 Qe7 Rxe6 fxe6 Bb6 Rf4 Nf1 Kh7 Bxa5 c5 
 26	+1.83!	28.5M  	0:18.03	c3! 
 26	+1.71?	25.6M  	0:16.22	Qd4 Rg4? 
 26	+1.85?	24.6M  	0:15.60	Qd4 Rg4? 
 26	+1.95?	24.4M  	0:15.48	Qd4 Rg4? 
 25	+2.04 	22.2M  	0:14.07	Qd4 Qd8 Nd3 Re8 b3 Bf5 Re1 Be4 Ng3 Bxd3 cxd3 Qd7 Bd2 Rxe1+ Bxe1 Qe7 Qc3 Qg5 Bd2 Qg4 Qe5 Qd1+ Nf1 h5 Qe8+ Kh7 Qxf7 Rf6 Qe8 h4 Bxa5 
 25	+2.07!	19.1M  	0:12.16	Qd4! 
 25	+1.95?	12.1M  	0:07.67	Qd4 Qd8? 
 25	+2.09?	12.0M  	0:07.60	Qd4 Qd8? 
 25	+2.19?	11.9M  	0:07.53	Qd4 Qd8? 
 24	+2.28 	11.5M  	0:07.28	Qd4 Qd8 Qc3 Re8 Re1 h5 Nd3 Bd7 Nef4 Rg5 Bd4 Rxe1+ Qxe1 Rf5 f3 h4 b3 Qg5 Nh3 Qd8 Nc5 Bc8 Bc3 Qf8 Nd3 Rh5 Bxa5 Bxh3 gxh3 Rg5+ Kf1 Rf5 Qxh4 
 23	+2.27 	9.81M  	0:06.23	Qd4 Qd8 Qc3 Re8 Re1 h5 Nd3 Bd7 Nef4 Rg5 Bd4 Re4 f3 Rxe1+ Qxe1 Rf5 Ne2 h4 Nef4 Bc8 b3 Kh7 Qc3 Qc7 
 23	+2.14!	9.16M  	0:05.82	Qd4! 
 23	+2.02?	8.44M  	0:05.37	Qd4 Qd8? 
 23	+2.16?	8.11M  	0:05.17	Qd4 Qd8? 
 23	+2.26?	8.07M  	0:05.14	Qd4 Qd8? 
 22	+2.35 	7.79M  	0:04.97	Qd4 Qd8 Qc3 Re8 Re1 h5 Nd3 Bd7 Ne5 Rge6 Nxd7 Qxd7 Qxa5 h4 Qa4 Qd8 Qd4 Re4 Qd2 Qd7 b3 h3 Ng3 Rg4 gxh3 Rh4 
 22	+2.27!	6.68M  	0:04.27	Qd4! 
 22	+2.06?	6.18M  	0:03.95	Qd4 Qd8? 
 22	+2.34!	4.95M  	0:03.17	Qd4! 
 21	+2.15 	4.09M  	0:02.64	Qd4 Qxd4 Nxd4 Re8 Bd2 h5 Kh2 Rg4 Bc3 Rf4 f3 g5 Rd1 Rf6 Bxa5 Rg6 Re1 Rxe1 Bxe1 Kh7 Kg3 h4+ Kh2 g4 Bxh4 gxf3 
 20	+2.08 	3.90M  	0:02.52	Qd4 Qxd4 Nxd4 Re8 Bd2 h5 Kh2 Rg4 Bc3 Rh4+ Kg1 Rxd4 Bxd4 Bf5 Rc1 Re2 Nd3 h4 
 19	+1.70 	3.21M  	0:02.08	Qd4 Rg4 Qd2 Re8 f3 Rg6 Bf2 Qh6 Qxh6 Rxh6 Re1 Kf8 Nd4 Rg6 Kf1 Rxe1+ Bxe1 h5 Bxa5 h4 Bd2 h3 gxh3 Bxh3+ Ke2 
 18	+1.84 	1.67M  	0:01.10	Qd4 Rg4 Qd2 Re8 Re1 h5 c3 Qd8 f3 Rg6 Nf4 Rh6 Nfd3 Rg6 Bf2 Rxe1+ Qxe1 Rh6 Bh4 g5 Bxg5 Qxg5 Qe8+ Kg7 Qxc8 
 17	+1.96 	1.03M  	0:00.69	Qd4 Rg4 Qd2 Re8 Re1 Qd8 f3 Rg6 Bf2 Rh6 Nd4 Rxe1+ Qxe1 Qd6 Nd3 c5 Qe8+ Qf8 Qxf8+ Kxf8 Nxc5 Rb6 Nd3 Ke8 
 16	+1.91 	764157	0:00.51	Qd4 Rg4 Qd2 Qf6 Bd4 Qd8 Re1 Re8 c3 h5 f3 Qg5 Qxg5 Rxg5 Kf2 h4 Be3 Rg6 Nf4 
 15	+2.00 	362087	0:00.25	Qd4 Qg4 Qxg4 Bxg4 Nd4 Rb8 b3 h5 Kh2 Re8 Bd2 Bc8 Rd1 h4 Bxa5 
 14	+1.87 	201756	0:00.14	Qd4 Qd8 Re1 Re8 Qd2 Qb6 Ng3 Qd8 Bd4 Rxe1+ Qxe1 h5 Bc3 h4 
 13	+1.75 	70837  	0:00.05	Qd4 Qd8 Re1 Bg4 Ng3 Re8 b3 Bc8 Qd3 h6 Qc3 Re7 Nd3 
 12	+1.81 	32161  	0:00.02	Qd4 Qg4 Qxg4 Bxg4 Nd4 h6 b3 Rb8 Bd2 Re8 
 11	+1.62 	25023  	0:00.02	Qd4 Qxd4 Nxd4 Bh3 g3 Rb8 b3 Bc8 Re1 
 10	+1.47 	14883  	0:00.01	Qd4 Qxd4 Nxd4 Bh3 g3 Re8 Kh2 Bc8 Rh1 Bg4 b3 
  9	+1.64 	11485  	0:00.01	g3 Re8 Qd2 Qc4 Re1 Qxa2 b3 Qa3 Nf4 
  8	+2.00 	3519    	0:00.00	g3 Re8 Qe1 Bf5 Qxa5 Bxc2 Nf4 
  7	+2.19 	1520    	0:00.00	g3 Re8 Nf4 Rg4 Kg2 
  6	+1.86 	691      	0:00.00	Qd4 Qxd4 Bxd4 Rd8 Rd1 Bh3 
  5	+3.56 	301      	0:00.00	Nf4 a4 
  4	+2.26 	193      	0:00.00	Nf4 a4 Nxg6 fxg6 
  3	+2.26 	133      	0:00.00	Nf4 a4 Nxg6 fxg6 
  2	+2.76 	84        	0:00.00	Nf4 a4 Nxg6 hxg6 
  1	+1.04 	40        	0:00.00	Nf4 
  0	# 
```
Something else might be going on - this is the second position I have seen today where current-dev-SF handles correctly , but somebody is claiming that dev-SF misplayed it - maybe some bad dev versions exe's were available for download.

**Comment by Alayan-stk-2** [comment]
Latest SF does better in this position, it has trouble in others similar situations (see the fastest losses to SF7 at NCM, it's basically one-move blunder missing some sacrificial attack on the king). It's not because april SFdev doesn't encounter the issue here that february SFdev didn't...

And really, it's almost sheer luck that Qd2 isn't the first consideration anymore.

With multiPV=10 and default Hash, Qd2 is 3rd move at depth 26 and 6th move at depth 27 :

```
info depth 26 seldepth 39 multipv 1 score cp 219 nodes 214769488 nps 1997465 hashfull 1000 tbhits 0 time 107521 pv d1d4 g6g4 d4d2 h4f6 c5d3 c8f5 a1e1 f5d3 c2d3 h7h5 d2a5 f6b2 a5c7 d5d4 e3c1 b2a2 e2f4 a2b1 c7e5 b1b4 f4h5 g4g6 h5f4 g6h6 f2f3 b4c3 g2g3 h6h7 e5e8 c6c5 f4d5
info depth 26 seldepth 39 multipv 2 score cp 205 nodes 214769488 nps 1997465 hashfull 1000 tbhits 0 time 107521 pv a1c1 f8e8 d1d4 g6g4 d4d2 h7h5 c2c3 h4f6 c1e1 h5h4 e2d4 g4g6 g1h1 c8g4 c5d3 a5a4 f2f3 g4f5 d3f4 g6h6 d4f5 f6f5 f4h3 h6h5 e3d4 e8e1 d2e1 h5h8 e1e8 g8h7 e8c6
info depth 26 seldepth 42 multipv 3 score cp 198 nodes 214769488 nps 1997465 hashfull 1000 tbhits 0 time 107521 pv d1d2 h4g4 g2g3 f8e8 a1e1 c8f5 e2d4 h7h5 d2e2 g4h3 e2f3 f5c8 c5d3 c6c5 d3f4 h3g4 f3g4 g6g4 d4c6 c8d7 c6a5 d5d4 e3d2 e8e1 d2e1 h5h4 f4d3 d7f5 a5c6 f5d3 c2d3
```

 
```
info depth 27 seldepth 44 multipv 1 score cp 207 nodes 261559130 nps 2001860 hashfull 1000 tbhits 0 time 130658 pv c2c3 f8e8 d1a4 h4f6 a1e1 h7h6 c5d3 c8a6 a4d1 g6g2 g1g2 f6g6 e2g3 a6d3 g2h2 e8e5 e3d4 e5g5 e1e3 d3b1 d1f1 g8h7 e3e1 b1a2 f1h3 h7g8 e1e8 g8h7 h3h4 g5g4
info depth 27 seldepth 42 multipv 2 score cp 205 nodes 261559130 nps 2001860 hashfull 1000 tbhits 0 time 130658 pv d1d4 g6g4 d4d2 h4f6 c5d3 c8f5 a1e1 f5d3 c2d3 h7h5 d2a5 f6b2 e2f4 h5h4 a5c7 b2b4 e1f1 b4b8 c7b8 f8b8 g1h2 b8b4 d3d4 g7g5 f4d3 b4d4 d3e5 d4a4 e5g4 a4g4
info depth 27 seldepth 37 multipv 3 score cp 200 nodes 261559130 nps 2001860 hashfull 1000 tbhits 0 time 130658 pv a1c1 f8e8 d1d4 g6g4 d4d2 h7h5 c2c3 h4f6 c1e1 h5h4 e2d4 e8e7 c5d3 c8d7 f2f3 g4g6 g1h1 d7f5 d4f5 f6f5 h1h2 e7e8 e1g1 e8e7 e3f4 f5f6 d3c5 f6f5 g1h1 e7e8 a2a3 a5a4
info depth 27 seldepth 44 multipv 4 score cp 194 nodes 261559130 nps 2001860 hashfull 1000 tbhits 0 time 130658 pv a1b1 f8e8 d1d2 c8f5 b1e1 h7h6 e2f4 g6g4 g2g3 h6h5 f4g2 h4d8 e3f4 e8e1 d2e1 d5d4 c5b7 d8d7 e1a5 f5c2 a5a8 g8h7 f2f3 g4g6 g2h4 d7d5 h4g6 c2g6 g1g2 d4d3 a8e8 d5a2
info depth 27 seldepth 40 multipv 5 score cp 192 nodes 261559130 nps 2001860 hashfull 1000 tbhits 0 time 130658 pv b2b3 f8e8 d1d4 g6g4 d4d2 h4f6 c2c3 f6f5 a1e1 h7h5 e2d4 f5f6 c5d3 c8a6 f2f3 g4g6 d3f4 g6g5 f4h3 g5e5 a2a4 c6c5 d4c2 c5c4 h3f4 f6f5 c2d4 f5f6 b3c4 a6c4
info depth 27 seldepth 39 multipv 6 score cp 192 nodes 261559130 nps 2001860 hashfull 1000 tbhits 0 time 130658 pv d1d2 h4g4 g2g3 f8e8 a1e1 c8f5 e2d4 h7h5 d2e2 g4h3 e2f3 g6f6 f3g2 h3g4 e1e2 f5e4 c5e4 d5e4 e2d2 e8b8 b2b3 c6c5 d4e2 f6f5 e2f4 h5h4 g2e4 h4g3 f2f3 g4g5
```
It clearly isn't spotting how awful Qd2 is at this depth.

On clear hash and after Qd2 is played, it switches from thinking black is losing to black is completely winning at depth 25.
