### ISSUE TITLE
Possible bug introduced by 76d2f5b94a0df20d84ccf

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#2019]
See https://github.com/official-stockfish/Stockfish/commit/76d2f5b94a0df20d84ccf922bd1c0fcf1c779090

**Comment by vondele** [comment]
confirmed, I'm testing some fixes.

**Comment by joergoster** [comment]
See also https://github.com/vondele/Stockfish/commit/4c9a684ec8430d711643646684699d3d46eb28a9

**Comment by mcostalba** [comment]
@vondele Thanks! While you are working on it I will revert. Please feel free to test against the new master.

**Comment by vondele** [comment]
can be closed now 

(as can several other issues IMO).
