### ISSUE TITLE
Shrink Reductions[] array to one dimension, different bench numbers  at a depth 25 and above

### ISSUE THREAD

**Issue by JavaMast** [official-stockfish/Stockfish#2032]
This commit has different bench compared to previous one (Pawn value tweak)

**bench 16 1 25**

![screenshot_136](https://user-images.githubusercontent.com/42765009/53829897-419b9080-3f92-11e9-9b66-50ea7123e266.png)

**bench 16 1 30**

![screenshot_137](https://user-images.githubusercontent.com/42765009/53829911-4eb87f80-3f92-11e9-9b8f-93e1ac95efa1.png)

**Comment by VoyagerOne** [comment]
Nice catch

**Comment by mcostalba** [comment]
Thanks! A standard bench did not caught it! Then we should run a STC[-3, 1] to validate the patch.

**Comment by Vizvezdenec** [comment]
@mcostalba I think that you mean LTC? Because it already passed STC.
I think that because it has effect on higher depth even [-3;1] SPRT on 120+1.2 should be a thing (because we don't hit depth 25 often at LTC either).

**Comment by MichaelB7** [comment]
Based on where the difference occur ( depth greater than 24)  the current testing parameters of LTC and STC are inadequate.  Perhaps multi-threaded testing ( to reach the desired depths more quickly)  here will be more appropriate.

**Comment by JavaMast** [comment]
**AMD Ryzen 7 1700X @3.6 GHz, Win 10 Pro x64
CuteChess 1.0, RR, 1 thread, concurrency 8
TC: 25 plies per move, hash 128 MB, book: test1.pgn**  

  PLAYER                                :  RATING  ERROR  PLAYED   (%)    W    D    L  D(%)  CFS(%)
   1 stockfish_050319_x64_modern_shrink    :    3208      6     706  52.2  107  523   76  74.1      99
   2 stockfish_050319_x64_modern               :    3192      6     706  47.8   76  523  107  74.1     ---

White advantage = 57.68 +/- 6.23
Draw rate (equal opponents) = 78.90 % +/- 1.75

**PGN:** 
[Results.zip](https://github.com/official-stockfish/Stockfish/files/2937242/Results.zip)

**Comment by protonspring** [comment]
If someone could please tell me what kind of test to set up I'd be glad to do it.

**Comment by vondele** [comment]
this can be closed IMO. No adverse effects of the patch has been seen, and the effect is minimal
