### ISSUE TITLE
Additional syzygy warnings with Intel compiler

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#204]
Inter compiler under Linux gives following warnings:

icpc -Wall -Wcast-qual -fno-exceptions -fno-rtti  -diag-disable 11,1476,10120 -Wcheck -Wabi -Wdeprecated -strict-ansi -I/usr/include/x86_64-linux-gnu/c++/4.8/ -g -fast -DIS_64BIT -msse -DUSE_BSFQ -msse3 -DUSE_POPCNT   -c -o syzygy/tbprobe.o syzygy/tbprobe.cpp
In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(223): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      entry->num += pcs[i];
                 ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(231): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->pawns[0] = pcs[TB_WPAWN];
                    ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(232): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->pawns[1] = pcs[TB_BPAWN];
                    ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(235): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
        ptr->pawns[0] = pcs[TB_BPAWN];
                      ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(236): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
        ptr->pawns[1] = pcs[TB_WPAWN];
                      ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(248): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
          ptr->enc_type = 1 + j;
                        ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(838): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      norm[0] = ptr->enc_type - 1;
              ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(868): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->pieces[0][i] = data[i + 1] & 0x0f;
                        ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(874): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->pieces[1][i] = data[i + 1] >> 4;
                        ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(886): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->pieces[i] = data[i + 1] & 0x0f;
                     ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(901): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->file[f].pieces[0][i] = data[i + j] & 0x0f;
                                ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(908): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->file[f].pieces[1][i] = data[i + j] >> 4;
                                ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(922): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      ptr->file[f].pieces[i] = data[i + j] & 0x0f;
                             ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(939): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      d->symlen[s] = d->symlen[s1] + d->symlen[s2] + 1;
                   ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(945): warning #2259: non-pointer conversion from "int" to "ushort={unsigned short}" may lose significant bits
    return d[0] | (d[1] << 8);
           ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(1231): warning #2259: non-pointer conversion from "int" to "ubyte={unsigned char}" may lose significant bits
      return d->min_len;
             ^

In file included from syzygy/tbprobe.cpp(21):
syzygy/tbcore.cpp(1241): warning #2259: non-pointer conversion from "int" to "ushort={unsigned short}" may lose significant bits
      idxOffset = (idxOffset << 8) | (idxOffset >> 8);

Compiler:
$ icc -v
icc version 14.0.1 (gcc version 4.8.0 compatibility)

Make command:
make build debug=yes optimize=yes ARCH=x86-64-modern COMP=icc

**Comment by zamar** [comment]
Just make an explicit cast... Should be very straightforward to fix.

**Comment by zamar** [comment]
Marco, do you want to post a patch for this?

I know that you dislike syzygy, but you have the compiler, you see the error messages, and it cannot take more than 15 minutes to put the explicit casts in place.

**Comment by mcostalba** [comment]
I have open a pull request:

https://github.com/official-stockfish/Stockfish/pull/215

**Comment by mcostalba** [comment]
Pull request applied. Issued closed.
