### ISSUE TITLE
Build issue with mingw since PR #2035

### ISSUE THREAD

**Issue by ElbertoOne** [official-stockfish/Stockfish#2044]
Hi, I'm building my SF with the following command:
`make profile-build ARCH=x86-64-modern COMP=mingw`

Until today this worked flawlessly, but since PR #2035 is merged the build fails with the following message:
_make[2]: *** No rule to make target `thread_win32.h', needed by `evaluate.o'.  Stop._

Any idea on how this could be remedied?

**Comment by ElbertoOne** [comment]
I found the remedy: I had my .depend file still with the old settings.

**Comment by mcostalba** [comment]
make clean
