### ISSUE TITLE
Regression cause for concern?

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2050]
So the latest regression test showed that we might have lost around 1 elo since the previous regression test, despite having had a few elo gaining patches (along with lots of simplifications). Is this cause for concern? I was thinking, since it's become increasingly difficult for elo gaining patches, or even just simplifications to come by, would it be a good idea to run a regression test before committing each patch so we can be sure it doesn't cause regression?
Please ignore this idea if it's really stupid. I'm just someone who's been following stockfish's development and never actually contributed (not a programmer sadly), so I might just be spouting nonsense here.

**Comment by Vizvezdenec** [comment]
regression tests have error bars of 1.8, 1 elo is nothing.
If you dig into history of them you will see multiple occasions of RT showing less than before. I just updated info btw. https://github.com/glinscott/fishtest/wiki/Regression-Tests

**Comment by mcostalba** [comment]
as @Vizvezdenec explained very well, regression test cannot be used to verify SPRT outcome. The fact that from time to time SF regresses a bit or at least does not advance is unfortunate, but it is a side effect of accepting patches with a possibly very small gain (below 1 ELO), and is also an effect of simplifications that by their nature could lead to some non completely neutral result. But in the long term these effects are usually overcome, so I am not particularly concerned.
