### ISSUE TITLE
macOS: llvm-profdata: command not found

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#2053]
We have an error below under macOS when using "profile-build":

```
Step 3/4. Building optimized executable ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make ARCH=x86-64 COMP=clang objclean
/Applications/Xcode.app/Contents/Developer/usr/bin/make ARCH=x86-64 COMP=clang clang-profile-use
llvm-profdata merge -output=stockfish.profdata *.profraw
/bin/sh: llvm-profdata: command not found
make[1]: *** [clang-profile-use] Error 127
make: *** [profile-build] Error 2 
```

So just checking:

```
MacBook-Pro:~ dew$ llvm-profdata
-bash: llvm-profdata: command not found
```

Cause under modern macOS we should to use "xcrun llvm-profdata [args]":

```
MacBook-Pro:~ dew$ xcrun llvm-profdata
llvm-profdata: No command specified!
USAGE: llvm-profdata <merge|show> [args...]
```

**Comment by MichaelB7** [comment]
For me this, this appeared recently ( last month or two) after a macOS update when using clang - I just added this to my ".bash_profile" to get around it .  You may need to tailor it to  the specific version of llmv you are using.
```
alias llvm-profdata="llvm-profdata-mp-7.0"
```
I use the clang version from MacPorts, not the apple provided version.  gcc 8.0 from MAcPorts works fine without issue and provides faster complies. Your mileage may vary.

**Comment by d3vv** [comment]
@MichaelB7 Thank You in Advance but if I can run fishtest on macOS then I know all tricks for that
I just want that sf and sftest will be more friendly for macOS users
Most of macOS users can't run fishtest and compile sf due to a lot of troubles and poor support
As for SF - my suggestion is solving compile issues
As for fishtest - I don't understand why we don't have cutechess-cli binaries for auto download by worker.py?
We do not needed QT and macports, brew and etc... All we need that developers to compile cutechess-cli with [ https://github.com/nesbox/qt5-static-mac ] and deploy to us binaries..

**Comment by MichaelB7** [comment]
Ok - in general , it’s a shame there is not equal amount of support for chess on Macs as there is for Windows , since the current Mac hardware is very good.  Let me know if I can ever help you with macOS issues. Last time I try to run fishtest , I was able to - will try again later tonight.

**Comment by d3vv** [comment]
@MichaelB7 I don't post only issues last time... I post solutions...
As for SF - I'm sure Xcode it is an easy way to install for users and developers against macports and homebrew solutions.. As for Xcode I have an alias like "alias llvm-profdata=xcrun llvm-profdata" into my .profile
Just need an easy way for macOS users to fishtest w/o any troubles..

**Comment by d3vv** [comment]
I mean to use "xcrun llvm-profdata" into Makefile if we have Darwin-kernel and clang (default for macOS at now days)

**Comment by d3vv** [comment]
as for cutechess-cli (I know it is for fishtest repo) but have a look how it compiled with standalone binaries with qt5-static and w/o qt5 libs:
[cutechess-cli.zip](https://github.com/official-stockfish/Stockfish/files/2989968/cutechess-cli.zip)

```
MacBook-Pro:testing dew$ otool -L cutechess-cli
cutechess-cli:
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1560.12.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 934.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1671.10.106)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.220.15)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by MichaelB7** [comment]
If I remember correctly, fishtest does not use profile builds.

**Comment by d3vv** [comment]
@MichaelB7 Come on you know:

```
MacBook-Pro:~ dew$ cat fishtest/worker/custom_make.txt 
make profile-build ARCH=x86-64 COMP=clang
```

**Comment by MichaelB7** [comment]
Curiously, I do not have this issue at on my iMac. Makefile is fine as is.  An do I know this used to work fine on my MacPro - I don't belief the issue we are both seeing is any fault of the makefile.   I believe this issue can be closed.

**Comment by d3vv** [comment]
Come on, macOS has no lvm-profdata into a path. Just show your "which lvm-profdata" to us, please.
Moreover xcoded solutions are easy for most users and recommended by Apple, against macports, homebrews/handmade and etc.

**Comment by MichaelB7** [comment]
iMac-3:src $ which llvm-profdata
/opt/local/bin/llvm-profdata
iMac-3:src $

**Comment by d3vv** [comment]
@MichaelB7 you have a "handmade" llvm-profdata which has nothing to do with system/apple clang.. It is just an alien binary from different versa which has conflicts with default clang in most cases..
My suggestion is to check:
if 'xcrun' is present
  then use 'xcrun llvm-profdata'
  else try run just 'llvm-profdata' and prey that it present into the path

**Comment by d3vv** [comment]
Just remark:
macOS has no llvm-profdata into the path cause it can use various toolchains
and xrun just start  llvm-profdata from current selected toolchain for use at a moment

**Comment by d3vv** [comment]
So if i have a macport clang, but using an apple clang by default and llvm-profdata/other tools from macports into a path - it produced bogus binaries.. xrun it is logical and right solution from apple in that case as well..

**Comment by d3vv** [comment]
If you are a real developer then you understand that xrun used tools from your selected compile-profile:
stable-xcode or curent/devel instance or lecacy xcode toolchain for compatibility reasons..

**Comment by d3vv** [comment]
> Curiously, I do not have this issue at on my iMac. Makefile is fine as is. An do I know this used to work fine on my MacPro - I don't belief the issue we are both seeing is any fault of the makefile. I believe this issue can be closed.

- Doctor, my leg hurts!
- Sick, what are you coming up with! I have the same leg, and it does not hurt!

**Comment by d3vv** [comment]
Moreover we can't to use "alias llvm-profdata="xcrun llvm-profdata" into .profile for Makefile for modern macOS due to "security by security" reason.. For workaround I used:
```
MacBook-Pro:~ dew$ which llvm-profdata
/usr/local/bin/llvm-profdata
MacBook-Pro:~ dew$ cat /usr/local/bin/llvm-profdata
#!/bin/sh

xcrun llvm-profdata $@
```

**Comment by d3vv** [comment]
I don't need a help - I just want stockfish will be friendly for a friendly "Another World" OS users
Just for sure, if stockfish will be more friendly then we will see more workers at fishtest
