### ISSUE TITLE
This MCTS Thing

### ISSUE THREAD

**Issue by VezirChess** [official-stockfish/Stockfish#2071]
Can't you do something for Monte-Carlo Tree Search? Because it is going to be really popular.
Komodo and some open source chess engines did it.( like https://github.com/amchess/ShashChess and  https://github.com/dshawul/Scorpio ) I think it will improve Stockfish's Playing strength.
Best Regards...
Ahmet Burak Gürsu

**Comment by mcostalba** [comment]
Thankfsfor your comment. The change you suggest is equivalent to write a new engine, so eventually the best approach for interested people (with a lot of time and energy) is to fork SF and move on from there.
