### ISSUE TITLE
Why can't we compile a list of bad positions manually?

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2084]
From watching Leela vs SF it seems that there are some positions that SF are completely blind to, and numerous patch attempts have failed to address them. What's stopping us from simply compiling a list of such positions and then tell SF to not go into those positions? I know there are lots and lots of possible positions, but surely having such a list of positions in the early to mid game that can come out of some common openings (Catalan, French for example, both of which SF is not very good at, at least compared to Leela) would be beneficial. Sorry if it's a stupid idea.

**Comment by Spill-The-Tea** [comment]
It is not a dumb idea, but it is incomplete. Leela isn't the only chess engine stockfish loses to. It's just the most publicized. That said, many have done this work, or are currently doing so now. This is what epd testsuites were designed for: to find positions that chess engines struggle with. But as programs become stronger, previously designed test suites become less relevant, which means test suites also need to evolve. This takes time, but for general information, see the chess programming wiki, regarding test positions, found [here](https://www.chessprogramming.org/Test-Positions). 

There are several people who are currently active in this pursuit. Including most notably:
1.  Johnathan Dart's [Arasan Test suite](https://arasanchess.org/testsuite.shtml).
2. Vincent Lejeune's (AKA @Vinvin), "[Hard](http://www.talkchess.com/forum3/viewtopic.php?t=64914#p727861)" Testsuite, found in talkchess forums.
3. Walter Eigenmann's [ERET Suite](https://glarean-magazin.ch/2017/03/05/computerschach-testaufgaben-engines-eigenmann-rapid-engine-test-eret/)
4. @dorszcz, in the Rybka Lounge, has been very active in this venture also, with positions found throughout several posts, [here](http://rybkaforum.net/cgi-bin/rybkaforum/board_show.pl?tid=32835#tid32835). 
5. Ten positions taken from AlphaZero Games (against SF8), in this talkchess thread, [here](http://www.talkchess.com/forum3/viewtopic.php?f=2&t=66184).

**Comment by Alayan-stk-2** [comment]
Besides won/lost positions which SF misevaluates, it would be useful to compile a list of forced draw positions with a rather high eval at depth (> 3 for one side)

Game analyses usually focus on SF losses, but missed wins because of a misunderstood drawing pattern are relevant too.
