### ISSUE TITLE
MultiPV broken on latest master

### ISSUE THREAD

**Issue by nmrugg** [official-stockfish/Stockfish#2092]
Using the latest master, Stockfish hangs under certain circumstances when `MultiPV` > 1.

I've tried to track down the problem, but it seems to be spread across a number of commits.

For example, as of 5b5687d76e7dc10af9ebaa91f03190db9a9f8d27, the following will cause Stockfish to hang:

```
setoption name MultiPV value 3
position fen 3qq3/5P2/2k5/2P5/8/5K1Q/8/3Q4 b - - 0 58
go depth 13
```

I have found other sets commands that cause Stockfish to hang as well.

The primary offender seems to be 76f1807baa90eb69f66001d25df2a28533f9406f, specifically https://github.com/official-stockfish/Stockfish/commit/76f1807baa90eb69f66001d25df2a28533f9406f#diff-71c8faa29f847041392f6e81e16bd9e6R933.  Reverting that commit fixes the above issue; however, that commit may not be the only problem.

0f63b35120e79fe6cc76abdd293d58243ccdbacb also causes problems because in multipv mode, `ss->staticEval` does not always equal `pureStaticEval`. Reverting that commit fixes some issues with hanging as well.

Furthermore, in my experiments, I found that reverting badb2aca44d6507f35dafc8b5c3921a6649a40f8, e51244cb27151075ac7a05282d0ec615cf93f290, and 22ef36803ed0f1597d8f40731c6e2d3aa01debf2 also seemed to prevent hanging, at least in certain positions.

**Comment by joergoster** [comment]
It's still responding to the 'stop' command immediately. So not a real hang, but more like in an endless loop or something. Further investigation needed.
Output implies it's still calculating PV line 3 at depth 13 ...

> go depth 13
> info depth 1 seldepth 2 multipv 1 score cp 1172 nodes 996 nps 498000 tbhits 0 time 2 pv d8d1 f3g2 d1d5 g2g3 e8f7
> info depth 1 seldepth 2 multipv 2 score cp 1153 nodes 996 nps 498000 tbhits 0 time 2 pv e8f7 f3g2 d8d1
> info depth 1 seldepth 2 multipv 3 score cp -69 nodes 996 nps 498000 tbhits 0 time 2 pv d8f6 f3g2 e8f7
> info depth 2 seldepth 4 multipv 1 score cp 1189 nodes 1614 nps 538000 tbhits 0 time 3 pv d8d1 f3g2 d1d5 g2g3 e8e3 g3g4 e3c5
> info depth 2 seldepth 3 multipv 2 score cp 1153 nodes 1614 nps 538000 tbhits 0 time 3 pv e8f7 f3g2 d8d1
> info depth 2 seldepth 3 multipv 3 score cp -140 nodes 1614 nps 538000 tbhits 0 time 3 pv d8f6 f3g2 f6f7 d1d6 c6b7
> info depth 3 seldepth 6 multipv 1 score cp 1215 nodes 2593 nps 864333 tbhits 0 time 3 pv d8d1 f3g3 e8f7 h3g2 c6c5
> info depth 3 seldepth 5 multipv 2 score cp 1215 nodes 2593 nps 864333 tbhits 0 time 3 pv e8f7 f3g3 d8d1 h3g2 c6c5
> info depth 3 seldepth 5 multipv 3 score cp -212 nodes 2593 nps 864333 tbhits 0 time 3 pv d8f6 f3g2 f6f7 d1d6 c6b7 d6b6 b7a8
> info depth 4 seldepth 8 multipv 1 score cp 1245 nodes 4073 nps 1018250 tbhits 0 time 4 pv d8d1 f3g2 d1d5 g2g1 d5c5 g1g2 c5c2 g2g3 c2g6 g3h2
> info depth 4 seldepth 5 multipv 2 score cp 1147 nodes 4073 nps 1018250 tbhits 0 time 4 pv e8f7 f3g2 d8d1 h3e3 d1b3
> info depth 4 seldepth 7 multipv 3 score cp -275 nodes 4073 nps 1018250 tbhits 0 time 4 pv d8f6 f3g2 f6f7 d1d6 c6b5 d6b6 b5a4
> info depth 5 seldepth 10 multipv 1 score cp 1281 nodes 5019 nps 1254750 tbhits 0 time 4 pv d8d1 f3g2 d1d5 g2g1
> info depth 5 seldepth 6 multipv 2 score cp 1180 nodes 5019 nps 1254750 tbhits 0 time 4 pv e8f7 f3g2 d8d1 h3c8 f7c7
> info depth 5 seldepth 8 multipv 3 score cp -7 nodes 5019 nps 1254750 tbhits 0 time 4 pv d8f6 f3g2 f6g6 g2f1 e8f7 f1e1
> info depth 6 seldepth 12 multipv 1 score cp 1292 nodes 9485 nps 1355000 tbhits 0 time 7 pv d8d1 f3g2 d1d5 g2g1 d5c5 g1g2
> info depth 6 seldepth 9 multipv 2 score cp 1213 nodes 9485 nps 1355000 tbhits 0 time 7 pv e8f7 f3g2 d8d1 h3c8 c6b5
> info depth 6 seldepth 11 multipv 3 score cp -32 nodes 9485 nps 1355000 tbhits 0 time 7 pv d8f6 f3g2 f6g6 h3g3 e8f7 d1d6 g6d6 g3d6 c6b5 d6d3 b5c5
> info depth 7 seldepth 12 multipv 1 score cp 2359 nodes 11990 nps 1498750 tbhits 0 time 8 pv d8d1 f3g3 e8f7 h3c8 f7c7 g3h3
> info depth 7 seldepth 11 multipv 2 score cp 1247 nodes 11990 nps 1498750 tbhits 0 time 8 pv e8f7 f3g2 d8d1 h3c8 c6b5 c8b8 b5c5
> info depth 7 seldepth 12 multipv 3 score cp -37 nodes 11990 nps 1498750 tbhits 0 time 8 pv d8f6 f3g2 f6g6 h3g3 e8e4 g2h2 g6f7 d1d2 c6b5 g3b8 b5a4
> info depth 8 seldepth 14 multipv 1 score mate 6 nodes 27439 nps 1614058 tbhits 0 time 17 pv d8d1 f3f4 d1c1 f4g4 e8c8 g4h4 c1f4 h4h5 c8h3 h5g6
> info depth 8 seldepth 12 multipv 2 score cp 1281 nodes 27439 nps 1614058 tbhits 0 time 17 pv e8f7 f3g2 d8d1 h3c8 c6b5 c8b8 b5c5 b8c8 c5b6
> info depth 8 seldepth 14 multipv 3 score cp -22 nodes 27439 nps 1614058 tbhits 0 time 17 pv d8f6 f3g2 f6g6 h3g3 e8e4 g2h2 g6f7 d1d2 c6b5 d2b2 b5a5
> info depth 9 seldepth 12 multipv 1 score mate 5 nodes 39317 nps 1709434 tbhits 0 time 23 pv d8d1 f3f4 d1c1 f4g4 e8e6 g4h4 c1f4 h4h5 e6f7
> info depth 9 seldepth 15 multipv 2 score cp 5912 nodes 39317 nps 1709434 tbhits 0 time 23 pv e8f7 f3g2 d8d1 h3c8 c6b5 c8b8 b5c5
> info depth 9 seldepth 16 multipv 3 score cp 3 nodes 39317 nps 1709434 tbhits 0 time 23 pv d8f6 f3g2 f6g6 h3g3 e8e4 d1f3 e4f3 g2f3 g6f7 f3g2 f7e7 g3d3 e7g5 g2h2
> info depth 10 seldepth 10 multipv 1 score mate 5 nodes 153952 nps 1655397 tbhits 0 time 93 pv d8d1 f3f4 d1c1 f4g4 e8e6 g4h4 c1f4 h4h5 e6f7
> info depth 10 seldepth 24 multipv 2 score cp 5898 nodes 153952 nps 1655397 tbhits 0 time 93 pv e8f7 f3g2 d8d1 h3h6 c6b5 h6b6 b5a4 b6c6 a4b4 c6e4 b4c5 e4e3 c5c4 g2g3 d1d5
> info depth 10 seldepth 25 multipv 3 score cp -19 nodes 153952 nps 1655397 tbhits 0 time 93 pv d8f6 f3g2 f6g6 h3g3 e8f7 d1d6 g6d6 g3d6 c6b5 c5c6 f7c4 g2f2 c4c6
> info depth 11 seldepth 10 multipv 1 score mate 5 nodes 402924 nps 1736741 tbhits 0 time 232 pv d8d1 f3f4 d1c1 f4g4 e8e6 g4h4 c1f4 h4h5 e6f7
> info depth 11 seldepth 32 multipv 2 score cp 5924 nodes 402924 nps 1736741 tbhits 0 time 232 pv e8f7 f3g2 d8d1 h3h6 c6b5 h6b6 b5a4 b6c6 a4b4 c6b6 b4a3 b6a6 a3b2 a6b6 d1b3 b6d8 f7g6 g2f1
> info depth 11 seldepth 29 multipv 3 score cp -1331 nodes 402924 nps 1736741 tbhits 0 time 232 pv d8f6 f3g2 f6g6 g2h1 e8f7 h3c8 c6b5 d1e2 b5b4 c8b8 b4c3 e2e3 g6d3 b8h8 c3c4 h8h4 c4b3 e3d3 b3b2 h4d4 b2a2
> info depth 12 seldepth 10 multipv 1 score mate 5 nodes 980668 nps 1153727 tbhits 0 time 850 pv d8d1 f3f4 d1c1 f4g4 e8e6 g4h4 c1f4 h4h5 e6f7
> info depth 12 seldepth 106 multipv 2 score cp 5916 nodes 980668 nps 1153727 tbhits 0 time 850 pv e8f7 f3e3 d8d1 h3c8 c6b5 c8b8 b5c5 b8c8 c5b4 c8b8 b4a3 b8a8 a3b2 a8h8 b2c1 h8c3 d1c2 c3c2 c1c2
> info depth 12 seldepth 24 multipv 3 score cp -1273 nodes 980668 nps 1153727 tbhits 0 time 850 pv d8f6 f3g2 f6g5 g2h1 e8e4 h3f3 g5h5 h1g2 h5g4 g2f2 g4h4 f2g1 c6b5 f3e4 h4e4 d1d7 b5b4 f7f8q
> stop
> info depth 13 seldepth 10 multipv 1 score mate 5 nodes 218307174 nps 873417 hashfull 1000 tbhits 0 time 249946 pv d8d1 f3f4 d1c1 f4g4 e8e6 g4h4 c1f4 h4h5 e6f7
> info depth 13 seldepth 22 multipv 2 score cp 2094 nodes 218307174 nps 873417 hashfull 1000 tbhits 0 time 249946 pv e8f7 f3e2
> info depth 12 seldepth 24 multipv 3 score cp -1273 nodes 218307174 nps 873417 hashfull 1000 tbhits 0 time 249946 pv d8f6 f3g2 f6g5 g2h1 e8e4 h3f3 g5h5 h1g2 h5g4 g2f2 g4h4 f2g1 c6b5 f3e4 h4e4 d1d7 b5b4 f7f8q
> bestmove d8d1 ponder f3f4

**Comment by MichaelB7** [comment]
hmmm ...looks like we should consider doing some type of MutliPV sanitization procedures on every patch to to ensure MutliPv bugs are not introduced...  it goes into "no man's land" (endless loop) , if you do "go movetime 20000", you wills see nps drop way from down.  Good catch btw.

**Comment by mcostalba** [comment]
@nmrugg maybe is a duplicate of https://github.com/official-stockfish/Stockfish/issues/2091

I have pushed a fixed, please could you check the new master?

**Comment by joergoster** [comment]
@mcostalba Seems to be fixed.

> info depth 13 seldepth 10 multipv 1 score mate 5 nodes 921068 nps 1798960 tbhits 0 time 512 pv d8d1 f3f4 d1c1 f4g4 e8e6 g4h4 c1f4 h4h5 e6f7
> info depth 13 seldepth 24 multipv 2 score cp 5940 nodes 921068 nps 1798960 tbhits 0 time 512 pv e8f7 f3e4 d8d1 h3c8 c6b5 c8b8 b5c5 b8c8 c5b6 c8b8 f7b7 b8b7 b6b7 e4f5 b7c6 f5e5 d1d5 e5f4 d5d4 f4g5 c6d6
> info depth 13 seldepth 23 multipv 3 score cp -1308 nodes 921068 nps 1798960 tbhits 0 time 512 pv d8f6 f3g2 f6b2 g2h1 e8f7 h3c8 c6b5 c8b8 b5a5 b8b2 f7h7 h1g1
> bestmove d8d1 ponder f3f4

**Comment by nmrugg** [comment]
Yes, reverting https://github.com/official-stockfish/Stockfish/commit/76f1807baa90eb69f66001d25df2a28533f9406f fixes the "hanging" issue.

I also think https://github.com/official-stockfish/Stockfish/commit/0f63b35120e79fe6cc76abdd293d58243ccdbacb should be re-reviewed because at https://github.com/official-stockfish/Stockfish/commit/0f63b35120e79fe6cc76abdd293d58243ccdbacb#diff-71c8faa29f847041392f6e81e16bd9e6R1191, `pureStaticEval` is not always the same as `ss->staticEval`.

> looks like we should consider doing some type of MutliPV sanitization procedures on every patch

That would be much appreciated.
