### ISSUE TITLE
Not able to compile Stockfish Polyglot with the latest changes of the Stockfish code

### ISSUE THREAD

**Issue by massimilianogoi** [official-stockfish/Stockfish#2095]
While compiling Stockfish Polyglot with the latest versions of the Stockfish code I get this error and I'm not able to get the executables:

main.o:main.cpp:(.text.startup+0x12a): undefined reference to `PolyBook::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.o:main.cpp:(.rdata$.refptr.polybook[.refptr.polybook]+0x0): undefined reference to `polybook'
search.o:search.cpp:(.text+0xe6df): undefined reference to `PolyBook::probe(Position&)'
ucioption.o:ucioption.cpp:(.text+0x32d): undefined reference to `PolyBook::set_best_book_move(bool)'
ucioption.o:ucioption.cpp:(.text+0x3ec): undefined reference to `PolyBook::set_book_depth(int)'
ucioption.o:ucioption.cpp:(.text+0x672): undefined reference to `PolyBook::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:496: stockfish.exe] Error 1
make[1]: Leaving directory '/home/Massimiliano Goi/Stockfish-master/src'
make: *** [Makefile:413: build] Error 2

What is wrong with it? I did it for months and I've always succeeded; the polybook.cpp and polybook.h files has been integrated in the code as I always did. I've tried with searching on Google for the problem but I had no luck...

**Comment by mcostalba** [comment]
make clean

**Comment by massimilianogoi** [comment]
Hello Mr. Costalba and thank you for your masterpiece. I did as you said and it did not solve the issue. This is the whole compiling output: https://pastebin.com/Aczeixpy

and this is the source I've made with the latest Stockfish Beta version: https://chess.massimilianogoi.com/download/stockfish/Stockfish_Polyglot_errors_in_compiling/

**Comment by mcostalba** [comment]
It does not seem that polybook.cpp has been comiled. You shoudl add it to your makefile

**Comment by massimilianogoi** [comment]
That solved the issue, thank you very much! I just had to add polybook.o near the other .o objects in the Makefile.
