### ISSUE TITLE
excludedMove and TT

### ISSUE THREAD

**Issue by svivanov72** [official-stockfish/Stockfish#2104]
In `search()`, line 603, the position key is modified if there is an excluded move, because "We don't want the score of a partial search to overwrite a previous full search TT value" as a comment says.

However the result of search with excluded move is never stored in the transposition table because of `if (!excludedMove)` on line 1186. I verified this by adding the following crude test:
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 15e88ca4..73eb20db 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -607,6 +607,9 @@ namespace {
             : ttHit    ? tte->move() : MOVE_NONE;
     ttPv = (ttHit && tte->is_pv()) || (PvNode && depth > 4 * ONE_PLY);
 
+    if (excludedMove && (ttValue!=VALUE_NONE || ttMove!=MOVE_NONE))
+        std::cerr << "excludedMove in TT!!!\n";
+
     // At non-PV nodes we check for an early TT cutoff
     if (  !PvNode
         && ttHit`
```
and running stokfish bench and not seeing any exclamation marks.

Other calls to `tte->save()` store only the static eval and TB lookup results. They could use the unmodified position key just as well, all stored values would be the same. So it seems that the modified key does nothing useful and only wastes TT entries.

One could either remove the `if (!excludedMove)` check to make these special TT entries work, or remove the modified key to save hash space. Which way it is supposed to work?

**Comment by vondele** [comment]
@svivanov72 no need to file an issue for these things (i.e. this is not a bug or user visible), just test the potential improvements on fishtest (with STC bounds [0.5, 4.5] or [-3,1] if the solution adds or removes complexity), and make a pull request of what passes (STC and LTC).

**Comment by svivanov72** [comment]
Closing the issue. Tested both ways to improve (use or not use TT with excludedMove) and both failed.
