### ISSUE TITLE
Opening specific improvement

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2120]
Knowing that SF is (relatively) bad at a couple of openings, the Calatan and the French being two I can recall off the top of my head, is it possible to create some patches that specifically target these openings? For example, what if we check the board and if the position matches a Calatan/French kinda position then we maybe do something to push the search in some other directions, otherwise we let SF proceed as usual. I think this idea makes sense because ultimately it's hard to come up with an evaluation function that works equally well in all positions. Even for Leela/any other NN engines, when feeding different positions into the network, surely different neurons would be activated, so in a sense their evaluation functions are also position-specific.
If we do create opening specific patches, maybe for testing we can have some different books containing only the specific opening a patch is created for. Otherwise I can't imagine these patches will be able to pass the tests with a general opening book.

**Comment by vdbergh** [comment]
There is a thread on the forum for suggestions

https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/vuoEKP2yOCE%5B1026-1050%5D
