### ISSUE TITLE
Self Learning with using a Tree Search (not lc0)

### ISSUE THREAD

**Issue by ghost** [official-stockfish/Stockfish#2140]
Hello. When I was searching for a Self Learning without using anything about Leela Chess Zero, I found something great and useful.
@kellykinyama12 created a Self Learning with a Tree Search and now @amchess improves it for his own engine ShashChess.
This Patch creates bin files which all the Windows versions can read. This is something like Neural Networks, but this feature doesn't need any programs like Lc0.
This is the information of ShashChess' Readme:

_NN Persisted Self-Learning

[https://github.com/Kellykinyama12/Stockfish] (montecarlo by Kelly Kinyama) only when true. It keeps the played games in created three type of files for machine/self learning purposes from experience:

experience.bin when no more than 40 moves are played, there are non more than 6 pieces on the chessboard and at a not low depth in analysis, the positions are stored and searched for by hash key
pawngame.bin when there are no more than 2 pieces and the game's phase is not the ending, to better play the following ending.
openings.bin, in the form .bin (>=1) at the initial stage of game with memorized the move played, the depth and the score. Every file is a single opening variation (random files).
When activated, it loads these files in memory and therefore it can use Search Statistics (Principal Variation, History Heuristics, Transposition Table, Refutation Table and Killer Moves) to play better if the same game is encountered. It persists the following information on the Hard Disk:
best move
board signature (hash key)
best move depth
best move score
With learning, the engine became stronger and stronger. The algorithm builds a decision tree of moves and contains the statistics similar to Monte Carlo Tree Search. It makes a decision depending on what information is in the Decision Tree, so both Best Search First and later Depth First Search._

I think we can use it for Improving Stockfish and training it for openings. I saw an issue for SF's openings and we can use it.

**Comment by adentong** [comment]
Here's the topic on fishcooking: https://groups.google.com/forum/#!topic/fishcooking/fhX7dFAsyew.

I hope this gains more traction since it seems to work, at least according to the author.
