### ISSUE TITLE
maintaners not have enough time

### ISSUE THREAD

**Issue by fun8** [official-stockfish/Stockfish#2144]
As i know all ours maintaners have real job, and they not have enough time for us.
Can we start colect money for they (social funding)?

**Comment by adentong** [comment]
...what? if you mean the PRs aren't getting merged, i'm sure they will be eventually. there's no hurry anyways since we don't have to submit a binary or anything.

**Comment by xoto10** [comment]
I don't think money is the problem, so it wouldn't help.

I don't see any great problem in slower processing of PRs anyway, it gives
a chance for debate and refining the change before merging.

**Comment by mcostalba** [comment]
@fun8 thank you but unfortunately giving me money will not make me going faster, so it would be a waste :-)

**Comment by fun8** [comment]
@mcostalba maybe we need 3rd maintaner, @snicolet is allmost not active?
