### ISSUE TITLE
New master fails to compile

### ISSUE THREAD

**Issue by Vizvezdenec** [official-stockfish/Stockfish#2148]
search.cpp: In function ‘Value {anonymous}::search(Position&, Search::Stack*, Value, Value, Depth, bool)’:
search.cpp:942:45: error: ‘class Thread’ has no member named ‘rootDepth’; did you mean ‘selDepth’?
                && ss->ply < 3 * thisThread->rootDepth / ONE_PLY) // To avoid too deep searches
                                             ^~~~~~~~~
                                             selDepth
I get this error

**Comment by mcostalba** [comment]
Thanks. Fixed now.
