### ISSUE TITLE
Blunder(?) in game 86 of TCEC super finals

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2161]
Here's the FEN: 8/6bk/2b3p1/P3p2p/4pp2/3RP1PP/5PB1/6K1 b - - 0 39. The rook sac, Rxd3, was in the PV since at least five moves ago. However, the eval went up from 0.97 to 7.96 as soon as the move was played. I hesitate to call this a blunder because SF obviously saw the move. In any case, I just want to open an issue to track this since this seems like a major oversight on SF's part.

**Comment by adentong** [comment]
I really wonder what happened there. It just seems so weird that a move that's been in its PV for multiple moves all of a sudden becomes a losing move. What's even more weird is that, if we for example look at move 34, SF already has more than 10 million TB hits.

**Comment by LouisZulli** [comment]
1. d4 f5 2. g3 Nf6 3. Bg2 g6 4. Nf3 Bg7 5. O-O O-O 6. c4 d6 7. Nc3 Nc6 8. d5 Ne5 9. Nxe5 dxe5 10. Qb3 Rb8 11. Rd1 Bd7 12. a4 c5 13. dxc6 bxc6 14. Qa3 Qc7 15. b4 e4 16. Bf4 e5 17. Be3 Be6 18. Bc5 Rfd8 19. b5 Rbc8 20. Rxd8+ Qxd8 21. Bxa7 Qa5 22. Bc5 Bxc4 23. Bb4 Qa7 24. bxc6 Rxc6 25. Rd1 h5 26. e3 Kh7 27. h3 Rc8 28. Nb5 Qa6 29. Rc1 Nd5 30. Nd6 Nxb4 31. Nxc8 Nd3 32. Rc2 Ne1 33. Rc1 Nd3 34. Rc3 Qxc8 35. Qa2 Bxa2 36. Rxc8 Bd5 37. Rd8 Bc6 38. a5 f4 39. Rxd3 exd3 40. Bxc6 Bf8 41. gxf4 exf4 42. exf4 Bc5 43. Kf1 Kh6 44. f3 g5 45. f5 d2 46. Ke2 Kg7 47. Be4 Kf6 48. a6 Be3 49. Bc2 1-0

**Comment by MichaelB7** [comment]
I believe 37.  ... Bc4 would have provided a stronger defense , but that that point , the game appears lost regardless.   An earlier suspect move is 29.  ..Nd5 . It appears 29. ...Bd3 there would have been better.  Likewise, I like 19. ... Rxd1 over 19....Rc8.  And one could argue, 7... Nc6 should have never been played, it appears that the position is begging for the simpler 7. ...c6.   In this game, it appears a bunch of smaller mistakes accumulated in a lost position way before  39. Rxd3.

**Comment by mooskagh** [comment]
It actually didn't move from 0.97 to 7.96 as soon as move was played, SF thought for some minutes before the eval jumped. So I guess at previous move it just didn't think to particular depth, it's not that the opponent's move was unexpected.
