### ISSUE TITLE
[FishTest 2019 Games Not Saving Bug Issue] Result in Weaker Stockfish Conversion to NN Form (-30 Elo)

### ISSUE THREAD

**Issue by Cscuile** [official-stockfish/Stockfish#2164]
There is a project of mine called BetaOne in which attempts to essentially convert Stockfish into an NN form engine. 

Currently 2019 games are not saving resulting in an overall 30 Elo or so weaker performance. 

Is there anyway I can assist in saving the FishTest games from 2019? 

Thanks to my college, I have unlimited drive space so if anyone is willing to help get me setup please feel free to contact me here or on discord Cscuile #0044. 

Thank you!

**Comment by fun8** [comment]
Better make this issue in this repo https://github.com/glinscott/fishtest

**Comment by Cscuile** [comment]
Done
