### ISSUE TITLE
MultiPV search doesn't stop at Limits.mate

### ISSUE THREAD

**Issue by joergoster** [official-stockfish/Stockfish#2168]
While doing some MultiPV sessions with my [multipv_jos](https://github.com/joergoster/Stockfish/tree/multipv_jos) branch, I noticed that 'go mate x' doesn't stop the search even when a mate in x is already found (as best PV line!).

Steps to reproduce in a console/terminal:
stockfish or ./stockfish
uci
setoption name MultiPV value 3
setoption name Hash value 512
ucinewgame
isready
position fen 3r3k/1P1r1p2/2K2P2/6P1/5PQp/2P5/1p1p2Pp/8 w - - 0 1
go mate 24

> info depth 42 seldepth 52 multipv 1 score mate 24 nodes 5818127 nps 1958965 hashfull 64 tbhits 0 time 2970 pv g4h5 h8g8 h5h6 d7d6 c6c5 d6d5 c5c4 d5d4 c3d4 d8d4 c4c5 d4d5 c5c6 d5d6 c6c7 d6d7 c7b8 d7b7 b8c8 b7b8 c8c7 b8b7 c7c6 b7b6 c6c5 b6b5 c5c4 b5b4 c4c3 d2d1n c3d2 b2b1n d2c1 b4c4 c1b1 c4b4 b1a2 d1c3 a2a3 b4a4 a3b3 a4a3 b3a3 c3b5 a3b2 h2h1q h6g7
> info depth 42 seldepth 19 multipv 2 score cp 0 nodes 5818127 nps 1958965 hashfull 64 tbhits 0 time 2970 pv g4h4 h8g8 h4h6 d7d6 c6c5 d6d5 c5c4 d5d4 c3d4 d8d4 c4c5 d4d5 c5c6 d5d6 c6c7 d6d7 c7c6
> info depth 42 seldepth 30 multipv 3 score cp -783 nodes 5818127 nps 1958965 hashfull 64 tbhits 0 time 2970 pv g4d7 d8d7 b7b8q h8h7 b8b4 d7d6 c6c7 d6e6 b4f8 h7g6 f8g8 g6f5 g8h7 f5f4 h7c2 h2h1q c2d2 f4f5 d2b2 h1h2 c7b7 f5g5 b2d2 g5g6 d2d3 g6f6 d3d8 f6g7 d8g5 e6g6

...

> info depth 55 seldepth 48 multipv 1 score mate 24 nodes 25547801 nps 2099934 hashfull 270 tbhits 0 time 12166 pv g4h5 h8g8 h5h6 d7d6 c6c5 d6d5 c5c4 d5d4 c3d4 d8d4 c4c5 d4d5 c5c6 d5d6 c6c7 d6d7 c7b8 d7b7 b8c8 b7b8 c8c7 b8b7 c7c6 b7b6 c6c5 b6b5 c5c4 b5b4 c4c3 d2d1n c3d2 b2b1n d2c1 b4c4 c1b1 c4b4 b1a2 d1c3 a2a3 b4a4 a3b3 a4a3 b3a3 c3b5 a3b2 h2h1q h6g7
> info depth 55 seldepth 18 multipv 2 score cp 0 nodes 25547801 nps 2099934 hashfull 270 tbhits 0 time 12166 pv g4h4 h8g8 h4h6 d7d6 c6c5 d6d5 c5c4 d5d4 c3d4 d8d4 c4c3 b2b1n c3b2 d4b4 b2c2 b4c4 c2b2
> info depth 55 seldepth 42 multipv 3 score cp -338 nodes 25547801 nps 2099934 hashfull 270 tbhits 0 time 12166 pv g4d7 d8d7 b7b8q h8h7 b8b4 d7d6 c6c7 d6f6 b4e4 f6g6 f4f5 g6g7 f5f6 g7g6 e4h4 h7g8 h4h3 g6g5 h3c8 g8h7 c8h3 h7g6 h3d3 g6h6 d3h3 g5h5 h3e3 h6g6

Although the mate in 24 is already found at depth 42, search simply continues.
**Note:** current master may take quite some more time to finally resolve the mate in MultiPV=3 mode! ;-)
_Edit_ P.S. Position taken from [here](http://talkchess.com/forum3/viewtopic.php?f=2&t=70832&start=10#p799968)

**Comment by joergoster** [comment]
Looking at the code
```
      // Have we found a "mate in x"?
      if (   Limits.mate
          && bestValue >= VALUE_MATE_IN_MAX_PLY
          && VALUE_MATE - bestValue <= 2 * Limits.mate)
          Threads.stop = true;
```
it seems clear why this happens.

In a MultiPV search 'bestValue' at this point refers to the last PV line searched. But we must check against the 1st PV line! Replacing 'bestValue' with 'rootMoves[0].score' should do the trick!

**Comment by mcostalba** [comment]
@joergoster Thanks! Could you please verify that the fix you proposed works? And eventually could you please open a PR?

**Comment by MichaelB7** [comment]
It does work with one caveat - and maybe it’s just my system.   It stops the search and produces the output - but  it’s several hundred nodes , up to 1000 nodes or so short of actually producing the mate - in - xx score.  It appears it sees the mate - in -xx , but the output is coming from perhaps a different thread and not the thread that has the mate score.  I say this because if you type “ go mate xx” again , it will always produce the mate in xx within a thousand or so nodes which is instantly.

**Comment by joergoster** [comment]
@MichaelB7 Try single thread first, please. In SMP mode and MultiPV search we currently don't allow another thread to be chosen as best thread.

I see 2 different ways to solve this.

1. Also allow to choose another thread as best thread in a MultiPV search.
Not sure though if this may cause further problems.

2. Move the "Have we found a "mate in x"?" code block below
```
if (!mainThread)
continue;
```
so that only the main thread will be checked for the "mate in x" score.
This will eventually increase the time to solution in some cases.

@mcostalba I would go with solution 2 at this point. Would this be ok for you?

**Comment by snicolet** [comment]
Is the issue still there in current master?

**Comment by snicolet** [comment]
I think that I will close this issue now, since there have been no progress in the last 6 months.

Maybe we can claim that it is a feature, as it allows us to check that only the best move leads to mate but moves 2 and 3 do not ?
