### ISSUE TITLE
FauziB20 patch disappeared

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2178]
Fauzi's new patch where he reduces contempt to 20 along with a bunch of param tweaks disappeared. In fact I think his github account disappeared. Since it was an elo gainer, does anyone have his patch so we can try to merge it to master?

**Comment by MichaelB7** [comment]
It has only disappeared from view.  His account got flag for whatever reason, probably for not a valid reason at all.  He just has to contact Github privately to get it unflagged.  It is a known issue that Github will randomly flag an account for some supposedly suspicious activity in error. ( totally automatic - not by human). Google "GitHub account flag" for more info.  It is a nuisance more than anything else.

**Comment by xoto10** [comment]
Yeah, I guess it was that large font and bold used in the pr.

**Comment by adentong** [comment]
Oh is that so... That's unfortunate.
