### ISSUE TITLE
Omit generating quiet moves when skipQuiets == true

### ISSUE THREAD

**Issue by yaneurao** [official-stockfish/Stockfish#2186]
In movepick.cpp , 

> case QUIET_INIT:
>      cur = endBadCaptures;
>      endMoves = generate<QUIETS>(pos, cur);
> ...
>       partial_insertion_sort(cur, endMoves, -4000 * depth / ONE_PLY);

I think this is not necessary when skipQuiets == true , how about changing to the following?

> case QUIET_INIT:
>   if (!skipQuiets) {
>      cur = endBadCaptures;
> ...
>      partial_insertion_sort(cur, endMoves, -4000 * depth / ONE_PLY);
>   }

**Comment by Vizvezdenec** [comment]
write the test and try it?
It's not an issue, it's an idea for the patch which is not a bugfix :)
