### ISSUE TITLE
Big failure to recognize winning positions when one side has fewer pieces than its opponent 

### ISSUE THREAD

**Issue by Octavio1994** [official-stockfish/Stockfish#2195]
SF still struggle a lot when analyzing positions with one side behind in material (2 pawns for example) such position can be easily win by the side with less pieces and the line is barely 3 or 4 moves beyond. However stockfish just fails to recognize that; despite the side is behind in material it has a winning position. 

1r2k2r/p5p1/2p1bp1p/q1B1p3/2P2n1P/2p1Q3/P1B2PP1/R3R1K1 w k - 0 1 

the winning move is rock a1-b1, despite this move could be find by using powerful hardware. It becomes impossible for the engine to see that move 2 or 3 positions behind

---------------------------------------------------------------------------------------------------------

Now the next 2 positions are really curious. In both of them is black to move and they get a winning position just for a single pawn push

r4r2/1p2p1bk/2ppbn1p/p1Pn1ppq/N2P4/1P2PBP1/P1QN1P1P/2RRB1K1 b - - 3 21 

Stockfish is simple unable to find that g5 leads black side to a winning position after a couple of moves

.........

4rnk1/2pbr1q1/1p1b1ppp/2pPp3/p1P1P2B/P1Q2N1P/1P1N1PP1/3RR2K b - - 3 21 

In this one again black just has to push g4 and then the king to h8 to get a winning position. despite that the engine always fails to recognize it. I simply don't know why but komodo does better here.

--------------------------------------------------------------------------------------------------------

q3nrk1/4bppp/3p4/r3nPP1/4P2P/NpQ1B3/1P4B1/1K1R3R b - - 3 1 

Here black just has to play Ne8-c7 to win the game, after the move is on the board the engine thinks white is winning but suddenly that evaluation drops to the black side

--------------------------------------------------------------------------------------------------------

Finally in this position

rn3r2/p3b1kp/2p5/1p3bp1/4B3/q1P1B1P1/P4P2/3RR1KQ b - - 3 21 

Here to save black pieces from death they just have to take the bishop on e4 Bf5xe4

However Stockfish always fails to plays Bf5-g6. After that move is played all perfect variations are leading white side to win. For further information about all the incredible variatons for this really curious game from A0 vs SF simply look for the GOI_5 opening book which you can find in the chessgod101 webpage

Thanks and really hope you can get this on mind. It would really improve the engine's strenght

**Comment by LouisZulli** [comment]
Thanks for posting the positions, and for wanting to help make Stockfish stronger.

As you note, Stockfish-dev does find Ra1 in the first position, though not quickly.

In the second position, the material is **even**. Stockfish-dev prefers g4 almost immediately, but does not see it as winning. Is it actually a winning move?
`0.00 21... g4 22. Bxd5 Bxd5 23. Nb6 e6 24. cxd6 Rf7 25. Nxa8 Qh3 26. f3 gxf3 27. Nxf3 Bxf3 28. Nc7 Ng4 29. Rd2 Be4 30. Qc3 e5 31. Ne6 f4 32. exf4 exd4 33. Nxd4 c5 34. Qxc5 Rxf4 35. gxf4 Qe3+ 36. Kf1 Bxd4 37. Qxd4 Nxh2+ 38. Rxh2 Qxd4 39. Rc7+ Kg6 40. Bc3 Qd1+ 41. Kf2 Qf3+ 42. Ke1 Qg3+ 43. Rf2 Qe3+ 44. Kf1 Qd3+ 45. Ke1 (depth 45, 0:19:42)
`

In the third position, the material is basically **even**---Black has a B while White has a N. Stockfish-dev finds g5, but does not (yet) see a win for Black. Is there one?
`-0.14 21... g5 22. Bg3 h5 23. h4 Rf7 24. Qe3 g4 25. Ng1 Ng6 26. Ne2 Ref8 27. Kg1 Be7 28. Nc3 f5 29. exf5 Bxf5 30. Nde4 Bxe4 31. Qxe4 Bxh4 32. d6 Bd8 33. Re2 h4 34. Bxe5 Nxe5 35. Qxe5 Qxe5 36. Rxe5 cxd6 37. Re4 Rg7 38. Rxd6 Bf6 39. Nb5 h3 40. Re2 g3 41. fxg3 Rxg3 42. Kh2 Rxg2+ 43. Rxg2+ hxg2 44. Kxg2 Bxb2 45. Rxb6 Kh7 46. Ra6 Rf4 47. Rxa4 Kg6 48. Kg3 (depth 43, 0:15:02)`




In the fourth position, the material is basically **even**, and Stockfish-dev finds the winning move:
`-6.65 1... Nc7 2. Qxc7 Rc8 3. Qxa5 Qxa5 4. Rc1 Rxc1+ 5. Rxc1 Bf8 6. f6 d5 7. exd5 Qa6 8. Bf1 Qa4 9. Bb6 Qxh4 10. d6 gxf6 11. gxf6 Qxf6 12. Nb5 Qf5+ 13. Ka1 Nd3 14. Bxd3 Qxd3 15. Na3 Bxd6 16. Bc5 Bxc5 17. Rxc5 Kg7 18. Rc3 Qd1+ 19. Nb1 h5 20. Rg3+ Kh6 21. Rg1 Qd4 22. Rc1 Kg5 23. Nc3 h4 24. Rh1 h3 25. Nb1 Kg4 26. Nc3 Qd3 (depth 45, 0:04:29)`


In the last position, Stockfish-dev does eventually switch to Bxe4:
`+0.31 21... Bxe4 22. Qxe4 Kg8 23. Qe6+ Rf7 24. Qg4 Nd7 25. Rxd7 Qxc3 26. Rc1 Qf6 27. Bd4 Qg6 28. Rc7 Re8 29. R1xc6 Qf5 30. Qxf5 Rxf5 31. Rxa7 Bf8 32. Rcc7 Rd8 33. Be3 h6 34. Kg2 Rf6 35. Rcb7 b4 36. Kh3 Rc6 37. Ra5 Rf6 38. Kg4 Rc6 39. Rba7 Re6 40. Rc7 Red6 41. Raa7 Rd3 42. Ra6 R3d5 43. Rg6+ Kh8 44. Kh5 R5d7 45. Rxd7 Rxd7 46. Rf6 Kg8 47. Kg6 Rc7 48. g4 Rc2 (depth 47, 0:08:13)`

**Comment by Octavio1994** [comment]
> Thanks for posting the positions, and for wanting to help make Stockfish stronger.
> 
> As you note, Stockfish-dev does find Rab1 in the first position, though not quickly.
> 
> In the second position, the material is **even**. Stockfish-dev prefers g4 almost immediately, but does not see it as winning. Is it actually a winning move?
> `0.00 21... g4 22. Bxd5 Bxd5 23. Nb6 e6 24. cxd6 Rf7 25. Nxa8 Qh3 26. f3 gxf3 27. Nxf3 Bxf3 28. Nc7 Ng4 29. Rd2 Be4 30. Qc3 e5 31. Ne6 f4 32. exf4 exd4 33. Nxd4 c5 34. Qxc5 Rxf4 35. gxf4 Qe3+ 36. Kf1 Bxd4 37. Qxd4 Nxh2+ 38. Rxh2 Qxd4 39. Rc7+ Kg6 40. Bc3 Qd1+ 41. Kf2 Qf3+ 42. Ke1 Qg3+ 43. Rf2 Qe3+ 44. Kf1 Qd3+ 45. Ke1 (depth 45, 0:19:42) `
> 
> In the third position, the material is basically **even**---Black has a B while White has a N. Stockfish-dev finds g5, but does not (yet) see a win for Black. Is there one?
> `-0.29 21... g5 22. Bg3 h5 23. Nf1 h4 24. Bh2 Qg6 25. Qc2 Qh5 26. Ng1 g4 27. hxg4 Bxg4 28. Ne3 Bxd1 29. Rxd1 Ng6 30. Qxa4 Rf8 31. f3 Rg7 32. Qc2 Ne7 33. Qc3 Rh7 34. Re1 f5 35. exf5 Nxf5 36. Nxf5 Rxf5 37. Re4 Kf8 38. Nh3 Rg7 39. Qd3 Be7 40. Qe2 Bf6 41. b3 Ke7 42. Rg4 Qh6 43. Bf4 Qh7 44. Be3 Rxg4 45. fxg4 (depth 44, 0:17:29) `
> And now a transposition, but not seeing a win:
> `-0.30 21... h5 22. Bg3 g5 23. h4 Rf7 24. Nf1 Qh7 25. Qc2 Ng6 26. Ne3 Ref8 27. Re2 Kh8 28. Rde1 Rg7 29. Rg1 gxh4 30. Nxh4 Nxh4 31. Bxh4 f5 32. exf5 Bxf5 33. Nxf5 Qxf5 34. Bg3 Qxc2 35. Rxc2 Kh7 36. Re1 Rg4 37. Kh2 Rfg8 38. Bxe5 Rxg2+ 39. Kh3 Bxe5 40. Rxe5 Kh6 41. Re6+ R8g6 42. Rxg6+ Rxg6 43. Re2 Rg4 44. Re7 Rxc4 45. Rxc7 Kg5 46. Rb7 Rd4 47. Rxb6 Rxd5 48. Kg2 Rd4 49. Re6 Rg4+ 50. Kf3 Rf4+ 51. Kg2 Kf5 52. Rh6 h4 53. Rc6 (depth 48, 0:39:04)`
> 
> In the fourth position, the material is basically **even**, and Stockfish-dev finds the winning move:
> `-6.65 1... Nc7 2. Qxc7 Rc8 3. Qxa5 Qxa5 4. Rc1 Rxc1+ 5. Rxc1 Bf8 6. f6 d5 7. exd5 Qa6 8. Bf1 Qa4 9. Bb6 Qxh4 10. d6 gxf6 11. gxf6 Qxf6 12. Nb5 Qf5+ 13. Ka1 Nd3 14. Bxd3 Qxd3 15. Na3 Bxd6 16. Bc5 Bxc5 17. Rxc5 Kg7 18. Rc3 Qd1+ 19. Nb1 h5 20. Rg3+ Kh6 21. Rg1 Qd4 22. Rc1 Kg5 23. Nc3 h4 24. Rh1 h3 25. Nb1 Kg4 26. Nc3 Qd3 (depth 45, 0:04:29)`
> 
> In the last position, Stockfish-dev does eventually switch to Bxe4:
> `+0.31 21... Bxe4 22. Qxe4 Kg8 23. Qe6+ Rf7 24. Qg4 Nd7 25. Rxd7 Qxc3 26. Rc1 Qf6 27. Bd4 Qg6 28. Rc7 Re8 29. R1xc6 Qf5 30. Qxf5 Rxf5 31. Rxa7 Bf8 32. Rcc7 Rd8 33. Be3 h6 34. Kg2 Rf6 35. Rcb7 b4 36. Kh3 Rc6 37. Ra5 Rf6 38. Kg4 Rc6 39. Rba7 Re6 40. Rc7 Red6 41. Raa7 Rd3 42. Ra6 R3d5 43. Rg6+ Kh8 44. Kh5 R5d7 45. Rxd7 Rxd7 46. Rf6 Kg8 47. Kg6 Rc7 48. g4 Rc2 (depth 47, 0:08:13)`

Hello and thanks you for your answer :) 

Good to know the engine thinks a lot better in a stronger processor, please could you share your PC specs?

In the second and third positions its possible to get a winning game by going for the pawn pushes, actually komodo does a bit better there but simply don't know why SF is unable to do so as well. In the last one Its always switching between Bxe4 and Bf5-g6 on my computer, in yours one does it choose Bxe4 all the time after it gave a deep analysis??

**Comment by Vizvezdenec** [comment]
Sorry but not finding winning moves is NOT an issue - unless program plays ideal chess there will always be such positions and it's not because of some bug or other stuff like this.
This can be discussed on stockfish forum and not there.

**Comment by Octavio1994** [comment]
> Sorry but not finding winning moves is NOT an issue - unless program plays ideal chess there will always be such positions and it's not because of some bug or other stuff like this.
> This can be discussed on stockfish forum and not there.

Hello Michael and thanks for your reply, 

First of all I have to say you're right, rather this is not an issue but a possible area of improvement; I hadn't think about it and apologize for that. I will post it in the general forum later and close this one.
