### ISSUE TITLE
Possible SF tablebases bug at CCC

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2196]
In CCC9 game 146, SF might have blundered in a drawn(?) 7-men position. The reason I say might have is because in a previous game of Rofchade vs Leela Leela lost because of a corrupted tb entry, and some people were saying SF blundered because of the same issue. I'm creating a new issue regardless if it was actually SF's fault and hopefully someone can look into it.

**Comment by adentong** [comment]
Ok this is interesting. https://syzygy-tables.info/?fen=1QK5/6k1/1qB1R3/8/8/8/6p1/8_b_-_-_0_1 black to move. Here the only draw saving move is Qxb8+. However, SF played g1=Q, which on the syzygy website says Zeroing, whatever that means. So this could potentially be a bug in how SF handles 7men tb?

**Comment by adentong** [comment]
@syzygy1 @vondele @mcostalba

**Comment by adentong** [comment]
I guess if it turns out to be a bug, then good thing we used CCC as a testing ground for 7men tb.

**Comment by adentong** [comment]
https://cccfiles.chess.com/archive/cutechess.debug-29220-30234.zip I think coolchess provided this link.

**Comment by Vizvezdenec** [comment]
Pls look at this (someone who has any clue about TBs).
Is it SF issue or TBs are broken? Additional logs can be provided if they are needed.

**Comment by Vizvezdenec** [comment]
@adentong I suggest you to change title to "possible SF tablebases bug at CCCC".
It will be much more informative description and will attract devs who know smth about this topic.

**Comment by adentong** [comment]
@Vizvezdenec Done.

**Comment by Vizvezdenec** [comment]
Nice!
Now let us just wait - if I had any knowledge about how this stuff works I would've done it myself, but...

**Comment by JavaMast** [comment]
In position: 8/1P6/5k2/R7/5K2/5B2/5qp1/8 w - - 0 190 
with full 6 men TB and **KQRBvKQP.rtbw**  current SF dev has blunder with 190.b8=Q in infinite analyzes

![Screenshot_262](https://user-images.githubusercontent.com/42765009/59716223-45d87a80-921e-11e9-98ef-12deabd0d1ee.png)

Stockfish 10 and Cfish has not this issue

**Comment by vondele** [comment]
well, I guess we have to understand first what table bases are available. The debug log gives us:

3854 <Stockfish(1): info string Found 621 tablebases

that 621 is strange. 6men is 510 tablebases, 7men is 1511 

Also, do we have both wdl and dtz ? 

Finally, are the tb files fine or corrupted. They need to pass md5sum -c 3-4-5-6.md5 (and equivalent for 7men)

**Comment by Vizvezdenec** [comment]
You probably should have dialogue with @coolchess123 since he is CCCC admin and ask him all you need to debug this (in discord or wherever).

**Comment by coolchess123** [comment]
i have asked for the following to CCC admin

1. do we have both wdl and dtz ?
2. md5sum of  all the tb files

**Comment by coolchess123** [comment]
any other information is required?, please let me know

**Comment by vondele** [comment]
I think understanding why Stockfish (and also Leela) only find 621 is important.... that seems like just a subset of 7men.

**Comment by JavaMast** [comment]
@vondele 
CCC have not all 7-men TB is - not enough free space:
https://github.com/official-stockfish/Stockfish/issues/2193
"SSD: 2x Crucial MX300 (1TB) in RAID1"

**Comment by syzygy1** [comment]
I guess the problem is caused by https://github.com/official-stockfish/Stockfish/commit/d39bc2efa197ba2fd55b68eced1c60bcfe2facc1#diff-77f6a424089763d9c85bf34eca3035f1

In particular the changes to tbRank in search.cpp and search.h

**Comment by JavaMast** [comment]
@syzygy1 
You are absolutely right. I just tried it on myself - the bug is gone.

**Comment by adentong** [comment]
@syzygy1 Wow! It seems like such an innocuous change.

**Comment by adentong** [comment]
Closing this since the bug fix just got merged.
