### ISSUE TITLE
Cfish-dev is about 35% faster than Stockfish-dev using 20 threads

### ISSUE THREAD

**Issue by fun8** [official-stockfish/Stockfish#2203]
http://talkchess.com/forum3/viewtopic.php?f=7&t=71027
http://talkchess.com/forum3/viewtopic.php?f=2&t=71013

**Comment by LouisZulli** [comment]
As I noted in my posts on TalkChess,com, I was surprised by the apparent difference in speed between Cfish-dev and Stockfish-dev on my hardware. I had hoped to understand things better before raising an issue here. If anyone sees an immediate flaw in my testing methodology, please let me know. Barring that, my next step will be to run similar tests using older (but equivalent according to bench signature) versions of the two engines. Perhaps this will reveal when the apparent speed disparity arose, which might suggest its cause(s).

**Comment by LouisZulli** [comment]
Am I correct that Stockfish now invokes "setoption name hash value" for each position in the bench file? That's what a look at the code is suggesting to me.

**Comment by LouisZulli** [comment]
It seems that the observed speed disparity is largely due to the fact that Stockfish re-initializes the transposition table for each bench position, while Cfish does not. Assuming I've understood the source codes correctly.

**Comment by joergoster** [comment]
No, that's not the case. 'ucinewgame' and the setoption commands for Threads and Hash are only sent once at the beginning of a new bench run.

**Comment by LouisZulli** [comment]
Thanks, Joerg. Then my puzzlement remains regarding the following, from recent Stockfish-dev and Cfish-dev with identical bench signature 3398333.

```
$ ./stockfish bench 4096 20 18 >> /dev/null
===========================
Total time (ms) : 8503
Nodes searched  : 214177526
Nodes/second    : 25188465

$ ./cfish bench 4096 20 18 >> /dev/null
===========================
Total time (ms) : 5081
Nodes searched  : 178563760
Nodes/second    : 35143428
```

**Comment by joergoster** [comment]
Hi Louis, on my machine single-threaded Cfish is about 4% faster than Stockfish which seems to be what can be expected. Both compiled as profile-build with gcc/g++ 8.3, Cfish with the additional `numa=no` option.
```
./stockfish bench 1024 1 18
===========================
Total time (ms) : 22141
Nodes searched  : 28626391
Nodes/second    : 1292913
```

```
./cfish bench 1024 1 18
===========================
Total time (ms) : 21290
Nodes searched  : 28626391
Nodes/second    : 1344593
```
And a multi-threaded run is in the same ballpark. (however, only 1 run)
```
./stockfish bench 1024 7 18
===========================
Total time (ms) : 14297
Nodes searched  : 115692197
Nodes/second    : 8092061
```

```
./cfish bench 1024 7 18
===========================
Total time (ms) : 9780
Nodes searched  : 82248337
Nodes/second    : 8409850
```
I can only guess what you're experiencing is somewhat NUMA-related.
Maybe @syzygy1 does know more. ;-)

**Comment by MichaelB7** [comment]
I don’t believe it’s numa related, I have experienced the same phenomenon on macOS ( does not support Numa). I believe it may be number of  threads related,i.e, once you go to 20 or more threads with the relatively short ( for 20 threads ) bench marks.

**Comment by LouisZulli** [comment]
Let's focus on single thread benchmark, but with a "big" hash setting. Here's Sf-dev:

$ ./stockfish bench 8192 1 18 >> /dev/null
===========================
Total time (ms) : 62489
Nodes searched  : 27175855
Nodes/second    : 434890

Why only 400K nps? Hash initialization takes a long time, but surely that is not included in the total time, right?

**Comment by LouisZulli** [comment]
A look at the code suggests that measuring of elapsed time is improperly including hash initialization.

**Comment by joergoster** [comment]
As far as I can say, in Stockfish the time it takes to initialize hash is indeed included.

**Comment by joergoster** [comment]
@LouisZulli I'm thinking about resetting the timer after Search::clear()
`        else if (token == "ucinewgame") { Search::clear(); elapsed = now(); }`
in uci.cpp. 

Additionally, I would change the order of the commands in benchmark.cpp to
```
  list.emplace_back("setoption name Threads value " + threads);
  list.emplace_back("setoption name Hash value " + ttSize);
  list.emplace_back("ucinewgame");
```
which seems to be more in sync with the UCI specs.
Can you give it a try?

**Comment by LouisZulli** [comment]
There seems to be an issue not related to bench. Single threaded search of startpos to depth 24 takes about twice as long with a 8192 MB transposition table than it does for a 16 MB table. Also, Stockfish is reporting about twice as many nodes as Cfish for what should be comparable searches?

Need to take a break from this, but something seems very wrong with Stockfish on my system. Does anything similar occur on a single core machine?

```
$ ./stockfish 
Stockfish 270619 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name Hash value 16
go depth 24
...
info depth 24 seldepth 34 multipv 1 score cp 65 nodes 22690004 nps 1478754 hashfull 1000 tbhits 0 time 15344 pv g1f3 d7d5 d2d4 c7c5 c2c4 e7e6 c4d5 e6d5 c1g5 f8e7 g5e7 g8e7 d4c5 b8d7 b1c3 d7c5 e2e3 e8g8 f1e2 c5e4 e1g1 c8g4 c3b5 g4f3 e2f3
bestmove g1f3 ponder d7d5
quit

$ ./stockfish
Stockfish 270619 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name Hash value 8192
go depth 24
...
info depth 24 seldepth 38 multipv 1 score cp 73 nodes 23430422 nps 677649 hashfull 25 tbhits 0 time 34576 pv d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 b1c3 c7c5 c4d5 e6d5 c1g5 f8e7 d4c5 e8g8 e2e3 h7h6 g5f4 e7c5 f1d3 b8c6 e1g1 c8g4 h2h3 g4f3
bestmove d2d4 ponder d7d5
quit
```

```
$ ./cfish
Cfish 210619 64 BMI2 NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Hash value 16
go depth 24
info string Binding thread 0 to node 0.
...
info depth 24 seldepth 31 multipv 1 score cp 83 nodes 14091126 nps 1776714 hashfull 1000 tbhits 0 time 7931 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 f8b4 c1g5 e8g8 e2e3 c7c5 c4d5 e6d5 f1e2 c5c4 e1g1 b4c3 b2c3 c8f5 f3h4 f5d7 f1e1 h7h6 g5f6 d8f6 h4f3 b8c6 a1b1
bestmove d2d4 ponder g8f6
quit

$ ./cfish
Cfish 210619 64 BMI2 NUMA by Syzygy based on Stockfish
info string NUMA enabled.
setoption name Hash value 8192
go depth 24
info string Binding thread 0 to node 0.
...
info depth 24 seldepth 31 multipv 1 score cp 61 nodes 12007350 nps 1524162 hashfull 15 tbhits 0 time 7878 pv e2e4 e7e6 g1f3 d7d5 e4d5 e6d5 d2d4 g8f6 f1d3 c7c5 c2c3 c5c4 d3c2 f8d6 d1e2 c8e6 f3g5 d8e7 g5e6 e7e6 e2e6 f7e6 b1d2 e8g8 d2f3 b8d7 c1d2 e6e5 d4e5 d7e5 f3e5 d6e5
bestmove e2e4 ponder e7e6

```

**Comment by LouisZulli** [comment]
More data. First is Stockfish-master. Second is Stockfish-master with Joerg's patch. Third is same as second, but bound to one NUMA node:

```
$ ./stockfish bench 8192 1 13 >> /dev/null
===========================
Total time (ms) : 8969
Nodes searched  : 3402454
Nodes/second    : 379357

$ ./stockfish bench 8192 1 13 >> /dev/null
===========================
Total time (ms) : 3832
Nodes searched  : 3402454
Nodes/second    : 887905

$ numactl --cpubind=0 --membind=0 ./stockfish bench 8192 1 13 >> /dev/null
===========================
Total time (ms) : 2274
Nodes searched  : 3402454
Nodes/second    : 1496241
```

**Comment by snicolet** [comment]
What is the status of this issue?
I sort of understand that there may be possible improvement with our NUMA implementation on Windows?

**Comment by LouisZulli** [comment]
I say close this. It was raised here prematurely, and likely involves a number of things. I can always raise a new issue if/when I understand better what is actually happening. NUMA-awareness is likely involved, and it is not confined to Windows, since I'm running a Linux system. But I can't believe that better NUMA handling would give a 35% speed increase. So more testing is needed.

**Comment by snicolet** [comment]
OK, thanks
