### ISSUE TITLE
Blunder in CCC

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2213]
I draw your attention to Game 432 in CCC9, where SF lost against Stoofvlees as black. In this position:
r1b2rk1/3n1pb1/2p1p1p1/p5P1/Pp2B1NQ/2q3P1/3R1P2/3R2K1 w - - 6 33
SF thinks white has a slight advantage. Stoofvlees played Rc2, expecting SF to reply with Qxc2. SF instead played Qb3, and as soon as Stoofvlees played Rxc7 SF's eval shot up to M19.
Can someone check this position out? Missing mate like this seems really weird. Also worth mentioning is that Qxc2 had in fact been in SF's PV the move before, but then SF changed its mind and played Qb3 instead. SF's eval also randomly dropped to -1.69 a couple of moves later, and then shot right back up.

**Comment by LouisZulli** [comment]
_Stoofvlees_ played 33. Rc2. Stockfish played 33...Qb3 (and not Qxc2), allowing mate-in 17.

Here is the position where Stockfish (Black) blundered: r1b2rk1/3n1pb1/2p1p1p1/p5P1/Pp2B1NQ/2q3P1/2R2P2/3R2K1 b - - 7 33

**Comment by adentong** [comment]
@LouisZulli You're right. I have updated the post accordingly.

**Comment by LouisZulli** [comment]
Stockfish-dev (with clear hash) takes a _very_ long time to see 34. Rxd7 while searching the position I posted above.

`info depth 53 seldepth 99 multipv 1 score cp -82 upperbound nodes 29757974807 nps 27302848 hashfull 1000 tbhits 0 time 1089922 pv c3b3 d1d7`

Eventually, Stockfish realizes it cannot allow 34. Rxd7, and switches to 33...Qxc2:

`info depth 53 seldepth 99 multipv 1 score cp -109 lowerbound nodes 39155979209 nps 27014948 hashfull 1000 tbhits 0 time 1449419 pv c3c2`

**Comment by Alayan-stk-2** [comment]
With 64th and 32GB hash, Occy reported it took SF 7.5B nodes to find the move. In my case, SFdev with 3th and 2GB hash took 13B nodes to switch to Rxd7.

In the continuations after Rxd7 Bxd7, white is down 2 pawns and a rook for a few moves, so it just gets pruned to death. The mate threat using the pawn on f6 and the queen threatening to go to g7 (the black king can't escape from the corner) following Nf6 Bxf6 gxf6 is missed.

**Comment by gonzalezjo** [comment]
Here is Bryan's reverse analysis of the game. https://groups.google.com/d/msg/fishcooking/G423KIiYC8s/33IdqBQ6BQAJ

**Comment by adentong** [comment]
Well something similar happened in CCC9 finals game 142. I don't believe there's anything to fix; it's simply how SF operates: aggressive pruning at the expense of blundering in a few positions.
