### ISSUE TITLE
Skill Levels

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#2216]
Considering that no GUI that I am  aware of can handle the new skill parameters, I submit for consideration  and discussion code snippets that would double the levels in manner that is consistent with the original skill level  code and revert the recently committed changes with no functional changes other than that old skill level "1" is now "2" , old skill level "2" is now "4" etc. etc and so forth until old skill level "20" is now skill level "40" and the new skill level are all of the odd number skill levels.  It is a simpler approach that all GUIs can handle now and it doubles the number of levels.   Using floating point decimals is not logical here since we use the mod of weakness in the "magic formula" and essentially we are capped by the magic formula to just 40 levels anyway ( the max value of weakness is 120 when at level 0 ( 120 - 0), the min value of weakness is 80 ( 120 - 40), the difference of the max and the min values represents how many levels the magic formula currently accommodates.

Edit : Just for clarification , we currently have 20 weaker levels, level 0 through 19 ( a count of 20) and at level 20 SF, is at full strength, in total we have 21 levels, one at full strength and 20 weaker levels.  With my suggestion below , it would be 40 weaker levels ( skill level 0 to 39 ) and level 40 would be full strength , 41 levels in total. 

the magic formula to weaken SF
```
        // This is our magic formula
        int push = (  weakness * int(topScore - rootMoves[i].score)
                    + delta * (rng.rand<unsigned>() % weakness)) / 128;
```

search.cpp:   this would change the number of weaker levels to 40 ( o thru 39) , while keeping the same functionality we had with weakening today - except double the number of levels
```
    bool enabled() const { return level < 40; }  // changed from  "bool enabled() const { return level < 20; } "

   int weakness = 120 - level);   //changed from  "int weakness = 120 - 2 * level;"
```

ucioption.cpp

```
    o["Skill Level"]              << Option(40, 0, 40); // changed from  "o["Skill Level"]              << Option(, 0, 20);"
````

Edit:
It would be nice if you give this a thumbs down the reasoning for the thumbs down so that any potential areas of concern could be addressed.  It's hard to respond when there is no verbiage.

**Comment by LouisZulli** [comment]
Good point about GUIs.

Options of type "spin" are supposed to be integers:

From the UCI specifications: spin  = a spin wheel that can be an integer in a certain range
option name Skill Level type spin default 20 min 0 max 20

**Comment by MichaelB7** [comment]
There is not much discussion about this - it's certainly not a high priority for most people.  I will proceed forward and make the pull request for 41 levels , up from the current 21 and whatever happens, happens.  I do agree with with @vondele that the gap between current 21 levels is too large.  Unfortunately his patch is non functional as it it requires updates to the GUI that may actually be contrary to the current UCI specs per @LouisZulli comment above.
