### ISSUE TITLE
Skill Level Weird Bestmove Issue

### ISSUE THREAD

**Issue by xigua** [official-stockfish/Stockfish#2217]
I am testing a very straight forward mate in one puzzle 7R/2r2pk1/p5p1/1pp3P1/8/P6R/1PP5/2K5 w - - 0 3

And try to use different skill level of stockfish 10 to solve the puzzle but got some very strange result.

I am using the following commands
setoption name Skill Level value 1
ucinewgame
position fen '7R/2r2pk1/p5p1/1pp3P1/8/P6R/1PP5/2K5 w - - 0 3'
go depth 10

It will return the following
info depth 1 seldepth 1 multipv 1 score mate 1 nodes 141 nps 141000 tbhits 0 time 1 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 405 nps 405000 tbhits 0 time 1 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 597 nps 597000 tbhits 0 time 1 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 775 nps 387500 tbhits 0 time 2 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 952 nps 476000 tbhits 0 time 2 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 1133 nps 566500 tbhits 0 time 2 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1318 nps 659000 tbhits 0 time 2 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1507 nps 753500 tbhits 0 time 2 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1702 nps 851000 tbhits 0 time 2 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1900 nps 950000 tbhits 0 time 2 pv h3h7
bestmove b2b3 ponder c7d7

The first discovery is bestmove "b2b3" doesn't match with pv in all 10 depth "h3h7". If we can explain that bestmove is adjusted due to the skill level setting and skill level = 1 is not very strong (although it's just a mate in one puzzle). Then I tried different skill level, I found when skill level = 20, it's consistently having correct bestmove "h3h7" however, even with skill level=18, I am still getting incorrect bestmove:
setoption name Skill Level value 18
go depth 10
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 122 nps 61000 tbhits 0 time 2 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 283 nps 141500 tbhits 0 time 2 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 438 nps 219000 tbhits 0 time 2 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 593 nps 296500 tbhits 0 time 2 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 748 nps 374000 tbhits 0 time 2 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 903 nps 451500 tbhits 0 time 2 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1058 nps 529000 tbhits 0 time 2 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1213 nps 606500 tbhits 0 time 2 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1368 nps 684000 tbhits 0 time 2 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1526 nps 763000 tbhits 0 time 2 pv h3h7
bestmove h3h7
go depth 10
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 122 nps 61000 tbhits 0 time 2 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 283 nps 141500 tbhits 0 time 2 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 438 nps 219000 tbhits 0 time 2 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 593 nps 296500 tbhits 0 time 2 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 748 nps 374000 tbhits 0 time 2 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 903 nps 451500 tbhits 0 time 2 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1058 nps 529000 tbhits 0 time 2 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1213 nps 606500 tbhits 0 time 2 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1368 nps 684000 tbhits 0 time 2 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1526 nps 763000 tbhits 0 time 2 pv h3h7
bestmove h3h7
go depth 10
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 122 nps 122000 tbhits 0 time 1 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 283 nps 283000 tbhits 0 time 1 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 438 nps 438000 tbhits 0 time 1 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 593 nps 593000 tbhits 0 time 1 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 748 nps 748000 tbhits 0 time 1 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 903 nps 903000 tbhits 0 time 1 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1058 nps 1058000 tbhits 0 time 1 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1213 nps 1213000 tbhits 0 time 1 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1368 nps 1368000 tbhits 0 time 1 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1526 nps 1526000 tbhits 0 time 1 pv h3h7
bestmove a3a4 ponder b5a4
go depth 10
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 122 nps 122000 tbhits 0 time 1 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 283 nps 141500 tbhits 0 time 2 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 438 nps 219000 tbhits 0 time 2 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 593 nps 296500 tbhits 0 time 2 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 748 nps 374000 tbhits 0 time 2 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 903 nps 451500 tbhits 0 time 2 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1058 nps 529000 tbhits 0 time 2 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1213 nps 606500 tbhits 0 time 2 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1368 nps 684000 tbhits 0 time 2 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1526 nps 763000 tbhits 0 time 2 pv h3h7
bestmove a3a4 ponder b5a4
go depth 10
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 122 nps 61000 tbhits 0 time 2 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 283 nps 141500 tbhits 0 time 2 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 438 nps 219000 tbhits 0 time 2 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 593 nps 296500 tbhits 0 time 2 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 748 nps 374000 tbhits 0 time 2 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 903 nps 451500 tbhits 0 time 2 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1058 nps 529000 tbhits 0 time 2 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1213 nps 606500 tbhits 0 time 2 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1368 nps 684000 tbhits 0 time 2 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1526 nps 763000 tbhits 0 time 2 pv h3h7
bestmove c2c3 ponder c7d7
go depth 10
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 122 nps 122000 tbhits 0 time 1 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 283 nps 283000 tbhits 0 time 1 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 438 nps 438000 tbhits 0 time 1 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 593 nps 593000 tbhits 0 time 1 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 748 nps 748000 tbhits 0 time 1 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 903 nps 903000 tbhits 0 time 1 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1058 nps 1058000 tbhits 0 time 1 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1213 nps 1213000 tbhits 0 time 1 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1368 nps 684000 tbhits 0 time 2 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1526 nps 763000 tbhits 0 time 2 pv h3h7
bestmove c2c3 ponder c7d7

interesting thing is, I ran the same command "go depth 10" 6 times, and I got 3 different bestmoves although infos were very consistent at h3h7.

Did I understand it wrong? To my understanding, skill level 18 should not do wrong in this simple mate in one puzzle.

Thanks a lot.

**Comment by creatorkuang** [comment]
I'm confused, too. Anyone know why?

**Comment by gvreuls** [comment]
This is how it's supposed to be. If you set a skill level the engine picks a sub par move **at random**. The skill level determines how large the list of sub par moves the engine picks form will be, the lower you set the skill level the larger this list will become so the engine will pick a worse move on average.

**Comment by MichaelB7** [comment]
Not a good test position for skill level usage since there are at least 10 moves that are mate-in-2 , the value between mate in 2 and mate in 1 is small.  So although the randomness for  level 18 is small, it's big enough to switch the move to a longer mate.  So, yes skill levels would clearly impact mate problems , especially when the DTM difference is just one move.  Skill level is designed for human play and not mate problems, but i'm sure you know that and you were just curious to see the impact.

**Comment by xigua** [comment]
Understood now. But then what the information about 'pv' in each info means? Is it the best option that the skill level can come up with given the thinking depth? Can we use pv as 'real bestmove' instead? 

Another question, how can we mimic a human player with ELO=600 (for example) using stockfish?

Really appreciate the help and enlightening.

**Comment by joergoster** [comment]
@xigua You're still getting incorrect moves even at Skill Level 18 because you didn't issue a 'ucinewgame' command after changing the setting.

**Comment by joergoster** [comment]
What really seems to be missing is the output of the picked, sub-optimal PV line ...

**Comment by xigua** [comment]
@joergoster I just ran the command again but still got "not the bestmove" bestmove :)

setoption name Skill Level value 18
ucinewgame
position fen '7R/2r2pk1/p5p1/1pp3P1/8/P6R/1PP5/2K5 w - - 0 3'
go depth 10
info depth 1 seldepth 1 multipv 1 score mate 1 nodes 141 nps 70500 tbhits 0 time 2 pv h3h7
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 405 nps 101250 tbhits 0 time 4 pv h3h7
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 597 nps 119400 tbhits 0 time 5 pv h3h7
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 775 nps 155000 tbhits 0 time 5 pv h3h7
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 952 nps 190400 tbhits 0 time 5 pv h3h7
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 1133 nps 226600 tbhits 0 time 5 pv h3h7
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1318 nps 263600 tbhits 0 time 5 pv h3h7
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1507 nps 301400 tbhits 0 time 5 pv h3h7
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1702 nps 340400 tbhits 0 time 5 pv h3h7
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1900 nps 316666 tbhits 0 time 6 pv h3h7
bestmove a3a4 ponder b5a4

what does the pv line in each info line really means? ^_^

**Comment by gvreuls** [comment]
The pv line is the sequence of best moves for both players regardless of whether you set a skill level or not, so the lower you set the skill level, the smaller the chance that the bestmove (which is the 1st move in th pv) gets played and consequentially the smaller the chance that the pv will appear on the board.

**Comment by xigua** [comment]
@gvreuls so pv is always from skill level=20 which is the strongest, right? Thanks for the info, very helpful. :)

**Comment by gvreuls** [comment]
@xigua Yes, unless you also set MultiPV to a value > 1 of course. If you set MultiPV to N you get N best pv lines, so you don't only get the best pv but also the second best, etc. (Note that setting MultiPV > 1 slows down the search.)

**Comment by MichaelB7** [comment]
@xigua xigua
> Another question, how can we mimic a human player with ELO=600 (for example) using stockfish?

The best you can do is set Skill Level to 0 and with a very short time control.  I believe it will still be stronger than 600 Elo. Alternatively, there are plenty of other engines that can made to play much weaker than Stockfish' weakest setting. 

Micro Chess 1976 is about 600 Elo, as the name implies, it was written in 1976.  I believe it can be run under an xBoard compatible GUI such as WInboard based on this link

http://www.andreadrian.de/schach/index.html ( search for Micro Chess)

**Comment by xigua** [comment]
@gvreuls got it, deeply appreciated!

**Comment by xigua** [comment]
thanks a lot for all the help. Now I understand it's by design where pv is always the strongest move but bestmove might vary due to different skill level setting. ^_^
