### ISSUE TITLE
Stockfish performance drops

### ISSUE THREAD

**Issue by Zeytec** [official-stockfish/Stockfish#2249]
The current version of Stockfish 10 comes with me with several tests only on an average ELO of 2300. Normally Stockfish is however much stronger. My computer is quite powerful. My computer features are attached below.
[info.txt](https://github.com/official-stockfish/Stockfish/files/3398990/info.txt)

Cann you help me ?

**Comment by Rocky640** [comment]
Please use https://groups.google.com/forum/?fromgroups=#!forum/fishcooking for such discussion.

Once there, you will have to provide more details:

Which GUI do you use to run your tests ?
What tests exactly ?
How do you came to the conclusion of ELO 2300 ?
What are your SF settings ? Are you using tablebases ?

How many CPU you have on your Win10 laptop ?

**Comment by snicolet** [comment]
Discussion should be moved to the fishcooking forum, closing.
