### ISSUE TITLE
ICC: -fast should be last

### ISSUE THREAD

**Issue by pdknsk** [official-stockfish/Stockfish#225]
With `icc`, `-m` is similar to `-march`, and thus not additional, but overrides some previously set flags.

``` Bash
$ icc -mavx -msse
icc: command line warning #10120: overriding '-mavx' with '-msse'
```

Stockfish uses `-fast` for optimised builds, which is [short](https://software.intel.com/en-us/node/522804) for other flags. Such as `-xHost`, which can be overriden by the later set `-msse` and `-msse3` flags. It makes for slower builds.

**Comment by zamar** [comment]
As long as gcc provides faster builds than icc, we have no motivation to fix this, but we can leave this issue open as a reminder.

**Comment by vondele** [comment]
@zamar, since -fast was removed should this issue be closed ?

More drastically, should icc support be removed from the Makefile (removes about 40 lines)?

**Comment by zamar** [comment]
Yeah, this one can be closed.

We still want to do ICC compiles every now and then for verification purposes.
