### ISSUE TITLE
SF becomes unresponsive after ucinewgame during search

### ISSUE THREAD

**Issue by fohristiwhirl** [official-stockfish/Stockfish#2262]
```
uci
ucinewgame
position startpos
go infinite
ucinewgame
```

After this, further commands have no effect.

**Comment by joergoster** [comment]
Although it makes no sense to send a 'ucinewgame' command while the engine is still thinking, and I don't think any GUI or cli tool will do this, it seems more appropriate to simply ignore unexpected commands.

From the protocol:
> * if the engine receives a command which is not supposed to come, for example "stop" when the engine is
>   not calculating, it should also just ignore it.

and

> * go
> 	start calculating on the current position set up with the "position" command.
> 	There are a number of commands that can follow this command, all will be sent in the same string.
> 	If one command is not sent its value should be interpreted as it would not influence the search.
> ...
> 	* infinite
> 		search until the "stop" command. Do not exit the search without being told so in this mode!
> 

However, I'm not sure the maintainers are very inclined to guard against this kind of wrong usage.

**Comment by fohristiwhirl** [comment]
Hmm, I think there's nothing in the letter of the UCI specs that prevent `ucinewgame` from being sent whenever.

* ucinewgame
   this is sent to the engine when the next search (started with "position" and "go") will be from
   a different game.

...unless this is supposed to specify that position and go will be the next commands sent.

But yes, you're probably right, nobody should do this.
