### ISSUE TITLE
Stockfish keeps crashing in my Python script

### ISSUE THREAD

**Issue by rayoh123** [official-stockfish/Stockfish#2292]
https://www.reddit.com/r/ComputerChess/comments/d248tn/why_did_stockfish_just_randomly_crash_on_me_as_i/

Does stockfish do this for anyone else?

**Comment by snicolet** [comment]
The provided FEN is illegal, closing.

**Comment by rayoh123** [comment]
Hi, I discovered another FEN for which stockfish simply takes forever to analyze: "r4rk1/pb4pp/4p1q1/2p1Bpn1/2Q5/1P6/P1P2PPP/R4RK1 b "
This particular FEN is not illegal and I can't find anything wrong with it. 

import chess
import chess.engine

engine = chess.engine.SimpleEngine.popen_uci("stockfish")

with engine.analysis(chess.Board("r4rk1/pb4pp/4p1q1/2p1Bpn1/2Q5/1P6/P1P2PPP/R4RK1 b ")) as analysis:
    for info in analysis:
        print(info.get("score"), info.get("pv"))

        # Unusual stop condition.
        if info.get("hashfull", 0) > 900:
            break

engine.quit()
