### ISSUE TITLE
Syzygy tables are not valid for positions with castling possible but SF uses them anyway

### ISSUE THREAD

**Issue by sf-x** [official-stockfish/Stockfish#230]
When analysing the following position:
2k5/3P4/8/8/8/8/1r5p/R3K3 b Q - 0 1 
bestmove with 5-men tables is c8d7, with "black wins" score.
If one makes that move and analyses the resulting position without syzygy, SF shows a "white wins" score.

The cause is probably the tablebase result being used without checking if castling rights exist.

**Comment by zamar** [comment]
Thanks for bringing this up.

We'll fix this issue post SF6.

**Comment by lantonov** [comment]
I have a black win with or without Syzygy, and with or without castling. For example, without Syzygy:
1. Kd8 2. O-O-O Rg2 -99.78

**Comment by sf-x** [comment]
You didn't make c8d7 move in the no-Syzygy case, as described above.

**Comment by lantonov** [comment]
Sorry, my fault. Program hasn't loaded Syzygy when I thought it has.

**Comment by lucasart** [comment]
fixing this inevitably means adding a test for castling rights in the hot path... not sure it's worth it.

**Comment by stockfishdeveloper** [comment]
Would this be a problem with the tablebases or Stockfish?

**Comment by Vinvin20** [comment]
If at least one castling is possible : don't call Syzygy's.
