### ISSUE TITLE
Compile: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by eljake** [official-stockfish/Stockfish#2308]
After the commit db00e162
With make profile-build ARCH=x86-64-bmi2 COMP=gcc
Step 2/4. Running benchmark for pgo-build ...
./stockfish bench > /dev/null
Illegal instruction (core dumped)
make: *** [Makefile:425: profile-build] Error 132

It compiles well with make profile-build ARCH=x86-64 COMP=gcc
The issue has something to do  with SSE4 and BMI2 after commit db00e162 - (4 days ago) Add sse4 if bmi2 is enabled - Joost VandeVondele

gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0

cpu family	: 6
model		: 42
model name	: Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
stepping	: 7

flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

Jake

**Comment by MichaelB7** [comment]
That’s an older cpu , now 8 years old, originally issued in 2011, although issued 4 years after SSE4 was released , some early CPIs that supposedly supported SSE4 , actually did not.  See if returning the flag to SSE3 works.

**Comment by MichaelB7** [comment]
Also, if that is the issue , as it seems , try
“make profile-build ARCH=x86-64-modern  COMP=gcc”

Often , for these older CPUs that  allegedly supported avx and sse4, which technically fall under the bmi2 builds , would build a faster exe using “modern” anyway ,   which would include the popcnt and sse3 flags and exclude avx and sse4 flags.   I recall early on , the avx flag was very problematic for some some CPUs that were supposed to support it.

**Comment by eljake** [comment]
It is a lovely old Lenovo W520 - i probably need to upgrade to something more modern soon. :) 
Changing from SSE4 to SSE3 still core dumps.
 Flags
-lgcov -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse3 -mbmi2 -flto

It works when compiling with make profile-build ARCH=x86-64-modern COMP=gcc

Total time (ms) : 2692
Nodes searched  : 4272173
Nodes/second    : 1586988

Thanks

**Comment by WOnder93** [comment]
> flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

There is no "bmi2" among these flags, so why would you expect the BMI2 build to work at all? It looks like it shouldn't have been working on your CPU even before db00e16...

**Comment by eljake** [comment]
> > flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
> 
> There is no "bmi2" among these flags, so why would you expect the BMI2 build to work at all? It looks like it shouldn't have been working on your CPU even before [db00e16](https://github.com/official-stockfish/Stockfish/commit/db00e1625eb46517f61085ffd3bcd28779e71220)...

But it did work and has worked for years. 
Therefor my initial suspicion was that particular build. Rolling back to the build prior db00e16 yields no error at all.

Cheers.
