### ISSUE TITLE
Travis CI gone missing

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2314]
for whatever reason, our PRs are no longer tested by travis, which is our main platform for CI. The .travis.yml file is still in the root directory unchanged, so it must be something else.

Any ideas?

**Comment by vondele** [comment]
The testing is seemingly still running, it just doesn't show up in the github pages. 

see e.g. https://travis-ci.org/official-stockfish/Stockfish/builds/587768841 for the latest PR

Maybe this is something that will fix itself?

**Comment by snicolet** [comment]
Yes, we can see them there for instance:
https://travis-ci.org/official-stockfish/Stockfish/pull_requests

Can we open a PR which would break Travis CI on purpose to see what happens and if we get notified on our github PR page?

**Comment by vondele** [comment]
https://github.com/official-stockfish/Stockfish/pull/2315

**Comment by vondele** [comment]
failed https://travis-ci.org/official-stockfish/Stockfish/jobs/587782988

but is right now not visible on the PR.

**Comment by snicolet** [comment]
The symptoms are somewhat similar to https://github.com/travis-ci/travis-ci/issues/9440

**Comment by vondele** [comment]
I think this is due to some changes at github:
```
Note: GitHub Services have been deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps. 
``` 
and in my clone, I fixed this by deleting and reinstalling the travis setup. Possibly just deleting under 'Integrations & services' would be enough, but this needs testing. 

@snicolet do you have access to 
https://github.com/official-stockfish/Stockfish/settings/
and 
https://travis-ci.org/official-stockfish/

if not @mcostalba needs to do this, or you need ownership rights to official-stockfish (which wouldn't be a bad idea)

**Comment by snicolet** [comment]
@vondele Yes, I have access to both https://github.com/official-stockfish/Stockfish/settings/ and https://travis-ci.org/official-stockfish/

Under Integration and Services, the service for Travis is there but inactive, I didn't delete it yet.
Under WebHooks, we have both AppVeyor and Travis, I didn't delete any but just edited the Travis one (adding a trigger for creating milestones, which we never do): let's see what happens with this PR: https://github.com/official-stockfish/Stockfish/pull/2318

**Comment by snicolet** [comment]
Hmmm, for my PR #2318 there is something strange: 

a) the AppVeyor failed for the commit for the wrong bench (as it should)

b) Then I pushed another commit on the same branch with the good bench but a data race, this time the AppVeyor ran fine, but the Travis WebHook ran Travis on the **previous** commit (and did not detect the spurious data race)

**Comment by vondele** [comment]
good thing... travis now appears on your PR #2318, so it is back.

For me it looks good, if you click on the red cross next to your first commit on the PR, it fails both travis and appveyor. The race one is still pending in travis, while we should expect it to pass in appveyor.

**Comment by snicolet** [comment]
But now in #2318 Travis passed on the second commit ( eef877c ) when it should not have because this commit is the data race.

**Comment by snicolet** [comment]
Is Valgrind deterministic? Can it detect all data races? This sounds like equivalent to the Halting Problem, so I guess they do it by trial/errors?

**Comment by vondele** [comment]
Also my race test needed two trials... it more like it is observing if there is a race, which depends on the actual ordering between reads & writes of the threads, etc. It can only prove things wrong, not prove right.

The race checking is done by the sanitizers not by valgrind, and can be tested on the command line (assuming one has a recent enough gcc):
```
 make clean && make -j2 ARCH=x86-64 sanitize=thread    optimize=no debug=yes build > /dev/null && ../tests/instrumented.sh --sanitizer-thread
```

**Comment by vondele** [comment]
looks like things work again. I'll close this issue, and reopen if needed.
