### ISSUE TITLE
Crash on particular legal position

### ISSUE THREAD

**Issue by noobpwnftw** [official-stockfish/Stockfish#2316]
I have encountered some FEN like this:
rnbqkbnr/nnnnnnnn/8/8/8/8/nnnnnnnn/RNBQKBNR w KQkq - 0 1

The position itself although crafted, it is perfectly legal and SF shouldn't crash.

**Comment by snicolet** [comment]
How did Black managed to promote 16 pawns? :-)

**Comment by noobpwnftw** [comment]
OK, so one assumption is that for each side cannot have more than 16 pieces?

**Comment by snicolet** [comment]
At least that is what Marco wrote in Position::pos_is_ok()

**Comment by noobpwnftw** [comment]
Well doing this doesn't trigger asserts in `pos_is_ok` in debug builds, seems counter-intuitive.

**Comment by vondele** [comment]
the reason the assert is not triggered is because pos_is_ok does by default a 'fast' check. Which omits most checks. https://github.com/official-stockfish/Stockfish/blob/a858defd332bddd828c9280a9e326a0b750b3dda/src/position.cpp#L1252

**Comment by CoffeeOne** [comment]
> The position itself although crafted, it is perfectly legal and SF shouldn't crash.

That was a joke, right? I am referreing to "it is perfectly legal". Black has 24 pieces, but worse is that white is in check by 2 black knights.

**Comment by MichaelB7** [comment]
Anything with more than 8 pawns , 8 non pawns or 16 pieces  in Rita is not legal.  In addition, pawns should only exist on ranks two through 7. 
This is Basic 101 Chess.

**Comment by noobpwnftw** [comment]
OK, adding position sanitizer elsewhere.

**Comment by MichaelB7** [comment]
Just FYI, the generally accept rule when dealing with a composition, that is a chess position that is not from a game , but it was composed for the specific purpose of providing a problem. A constraint on the composition of an orthodox chess problem is that the original position be reachable via a series of legal moves from the starting position, most problem positions would not arise in over-the-board play.
