### ISSUE TITLE
Same Line, Different Values

### ISSUE THREAD

**Issue by MoonstoneLight** [official-stockfish/Stockfish#2317]
Hi,
I just want to know why same lines evaluated different.
Something like;
1.d4 e6 2.e4 d5 xyzxyzxyz...
1.e4 e6 2.d4 d5 xyzxyzxyz...
These kind of lines evaluated differently. Why?

**Comment by ddugovic** [comment]
This use case is incomplete.  How specifically did you test this?

**Comment by snicolet** [comment]
This is not a specific bug case, so the question would be better asked in the forum.
