### ISSUE TITLE
Flush standard output for our logging utility

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#2324]
On my system (Clang on Mac OS 10.13.6), the logger needs a `std::flush` to work properly. If not, I can get in a repeatable state where there is search info in the Terminal but not in the log file.

### Steps to reproduce:

1) compile Stockfish
2) in a Terminal, type
```
./stockfish
setoption name Debug Log File value logloglog.txt
```
3) open the file **logloglog.txt** in a text editor (for instance BBEdit)
4) in the Terminal, type
```
go depth 20
```

### Expected behaviour:

• The Terminal console shows the search up to depth 20, including the `bestmove e2e4 ponder e7e6` line
• the log file should also show the search up to depth 20, including the `bestmove` line.

### Observed behaviour:

• The Terminal console shows the search up to depth 20, including `bestmove e2e4 ponder e7e6`command
• the log file shows also the search only to depth 19. I have to close the file window in the text editor and reopen it to see the updated content.

### Fix:

Calling `std::flush` for the standard output in the `sync_endl` macro of misc.h is enough to make the bug disappear
```
   #define sync_endl std::endl << std::flush << IO_UNLOCK
```

**Comment by snicolet** [comment]
Would we have any performance degradation by adding `std::flush` in the `sync_endl` macro?

**Comment by gvreuls** [comment]
According to the standard `std::endl` already flushes the output stream, so it's weird this fixes the log problem on Mac.
[cppreference.com std::endl entry:](https://en.cppreference.com/w/cpp/io/manip/endl)
>**std::endl** Inserts a newline character into the output sequence os and flushes it as if by calling os.put(os.widen('\n')) followed by os.flush().

**Comment by Rocky640** [comment]
I don't have a Mac.
Some text editors have a menu to manually refresh the currently displayed text file.
Some text editors have settings to auto refresh.
Maybe the problem is with your text editor ?

**Comment by snicolet** [comment]
My text editor has the auto-refresh check box on, but it still does not get refreshed :( 
Adding the std::flush makes the problem less frequent, but not completely gone.

However **ls** sees the final size of the log file, so it is a problem with the editor.

Closing
