### ISSUE TITLE
How make chess engine to artificially play positionally

### ISSUE THREAD

**Issue by abdulbadii** [official-stockfish/Stockfish#2328]
What concept in making chess engine to play more positionally, quietly  and less aggressively
(sort of Capablanca or Karpov play style)
is it supposed to be tuned more in search or in evaluation,
or is there the latest AI/NN algorithm innovation has proved working well enough ?

**Comment by MichaelB7** [comment]
Not 100% sure what your question is , it seems to be missing some words.  But in any event , any question how to “artificially” make Stockfish play differently is best directed to the forum and not here.

**Comment by snicolet** [comment]
These are interesting questions indeed, but as suggested the best location to discuss is probably in the forum because "Issues" should be for discussing concrete bugs. Please repost in https://groups.google.com/forum/?fromgroups=#!forum/fishcooking :-)
