### ISSUE TITLE
Something is wrong with draw detection

### ISSUE THREAD

**Issue by karolm2** [official-stockfish/Stockfish#2343]
The following position is a draw:

2rqkb1r/1R1b1ppp/p3p3/3pP3/3B1P2/2N5/P1PQ2PP/5RK1 w k - 3 17

I've run latest Sockfish_dev (021019) many times here (deep search on 6 threads up to depth 65) and each time Stockfish gives the following line: 17.f5 exf5 18.Qd3 (the rest is forced) Bc5 19.Bxc5 Rxc5 20.Nxd5 Bb5 21.Qxf5 O-O 22.c4 Bxc4 23.Rd7 Rxd5 24.Rxd8 Rdxd8 25.Ra1 leading to a position with an imbalance  Q vs RB, where black can create some kind of fortress and make an easy draw. The strange thing is that in the given position Stockfish cannot detect 0.00 draw even after very deep search. Here is a sample line, where it gives +0.37 at depth 60.

1:58.28: +0.37/60 17.f5 exf5 18.Qd3 Bc5 19.Bxc5 Rxc5 20.Nxd5 Bb5 21.Qxf5 O-O 22.c4 Bxc4 23.Rd7 Rxd5 24.Rxd8 Rdxd8 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Be6 29.Qxa6 Rd8 30.Kf2 Rd2+ 31.Kg3 g6 32.h3 Kg7 33.Qa1 Ra2 34.Qc3 Ra8 35.Kf2 h6 36.Kg3 Ra2 37.Qd3 Ra1 38.Qd8 Ra3+ 39.Kh2 Ra2 40.Qd3 Ra8 41.Qd6 Ra2 42.Qd8 Rc2 43.Qf6+ Kh7 44.Qf3 Kg8 45.Qd3 Ra2 46.Qd4 Kg7 47.Kg1 Rc2 48.Qe3 Ra2 49.Qc3 Ra4 50.Qd3 Ra2 51.Qd1 Ra5 52.Qd6 Rd5 53.Qb8 Rd2 54.Qb4 Rc2 55.Qd4 Kh7 56.Kh2 Kg7 57.Qe4 Rc8 58.Kg3 Rc4 59.Qe2 Rc5 60.Qb2 Rc4 61.Kf2 Rc8 62.Kf3 Ra8 63.Qd4 Ra2 64.Qc5 Rd2 65.Qc3 Rd8 66.Qe3 Rc8 67.g4 Rc2 68.Qd4

Now, when I start analysis from the position after 17.f5 exf5 18.Qd3 Bc5 19.Bxc5 Rxc5 20.Nxd5 Bb5 21.Qxf5 O-O 22.c4 Bxc4 23.Rd7 Rxd5 24.Rxd8 Rdxd8 - Stockfish finds 0.00 almost immediately.

5.13 25.Ra1 (depth 60, 1/35), 2,8G nodes (8,9M nps), 2,7M tbhits
0.00: +1.03/3 25.Rc1 Bxa2 26.Rc2
0.00: +1.03/4 25.Rc1 Bxa2 26.Rc2 Rd1+ 27.Kf2
0.00: -0.65/5 25.Qf4 Bxf1 26.Kxf1 Rfe8 27.Ke2
0.00: +1.00/6 25.Rc1 Bxa2
0.00: +0.92/7 25.Rc1 Bxa2 26.Qf4 Bd5 27.Ra1 Rfe8 28.Rxa6
0.00: +0.55/8 25.Re1 Bxa2 26.Ra1 Bd5 27.Qf4 h6 28.Qh4
0.00: +0.37/9 25.Rc1 Bxa2 26.Qf4 Be6 27.Ra1 a5 28.Rxa5 Rd1+ 29.Kf2 Rc8 30.Kg3
0.00: +0.48/10 25.Re1 Bxa2 26.Ra1 Be6 27.Qf4 Rc8 28.h3 Rc4 29.Qf3 Rd8 30.Kh2
0.00: +0.51/11 25.Ra1 Rd4 26.Qg5 Be6 27.a3 h6 28.Qe3 Rfd8 29.Qc3 R8d5 30.Rc1
0.00: +0.86/12 25.Ra1 Rd4 26.Qc2 Be6 27.Qe2 Bc4 28.Qe3 Rfd8 29.Qc3 h5
0.00: +0.94/13 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Be6 29.Qxa6 Rc8 30.Qd3 Rc1+ 31.Kf2 Rc8 32.Ke3 h6 33.Qd2
0.00: +0.88/14 25.Ra1 Rd4 26.Qc2 Be6 27.Rd1 Rxd1+ 28.Qxd1 Bxa2 29.Qe2 Be6 30.Qxa6 h6 31.Qb6 Rc8 32.Qd4 Kh7 33.Kf2 Rc2+ 34.Kg3
0.00: +0.89/15 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Be6 29.Qxa6 Rc8 30.Qd3 h5 31.h3 Rc5 32.Qd4 Rc4 33.Qd1 h4
0.00: +0.48/16 25.Ra1 Rd4 26.Qc2 Rfd8 27.Qc3 Be6 28.a3 h6 29.Rc1 R4d5 30.h3 Rc8 31.Qe3 Rxc1+ 32.Qxc1 Rxe5 33.Qc6 Ra5
0.00: +0.60/17 25.Ra1 Rd4 26.Qc2 Rfd8 27.Qc3 Be6 28.a4 h6 29.Qa5 Rd2 30.Qxa6 Bd5 31.Qa5 Ba8 32.g3 Bf3 33.Qb6 R8d3 34.e6 Rg2+ 35.Kf1
0.00: +0.64/18 25.Ra1 Rd4 26.Qc2 Rfd8 27.Qa4 Be6 28.Qxa6 Rd1+ 29.Rxd1 Rxd1+ 30.Kf2 Rd2+ 31.Kg3 Rxa2 32.Qd6 h6 33.Qd8+ Kh7 34.Qd3+ Kg8 35.h4 g6 36.Qd8+ Kh7 37.Qd1 Kg8 38.h5 Ra3+ 39.Kf4 gxh5 40.Qxh5 Kg7
0.00: +0.66/19 25.Ra1 Rd4 26.Qc2 Rfd8 27.Qc3 Be6 28.a3 h6 29.Rb1 Rd2 30.Rb2 R2d3 31.Qc7 Kh7 32.h3 Rc8 33.Qa5 Rc1+ 34.Kh2 Ra1 35.a4 Rd4 36.Qxa6 Raxa4 37.Qe2 Ra1 38.Qc2+ g6 39.Qc3 Rd8 40.Kg3 Kg7 41.Rb8 Rxb8 42.Qxa1
0.00: +0.62/20 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.h3 h6 30.Qa5 Bc4 31.Qc5 Be6 32.Qd6 Ra8 33.Qc6 Rd8 34.Qxa6 Rd5 35.Qa1 Kh7 36.Qb1+ g6 37.Qb2
0.01: +0.11/21 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Be6 29.Qxa6 h6 30.Qa5 Rb8 31.Qa1 Rc8 32.Qd4 g6 33.Kf2 Rc2+ 34.Kg3 Kg7 35.h3 Ra2 36.Qd6 Rb2 37.h4 Ra2 38.Kf3
0.01: +0.16/22 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Be6 29.Kf2 Rc8 30.Qxa6 h6 31.Qd3 g6 32.h3 Kg7 33.g4 Ra8 34.Kf3 Rb8 35.Qf1 Kh7 36.Ke4
0.01: +0.10/23 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.h4 h6 30.Qxa6 Ra8 31.Qd3 Be6 32.Qd1 Rb8 33.Kf2 Rb2+ 34.Kg3 Rb3+ 35.Kf4 Rc3 36.h5 Rc4+ 37.Kg3 Rg4+ 38.Qxg4 Bxg4 39.Kxg4 Kf8 40.Kf5 Kg8
0.01: +0.07/24 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.Qc6 Rc4 37.Qa6 Rh4 38.Qa8+ Kh7 39.h3 Rb4 40.Kc3 Rc4+ 41.Kd2 Rb4 42.Kd3 Rb2 43.Ke3 Ra2 44.Qb7 Ra4 45.Kd3 g6 46.Qe7 Ra5 47.Qb4 Ra2
0.02: +0.03/25 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.Qc6 Rb4 37.Qa8+ Kh7 38.Ke3 g6 39.h3 Kg7 40.Qa6 Rb2 41.Qf1 Rc2 42.Kd4 Rc4+ 43.Qxc4 Bxc4 44.Kxc4 Kf8 45.Kc5 Ke7
0.02: **0.00**/26 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.Qc6 Ra5 37.Kd4 Rd5+ 38.Ke4 Ra5 39.Kd4
0.02: **0.00**/27 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.Qc6 Ra5 37.Qb6 Ra2 38.Qb8+ Kh7 39.Qb7 g6 40.Kd4 Rd2+ 41.Ke3 Rc2 42.h3 Rc3+ 43.Kd4 Rc4+ 44.Kd3 Ra4 45.Qc6 Ra2 46.Ke3 Rb2
0.02: **0.00**/28 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Kd4 Rd5+ 39.Ke3
0.02: **0.00**/29 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Kd4 Rd5+
0.02: **0.00**/30 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Qc3 Ra2 39.Qc6 Ra1 40.Qb7 Ra4 41.Kd3 Kg7 42.Qb2
0.02: **0.00**/31 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Qc3 Ra2 39.Qc6 Ra1 40.Qb7 Ra4 41.Qc6
0.03: **0.00**/32 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Qc3 Ra2 39.Qc6 Ra1 40.Qb7 Ra4 41.Kd3 Kg7 42.Kc3 Rc4+ 43.Kd2 Rc5 44.Qb2 Ra5 45.Ke3
0.03: **0.00**/33 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Qc3 Ra2 39.Qc6 Ra1 40.Qb7 Ra4 41.Kd3 Kg7 42.Kc3 Rc4+ 43.Kd2 Rc5 44.Qb2 Ra5 45.Ke3
0.04: **0.00**/34 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Qc3 Ra2 39.Qc6 Ra1 40.Qb7 Ra4 41.Kd3 Kg7 42.Kc3 Rc4+ 43.Kd3
0.05: 0.00/35 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Kh7 34.h3 g6 35.Kd3 Rc5 36.Qb2 Rd5+ 37.Ke3 Ra5 38.Qc3 Ra4 39.Qc6 Ra1 40.Qb7 Ra4 41.Kd3 Ra2 42.Kd4 Rc2 43.Qa8 Kg7 44.Ke3 Rc8 45.Qa6 Rc3+ 46.Kd4 Rc4+ 47.Kd3 Rc5 48.Qa1 Kh7 49.Ke3 Kg7 50.Kd4 Rc4+ 51.Kd3 Rc5 52.Qb2 Kh7 53.Ke3
0.05: **0.00**/36 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qe4+ g6 40.Qe2 Kg7 41.Qe1 Kh7 42.Kd3 Kg7 43.Qe3 Rb5 44.Kd4 Rd5+ 45.Kc3 Rb5 46.Kd4
0.06: **0.00**/37 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qe4+ g6 40.Qe2 Kg7 41.Qe1 Rc4 42.Kd3 Ra4 43.Ke3 Kh7 44.Qc3 Ra2 45.Qc6 Rb2 46.Qe4 Ra2
0.07: **0.00**/38 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qe4+ g6 40.Qe2 Kg7 41.Qe1 Rc4 42.Kd3 Ra4 43.Ke3 Kh7 44.Qc3 Ra2 45.Qc6 Rb2 46.Qe4 Kg7 47.Qa8 Rc2 48.Kd4 Rc4+ 49.Kd3 Rc5 50.Qa1 Rd5+ 51.Ke3 Rb5 52.Qd4 Kh7 53.Kf2 Rb3 54.Qa1 Kg8 55.Kg1 Kh7
0.08: **0.00**/39 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qe4+ g6 40.Qe2 Kg7 41.Qe1 Rc4 42.Kd3 Ra4 43.Ke3 Kh7 44.Qc3 Ra2 45.Qc6 Kg7 46.Kd3 Kh7
0.10: **0.00**/40 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qe4+ g6 40.Qe2 Kg7 41.Qe1 Rc4 42.Kd3 Ra4 43.Ke3 Kh7 44.Qc3 Ra8 45.Qd3 Ra2 46.Qf1 Ra5 47.Kd4 Rd5+ 48.Ke4 Rc5 49.Qf6 Rc2 50.g4 Re2+ 51.Kd4
0.12: **0.00**/41 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Ra3+ 38.Kd4 Ra4+
0.15: **0.00**/42 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Ra3+ 38.Kd4 Ra4+ 39.Kc5 Ra5+ 40.Kd6 Rd5+ 41.Ke7 Rxe5 42.Qb2 Rc5 43.Qb1+ Kg8 44.Qb6 Rc8 45.Qa5 Rb8 46.Qa7 Rc8 47.Qb6 Bd5 48.Qa5 Be6
0.17: **0.00**/43 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Rb2 43.Qe4 Rb5 44.Kf4 Kg7 45.Qa8 Rb2 46.Ke3 Kh7
0.19: **0.00**/44 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Rb2 43.Qe4 Rb5 44.Kf4 Kg7 45.Qa8 Rc5 46.Qa1 Kh7 47.Ke3 Rc2 48.Qa8 Rc3+ 49.Kf4 Kg7 50.Qb7 Rc4+ 51.Ke3 Rc3+
0.26: **0.00**/45 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Rb2 43.Qa8 Rc2 44.Kd4 Rc4+ 45.Kd3 Rc5 46.Qa1 Rd5+ 47.Ke2 Rc5 48.Ke3 Rc2 49.Qa8 Kg7 50.Kd4 Kh7 51.Qb7 Rc4+ 52.Kd3 Ra4 53.Qb8 Kg7 54.Qb2 Kh7
0.34: **0.00**/46 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Bf5 43.Kf4 Be6
0.38: **0.00**/47 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Rc4 43.Qa8 Rc3+ 44.Kd4 Rc4+
0.45: **0.00**/48 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Ra1 44.Qb7 Ra3+ 45.Ke4 Ra4+ 46.Kd3 Ra2 47.Kd4 Rc2 48.Qf3 Rc4+ 49.Kd3 Ra4 50.Qf6 Rb4 51.Qf2 Ra4
0.53: **0.00**/49 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Kg7 44.Qb5 Rc2 45.Qd3 Ra2 46.Qd6
1.05: **0.00**/50 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Ra3+ 44.Ke4 Ra2
1.13: **0.00**/51 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Rd2 44.Kf4 Re2 45.Qf3 Rd2
1.30: **0.00**/52 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Kg7 44.Qb5 Rc2 45.Qb7 Rc3+ 46.Kf4 Rc4+ 47.Ke3 Rc3+
1.43: **0.00**/53 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Kg7 44.Qb5 Rc2 45.Qb7 Rc3+ 46.Kf4 Rc4+ 47.Ke3 Rc3+
2.41: **0.00**/54 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Kg7 44.Qb5 Rc2 45.Qb7 Rc3+ 46.Kf4 Rc4+ 47.Ke3 Rc3+ 48.Kd4 Rc4+ 49.Kd3 Rc5 50.Qb2 Kh7 51.Kd4 Rd5+ 52.Ke4 Rc5 53.Qb7 Rc4+ 54.Kd3 Rc5 55.Kd4 Rc4+ 56.Ke3
3.16: **0.00**/55 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra4 42.Qc6 Ra2 43.Kf3 Kg8 44.Qb5 Kg7 45.Kg3 Kg8
3.19: **0.00**/56 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Kg7 43.Qb7 Ra3+ 44.Kd4 Ra4+ 45.Kc5 Ra5+ 46.Kd6 Rd5+ 47.Qxd5 Bxd5 48.Kxd5 g5 49.Kd6 Kg6 50.g3 Kf5 51.g4+ Kg6 52.Ke7 Kg7 53.Kd7 Kg6
4.26: **0.00**/57 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Kg7 43.Qb7 Ra3+ 44.Kd4 Ra4+ 45.Kc5 Rc4+ 46.Kd6 Rd4+ 47.Ke7 Rd7+ 48.Qxd7 Bxd7 49.Kxd7 g5 50.Ke7 Kg8 51.g3 Kg7 52.g4 Kg8 53.Kd6 Kg7 54.Kd7 Kg6 55.Ke7 Kg7 56.Ke8 Kg8 57.Ke7
4.50: **0.00**/58 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Ra5
5.13: **0.00**/59 25.Ra1 Rd2 26.Qf4 Rxa2 27.Rxa2 Bxa2 28.Qa4 Bd5 29.Qxa6 Ra8 30.Qb5 Be6 31.Qb7 Rc8 32.Kf2 h6 33.Ke3 Rc3+ 34.Kd4 Rc4+ 35.Kd3 Ra4 36.h3 Kh7 37.Kc3 Rc4+ 38.Kd2 Rc5 39.Qb2 g6 40.Ke3 Ra5 41.Qc3 Ra2 42.Qc6 Kg8 43.Kd4 Rd2+ 44.Kc3 Re2 45.Qb7 Kg7 46.Kd4 Kh7 47.Qf3 Rc2 48.Qf1 Rc4+ 49.Kd3 Rc5 50.Kd4

So my point is that something is wrong when it comes to detecting draws from distance.

edit: analysis contempt is of course set to off.

**Comment by vdbergh** [comment]
No progress draws are very hard to detect for A/B engines.

**Comment by karolm2** [comment]
I made a small investigation and it seems to me that these misevaluation issues are related to dynamic contempt. It's obvious to me that disabling Analysis Contempt should automatically make Dynamic Contempt disabled. Curently, with Analysis Contempt set to Off, Stockfish behaves like Dynamic Contempt is still active, which is very bad for analysis. I belive that there was a discussion about this issue in 2018, when Dynamic Contempt combo box idea was introduced. Can someone create a patch that turns off dynamic contempt while Analysis Contempt is being set to Off?

**Comment by snicolet** [comment]
Closing this issue, as it is not a direct bug but rather a discussion best suited for the forum.
