### ISSUE TITLE
Stockfish/fishtest projects: assets, responsabilities, governance

### ISSUE THREAD

**Issue by ppigazzini** [official-stockfish/Stockfish#2345]
# Stockfish
### GitHub account
https://github.com/official-stockfish
Type: Organization, GitHub Team for Open Source
Owners: @glinscott @mcostalba @zamar @snicolet

### Github repository (official-stockfish)
https://github.com/official-stockfish/Stockfish
Owners: @glinscott @mcostalba @zamar @snicolet @vondele
Team "Maintainers": @locutus2 @snicolet @vondele
Owners and Maintainers have "Admin" permission level on the repos

### CI (actions)
Owners: @glinscott @mcostalba @zamar @snicolet

### NN trainer repository
https://github.com/glinscott/nnue-pytorch
Type: Personal
Owner: @glinscott
Collaborators: @Sopel97 @vondele
Collaborators have "Write" permission level

### Wiki for Stockfish/Fishtest
https://github.com/glinscott/fishtest/wiki
Owner: @glinscott

#### Wiki page "Regression Tests"
https://github.com/glinscott/fishtest/wiki/Regression-Tests
Maintainer: @bknox83

### Stockfish Discord channel
https://discord.gg/nv8gDtt
Owner: @Disservin 

### Abrok (development versions)
http://abrok.eu/stockfish/
Owner: Roman Korba (roman.korba@t-online.de, korba.roman@gmail.com)

## Forum
https://groups.google.com/g/fishcooking
Owner: @mcostalba 

## History of past tests
https://groups.google.com/g/fishcooking-results
Owners: @ppigazzini @vondele @zungur
https://groups.google.com/g/fishcooking_results
Owner: @mcostalba

## Website (stockfishchess.org)
https://stockfishchess.org
on github as https://github.com/daylen/stockfish-web
Owner: @daylen
Maintainer: @daylen

## Domain stockfishchess.org + CDN
Owner: @daylen

## Twitter
https://twitter.com/stockfishchess
Owner: @daylen
Maintainer: @daylen

## Facebook
https://www.facebook.com/stockfishchess
Owner: @daylen
Maintainer: @daylen

---------------------------------------------

# Fishtest
### GitHub account
https://github.com/glinscott
Owner: @glinscott

### Fishtest repository
https://github.com/glinscott/fishtest
Type: Personal
Owner: @glinscott
Collaborators: @ppigazzini @zungur
Collaborators have "Write" permission level

### CI (actions)
Owners: @glinscott 

### VPS (tests.stockfishchess.org)
Owner: @glinscott
Maintainers: @ppigazzini @zungur

### Networks (data.stockfishchess.org)
Owner: @noobpwnftw
Maintainers: @ppigazzini @zungur @noobpwnftw @vondele 

### S3 Mongodb & Nets backups
Owner: @glinscott

### FishCooking repository (books and binaries)
https://github.com/official-stockfish/books
Owners: @glinscott @mcostalba @zamar @snicolet
Team "Maintainers": @locutus2 @snicolet @vondele
Owners and Maintainers have "Admin" permission level on the repo

---------------------------------------------
## People

| People | Status |
| --- | --- |
| @vondele | active |
| @snicolet | active |
| @glinscott | active |
| @mcostalba | inactive |
| @zamar | inactive |
| @daylen | active |
| @ppigazzini | active |
| @zungur | active |
| @noobpwnftw | active |
| @bknox83 | active |
| @Sopel97 | active |
| @locutus2 | active |

---------------------------------------------
## Governance
TL;DW

---------------------------------------------
## References
https://help.github.com/en/articles/setting-team-creation-permissions-in-your-organization

**Comment by ppigazzini** [comment]
Issue to collect information about the asset, responsibilities, governance of the Stockfish/fishtest project, when complete this should be published in the wiki.

To have a clear picture of the today situation and to decide if/how to make changes.

**Comment by snicolet** [comment]
Thanks for starting this thread!
I have added the owners of the official-stockfish github

**Comment by chessy1** [comment]
forum
https://groups.google.com/forum/#!forum/fishcooking
Owner:  @mcostalba

**Comment by ppigazzini** [comment]
@snicolet I insert the GitHub nomenclature to describe role and permission level, please review my changes.
If I'm not wrong https://github.com/official-stockfish should be a GitHub Organization.
I added also the ChessDBCN workers fleet because the fishtest maintainer must coordinate with @noobpwnftw before enforcing worker code changes.

**Comment by snicolet** [comment]
@ppigazzini Yes, https://github.com/official-stockfish is a GitHub organization. Marco created a team called Maintainers inside it, with admin privileges on the Stockfish repo.

I have added the Abrok site, which is a little bit independent but still very often used by everybody in the community.

**Comment by ppigazzini** [comment]
@snicolet IMO a natural step should be to promote you as owner of https://github.com/official-stockfish

**Comment by Vizvezdenec** [comment]
we can add approvers list, althuogh it will be pretty big.

**Comment by xoto10** [comment]
Not sure it's a good idea to publish the approvers, requiring approval is
how we stop people messing with fishtest by submitting fake tests.

**Comment by ppigazzini** [comment]
Congratulation to the new https://github.com/official-stockfish owner. Well deserved @snicolet !

**Comment by vondele** [comment]
as per https://github.com/official-stockfish/Stockfish/issues/2391 we should also track who owns the CI infrastructure (travis and appveyor).

**Comment by snicolet** [comment]
I have added Joost in the maintainers list. Welcome!

**Comment by Vizvezdenec** [comment]
Yeah if I thought about a substitute maintainer my first guess will be Joost :)
@vondele Good luck for you in this not that easy task :)

**Comment by ppigazzini** [comment]
Thank you @snicolet for the hard work!
Good luck @vondele :)

**Comment by tomtor** [comment]
I am sure @vondele will do an excellent job as did @snicolet !

**Comment by xoto10** [comment]
Thanks for all your hard work @snicolet excellent job :-)

And @vondele thanks for offering to do this !

**Comment by snicolet** [comment]
@glinscott @mcostalba @zamar 

Would it be possible to add @vondele to the "owner" list? That would ease the integration of the NNUE architecture on the site, as there are some actions he cannot do with the mere "maintainer" status.

**Comment by snicolet** [comment]
Added a link to the Stockfish discord channel

**Comment by ianfab** [comment]
The nodchip repo for the NNUE training code might also be worth adding.

**Comment by NightlyKing** [comment]
Ownership of the discord changed. Now "Additional Pylon" is in charge of managing the discord (with a handful of mods).

**Comment by ppigazzini** [comment]
@vondele added the "NN trainer" repository (shortcut used in fishtest home page), please review the maintainers/collaborators. Added also @bknox83 as maintainer of the Regression Tests wiki page :)

**Comment by NightlyKing** [comment]
@Disservin is now the owner of the discord server.

**Comment by Disservin** [comment]
The wiki is for now enabled in this repo but we ran into some problems regarding special permissions, currently its only possible to either have public edits or only collaborators with write permission (which means they could merge PR's too..) .
I have started to add a few sections to the wiki and also moved the content of this issue there so that for the future we can keep track of the information there.

https://github.com/official-stockfish/Stockfish/wiki/Governance-and-responsibilities

**Comment by vondele** [comment]
so now that this issue has been transferred to the wiki, we can close it as an issue here.

Many thanks to @ppigazzini for having started it, this is valuable information to have documented in this way.

**Comment by dav1312** [comment]
Probably should be unpinned now
