### ISSUE TITLE
iOS/GPL v3.0 Incompatibilty

### ISSUE THREAD

**Issue by MattFoley** [official-stockfish/Stockfish#235]
Hi,

I'd really love to work on an open source competitive multiplayer derivative of the StockFish app for iOS, unfortunately the technical reading of the law is that GPL is completely incompatible with iOS. 

Even if I release my final source code, and distribute the app entirely for free (which is definitely the plan), I could be sued later if I'm not given express permission from all contributors.

I've started this as a discussion on the StockFish support page, which references FSF's stance on iOS and it's GPL 3.0 license.

http://support.stockfishchess.org/discussions/questions/1550-licensing-of-entire-ios-app

Would it be possible for all contributors to agree to an addendum to the license allowing iOS App Store distribution? ie: "As an addendum to GPL 3.0, you have my permission to publish free derivative software to the iOS App Store, as long you distribute any modified source code."

Thank you!

**Comment by mcostalba** [comment]
I don't see how this can be recognized as a technical issue, please use the forum for these kind of comments. I am closing it now.
