### ISSUE TITLE
Contempt for maximum objective play

### ISSUE THREAD

**Issue by NKONSTANTAKIS** [official-stockfish/Stockfish#2357]
I open this issue in order to clarify a common misconception that contempt makes SF play objectively inferior moves which are elo gaining vs inferior opposition.
The truth is that contempt implementation is an elo gaining one, resulting into superior analysis and play. There are many indications for this but no proof yet.

As you can see here in the past despite c21 passing non-regression vs c0,
http://tests.stockfishchess.org/tests/view/5b1a170b0ebc5902ab9c3fde
**C10 proved an elo gain over C12 with [0,4] bounds**
http://tests.stockfishchess.org/tests/view/5a968d710ebc590297cc8ceb

Theoretically, the objective elo gaining curve of contempt rises up to a point and then falls, with 24 being just a tad weaker than 0. Some people speculate that this curve lies indistinguishably near neutral elo. From my research I lean towards 2-3 elo at peak curve which is estimated to lie around C= 8-10. Therefore, 

**I request a single C10 vs C0 [0,4] LTC**, with the purpose of:
1. Finally proving that contempt is a search-enhancing universal elo-gaining mechanism besides an elo-maximizing relatively to opposition one.
2. Helping ICCF analysts get the most out of SF.
3. Getting important information in our quest for optimal settings in matches. (SF vs Leela)

**I have to say that I fully support the highest possible default contempt, for the many advantages it offers. And I hope that any results will not endanger our max default methodology (-3,1) vs C0.**

Given our ample resources, the theoretical interest of the subject, our discussions of ideal anti-Leela setting, I hope that this test is not denied (at least at an idle framework). I kindly ask anyone to park it at -1 prio already. It should be a fast green, if it goes high numbers feel free to terminate it.

**I also hope that potential success of this single test will not lead to further contempt testing which is usually trivial and wasteful. Focus and resources are best channelled into code and "real" elo gainers. Also small differences in contempt value are too small to measure.**

**Comment by SFisGOD** [comment]
Failed LTC:
LLR: -2.96 (-2.94,2.94) [0.00,4.00]
Total: 30380 W: 3904 L: 3973 D: 22503
http://tests.stockfishchess.org/tests/view/5da32c3f0ebc597ba8ed45b6

**Comment by NKONSTANTAKIS** [comment]
@SFisGOD Thanks, it seems any possible elo difference is minimal.
Closing...
