### ISSUE TITLE
UCI_Limitstrength time managment 

### ISSUE THREAD

**Issue by ghost** [official-stockfish/Stockfish#2361]
With option UCI_Limitstrength=true stockfish plays slower. Something wrong with it's time control when this option activated.

**Comment by name09324ggq** [comment]
All settings are standard except for:
UCI_Limitstrength=true
UCI_ELO=2000

Here i just paste some move times:

Time Control: 10 min
(settings above)
1) 8:57  - so move time 1 minute 3 seconds
2) 8:27 - 30 seconds 
3) 8:14
4) 7:43 
5) 7:37
Here default settings:
1) 9:30
2) 9:27
3) 8:58
4) 8:53
5) 8:27

Yes, positions may be different, but in most cases "Limited Stockfish" uses more time.

Time control: 60 min
"Limited Stockfish"
1) 54:29
2) 52:51
3) 49:29
-------------------
default settings:
1) 58:44
2) 58:09
3) 57:14

I am using Xboard, to change Stockfish's settings. Xboard uses Polyglot program to set engine's settings, maybe it's important  .


Anyway please try it yourself, and you will see, that time management in "Limited Stockfish" is different

**Comment by MichaelB7** [comment]
An interesting discovery.  As you may or may not know ,  limit strength introduces some randomization.  My guess is the randomization introduces some additional fail highs and fail lows which must be resolved, hence takes more time on the early going . I would be more concerned if it was getting flagged. 

The logic for time is the same for both, so what are you seeing is an artifact of introducing limit strength and the resulting artificial fail highs or lows from introducing randomization , which obviously forces SF to play weaker and use up more time in the early going .  There is nothing wrong with it , it is not a bug unless of course you can show us it is losing on time , I.e, getting flagged which had not been demonstrated. 

Thank you.

**Comment by ianfab** [comment]
I think the explanation might be more simple: Enabling skill level or UCI_LimitStrength enforces multiPV mode and multiPV search takes more time to finish the current depth, so it might on average consume more of the remaining time than normal search. Disabling UCI_LimitStrength but setting multiPV to 4 will most likely give the same results.

**Comment by vondele** [comment]
yes, most definitely an effect of enabling multiPV with UCI_LimitStrength. Not an issue, thus.
