### ISSUE TITLE
Crashed for wrong debug log file

### ISSUE THREAD

**Issue by nguyenpham** [official-stockfish/Stockfish#2365]
Stockfish crashes immediately if users enter a wrong file name (or even an existing folder name) for debug log file. It may be hard for users to find out since it prints nothing. If they enter the string via a chess GUI, the chess GUI may remember and auto-send to Stockfish next time, makes Stockfish crashes all the time.

Tested with the latest Stockfish (211019, cloned from GitHub), 64 bit on a macOS.
Log:
```
$ ./stockfish 
Stockfish 211019 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
setoption name Debug Log File value /nofolder/a.txt
isready

(crashed)
```

**Comment by snicolet** [comment]
@nguyenpham @vondele
Issue corrected via 215cd19108d97376284192c29790b42a0b0e618a, thanks for the bug report and the bug fix :-)
