### ISSUE TITLE
position.cpp: Line 1264

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#2373]
```
bool Position::pos_is_ok() const {

  constexpr bool Fast = true; // Quick (default) or full check?

  if (   (sideToMove != WHITE && sideToMove != BLACK)
      || piece_on(square<KING>(WHITE)) != W_KING
      || piece_on(square<KING>(BLACK)) != B_KING
      || (   ep_square() != SQ_NONE
          && relative_rank(sideToMove, ep_square()) != RANK_6))
      assert(0 && "pos_is_ok: Default");

  if (Fast)
      return true;

  if (   pieceCount[W_KING] != 1
```

it seems like last line "if (   pieceCount[W_KING] != 1" and further is an Unreachable code cause "Fast" value is always true..

**Comment by Rocky640** [comment]
This is intended.
One can use Fast = false for debugging purpose.

**Comment by d3vv** [comment]
@Rocky640 "Fast = false" it is a hardcoded action but this is Release code. For debugging purpose most used DEBUG flag or something else w/o boring compiler into release. Moreover it is hard to explore code w/o intent look.

**Comment by Rocky640** [comment]
/// Position::pos_is_ok() performs some consistency checks for the
/// position object and raises an asserts if something wrong is detected.
/// This is meant to be helpful when debugging.

it is used only in the following way
 assert(pos_is_ok());

since assert is called only in debug mode,
pos_is_ok will not make it in release code.

If it is compiled in debug mode and Fast == true,
since Fast is a constexpr, the compiler will stop before  `if (Fast)`

**Comment by d3vv** [comment]
Most likely I didn’t figure it out and I'm wrong.
But still, such code structure makes it necessary to use unused compiler functions constantly into release.
Sure it is wrong, and it's a waste of time for fishtest users for example

**Comment by d3vv** [comment]
use = syntax parse at least

**Comment by Rocky640** [comment]
similar to endgame.cpp where verify_material is used only in context of assert(verify_material(...))
```
#ifndef NDEBUG
  bool verify_material(const Position& pos, Color c, Value npm, int pawnsCnt) {
    return pos.non_pawn_material(c) == npm && pos.count<PAWN>(c) == pawnsCnt;
  }
#endif
```

we could use  in position.h
```
#ifndef NDEBUG
 bool pos_is_ok() const;
#endif
```

and in position.cpp
```
#ifndef NDEBUG
bool Position::pos_is_ok() const {
  ....
}
#endif
```

another twist could be to use
bool Position::pos_is_ok(bool fast=true) const {

and if someone writing code need more thorough tests, he can simply change bool fast=false

**Comment by snicolet** [comment]
Master code is fine, closing.
