### ISSUE TITLE
misc.cpp: Line 252

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#2375]
` ptr = buffer = (SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX*)malloc(returnLength);`

strange code cause argument for malloc is size_t but:

`DWORD returnLength = 0;`

**Comment by snicolet** [comment]
Excuse, I can't understand what you mean. Please open a PR if you think this has to change, thanks :-)
