### ISSUE TITLE
How to compile Stockfish for Android?

### ISSUE THREAD

**Issue by massimilianogoi** [official-stockfish/Stockfish#2380]
The plain way to compile with **make build ARCH=armv7 COMP=gcc** or **make build ARCH=armv7 COMP=mingw** produces binaries that just don't work on Android (Droidfish interface).. Same result doing it through MSYS2 on Windows or with the standard GCC compiler on Linux.

I have tried to install Android Studio and NDK but there is not a single tutorial on the whole Internet for these developing softwares describing how to compile the Stockfish source.

Android devices are by now the 30-40% of the Internet traffic, therefore there should be at least a **simple** and **complete** tutorial on how to compile Stockfish for Android in the official Stockfish GitHub repository.

**Comment by MichaelB7** [comment]
Sounds good - please see this guide on how to contribute https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by ppigazzini** [comment]
@massimilianogoi here https://github.com/glinscott/fishtest/issues/424 @nonsio28 built a working stockfish on his phone using [AnLinux](https://play.google.com/store/apps/details?id=exa.lnx.a&hl=en) and `CXXFLAGS='-march=native' make -j profile-build ARCH=armv7 COMP=gcc`

**Comment by abdulbadii** [comment]
Why don't try contact the Stockfish developer seen on Google play store such droidfish, blabla... etc.. like "How can you fully produce this SF perfectly working ?"

**Comment by snicolet** [comment]
Closing now, since we can move the discussion to https://github.com/official-stockfish/Stockfish/issues/1457
