### ISSUE TITLE
Appveyor build problems

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2391]
looks like appveyor CI testing is stuck right now, or with a long backlog of tests:
https://ci.appveyor.com/project/mcostalba/stockfish/history

currently in 'starting state':
https://ci.appveyor.com/project/mcostalba/stockfish/builds/28524169/job/7w2vtm03sdewvt6s

**Comment by Alayan-stk-2** [comment]
We had a similar issue for another project I contribute to. One appveyor build was stuck, and all the following CI tests were stuck.

The solution was logging in appveyor and manually removing the stuck builds. After this, CI worked as expected for newer commits.

However, that this happened to two different projects I have contributions to in less than a week indicates that there is some deeper issue with appveyor causing the stuck build issue in the first place.

**Comment by vondele** [comment]
yes, I think this indeed needs @mcostalba or @snicolet to cancel this pending appveyor job using the above links.

**Comment by snicolet** [comment]
I had a look at the list of stuck builds in the link 
https://ci.appveyor.com/project/mcostalba/stockfish/history

But I didn't manage to cancel the offending build (namely https://ci.appveyor.com/project/mcostalba/stockfish/builds/28524169/job/7w2vtm03sdewvt6s ) 

So indeed it looks like only @mcostalba can make CI work again for Stockfish. 
Marco ? :-)

**Comment by vondele** [comment]
also reported upstream:
https://help.appveyor.com/discussions/problems/25316-job-stuck-in-starting-state-since-days

**Comment by vondele** [comment]
This now seems to work again, the queue is being processed and things should normalize. Closing.
