### ISSUE TITLE
Can't compile Stockfish

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2399]
When compiling stockfish through MSYS2, it gets to "step 2/4: running benchmark for pgo-build".
It gets stuck to position 4/46 or 6/46.

**Comment by Rocky640** [comment]
Maybe the following link will help.
https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows

Which commit of stockfish did you compiled ?
Which version of MSYS2 ?

**Comment by ppigazzini** [comment]
My workers are building SF w/o problem with an updated MSYS2. Perhaps @anonymous7002 was using a MSYS2 with the bugged libwinpthread, so a simple `pacman -Syuu` should solve his problem.

**Comment by snicolet** [comment]
I suppose @anonymous7002 has been able to solve his compilation problem by now, closing.
