### ISSUE TITLE
Stockfish stable vs development match

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2402]
Stockfish stable version is currently playing against development version. The stable version is currently leading 15 1/2 - 11 1/2

I have attached the pgn. stockfish-10-x64-popcnt is the stable one and stockfish-x86-64-modern is the development one.
[Arena.pgn.txt](https://github.com/official-stockfish/Stockfish/files/3827053/Arena.pgn.txt)

**Comment by Rocky640** [comment]
a) You cannot conclude much after just a few games.
    and "Issues" is not the place to publish your home games.

b) On fishtest, we regularly test latest development version against SF 10.
Here is the latest result where each engine was allocated 1 thread with TC 60+0.6
http://tests.stockfishchess.org/tests/view/5dc0b9660ebc5904493b0107

c) We don't know what other programs were running on your laptop,
or your engine settings or your tournament settings. To do proper testing, you need a stable and dedicated environment.
You will notice that in your attached pgn,
the last three games finished with some problems.

so please close this non-issue. 

[Event "stockfish"]
[Site "LAPTOP-VHBM5OJC"]
[Date "2019.11.09"]
[Round "26"]
[White "Stockfish_x86-64-modern"]
[Black "Stockfish_10_x64_popcnt"]
[Result "*"]
[BlackElo "2200"]
[ECO "B00"]
[Opening "King's Pawn"]
[Time "04:50:20"]
[WhiteElo "2200"]
[TimeControl "40/240:40/240:40/240"]
[Termination "unterminated"]
[PlyCount "1"]
[WhiteType "program"]
[BlackType "program"]

1. e4 {(1.e4 e5) +0.71/16 18776} *

[Event "stockfish"]
[Site "LAPTOP-VHBM5OJC"]
[Date "2019.11.09"]
[Round "26"]
[White "Stockfish_x86-64-modern"]
[Black "Stockfish_10_x64_popcnt"]
[Result "0-1"]
[BlackElo "2200"]
[Time "10:03:21"]
[WhiteElo "2200"]
[TimeControl "40/240:40/240:40/240"]
[Termination "rules infraction"]
[PlyCount "0"]
[WhiteType "program"]
[BlackType "program"]

 0-1

[Event "stockfish"]
[Site "LAPTOP-VHBM5OJC"]
[Date "2019.11.09"]
[Round "27"]
[White "Stockfish_10_x64_popcnt"]
[Black "Stockfish_x86-64-modern"]
[Result "1-0"]
[BlackElo "2200"]
[ECO "B00"]
[Opening "King's Pawn"]
[Time "10:03:34"]
[WhiteElo "2200"]
[TimeControl "40/240:40/240:40/240"]
[Termination "rules infraction"]
[PlyCount "1"]
[WhiteType "program"]
[BlackType "program"]

1. e4 {(1.e4 e5 2.Nf3 Nc6 3.Bb5 Nd4 4.Nxd4 exd4 5.0-0 c6 6.Bc4 Nf6 7.e5 d5
8.Be2 Nd7 9.f4 Bc5 10.d3 Be7 11.Bf3 0-0 12.Nd2 Nc5) +1.03/18 9  Arena
Adjudication. Illegal move!} 1-0
