### ISSUE TITLE
Stockfish still searching after insufficient material

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2403]
This is a clip of stockfish analysis:
8/1k6/5p2/8/4K3/8/8/8 w - - 0 1
1. Kf5 Kb6 2. Kxf6 Kb5 3. Kg5 Ka4...
Look how it is still searching after the game would have been ended because the capture of the pawn.
Sorry for my bad english.

**Comment by vdbergh** [comment]
This is the result of a simplification. It was determined that letting SF continue to search in a draw position does not lose elo. This saves a few lines of code so...

**Comment by NKONSTANTAKIS** [comment]
It saves a few lines of code but wastes cpu resources, right? Less code is desired but is it an end in itself? Maybe I'm too obsessed with frugality, (as I hate seeing parked cars with engine on, taps running, etc) but I think a reconsideration is worth it.

**Comment by snicolet** [comment]
Probably not a issue, but if somebody feels like writing a patch and opening a PR, then we could discuss it there. So I am closing this for now
