### ISSUE TITLE
MultiPV overwrites TT entries at the Root Node that should not be overwritten

### ISSUE THREAD

**Issue by AndyGrant** [official-stockfish/Stockfish#2404]
This might be less of an issue, and more of an observation, but it appears to me that if we are to use Stockfish with ``MultiPV=2``, each successive search for a given depth will overwrite the previous line of play's Root TT entry. 

IE at the start position, if we were to find on the first iteration that ``e2e4=20cp`` and on the second iteration find that ``c2c4=15cp``, the ``c2c4=15cp`` entry would be saved into the TT and since it may also have an exact bound, it would overwrite the entry saved previously by ``e2e4=20cp``. This of course has hardly any impact on play, as only a small amount of transpositions (if any) can cause the "incorrect" TT entry to be used in any meaningful way.

Master:
```
if (!excludedMove)
    tte->save(posKey, value_to_tt(bestValue, ss->ply), ttPv,
              bestValue >= beta ? BOUND_LOWER :
              PvNode && bestMove ? BOUND_EXACT : BOUND_UPPER,
              depth, bestMove, ss->staticEval);
```

Resolved:
```
if (!excludedMove && !(rootNode && thisThread->pvIdx))
    tte->save(posKey, value_to_tt(bestValue, ss->ply), ttPv,
              bestValue >= beta ? BOUND_LOWER :
              PvNode && bestMove ? BOUND_EXACT : BOUND_UPPER,
              depth, bestMove, ss->staticEval);
```

**Comment by vondele** [comment]
I indeed assume this won't affect playing strength, but let's check:
http://tests.stockfishchess.org/tests/view/5dcdbd810ebc590256324a11
