### ISSUE TITLE
If Chess960 on then castling has bad error

### ISSUE THREAD

**Issue by abdulbadii** [official-stockfish/Stockfish#2405]
Why if Chess960 on then castling having bad behaviour,
 in some ms it shows king going to take rook of which his pair to castle then right off is hanging?
Please fix it...

**Comment by Rocky640** [comment]
Stockfish has played in numerous chess 960 tournaments, and no one ever reported a problem.

Your description it is not clear at all.  An example of what you think is a problem would be more useful ? You can paste a fen or a picture.

If you are using Arena,  see help menu of Arena and look for Chess 960 to learn how to set up a Chess 960 game properly.

For more about castling rules in chess 960, see https://en.wikipedia.org/wiki/Fischer_random_chess#Castling_rules

**Comment by miguel-l** [comment]
I think this might be a misunderstanding. iirc, the UCI notation in Chess 960 for castling is that the king captures the rook. This is because something like "f1-g1" is ambiguous: If the king started at f1, then it could mean both "castle kingside", and "King to g1" and the GUI has no way of knowing. Whereas the current convention is always clear, regardless of where the kings and rook start. If the square is occupied by the rook, you know exactly that it meant "Castle on this side".

If you still think that there is an error it would be helpful if you could post steps to replicate it, and/or screenshots.

**Comment by snicolet** [comment]
Good answers by Alain and Miguel, so I shall close the issue now.

**Comment by Craftyawesome** [comment]
Make sure you put in `setoption name UCI_Chess960 value true`

Or if you are using the gui make sure both it and the engine are in 960 mode.

**Comment by Disservin** [comment]
Yes a) the engine needs `setoption name UCI_Chess960 value true`
b) the move isnt ambiguous, if it were castling it would be f1h1 (Stockfish says king captures rook)

**Comment by Luiz-Lino** [comment]
[I changed the same game.txt](https://github.com/official-stockfish/Stockfish/files/12245689/I.changed.the.same.game.txt)
The UCI_Chess960 option was correctly provided. If you notice on the 12th line in the file I provided there is the following string:

info depth 6 seldepth 7 multipv 2 score cp -1079 nodes 3461 nps 692200 tbhits 0 time 5 pv f1g1 d7d6 c5d6 c7d6 f1c1 b8c7

f1c1 is only possible with castling.

I changed the same game, but with the King on g1, the result was “bestmove g1g1 ponder d7d6”.

Another point that I also find strange is the fen “w K - 4 17 “, my gui provided “w H - 4 17”
Stockfish calculates the same bestmove but always returns “w K - 4 17 “.
(The original text in Portuguese was translated by google, sorry if there is no sense in the comment.)

**Comment by Craftyawesome** [comment]
SF seems like it will attempt to castle regardless of what UCI_Chess960 is set to. The option just changes the output. Also make sure it is set before you send the position.
[correct.txt](https://github.com/official-stockfish/Stockfish/files/12245816/correct.txt)
[no 960.txt](https://github.com/official-stockfish/Stockfish/files/12245814/no.960.txt)
[misplaced 960.txt](https://github.com/official-stockfish/Stockfish/files/12245815/misplaced.960.txt)

**Comment by Luiz-Lino** [comment]
Sorry for the delay, I finally figured out the reason for above reported behavior. My gui provided “setoption name UCI_Chess960 value true “ before “position fen “, however my gui provides this parameter with the term at the end of the text '/n', as informed in “The UCI protocol as published by Stefan-Meyer Kahlen (ShredderChess):”. It was just removing the term “/n” that everything started to work correctly. Thanks.
