### ISSUE TITLE
Syzygy tables into time trouble (Zeitnot) with HDD and slow SSD.

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#2432]
Using Syzygy tables in time pressure with "slow" storage leads to {"Side" loses on time}.

Sure this is unacceptable behavior.

Logic could be like with generally accepted practice for chess opening books: "Lookup position in book if possible".

**Comment by vondele** [comment]
not necessarily.. people might want a TB correct answer at root. See also 4b88bea4fcd5c4cb931610f97460615dd71ff35b
and PRs mentioned there.

Practically, one can increase 'Move Overhead' to be on the safer side with slow HDD.

**Comment by d3vv** [comment]
@vondele MoveOverhead it is forced empirical setting due to net or gui lags.
In this case we can only try to guess "start-before" value step by step via hands.
And it is only one way cause sf-app can't control time from outside factors.

I agree that we can to use MoveOverhead if TB correct answer needed strongly.
Especially if we have no time control limits.
Problem - how we can to guess "normal" value?

But endgame tablebase lags it is not unknown external factor for sf application.
It is internal and under control.
App always can check i/o performance by reading several random probes from tables-files at the beginning.
And with lack of time decide to correct MoveOverhead, refuse to use tables in critical moments or something else..

**Comment by d3vv** [comment]
Moreover each read operation from tables returns us the operation time.
It can be used into "timeLoss autoCorrection value" in real time.
Sure need to use the slowest result always.
Because it means that I/O waits, hard loads persist for system.

**Comment by MichaelB7** [comment]
Differences between hardware configurations are best settled by the UCI options provided.
A user has two options:

1. Increase Slow Mover to a higher value.
2. Increase SyzygyProbeDepth

It will not take long to figure out your ideal settings for you hardware.

If you are using 7 men on HDD, that may be different story.  I had to modify the source to limit the number of searches with 7 men TB on HDD as it could it slow SF down to 10K, but there are not many of us around with the full (almost, some are on SSD)  7 men set on HDD.

**Comment by d3vv** [comment]
@MichaelB7 Regarding time, with such a manual approach I need to spend half a day for tc 3+1.8 for to check one value of  Slow Mover. Cause "loses on time" may occur after 20-25 games. Moreover the error can occur through a large number of games if I increase Slow Mover value. Therefore it is not possible to determine the most accurate value at an adequate time. Using an approximate value, it will degrade the quality of the game. Sure this is odd and improper way.

**Comment by snicolet** [comment]
> Sure this is unacceptable behavior.

If you have nothing more constructive to say, I will close the issue. Thanks :-)
