### ISSUE TITLE
Static evaluation is no longer possible while in check

### ISSUE THREAD

**Issue by craylton** [official-stockfish/Stockfish#2433]
Since the commit [Extend bench to static evaluations](https://github.com/official-stockfish/Stockfish/commit/54253bcce69a0ebc3e6bc4c35dfa76f8ff46521e) on November 27th, it isn't possible to perform an `eval` if the side to move is in check any more.
This is an issue for me because a mini project I've been working on is now unable to parse the results of certain `eval` calls. It will be a bit of a headache for me to work around it.

I know a static evaluation in such a situation is likely to be inaccurate and misleading, but I don't think that's enough of a reason to remove the functionality entirely. I can;t see any functional reason why the restriction is in place. 
If people feel strongly about it then perhaps we could include a note after the eval results to explain that the player is in check, or something like that?

**Comment by vondele** [comment]
see https://github.com/official-stockfish/Stockfish/pull/2434#issuecomment-560071308 ... it was 'never possible' to call evaluation while in check if the code was compiled with `debug=yes`.

Obviously, catching the case where the value printed is 'none' should be doable, so maybe you can be more specific on the requirements you have?

**Comment by craylton** [comment]
I hadn't noticed that `assert`. It looks like that was introduced in 2009 in response to a crash caused by searching at depth `MAX_PLY` in a check position (d8e7ce1863d234f585193125b328e18668bd1e71).
I don't know why that crash would occur - possibly due to extension beyond `MAX_PLY`?  In which case I think an assert against `MAX_PLY` would be more appropriate since checks are only one possible cause of extension.

**Comment by vondele** [comment]
I would guess that at that point the eval code could crash  if in check... the fix does only change that aspect.

There is a similar assert in endgame.cpp

https://github.com/official-stockfish/Stockfish/blob/54253bcce69a0ebc3e6bc4c35dfa76f8ff46521e/src/endgame.cpp#L117-L122

if I comment both asserts out, I do not observe a crash in a deeper bench where I explicitly call eval if in check... but that's just a weak verification that this can't happen.

**Comment by joergoster** [comment]
@vondele It seems safe to remove the assert in Endgame KXK since endgame code is only called from within our main evaluation, right? And we already check at the beginning of the main evaluation.

**Comment by vondele** [comment]
well ... it is a 'design by contract'-like thing. That particular function asserts it assumption. So generally, I would keep such asserts.

It is also a useful example to see what could happen. The function would return VALUE_DRAW on mate positions, since based on the no-check assumption, if the weak side can not move, it is a stalemate..

**Comment by craylton** [comment]
So does anybody know exactly why eval can't be called while in check?
I removed this restriction from evaluate and search and called `go infinite` on a few positions, and it crashed each time (segmentation fault) at around depth 13-16. But then I called `eval` directly on about 1000 positions where the side to move was in check, and there was no crash.
So it seems to me that either: the crash isn't in the evaluation code, or, being in check isn't the only reason for the crash.

**Comment by Chess13234** [comment]
> the crash isn't in the evaluation code, or, being in check isn't the only reason for the crash.
The crash is likely because inCheck condition  skips early pruning(that means Qsearch in Razoring and nullMoves(which can't be done in check obviously)).

**Comment by ianfab** [comment]
@craylton What exactly did you change in the search? Did you only enable evaluation when in check or did you remove the code block including the `goto`? Because if you remove the goto, then you enable null move pruning when in check, which could explain the crashes.

**Comment by craylton** [comment]
@ianfab You're right, I'd removed the whole code block. It doesn't crash when I undo that.
So there are at least two situations where evaluating while in check can cause a crash:
- When doing a null move
- When we are at `MAX_PLY` (although I couldn't replicate this one even when I reduced `MAX_PLY` to 20)

Plus as @vondele pointed out, some endgame code also requires not being in check.
I imagine removing the restriction wouldn't be trivial and would require a lot of testing then, and I have no reason to believe doing so would actually improve stockfish at all :) So I will close this issue if nobody has anything else to add.

**Comment by ddugovic** [comment]
Could we parameterize the `evaluate.cpp` assertion so that the `eval` command works in many positions?

`assert(T == TRACE || !pos.checkers());`
