### ISSUE TITLE
Lose on time under Fritz GUI

### ISSUE THREAD

**Issue by maelic13** [official-stockfish/Stockfish#2442]
I have bought myself a Fritz 17 GUI to replace Arena. But I found out that Stockfish (latest dev version, compiled myself) is losing on time in their tournamets. Is this a known issue? If not, I can provide some more informations about the problem if you tell me what's needed.

**Comment by veselychess** [comment]
try to setup move overhead to 300, anyway for fritz better longer time games, if u need very fast games, use cutechess

**Comment by maelic13** [comment]
Will do - but lately I encoutered the problem in Aquarium too while the GUI crashes with it. Perhaps different cause than time loss? Sadly I do not really have any insight into inner workings of the engine so I have no idea how to investigate...

**Comment by Rocky640** [comment]
a) You said you compiled yourself, 
please give a try to the official version  https://stockfishchess.org/
and if you configured the engine please document the uci settings

b) what time control ?

c) are you using tablebases ? which one are loaded ?

**Comment by vondele** [comment]
@maelic13 I'm assume this issue is resolved, if not, please reopen, providing the information asked in the the previous comment.
