### ISSUE TITLE
Small issue: repetition in StateInfo is copied although it shouldn't

### ISSUE THREAD

**Issue by Matthies** [official-stockfish/Stockfish#2443]
Just a very small issue:

Someone introduced "repetition" as new first member of the "Not copied when making a move (will be recomputed anyhow)" area of StateInfo. But the memcpy in do_move() (and maybe others?) still takes "key" (now second member of the non-copy-area) as offset to non-copy:
std::memcpy(&newSt, st, offsetof(StateInfo, key));
So either the order of the members should be changed or the offsetof should use "repetition".

Probably won't get a single Elo but should be fixed imo.

**Comment by snicolet** [comment]
Closing, as it has been fixed in 384bff4264f199ded8fa28d241ce0e7dc021a97c. Thanks!
