### ISSUE TITLE
RFC: logistic Elo bounds instead of BayesElo bounds?

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/Stockfish#2459]
The BayesElo bounds are a historical artifact and serve no purpose anymore. In fact internally they are now converted into logistic Elo bounds (more precisely scores). 

So I wonder if there would be any interest in switching to logistic Elo bounds on Fishtest. It would be easier for users and it would also simplify the internal logic of Fishtest.

One can find the logistic Elo bounds on the audit page of a test. For example BayesElo -1.5,4.5 corresponds very closely to -1,3 Elo at STC.

**Comment by vdbergh** [comment]
Maybe I should phrase the question differently. Would there be any objections at all to switching to standard (logistic) Elo bounds? We could do a one time conversion of the current BayesElo bounds to logistic Elo bounds and then to continue with those. 

Suitable conversions would be 

```
STC(-1.5,4.5)  ->    -1,3 
LTC(0,3.5)     ->     0,2
STC(-3,1)      ->    -2,0.5
LTC(-3,1)      ->  -1.5,0.5
```

**Comment by ddugovic** [comment]
My suggestion is https://github.com/zamar/spsa/pull/6

**Comment by vondele** [comment]
I wouldn't mind SPRT being converted to logistic Elo... that's easier to reason about for me.

**Comment by vdbergh** [comment]
See https://github.com/glinscott/fishtest/pull/479 .

**Comment by vdbergh** [comment]
One of the arguments put forward in favour of BayesElo bounds was that these would somehow compensate for "elo compression" at higher TC. This argument should be considered obsolete as the current SF actually super scales with TC.

A number of 40000 games tests of master vs master (Refine improving-logic) using 2moves_v1.pgn were done at various time controls and the results were of as follows:

|1+0.01|2+0.02|5+0.05|10+0.1|60+0.6|
|---|---|---|---|---|
| -83.86 +-3.0|  -13.77 +-2.6| 31.99 +-2.4|44.50 +- 2.3 | 58.01 +-2.0 |

**Comment by MichaelB7** [comment]
@vdbergh I find your comment interesting, but I'm not understanding the term 'superscales' and how am I to read the output. As an example, what does 58.01 and +-2.0 represent under the 60+.06 TC. Thanks in advance.

**Comment by vondele** [comment]
@MichaelB7 Elo gain sfdev vs sf10:
60 http://tests.stockfishchess.org/tests/view/5e007946c13ac2425c4a9a22
10 http://tests.stockfishchess.org/tests/view/5dfc68e9e70446e17e451015
5   http://tests.stockfishchess.org/tests/view/5dff3e6ee70446e17e451190
2   http://tests.stockfishchess.org/tests/view/5dff3a2ce70446e17e451188
1   http://tests.stockfishchess.org/tests/view/5dff379de70446e17e451185

**Comment by MichaelB7** [comment]
Got it , thank you @vondele !

**Comment by vdbergh** [comment]
Does anyone know who is responsible for this script?

http://chess-sprt-calc.azurewebsites.net/

If and when Fishtest converts to logistic, it should be updated (I can do that).

Probably it would be better to link to this script from the Wiki. It always takes me forever to find it.

**Comment by vdbergh** [comment]
The question was answered on the corresponding Fishtest PR.

**Comment by vondele** [comment]
> 1+0.01 	2+0.02 	5+0.05 	10+0.1 	60+0.6
> -83.86 +-3.0 	-13.77 +-2.6 	31.99 +-2.4 	44.50 +- 2.3 	58.01 +-2.0

I've run a number of tests against sf10, with all patches in sfdev except for those touching search and movepick... so from a strength point of view, essentially eval. The results are really interesting and different to those posted above:

| 0.5 + 0.005 | 1 + 0.01 | 2 + 0.02 | 5 + 0.05 | 10 + 0.1 | 60 + 0.6 |
| --- | --- | --- | --- | ---  | --- | 
| 6.67 +. 2.4 | 9.40 +- 2.9 | 6.45 + - 2.6 | 10.88 +- 2.4 | 10.61 +- 2.2  | 14.17 +- 1.9 |

so, while the full performance changes by roughly 160 Elo, the eval-only part is in comparison almost constant, down to very short times.

http://tests.stockfishchess.org/tests/view/5e063325c13ac2425c4a9dc8
http://tests.stockfishchess.org/tests/view/5e062cfbc13ac2425c4a9db9
http://tests.stockfishchess.org/tests/view/5e062d29c13ac2425c4a9dbb
http://tests.stockfishchess.org/tests/view/5e062d3ac13ac2425c4a9dbd
http://tests.stockfishchess.org/tests/view/5e062d46c13ac2425c4a9dbf
http://tests.stockfishchess.org/tests/view/5e0654a4c13ac2425c4a9e14

**Comment by snicolet** [comment]
I suppose we can close this issue now that https://github.com/glinscott/fishtest/commit/948adb1fa657aa4de89e3e74d54e52bc681d7930 has been commited?
