### ISSUE TITLE
PV lines too short?

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2462]
For example:
```
position fen r4nk1/1p1b1N1p/4p1p1/p2pP3/1r1q4/5R2/3Q1PPP/2R2NK1 w - - 2 28
```
leads to
```
info depth 40 seldepth 5 multipv 1 score cp 0 [...] pv f7h6 g8h8 h6f7 h8g8
```
which is draw by a 3-fold, but the PV doesn't show the final drawing move.

Anybody has an easy fix?

**Comment by ttruscott** [comment]
This is probably due to the upcoming-draw (has_game_cycle) detector. When a repetition is detected, has_game_cycle could return the upcoming draw move as a side effect and then the caller could tack it onto the PV.  Cringe worthy.

**Comment by vondele** [comment]
we have one more ply if I comment out the has_game_cycle code:
```
pv f7h6 g8h8 h6f7 h8g8 f7h6

```
but not yet the drawing move.

**Comment by ianfab** [comment]
If the repetition is strictly after the root then we stop at the first repetition, so I guess this is expected.

**Comment by vondele** [comment]
For reference, a test where the has_game_cycle code was made !PvNode failed:
http://tests.stockfishchess.org/tests/view/5e02d7c9c13ac2425c4a9b3b

**Comment by snicolet** [comment]
Probably not a critical bug, so I will close the issue for now.
