### ISSUE TITLE
Missing pawn prefetch in Position::do_move

### ISSUE THREAD

**Issue by Mega-Wolf** [official-stockfish/Stockfish#2467]
The commit https://github.com/official-stockfish/Stockfish/commit/4e72e2a964754611de85536c13ae069f85839b85#diff-760a56b9dcfc15bf67577d7d6a273fb9 removed the call
`prefetch2(thisThread->pawnsTable[st->pawnKey]);`
in `Position::do_move`
However, the comment is still explaining that a prefetch happens. Since I did not find a reason for the removal of the prefetch, I do not know whether the comment should be updated or a prefetch should be taken in again.

**Comment by Rocky640** [comment]
This came from pull request
https://github.com/official-stockfish/Stockfish/pull/2070

It was tested that removing prefetch2 was ok
http://tests.stockfishchess.org/tests/view/5cbfa0f00ebc5925cf028947

So indeed the comment could be changed from
`// Update pawn hash key and prefetch access to pawnsTable`

to
`// Update pawn hash key`

**Comment by Alayan-stk-2** [comment]
The test showed a minor elo loss (over 0.5) though within error bars. Sure it's simpler to do without, but it's not clear it didn't give a measurable small speed-up.

**Comment by snicolet** [comment]
I am going to close this issue now, since the comment has been removed in 384bff4264f199ded8fa28d241ce0e7dc021a97c. Thanks!

Feel free to test if adding the prefetch again gains sufficient speed to pass STC and LTC in fishtest, of course :-)
