### ISSUE TITLE
Stockfish 10

### ISSUE THREAD

**Issue by GUERRABRAZIL** [official-stockfish/Stockfish#2478]
I have a Ryzen3 2300x GTX1050ti 16Gb . what is the best parameter for my computer?

**Comment by MichaelB7** [comment]
Either the fish cooking google groups forum or the talk chess.com forum are better places to ask that question.  Your question or comment   pertains to your own personal hardware situation  - not to any issue with Stockfish.

**Comment by snicolet** [comment]
Yes, please use the fishcooking forum, thanks :-)
