### ISSUE TITLE
Broken link on main website to the Fishtest worker.

### ISSUE THREAD

**Issue by konsolas** [official-stockfish/Stockfish#2483]
I'd like to install fishtest to help improve Stockfish, but the link on 
https://stockfishchess.org/get-involved/
seems to be dead as it links to a page that hasn't been created.

I imagine that a number of people who might have otherwise joined fishtest may have been unable to as a result of this. Could someone link the correct page (and preferably update the website so others can find their way there)?

**Comment by snicolet** [comment]
Thanks for reporting this, the correct links are now:
https://github.com/glinscott/fishtest/wiki 
https://github.com/glinscott/fishtest/wiki/Running-the-worker:-overview

I have sent an email to Daylen Yang to ask if if he can fix the link on the https://stockfishchess.org/get-involved/ web page.

**Comment by ppigazzini** [comment]
@snicolet the button "Fishtest Dashboard" should use the https link:
https://tests.stockfishchess.org/tests

**Comment by daylen** [comment]
The link is updated! This issue can be closed.

**Comment by snicolet** [comment]
Thanks for the "Install the worker" link, Daylen!
Pasquale also made the point that the link under "Fishtest dashboard" could use the https protocol, as we have switch to using that now : https://tests.stockfishchess.org/tests

**Comment by konsolas** [comment]
I also noticed this link on the same page: https://github.com/glinscott/fishtest/wiki/A-portable-fishtest-worker-for-Windows-64-bit

Since it seems much easier to set up, should new users be linked to that rather than to https://github.com/glinscott/fishtest/wiki/Running-the-worker:-overview
which seems to require several different installations and a lot of setup?

**Comment by ppigazzini** [comment]
@konsolas the page linked has links for several OS, not only Windows.

By the way the "Portable Fishtest Worker Install" uses discontinued and not maintained software (msys, python 2.x, "Portable Fishtest Worker Install" itself) and IMO should be ditched.

The new worker installation instruction for Windows are very easy and setup a "live" environment, easy to be kept up to date:
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows#msys2--mingw-w64
