### ISSUE TITLE
Debug (in visual studio) StockFish compiled with visual studio, used from Arena.exe

### ISSUE THREAD

**Issue by MisesEnForce** [official-stockfish/Stockfish#2484]
Hello guys,
I had a technical problem while trying to debug my chess engine (coded with visual studio, debug inside visual studio) when using it from Arena.exe GUI.
Thinking that my engine was the problem, I picked up StockFish's source code, compiled in a visual studio console project, and tried as I tried with my engine, to debug it while using it inside Arenax.exe GUI, and I had the same problem.
I documented the problem on CSE here : https://chess.stackexchange.com/questions/27911/debugging-my-chess-engine-through-the-arena-gui
I know this is not an issue per se, but i think that if I have the same problem with StockFish, for sure one of you guy should know what I am doing wrong.
Thx in advance !

**Comment by Rocky640** [comment]
"I put breakpoints in my code but each has a "no symbols loaded"."
Most likely:
Debug=>Options=>General => Remove the check mark for "Enable Just My Code"
or
you have multiple projects, and you should set the "starting project" to stockfish

google for
visual studio breakpoints not working

or look into
https://developercommunity.visualstudio.com/content/problem/97445/vs2017-the-breakpoint-will-not-currently-be-hit-no.html

**Comment by MisesEnForce** [comment]
Stockfish project is of course already set as startup project as I want to debug it. Unchecking "Enable just my code" doesn't change anything.
Did you already debug Stockfish from Arena under Windows ?

**Comment by Rocky640** [comment]
"in visual studio I make an "attach to process" and add Arena as process to attach to. "

You must attach stockfish exe, not arena !

**Comment by MisesEnForce** [comment]
I want to debug stockfish used in arena. To do this you attach to arena while debugging Stockfish project. (I don't want to debug stockfish just as a console project, which is what it is by definition, by passing moves to it etc.) That's what I did as already mentioned, without success.

**Comment by Rocky640** [comment]
"I want to debug stockfish used in arena. "

compile a stockfish in debug mode. You get some exe. Lets call it debug.exe
you run arena, your start the debug.exe engine from arena and attach to the process debug.exe
this will work.

**Comment by MisesEnForce** [comment]
"this will work"

For the third time, "this" is what I do. And I end up with "no symbols".

**Comment by Rocky640** [comment]
you said you attached to the process arena.exe 
you must attach to the process debug.exe

It works here

a) compile stokfish from your vs studio in debug mode
here is my output. If you dON,t Have a pdb file this will not work.
![image](https://user-images.githubusercontent.com/8949638/72226151-e8aa6a80-355b-11ea-9e67-797332ffb947.png)


start arena, and add new engine 
...\Projects\bin\Debug\x64\Stockfish.exe
in arena, click analyse, this will start your engine
in visual studio, attach to process stockfish.exe
![image](https://user-images.githubusercontent.com/8949638/72226193-5a82b400-355c-11ea-92ad-0169b5a652c6.png)

Click button Attach

Your breakpoint will be hit.

![image](https://user-images.githubusercontent.com/8949638/72226209-75552880-355c-11ea-87af-1dda091ca6df.png)

**Comment by MisesEnForce** [comment]
Ah yes, attach to engine.exe, not arena.exe ... Sorry, you are right though !
(Strange though : if I code a c++ dll usable in excel and if I want to debug it, I'll have to attach to excel, not to the dll.)
Now I will have to find an efficient way of debugging my engine ...

**Comment by Rocky640** [comment]
well, in this case, it is not a dll, it is an exe.

Great. you can close this issue now. Have fun !

**Comment by MisesEnForce** [comment]
Well I see the fact that dll != exe, but it is not a sufficient "explanation" to me.
Thx
