### ISSUE TITLE
Wrong bench numbers

### ISSUE THREAD

**Issue by lantonov** [official-stockfish/Stockfish#249]
The 32 bit Windows compiles on abrok give wrong bench numbers lately (Windows 8.1 32bit, CPU Intel Core Duo and CPU i3):
These 2 commits:
Commit #1
Author: Stefan Geschwentner 
Date: Tue Feb 3 11:19:33 2015 +0800 
Timestamp: 1422933573 

Add bonus for pawn attack threats 

Latent pawn attacks: Add a bonus to safe pawn pushes which attacks an 
enemy piece. Based on an idea of Lyudmil Tsvetkov. 

STC: 
LLR: 2.95 (-2.94,2.94) [-1.50,4.50] 
Total: 7925 W: 1666 L: 1537 D: 4722 

LTC: 
LLR: 2.95 (-2.94,2.94) [0.00,6.00] 
Total: 40109 W: 6841 L: 6546 D: 26722 

Bench: 7696257 
Resolves #240 

gives bench 7695175,

Commit #2 
Author: Joona Kiiski 
Date: Sun Feb 8 19:28:01 2015 +0000 
Timestamp: 1423423681 

Pawn Center Bind Bonus 

Bonus for two pawns controlling the same central square 

STC: 

LLR: 3.14 (-2.94,2.94) [-1.50,4.50] 
Total: 15974 W: 3291 L: 3133 D: 9550 

LTC: 

LLR: 3.24 (-2.94,2.94) [0.00,6.00] 
Total: 10449 W: 1837 L: 1674 D: 6938 

Idea from Lyudmil Tsvetkov. 

Bench: 7699138 

Resolves #248 

gives bench 7637783.

**Comment by hxim** [comment]
I checked Windows 32 compiles on abrok and bench is different for me for 
"King safety tuning with values obtained by SPSA."
https://github.com/official-stockfish/Stockfish/commit/7837fb2aca6db425e5f7237f5cc714412fc0140d
and all later versions.

**Comment by hxim** [comment]
I investigated more and it seems there is problem with
 KingDanger[100] value which can be sometimes 269 (gives bench 7637783) and sometimes 270 (gives bench 7699138).
It is initialized with floating-point operations which are imprecise.
int(0.027*100*100) isn't always 270.

**Comment by locutus2** [comment]
@hxim 
My own compile tests on 32- and 64 bit machines give the same result. The problem on 32 bit occurs since the patch you mentioned.
