### ISSUE TITLE
Illegal use of Stockfish code ?

### ISSUE THREAD

**Issue by alexevane** [official-stockfish/Stockfish#2503]
Hi, 

The friend of mine, brought variant of chess software. And then we found out that it is actually variant of stock fish. 

The one claimed that he is a developer name name "Woradet Jangwattanasub" (วรเดช จังวัฒนาทรัพย์) and this is what he did.
Changed name "Stock fish" into "pr0rp" or something. 
Claiming that it is their own software and selling it as their own interest.  with out credit or source code.

This is highly unacceptable.

links 
https://www.facebook.com/pr0rp1/posts/891563284613063
https://www.facebook.com/groups/makrukthaiclub/permalink/2727074577331829/

https://www.facebook.com/pr0rp

Updated:
He change his facebook to 
https://www.facebook.com/pr0rpredghost
and his page changed to
https://www.facebook.com/pr0rpred/

**Comment by ddugovic** [comment]
I don't know whether that is legal, but I do know the software license (which under some conditions may allow for commercial use) is GPLv3:
https://github.com/official-stockfish/Stockfish/blob/master/Copying.txt

**Comment by alexevane** [comment]
He claim he develop this by him self or with his small team. 
And nothing refer back to Stockfish not even source code or GPL.

**Comment by alexevane** [comment]
He claim that he develop that program.
And nothing refer back to Stockfish not even source code or GPL (by the reported time).

**Comment by protonspring** [comment]
It's not legal, but no one is going to expend legal costs to enforce something like this.  He won't likely profit much from this and all we (you) can do is educate the public.  If he begins make hoards of money, well then, it may be worth it, but I'm 99.9% sure that will never happen.

This can probably be closed.

**Comment by vondele** [comment]
Clearly, conveying a derived work from the stockfish code without respecting the license is not legal. Among other things, the license requires providing access to the sources needed to build that derived work. If this is not the case, one should at least let the authors know that what they are doing violates the rights of the stockfish authors and inform them this should stop. 

I agree with @protonspring  that we can close this issue and reopen in the future if needed.
