### ISSUE TITLE
How to compile Stockfish on Android?

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2504]
I tried on Windows with MSYS2 MinGW64: make -j profile-build ARCH=arm64v8 COMP=mingw
Apparently, Stockfish does not allow arm64v8, although compiled Android version has arm64v8.
I tried armv7, but that produced normal Windows binaries.

**Comment by snicolet** [comment]
Looks like a duplicate of https://github.com/official-stockfish/Stockfish/issues/2380. Closing.
