### ISSUE TITLE
How to build stockfish for android?

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2506]
I tried on Windows with MSYS2 MinGW64: make -j profile-build ARCH=arm64v8 COMP=mingw
Apparently, building Stockfish does not allow arm64v8, although compiled Android version downloaded from the home page has arm64v8 version with it.
I tried armv7, but that produced normal Windows binaries.

**Comment by snicolet** [comment]
Looks like a duplicate of https://github.com/official-stockfish/Stockfish/issues/2380. Closing.
