### ISSUE TITLE
SF11 high-thread possible overpruning

### ISSUE THREAD

**Issue by NKONSTANTAKIS** [official-stockfish/Stockfish#2509]
At Oct 1 this 
https://github.com/official-stockfish/Stockfish/pull/2337
was introduced by @vondele, featuring every thread to prune more with the logic that the more they are, the more likely it is to cover each others holes wide in the tree.

Since then we prune a lot more by default (and test on 1-thread), so this smp behavior might be too much. We could try to simplify it away, use smaller prefactor (like 1/4 or 1/8), or use lower base value

**Comment by NKONSTANTAKIS** [comment]
But probably its wiser to first see it at high TC + High thread combo, as the concept seems very promising for such an environment. Its just the very short TC+high thread combo that concerns me for the risk of threads running thin.

**Comment by snicolet** [comment]
Hi @NKONSTANTAKIS 

My suggestion would be to get precise data to describe the problem, and then move the thread to the forum. When we have enough data for a repeatable fix, we can open an issue or a PR.
