### ISSUE TITLE
Bug in Stats::update(Piece pc, Square to, Value v)

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#251]
I'm not very familiar with this code but it seems to me that

``` c++
void update(Piece pc, Square to, Value v) {

    if (Gain)
        table[pc][to] = std::max(v, table[pc][to] - 1);

    else if (abs(table[pc][to] + v) < Max)
        table[pc][to] +=  v;
}
```
was maybe really intended to be

``` c++
void update(Piece pc, Square to, Value v) {

    if (Gain)
        table[pc][to] = std::max(v, table[pc][to] - 1);
    else
        table[pc][to] = std::min(std::max(table[pc][to] + v, Value(1 - Max)), Value(Max - 1));
}
```

Let's say for example the current value of table[pc][to] is 200 and update() is called(Gain = false) with v of 40.  The result will be 240.  If instead update() gets called with v of 60 the result will be 200.  It seems inconsistent that an update with a smaller v can result in a greater final value than an update with a larger v.  I think the result of the v=60 update in this example should be 249(the maximum allowed).  Could someone familiar with this code confirm that this is a bug?  Also if I wanted to submit this fix to fishtest what would be the appropriate sprt parameters?  I doubt it's a significant elo gain.

Thanks Fisherman

**Comment by mcostalba** [comment]
Well I think here we have more slowdown than fix, anyhow the correct code
should be:

  void update(Piece pc, Square to, Value v) {


    if (Gain)

        table[pc][to] = std::max(v, table[pc][to] - 1);


    else

        table[pc][to] = std::max(std::min(table[pc][to] + v, Max), -Max);

  }



Because Max is assumed to be a valid value for history. But, as I said, I
don't think there is any gain.

I would test with SPRT[0, 4]

**Comment by zamar** [comment]
This is not a bug, but feel free to test Marco's suggestion :)

**Comment by mstembera** [comment]
Ok I scheduled a test at low priority.
http://tests.stockfishchess.org/tests/view/54db242e0ebc593e9fac1280

@mcostalba 
I'm sure you are correct about Max being a valid value but the current code only allows Max-1.  Maybe it should be changed to

```c++
else if (abs(table[pc][to] + v) <= Max)
        table[pc][to] +=  v;
```
