### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2515]
Say, @mcostalba, you suggested adding a build chain for Android versions on March of 2018.
You are a developer of stockfish, so you probably have compiled the Android version for public use.
There's arm64v8 version on public release, yet it is not in the Makefile!
You may know how to compile the Android version. 
Btw, stockfish 11 is still not on Android.

**Comment by JavaMast** [comment]
@anonymous7002 
Stockfish 11 (arm7, arm64)
https://app.box.com/s/eosxtv3cf2raq1rkmzswrfr7fde80xqd

===================
Compiled by **hagtorp**  - the author of official Stockfish 10 build for android.

**Comment by anonymous7002** [comment]
What's the difference between Android 6-9 and 10 versions?

**Comment by JavaMast** [comment]
@anonymous7002 
Android 6-9 version may not work on Android 10 devices
If both version works for you - use faster build

=============
If you have another questions about android builds - better ask **hagtorp** on **Outskirts forum**
http://outskirts.altervista.org/forum/viewforum.php?f=40

Stockfish Github page is not good place for this discussion.

**Comment by vondele** [comment]
closing as per previous comment.

However, if improved Arm and or Android build instructions are available, feel free to improve the wiki, or make a PR which fixes short-comings of the current build infrastructure.
