### ISSUE TITLE
possible bug with TB ?

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2533]
I'm reposting here a comment by @svivanov72 for further analysis:

https://github.com/official-stockfish/Stockfish/commit/5ae195ee7e3ccac01b8145f9b7022e352a288f07#commitcomment-37010103

Maybe I'm a bit late to comment here, but what does this patch do to TB win scores? The constant VALUE_MATE_IN_MAX_PLY (= VALUE_MATE - 2 * MAX_PLY) is actually the lower bound of the TB win range. The TB win scores are between this value and VALUE_MATE - MAX_PLY. It seems that the new value_from_tt() interprets them as mates beyond 50-move rule and returns VALUE_MATE_IN_MAX_PLY for all of them. Wouldn't SF lose direction to the TB win because of this?

**Comment by svivanov72** [comment]
Thank you for reposting, I did not have time today to file an issue myself. A couple of thoughts: if I read the code correctly, it effectifely makes all TB win scores in the TT have the same value. Common sense suggests that this is harmful but I don't know how to test this. Perhaps a case may look like this: a distant TB win is found, but then the hash is filled with identical TB win values and SF is having trouble finding an actual winning path.

**Comment by vondele** [comment]
@svivanov72 I think you're right, in the original commit it was overlooked that VALUE_MATE_IN_MAX_PLY is not 'VALUE_MATE - MAX_PLY', but includes TB scores. The obvious fix would be to leave the TB range untouched. Would this be the proper fix in your opinion? 

```diff
diff --git a/src/search.cpp b/src/search.cpp
index 9562bf864..1d50aab01 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1579,9 +1579,9 @@ moves_loop: // When in check, search starts from here
 
   Value value_from_tt(Value v, int ply, int r50c) {
 
-    return  v == VALUE_NONE             ? VALUE_NONE
-          : v >= VALUE_MATE_IN_MAX_PLY  ? VALUE_MATE - v > 99 - r50c ? VALUE_MATE_IN_MAX_PLY  : v - ply
-          : v <= VALUE_MATED_IN_MAX_PLY ? VALUE_MATE + v > 99 - r50c ? VALUE_MATED_IN_MAX_PLY : v + ply : v;
+    return  v == VALUE_NONE            ? VALUE_NONE
+          : v >=  VALUE_MATE - MAX_PLY ? VALUE_MATE - v > 99 - r50c ? VALUE_MATE - MAX_PLY  : v - ply
+          : v <= -VALUE_MATE + MAX_PLY ? VALUE_MATE + v > 99 - r50c ? -VALUE_MATE + MAX_PLY : v + ply : v;
   }

```

interestingly, this also seems to fix https://github.com/official-stockfish/Stockfish/issues/2543
I'm not quite sure yet why that is, any insight would be welcome.

**Comment by svivanov72** [comment]
It seems that this removes the ability to track the distance to TB wins (but I still don't know how to test the effects).
Here is my attempt, weird but doing only two checks in the common case, so it might be even faster despite weirdness.
```iff --git a/src/search.cpp b/src/search.cpp
index 9562bf86..7a6231ca 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1579,9 +1579,12 @@ moves_loop: // When in check, search starts from here
 
   Value value_from_tt(Value v, int ply, int r50c) {
 
-    return  v == VALUE_NONE             ? VALUE_NONE
-          : v >= VALUE_MATE_IN_MAX_PLY  ? VALUE_MATE - v > 99 - r50c ? VALUE_MATE_IN_MAX_PLY  : v - ply
-          : v <= VALUE_MATED_IN_MAX_PLY ? VALUE_MATE + v > 99 - r50c ? VALUE_MATED_IN_MAX_PLY : v + ply : v;
+    return  v >= VALUE_MATE_IN_MAX_PLY ?
+              ( v == VALUE_NONE ? VALUE_NONE
+              : v >= VALUE_MATE - MAX_PLY && VALUE_MATE - v > 99 - r50c ? VALUE_MATE - MAX_PLY : v - ply )
+          : v <= VALUE_MATED_IN_MAX_PLY ?
+              ( v <= -VALUE_MATE + MAX_PLY && VALUE_MATE + v > 99 - r50c ? -VALUE_MATE + MAX_PLY : v + ply )
+          : v;
   }
 
 
```
Why it helps #2543 is a mystery to me. By the way, it displays bogus 'mate in 123' which is probably the score for VALUE_MATE-MAX_PLY. Might be fixable in uci.cpp:263.

**Comment by vondele** [comment]
I looked a little more in how this affects #2543, and it seems that indeed quite a number of mate lines are found that trigger the 50mr condition, before a mate is displayed. Having a mate score, instead of a TB score, definitely helps search with the mate distance pruning trick.

I've also seen the mate 123, which needs understanding but doesn't need to be really bogus.

**Comment by vondele** [comment]
Meanwhile, I've tested 7000 LTC games, with 6men TB, no adjudication, with the old commit that introduced this code (mf), and the commit just before (mfm1). Good news, no indication of a regression:
```
Score of mf vs mfm1: 900 - 858 - 5242  [0.503] 7000
Elo difference: 2.1 +/- 4.1, LOS: 84.2 %, DrawRatio: 74.9 %
```

**Comment by vondele** [comment]
The mate 123, is VALUE_MATE - MAX_PLY, and would be a potential false mate announcement. A good testcase for that is:
```
position fen 8/8/8/3k4/8/8/6K1/7R w - - 0 1
go depth 40
position fen 8/8/8/3k4/8/8/6K1/7R w - - 76 1
go depth 20
ucinewgame
```
the second search should never display a mate.

**Comment by svivanov72** [comment]
> Meanwhile, I've tested 7000 LTC games, with 6men TB, no adjudication, with the old commit that introduced this code (mf), and the commit just before (mfm1). Good news, no indication of a regression:
> 
> ```
> Score of mf vs mfm1: 900 - 858 - 5242  [0.503] 7000
> Elo difference: 2.1 +/- 4.1, LOS: 84.2 %, DrawRatio: 74.9 %
> ```

Interesting... Did this test use a large hash or the 8MB?

**Comment by vondele** [comment]
standard LTC hash (64MB)

**Comment by vondele** [comment]
So, I'm converging on this patch:
```diff
diff --git a/src/search.cpp b/src/search.cpp
index c8a35a36d..50e91515a 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1578,10 +1578,9 @@ moves_loop: // When in check, search starts from here
   // from current position) to "plies to mate/be mated from the root".
 
   Value value_from_tt(Value v, int ply, int r50c) {
-
-    return  v == VALUE_NONE             ? VALUE_NONE
-          : v >= VALUE_MATE_IN_MAX_PLY  ? VALUE_MATE - v > 99 - r50c ? VALUE_MATE_IN_MAX_PLY  : v - ply
-          : v <= VALUE_MATED_IN_MAX_PLY ? VALUE_MATE + v > 99 - r50c ? VALUE_MATED_IN_MAX_PLY : v + ply : v;
+    return  v == VALUE_NONE            ? VALUE_NONE
+          : v >=  VALUE_MATE - MAX_PLY ? VALUE_MATE - v > 99 - r50c ?  VALUE_MATE - MAX_PLY - 1 : v - ply
+          : v <= -VALUE_MATE + MAX_PLY ? VALUE_MATE + v > 99 - r50c ? -VALUE_MATE + MAX_PLY + 1 : v + ply : v;
   }
 
 ```

this should have no effect on TB, remain effective at not showing false mate scores, and seems to be fixing the mate finding ability. Basically, a potentially false mate (i.e. 50mrc) is now treated as a good TB hit.

**Comment by vondele** [comment]
@svivanov72 I'm not moving the VALUE_NONE comparison down, as I don't really like these comparisons that depend on the value of defined constants (i.e. VALUE_NONE being positive or negative).

**Comment by svivanov72** [comment]
Your patch no longer inverts value_to_tt() for TB win scores. On saving the score to TT, value_to_tt() adds ply converting "plies from root" to "plies from here". Then value_from_tt() does not convert it back.

I tired in on 1R6/3k4/8/K2p4/4n3/2P5/8/8 w - - 0 1 (a TB win win DTZ 51) with 5 men tablebases and hash 2048. The search slows down significantly after seeing the TB win.

Your patch:
info depth 53 seldepth 66 multipv 1 score cp 6527 nodes 83931592
info depth 54 seldepth 70 multipv 1 score cp 14896 nodes 220108514
info depth 55 seldepth 72 multipv 1 score cp 14897 nodes 552429418
info depth 56 seldepth 76 multipv 1 score cp 14907 nodes 1560047423
info depth 57 seldepth 62 multipv 1 score cp 14907 nodes 2837229053
info depth 58 seldepth 64 multipv 1 score cp 14907 nodes 3068843357

Current master:
info depth 53 seldepth 66 multipv 1 score cp 6527 nodes 83931592
info depth 54 seldepth 60 multipv 1 score cp 14792 nodes 88277454
info depth 55 seldepth 62 multipv 1 score cp 14792 nodes 99331730
info depth 56 seldepth 65 multipv 1 score cp 14792 nodes 115376430
info depth 57 seldepth 64 multipv 1 score cp 14792 nodes 117287811
info depth 58 seldepth 65 multipv 1 score cp 14792 nodes 133052492

The variant with pre-5ae195e value_from_tt():
info depth 53 seldepth 57 multipv 1 score cp 6583 nodes 48445646
info depth 54 seldepth 60 multipv 1 score cp 6608 nodes 48716562
info depth 55 seldepth 66 multipv 1 score cp 14876 nodes 49142009
info depth 56 seldepth 62 multipv 1 score cp 14876 nodes 50018467
info depth 57 seldepth 70 multipv 1 score cp 14878 nodes 53119443
info depth 58 seldepth 78 multipv 1 score cp 14881 nodes 59161631

**Comment by vondele** [comment]
right... overlooked the TB case. Let me have a more careful look. Thanks for your help, BTW.

**Comment by vondele** [comment]
this should be fixed now, thanks for your report and the help.
