### ISSUE TITLE
Stockfish crashes on certain positions 

### ISSUE THREAD

**Issue by shlosmem** [official-stockfish/Stockfish#2549]
Command Example:
$stockfish position fen "q3kb2/rbpppppr/p1n4p/1p1n4/P4PB1/NP2P3/1RPP2PP/2B1QKNR b kq - 1 1"
Happens in several versions.

**Comment by Matthies** [comment]
FEN string is illegal (pieces vs. castle rights). Stockfish doesn't check fen for legality, that is job of the GUI / the user.

**Comment by vondele** [comment]
yes, not an issue.
