### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Rakicc** [official-stockfish/Stockfish#2556]
How to distribute it on armv7 for android?
It will create exe file.
CXXFLAGS='-static' make -j profile-build ARCH=armv7 COMP=mingw
So I stripped by , strip stockfish.exe -o stockfish.armv7
Not working in Android, also tried  by changing code armv7 instead of EXE on makefile, result is same it produces binaries only...

**Comment by vondele** [comment]
see other issues on missing toolchain and docs for arm
