### ISSUE TITLE
Number of moves returned fewer than expected

### ISSUE THREAD

**Issue by KQRBNP** [official-stockfish/Stockfish#2560]
In stockfish-10-bmi2 for Mac:
go depth 6
info depth 1 seldepth 1 multipv 1 score cp 116 nodes 20 nps 10000 tbhits 0 time 2 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 112 nodes 54 nps 27000 tbhits 0 time 2 pv e2e4 b7b6
info depth 3 seldepth 3 multipv 1 score cp 148 nodes 136 nps 68000 tbhits 0 time 2 pv d2d4 d7d6 e2e4
info depth 4 seldepth 4 multipv 1 score cp 137 nodes 247 nps 123500 tbhits 0 time 2 pv d2d4 e7e6 e2e4 c7c6
info depth 5 seldepth 5 multipv 1 score cp 77 nodes 1157 nps 385666 tbhits 0 time 3 pv **c2c3 d7d5 d2d4 b8c6 c1g5** **<-- 5 moves here**
info depth 6 seldepth 6 multipv 1 score cp 83 nodes 2250 nps 562500 tbhits 0 time 4 pv e2e4 b8c6 d2d4 d7d6 f1c4 g8f6
bestmove e2e4 ponder b8c6

In stockfish-11-bmi2 for Mac:
go depth 6
info depth 1 seldepth 1 multipv 1 score cp 114 nodes 20 nps 20000 tbhits 0 time 1 pv e2e3
info depth 2 seldepth 2 multipv 1 score cp 126 nodes 54 nps 54000 tbhits 0 time 1 pv e2e3 b7b6
info depth 3 seldepth 3 multipv 1 score cp 124 nodes 147 nps 147000 tbhits 0 time 1 pv e2e3 b7b6 f1c4
info depth 4 seldepth 4 multipv 1 score cp 75 nodes 574 nps 287000 tbhits 0 time 2 pv d2d4 e7e6 e2e3 b8c6
info depth 5 seldepth 5 multipv 1 score cp 86 nodes 782 nps 391000 tbhits 0 time 2 pv **c2c3 b8c6 d2d4 d7d6**  **<-- only 4 moves here??**
info depth 6 seldepth 6 multipv 1 score cp 56 nodes 2734 nps 683500 tbhits 0 time 4 pv d2d4 c7c6 g1f3 d7d5 c2c3 g8f6
bestmove d2d4 ponder c7c6

**Comment by vondele** [comment]
no that's not a bug. The length of the principal variation (pv) can be anything, in particular shorter than the depth.

**Comment by KQRBNP** [comment]
If you type 'go depth 5', you'd expect to see pv of length 5, but you ended up seeing this:

go depth 5
... (skip) ...
info depth 5 seldepth 5 multipv 1 score cp 86 nodes 782 nps 260666 tbhits 0 time 3 pv c2c3 b8c6 d2d4 d7d6 **<- this only gives you pv of length 4**
bestmove c2c3 ponder b8c6

**Comment by vondele** [comment]
that's what I'm trying to say, it is the wrong expectation. There is nothing in the code that guarantees a pv of a length equal to the depth.... I guess stockfish shares this behavior with essentially any other engine out there.

**Comment by KQRBNP** [comment]
interesting. How is the length of the pv generated then? Isn't depth the ply search depth?

**Comment by vondele** [comment]
Too complicated for an issue tracker ;-) Basically depth is indicative of the depth, but all kinds of tricks that make an engine strong come into play (reductions, extensions, aspiration windows, etc.), change the effective depth. Have a look here https://www.chessprogramming.org/
