### ISSUE TITLE
New idea for improving SF

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2566]
The regression tests are showing some disappointing results so I figured I'd throw this idea I've had for a while now out there so people can discuss. It's obviously a lot harder to improve SF now so perhaps it's time to rethink our strategy for improving and testing SF a little bit.
Is it possible to create opening specific patches? So we can split opening books into one or two move openings and then we can try to create some patches for specific openings using the opening specific book, then run a non-regression test on the whole book.

**Comment by Sopel97** [comment]
To me this seems like an equivalent of tightenning the sprt bounds. If a patch gains 1 elo in some specific openning it may gain something like .25 elo in general. This basically reduces elo/patch and is equivalent to throwing more resources at testing.

**Comment by vdbergh** [comment]
@Sopel97 I do not think this is true. I think the bounds are currently about as tight as they can reasonably be. A method as proposed by the OP could lead to progress without requiring further tightening of the bounds.

While I do not necessarily think that splitting up the opening book according to the ECO code is a good idea, I do believe that by using specialized opening books it may be possible to make progress on positions with specific features. The resulting changes can then be tested for non-regression with the standard book. Hopefully with enough such changes, the Elo gain will also become visible with the standard book.

**Comment by Sopel97** [comment]
well, you can do arbitrarily narrow elo bounds, like https://tests.stockfishchess.org/html/SPRTcalculator.html?elo-0=-1&elo-1=3&draw-ratio=0.61&rms-bias=0 for example. But it tends to a ridiculous amount of games. Still not obvious what is better though.

**Comment by Sopel97** [comment]
You can get arbitrarily narrow bounds. https://tests.stockfishchess.org/html/SPRTcalculator.html?elo-0=0&elo-1=0.5&draw-ratio=0.61&rms-bias=0
The amount of games just obviously get much higher.

**Comment by NKONSTANTAKIS** [comment]
I consider even more promising a full optimization on different opening categories. Lets say 3 categories (open closed semi). Instead of just gaining elo in a subset and not regressing in generic,  the appropriate parametrization will be selected on the fly.

**Comment by adentong** [comment]
Given that we're still making progress (albeit more slowly) I will close this. We can also revisit this idea later.
