### ISSUE TITLE
Android Stockfish 11 not yet available 

### ISSUE THREAD

**Issue by rackbrain** [official-stockfish/Stockfish#2576]
When will Stockfish 11 be available to download for Android?

**Comment by vondele** [comment]
see https://groups.google.com/d/msg/fishcooking/nwSNnMe02mg/LweAclBRBAAJ for more info, and how to obtain an Android binary. 

Having said that, yes, it is still missing on the official download page. I guess we need somebody with Android expertise to step forward and tackle some of the open issues.

**Comment by JavaMast** [comment]
@rackbrain 
Stockfish 11 for Android is available here: 
https://app.box.com/s/eosxtv3cf2raq1rkmzswrfr7fde80xqd

**Comment by SAMOUELt** [comment]
كنت افكر علي اقتراح تجميع محرك ستوك بشبكة عصبيه ضخمة علي الانتر نت. بحيثو يكون متاح للمستخدمين. ويتم تشغيل المحرك. بلانترنت بحيث يكون مخزون جميع العاب 
 .المحرك للمستخدمين في شبكه عصبيه وحده 
 بصوره مبسطه كل ما علي المستخدم وصل ‘النت وفت الوجها ثم تشغيل المحرك سوف يلتقط المحرك جميع بينات الشبكه ‘‘

**Comment by vondele** [comment]
I'll close this, there is more effort going on in https://github.com/official-stockfish/Stockfish/issues/2860 to get to a proper build process for Android.
