### ISSUE TITLE
Increased time spent on obvious moves

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#2582]
We have the following position:

SF spent 4 minutes of time under the control of 120 + 30.
My question is: what did he analyze there?

![Capture](https://user-images.githubusercontent.com/51216501/76643847-ecac3600-6566-11ea-883c-51edb4b44b80.PNG)

This allows you to be optimized, perhaps at a depth of 30 rather than 47?

**Comment by Marat-Ka** [comment]
As an example: if you are a master or grandmaster, how much do you plan to think about this move?

**Comment by ddugovic** [comment]
Here is what it analyzed:
![image](https://user-images.githubusercontent.com/1834123/76649571-fa45c980-652e-11ea-9837-caaf432d729e.png)

**Comment by Marat-Ka** [comment]
In addition: I used the most popular 7-man tables located on RAID5 of 6 mechanical HDDs. Only some 7-man were on SSD. But all 6 and below tables were on SSD.

**Comment by vondele** [comment]
I'll close this as this is not really an issue, but a suggestion for a patch. Feel free to experiment with this on fishtest: https://github.com/glinscott/fishtest/wiki/Creating-my-first-test

Various tests have been tried in this direction in the past, usually without effect.
