### ISSUE TITLE
go commands order

### ISSUE THREAD

**Issue by sallyx** [official-stockfish/Stockfish#2601]
"go movetime 6000 searchmoves c2c4" search for 6 seconds, but 
"go searchmoves c2c4  movetime 6000" does not.

**Comment by joergoster** [comment]
Unfortunately, the description of the UCI protocol is not very clear in that (and other) regard.
But it seems reasonable to only support the 1st command which is also the one sent by GUIs afaik.

> 	* searchmoves <move1> .... <movei>
> 		restrict search to this moves only
> 		Example: After "position startpos" and "go infinite searchmoves e2e4 d2d4"
> 		the engine should only search the two moves e2e4 and d2d4 in the initial position.

**Comment by sallyx** [comment]
UCI protocol says only "There are a number of commands that can follow this command, all will be sent in the same string."  and then list the command in order where searchmoves is first and movtime almost last.  How can one conlude from this taht searchmoves MUST be after movetime?

What about other commands, do I have to send first winc and then wtime, but in case I send depth i need to send wtime, dept and then winc, but in case i send mat and not btime, btime must go after mate but not before movetime? What are the rules really?

**Comment by vondele** [comment]
all commands can be anywhere on the line except searchmoves. The reason is that it can be followed by an arbitrary number of tokens. All tokes following searchmoves are interpreted as a move, and ignored if illegal: https://github.com/official-stockfish/Stockfish/blob/58746d9fb8bab4e9617cd7c809c6a0afd809c35e/src/uci.cpp#L117-L133

**Comment by sallyx** [comment]
I understand this is easy to code like this, but "go searchmoves c2c4 movetime 6000" sends "go" command with "searchmoves" and "movetime" in one string and UCI protocol is clear in how they should be interpreted.

Would It be hard to use something like `std::regex(".*searchmoves((:?\\s+[a-h][1-8][a-h][1-8][qrbn]?)+).*")`

**Comment by ddugovic** [comment]
I think vondele's answer is sufficient provided that we can document it somewhere.

**Comment by joergoster** [comment]
@sallyx Did you even read what I wrote?
> Unfortunately, the description of the UCI protocol is not very clear in that (and other) regard.


> UCI protocol says only "There are a number of commands that can follow this command, all will be sent in the same string." and then list the command in order where searchmoves is first and movtime almost last. How can one conlude from this taht searchmoves MUST be after movetime?

Where exactly did I state this? I said _it seems reasonable ..._

I have a question for you:
Do you think it makes sense to send `wtime` and `btime` options if you want to search to a specified depth with 'go depth x'?

Applying some common sense is certainly of help here ...

**Comment by MichaelB7** [comment]
Shredder, written by Stefan Meyer-Kahlen , the one who created the UCI protocol, does not follow the suggestion provided by @Sallyx.  If suggest if you desire a change to the UCI protocol or wish it is made more clear, please contact  the UCI protocol author directly, Stefan Meyer-Kahlen at support@shredderchess.com.  Everyone I know understands the parameter searchmoves should always come last for the reasons @vondele stated.

**Comment by vondele** [comment]
I've documented this in the code as part of https://github.com/official-stockfish/Stockfish/pull/2584
