### ISSUE TITLE
Parameter tweak bounds

### ISSUE THREAD

**Issue by NKONSTANTAKIS** [official-stockfish/Stockfish#2614]
Traditionally tweaks have had easier bounds due not adding code complexity. After the first change from [0.5] [0,5] their status was frozen by @mcostalba for assessing "one change at a time". For quite a while tweaks had harder bounds! Now they use the same. But the initial discussion never took focus.

Is the current status quo a crystallized plan? If yes, is there a reasoning for same treatment of patches which do not add code and ones that they do? Is it maybe to deter efforts on tweaks, as less important?

**Comment by NKONSTANTAKIS** [comment]
I think its a fine strategy runs like those to be merged
https://tests.stockfishchess.org/tests/view/5e96e110a14112562c92c691
https://tests.stockfishchess.org/tests/view/5e972323a14112562c92c6ee

I can only locate Pros:
1. Equal complexity to master, even if they are +0.1 elo its good. 
2. +1 elo having 50% chance, basically guarantees that the bulk of those will be on the +0.5 to +1.2 range. Just 1 in 50 will be 0 elo, so this strategy will surely boost progress.
3. Saving resources from subsequent tests of slight modifications.

This will also allow a regular filling of the small gaps that drastic changes create, the dynamics so to say.

**Comment by vondele** [comment]
no, just merging in yellow patches makes no sense. More work for the maintainer, more risk of regression. Both patches you link to have 20-30% prob to be < 0 Elo.

However, to make it easier for people to make parameter tweak combo patches, or add such patches as 'compensation': 
* there is now a link that lists yellow patches:
https://tests.stockfishchess.org/tests/finished?yellow_only=1 (with button on the main page).
* Each test page also now a button to quickly apply them to a local branch (look for `Copy apply-diff command`)
