### ISSUE TITLE
Compile StockFish (SF) for Android

### ISSUE THREAD

**Issue by kandalto** [official-stockfish/Stockfish#2617]
Hi!

 I've looked at the previous issues, but wasn't able to find a comprehensive list of instruction on how to compile SF for Android (Droidfish in particular). Sorry if it was already answered before.

Cheers!

**Comment by museum-future** [comment]
i think the information is in the Makefile

**Comment by vondele** [comment]
I'll close this, there is more effort going on in #2860 to get to a proper build process for Android.
