### ISSUE TITLE
MultiPv Blunders

### ISSUE THREAD

**Issue by user6812** [official-stockfish/Stockfish#2625]
White has left his bishop en prise on e6.  
What would you guess is the Stockfish shallow (depth 2) reply, QPxB or BPxB?
```
---a-b-c-d-e-f-g-h---
8  r n . q k b . r  8
7  p b p p . p p p  7
6  . p . . B n . .  6
5  . . . . . . . .  5
4  . . . . P . . .  4
3  . . . P . N . .  3
2  P P P . . P P P  2
1  R N B Q K . . R  1
---a-b-c-d-e-f-g-h---

rn1qkb1r/pbpp1ppp/1p2Bn2/8/4P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 0 5
BLACK to move

Stockfish 11 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
> uci
id name Stockfish 11 64
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott
...options...
uciok
> setoption name Ponder value false
> setoption name MultiPV value 8
> setoption name Threads value 1
> position fen rn1qkb1r/pbpp1ppp/1p2Bn2/8/4P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 0 5
> isready
readyok
> go depth 2
info depth 1 seldepth 1 multipv 1 score cp 371 nodes 278 nps 92666 tbhits 0 time 3 pv d7e6
info depth 1 seldepth 1 multipv 2 score cp 324 nodes 278 nps 92666 tbhits 0 time 3 pv f7e6
info depth 1 seldepth 1 multipv 3 score cp 76 nodes 278 nps 92666 tbhits 0 time 3 pv f6e4 d3e4 d7e6 d1d8 e8d8
info depth 1 seldepth 1 multipv 4 score cp -21 nodes 278 nps 92666 tbhits 0 time 3 pv b7e4 d3e4 d7e6 d1d8 e8d8
info depth 1 seldepth 1 multipv 5 score cp -30 nodes 278 nps 92666 tbhits 0 time 3 pv b8c6
info depth 1 seldepth 1 multipv 6 score cp -32 nodes 278 nps 92666 tbhits 0 time 3 pv d8e7
info depth 1 seldepth 1 multipv 7 score cp -63 nodes 278 nps 92666 tbhits 0 time 3 pv f8c5
info depth 1 seldepth 1 multipv 8 score cp -73 nodes 278 nps 92666 tbhits 0 time 3 pv b8a6
info depth 2 seldepth 2 multipv 1 score cp 379 nodes 599 nps 199666 tbhits 0 time 3 pv b8c6 c2c3 d7e6
info depth 2 seldepth 2 multipv 2 score cp 323 nodes 599 nps 199666 tbhits 0 time 3 pv f8c5 c2c3 d7e6
info depth 2 seldepth 2 multipv 3 score cp 320 nodes 599 nps 199666 tbhits 0 time 3 pv d7e6 c2c3
info depth 2 seldepth 2 multipv 4 score cp 318 nodes 599 nps 199666 tbhits 0 time 3 pv f7e6 c2c3
info depth 2 seldepth 2 multipv 5 score cp 316 nodes 599 nps 199666 tbhits 0 time 3 pv b8a6 c2c3 f7e6
info depth 2 seldepth 2 multipv 6 score cp 301 nodes 599 nps 199666 tbhits 0 time 3 pv d8e7 c2c3 f7e6
info depth 2 seldepth 2 multipv 7 score cp 76 nodes 599 nps 199666 tbhits 0 time 3 pv f6e4 d3e4
info depth 2 seldepth 2 multipv 8 score cp -21 nodes 599 nps 199666 tbhits 0 time 3 pv b7e4 d3e4 d7e6
bestmove b8c6 ponder c2c3

**Comment by vondele** [comment]
well, low depth, multiPV, and a heavily pruning engine, what is the issue? 

move ordering, hash, etc is all set by the PV 3 - 8, and hence quite garbage at such low depth.

**Comment by user6812** [comment]
I have tried to present the simplest example I've run across. (Stockfish 8 did this kind of thing at depths of 5 or 6.) My expectation was that multipv would hurt performance because it would necessarily limit pruning. Instead, I think you're telling me that---to keep up performance---it is the quality of the multipv that is sacrificed. Is there some switch to tip the balance of this trade-off?

**Comment by vondele** [comment]
what I'm suggesting is that the search at depth 2, first has to recover of the search of depth 1 for PVs 3 - 8, which basically pollutes heuristics. But (presumably) only a such a low depth. SF is really optimized to return the best move within a certain time, not a certain depth. MultiPV N is mostly worse than MultiPV 1 as it searches carefully N lines, and hence has about 1/Nth of the time to search the best move.

I guess the issue can be closed. reopen that is not the case.

**Comment by joergoster** [comment]
@user6812 Thank you for posting this. This helped me fixing a bug!

This is what I get with **Moonfish** (see https://github.com/joergoster/Moonfish):

> setoption name MultiPV value 8
> info string MultiPV set to 8
> ucinewgame
> isready
> readyok
> position fen rn1qkb1r/pbpp1ppp/1p2Bn2/8/4P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 0 5
> go depth 2
> info depth 1 seldepth 1 multipv 1 score cp 359 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv d7e6
> info depth 1 seldepth 1 multipv 2 score cp 312 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv f7e6
> info depth 1 seldepth 5 multipv 3 score cp 62 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv f6e4 d3e4 d7e6 d1d8 e8d8
> info depth 1 seldepth 5 multipv 4 score cp -35 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv b7e4 d3e4 d7e6 d1d8 e8d8
> info depth 1 seldepth 1 multipv 5 score cp -41 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv b8c6
> info depth 1 seldepth 1 multipv 6 score cp -44 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv d8e7
> info depth 1 seldepth 1 multipv 7 score cp -69 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv f8c5
> info depth 1 seldepth 1 multipv 8 score cp -84 nodes 89 nps 89000 tbhits 0 terminalHits 0 time 1 pv b8a6
> info depth 2 seldepth 3 multipv 1 score cp 292 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv d7e6 e1g1 b8c6
> info depth 2 seldepth 3 multipv 2 score cp 260 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv f7e6 b1c3
> info depth 2 seldepth 9 multipv 3 score cp 50 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv d7d5 f3d4 f7e6 d4e6
> info depth 2 seldepth 5 multipv 4 score cp -50 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv f6e4 e6f7 e8f7 d3e4 b7e4
> info depth 2 seldepth 4 multipv 5 score cp -99 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv d8e7 e6c4
> info depth 2 seldepth 4 multipv 6 score cp -115 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv b8c6 e6c4
> info depth 2 seldepth 6 multipv 7 score cp -118 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv f8b4 c2c3 d7e6 c3b4
> info depth 2 seldepth 4 multipv 8 score cp -136 nodes 2350 nps 783333 tbhits 0 terminalHits 0 time 3 pv f8c5 e6c4
> bestmove d7e6 ponder e1g1

@vondele I tend to disagree.

The best move at any given time is either
- the best move of the just finished iteration
- the best move of the moves we have searched so far at the current iteration (search has been stopped)

**Comment by vondele** [comment]
feel free to reopen and or post a patch that fixes this... I didn't check the code carefully. 

One issue is that we don't have a good protocol to test MultiPV patches.

**Comment by joergoster** [comment]
@vondele This is the least invasive I can come up with. https://github.com/joergoster/Stockfish/commit/9c93a4c3787e35fd7baf905c85c3e176e30b70de

**MultiPV=8 output of the above position:**
info depth 1 seldepth 1 multipv 1 score cp 376 nodes 281 nps 140500 tbhits 0 time 2 pv d7e6
info depth 1 seldepth 1 multipv 2 score cp 329 nodes 281 nps 140500 tbhits 0 time 2 pv f7e6
info depth 1 seldepth 1 multipv 3 score cp 73 nodes 281 nps 140500 tbhits 0 time 2 pv f6e4 d3e4 d7e6 d1d8 e8d8
info depth 1 seldepth 1 multipv 4 score cp -22 nodes 281 nps 140500 tbhits 0 time 2 pv b8c6
info depth 1 seldepth 1 multipv 5 score cp -23 nodes 281 nps 140500 tbhits 0 time 2 pv b7e4 d3e4
info depth 1 seldepth 1 multipv 6 score cp -24 nodes 281 nps 140500 tbhits 0 time 2 pv d8e7
info depth 1 seldepth 1 multipv 7 score cp -51 nodes 281 nps 140500 tbhits 0 time 2 pv f8c5
info depth 1 seldepth 1 multipv 8 score cp -65 nodes 281 nps 140500 tbhits 0 time 2 pv b8a6
info depth 2 seldepth 3 multipv 1 score cp 308 nodes 1650 nps 550000 tbhits 0 time 3 pv d7e6 e1g1 b8c6
info depth 2 seldepth 3 multipv 2 score cp 276 nodes 1650 nps 550000 tbhits 0 time 3 pv f7e6 b1c3
info depth 2 seldepth 2 multipv 3 score cp 92 nodes 1650 nps 550000 tbhits 0 time 3 pv d7d5 e4e5 f7e6 e5f6 g7f6
info depth 2 seldepth 2 multipv 4 score cp -38 nodes 1650 nps 550000 tbhits 0 time 3 pv f6e4 e6f7 e8f7
info depth 2 seldepth 2 multipv 5 score cp -79 nodes 1650 nps 550000 tbhits 0 time 3 pv d8e7 e6c4
info depth 2 seldepth 2 multipv 6 score cp -95 nodes 1650 nps 550000 tbhits 0 time 3 pv b8c6 e6c4
info depth 2 seldepth 3 multipv 7 score cp -98 nodes 1650 nps 550000 tbhits 0 time 3 pv f8b4 c2c3 d7e6 c3b4
info depth 2 seldepth 2 multipv 8 score cp -118 nodes 1650 nps 550000 tbhits 0 time 3 pv f8c5 e6c4
bestmove d7e6 ponder e1g1

This version is significantly stronger at fixed depth=2 (although many will consider this meaningless):

> Finished game 2000 (SF-Master vs SF-LowPlies4a): 0-1 {Black wins by adjudication}
> Score of SF-LowPlies4a vs SF-Master: 1524 - 324 - 152  [0.800] 2000              // fixed depth 2
> Elo difference: 240.8 +/- 17.9, LOS: 100.0 %, DrawRatio: 7.6 %
> Finished match

And still competitive at ultrafast 1"+0.01" time control:

> Finished game 500 (SF-Master vs SF-LowPlies4a): 1/2-1/2 {Draw by 3-fold repetition}
> Score of SF-LowPlies4a vs SF-Master: 196 - 173 - 131  [0.523] 500
> Elo difference: 16.0 +/- 26.2, LOS: 88.4 %, DrawRatio: 26.2 %
> Finished match

Note: This is not necessarily a MultiPV issue, it's just that a MultiPV search much better _reveals_ the consequences of the shallow pruning during the very first iterations.

**Comment by joergoster** [comment]
And another example from the start position.

**master**
info depth 1 seldepth 1 multipv 1 score cp 112 nodes 132 nps 132000 tbhits 0 time 1 pv e2e3
info depth 1 seldepth 1 multipv 2 score cp 107 nodes 132 nps 132000 tbhits 0 time 1 pv e2e4
info depth 1 seldepth 1 multipv 3 score cp 96 nodes 132 nps 132000 tbhits 0 time 1 pv d2d4
info depth 1 seldepth 1 multipv 4 score cp 94 nodes 132 nps 132000 tbhits 0 time 1 pv d2d3
info depth 1 seldepth 1 multipv 5 score cp 65 nodes 132 nps 132000 tbhits 0 time 1 pv b1c3
info depth 1 seldepth 1 multipv 6 score cp 61 nodes 132 nps 132000 tbhits 0 time 1 pv g1f3
info depth 1 seldepth 1 multipv 7 score cp 30 nodes 132 nps 132000 tbhits 0 time 1 pv b2b3
info depth 1 seldepth 1 multipv 8 score cp 29 nodes 132 nps 132000 tbhits 0 time 1 pv c2c4
info depth 2 seldepth 2 multipv 1 score cp 124 nodes 313 nps 313000 tbhits 0 time 1 pv e2e3 b7b6
info depth 2 seldepth 2 multipv 2 score cp 119 nodes 313 nps 313000 tbhits 0 time 1 pv e2e4 b7b6
info depth 2 seldepth 2 multipv 3 score cp 91 nodes 313 nps 313000 tbhits 0 time 1 pv d2d4 c7c6
info depth 2 seldepth 2 multipv 4 score cp 86 nodes 313 nps 313000 tbhits 0 time 1 pv d2d3 c7c6
info depth 2 seldepth 2 multipv 5 score cp 68 nodes 313 nps 313000 tbhits 0 time 1 pv g1f3 b7b6
info depth 2 seldepth 2 multipv 6 score cp 61 nodes 313 nps 313000 tbhits 0 time 1 pv b1c3 c7c6
info depth 2 seldepth 2 multipv 7 score cp 41 nodes 313 nps 313000 tbhits 0 time 1 pv h2h4 b7b6
info depth 2 seldepth 2 multipv 8 score cp 40 nodes 313 nps 313000 tbhits 0 time 1 pv g2g4 b7b6

**patch**
info depth 1 seldepth 1 multipv 1 score cp 112 nodes 132 nps 132000 tbhits 0 time 1 pv e2e3
info depth 1 seldepth 1 multipv 2 score cp 107 nodes 132 nps 132000 tbhits 0 time 1 pv e2e4
info depth 1 seldepth 1 multipv 3 score cp 96 nodes 132 nps 132000 tbhits 0 time 1 pv d2d4
info depth 1 seldepth 1 multipv 4 score cp 94 nodes 132 nps 132000 tbhits 0 time 1 pv d2d3
info depth 1 seldepth 1 multipv 5 score cp 65 nodes 132 nps 132000 tbhits 0 time 1 pv b1c3
info depth 1 seldepth 1 multipv 6 score cp 61 nodes 132 nps 132000 tbhits 0 time 1 pv g1f3
info depth 1 seldepth 1 multipv 7 score cp 30 nodes 132 nps 132000 tbhits 0 time 1 pv b2b3
info depth 1 seldepth 1 multipv 8 score cp 29 nodes 132 nps 132000 tbhits 0 time 1 pv c2c4
info depth 2 seldepth 2 multipv 1 score cp 37 nodes 607 nps 303500 tbhits 0 time 2 pv e2e3 e7e6
info depth 2 seldepth 2 multipv 2 score cp 32 nodes 607 nps 303500 tbhits 0 time 2 pv e2e4 e7e6
info depth 2 seldepth 2 multipv 3 score cp 14 nodes 607 nps 303500 tbhits 0 time 2 pv d2d4 e7e6
info depth 2 seldepth 2 multipv 4 score cp -5 nodes 607 nps 303500 tbhits 0 time 2 pv d2d3 e7e5
info depth 2 seldepth 2 multipv 5 score cp -13 nodes 607 nps 303500 tbhits 0 time 2 pv g1f3 e7e6
info depth 2 seldepth 2 multipv 6 score cp -18 nodes 607 nps 303500 tbhits 0 time 2 pv b1c3 e7e6
info depth 2 seldepth 2 multipv 7 score cp -39 nodes 607 nps 303500 tbhits 0 time 2 pv h2h4 e7e6
info depth 2 seldepth 2 multipv 8 score cp -40 nodes 607 nps 303500 tbhits 0 time 2 pv c2c3 e7e6

More reasonable scores and PVs.

**Comment by user6812** [comment]
Thanks, Jörg, I have switched to Moonfish.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Monday, April 13, 2020 4:33 AM, Jörg Oster <notifications@github.com> wrote:
[@user6812](https://github.com/user6812) Thank you for posting this. This helped me fixing a bug!

**Comment by Vizvezdenec** [comment]
tbh who can possibly care about fixed depth 2?

**Comment by joergoster** [comment]
I do.

**Comment by vdbergh** [comment]
It is well known that SF may  blunder at low depth (this is often reported). This is caused by late move pruning in PV nodes. Perhaps multi PV reinforces this.

**Comment by vondele** [comment]
I think this is thus not a particular bug in MultiPV, but just related to the very low search depth. Of course one could prune less at low depth, but optimizing for ultra STC is not a goal, so I would not add code for it, unless it is an improvement at our usual TCs.
