### ISSUE TITLE
LTC tunes should be run at lower priority

### ISSUE THREAD

**Issue by xoto10** [official-stockfish/Stockfish#2635]
I believe tunes stress the fishtest server quite hard. Also 100k+ LTC games is a very large load and I think any LTC job that isn't a SPRT test that will lead directly to a patch should run at a lower priority.

Thoughts?

Edit: I mean lower throughput of course, not priority

**Comment by vondele** [comment]
non-sprt runs already have a reduced throughput automatically (0.5x) (see calc_itp in fishtest). So, at least it is accounted for in part. I believe authors should indeed consider tunes at LTC (which are kind of speculative) to be reduced even more.

**Comment by Alayan-stk-2** [comment]
With 7K cores on like we have right now, there isn't a big issue when it comes to slowing down other tests. For server stress though this might be problematic.

In any case, care should be taken that the tune has a reasonable chance of success : tune something useful, have values that don't stay static...

LTC is kind of the norm for tunes nowadays. Shorter tune can be useful to get an approximation on a new term, but when refining existing values short TC tunes have a very poor record.

**Comment by locutus2** [comment]
I support reducing throughput for LTC tuning. At least half it so in effect we have 1/4.
That we have many cores is no argument because that many we have not regulary. And then the tunings clutter up the test queue. And if we have that many cores the tunings are not really so hurt.

**Comment by vondele** [comment]
My opinion is that we should not enforce it by code, but that tuning patch authors should either do that spontaneously (since LTC tuning is not the rule or the policy), or if things are excessive enforced by the approvers (nobody needs to approve an LTC tuning patch, and approvers can adjust tp if deemed appropriate). Right now, I don't see we have an urgent problem. Last 200 tests or so included 2 tuning runs.

**Comment by Alayan-stk-2** [comment]
LTC tuning is pretty much the rule or the policy. It hasn't been very successful, but low TC tuning has an abysmal success rate.

**Comment by vondele** [comment]
I'll close this issue. Note that there is a fishtest issue looking into SPSA, and if the current default parameters are good enough https://github.com/glinscott/fishtest/issues/535
