### ISSUE TITLE
SF search is poor with 128 cores or 256 threads

### ISSUE THREAD

**Issue by hero2017** [official-stockfish/Stockfish#2647]
So I've had this dual epyc 7742 system for a while now, analyzed quite a few games now and if there's one thing that I've learned is that this system plays weak with ugly and boring games. I am consistently finding better moves (or my opponents are) that it otherwise does not find by forcing moves on my own. This is even more evident when it comes to the response moves, another words not the root moves but after the root move is played, the opponent's move replies with its own move that SF never expected, even after searching the position for many hours. I've been playing correspondence for over a decade now and on my dual xeon E5-2696v3 (36 cores, 72 threads) that was quite rare in comparison.

Although this system is about 3x faster it seems to play worse than the dual xeon. That should not be true. I've played dozens of games now and drew them all and that has never happened to me in the 10+ yrs I've played. Yes you may say it's a rare coincidence but I can tell just by the moves it's analyzing. I know it's expected that the engine can play better when you help it along and play out the lines it finds and going back to the root position. But this was just a lot less necessary on the xeon system as I'd rarely help it find a better move than I do now.

So it doesn't matter if HT is off or not it just keeps missing moves, even at the root. I don't know how to test it from a programmer's point of view but I'm open to run any tests that would help convince someone on the SF team. One other thing. With SF on this system I often hit a depth of 70, 80 or even 90 - on the 10th move after just an hour or so!! This leads me to think that SF prunes way too much.

If there's anything I can try tweaking in the code I'm happy to recompile and try on my own. Just let me know what values I should try changing.

**Comment by vondele** [comment]
first thing to try would be to quantify the effect, set up a match between your dual xeon and your dual epyc, and report the result of a match here.

**Comment by vondele** [comment]
BTW https://tests.stockfishchess.org/tests/view/5b391fae0ebc5902b2e60162 is a thread testing 384 (hyper threads) against 192 threads, now almost 2 years ago. In that setting yielded:
 ELO: 22.27 +-9.7 (95%) LOS: 100.0%
Total: 1000 W: 134 L: 70 D: 796

**Comment by hero2017** [comment]
Thanks for that, but that was 2 years ago and perhaps something got messed up since. Is it possible for me to set up such a test on fishtest using my 256 threads, perhaps against ChessDBCN or noobpwnftw and 128 cores?

> 
> 
> first thing to try would be to quantify the effect, set up a match between your dual xeon and your dual epyc, and report the result of a match here.

Unfortunately I'm using the ram from the xeon inside the epyc so the xeon is currently unavailable until I get more ram. But yes that's definitely something to try then.

**Comment by hero2017** [comment]
> 
> 
> BTW https://tests.stockfishchess.org/tests/view/5b391fae0ebc5902b2e60162 is a thread testing 384 (hyper threads) against 192 threads, now almost 2 years ago. In that setting yielded:
> ELO: 22.27 +-9.7 (95%) LOS: 100.0%
> Total: 1000 W: 134 L: 70 D: 796

Thanks for that, although that was 2 years ago and perhaps something got messed up since. Is it possible for me to set up such a test on fishtest using my 256 threads, perhaps against ChessDBCN or noobpwnftw and 128 cores? I used to devote my Xeon in fishtest before once in a while for testing too although not specific tests like this.

**Comment by vondele** [comment]
on fishtest you don't play against a different machine, just on your own machine. While we could run on fishtest, it is easier if you just execute such a match locally (which is what fishtest would do anyway). 

Assuming you're on linux, you have cutechess and the noob_3moves.epd book (see https://github.com/official-stockfish/books for both) downloaded, you run:
```
./cutechess-cli -repeat -rounds 500 -games 2 -tournament round-robin -srand 1942127704 \
                -concurrency 1 -openings file=noob_3moves.epd format=epd order=random plies=16 \
                -resign movecount=3 score=400 -draw movenumber=34 movecount=16 score=20 \
                -engine name=sf.256 cmd=stockfish option.Threads=256 option.Hash=16000 tc=60+0.6 \
                -engine name=sf.128 cmd=stockfish option.Threads=128 option.Hash=16000 tc=60+0.6 \
                -each proto=uci -ratinginterval 1
```
or fewer games if you don't want to wait for 4 days. Obviously, you can also do that with threads/hash/tc set to a different value.

**Comment by hero2017** [comment]
Thanks vondele. I'll try that as soon as I get a chance.

**Comment by vondele** [comment]
Let us know what the result of the test is, and feel free to reopen the issue if it provides evidence for worse performance on 256 threads vs 128 threads.
