### ISSUE TITLE
SF dev version detected as a Virus

### ISSUE THREAD

**Issue by jean152** [official-stockfish/Stockfish#2655]
Hi,

My antivirus (Panda free edition) detects Stockfish development version as a virus.

I believe this is a false positive, but do you know why this happens ?

![sf_dev](https://user-images.githubusercontent.com/33521187/80707352-1bb44200-8aea-11ea-9da7-78e98dc7b108.png)

**Comment by MichaelB7** [comment]
https://www.pandasecurity.com/mediacenter/security/false-positives-what-are-they/

**Comment by vondele** [comment]
Most likely a false positive, for reasons mentioned above. You can always try to cross-check with other anti-virus products, or just compile from sources yourself.
