### ISSUE TITLE
Broken skill levels

### ISSUE THREAD

**Issue by locutus2** [official-stockfish/Stockfish#2669]
Something seems broken with the Skill Level option. My two tests at STC shows over 500 elo loss for skill level 18 and 19!

https://tests.stockfishchess.org/tests/view/5eb7d40ae0300e8e8c8961f7
https://tests.stockfishchess.org/tests/view/5eb7d425e0300e8e8c8961f9

**Comment by vondele** [comment]
answered also on fishcooking, pasting here: 

That's actually the right number.  To enable skill level we need to play MultiPV 4, which is a significant overhead, at STC, roughly 500 Elo. That's also why UCI_Elo is capped at 2850 Elo, that's roughly skill level 19. 

please close the issue if that resolves it.

**Comment by LouisZulli** [comment]
Please consider this an opportunity to remove all strength-weakening code/options from Stockfish. There are plenty of naturally weaker, open-source engines available. I'm sure the authors of those engines would be happy to see their engines being used.

**Comment by locutus2** [comment]
@vondele 
Yes, thats ok. i now trying to modify code to get less loss.
