### ISSUE TITLE
Dubious movegen when given a c960 position without UCI_Chess960 flag

### ISSUE THREAD

**Issue by fohristiwhirl** [official-stockfish/Stockfish#2671]
I drilled down into the top example from <http://talkchess.com/forum3/viewtopic.php?f=7&t=73901>

```
position fen nrkb2nr/ppppp1p1/6bp/5p2/BPP1P1P1/P7/3P1P1P/qRK1BQNR w BHbh - 0 3
go perft 1
d2d3: 1
f2f3: 1
h2h3: 1
b4b5: 1
c4c5: 1
e4e5: 1
g4g5: 1
d2d4: 1
f2f4: 1
h2h4: 1
e4f5: 1
g4f5: 1
g1e2: 1
g1f3: 1
g1h3: 1
a4d1: 1
a4c2: 1
a4b3: 1
a4b5: 1
a4c6: 1
a4d7: 1
b1a1: 1
c1c1: 1
c1c2: 1
f1e2: 1
f1g2: 1
f1d3: 1
f1h3: 1
c1d1: 1

Nodes searched: 29
```

What is `c1c1`?

**Comment by fohristiwhirl** [comment]
Ah, it's because I didn't set UCI_Chess960 to true. Hmm.

**Comment by fohristiwhirl** [comment]
Actually I'll reopen this until you decide whether you want to do anything about it, because the behaviour is so weird. It's like it does and doesn't know it's in a Chess960 game.

The exact reproduction steps are:

* Don't set UCI_Chess960 option
* Have king on C file
* Have castling rights to B file
* Have hostile queen on A file

**Comment by MichaelB7** [comment]
Chess960 castling rights do not mean anything in standard chess. It is incongruent.   There is no mix and match here intended here . It’s not a bug.

**Comment by fohristiwhirl** [comment]
> Chess960 castling rights do not mean anything in standard chess.

The way I see it, SF either believes it's playing standard chess, in which case c1c1 is illegal, or it believes it's playing Chess960, in which case O-O-O is illegal (in that exact position).

But if you want to say behaviour becomes undefined when a bad FEN is entered, that's fair enough.

**Comment by vondele** [comment]
prior to providing a Chess960 fen, one must set UCI_Chess960, otherwise, it is undefined behaviour on providing an illegal FEN. So, I assume the issue can be closed.

**Comment by fohristiwhirl** [comment]
OK.
