### ISSUE TITLE
abrok builds not automatically uploading from main branch here

### ISSUE THREAD

**Issue by ssj100** [official-stockfish/Stockfish#2672]
I've noticed recently (last few builds?) that abrok builds are not uploading very quickly.  Previously they were uploaded within about 5-15 minutes of each patch commit here.  Latest commit was performed 3-4 hours ago and it's still not uploaded on abrok.

Just wondering if something has changed?

**Comment by vondele** [comment]
maybe the machine is down for maintenance. Anyway, abrok is 'external' to the project, but the owner can be reached (see https://github.com/official-stockfish/Stockfish/issues/2345), maybe good to contact him if no uploads have happened next weekend.

**Comment by dorzechowski** [comment]
Abrok up and running again.

**Comment by vondele** [comment]
looks like it is working indeed.
