### ISSUE TITLE
Which set would be stronger, 7㎇ with large pages or 8㎇ without large pages?

### ISSUE THREAD

**Issue by Silver-Fang** [official-stockfish/Stockfish#2680]
On my 16㎇ memory Surface Book 2, if I set hash to more than 7㎇, the large pages won't be used. Should I sacrifice some hash size to obtain large pages support?

**Comment by MichaelB7** [comment]
For your machine 2048 would be fine. No need to set more. The large hash sizes really come into play when using very high thread count for most people.

**Comment by vondele** [comment]
It all depends on usage type (e.g. TC or threads etc.). It is also for discussion in fishcooking or elsewhere, not an issue.
