### ISSUE TITLE
Extreme amount of time losses...

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/Stockfish#2683]
See the (purged) test

https://tests.stockfishchess.org/tests/view/5ebd9e7275bec66815b8878c

Worth to have a look?

**Comment by noobpwnftw** [comment]
One cutechess cannot handle more than about 64 concurrent games anyway(provided that 255 thread worker is legit). A few other workers picked up the bailed task inherited the time loss.

**Comment by vondele** [comment]
Indeed, cutechess can't manage 255 concurrent games, unless TC (or threading) is very large. If one wants to add such a worker to fishtest, one needs to start e.g. multiple workers (each in their own directory), with reduced concurrency.

**Comment by hero2017** [comment]
So I plan to run 4 concurrent fishtests (at 64 threads each). They would be from the same machine so same ip. Do I need to do anything else? I've created a .netrc file in my windows profile folder so hopefully I won't hit the api limit if I ever decide to run my workers for more than 24 hrs.

**Comment by vondele** [comment]
I don't think so, worth testing. Let's keep en eye on the number of timeouts. If it is large we need to reduce cutechess concurrency further. 
So, I assume you're matching the fishtest yorkman ID ? We can increase the number of machines as well.
