### ISSUE TITLE
The base branch is not the same as stockfish master.

### ISSUE THREAD

**Issue by Vizvezdenec** [official-stockfish/Stockfish#2701]
But it's the same.
https://tests.stockfishchess.org/tests/view/5ecc2e8880f2c838b96557d5
Example.
Test goes normally, but it's kinda uncomfortable to see. Or maybe it should go to fishtest github?

**Comment by vondele** [comment]
probably fishtest issue.

**Comment by Vizvezdenec** [comment]
or github issue?
I see no difference for all patches also...
https://github.com/Vizvezdenec/Stockfish/compare/d40d04c...b80b2fe like this one

**Comment by vondele** [comment]
is now tracked here:
https://github.com/glinscott/fishtest/issues/688
looks like taking just 7 characters from the sha is too little, will be fixed with the next commit. I'll close this one
