### ISSUE TITLE
Stockfish 6 - Segmentation fault (core dumped) on position analysis

### ISSUE THREAD

**Issue by cameronjacobson** [official-stockfish/Stockfish#271]
I'm participating in a competition on kaggle.com 'FindingElo' [http://www.kaggle.com/c/finding-elo].  They recommended using your chess engine for position analysis.  Besides providing 50000 games for analysis they opened the competition to allow us to find games online.  I've analyzed a little over 28 million FEN positions using the convention below, so I think it's safe to say this is not coincidence that it will always segfault on this particular FEN string (at least in my tests).

I also received confirmation from Daylen Yang (Support staff) that he was able to replicate the issue.

I was originally thinking a core on one of my CPUs was going bad, but then I realized it was always only happening on this particular FEN.

```
> uci
> ucinewgame
> position fen 8/6qk/8/5KPp/1Q3p2/4P1P1/8/1p6 w - - 0 70
> go depth 14
```

**Comment by mcostalba** [comment]
This position is wrong: it has a black pawn on square B1 (see /1p6) and
this is not possible

**Comment by cameronjacobson** [comment]
I see.  I did find a FEN viewer online to review the position, and now it's apparent by looking at the layout of the board.

Thank you.

**Comment by cameronjacobson** [comment]
I don't know if this will make any difference, but figured I should add it to this thread.  I remembered the fen was generated by pgn-extract with "--fencomments" option.  It turns out the fen was representing the last move of the game.  Here's the excerpt from the relevant pgn:

`1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. d3 Be7 5. Bb3 O-O 6. Nbd2 d6 7. c3 Na5 8. Bc2 c5 9. O-O Nc6 10. Re1 Re8 11. Nf1 h6 12. Ng3 Bf8 13. h3 Qc7 14. Nh2 Be6 15. Qf3 Nh7 16. Nf5 Rad8 17. Ng4 d5 18. Ba4 Kh8 19. h4 dxe4 20. dxe4 f6 21. Nge3 Qf7 22. Qe2 g6 23. Ng3 h5 24. b3 Qc7 25. Bb2 Bh6 26. Rad1 Rxd1 27. Rxd1 Rd8 28. Ngf1 Rxd1 29. Qxd1 a6 30. Nd5 Qd8 31. c4 Nd4 32. b4 Bf8 33. bxc5 Bxc5 34. Nfe3 b5 35. cxb5 axb5 36. Bc2 Nxc2 37. Nxc2 Kg7 38. Qd3 Bxd5 39. exd5 Qb6 40. Ne3 Nf8 41. Bc1 f5 42. Nd1 Nd7 43. Qd2 Nf6 44. Bb2 Bd4 45. Kf1 Nxd5 46. g3 b4 47. Bxd4 Qxd4 48. Ke1 Qc4 49. Ne3 Nxe3 50. Qxe3 e4 51. Qb6 Qc3+ 52. Ke2 Qd3+ 53. Ke1 Qb1+ 54. Ke2 Qxa2+ 55. Ke3 Qb3+ 56. Kf4 Qf3+ 57. Ke5 Qc3+ 58. Kd5 b3 59. Qb7+ Kh6 60. Qb8 b2 61. Ke6 Kh7 62. Qb7+ Qg7 63. Qb5 Qg8+ 64. Kf6 Qf8+ 65. Ke6 Qg7 66. Qb4 g5 67. hxg5 e3 68. fxe3 f4 69. Kf5 b1 0-1`

Note that the move to 'b1' was the last move of the game.  Do you recommend I put a bug report in to the maintainers of pgn-extract?  I realize it's probably not a useful thing to analyze the last move of a game, except in cases where someone may forfeit and you want to know whether that decision really was a good one.  The match above was not a draw, so I imagine for some reason my dataset was not fully filtered (removing all end-of-game fen) before I started analysis.
