### ISSUE TITLE
memory mapping of TB files can lead to blue screens on Windows

### ISSUE THREAD

**Issue by chrkorn** [official-stockfish/Stockfish#2714]
I am using Aquarium to run multiple instances of Stockfish, all with access to 7 piece tablebase files on local SSDs. This frequently leads to blue screens that do not happen if I disable TB access. The issue seems to be the memory mapping, apparently Windows can either not cope with the number of mapped files, or runs out of virtual address space.

For reference, I use a 3990x with 32 GB of RAM and Stockfish is configured to use 32 MB of hash space per instance. The blue screen is reproducible with 30 instances of SF @ 4 cores each, as well as with 15 instances of SF @ 8 cores each. 8 instances @ 16 cores each seem to run reliably so far.

**Comment by LouisZulli** [comment]
This strikes me as a defect of the OS, not Stockfish.

**Comment by chrkorn** [comment]
> This strikes me as a defect of the OS, not Stockfish.

Yes, I can see the point. I don't mind if this does not get fixed, but I did want to report it to make it known.

**Comment by vondele** [comment]
Any suggestions for a fix/workaround ?

I somehow recall that with N-men table base, one should have RAM to cache (N-1)-men. Not sure where this rule of thumb came from.

**Comment by MichaelB7** [comment]
Blue Screens or BSOD are generally related to hardware issues or hardware driver issues.  There is usually a specific message associated with it that you can research.  They are also often associated with overclocking or inappropriate memory timings.  There is a built-in Windows tool called “Windows Memory Diagnostic”.  Search for the tool in your lower left search windows.  The tool will identify any possible hardware issues with your memory.  If you are using default memory timings  and  are not overclocking , and it fails that test, you may have to replace your memory.   It is highly unlikely Stockfish is causing this BSOD.

**Comment by MichaelB7** [comment]
I also just noticed you have a 3990x with 32 GB of ram .  Have you also enable Largepages ( memory lock). I would not be surprised if your BSOD goes away with more RAM just running at default or minimal OC settings.  Heat will also play a role in memory instability.  I recommend using a heat throttle setting of 79C with the threadripper. If you have have a end GPU , that will be adding to the heat.

**Comment by chrkorn** [comment]
Yes, I have large pages enabled. Heat shouldn't be an issue, the CPU stays consistently at just under 75C. The GPU ventilates directly to the rear, so heat from it does not reach RAM and CPU. It sits in a well ventilated case with 3 fans blowing in at the front, two exhausting at the rear, and the CPU's water cooler blows through the top.
But yes - 32 GB is not ideal (the machine was not built for chess and work requirements did not call for more...). I've now ordered a 128 GB set that is specifically approved to be compatible with the mainboard.

**Comment by MichaelB7** [comment]
That should be a good setup. I run a lot of testing - when testing , I cap my ram at 256 Mb per engine when using 60 threads ( 3970x).  No problems here with large pages. When “analyzing” I can always use 65536 Gb for hash ( 128 GB RAM ). To use 98304 RAM , I may have to reboot.  You have twice as many cores / threads - so your ymmv.

**Comment by chrkorn** [comment]
Good advice - thanks for the insight and your help!
