### ISSUE TITLE
Run tests with 2 threads instead of 1?  (Investigating 1. ... e6)

### ISSUE THREAD

**Issue by xoto10** [official-stockfish/Stockfish#2721]
I've been doing some local tests with openings 1. e4 and 1. d4 to look at the 1. ... e6 issue. One thing I've noticed is that the lines seem to be very deterministic on 1 thread, but the lines change with time control. So one tc might show a lot of e5 replies, another more c5. And the same for later moves, so at a given time control I only see a small range of lines.

If I run tests with 2 threads and half the time, I get much more variation in the lines chosen, so the exact tc chosen becomes less important.
E.g. For 100 games using a 2 line book with e4 and d4 at 60+0.6 on 1 thread I get 11 different lines to ply 7 (3 plies from each engine), but if I use 30+0.3 th 2 I get 43 different lines. That seems like quite a striking difference to me!

Perhaps we could make fishtest automatically use 2 threads for at least some of the workers on each test to get more variations in the lines played?

**Comment by Chess13234** [comment]
Its far more realistic to assume multi-core machines used to run stockfish in actual games, but due time savings fishtest optimizes stockfish for one core tests.

**Comment by xoto10** [comment]
Yes, but if fishtest did this with half time control automatically "behind the scenes" (or 55%, whatever) then the runtime would be about the same.

Another point is that currently fishtest adjusts the actual tc used, to account for faster / slower processors. Perhaps we would be better doing the opposite and deliberately varying the tc a little so that "10+0.1" tested a range of values from (say) 7+0.07 to 14+0.14?

**Comment by mstembera** [comment]
Fishtest uses 1 core tests by default only because multi threaded is a bit less efficient.  However given the new data you discovered through your detective work and that 2 core is only slightly less efficient I think it's a well worth trade off.  2 core would also exercise more SF code for better code coverage.

**Comment by Alayan-stk-2** [comment]
The scaling from 1 to 2 threads is excellent, over 95% efficiency iirc. So it's arguable if the efficiency loss would be worth the reduced determinism.

The current fishtest book is big enough that if the discussed cutechess adjustments were done we could ensure each game pair sees a different opening. We don't know how much transpositions are seen though.

**Comment by vondele** [comment]
@xoto10 if this is changed, we should run all tests threaded. Which means removing single core workers from fishtest... Resource-wise, that's very few cores, but there are number of contributors that just have single core contributions, and it seems a pity to force them away.

Also, with the opening book randomization and size, our current books are leading to sufficiently many games (i.e. the books provide opening positions for 300k games). Transpositions could happen, but it is a small fraction (unless if is a very forced line, the fact that the hash is in a different state for a transposition will lead to divergence quite easily).

Right now, my feeling rather is, if it works don't fix it....

**Comment by xoto10** [comment]
Fair enough. As suggested on the fishtest issue https://github.com/glinscott/fishtest/issues/699 I have requested tests to gather information.

**Comment by xoto10** [comment]
Regarding the single core workers, I was thinking that maybe we would schedule say 75% of jobs to workers with even core counts as 2 thread tests, and 25% as 1 thread. That way we would get a mix of 1- and 2-thread tests, and the proportion of single-core workers that happened to be used wouldn't shift that ratio too much.

Regarding opening books. Well, yes, I find it hard to believe 2 threads can add much when the opening book has 150k lines, but it would be nice to allow better results from smaller books. Anyway, we can leave it as a thought process for now. I'll close this issue in a couple of days or so, and we can continue the data gathering on the fishtest issue.

**Comment by xoto10** [comment]
To go back to the reason for this, I was looking at sf playing the French. Below is the list of lines played in one of my tests, 50 games @ 10+0.1 th 1. The forced opening book used has just 2 lines, 1. e4 and 1. d4.

The initial move is not shown but it's easy enough to infer, 1. e4 is followed by 1. ... e5, and d4 is followed by Nf6. So master and my test patch were both playing e5 in response to e4 at STC - _it looks like it's not playing 1. ... e6 at this tc_. If this is happening in similar positions in fishtest, then maybe we're almost never testing in French "e6" style positions unless the opening book forces it directly - perhaps this is one reason it's hard for patches aimed at this to pass?
```
(draw results are blank so that the wins stand out)

e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result "0-1"]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result "1-0"]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result "1-0"]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result "1-0"]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result "1-0"]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... e5   2.   Nf3  Nc6  3.   Bc4  Nf6  4.   d3   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result "1-0"]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result "1-0"]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result "1-0"]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result "1-0"]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]
e61d    vs   master  1... Nf6  2.   Nf3  d5   3.   e3   e6   4.   c4   [Result            ]

master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result "0-1"]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result "1-0"]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... e5   2.   Nf3  Nc6  3.   Bb5  Nf6  4.   O-O  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
master  vs   e61d    1... Nf6  2.   c4   e6   3.   Nc3  d5   4.   Nf3  [Result            ]
```
Testing at 20+0.2 sees similar play. Going the other way to shorter tc, 2+0.1 does see a lot of 1. ... e6 replies, but black tends to win these games! e.g.
```
e61d    vs   master  1... e6   2.   d4   d5   3.   Nc3  Bb4  4.   a3   [Result "0-1"]
e61d    vs   master  1... e6   2.   d4   d5   3.   Nc3  Bb4  4.   a3   [Result "0-1"]
e61d    vs   master  1... e6   2.   d4   d5   3.   Nc3  Bb4  4.   a3   [Result "0-1"]
...
```
master played 1. ... e6 25 times in 100 games (i.e. every time it faced 1. e4), and result was +22-0=3. So even if fishtest does see 1. ... e6 style openings, perhaps master is winning by playing this :(
(My e61d patch successfully avoided e6, playing e5 instead, but got +2-5=18, so obv worse results than master, even though it's doing the move I want to encourage. Hard to improve on that +22 by master!)

Perhaps this gives us some other ideas on how we can alter/improve fishtest to help improve sf's play in the French? It seems to me that to have patches aimed at weakness in the French pass fishtest, we need some combination of, 1) making fishtest play e6 more often, 2) teaching sf how to win as white when black does play e6.

My suggestion is to use multiple threads or perhaps some explicit randomisation (temperature), together with a shorter / more mixed opening book, but perhaps there are other ways?

**Comment by vondele** [comment]
I think there is a big leap of faith in going from 'multiple threads or explicit randomisation' to 'plays better french'. To prove this we could proceed as follows 

* Demonstrate that a given patch makes SF play french better (not easy), i.e. develop and show this with reasonable local testing (could be small book with threads, or TC randomization)
* Show this patch doesn't work on fishtest
* Experiment with that patch specifically with e.g. threading or randomization attempts.

**Comment by NKONSTANTAKIS** [comment]
From this data I get the impression that we are suffering from determinism.
Specific TC and 1-core do not offer enough variance.
The openings obviously help a lot, but it would be nice if the engine increased the variance on its own.

Some ideas:

1. To randomize a bit the TC. 
Instead of fixed 10+0.1 to allocate an equal homogenous range of TC's, ie (8+0.08, 12+0.12 etc), centered at 10+0.1.

2. To mix up the threads testing.
As 1-core has the maximum efficiency, it can be the bulk, but why to put all eggs in one basket?
Blending some multithreaded testing into the normal STC signal would enrich it with more dimensions. ie 60% 1-core 30% 2-threads 10% 4-threads

3. To randomize first 2-3 moves out of the book via multi-PV.
Enabling multi-PV for just 2-3 moves and adding some randomization to top 3-5 moves with an eval margin guard, would be very cheap resource wise and offer a much wider opening coverage.

Pondering on the situation, I think its critical, due to the big amount of transpositions in chess.
Positions that are liked by SF's eval function, will be aimed for across a multitude of paths.
This way the optimization is unevenly spread and affected by overrepresentation of tendencies & overfitting.

**Comment by vondele** [comment]
Note that we're not really suffering from determinism in the current setup, i.e. the current opening books are sufficiently big to run ~300k games, in principle, without repetition.

**Comment by NKONSTANTAKIS** [comment]
I agree that the testing of the last months looks very healthy, but looking for more improvements. Btw lets also try our noob_4moves as well? More positions and +2 elo elo spread as far as I remember. I wouldn't worry at all for not optimizing opening due to deeper book, as the early choices depend upon correct evaluation of much deeper positions.

**Comment by xoto10** [comment]
Well, I will see what I can do.

I (and other devs) have tried many test patches to improve sf's play in the French, I'm just trying to look at the problem from different angles - maybe there is something about our test setup that is making it hard / preventing us from finding an improvement? 
I probably shouldn't have mentioned my threads / randomisation thoughts in my last comment, my aim in altering the title and asking "perhaps there is another way?" was to open the conversation up to any other thoughts for a day or two before I close this.
