### ISSUE TITLE
Enable -flto for mingw

### ISSUE THREAD

**Issue by Morilli** [official-stockfish/Stockfish#2731]
I noticed that the makefile contains this suspicious line: ``Link Time Optimization, it works since gcc 4.5 but not on mingw under Windows.``. As I have compiled numerous software with link-time optimization enabled, I can assure it does work on mingw. I have found this previous issue #392, which is almost 5 years old by now and must be outdated. I'd like for someone to confirm that -flto does work on windows with mingw so it can be enabled in the makefile.

**Comment by vondele** [comment]
This should really work, and I think the comment is an old left-over. 
It is also what we advertise here:
https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows#build-stockfish
Just verify this works, for you, and let us know. We'll fix-up the comment later.

**Comment by Morilli** [comment]
I have definitely tested it and it does work. I can launch the executable just fine and it's a little smaller than without -flto.

**Comment by vondele** [comment]
OK, I've removed the comment as part of https://github.com/official-stockfish/Stockfish/pull/2695
Thanks for reporting.

**Comment by Morilli** [comment]
Shouldn't the actual code be adjusted as well? Because currently when using ``COMP=mingw`` -flto will not be set.

**Comment by vondele** [comment]
Ah sorry, I understood that the code worked as if. Can you show the changes you made to the Makefile?  (`git diff`)

**Comment by Morilli** [comment]
Had actually just hacked that in before, but I think this should work: 
[mingw_diff.txt](https://github.com/official-stockfish/Stockfish/files/4767511/mingw_diff.txt)

**Comment by abdulbadii** [comment]
Wait, Watch !
it works only for non profile
it will break as PGO processes by `bench` CLI parameter

**Comment by Morilli** [comment]
Uhm I cannot tell why it doesn't work for you, both build and profile-build work with ``-flto`` for me.

**Comment by abdulbadii** [comment]
running abruptly breaks, only build succeeds

**Comment by unaiic** [comment]
@Morilli Does it work now as it is in #2763?

**Comment by abdulbadii** [comment]
open it
