### ISSUE TITLE
Permanent book integration

### ISSUE THREAD

**Issue by adentong** [official-stockfish/Stockfish#2732]
Crossposting @protonspring's thread on fishcooking here https://groups.google.com/g/fishcooking/c/iKYBcbgHfG8

**Comment by vondele** [comment]
I don't think this is a good idea... better improve the engine in other ways.

**Comment by protonspring** [comment]
Just a quick question. . is it just as bad to have a short book of moves to NOT make?  Just enough to keep sf out of bad play lines.

In practice, if a "bad" move is in our book, make the second best move.

**Comment by vondele** [comment]
I think so, it is hiding the root cause of the poor choice, i.e. an eval problem for positions deeper in the tree. I'm not saying some book approach (like bookfish or brainfish, or ...) has no merit, but I think the core project should tackle it with eval patches.

**Comment by protonspring** [comment]
Great thx.

**Comment by mstembera** [comment]
@protonspring In case u find it interesting here is my experiment to avoid the French(as black) using only eval terms.
https://tests.stockfishchess.org/tests/view/5cd770f90ebc5925cf051fda

**Comment by protonspring** [comment]
Nice. That's what i was thinking about. Thx.

**Comment by Chess13234** [comment]
Lets instead examine *why* Stockfish wants to play French, perhaps it thinks pawn chains at the opening are important(e6 is well-defended) and outweigh most tactical drawbacks?
Perhaps its some king safety issue where e6 is sub-optimal but gives a "safer king position" score(meaningless in openings)?
