### ISSUE TITLE
Change Board size

### ISSUE THREAD

**Issue by Mudasar-Makandar** [official-stockfish/Stockfish#2754]
Can someone help me?
I want to change the size of Chess Board and change few rules.
Where to change these?

**Comment by ianfab** [comment]
If you want to implement a chess variant with modified rules in Stockfish, you might want to try out my fork [Fairy-Stockfish](https://github.com/ianfab/Fairy-Stockfish), which supports to configure rules like board size at runtime via a [variant configuration file](https://github.com/ianfab/Fairy-Stockfish/blob/master/src/variants.ini), so you might not even need code changes if your desired rule changes are already supported (or maybe it even already is among the ~100 built-in variants).

Can you give more details about the rules you want to implement?

**Comment by vondele** [comment]
@Mudasar-Makandar yes please see the nice work by @ianfab for variants. I'll close the issue here.

**Comment by Mudasar-Makandar** [comment]
Thank you @ianfab
