### ISSUE TITLE
bestmove without info string

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2757]
```
position fen 1q2B2q/2q1B1q1/3qkq2/qrr1rRRQ/3QKQ2/2Q3Q1/1Q2n2Q/Q3n3 w - - 10
go nodes 1000
```
yields a bestmove without info string. The UCI protocol requires an info string before a bestmove.

**Comment by vondele** [comment]
note this is not just `go nodes` also time:

```
position fen 1q2B2q/2q1B1q1/3qkq2/qrr1rRRQ/3QKQ2/2Q3Q1/1Q2n2Q/Q3n3 w - - 10
go wtime 1 winc 1 btime 1 binc 1
```
this is presumably related to the check in `UCI::pv()` 

This would fix it for me, but would need a second pair of eyes:
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 031d8fc84..51d8dcf82 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1816,12 +1816,15 @@ string UCI::pv(const Position& pos, Depth depth, Value alpha, Value beta) {
   {
       bool updated = rootMoves[i].score != -VALUE_INFINITE;
 
-      if (depth == 1 && !updated)
+      if (depth == 1 && !updated && i > 0)
           continue;
 
-      Depth d = updated ? depth : depth - 1;
+      Depth d = updated ? depth : std::max(1, depth - 1);
       Value v = updated ? rootMoves[i].score : rootMoves[i].previousScore;
 
+      if (v == -VALUE_INFINITE)
+          v = VALUE_ZERO;
+
       bool tb = TB::RootInTB && abs(v) < VALUE_MATE_IN_MAX_PLY;
       v = tb ? rootMoves[i].tbScore : v;
 
```

**Comment by unaiic** [comment]
@vondele It also works for me, although I've seen that the `if (v == -VALUE_INFINITE) v = VALUE_ZERO;` is unnecessary and could be simplified. I have tried it with both nodes and time, and it works as expected.

**Comment by joergoster** [comment]
I don't think there is anything to fix here.

> The UCI protocol requires an info string before a bestmove.

This is wrong. The protocol recommends to send an info string of the last search/iteration. But since the 1st iteration did not even complete, we have nothing to send! Note that this is a very special case, and sending `bestmove` only for this case looks perfectly fine to me.

**Comment by unaiic** [comment]
There is nothing wrong however if we always have something to send. I think there is no reason not to update that.

**Comment by vondele** [comment]
@joergoster 

```
* bestmove  [ ponder  ]
	[...]
	Directly before that the engine should send a final "info" command with the final search information,
```

**Comment by vondele** [comment]
@unaiic without that statement 'mate 0' is printed which is not so nice.

**Comment by unaiic** [comment]
Oh. So I think it's okay as you first said.

**Comment by joergoster** [comment]
So because we have no valid score to output, we are now making something up? Ridiculous!

**Comment by vondele** [comment]
@joergoster what would you suggest to output, given that we're required to give an info line (like we're required to give a bestmove, even if we don't know what it is).

**Comment by joergoster** [comment]
@vondele Just leave it as is. If we couldn't even finish the very first iteration it makes no sense to output anything, imho.

**Comment by vondele** [comment]
unfortunately, that is not a good option IMO, even if it makes sense. The protocol expects an output, and otherwise robust tools like python chess will report an error on it.

**Comment by joergoster** [comment]
Then it seems a much better solution to only start obeying any search limits after finishing the first iteration ...

**Comment by niklasf** [comment]
python-chess doesn't make this assumption. The warning is for the unexpected empty line that is printed before `bestmove`.

Independently of that, from a user perspective it would be very useful if Stockfish reliably produced some evaluation (however bad) no matter what.

Both the patch or always finishing at least one iteration seem reasonable to me.

**Comment by MichaelB7** [comment]
I would not categorize python as “robust”, I would categorize it is “intrusive”.  It is asking for something that is not available. 
info information not available - would be appropriate output.

**Comment by vondele** [comment]
@joergoster I wanted to test this patch:
```diff
diff --git a/src/search.cpp b/src/search.cpp
index 1e2980cb0..22d029a01 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -1793,6 +1793,10 @@ void MainThread::check_time() {
   if (ponder)
       return;
 
+  // Always finish at least 1 iteration.
+  if (rootDepth < 2)
+      return;
+
   if (   (Limits.use_time_management() && (elapsed > Time.maximum() - 10 || stopOnPonderhit))
       || (Limits.movetime && elapsed >= Limits.movetime)
       || (Limits.nodes && Threads.nodes_searched() >= (uint64_t)Limits.nodes))
@@ -1817,9 +1821,6 @@ string UCI::pv(const Position& pos, Depth depth, Value alpha, Value beta) {
   {
       bool updated = rootMoves[i].score != -VALUE_INFINITE;
 
-      if (depth == 1 && !updated)
-          continue;
-
       Depth d = updated ? depth : depth - 1;
       Value v = updated ? rootMoves[i].score : rootMoves[i].previousScore;
 
```
however, that doesn't work when the user sends a stop command. It is not easy to deal with that case, i.e. an immediate stop command before the search has completed 1 iteration, still provides no info line:
```bash
$ cat t
position fen 1q2B2q/2q1B1q1/3qkq2/qrr1rRRQ/3QKQ2/2Q3Q1/1Q2n2Q/Q3n3 w - - 10
go nodes 100000
stop
$ cat t | ./stockfish
Stockfish 240620 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
bestmove f4e5
```

**Comment by niklasf** [comment]
Seems fair, although perhaps not following the spec to the letter. At least the GUI could now make a deliberate decision not to send `stop` before getting at least one info, if it needs that.

**Comment by joergoster** [comment]
@vondele I need to think about this, especially about MultiPV mode.

**Comment by joergoster** [comment]
@vondele With your proposed change (combined with ponder check), I get two iterations. Depth 1 should be sufficient, no?
```
  // We should not stop pondering until told so by the GUI.
  // Also, finish at least one iteration to have some valid search info.
  if (ponder || rootDepth < 2)
      return;
```

```
position fen 1q2B2q/2q1B1q1/3qkq2/qrr1rRRQ/3QKQ2/2Q3Q1/1Q2n2Q/Q3n3 w - - 10
go nodes 1000
```

Output:

> info depth 1 seldepth 6 multipv 1 score mate 10 nodes 2812 nps 937333 tbhits 0 time 3 pv f4e5 c5e5 f5e5 b5e5 g5e5 d6e5 h5e5 c7e5 d4e5 b8e5 c3e5 a5e5 b2e5 f6e5 g3e5 g7e5 h2e5 h8e5 a1e5
> info depth 2 seldepth 6 multipv 1 score mate 10 nodes 2813 nps 937666 tbhits 0 time 3 pv f4e5 c5e5 f5e5 b5e5 g5e5 d6e5 h5e5 c7e5 d4e5 b8e5 c3e5 a5e5 b2e5 f6e5 g3e5 g7e5 h2e5 h8e5 a1e5
> bestmove f4e5 ponder c5e5

The reason for this is most probably, that we do not check for limits nodes or movetime when we finished an iteration. We do this for limits mate and depth, however!

Another question is what to do in MultiPV mode. Only stop after finishing a complete iteration, or already stop after the 1st PV line?

**Comment by vondele** [comment]
I think the variant https://github.com/official-stockfish/Stockfish/issues/2757#issuecomment-648263667 is most robust here, no need to change search, just provide the UCI what it wants, even if the eval means nothing.
