### ISSUE TITLE
prio -1 pending tests

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2771]
can we (ideally submitter) just delete those as soon as the base branch is outdated... it is annoying to have to scroll 28 tests to approve pending new tests. 

The standard procedure is to have a submitted test just run to completion. If a user has too many tests running, the throughput is the best variable to adjust resource usage. If the test has become meaningless (e.g. conflicting patch on master, bug, etc..) stop is the right action.

**Comment by Lolligerhans** [comment]
Hey, I did not realize there would be an issue for approvers, I used it to prolong decisions on tests when I believe that another version of an idea may increase on a particular try (very convenient for the submitter). I removed some of my pending tests to clear that section.

Maybe this is an issue for fishtest (?); sorting unapproved tests to the top of the list may help. The expansion of pending tests shows unapproved ones w/o scrolling.

**Comment by vondele** [comment]
closing as the queues get empty
