### ISSUE TITLE
Simplification bounds upgrade

### ISSUE THREAD

**Issue by NKONSTANTAKIS** [official-stockfish/Stockfish#2783]
Assessment of last 6-months, show that the scaling is becoming better and better.
I contribute most of all for this the nice bounds combo of easier STC, harder and more confident LTC, for promoting scaling.
Scaling is hard to measure, but its by far the most important metric of all. So taking it into account indirectly with such an inexpensive trick is pure gold: you don't need to care if STC flukes or LTC flukes, as the net will catch more good scalers "by design".

Some points for current simplification bounds:
-0.5 elo has 25% to pass, while old [-3,1] had 20%
SF is hundreds of elo stronger + more optimized, making certain that current selection bias is less favorable than then.

Pass rates for simplification attempts confirm the selection bias hypothesis, being low. If average simplification was -0.25 elo, 50% of simplification attempts would make it.

My recommendation is to introduce this successful scaling bounds trick to simplifications as well. Not just as a protection vs regression, but also for getting more good-scaling regressions when we get unluckily fluked.

This will also reduce both the need and the motivation for using of VLTC as means of protection.

The change could be just a simple +0.25 to LTC {-1.25 , 0,75}, bringing the -0.5 elo analogy back to ~20%, or to copy the successful elo gaining scheme, increasing LTC confidence as well to width 1.5 ie {-1 , 0.5}.

Current bounds seem risky, and possibly not worth attempting light code removal.

On the plus side, general progress is robust, indicating that elo-gainers absorb any setbacks, as they also outnumber them.

**Comment by vondele** [comment]
Current bounds are time proven, and various tests have shown that no regressions have been introduced by this testing procedure. Do you have data to the contrary? If not, I would close the issue.

**Comment by NKONSTANTAKIS** [comment]
No tests can measure this, because a massive reverse of simplifications affects the performance of in-between elo gainers. Lets take it easy and step by step, what of the things I write you consider inaccurate?

 If the pass analogy is 50% we lose 0.25 on average, agreed?

The pass rate data since january is there, easily accessible I guess.

Feel free to close it anytime, you are the maintainer. If you don't find my contribution useful or my ways appropriate, it will save me a lot of effort.

**Comment by NKONSTANTAKIS** [comment]
i value harmony more than truth, I am not going to fight for it because the clash is painful. You are negative to my proposition, that's ok, SF is going well anyway. You are doing a good job. Dunno why you are so annoyed by me, but I can feel it.

**Comment by NKONSTANTAKIS** [comment]
Closing this by all means excellent suggestion in order to preserve group uniformity, which is probably more valuable and definitely more enjoyable. A pity...

**Comment by NKONSTANTAKIS** [comment]
Tbh regressions that happened at january with {0,2}, will naturally happen much more frequently with {-1.5, 0.5}. Same confidence & -1.5 midpoint elo. Reasoning aside, I got no proof they hurt, but wouldn't we enjoy some more confidence for LTC simplifications, soas be on the safe side? Those weird results around bad outpost patch at least indicate that noise must be high, maybe our high resolution is jittery (oversensitive). I will open an issue to discuss about noise.

**Comment by vondele** [comment]
As pointed out, the outpost patch doesn't seem to be simplified away with our standard STC+LTC testing, in line with the expectation after having passed STC+LTC (multiple times in variants). So the procedure works?  The surprise might be that it passed a single STC simplification test as well, but the odds of doing that are not small, somewhere between 20 and 1% if we estimate the true Elo of the patch to be between 1 - 2 Elo.

Keeping our threshold for passing simplification at -0.5Elo (as I want), but reducing the odds of a passing a single SPRT test for something expected to gain 1 Elo (our Elo gainers) increases resources significantly. For example reducing the passing rate from 20% to 1% (for a single STC simplification test) requires to reduce the interval to [-0.85, -0.15], and can be expected to increase resources needed by roughly 8 times.

**Comment by NKONSTANTAKIS** [comment]
I understand, its like you don't mind much small regressions due to the combined benefit of code removal and resource economy. But what would be the increase of resources for say {-1.25, 0.25} just at LTC? Its going to rise a lot due to most samples lying at the middle? Maybe not a profitable investment + a nice side effect of current bounds is that they deter overuse of simplification attempts. I am ok with all this.

Now, what if we kept the same pass-rate of 25% for STC+LTC for -0.5 elo midpoint + same confidence, but just introduced the scaling concept, making STC a bit easier and LTC a bit harder? I regard this scaling promotion very healthy long-term.

**Comment by vondele** [comment]
{-1.25, 0.25} at LTC would probably be around 80% more resources.

A hybrid scheme like {-2.0, 0.0} and {-1.25, 0.75} would roughly keep confidence and 25% passing at -.5 but the benefits seem somewhat limited (I would have the plot the probabilities to see the difference).

**Comment by NKONSTANTAKIS** [comment]
Some statistics for different elo (draw ratio 0.61, RMS bias 0):

ELO    STC {-2,0}      LTC {-1.25 , 0.75}    Flat Hybrid          {-1.5 , 0.5}     Flat X2
-0.8      64.3%                16.5%                  10.6%                  29.2%        8.52%
-0.6      76.5%                26.3%                  20.1%                  42.7%        18.2%
-0.5      81.3%                32.4%                  26.3%                  50%           25%
-0.4      85.4%                39.1%                  33.4.%                 57.3%        32.8%
-0.3      88.7%                46.3%                  41%                     64.3%        41.3%

And now for scaling slopes:

ELO STC/LTC (slope)                      Hybrid                    X2
-0.8/-0.3 (very positive)                  29.8%                   18.8%
-0.6/-0.4 (positive)                          29.9%                   24.5%
-0.5/-0.5 (flat)                                 26.3%                    25%
-0.4/-0.6 (negative)                         22.5%                   24.5%
-0.3/-0.8 (very negative)                 14.6%                   18.8%

Its not a huge benefit, as you said, but also at a small price, so I think its worth it.

I take into consideration that simplifications are usually speedups, which thrive at STC, meaning that the slope will be more negative than average. On the other hand, if a simplification happens to scale well, it will be a pity to filter it at STC, not giving it an opportunity to perform at LTC.

However, another train of thought, is that due to simplifications scaling negative on average, by keeping equal bounds we indirectly promote scaling, as those were introduced via the new elo-gaining scaling promotion system. Unless they target code introduced before 2020, that is. But even that helps long term by making space for new concepts via the scaling system.

I would prefer a midpoint at -0.4 or -0.3, but can't argue against your wish to keep it at -0.5, thanks for clarifying that, it eases my considerations.

So that's all from me, hybrid might be marginally worth it, but I'm fine anyway. Cheers.

PS. Proper drawrate and RMS bias might alter impressions at the table?

**Comment by vondele** [comment]
drawrate and RMS bias do not influence pass probabilities, only the expected number of games needed to prove the result.

**Comment by vondele** [comment]
I'll close this, needs re-evaluation after NNUE merge
