### ISSUE TITLE
WDL Statistics not parsed by GUI

### ISSUE THREAD

**Issue by CalKK8** [official-stockfish/Stockfish#2787]
Today, I downloaded the [latest SF release](https://abrok.eu/stockfish/builds/110068808b51344ac59f8c6a0846f5dfdf670392/linux64bmi2/stockfish_20070107_x64_bmi2), but in the console it kept outputting errors.

Below are a few of the error messages.

```
2020-07-01 21:04:10,816: exception parsing score cp value from info: 'depth 1 seldepth 1 multipv 1 score cp 110 wdl 355 620 25 nodes 133 nps 133000 tbhits 0 time 1 pv e2e3'
Traceback (most recent call last):
  File "/home/calkk8/.local/lib/python3.6/site-packages/chess/uci.py", line 543, in _info
    score_cp = int(token)
ValueError: invalid literal for int() with base 10: 'wdl'
2020-07-01 21:04:10,818: exception parsing score cp value from info: 'depth 2 seldepth 2 multipv 1 score cp 122 wdl 392 587 21 nodes 478 nps 478000 tbhits 0 time 1 pv e2e3 b7b6'
Traceback (most recent call last):
  File "/home/calkk8/.local/lib/python3.6/site-packages/chess/uci.py", line 543, in _info
    score_cp = int(token)
ValueError: invalid literal for int() with base 10: 'wdl'
2020-07-01 21:04:10,818: exception parsing score cp value from info: 'depth 3 seldepth 3 multipv 1 score cp 116 wdl 375 602 23 nodes 845 nps 845000 tbhits 0 time 1 pv e2e3 b7b6 g1e2'
Traceback (most recent call last):
  File "/home/calkk8/.local/lib/python3.6/site-packages/chess/uci.py", line 543, in _info
    score_cp = int(token)
ValueError: invalid literal for int() with base 10: 'wdl'
2020-07-01 21:04:10,819: exception parsing score cp value from info: 'depth 4 seldepth 4 multipv 1 score cp 60 wdl 214 737 49 nodes 4916 nps 2458000 tbhits 0 time 2 pv d2d4 e7e6 e2e3 d7d5'
Traceback (most recent call last):
  File "/home/calkk8/.local/lib/python3.6/site-packages/chess/uci.py", line 543, in _info
    score_cp = int(token)
ValueError: invalid literal for int() with base 10: 'wdl'
2020-07-01 21:04:10,819: exception parsing score cp value from info: 'depth 5 seldepth 5 multipv 1 score cp 94 wdl 304 665 31 nodes 5805 nps 2902500 tbhits 0 time 2 pv d2d4 e7e6 e2e3'
```
I can only hope that this is fixed...

**Comment by LouisZulli** [comment]
You seem to be using a Python-based GUI that is now choking on Stockfish's info strings. 

wdl is not mentioned in the UCI protocols, so one wonders if Stockfish should be sending this at all. Clearly, some GUI's will need to be updated.

**Comment by Rocky640** [comment]
you can change uci custom option for the engine
UCI_ShowWDL to false

**Comment by LouisZulli** [comment]
Perhaps UCI_ShowWDL should be false by default?

**Comment by Vizvezdenec** [comment]
I also have quite some people that say that engine refuses to start in some GUIs because of this.
I think we should have this turned off by default to not confuse people and let more experienced users to decide themselves if they want to use it or not.

**Comment by vondele** [comment]
in principle the UCI protocol states:
```
* if the engine or the GUI receives an unknown command or token it should just ignore it and try to
  parse the rest of the string.
```
so strictly those are GUI bugs, and should IMO also be filed with the GUI authors/vendors. It would be nice to know which GUIs / tools are affected.

However, these issues are to be expected, so that's why the option is there. Having it true or false by default was one of the questions I had, and I opted for true to start with, even though eventually I could change my opinion, certainly if these problems would remain significant closer to the release date of SF 12. I would at least keep the current state for a couple of weeks.

The reasoning for 'true' is that this is nice output to have. The wdl numbers are instructive on actual winning chances, and also have the nice property that the win rate is now decreasing with every move in fortress situations. GUI authors have an interest in supporting Stockfish, I'm rather sure they will quickly update their projects if affected by this issue.

**Comment by Vizvezdenec** [comment]
The problem is that not all GUIs have really active development + a lot of people use older versions of GUIs because of some features that disappeared in later releases so even if GUI "fixes" it this wouldn't affect them. So people who use this GUIs will have problems for like forever.
I honestly think that we should stick to what works for everyone by default and let smth that provides better stats as an option for people who actually can use it.

**Comment by MikeKagansky** [comment]
The only solid way here:
UCI_ShowWDL [ default: false ]

**Comment by Marat-Ka** [comment]
If I do not have the required option in the Fritz 15 shell, is it turned on, turned off, or is it not being processed at all?

**Comment by Rocky640** [comment]
by default it is turned on.

you should see it listed in the engine parameters 
![image](https://user-images.githubusercontent.com/8949638/86380609-48a3e300-bc5a-11ea-974d-940d080f99d9.png)

if fritz does not recognize  some info string, it will not show it.

**Comment by Marat-Ka** [comment]
What next?

[url=https://imageup.ru/img265/3626460/dgf.jpg.html][img]https://imageup.ru/img265/3626460/dgf.jpg[/img][/url]

**Comment by joergoster** [comment]
@Rocky640 No! Unknown options with `UCI_` prefix are not being displayed by the GUI by design.

> If the GUI gets an unknown Option with the prefix "UCI_", it should just
> 		ignore it and not display it in the engine's options dialog.

**Comment by Rocky640** [comment]
@joergoster  is right. 

we have five UCI_ parameters, and they will not how in fritz gui
![image](https://user-images.githubusercontent.com/8949638/86383869-4478c500-bc5c-11ea-9e08-a5cdcea731ce.png)


![image](https://user-images.githubusercontent.com/8949638/86384216-6c682880-bc5c-11ea-92a5-299e8b458613.png)

However 2 of them show in Arena GUI
![image](https://user-images.githubusercontent.com/8949638/86384506-d385dd00-bc5c-11ea-8d90-26f15545a626.png)

**Comment by vondele** [comment]
OK, I wasn't aware of the fact that the UCI_ShowWDL option would not be shown. If the user can't switch it off, and it breaks by default (even if the GUIs are buggy), it is better to have the option set to false. It is a pity, but well..

**Comment by joergoster** [comment]
UCI_Chess960 and the other options are handled in other place/s in the Fritz GUI. This is probably also the case in other GUIs. But I don't know for sure.

It is possible that Fritz can already deal with this option, as LC0 and FatFritz also may report WDL data. Somebody else more knowledgeable with the Fritz GUI needs to check.

**Comment by Marat-Ka** [comment]
> OK, I wasn't aware of the fact that the UCI_ShowWDL option would not be shown. If the user can't switch it off, and it breaks by default (even if the GUIs are buggy), it is better to have the option set to false. It is a pity, but well..

Thx.

**Comment by Marat-Ka** [comment]
> 
> 
> UCI_Chess960 and the other options are handled in other place/s in the Fritz GUI. This is probably also the case in other GUIs. But I don't know for sure.
> 
> It is possible that Fritz can already deal with this option, as LC0 and FatFritz also may report WDL data. Somebody else more knowledgeable with the Fritz GUI needs to check.

FatFritz IMHO is more an engine than a shell, and the shell there is the usual Fritz 17.

**Comment by joergoster** [comment]
@Marat-Ka Right-click in the engine window, untick show winning probabilities (or similar)

**Comment by CalKK8** [comment]
I use Stockfish while playing as a Bot on [lichess.org](https://lichess.org/). I this [GitHub repository](https://github.com/ShailChoksi/lichess-bot).

**Comment by vondele** [comment]
@CalKK8 the lichess bot seems to require a specific version of python chess https://github.com/ShailChoksi/lichess-bot/blob/master/requirements.txt you could try to upgrade it to a later version and see if it works. However, I'll probably merge the PR that will fix this issue in the coming days.

**Comment by CalKK8** [comment]
@vondele Thank you.
