### ISSUE TITLE
Unable to compile Stockfish on MSVC

### ISSUE THREAD

**Issue by Nazine** [official-stockfish/Stockfish#279]
I get the following error;

tbcore.cpp(67): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead.
To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string.h(112) : see declaration of 'strcpy'

Any fix?

**Comment by mcostalba** [comment]
It's not an error, it'a a warning. Compile ends and is not blocked by this.

The fix is to rewrite TB code in a proper way....

**Comment by mcostalba** [comment]
Close now, because is not a compile error.

**Comment by rapgro** [comment]
https://github.com/official-stockfish/Stockfish/issues/272
