### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by se7enty6** [official-stockfish/Stockfish#2802]
When is the next stable release of Stockfish(12) expected?

**Comment by vondele** [comment]
Traditionally, when SFdev is about 50 Elo stronger than SF11. That's probably about 6 months away.

**Comment by se7enty6** [comment]
Will there be any performance gain if I change the value of 'Skill level'
from 20 to 100 in Stockfish settings?

**Comment by mstembera** [comment]
@se7enty6 These questions are not dev issues and so don't belong here.  Please post them to fishcooking.
