### ISSUE TITLE
Fails to start on Linux with large hash size

### ISSUE THREAD

**Issue by kamyarkaviani** [official-stockfish/Stockfish#2809]
Ever since this commit https://github.com/official-stockfish/Stockfish/commit/39437f4e55aaa26ef9f0d5a1c762e560e9ffde32, if I specify the hash size to be larger than 256 MB, the engine doesn't load. I get some single threaded activity, but no PV output or anything else. It just runs without outputting anything. 

I'm on Ubuntu 20.04 with Linux kernel 5.4.0-40-generic, and using ChessX as my GUI.

**Comment by vondele** [comment]
same ubuntu and kernel here, things work, maybe some GUI issue? 

Can you try from the command line / terminal to start stockfish and run type the commands:
```
setoption name Hash value 512
go depth 50
```

**Comment by kamyarkaviani** [comment]
Hmm. From the command line it works fine. This must be a bug with ChessX. Will file a bug with them. Closing this one. Thanks.
