### ISSUE TITLE
Are we having high noise?

### ISSUE THREAD

**Issue by NKONSTANTAKIS** [official-stockfish/Stockfish#2810]
Taking incentive from the unexpected results around the bad outpost patch, I think its very likely.

Factors that possibly contribute to this are: 
1. C24 vs C24 risky playstyle, outcome can go both ways. Rolling the dice at a specific move, as @vdbergh would say.
2. Tendency of SF to opt for specific variations & setups (eg french). Book helps here, but there are also transpositions. 
3. The random distribution of the book. Stuff that improve on some openings could hurt on others. So luck of the draw.

For 1. we could maybe lower it, its debatable that lowering drawrate will hurt selection. Vdbergh firmly believes it will boost it.
For 2. we could force deeper (variable length?) book, with the intention of allowing optimization at a wider spectrum of positions via disallowing transpositions to specific setups that the eval loves. Also reduce overfitting.
For 3. Would there be an option to use sequential book, for equal and unique representation? But how to use it with sprt, this is more suitable for fixed games. Unless we arrange the sequence with a balanced and smart hierarchy, then it could be even beneficial for sprt.

This is not intended as pointing out a problem that needs to be fixed (progress is very nice after all, and some noise might be a reasonable price for increased resolution), but for brainstorming, exchanging opinions, analysing the possibilities for future improvements, etc, and also helping with the decision about default contempt.

**Comment by adentong** [comment]
Why do you think the outpost patch is bad? It's resisting ltc simplification so it was not a fluke.

**Comment by NKONSTANTAKIS** [comment]
If passing 3xltc at 20k games was a fluke we could pack and go home :p 

My point is that this patch had the highest recent confidence of being good and yet not resisting as easy as one would expect. 

Ltc simplification has lower confidence than ltc elo gain, let alone passing thrice, so why are you not basing your confidence of not being a fluke at the ltc performance and you base it on resisting simplification?

This topic is about noise, not about the patch. Higher noise requires higher confidence. Those results indicate that noise must be pretty high, so i am opening the topic for people with scientific skills to investigate.

**Comment by NKONSTANTAKIS** [comment]
After more consideration, I assess that the C24 vs C24 effectively increases resolution and fluctuation (white noise). That's favorable in general because while fluctuation is annoying only at small samples, resolution is helpful everywhere.

In practice this means that while premature termination via a wild swing of wins/losses is more likely at low gamecounts, the result will surely be more accurate after a point.

**Comment by vondele** [comment]
I'll close this, this has all changed drastically with the NNUE merge.
