### ISSUE TITLE
Stockfish user questions re skill levels?

### ISSUE THREAD

**Issue by yuribudilov** [official-stockfish/Stockfish#2817]
Hello everyone.

I am a user of Stockfish, not a developer.

Where can I ask questions about Stockfish from the end user perspective?

Specifically, the Skill Level (1-20) ELO approximate strength?
I would like to know how to obtain approximate ELO FIDE strength rating from Stockfish levels below its 20-top.
This is playing *longer time controls* of 1 hour plus 30 sec move increment, *not* for the blitz games.
For example, if I can beat Stockfish on 60 min + 30 sec time control on skill level 10, what is the ELO of level 10?

I am already aware of ELO Stockfish playing very fast 1 min + 1 sec time controls as published here:
https://www.sp-cc.de/experiments.htm

Many thanks for such a great chess engine!

**Comment by LouisZulli** [comment]
You might ask at https://groups.google.com/g/fishcooking or at http://talkchess.com/forum3/index.php
