### ISSUE TITLE
master bench unstable.

### ISSUE THREAD

**Issue by Vizvezdenec** [official-stockfish/Stockfish#2822]
https://tests.stockfishchess.org/actions
Tests are getting stopped because of it.

**Comment by noobpwnftw** [comment]
It's still happening(and in one case not from me). I thought it was due to my worker but now it seems there is a bug.

https://github.com/glinscott/fishtest/issues/729

**Comment by noobpwnftw** [comment]
[log.txt](https://github.com/official-stockfish/Stockfish/files/4960939/log.txt)

**Comment by vondele** [comment]
After some digging, this appears to be a hardware defect. I'll close the issue here.
