### ISSUE TITLE
Change NNUE file extension

### ISSUE THREAD

**Issue by nguyenpham** [official-stockfish/Stockfish#2849]
The current file extension .bin makes confused since it says so little information, can’t help to recognise from other file purposes. In chess, that extension (.bin) is used already for Polyglot opening books too.

I suggest to change to specific ones such as “.nnue”, “.sfbin”, “.sfnnue”... to delete any confusion/wrong use in long terms.

**Comment by vondele** [comment]
@nodchip what would be your opinion?  I wouldn't be opposed to .nnue but I have no strong opinion.

**Comment by nodchip** [comment]
I also don't have any strong opinions.  Though .nnue sounds good to me.

**Comment by stockchess** [comment]
.nnue logical and distinctive extension.

**Comment by vondele** [comment]
done
