### ISSUE TITLE
(NNUE) How to set SF to use NNUE at default

### ISSUE THREAD

**Issue by CalKK8** [official-stockfish/Stockfish#2869]
How can I have Stockfish use the NNUE eval file at default using Terminal? I tried

```
./stockfish
setoption name Use NNUE value true
```

But the default stayed false.

**Comment by LouisZulli** [comment]
This is not an issue. That said, edit [here](https://github.com/official-stockfish/Stockfish/blob/21d43e95008678dc6ad164c403004c3a4aeb8f56/src/ucioption.cpp#L96) before compiling.

**Comment by CalKK8** [comment]
@LouisZulli Thank you.
