### ISSUE TITLE
[NNUE] Missing Makefile header dependencies

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#2870]
We now have some header files that are not properly recognized as dependencies in the Makefile.
nnue_feature_transformer.h is one example.  It should cause evaluate_nnue.cpp to rebuild but doesn't.
I'm not enough of a Makefile expert to know how to add them.

**Comment by vondele** [comment]
additionally, it also seems something is wrong with the syzygy dependencies, at least that's my feeling. Maybe part of https://github.com/official-stockfish/Stockfish/issues/2660 go reverted?

**Comment by vondele** [comment]
Another question I have is the use/correctness of the new `ifeq ($(COMP),msys2)` section... is this needed or redundant ?

**Comment by vondele** [comment]
fixed

**Comment by mstembera** [comment]
Works.  Thanks.
