### ISSUE TITLE
[NNUE] Change suffix extension to a more traditional 3 or 2 characters

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#2875]
I should have been more precise in my original objection, having 4 characters as a file extension goes against all traditional file naming extension conventions.it should  be change it to 3 or 2 characters , I suggest "nnu" or going with two letters "nn".  Not really a big deal., just trying to help clean it up.

**Comment by vondele** [comment]
3 char file extensions are really a relic of the old age, longer extensions are quite common (.docx or .pptx come to my mind).

**Comment by MichaelB7** [comment]
Good point - I’m also a relic of the old age 😊
