### ISSUE TITLE
[NNUE] UCI protocol issue

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/Stockfish#2886]
The message

"Error! nn-c157e0a5755b.nnue not found or wrong format"

is not valid UCI. It should be an info string (it confuses xboard for some reason).

**Comment by vondele** [comment]
OK, thanks. Possibly an info string is better. 

A hard error seems not the right thing at this point, but maybe when search starts, Use NNUE is true, and no net is loaded...

**Comment by vdbergh** [comment]
This is being discussed now. Hence closing.

**Comment by vondele** [comment]
I'll close it once the needed code is merged. Note that an alternative is https://github.com/official-stockfish/Stockfish/pull/2893

**Comment by vondele** [comment]
fixed with  #2893
