### ISSUE TITLE
[NNUE] avoid HACK 

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2888]
```
  #if defined(__MINGW32__) || defined(__MINGW64__)
            // HACK: Use _mm256_loadu_si256() instead of _mm256_load_si256. Because the binary
            //       compiled with g++ in MSYS2 crashes here because the output memory is not aligned
            //       even though alignas is specified.
```
probably related to the version of gcc rather than the target. Need to figure out more precisely when this can be avoided.

**Comment by dorzechowski** [comment]
On MinGW 10.2.0 it seems to be unnecessary.

**Comment by syzygy1** [comment]
Is it related to this bug report?
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89357
Then it seems to have been fixed in gcc-9.3 and gcc-10.

**Comment by dorzechowski** [comment]
Looks like this is it.

I can confirm also no problems with gcc 9.3.0.

**Comment by syzygy1** [comment]
But that bug seems to be related to ARM. Still, it might be an issue somehow common to ARM and mingw...

**Comment by dorzechowski** [comment]
Also no problems with gcc 8.3.1 on Linux. Perhaps we can remove this hack, requiring reasonably new compilers seems not too outrageous to me.

**Comment by syzygy1** [comment]
I am guessing that mingw-gcc shares with arm-gcc that MAX_STACK_ALIGNMENT is/was 16 (due to Windows, basically), whereas it is 2^31-1 on linux-gcc.

**Comment by mstembera** [comment]
Probably we should also change
struct alignas(32) Accumulator
to
struct alignas(kCacheLineSize) Accumulator
in nnue_accumulator.h since everything else is aligned to kCacheLineSize.

**Comment by dorzechowski** [comment]
This hack exists only in sections requiring AVX2 or AVX512, not relevant to ARM. I think it's safe to try and remove it.

**Comment by vondele** [comment]
@nodchip, do you recall the origin of this 'HACK', i.e. on which system was it needed. See also  #2891

**Comment by nodchip** [comment]
A crash bug was reported on the unofficial Discord Stockfish server.  I asked the reporter to investigate with gdb, and found the memory is was not aligned.  I'm sorry but I forgot the reporter's system.  I'm not sure if we can remove it safely.

**Comment by vondele** [comment]
was it this one: https://discord.com/channels/435943710472011776/718853716266188890/724478071427825676

From that thread it seems that c++17 fixed it for the poster. However, you didn't mention in that thread that you implemented the 'HACK' for it.

**Comment by nodchip** [comment]
I thought that it was the origin.  But it seems not to be...  I'm sorry but I forgot the origin...

**Comment by vondele** [comment]
so, I think it is better to avoid doing this cleanup as part of the merge. Rather keep it open so that we can deal with it later, and more easily revert/adjust as needed.

**Comment by dorzechowski** [comment]
I'm of course fine with postponing it till later. We can see [in nodchip's repo](https://github.com/nodchip/Stockfish/commit/09e529edd37257d5d272bd924932d4aee767ba73) that this hack was commited over a year ago and concerned g++ on MSYS2. I use MSYS2 and see no problems. However, using C++14 instead of C++17 indeed results in a crash.

**Comment by syzygy1** [comment]
Is the crash caused by misalignment?

**Comment by dorzechowski** [comment]
Yes.

**Comment by syzygy1** [comment]
And do you get the warning when compiling about requested alignment being > 16?

**Comment by vondele** [comment]
I've seen such a warning on PPC https://github.com/official-stockfish/Stockfish/issues/2823#issuecomment-664357858

**Comment by dorzechowski** [comment]
No, I haven't seen it (gcc 9.3.0).

**Comment by vondele** [comment]
warning on requested alignment is seen on msys2 with older gcc https://github.com/glinscott/fishtest/pull/738#issuecomment-667997437

**Comment by alex-ssy** [comment]
I thank you for your kind attention and wish you every success in your work.

**Comment by nodchip** [comment]
I found the origin of this issue...  https://twitter.com/nodchip/status/1146797306705874944

**Comment by vondele** [comment]
this has been fixed in a recent commit https://github.com/official-stockfish/Stockfish/commit/875183b310a8249922c2155e82cb4cecfae2097e 
we'll need to use gcc >= 9 for efficient avx2 code.

on a related note, avx512 will need gcc >= 10
