### ISSUE TITLE
Honey-XI-r4 not running on Mac

### ISSUE THREAD

**Issue by ArminHHJ** [official-stockfish/Stockfish#2903]
Hi,

I am a Mac User and download the macOS-bmi2.zip and macOS-modern.zip
https://github.com/MichaelB7/Stockfish/tree/48607844bae61e8442a1585e8c39c7dd0756e439

Both downloads crashed in HIARCS Chess Explorer (Unexpected Error), when using a Sergio-NN or NNUE. For all included compiles.

Now I download the Source and make an own executable.
make build ARCH=x86-64-bmi2 comp=clang

I got an error while compliling:
misc.cpp:477:3: error: void function 'std_aligned_alloc' should not return a
      value [-Wreturn-type]
  return aligned_alloc(alignment, size);

Edit in misc.cpp:477 to correct(?) this.

void* std_aligned_alloc(size_t alignment, size_t size) {
#if defined(__APPLE__)
  return std_aligned_alloc(alignment, size);

A Stockfish-XIr4 was build, but don’t work in HIARCS Chess Explorer.
It crashed in HIARCS Chess Explorer (Unexpected Error), when using a Sergio-NN or NNUE.

Last week I make a Stockfish-NN from your sources (19.07.20?).
Configured with Brainfish-Books and Sergio-NN. Great performance, it is the strongest fish on my Mac ever :).

0,1 sec per move, 03.08.20, MacBook Pro, 1 CPU, HERT500-Book 8ply
Rank 	Name                          			Elo     	+/-   	Games   	Score   	Draws
   1 		SF+NN-XI-1907-SV0801-Brain     104      	25     	500   	64.6%   	36.0%
   2 		Brainfish-240720-bmi2-AJ       	  50      	24     	500   	57.1%   	37.4%
   3 		SF+NN-XI-1907-SV0801                 7      	25     	500   	51.0%   	32.4%
   4 		Stockfish-11-200726-bmi2-AJ    -48      	25     	500   	43.1%   	35.4%

Starting the executible in terminal, you see it is Stochfish-XI-NN
Armins-MacBook-Pro:~ armin$ /Users/armin/Downloads/Stockfish-NN/src/Stockfish-NN-1907-bmi2-AJ ; exit;

    ######                                             #    #       .-'`````'-.   #     # ###                      
    #     # #####  ####   ####  #    # ###### #  ####  #    #  (\  /   \   /   \   #   #   #     #    # #    #     
    #         #   #    # #    # #   #  #      # #      #    #  ) \/   (@) (@)   \   # #    #     ##   # ##   #     
     #####    #   #    # #      ####   #####  #  ####  ###### (__(       W       )   #     # ### # #  # # #  #     
          #   #   #    # #      #  #   #      #      # #    #    (  V v V V v V  )  # #    #     #  # # #  # #     
    #     #   #   #    # #    # #   #  #      # #    # #    #     \  A A A A A  /  #   #   #     #   ## #   ##     
     #####    #    ####   ####  #    # #      #  ####  #    #      \/\-.,,,.-/\/  #     # ###    #    # #    #     
    Stockfish XI-NN  by T. Romstad, M. Costalba, J. Kiiski, G. Linscott

My Questin und please to support:

Why crashing the bin from your compile?
Was this editing right?
How I can build a running Version or the other Version like Honey, Diamond … if I do an own compile?

Hope you can help for the new r4

Armin

**Comment by vondele** [comment]
This is the wrong repo, @MichaelB7 might know.

**Comment by MichaelB7** [comment]
You can contact me here if you're still having an issue.
https://github.com/MichaelB7/Stockfish
Just open an issue on my fork.

**Comment by ArminHHJ** [comment]
I wanted do that, but there is no possibility to do that... I found no "Issue"-Button. All compiles (downloads) you have done (for Mac) in XI r4 are not running, also the source download. Last version XI from yesterday I downloaded, I can compile (Stockfish-XIr4)
