### ISSUE TITLE
[NNUE] NNUE and FRC

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2905]
reported to crash https://github.com/official-stockfish/Stockfish/issues/2728#issuecomment-669012059

**Comment by vondele** [comment]
@gekkehenker do you have one of those positions that crashes?

Note that our standard bench includes FRC, and people have been running it with NNUE eval... and so would we if we start moving towards PGO with NNUE.

**Comment by vondele** [comment]
@nodchip @dorzechowski do you have an idea what could be missing on the branch for FRC?

**Comment by nodchip** [comment]
I have never tried FRC.  We could need some positions causing crash for investigation.

**Comment by gekkehenker** [comment]
When I'm home I'll run a new test and share the PGN.

**Comment by vondele** [comment]
I can at least do a bench using the starting positions, without crash:

https://raw.githubusercontent.com/AndyGrant/Ethereal/master/src/perft/fischer.epd

```
setoption name UCI_Chess960 value true
setoption name Use NNUE value true
bench 16 1 13 fischer.epd depth
```

**Comment by vondele** [comment]
also no crash playing 2000 quick FRC games, or bench like above to depth 20. 

We'll need to wait for confirmation this is a bug, and/or have a careful look at do_move etc. that it is doing the right thing for FRC.

**Comment by dorzechowski** [comment]
I played couple hundred FRC games and seen no problems (in cutechess-cli). Most likely someone didn't set it up properly.

**Comment by gekkehenker** [comment]
Seems like only my old binaries crash with FRC.

**Comment by vondele** [comment]
OK, I think we can consider this resolved. I also ran a long FRC bench under valgrind and all seems clear.
