### ISSUE TITLE
[NNUE] Consider column-major storage in AffineTransform,like in FeatureTransformer

### ISSUE THREAD

**Issue by sf-x** [official-stockfish/Stockfish#2908]
Moving here, per nodchip's request, from https://github.com/nodchip/Stockfish/issues/73 :

https://hxim.github.io/Stockfish-Evaluation-Guide/?p=nnue tool shows that the activations in hidden layers are also sparse (in the biggest layer, less than 1/4 in the positions I tried). Therefore, switching to column-major (possibly tiled) storage of matrix in AffineTransform class, like in FeatureTransformer (or more complicated) should be a major (yes, word play was intentional) speedup in the "non-SIMD" (really compiler-generated SIMD) case, and relatively simple to implement.
Besides, this format would permit SIMD using scalar instructions (since the entire column is mul'd by the same value).
Also possible that that means the initialization is not optimal and many "neurons" end up not affecting anything.

**Comment by sf-x** [comment]
This was done in Cfish: https://github.com/syzygy1/Cfish/commit/a8b09a7d2952c3b60f6a91b27c58cbaa1aa4781d
Apparently, on some CPUs SSE2 build with that is better than SSSE3 one without...

**Comment by vondele** [comment]
I'll close this issue, it hasn't seen updates for a long while, and we have made many changes to the code since.
