### ISSUE TITLE
[NNUE] Optionally use a network for profile-build to optimize NNUE code.

### ISSUE THREAD

**Issue by xgfs** [official-stockfish/Stockfish#2917]
Title pretty self-explanatory. As far as I understand, currently `bench` only uses the standard eval, so PGO optimization is currently not possible for the master branch.

One option would be to search for network files nearby, and use that, if available, for existing profile-build rule.

**Comment by vondele** [comment]
duplicate of #2907 ?

**Comment by xgfs** [comment]
Sorry, overlooked.
