### ISSUE TITLE
MS PowerShell : download default NNUE net. Help needed.

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#2924]
To be able to download the default net in [appveyor](https://github.com/official-stockfish/Stockfish/blob/master/appveyor.yml) CI we need some PowerShell equivalent of the  `make net` target:

```make
net:
        $(eval nnuenet := $(shell grep EvalFile ucioption.cpp | grep Option | sed 's/.*\(nn-[a-z0-9]\{12\}.nnue\).*/\1/'))
        @echo "Default net: $(nnuenet)"
        $(eval nnuedownloadurl := https://tests.stockfishchess.org/api/nn/$(nnuenet))
        $(eval curl_or_wget := $(shell if hash curl 2>/dev/null; then echo "curl -sL"; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi))
        @if test -f "$(nnuenet)"; then echo "Already available."; else echo "Downloading $(nnuedownloadurl)"; $(curl_or_wget) $(nnuedownloadurl) > $(nnuenet); fi
```

which basically greps the value of the default net out of `ucioption.cpp` and uses curl/wget to download it.

Having this functionality is needed before we can do PGO builds / mixed benches. Code welcome.

**Comment by gvreuls** [comment]
This works on Windows 10, it assumes ucioption.cpp in in the current directory and downloads to it too.
```
$nnuenet = cat ucioption.cpp | Select-String -CaseSensitive -Pattern "Option" | Select-String -CaseSensitive -Pattern "nn-[a-z0-9]{12}.nnue"
$nnuenet -match "(?<nnuenet>nn-[a-z0-9]{12}.nnue)"
$nnuenet = $Matches.nnuenet
echo "Default net: $nnuenet"
$nnuedownloadurl = "https://tests.stockfishchess.org/api/nn/$nnuenet"
if (Test-Path -Path $nnuenet) {
    echo "Already available."
} else {
    echo "Downloading $nnuedownloadurl"
    Invoke-WebRequest -Uri $nnuedownloadurl -OutFile $nnuenet
}
```

**Comment by vondele** [comment]
Thanks! Could you make a PR that adds this to appveyor. It will be unused for now, but needed soon.

**Comment by gvreuls** [comment]
@vondele Should I strip the status echos and the net file existence check? The integration test will be built in a clean environment so the net file won't be present anyway.

**Comment by vondele** [comment]
I would think it is good to have them (if they are just a few lines of output), will help to diagnose when something goes wrong.

**Comment by vondele** [comment]
I'll close that since we have the solution as part of https://github.com/official-stockfish/Stockfish/pull/2931
Thanks @gvreuls !
