### ISSUE TITLE
I am unable to build a binary using Intel Parallel Studio 2020.

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#2925]
Hello!
I cannot build a binary using Intel Parallel Studio 2020 integrated into MSVC [2019.
When building, I get an error message:

icl: : warning #10428: '/Qstd:<arg>' conflicts with '/std:<arg>'; using '/Qstd:<arg>'
  benchmark.cpp
  misc.cpp
  tbprobe.cpp
  uci.cpp
  bitbase.cpp
  endgame.cpp
  movegen.cpp
  half_kp.cpp
  pawns.cpp
C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\pawns.cpp(40): error : expression must have a constant value
      constexpr Score BlockedPawn[2] = { S(-13, -4), S(-4, 3) };
                                       ^
  C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\types.h(369): note: value exceeds range of "int"
      return Score((int)((unsigned int)eg << 16) + mg);
                                                 ^
  
  position.cpp
  thread.cpp
  tt.cpp
  ucioption.cpp
  bitboard.cpp
  evaluate.cpp
C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\evaluate.cpp(128): error : expression must have a constant value
      constexpr Score MobilityBonus[][32] = {
                                            ^
  C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\evaluate.cpp(128): note: attempt to access run-time storage
      constexpr Score MobilityBonus[][32] = {
                                   ^
  
  main.cpp
  material.cpp
  movepick.cpp
  evaluate_nnue.cpp
  psqt.cpp
C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\psqt.cpp(32): error : expression must have a constant value
    constexpr Score Bonus[][RANK_NB][int(FILE_NB) / 2] = {
                                                         ^
  C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\psqt.cpp(32): note: attempt to access run-time storage
    constexpr Score Bonus[][RANK_NB][int(FILE_NB) / 2] = {
                         ^
  
C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\psqt.cpp(88): error : expression must have a constant value
      { // Pawn (asymmetric distribution)
      ^
  C:\Users\Marat\Documents\Visual Studio 2019\Oficial_Stockfish+NN\src\types.h(369): note: value exceeds range of "int"
      return Score((int)((unsigned int)eg << 16) + mg);
                                                 ^
  
  search.cpp
  timeman.cpp
  tune.cpp

**Comment by vondele** [comment]
your post starts with `icl: : warning #10428: '/Qstd:' conflicts with '/std:'; using '/Qstd:'` are you sure you specified c++17 correctly? 

MSCV CI works here: https://ci.appveyor.com/project/mcostalba/stockfish/builds/34536049/job/fpf1a3wrleve9jx8

**Comment by Marat-Ka** [comment]
I think yes.

https://imageup.ru/img28/3639218/capture.png

**Comment by Marat-Ka** [comment]
I think I found the problem.
For some reason, when switching from the MS compiler to the Intel compiler, this option was not enabled:

https://imageup.ru/img71/3639236/intel.png

The switch has been set to "no".

The build is currently running correctly.

**Comment by vondele** [comment]
OK, thanks for the update. I'll close the issue, please reopen if a problem persists.
