### ISSUE TITLE
Full Engine Name

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#2929]
Please display the full name of the engine and network.
For example, instead of "StotskFish 20200805" - type "StotskFish 20200805 x86/64 SSE3/4.1/4.2/AVX2  etc. and net_file_name (or net's CheckSum)"

Now this is possible and not very important, but soon, when we will analyze games, when there will be many games and many engines and networks, this will probably be needed.

**Comment by vondele** [comment]
try `./stockfish compiler` and of course the network depends on the value of `EvalFile` (which on gets from `./stockfish uci`

**Comment by Marat-Ka** [comment]
How can I do it in MSVC shell?

**Comment by Marat-Ka** [comment]
And yet, I would like this to be the official behavior of any compilers.

**Comment by vondele** [comment]
I think the current outputs are sufficient, no need to embed this all in the name
