### ISSUE TITLE
Hybrid issues

### ISSUE THREAD

**Issue by mbabigian** [official-stockfish/Stockfish#2938]
Although the hybrid eval was a good idea and gained good ELO, it causes problems and should be a UCI option.  As a programmer I can remove it and recompile.  Most users cannot.  Just like many engines allow you to disable Null move to solve zugzwang positions, this too should be an option users can turn off or adjust the threshold.  No one yet knows the best threshold for max ELO or even if the imbalance calculation is the best method to decide when to switch.  Please consider making this an option for those that aren't programmers and are already finding many positions where it causes problems.  This will allow us to learn more about it and perhaps further improve the idea.

For my use cases, I will be building my own exec's without it.

P.S. One other point.  With improved training code and training techniques, networks may become better at playing the endgame than SF's current handcrafted eval.  How will anyone know this, if they can't turn hybrid off?

**Comment by Vinvin20** [comment]
The most usefull settings would be a choice between :
1) Only C++ eval
2) Only NNUE eval
3) Mixed eval

**Comment by vondele** [comment]
Of course one can use an old binary as well. 
I don't think this warrants a UCI option, like we don't have UCI options to disable null-move pruning, LayzEval classical, etc. I'm rather sure that we will have nets soon that won't work well without the hybrid option, i.e. are specifically constructed to benefit from the fact that classical eval is good enough for many positions. I think hybrid is a real opportunity.
