### ISSUE TITLE
HyperThreading on/off and the strength of the game

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#2955]
I am sure that it is necessary to test the quality of the game with HyperThreading enabled and disabled.

The problem is that HyperThreading has a good effect on integer operations, (i.e., conditionally - search), but has practically no effect on vector (network position estimation), so there may be situations when turning on HT will only additionally heat up the CPU, which will cause reducing its frequency, but will not give a profit in the strength of the game.

**Comment by vondele** [comment]
That's not an engine issue. Yes, will need testing, but actually it is well possible that hyperThreading is very effective for an engine that mixes both vector instructions and integer ops.  See also: http://www.talkchess.com/forum3/viewtopic.php?f=2&t=74705&sid=81373c80ada74c41cf13b3c1e09143d9
