### ISSUE TITLE
Value Eval::evaluate( const Position& pos )

### ISSUE THREAD

**Issue by MikeKagansky** [official-stockfish/Stockfish#2961]
If the user chose [ Use NNUE: ON ], then the only solid way is:

Value Eval::evaluate( const Position& pos ) 
{
if( Eval::useNNUE ) return ( NNUE::evaluate(pos) + Tempo );
return Evaluation<NO_TRACE>(pos).value();
}

Without lines that slow down the engine in the clear majority of positions ( < +5.00 )

**Comment by MikeKagansky** [comment]
checkbox [ Use NNUE ] ( true / false ) 

can also be replaced with

combobox [ Eval ] ( NNUE_ONLY / Hybrid / Classic_ONLY )

**Comment by ZagButNoZig** [comment]
Use nnue != ONLY use nnue

**Comment by MikeKagansky** [comment]
( nodchip )-style ----------- Hybrid / Classic_ONLY ( checkbox )
https://github.com/nodchip/Stockfish/blob/master/src/evaluate.cpp ( Line 943 )

( FireFather )-style --------- NNUE_ONLY / Classic_ONLY ( checkbox )
https://github.com/FireFather/sf-nnue/blob/master/src/evaluate.cpp ( Line 896 )

( !!! ) must be
( Stockfish )-style ---------- NNUE_ONLY / Hybrid / Classic_ONLY ( combobox )

**Comment by LouisZulli** [comment]
Others have made the same request, but this is not the path that the Stockfish team has decided to take. 

You might wish to go to https://github.com/joergoster/Stockfish/tree/nnue_always

**Comment by vondele** [comment]
I'll close this, the precise use of NNUE in the code is an implementation detail. We will use it the way it brings most Elo in tests, and this is guaranteed to change as the code and nets get refined. Exposing this with an UCI option is premature, and limits our freedom to adjust. If pure NNUE is the strongest approach, which it might eventually be, we will go there.
