### ISSUE TITLE
Fix a data race for NNUE build  - App crash for the bmi version

### ISSUE THREAD

**Issue by Coolchessguykevin** [official-stockfish/Stockfish#2963]
Latest build from abrok.eu (BMI2 version), terminal engine window works well, but when trying to start analisys in any GUI (checked at Fritz and Aquarium), engine is crashing. NNUE=true, default net used. 

Yesterday's build worked well at the same conditions.

Some info from windows event log:

P1: stockfish_20080923_x64_bmi2.exe
P2: 0.0.0.0
P3: 00000000
P4: stockfish_20080923_x64_bmi2.exe
P5: 0.0.0.0
P6: 00000000
**P7: c0000005**
P8: 00000000000eaaca
P9: 
P10:

**Comment by Coolchessguykevin** [comment]
It happens ONLY when NNUE=true. With classic evaluation engine works without crashes.

**Comment by Coolchessguykevin** [comment]
From the engine log file before its crashes:

>> setoption name Contempt value 0
>> setoption name Threads value 7
<< info string Hash table allocation: Windows large pages not used.
>> setoption name Use NNUE value true
>> setoption name EvalFile value C:\NNUE\nn-9931db908a9b.nnue
>> quit

**Comment by crossbr** [comment]
I have the same problem, both with bmi and with avx2, in Arena GUI. It works if I uncheck the "Use NNUE" box, but not if I check that box.

**Comment by fohristiwhirl** [comment]
I have what seems to be this crash - I agree the relevant commit is the previous one, a6e8929 ("Avoid special casing for MinGW")

**Comment by vondele** [comment]
OK, compiler issue identified with gcc 7.3, I'll revert the offending commit.
