### ISSUE TITLE
SSE4x and AVX1

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#2972]
SSE4x and AVX (not AVX2) can speed up?
Now, as I see it, only three instruction variants are used - AVX512, AVX2 and SSSE3:

#if defined(USE_AVX512)
      constexpr IndexType kNumChunks = kPaddedInputDimensions / (kSimdWidth * 2);
      const __m512i kOnes = _mm512_set1_epi16(1);
      const auto input_vector = reinterpret_cast<const __m512i*>(input);

  #elif defined(USE_AVX2)
      ...

  #elif defined(USE_SSSE3)
      ...

Does anyone know if this work is planned?

**Comment by vondele** [comment]
not really, see discussion https://github.com/official-stockfish/Stockfish/pull/2922

Also do not use issues to post questions, this is not a help forum. For real bugs/problems, use issues, for proposed patches make a pull request.
