### ISSUE TITLE
AVX512 architecture build fails with older GCC compilers.

### ISSUE THREAD

**Issue by gvreuls** [official-stockfish/Stockfish#2975]
The merge of PR #2962 introduced the `_mm512_zextsi256_si512` intrinsic for AVX512 builds. The definition of this and other intrinsics is missing in the file `avx512fintrin.h` for GCC compilers older than version 10.

I tried including avx512fintrin.h directly (which is not best practice) in PR #2974 but this only looked like a fix due to my dodgy git practices, the only workaround right now is to use GCC 10 (or clang).

**Comment by vondele** [comment]
right, in addition to g++-10,  also works with clang++-9 and clang++-10

**Comment by mstembera** [comment]
According to https://software.intel.com/sites/landingpage/IntrinsicsGuide _mm512_zextsi256_si512 is part of the base AVX512F instructions and supposed to be in declared <immintrin.h> which we include.  I can write a version w/o it however.  Is that how we want to proceed?

**Comment by vondele** [comment]
You propose again something conditional on the gcc version ? Depends a bit if this is easy or invasive, and if it is performance wise similar or not.

**Comment by Vizvezdenec** [comment]
no offense but what the fuck is this.
https://i.imgur.com/Rr9VnVx.png

**Comment by vondele** [comment]
@Vizvezdenec no idea, you'll need to give more info. Obviously something specific to your setup / local changes?

**Comment by Vizvezdenec** [comment]
I did update to the latest master and this is what it's returning with make of anything

**Comment by Vizvezdenec** [comment]
Hm, okay, I did make clean and then usual build path and it started to work. No idea what it was, it's the first time I've seen smth like this.

**Comment by mstembera** [comment]
@gvreuls @vondele Can you try this https://github.com/official-stockfish/Stockfish/pull/2976
