### ISSUE TITLE
BMI2 build fails to compile with gcc 9.2

### ISSUE THREAD

**Issue by hero2017** [official-stockfish/Stockfish#2977]
I'm able to compile the latest SF but near the end I get:

`make[3]: [N:\msys64\tmp\ccH0xcXx.mk:12: N:\msys64\tmp\stockfish.exe.AD1ZKf.ltrans3.ltrans.o] Error 1 (ignored)
make[3]: [N:\msys64\tmp\ccH0xcXx.mk:3: N:\msys64\tmp\stockfish.exe.AD1ZKf.ltrans0.ltrans.o] Error 1 (ignored)
make[3]: [N:\msys64\tmp\ccH0xcXx.mk:9: N:\msys64\tmp\stockfish.exe.AD1ZKf.ltrans2.ltrans.o] Error 1 (ignored)
make[3]: [N:\msys64\tmp\ccH0xcXx.mk:6: N:\msys64\tmp\stockfish.exe.AD1ZKf.ltrans1.ltrans.o] Error 1 (ignored)`

I've never seen this before and previous compiles worked fine up until the last few SF updates. I made no changes to my system, mingw, gcc or msys2. This is on Win'2012R2.

I still get a stockfish.exe but I don't know how reliable that is. make clean doesn't help either.

I'm compiling with `CXXFLAGS='-flto' LDFLAGS='-flto -O3 -march=native' make profile-build -j ARCH=x86-64-bmi2 COMP=gcc` as I have been for some time now.

**Comment by MichaelB7** [comment]
It looks like an lto error - can you try without the -flto flag and can you try it with gcc 10 with flto? Refreshing your compiler set might help.  There has been an issues with flto  of late , remedy has been to upgrade gcc 10.

**Comment by mstembera** [comment]
I get similar output using gcc 10.1.0
See https://bugs.launchpad.net/gcc-arm-embedded/+bug/1853451
The -save-temps flag gets rid of it.

**Comment by hero2017** [comment]
@MichaelB7 I tried it without the -flto flag but got the same errors.

@mstembera I tried the -save-temps flag which did get rid of the error but the engine crashes upon starting infinite analysis in Aquarium with a windows unhandled exception error. It doesn't crash if I disable nnue. I tried several of sergio's nets, including the ones approved by SF (nn-112bb1c8cdb5.nnue) and the engine still crashes.

**Comment by hero2017** [comment]
I have just updated to gcc 10.2 but same errors.

Btw I just noticed #2943. So we are not to use COMP=gcc anymore, only (and always) COMP=mingw? That means no flto though right?

Anyway COMP=mingw does work and even though I specified -flto still the file size is 1.2 MB instead of the usualy 310KB so no link time opt I guess.
