### ISSUE TITLE
'make clean' doesn't remove downloaded nets

### ISSUE THREAD

**Issue by GBeauregard** [official-stockfish/Stockfish#2982]
After https://github.com/official-stockfish/Stockfish/commit/ea6220f3813e5b76b444a02905eaf2c556bdb368, profile-build produces new files that aren't cleaned up/removed with `make clean` (the downloaded NNUE nets). This means that as the default net changes the src directory will grow and require manual cleaning not covered by `make clean`.

**Comment by vondele** [comment]
that's on purpose as downloading the nets takes time, and make clean is common. I would rather consider it 'source' (but for technical reasons not part of the github history), not generated files.

**Comment by GBeauregard** [comment]
> that's on purpose as downloading the nets takes time, and make clean is common. I would rather consider it 'source' (but for technical reasons not part of the github history), not generated files.
I noticed https://github.com/official-stockfish/Stockfish/issues/2981 proposes to literally include it in the source, so I'm linking for reference.

**Comment by ddugovic** [comment]
I don't know what I'm talking about, but could making NNUE nets a submodule somehow allow Git to track the maps without them appearing in this project's history?

**Comment by gvreuls** [comment]
How about
```Makefile
netclean:
    @rm -f nn-*.nnue
```
``make netclean``

**Comment by GBeauregard** [comment]
> How about
> 
> ```makefile
> netclean:
>     @rm -f nn-*.nnue
> ```
> 
> `make netclean`

I think this is a nice solution that addresses the concerns.

**Comment by vondele** [comment]
but I wonder how many people will recall the 'netclean' target, as opposed to just execute `rm nn-*.nnue`

**Comment by vondele** [comment]
I'll close this, I think the current state is fine.
