### ISSUE TITLE
Integration with GUI on Android Q

### ISSUE THREAD

**Issue by jairhumberto** [official-stockfish/Stockfish#2983]
Hello Dear Friends,

I know this is not really a Stockfish issue, but I hope you can help me, or tell me where to find help. (I didn't find anybody else who could help me after 15 days searching, I really am out of options). I tried to register myself at the forum http://talkchess.com but they didn't activate my registration until now, after 4 days (I tried to contact them with no success).

The thing is that I spent one and a half years developing a GUI for Stockfish for Android using the SDK (not NDK) and I relied on the copy and paste the stockfish binary from the assets folder to the files folder and then executing it. It was working perfectly.

However, Android Q forbade such behavior, saying that it is a w^x principle violation. Now, instead, I have to execute the binary from the apk or from the native libs folder. I know how to proceed in neither case. If I don't fix this, I won't be allowed to publish my app.

I found that I have to move my binary to the app/libs/{ABI} folder, rename it to something like libstockfish.so, and enable android:extractNativeLibs=true in the application tag on the manifest. I did that, but it doesn't work as expected. When I try to load the Stockfish from the ApplicationInfo.nativeLibraryDir dir on Android, it says "No such file or directory found".

Would you know where should I search to find help?

**Comment by vondele** [comment]
doesn't look like there has been much response for a week. The closest we have right now is the issue of building stockfish for android (https://github.com/official-stockfish/Stockfish/issues/2860). Since this issue is not really stockfish specific, I'll close it now.
