### ISSUE TITLE
NNxxx.nnue can't be changed in ucioption

### ISSUE THREAD

**Issue by hartmajr** [official-stockfish/Stockfish#2991]
I provide my own .nnue file in src while compiling and call it nn.nnue. If I change ucioption to reflect that, I can't compile. Here's the error I get on GCC 10.2.

Default net: o[EvalFile]              << Option(nn.nnue, on_eval_file);
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `if test -f "o["EvalFile"]              << Option("nn.nnue", on_eval_file);"; then echo "Already available."; else echo "Downloading https://tests.stockfishchess.org/api/nn/o["EvalFile"]              << Option("nn.nnue", on_eval_file);"; curl -sL https://tests.stockfishchess.org/api/nn/o["EvalFile"]              << Option("nn.nnue", on_eval_file); > o["EvalFile"]              << Option("nn.nnue", on_eval_file);; fi'
/bin/sh: warning: here-document at line 0 delimited by end-of-file (wanted `Option')

Any ideas?

**Comment by LouisZulli** [comment]
As a workaround, simply give _your_ .nnue file whatever name appears in ucioption.cpp. Recent changes to the Makefile prevent the sort of editing of ucioption.cpp that you want to do.

**Comment by hartmajr** [comment]
Will the compiled exe file recognize any .nnue file in the same directory, or does it have to have the same name as what's in the makefile?

**Comment by hartmajr** [comment]
And can I alter the makefile to get around this?

**Comment by noobpwnftw** [comment]
Yes, you can remove part of the Makefile that parses default net from sources and download if it doesn't exist and it'd be fine.

**Comment by hartmajr** [comment]
So just delete 599-604?

**Comment by noobpwnftw** [comment]
Either that or remove "net" here: https://github.com/official-stockfish/Stockfish/blob/6bc0256292cf51d390fee0cb78963da884dc2677/src/Makefile#L572

But make sure your net is present in the src folder so the PGO process will not fail to load it.

**Comment by hartmajr** [comment]
Thanks! This is a big help.

**Comment by vondele** [comment]
at compile time, it really make little sense to provide your own net unless it is a different architecture. If you want to prepare a test for a new default net, you follow the naming convention and adjust EvalFile in ucioption.cpp

**Comment by hartmajr** [comment]
It does indeed make a difference when you are compiling for specific audiences and reasons. Not all engine users are savvy enough to figure out uci settings each time a new / stronger net comes out. If I can give them an engine with a simple net name hardcoded in it (and one that either uses the AB eval or the NN eval, not both / hybrid) I can also give them updated networks using the same name, and all they have to do is overwrite the old file, etc.

**Comment by vondele** [comment]
possibly, when a new net comes out that is stronger (as guaranteed by fishtest), it will appear as the default value of EvalFile. The distribution of this is a little more tricky, basically both binary and net form a pair that should not be separated. Having a unique name is pretty important IMO, it is like a version number of a binary. One wants to know how to reproduce a previous analysis, and for that the net name is essential. 

BTW, given we have a standard API for net downloads, a GUI could automatically fetch them based on the value of EvalFile and put them in the right place if not yet available. Users could just drop the binary and the GUI could help with the net. 
@nguyenpham ?

**Comment by vondele** [comment]
@nguyenpham only when the user adds the new engine, download the default net (In the future, new nets will likely not work with old binaries). The net and binary should be used together IMO (e.g. by the time a new net comes out, also the binary will be stronger).

This doesn't need to be just SF, you could always look for the EvalFile UCI option and if it happens to match `nn-[a-z0-0]\{12\}.nnue` try a download from `https://tests.stockfishchess.org/api/nn/[filename]`. For SF the net will always be there, for other engines this is not unlikely. Storing the net, I don't know, but I assume the gui has some place where it stores configuration data already ? (like $HOME/.mygui/data/nn/). The GUI could presumably also adjust the path prefix of the default net, if it is stored there.
