### ISSUE TITLE
API to download the latest net

### ISSUE THREAD

**Issue by nguyenpham** [official-stockfish/Stockfish#2997]
The README says about downloading a net if we know already the name. I wish we have a few more API to download easier as well as doing automatically/writing in scripts:

* API to download the latest net, e.g:
https://tests.stockfishchess.org/api/nn/latest

* API to get name of the latest net (to decide to download or not), e.g:
https://tests.stockfishchess.org/api/nn/latestname

**Comment by vondele** [comment]
the latest date is not always the best net, we would need at least the last default net. Furthermore nets will be specific to the binary (e.g. format changes, etc).  

One basically needs to get this from the binary (or sources). I would use the equivalent of `./stockfish uci | grep EvalFile`. People compiling from sources should use `make net`

**Comment by snicolet** [comment]
To extract the recommended net for a specific stockfish binary:
```
./stockfish uci | grep EvalFile | awk 'NF>1{print $NF}'
```

**Comment by vondele** [comment]
![image](https://user-images.githubusercontent.com/4202567/90310992-e5fb6380-def6-11ea-8785-df033fd8c049.png)

so, some updates to fishtest by @tomtor to address part of these concerns:

* nets which achieved 'default net' status in the history of development will highlight green on the list. The newest of those will most probably be the default net of master.
* nets will only be visible to the outside world if they have had a running test on fishtest. Without test, needs fishtest login to be visible. This might help to deal with the illegal upload of nets by non-authors, or without explicit CC0 license. Approvers should engage with unknown net authors before approving (FYI, @Vizvezdenec, @locutus2, @tomtor, @snicolet, @mstembera, @pb00067, @MJZ1977, @ElbertoOne, @protonspring, et al)
* nets will show the date/link of the first and last test that has been run with them, which will tell how well it performed when introduced, and how long it has been active.

@sergiovieri, @jjoshua2,  @gekkehenker the process of uploading and testing should remain identical. Future nets will have the proper first test data field, now we had to populate the database with a some new tests, for simplicity.

**Comment by vondele** [comment]
I see that the Banksia GUI now has the feature to automatically download and install the net with a new engine. 
http://www.talkchess.com/forum3/viewtopic.php?f=2&t=72350&start=960#p856303
Thanks @nguyenpham ! I hope other GUIs will follow.

I'll close this as resolved.
