### ISSUE TITLE
Downloading the net on windows

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#3005]
The Makefile doesn't work on windows (by curl or wget)

**Comment by vondele** [comment]
can you build the code on windows otherwise? curl should be part of the current msys2 distribution.

https://packages.msys2.org/package/mingw-w64-x86_64-curl
maybe it is not installed by default, in which case one should be able to get it with `pacman -S mingw-w64-x86_64-curl` or similar, and we could make it part of the windows installer.

**Comment by amchess** [comment]
> 
> 
> can you build the code on windows otherwise? curl should be part of the current msys2 distribution.
> 
> https://packages.msys2.org/package/mingw-w64-x86_64-curl
> maybe it is not installed by default, in which case one should be able to get it with `pacman -S mingw-w64-x86_64-curl` or similar, and we could make it part of the windows installer.

Ok. Thanks. The problem is I'm with msys1.0. So, perhaps I have to pass to msys2.0 or remove net profile in profile-build and download the net manually.

**Comment by vondele** [comment]
I think upgrading to msys2 is a good idea, it might also be needed to have recent enough compilers. You might want to checkout the docs here https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows#installing-msys2

However, if you manually download before profile-build, you don't have to change the makefile, it will detect the file being present.

**Comment by amchess** [comment]
Thanks a lot!
I will try.

**Comment by vondele** [comment]
@ppigazzini maybe you can add the install command for curl to the scripts here https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows#building-stockfish after testing.

**Comment by ppigazzini** [comment]
@vondele msys2 is shipped with curl and wget, the wiki script tests only for non default packages (unzip, make, gcc).

**Comment by vondele** [comment]
OK, good. There was a similar message on fishcooking https://groups.google.com/g/fishcooking/c/Sd-GtjmUznQ/m/7T485HxWBQAJ that's likely also a missing curl. Maybe the old 'portable installer' doesn't have curl?

**Comment by ppigazzini** [comment]
I confirm that "Portable" hasn't curl/wget and it's not able to run fishtest. Users need to update to msys2 setup.

**Comment by vondele** [comment]
So time to retire the https://github.com/glinscott/fishtest/wiki/A-portable-fishtest-worker-for-Windows-64-bit page ?

**Comment by ppigazzini** [comment]
@vondele wiki page retired (after some backups).
