### ISSUE TITLE
NNUE and endianness 

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#3007]
I'm taking the comment by @syzygy1 here 
https://github.com/official-stockfish/Stockfish/issues/2915#issuecomment-674295715
to an issue.

quote: Am I wrong to think that NNUE has endianness problems?
For example, ReadParameters() reads a uint32_t by reading 4 chars into the memory location of the uint32_t. The outcome is dependent on the machine's endianness.

@nodchip any idea ?

**Comment by syzygy1** [comment]
Of course this is relatively easy to fix (if the problem indeed exists).

**Comment by vondele** [comment]
patches more than welcome, if indeed there is an issue.

**Comment by vondele** [comment]
probably would need a convention on both the learner (writes) and the player (reads), so in principle both can run on different endianness.

**Comment by syzygy1** [comment]
Little endian probably makes the most sense given the current nets and the prevalence of x86. Then big-endian machines will have to swap bytes when writing and reading 16-bit and 32-bit values.

**Comment by vondele** [comment]
yes, I agree we should keep the format of the file little endian and swap if needed. Can you make pull request for that? Bonus points if you have big endian hardware to test, of course.

**Comment by syzygy1** [comment]
OK, I'll come up with something probably later today.
