### ISSUE TITLE
Problems compiling 32bit with MinGW.

### ISSUE THREAD

**Issue by massimilianogoi** [official-stockfish/Stockfish#3025]
32bit developing environment: classical MinGW:

I wasn't able to compile:

a) 32bit
b) 32bit old
c) 32bit general

 Because of this error:

Default net: nn-82215d0fd0df.nnue
Already available.
./nn-82215d0fd0df.nnue: ./nn-82215d0fd0df.nnue: cannot execute binary file
Failed download or nn-82215d0fd0df.nnue corrupted, please delete!
make: *** [net] Error 1
strip: 'stockfish.exe': No such file
The system cannot find the file specified.
The system cannot find the file specified.

The only flavour who compiled properly was 32bit ppc, for unknown reasons.

Compiling a,b,c after deleting the file nn-82215d0fd0df.nnue:

Default net: nn-82215d0fd0df.nnue
Downloading https://tests.stockfishchess.org/api/nn/nn-82215d0fd0df.nnue
./nn-82215d0fd0df.nnue: ./nn-82215d0fd0df.nnue: cannot execute binary file
Failed download or nn-82215d0fd0df.nnue corrupted, please delete!
make: *** [net] Error 1

WORKAROUND:

In the Makefile I deleted:

	$(eval nnuedownloadurl := https://tests.stockfishchess.org/api/nn/$(nnuenet))
	$(eval curl_or_wget := $(shell if hash curl 2>/dev/null; then echo "curl -skL"; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi))
	@if test -f "$(nnuenet)"; then echo "Already available."; else echo "Downloading $(nnuedownloadurl)"; $(curl_or_wget) $(nnuedownloadurl) > $(nnuenet); fi
	$(eval shasum_command := $(shell if hash shasum 2>/dev/null; then echo "shasum -a 256 "; elif hash sha256sum 2>/dev/null; then echo "sha256sum "; fi))
	@if [ "$(nnuenet)" != "nn-"`$(shasum_command) $(nnuenet) | cut -c1-12`".nnue" ]; then echo "Failed download or $(nnuenet) corrupted, please delete!"; exit 1; fi

And the compilation of a,b,c ran smoothly.

**Comment by vondele** [comment]
The old mingw distribution is missing a now needed tool (curl / wget). I'll make patch to make that clearer from the error message. The solution is to install a more modern mingw. The instructions for that are 
https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows#install-msys2-with-chocolatey
or even more automatic as part of the fishtest worker installation:
https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows#msys2

**Comment by vondele** [comment]
And additionally, the curl/wget is not needed if one does a `build` instead of a `profile-build`
