### ISSUE TITLE
Mate in 5 that Stockfish nor NNE can see

### ISSUE THREAD

**Issue by aochoam** [official-stockfish/Stockfish#3029]
Maybe this has been discussed before.

4K1k1/8/1p5p/1Pp3b1/8/1P3P2/P1B2P2/8 w - - 0 1

Reading the talkchess forum, http://talkchess.com/forum3/viewtopic.php?f=2&t=74818, I also verified this position and Stockfish as well NNE have a hard time to find it.

I tested the old Zappa Engine and it is able to find in less than 3 seconds.

Thanks.

**Comment by Hanamuke** [comment]
The position is just very hard, it's not mate in 5.

**Comment by LouisZulli** [comment]
Did you mean this actual mate-in-5?

rk6/p1r3p1/P3B1Kp/1p2B3/8/8/8/8 w - - 0 1

http://www.talkchess.com/forum3/viewtopic.php?f=2&t=74803#p856379

**Comment by vondele** [comment]
Ah, I was expecting that one. 
Anyway, we all know that this is pruning related, and old engines prune less so have an easier time to find this.

**Comment by aochoam** [comment]
Hello.

@LouisZulli . That one!

It would ne intereting to check why Leela, not old, is able to see so soon.

Thanks.

**Comment by vondele** [comment]
MCTS not AB.

**Comment by snicolet** [comment]
Closing, as indeed the Talkchess thread is a nice place to discuss and visualize the positions(with boards, etc)
http://www.talkchess.com/forum3/viewtopic.php?f=2&t=74803#p856379
