### ISSUE TITLE
Improve dealing with the default net?

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#3030]
This is an issue to see if we should improve the current way we look for the default net. Currently, the default net will be found if it has been downloaded and copied to the working directory of the engine, or if the user specified the 'EvalFile' with the proper path if the file is located elsewhere. Bullet points are mixed pro/cons.

Several options exist:
* (**option 1**) Leave as is:
  * This is easy, users will figure this out.
  * GUIs will help them. One GUI already auto-downloads the needed net (http://www.talkchess.com/forum3/viewtopic.php?f=2&t=72350&start=960#p856303). Legacy GUIs will not do this.
  * Not all users know this, the clear error message with missing net goes to cerr, and is not shown by all GUIs. An info string might help? (https://github.com/official-stockfish/Stockfish/pull/3031)
* (**option 2**) First look in the CWD, afterwards look in the dir of the binary (https://github.com/snicolet/Stockfish/commit/1d62e773d91e80e5459e19fea5ac8caad0ec8691) also https://github.com/official-stockfish/Stockfish/pull/3001
  * introduces a heavy dependency (std::filesystem), not available everywhere
  * magic might not work e.g. for linux distros that will keep binary and net separate
* (**option 3**) Extend the semantics of EvalFile .. if directory look for the default net there. (https://github.com/official-stockfish/Stockfish/pull/3001)
  * needs to be set only once, works with any new default net
* (**option 4**) Introduce an EvalFilePath 
  * one more UCI option.
  * Could be set at compile time for distros (caveat building profile build)
* (**option 5**) Integrate the net in the binary (https://github.com/official-stockfish/Stockfish/issues/2915#issuecomment-672294651)
  * linker tricks 
  * bin2hex and compile
  * Edit: large download volumes might be problematic.

While most things can be easily implemented, the question is is we need them, or if they become a source of confusion and mistakes.

**Comment by gekkehenker** [comment]
I think integrating the net is a nice thing for a SF12 (or 13, 14, etc.) official release.
Releases tend to attract the people who just want it to work with a single click and not worry about settings and other "difficult" stuff. For them SF12 can be the one click install.

In other cases I think it's fine just the way it's currently is.

**Comment by nguyenpham** [comment]
I think one of the strong points of current SF NNUE is that there are so few networks to choose (or that is a very weak point ;) ) and there is always a suggested-network as the default value of EvalFile, thus users get less confusion to find, select, download... In contrast, I have seen so many supports/answers from LC0 teams are just about the need for networks, which/where to download, etc... Thus, I hove SF NNUE can continue that advantage: always have one good network fit for multi-purpose/hardware.

For chess GUIs, I think once they support downloading networks, they can do more work to manage them. For example, they can search from multi folders, sort to display, verify, delete them, let users select and auto do the rest (such as setting up paths). Basically, if we accept the help from chess GUIs on, we have done on that issue, users don't need to go to the engine level/folder to fix problems.

**Comment by vondele** [comment]
@gekkehenker We should not adopt a different method for our releases from the one we use during development. Only if we're able to use it ourselves all the time will it be good enough.

**Comment by snicolet** [comment]
As a funny subtext for the current discussion, please watch the small video of https://github.com/official-stockfish/Stockfish/issues/3052 . 

Obviously this "Samer707" chess fan is so fast that @the-real-greco is right, he will never read a Readme
nor navigate to a forum, a Discord, etc... What he wants is download a Stockfish version, point his GUI at
the executable, and run analysis.

Isn't interested in nnue files, no Readme, no parameter dialog, no nothing...

download exe, point, run.

It must work out of the box :-)

**Comment by vondele** [comment]
which will not necessarily work by having SF look for a net close to the binary. Just two typical cases, are linux distros which will put those files in different locations, and users that will download the files as they always did, and move the exe to where they store their other exes, separating them from the network. If we really think users are not smart enough, the only option I see is to embed it in the binary.

**Comment by vdbergh** [comment]
I do not think we have to worry about Linux packaging. The packagers will simply patch the source so that SF will find the net. Of course the tools used for generating binary packages are equipped to do this automatically.  

IMHO: one sensible way to help linux packagers is to create a makefile argument with the default value for the NNUE path

**Comment by vondele** [comment]
I think fundamentally we have two choices:

1) we provide a single file
2) we provide two files.

IMO:

1) will make it 'fool-proof'. If a user manages to download the exe, it will probably work. It will come with a number of downsides related to very large binaries (e.g. slow build, more difficult distribution (github/abrok), virus scanners going crazy, etc). Even if our nets today are 'small', this will likely change. One thing that is missing is a patch that implements this option.

2) users will always find a way to separate the two, and have any amount of 'smart logic' fail, so we'll patch it up, over and over.

**Comment by gvreuls** [comment]
How about this scheme:
* Keep EvalFile and apply the "stockfish starting directory from argv[0] magic" to it. This way simple distribution of development versions from websites, where the user puts the executable and net files in the same directory, work.
* Extend the EvalFile magic in the sense that if it's empty, a fixed file path to the net file specified at compile time is used. This way fancy packagers that put the net file in another directory can compile in a fixed net on a specified location and clear the default EvalFile value.

This way you keep the ease of distributing development versions with the "argv[0] magic", while packagers are able to compile in another default path and net without drastically changing the code. GUIs and/or users who put their nets in yet another location are assumed to know what they're doing and must set EvalFile manually; there is no difference in doing this between home compiled versions, development distributed versions and Linux distro packaged versions, the logic is always the same.

So here is the logic:
1) If EvalFile is empty, use the compiled in default path and net.
2) If EvalFile isn't empty, try to load the net from EvalFile without applying any magic.
3) If 2. fails, prepend the argv[0] starting directory to EvalFile and try to load EvalFile from the resulting location.

**Comment by vondele** [comment]
@snicolet patch contains this, we could easily make it like
```
std::vector<std::string> dirs = { "" , CommandLine::binaryDirectory };
```
distros
```
std::vector<std::string> dirs = { "" , CommandLine::binaryDirectory, "DEFAULT_NET_DISTROS" };
```
where DEFAULT_NET_DISTROS  could be changed with a define at compile time. So, would search 3 directories instead of 2.

**Comment by gvreuls** [comment]
@vondele You need some preprocessor-foo to get a -D macro quoted: https://github.com/official-stockfish/Stockfish/blob/530fccbf272ffe424ae53a464b91db148cc968ae/src/misc.cpp#L165-L166
but basically:
```C++
#ifdef DEFAULT_NET_DISTROS
  std::vector<std::string> dirs = { "" , CommandLine::binaryDirectory, stringify(DEFAULT_NET_DISTROS) };
#else
  std::vector<std::string> dirs = { "" , CommandLine::binaryDirectory };
#endif
```
and a minor makefile change and we're in business (if you go for it).

**Comment by syzygy1** [comment]
Perhaps there could be two kinds of builds: (i) a build with integrated network and without an EvalFile option, and (ii) a build without integrated network and with an EvalFile option.

The official builds for regular users would be of type (i). I guess this is the only way to make SF12 available to regular chess players without causing them headaches and frustration.

For advanced users wishing to experiment with different nets, builds of type (ii) might also be provided. Alternatively, they have to compile such a build themselves or obtain it from someone else.

I do think it is important to keep builds of type (ii) since SF development can benefit from users being able to test other networks. (Also, it would be annoying for sites like abrok to have to provide 20M+ development versions for download.)


If the network is (optionally) included in the SF binary, we might want to reconsider compressing the (integrated) network file, e.g. to save bandwidth.

**Comment by Dantist** [comment]
> it would be annoying for sites like abrok to have to provide 20M+ development versions for download
> we might want to reconsider compressing the (integrated) network file

It can be 7MB: https://github.com/nodchip/Stockfish/issues/76
But things may change as the net architecture evolves.

**Comment by syzygy1** [comment]
@Dantist 

> > it would be annoying for sites like abrok to have to provide 20M+ development versions for download
> > we might want to reconsider compressing the (integrated) network file
> 
> It can be 7MB: [nodchip#76](https://github.com/nodchip/Stockfish/issues/76)
> But things may change as the net architecture evolves.

That proposal seems to be about some sort of special-purpose compression, which may well break (or become inefficient) if the network architecture changes. It probably makes more sense to use a general-purpose compressor like gzip/zlib. Of course the decompression library will have to be statically linked or we would just be replacing one dependency for another.

Hmm, I just realise that the argument against including decompression code for "external" network files is just as valid for integrated network files. Instead of letting SF decompress the network weights, just provide the SF binary as a zip file...

**Comment by daylen** [comment]
When we distribute Stockfish 12, it will be in zip files. So I don't think size is a huge concern for a main release.

@vondele is right, fundamentally the choice is between distributing 1 file or 2 files. I think that with enough "smart logic" the engine will be able to find the EvalFile most of the time…

Another idea is that rather than stop analysis when the EvalFile is not found with this error:
```
info string ERROR: NNUE evaluation used, but the network file nn-82215d0fd0df.nnue was not loaded successfully.
info string ERROR: The UCI option EvalFile might need to specify the full path, including the directory/folder name, to the file.
info string ERROR: The default net can be downloaded from: https://tests.stockfishchess.org/api/nn/nn-82215d0fd0df.nnue
info string ERROR: If the UCI option Use NNUE is set to true, network evaluation parameters compatible with the program must be available.
info string ERROR: The engine will be terminated now.
```
we fallback to the classical evaluation. This would make the engine "always work" but at the cost of sometimes not using NNUE. If the user is wondering which eval is _actually_ being used, the engine does say which eval is in use with `info string` but I'm not sure if all GUIs display that string.

**Comment by Dantist** [comment]
It seems that as the engine develops, the classical search alone will become weaker and weaker, so the binary with strongest classical search - is the binary compiled just before the NNUE branch merge. If so, then the NNUE file should be an integral part of the engine and over time the stockfish without the NNUE file alongside, will simply be "too weak"..

**Comment by nguyenpham** [comment]
IMO, stopping when the network not found is better than the auto-switching to the classic one. Users must find and solve the problem instead of ignoring and assuming there is no problem. They may find and fix the problem much quicker. No point to continue since it is not what users want, according to the engine's settings.

Chess GUIs can show info strings, typically not in popups but just normal windows/panels (to avoid disturbing users too much). Users may turn those panels off or hide them under other panels thus they may easily ignore that info. Thus, the stop/crash of the engine may take much more attention.

**Comment by vondele** [comment]
The following is a link to a repo that deals with including binaries in sources:

 https://github.com/graphitemaster/incbin 

It works great in clang/gcc and 10+ other compilers (i.e. essentially no added compile time), but MSVC support requires generating an additional source file, which needs about 1-2 min to compile. The same is true for the header generated via `xxd -i nn-82215d0fd0df.nnue > nn.h`.

There is also a proposal for `std::embed`  http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1040r4.html but that has gone nowhere so far.

**Comment by syzygy1** [comment]
I think what you mean is including a binary data file in the compiled binary/executable (not "including binaries in sources").

**Comment by syzygy1** [comment]
(Not trying to nitpick, but I was about to question why the network file would have to be included in the SF sources.)

**Comment by MJZ1977** [comment]
Personally, I find that "option 1" is working well and not complicated. 
But if there is some difficulties to use it, why not using a new parameter to default path (option 4?)

**Comment by noobpwnftw** [comment]
We are mainly dealing with 3 types of binary files:
1. PE/COFF, Windows, the most trivial way is to add the net as overlay data at the end of the file on disk, very common practice for most self-extracting installers and Whatever2EXE(SWF2EXE, Perl2EXE and so on), antivirus may complain, but we can apply digital signatures(Authenticode) to silence most of them.
2. ELF, Linux, the most trivial way is to add data as extra symbol/object with the linker, as described earlier.
3. Mach-O, Mac, very similar to ELF and can probably do the same.

There are plenty of scenarios where such embedding mechanism is needed for various reasons, and there are well-established specifications within each executable format on how to accomplish this.

**Comment by vondele** [comment]
thinking a little more with it, using [incbin](https://github.com/graphitemaster/incbin) seems like it could work. `<internal>` could be added as one more path to https://github.com/official-stockfish/Stockfish/pull/3054 and on those setups where incbin works (essentially all) we could first see if the net is part of the binary, falling back to the other mechanisms as needed (also e.g. for non-default networks).

Only MSVC users would compile their own binaries that would never find something under `<internal>` since it is not supported, they would continue to use the current mechanism. Since nobody distributes MSVC compiled binaries as far as I know, the magic would work for essentially all users that download binaries.

If somebody could come up with a prototype patch, that would be appreciated. I expect this will need an iteration or two, since it needs to smoothly work with fishtest, CI, etc.

**Comment by snicolet** [comment]
Here is a prototype: https://github.com/official-stockfish/Stockfish/pull/3070

**Comment by vondele** [comment]
So, IMO #3070 looks like an approach that covers the most important cases from the user perspective. 

1) It embeds the default net in the binary, so a download of that binary will result in a working engine with the default net, no need to fiddle around with any options. 

2) It still allows non-default nets to be used, which will be looked for in up to three directories (working directory, location of the binary, a distro specific directory). This mechanism is also kept for those developers that use MSVC, the one compiler that doesn't have an easy mechanism for embedding data.

Would be good if #3070 could get some testing in the wild, since it uses some less standard code. In particular, testing on windows would be needed.

Comments on the approach, in particular overlooked aspects, would be welcome as well.

**Comment by snicolet** [comment]
One small caveat of #3070 is that (if the default net is not yet in the src directory) it relies on the availability of an Internet connection to download the net before compiling: the API `https://tests.stockfishchess.org/api/nn/` has to be available and running.

Today around 5:30 CST time, it so happened that fishtest went down, so I took the opportunity to rename the default net in my src directory and try to compile #3070, I got a make error for the implicit net target of the Makefile after one minute:

**make clean**
**make build**
make: *** [net] Error 7

Of course this is only relevant for compiling from sources, once the end users get the big stockfish with the embedded net in their hard disc they will be able to use it, internet connection or not.

**Comment by hartmajr** [comment]
#1 seems best to me. FWIW.

**Comment by Alayan-stk-2** [comment]
I think embedding a net is a good solution for many end users. The less effort the user has to spend to make things run correctly, the less likely the user will mess up something.

**Comment by Silver-Fang** [comment]
After so many days of practice after deciding to embed, I am now firmly opposed to embedding. Look at my analysis of pros and cons:

Pros: 1

- Allows traditional users to enjoy the latest and strongest engine power without changing configuration.

Cons: 2

- The network part is rarely updated compared to the executable part. So with each executable update, users need to re-download the **large and unchanged** network part, wasting time, storage space, and bandwidth.

- In order to save download time, storage space and bandwidth, a ZIP file is downloaded now, requiring extra steps after download like decompression, renaming, etc. The operation is very cumbersome.

BTW, please don't use Straw Poll on abrok.eu. This site is broken on its account login or register, so voters can't leave comments.

**Comment by noobpwnftw** [comment]
@Silver-Fang 
Your goal contradicts your approach, on one hand you want to save download time, storage space and bandwidth, on the other hand, you want to download a binary for every commit, decompress and archive them in uncompressed form. This outcome is decided by two factors: size of the binary and the frequency of commits, however you only see the former as a problem, for the latter you can simply download a compile once every week/month/year, which would easily meet your desired goal of saving download time, storage space and bandwidth.

Meanwhile, do people very often download, compile, or archive every Chrome, GCC, or any other projects' nightly build? If not, why would they do that to a chess engine in particular? It is exactly for those people who cannot understand the difference between a release and a nightly build, that we need to have everything embedded to save their day.

**Comment by vondele** [comment]
I'm very strongly in favor of keeping the default net embedded. Let's optimistically estimate that only 5% of the roughly 1M users of SF struggle only 10min to find the right solution. That's literally 1 year of human time lost. In reality it is much more. Even I only transferred the binary to my phone after the net was embedded, as I couldn't (care to) find out where to put the net and how to specify it...

Embedding only makes it easier for the majority of people. Most that whine don't even verify that you can still run any net you want. The only downside is the storage.... those that are capable of dealing with a non-embedded net are some hobbyists, and they should spent $50 on a 500GB HD that stores them 25000 exes ($0.002 per stored binary).

I would have preferred that the exes are not zipped on abrok, I do think it adds one click too many. But that's up to the owner of the site to decide.

**Comment by syzygy1** [comment]
What the Stockfish source code offers as default compilation option shouldn't stop sites like abrok.eu from compiling SF without embedded net, should they so wish (up to them).

**Comment by vondele** [comment]
The problem is that most issues that users have with binaries downloaded on abrok come to us (github issues, fishtest, direct messages, etc), and we do suggest people to get their dev versions from abrok. So if that source would not be suitable anymore, we would presumably have to create an alternative, which seems like an unneeded effort.

**Comment by Silver-Fang** [comment]
@noobpwnftw @vondele 
However, why don't we suggest those, who have no interest in understanding the exe-net relationship, to simply download the official release version, which has a net embedded? That's where we actually want plain users to go, isn't it? I probably didn't make it clear before. What I mean is that, it should be only the release version, but never the development build, that has the net embedded in.

**Comment by vondele** [comment]
@Silver-Fang so far abrok was a site for users, you seem to want to limit it to a small subset of people. Why optimize for those who can't affort a 20MB download, instead of keeping the latest and strongest SF available to a wide user base? The former can compile that special version from sources. I'm really unable to see what use-case you have in mind that is blocked by a 20MB exe.
