### ISSUE TITLE
The ndk commit has broken compilation on AArch64 elsewhere

### ISSUE THREAD

**Issue by gsobala** [official-stockfish/Stockfish#3056]
The ndk commit has broken compilation on AArch64 elsewhere: as per the [ARM Reference Guide](https://developer.arm.com/documentation/dui0774/f/Compiler-Command-line-Options/-mfpu), -mfpu is not required for AArch64 and actually triggers a gcc error (unrecognised option). Thus 

```
make build ARCH=armv8
```
now fails on a Raspberry Pi running a 64-bit OS.

Note that (pragmatically) -DUSE_NEON still is required to enable neon.

**Comment by snicolet** [comment]
@gsobala 

In you opinion, which part of the ndk commit (65b976439f8867e81682c0b66da6796ad3176177) is the offending part? How could we fix that on your machine?

**Comment by gsobala** [comment]
[This branch](https://github.com/gsobala/Stockfish/tree/raspi) fixes it in a very raspberry pi specific way, but the more I read about it I suspect that gcc will fail on all armv8 systems with -mfpu - but I have no way of testing this.

**Comment by vondele** [comment]
BTW, as mentioned elsewhere, the following compiled on master... 
```
# cross to RPI
make clean && make -j build ARCH=armv7         COMP=gcc COMPILER=arm-linux-gnueabihf-g++
make clean && make -j build ARCH=armv7-neon    COMP=gcc COMPILER=arm-linux-gnueabihf-g++
```
however, we should try to fix the other variants, and I see you have a PR ready.

**Comment by gsobala** [comment]
Yes, armv7 does require the mfpu flag
