### ISSUE TITLE
Proposal : double throughput

### ISSUE THREAD

**Issue by MJZ1977** [official-stockfish/Stockfish#3066]
This is not an issue, but rather a proposal : can we allow users with only one running test on fishtest to double the throughput ?

One double throughput test is equivalent to 2 normal throughput test and take even less ressources than 3 or 4 running tests on the same idea. This also allow the possibility to make quick tests even if the queue is full and a better sharing of the ressources. Any other idea is welcome.

**Comment by VoyagerOne** [comment]
Better idea is to have approvers not approve those patches.

**Comment by MJZ1977** [comment]
@VoyagerOne : I am approver but I don't know what criteria to use to detect "those patches". I understand that sometimes we need to try something like "what if ...". But the limit is not clear and the "what if ..." method sometimes works as well.

**Comment by Sopel97** [comment]
Maybe don't allow two patches to run in parallel if they touch the same area of the code or a patch like this already passed shortly before.

**Comment by vondele** [comment]
IMO, we don't need to make the implementation of priorities on fishtest too complicated. Right now it is designed to give highest priority to patches with best LLR / LTC. Excessive use is best handled by kindly requesting the user to moderate the usage and adjust throughput by hand. 

So, I don't see a real need to act with a patch to fishtest, and I'll close the issue.
