### ISSUE TITLE
Stockfish struggling with Nakhmanson gambit

### ISSUE THREAD

**Issue by ElianCordoba** [official-stockfish/Stockfish#3078]
I just saw [this](https://youtu.be/vnX6Y9QNeTo) video where it show a few positions in which SF did not found the best lines, at one point early in the video, even missing a mate in 8

**Comment by locutus2** [comment]
There the old Stockfish 11 is used which is around 100 elo behind current master.

**Comment by Sopel97** [comment]
By "struggling" you mean that it cannot find the 'correct' move when given 10 seconds on a single core. Not surprising.

**Comment by vondele** [comment]
so I'll close as not an issue. There will always be single positions where finding the bestmove is slow. There needs to be a pattern before it can be addressed.
