### ISSUE TITLE
Testing contempt

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#3079]
Hi all,

There have been quite a few contempt tests for NNUE against sf-8, sf-9, sf-10, sf-11 even, but their results are very difficult to interprêt because of the chi2 problem (p-value = 0.00), a consequence of the speed disparity in the nnue optimzations.

Two suggestions maybe for contempt testing:

1) we could decide that the weak side of a contempt test will have a time handicap instead of a old version handicap. So for instance contempt would be 1 sec against 19 sec, or 2 sec against 18 sec. This way the weak side and the strong side would both use nnue, on the same machine.

2) or we could decide that contempt tests should all be compiled with the same minimal SIMD implementation (sse2) or even without any SIMD implementation (plain C++)

Opinions?

Stephane

**Comment by vondele** [comment]
One could also pick as the weaker side the master branch, but use a weaker net (nn-c157e0a5755b.nnue), or the initial NNUE commit (84f3e867903f62480c33243dd0ecbffd342796fc). The first option would be most hardware-agnostic. The Elo difference is probably not very large (50?)

I'm not sure how important the effect is if tests run at the same time, i.e. have roughly the same set of machines present. It is most pronounced if a fleet of more modern hardware lands.

**Comment by mstembera** [comment]
The nice thing about a time handicap is that you can effectively dial in whatever elo difference you wish.

**Comment by vondele** [comment]
AFAIK there there is no way to do this on fishtest?

**Comment by lp--** [comment]
Probably it should not be that much work to substitute SF-dev search with, say, SF9 search and create weaker NNUE opponent.

**Comment by Sopel97** [comment]
or if fishtest doesn't support variable time control then just make a fork that divides the time values by a constant when receiving them over uci

**Comment by mega-optimus** [comment]
IMHO, we should aim for *perfect* evaluation function, which assumes infinite time control.

Furthermore, from perfect evaluation function's point of view, contempt is the advantage of stm. NNUE has stm information as input, so there doesn't seem to be a need for contempt value of NNUE.

**Comment by snicolet** [comment]
@mega-optimus 

Maybe there are philosophical reasons why contempt will not work with NN in the end, but the current situation is that we don’t know, and have no precise way to test. This thread is to gather ideas for a more precise testing procedure :-)

**Comment by barrtgt** [comment]
Why not use a node limit instead? Or would that make comparisons with time control matches more difficult?

**Comment by syzygy1** [comment]
The hypothetical perfect evaluation function with infinite time control would only return a draw value or a mate value. It would probably make SF play terrible chess, aimlessly shuffling pieces from drawn position to drawn position (unless the opponent doesn't play the same aimless shuffling game and walks into a mate-in-85).

So I do not agree that Stockfish should aim for a perfect evaluation function. Instead, it should aim for an evaluation function that tends to gradually lure the weaker opponent into making a fatal mistake in a game that probably has a relatively wide theoretical drawing margin. Contempt makes a lot of sense to me.

How to do this properly with NNUE is an interesting question.

**Comment by mega-optimus** [comment]
> The hypothetical perfect evaluation function with infinite time control would only return a draw value or a mate value. It would probably make SF play terrible chess, aimlessly shuffling pieces from drawn position to drawn position (unless the opponent doesn't play the same aimless shuffling game and walks into a mate-in-85).
> 
> So I do not agree that Stockfish should aim for a perfect evaluation function. Instead, it should aim for an evaluation function that tends to gradually lure the weaker opponent into making a fatal mistake in a game that probably has a relatively wide theoretical drawing margin. Contempt makes a lot of sense to me.
> 
> How to do this properly with NNUE is an interesting question.

Playing perfect move is *not* aimless, and perfect moves are extremely rare like needles in a haystack.

**Comment by syzygy1** [comment]
@mega-optimus 
It is quite likely that the following game consists of only perfect moves:
1. Nf3 Nf6 2. Ng1 Ng8 3. Nf3 Nf6 4. Ng1 Ng8  1/2-1/2

Obvously 2. Ng1 is a pretty stupid move if the goal is to win the game, but with a perfect evaluation function there is no difference between 2. Ng1 and, say, 2. d4. Unless 2. Ng1 turns the game into a theoretical win for black, which seems unlikely.

**Comment by mega-optimus** [comment]
> @mega-optimus
> It is quite likely that the following game consists of only perfect moves:
> 
> 1. Nf3 Nf6 2. Ng1 Ng8 3. Nf3 Nf6 4. Ng1 Ng8  1/2-1/2
> 
> Obvously 2. Ng1 is a pretty stupid move if the goal is to win the game, but with a perfect evaluation function there is no difference between 2. Ng1 and, say, 2. d4. Unless 2. Ng1 turns the game into a theoretical win for black, which seems unlikely.

We don't know whether Ng1 leads to win or draw or loss.

**Comment by syzygy1** [comment]
@mega-optimus Sure, but I hope you do get the point?

**Comment by mega-optimus** [comment]
> @mega-optimus Sure, but I hope you do get the point?

Yes. Any seemingly innocent move could have catastrophic impacts.

**Comment by snicolet** [comment]
The idea to use a different net is interesting. I have uploaded the net used in Igel called "Night Nurse 0.2", described in this talkchess thread: http://talkchess.com/forum3/viewtopic.php?p=856742#p856742

**Comment by locutus2** [comment]
@snicolet 
I retry my old nnue contempt ideas with this net. My best try with C=24 and C=50 gets 127 elo in comparison to 124 but this is lies in the error bar. Currently i try less contempt C=12 https://tests.stockfishchess.org/tests/view/5f5a092c093dcfbade2b79d8. But i have the impression that probably ~130 elo weaker opponent (in the past we used over 200 elo) is not enough for good contempt testing. Is there perhaps a older Night Nurse which is between 200-300 elo weaker?

**Comment by vondele** [comment]
The old measurements https://github.com/glinscott/fishtest/wiki/UsefulData#contempt-measurements show roughly 15-20 Elo against an opponent that's 100 Elo weaker. I think the current testing setup is sufficient. 

Note also that only authors of the nets should upload them unless they are CC0 licensed already.
