### ISSUE TITLE
Why is the abrok.eu download now a ZIP?

### ISSUE THREAD

**Issue by Silver-Fang** [official-stockfish/Stockfish#3082]
I am used to download EXE directly to overwrite the old EXE with the filename unchanged. Now I'll have to unzip and rename. Very inconvenient.

**Comment by ssj100** [comment]
It seems to me that since the net was embedded into the binary, the file size has increased to over 20Mb.  By zipping it, this is reduced to around 12Mb.

**Comment by Silver-Fang** [comment]
> It seems to me that since the net was embedded into the binary, the file size has increased to over 20Mb. By zipping it, this is reduced to around 12Mb.

However I don't feel significant acceleration of download before and after zipping. Instead the unzip and rename procedures are quite annoying. Anyway, who has the patience and Internet speed to download 12 ㎆ won't care if it becomes 20 ㎆ - a difference of only a dozen of seconds.

**Comment by Silver-Fang** [comment]
At least for me, the manual unzip and rename procedures cost considerably more time than that saved by 8 ㎆ less download.

**Comment by TonHaver** [comment]
Reducing filesize by 40% can be insignificant for an end-user as you, but could be significant for the one who's paying for the bandwidth of the server

**Comment by Sopel97** [comment]
I'm sure you can afford to spend a few more seconds to get the engine running every few days or so.

**Comment by MichaelB7** [comment]
They could offer both — zipped and unzipped.  Looks like both cases are legitimate.

**Comment by Silver-Fang** [comment]
> Reducing filesize by 40% can be insignificant for an end-user as you, but could be significant for the one who's paying for the bandwidth of the server

Are you sure that the server is billed by traffic rather than time? Usually I prefer servers charging a fixed monthly fee.

**Comment by snicolet** [comment]
We discussed this with Roman Korba, who runs and pays for the Abrok site thanks!) and gives it to you free of charge. He decided that using compression was a good idea for him to save storage and bandwidth.

Stockfish is a popular project, with quite a few new versions every week, sometimes several a day. When you do the maths, the storage and bandwidth required are much more than what you think.

If you don’t like the compressed binaries, I would suggest downloading the sources and compiling yourself. Or maybe even better, running a site equivalent to Abrok, putting only uncompressed binaries for the community. Thanks in advance! :-)

Stéphane

**Comment by Silver-Fang** [comment]
> We discussed this with Roman Korba, who runs and pays for the Abrok site thanks!) and gives it to you free of charge. He decided that using compression was a good idea for him to save storage and bandwidth.
> 
> Stockfish is a popular project, with quite a few new versions every week, sometimes several a day. When you do the maths, the storage and bandwidth required are much more than what you think.
> 
> If you don’t like the compressed binaries, I would suggest downloading the sources and compiling yourself. Or maybe even better, running a site equivalent to Abrok, putting only uncompressed binaries for the community. Thanks in advance! :-)
> 
> Stéphane

I understand if he really cares about the bandwidth. But are all binaries permanently preserved? Now with the net built in, storage can be critical even with the compression.

**Comment by Sopel97** [comment]
> "Now with the net built in, storage can be critical even with the compression."

Yes, you're absolutely right. It would be the best if abrok ceased to exist.
