### ISSUE TITLE
NNUE testing on longer TC

### ISSUE THREAD

**Issue by xgfs** [official-stockfish/Stockfish#3085]
Hi all!

I've been conducting some personal testing of NNUE nets, and figures it would be interesting to check how the network performance scales with time. The implicit assumption of Fishtest is that small patches typically have very predictable performance with TC increase. I want to propose that this is not the case for NNUE net updates, so they should be evaluated differently.

In the example below, notice how the latest net 0824-1705 is the best on LTC (not within CF of all nets, but still) while being in the middle, slightly weaker than some older nets.

Results on 300"+5":
```
   # PLAYER                        :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)    W     D    L  D(%)
   1 SF-NNUE-20200824-1705.bin     :    67.5   10.3   594.5    1000    59      86  213   763   24    76
   2 SF-NNUE-20200813-1010.bin     :    59.9    9.8   584.0    1000    58      99  208   752   40    75
   3 SF-NNUE-20200802-2257.bin     :    44.3    9.8   562.5    1000    56      66  162   801   37    80
   4 SF-NNUE-20200805-1512.bin     :    41.5    9.5   558.5    1000    56     100  160   797   43    80
   5 Stockfish 220720 64 POPCNT    :     0.0   ----  1700.5    4000    43     ---  144  3113  743    78
```

Results on 10"+0.1" (some nets omitted, same settings as above besides TC and hash):
```
   # PLAYER                                    :  RATING  ERROR    POINTS  PLAYED   (%)  CFS(%)       W       D       L  D(%)
   1 SF-NNUE-20200813-1010.bin                 :    75.5    5.3    4985.5    8241    60      69    2862    4247    1132    52
   5 SF-NNUE-20200805-1512.bin                 :    71.4    4.8    5995.0   10000    60      87    3389    5212    1399    52
   7 SF-NNUE-20200824-1705.bin                 :    67.6    4.3    7168.0   12062    59      51    3982    6372    1708    53
   8 SF-NNUE-20200802-2257.bin                 :    67.5    4.6    5942.0   10000    59      64    3345    5194    1461    52
  81 Stockfish 220720 64 POPCNT                :     0.0   ----  349918.0  809087    43     100  131152  437532  240403    54
```

I would suggest a more careful evaluation of NN weight update, since they seem to impact the strength of the engine across different time controls in an unpredictable way.

**Comment by Dantist** [comment]
My 2 cents. The number of games is too small to draw accurate conclusions, plus TCs is somewhat hardware-dependent. 
For example, according to your results performance of `SF-NNUE-20200813-1010.bin` on both TCs is as following:

300"+5":
```
ELO: 58.93 ±10.4 (95%)
Total: 1000 W: 208 L: 40 D: 752
```

10"+0.1":
```
ELO: 74.04 ±5.2 (95%)
Total: 8241 W: 2862 L: 1132 D: 4247
```

It may be 69.33 on 300"+5" and 68.84 on 10"+0.1" with 95% confidence :-)

This should be tested on fishtest when the queue is empty (if not tested previously).

**Comment by xgfs** [comment]
You have missed the point. ELO compression is natural with increased TC. The problem is that the strongest STC net is not the strongest LTC net.

**Comment by syzygy1** [comment]
Well, it seems to me that 0824-1705 is the strongest at STC since it was found to be best by fishtest...

**Comment by locutus2** [comment]
I will test the 20200824-1705 net at LTC at fish test so we get a clear picture. After this we can decide what to do.

Here the original STC test: https://tests.stockfishchess.org/tests/view/5f438b275089a564a10d84e7

**Comment by Ipmanchess** [comment]
Have run 7 times 22.000games with different nnue nets.

Lists are updated : [http://ipmanchess.yolasite.com/i9-7980xe.php](url)
For comments,more info : [http://ipmanchess.yolasite.com/testings-i9-7980xe.php](url)
Spreadsheet with results & ongoing tests : [https://docs.google.com/spreadsheets/d/11vXZe4Dm7nIXWIYD9EoZguR4xOuRWUQHpzSfQW2HaMo/edit#gid=1460182227](url)

Now busy with 1705

- 

ENGINE | ELO
-- | --
SFNNUE 190820 avx512 SV2257 | 155.1
SFNNUE x64 flto avx512 SV1010 | 133.3
SFNNUE x64 flto avx512 SV0943 | 120.7
SFNNUE x64 avx512 SV0109 | 113.8
SFNNUE x64 240720 avx2 SV1134 | 79.1
Stockfish nnue.h 150720 avx512 (Gek.27/06) | 53.5
sf-nnue-bmi2-halfkp (Gek. 27/06) | 39.6
Stockfish 11 x64 bmi2 | 0

**Comment by gekkehenker** [comment]
Seems like you were right, but a newer Sergio net has already come to obsolete both. :+1:

**Comment by vondele** [comment]
Thanks, for testing, but given the new net the issue can be closed.

Note that there is a lot of value in doing many games in these tests. Generally I would only trust results if they yield Elo estimates  that are different by more than the two error bars (i.e. non-overlapping confidence intervals).
