### ISSUE TITLE
Embedded doesn't compile with MinGW

### ISSUE THREAD

**Issue by dorzechowski** [official-stockfish/Stockfish#3086]
Windows, MSYS2, MinGW10:

g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2   -c -o evaluate.o evaluate.cpp
/tmp/ccI2eGAQ.s: Assembler messages:
/tmp/ccI2eGAQ.s:6: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccI2eGAQ.s:6: Error: junk at end of line, first unrecognized character is 'g'
/tmp/ccI2eGAQ.s:11: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccI2eGAQ.s:11: Error: junk at end of line, first unrecognized character is 'g'
/tmp/ccI2eGAQ.s:16: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccI2eGAQ.s:16: Error: junk at end of line, first unrecognized character is 'g'
make[1]: *** [<builtin>: evaluate.o] Error 1
make[1]: Leaving directory '/c/git/Stockfish/src'
make: *** [Makefile:716: build] Error 2

No problems compiling with `-DNNUE_EMBEDDING_OFF`. Also, maybe it would be easier to have a separate target for building embedded or at least option `embed=yes` or something like that and leave default build target as it was before (i.e. without embedding).

**Comment by vondele** [comment]
interesting.. any idea what might be different to the setup of the machines on fishtest, for which this works?

**Comment by dorzechowski** [comment]
Really no idea. But fishtest machines are 95% on Linux and those few ones on Windows might have used different compiler. I tried now with just gcc 9.3.0 (so without COMP=mingw on my setup) and got similar error but at linking stage:

g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o evaluate_nnue.o half_kp.o  -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -flto -flto=jobserver -save-temps
stockfish.exe.ltrans0.s: Assembler messages:
stockfish.exe.ltrans0.s:6: Warning: .type pseudo-op used outside of .def/.endef: ignored.
stockfish.exe.ltrans0.s:6: Error: junk at end of line, first unrecognized character is `g'
stockfish.exe.ltrans0.s:11: Warning: .type pseudo-op used outside of .def/.endef: ignored.
stockfish.exe.ltrans0.s:11: Error: junk at end of line, first unrecognized character is `g'
stockfish.exe.ltrans0.s:16: Warning: .type pseudo-op used outside of .def/.endef: ignored.
stockfish.exe.ltrans0.s:16: Error: junk at end of line, first unrecognized character is `g'
make[2]: *** [/tmp/ccYq0BYv.mk:2: stockfish.exe.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:844: stockfish] Error 1
make[1]: Leaving directory '/c/git/Stockfish/src'
make: *** [Makefile:716: build] Error 2

Also files named `-lstdc++.res` and `stockfish.exe.ltrans.out` are left behind after `make clean`.

**Comment by noobpwnftw** [comment]
How about defaulting to not embed nets(especially for fishtest)? Nets are cached anyways, and now we have each cached compile having embedded nets.

**Comment by vondele** [comment]
We might have 50 cached binaries with a net, so about 1Gb. Is that problematic?

**Comment by MichaelB7** [comment]
No issues here with msys2 and gcc 10.2.

**Comment by vondele** [comment]
@dorzechowski is that again an LTO problem on mingw? (i.e. the workaround -save-temps not working?)

**Comment by noobpwnftw** [comment]
@vondele It's not problematic, but it is unnecessary.

**Comment by vondele** [comment]
while, with some coding, we can do something different on fishtest, there is value in having one way of doing things. For example for this issue, we see that at least for some users on fishtest this is just working. Every option to deal with specific requirements makes the whole thing more fragile, exponentially. So, I'm not saying we shouldn't add the code to deal exceptions on fishtest, but I would hope we can minimize the number of special cases.

**Comment by Karma-Tron** [comment]
I use Windows10, MSYS2, MinGW10 as well, and can compile without problems.

**Comment by dorzechowski** [comment]
I don't know how to even debug it. If it works for others, maybe something is messed up in my setup. I will continue to compile for myself without embedding (and I hope this option will never get removed) as it works fine without it.

**Comment by vondele** [comment]
what about adding `-v` to the CXXFLAGS and sharing what version of especially ld you use?

**Comment by vondele** [comment]
the second piece of information will be to add `-fno-lto` after the `-flto=...` flag, or remove that altogether.

**Comment by MichaelB7** [comment]
For those that may not know - the flto flag does work under Msys2 / Mingw64 with gcc 10.2.

**Comment by dorzechowski** [comment]
OK, so my MinGW used gcc 9.3.0, not 10.2.0 as it should. I fixed it and it works now. I used several compilers before when I was working on NNUE branch but any failure with compiling is a bit surprising as it worked fine before 'embedded' patch. Closing this ticket.
