### ISSUE TITLE
Stockfish crashes if bad fen entered

### ISSUE THREAD

**Issue by wickeduk** [official-stockfish/Stockfish#3087]
It probably should ignore a bad FEN gracefully and not crash (uci protocol doesn't allow an error to be returned).

position fen blah
Segmentation fault (core dumped)

**Comment by vondele** [comment]
That's a common question so we have an FAQ on that https://github.com/glinscott/fishtest/wiki/Fishtest-faq#why-sf-crashes-on-incorrect-fen
