### ISSUE TITLE
"bench" command with NNUE and Classic is both wrong, getting wrong "bench" and "nodes searched", impossible to select mode

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#3089]
Downloaded latest build from Abrok, for benchmarking, but I am unable to get the right results:
According to Abrok, Date: Sun Aug 30 14:22:07 2020 +0200, after commit  "Update parametes in classical evaluation."

I expect to get this bench, with both classic and NNUE evaluation:
bench: 3736029

In reality I cannot reproduce this number:
Actual results:
1st run:
stockfish_20083014_x64.exe bench 16 1 13 default depth classical

Total time (ms) : 10328
Nodes searched  : 4138101
Nodes/second    : 400668

2nd run:
stockfish_20083014_x64.exe bench 16 1 13 default depth nnue

Total time (ms) : 28342
Nodes searched  : 3666857 (wrong!)
Nodes/second    : 129378

3rd run:
stockfish_20083014_x64.exe bench

Total time (ms) : 13290
Nodes searched  : 3736029
Nodes/second    : 281115

4th run:
stockfish_20083014_x64.exe bench 16 1 13 default depth mixed
Total time (ms) : 13713
Nodes searched  : 3736029
Nodes/second    : 272444

Only on the 3rd run I could reproduce those numbers, but then I have no idea if classic or NNUE is active.
And I need to control classic or NNUE. There must be some parameter to run benchmark with default everything but change classic or NNUE.

UPDATE: ok, seems that 4th run works ! "mixed" mode.
Just needs some documentation lads !

-Alexey E. 01.09.2020

**Comment by syzygy1** [comment]
The reported bench has always been the bench reported by "bench".

**Comment by vondele** [comment]
stockfish_20083014_x64.exe bench 
or the specific command 
stockfish_20083014_x64.exe bench 16 1 13 default depth mixed
give the precise number.
