### ISSUE TITLE
Please add --help parameter, as most CLI programs do

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#3090]
Most CLI programs have some kind of built-in help, esp useful for tricky commands such as "bench" with a ton of parameters.

C:\GAMES\Chessmaster\engines\Stockfish12>stockfish_20083014_x64.exe --help
Stockfish 300820 by the Stockfish developers (see AUTHORS file)
Unknown command: --help

Please add this CLI help to Stockfish.

**Comment by vondele** [comment]
We have now documented a bit better that Stockfish implements the UCI protocol and documented the non-standard commands. 

https://github.com/official-stockfish/Stockfish#the-uci-protocol-and-available-options

**Comment by kdave** [comment]
The documentation update is certainly useful, but I think the point of the issue/request is to print something ready to use or for quick reference. The command line arguments are passed to the UCI parser and the first one is executed, so I think the only relevant commands are `bench`, `uci` or `export_net`. Any other would need more commands to eg. set up position and evaluate.

I don't have a concrete proposal for the help text, suggestions welcome, the following code adds the place where to add it once it's settled. A PR can follow.

```
--- a/src/uci.cpp
+++ b/src/uci.cpp
@@ -221,6 +221,10 @@ namespace {
 
 } // namespace
 
+static void print_help(void)
+{
+    sync_cout << "YO HELP" << sync_endl;
+}
 
 /// UCI::loop() waits for a command from stdin, parses it and calls the appropriate
 /// function. Also intercepts EOF from stdin to ensure gracefully exiting if the
@@ -239,6 +243,11 @@ void UCI::loop(int argc, char* argv[]) {
   for (int i = 1; i < argc; ++i)
       cmd += std::string(argv[i]) + " ";
 
+  if (argc == 2 && std::string(argv[1]) == "--help") {
+      print_help();
+      return;
+  }
+
   do {
       if (argc == 1 && !getline(cin, cmd)) // Block here waiting for input or EOF
           cmd = "quit";
```

**Comment by vondele** [comment]
yes, both 'help' and '--help' can be passed on the command line.
