### ISSUE TITLE
UCI_Elo on Stockfish 12 

### ISSUE THREAD

**Issue by yuribudilov** [official-stockfish/Stockfish#3101]
Hello

Question re this Doc: (and request to update doc with more information)

UCI_Elo

If enabled by UCI_LimitStrength, aim for an engine strength of the given Elo. 
This Elo rating has been calibrated at a time control of 60s+0.6s and anchored to CCRL 40/4.

----
Questions (and request to update docs):
Q1. How many CPU Threads would this calibration use? 1 CPU Thread? 
Q2. Would this calibration use new NNUE or Classical or perhaps this is same ELO regardless of NNUE? 

Many thanks!

**Comment by vondele** [comment]
Q1 -> 1
Q2 -> the Elo was valid at the point of calibration. Probably this has changed a bit now.
