### ISSUE TITLE
UCI info messages repeated and in wrong place/sequence

### ISSUE THREAD

**Issue by tzipproth** [official-stockfish/Stockfish#3111]
When manually entering this sequence in the SF commandline as a whole block:

setoption name Debug Log File value log.txt
uci
setoption name Contempt value 0
setoption name Hash value 2048
setoption name Threads value 1
setoption name EvalFile value D:\nnue\20200814-1035.bin
setoption name SyzygyPath value D:\\syzygy345
isready
setoption name Clear Hash
go infinite

the UCI output and log file from Stockfish contains repetitions of some info messages, partially also in the wrong place:
(Sending it from a program/GUI gives the same results)

>> uci
<< id name Stockfish 040920
<< id author the Stockfish developers (see AUTHORS file)
<< 
<< option name Debug Log File type string default 
<< option name Contempt type spin default 24 min -100 max 100
...... (List shortened)
<< option name Use NNUE type check default true
<< option name EvalFile type string default nn-308d71810dff.nnue
<< uciok
>> setoption name Contempt value 0
>> setoption name Hash value 2048
**<< info string Hash table allocation: Windows large pages used.**
>> setoption name Threads value 1
**<< info string Hash table allocation: Windows large pages used.   <----- repetition, wrong place**
>> setoption name EvalFile value D:\nnue\20200814-1035.bin
>> setoption name SyzygyPath value D:\\syzygy345
**<< info string Found 203 tablebases**
>> isready
<< readyok
>> setoption name Clear Hash
**<< info string Found 203 tablebases       <----- repetition, wrong place**
>> go infinite
**<< info string NNUE evaluation using D:\nnue\20200814-1035.bin enabled     <----- wrong place**
<< info depth 1 seldepth 1 multipv 1 score cp 8 nodes 20 nps 5000 tbhits 0 time 4 pv d2d4
<< info depth 2 seldepth 2 multipv 1 score cp 54 nodes 42 nps 6000 tbhits 0 time 7 pv d2d4 a7a6

...
stop
go infinite
**<< info string NNUE evaluation using D:\nnue\20200814-1035.bin enabled    <----- repetition**
<< info depth 1 seldepth 1 multipv 1 score cp 8 nodes 20 nps 5000 tbhits 0 time 4 pv d2d4
...

After a "stop" command and following "go infinite",
the message 
**info string NNUE evaluation using D:\nnue\20200814-1035.bin enabled**
is repeated every time after "go infinite"

**Comment by vondele** [comment]
in prints the info messages when the hashtable is reallocated / tbs are reloaded in the code. The output is consistent with the implementation.

**Comment by tzipproth** [comment]
I was irritated from the repetition of "info string Found 203 tablebases" after the "Clear Hash" command, and from the repetion of "info string NNUE evaluation using D:\nnue\20200814-1035.bin enabled" after every "go infinite", which leads to an endless accumulation of info messages per position in the GUI I use, but it may be a bug in this private GUI. 

So if the info messages are correct and in the right place/sequence, this issue can be closed or deleted (sry, I was sure that this must be an error).

**Comment by vondele** [comment]
At least the messages are there on purpose.
