### ISSUE TITLE
"bench" changes the default program state

### ISSUE THREAD

**Issue by gcp** [official-stockfish/Stockfish#3112]
If you run "bench" before doing normal operations, the default program state will have changed compared to a normal startup: NNUE will be disabled because the last bench position runs without NNUE.

This seems potentially error-prone.

**Comment by vondele** [comment]
I agree that's happening, but it isn't new, i.e. bench is a shortcut setting various state (threads, Hash), and now also 'Use NNUE'. The latter one is more visible, I agree, but also the former matter. Would one record the state before bench, and restore to that, or restore to before, or just leave the state as implied by bench?

**Comment by gcp** [comment]
I can see that if you set state, and do "bench", there's an argument the state before bench should be restored, which is obviously more work for no obvious gain.

A further complication is that UCI interfaces are expected to know about Hash and things like that, but not "NNUE Enabled", so you could argue that only these nonstandard settings should be restored, as the interface can presumably know it should set the others appropriately. But unfortunately,  "Threads" isn't in the UCI specification so strictly speaking this argument doesn't work. It's so commonly supported though, that it might as well be.

Based on the latter, I think there's a good argument to restore any non-UCI-standard settings (but not Threads, see above) to the defaults after bench. Which is likely only NNUE right now?

This is obviously a judgement call.

**Comment by vondele** [comment]
I can see last point, and there is some precedent in that UCI_Chess960 is restored to the default as the last thing after testing it. 
I could agree with setting it back to the default, after having gone through the list of fens, so that at least the state doesn't depend on the number of positions in the fens file. You mind making a PR with that? (1-liner in benchmark.cpp near line 166).

**Comment by gcp** [comment]
Here's a nice example of where things can go wrong:

```
bench
uci
```

Stockfish now claims NNUE is enabled, but it isn't.

**Comment by vondele** [comment]
uci lists defaults?

**Comment by gcp** [comment]
I would assume that if UCI lists a setting as default, and it's what you want, you don't change it.
