### ISSUE TITLE
Problem compilation Stockfish 12 in Xcode

### ISSUE THREAD

**Issue by GiordanoVicoli** [official-stockfish/Stockfish#3115]
Hi,

Some time ago I tried to include SF 12 beta in my application developed with Xcode and all was working.
Now I tried with the final release and I have some problems with incbin.h. I have the following error during compilation:`<inline asm>`. What does it mean?

Thanks and regards,
Giordano

**Comment by snicolet** [comment]
What error, exactly?

**Comment by GiordanoVicoli** [comment]
this:  <inline asm> without explanation

But just now I have solved disabling incbin.h and it works. But I would like to now if I miss something disabling incbin.h

**Comment by snicolet** [comment]
I would be difficult for us to tell, without seeing the source code of your application. Can you please show us?

**Comment by GiordanoVicoli** [comment]
This is the error I have during compilation:

Inline Assembly Issue Group

/<inline asm>:5:9: Could not find incbin file 'nn-82215d0fd0df.nnue'

The code is Stockfish 12 code without changing. It is only compiled inside Xcode.

**Comment by vondele** [comment]
so did you download the net 'nn-82215d0fd0df.nnue' and put it in the source tree? https://tests.stockfishchess.org/nns

**Comment by GiordanoVicoli** [comment]
Yes, obviously, I already did when I tested the beta version.

However this is the piece of code I modified and now it is working;

#if !defined(_MSC_VER) && !defined(NNUE_EMBEDDING_OFF)
  //INCBIN(EmbeddedNNUE, EvalFileDefaultName);
  const unsigned char        gEmbeddedNNUEData[1] = {0x0};
  const unsigned char *const gEmbeddedNNUEEnd = &gEmbeddedNNUEData[1];
  const unsigned int         gEmbeddedNNUESize = 1;
#else
  const unsigned char        gEmbeddedNNUEData[1] = {0x0};
  const unsigned char *const gEmbeddedNNUEEnd = &gEmbeddedNNUEData[1];
  const unsigned int         gEmbeddedNNUESize = 1;
#endif

I commented INCBIN and copied the code inside #else under #if.
In this way Stockfish 12 works but it load the net without INCBIN. Is it the same?

**Comment by vondele** [comment]
you need to fix you build process, rather than the hack? It just doesn't find the file at compilation time.
It is also not functionally the same... 
However, if you don't need the functionality, you could just add '-DNNUE_EMBEDDING_OFF' to your CXXFLAGS instead of the source modification.

**Comment by GiordanoVicoli** [comment]
Ok, it works, I added the compiler flag for the file evaluate.cpp.

But which is the real advantage in the use of incbin?

**Comment by vondele** [comment]
https://github.com/official-stockfish/Stockfish/commit/406979ea12ee7828e079871b0f9f3dc8f127a741

so not a stockfish issue, I guess.
