### ISSUE TITLE
Suggestion: Adding FEN in Bench Output

### ISSUE THREAD

**Issue by GoldenRare** [official-stockfish/Stockfish#3117]
Not sure if anyone else has felt the same way or even if it is worth the extra time investment to Bench, but would adding the FEN string to the output of Bench be beneficial.  For example, instead of 
```
Position: 25/47
info string classical evaluation enabled
info depth 1 ...
``` 
to something along the lines of 
```
Position: 25/47 (8/3p4/p1bk3p/Pp6/1Kp1PpPp/2P2P1P/2P5/5B2 b - - 0 1)
info string classical evaluation enabled
info depth 1 ...
``` 
since I found myself sometimes wanting to know which position exactly is being benched without the hassle of miscounting the 47 positions in Defaults.

**Comment by snicolet** [comment]
Why not? 
I don’t think there are any scripts that rely on the current behavior

**Comment by ddugovic** [comment]
I agree this information would be nice to have although I'm not sure the `()` characters make it easier to read (than without them).
