### ISSUE TITLE
Feature Request : run in fixed time

### ISSUE THREAD

**Issue by KurCan6** [official-stockfish/Stockfish#3120]
hello , my problem is engine keep running infinitive time in kbitzing , this is bad for laptop battery, it would be nice to implement option for a fixed time running,

to make myself clearly for example, in chessbase when analyzing/kibitzing a game I want it to stop by itself after 20 sec , that is enough for me,bu it keeps calculating.. instead of stoppping manually it would be nice to stop it after in a fixed time or fixed depth

i can do it in a chess software which name is kvetka, by adding command movetime 5000 ( 5 sec ) but in chessbase i cant do it

**Comment by Alayan-stk-2** [comment]
That's a chessbase issue, not a Stockfish issue.

**Comment by MichaelB7** [comment]
Clearly a ChessBase issue , since the command is there for them to use and the fact that one GUI has figured that out.  The “feature” is already there.

**Comment by vondele** [comment]
Indeed, a GUI issue, since the movetime command supports that.
