### ISSUE TITLE
Stockfish starts the analysis every time after 2.5 seconds BUG

### ISSUE THREAD

**Issue by lex312** [official-stockfish/Stockfish#3125]
For example when I run some test suites using the Fritz gui, Stockfish starts the analysis with every new position, after 2.5 seconds.
Why this is happening?
Other engines starts the analysis instantly.

I have 64 GB RAM.
When I use LC0 and 32 GB RAM, the analysis starts every time instantly.
When I use Cfish and 32 GB RAM, the analysis starts every time after 1.5 seconds.
When I use Stockfish (12 or dev.) and 32 GB RAM, the analysis starts every time after 2.5 seconds.

Why Cfish is with 32 GB RAM every time 1 second faster than Stockfish?
Why LC0 is with 32 GB RAM every time 2.5 seconds faster than Stockfish?
What does it mean and how can it be improved or fixed?

**Comment by vondele** [comment]
probably your GUI sends the Threads, Hash, or Clear Hash UCI option before each new position, and the hash is reallocated and/or zeroed?

**Comment by syzygy1** [comment]
He is using a 32GB hash table for 1-second searches. I already told him to use 16MB and certainly not more than 64MB.

**Comment by syzygy1** [comment]
And LC0 apparently doesn't clear the hash table on ucinewgame (is my guess).

**Comment by lex312** [comment]
But maybe there is something to improve. 
Why Stockfish needs 1 second more than Cfish when both use 32 GB RAM? It‘s more or less the same fish.
And why Stockfish needs up to 2.5 seconds more than other Engines and shouldn‘t it be fixed?

Should I do a logfile?

**Comment by lex312** [comment]
With 1 second and with 4 seconds per move:
[logfile.txt](https://github.com/official-stockfish/Stockfish/files/5248046/logfile.txt)

**Comment by Matthies** [comment]
Seems that SF is initializing the tablebases at every ucinewgame which may take some time depending on the storage. Is this really needed?

**Comment by vondele** [comment]
kind of needed, was added to fix a problem where the OS would not 'free' the files that are mmap'ed, unless done by hand. 

There is basically no need to issue an ucinewgame before analysis of each new position.

**Comment by syzygy1** [comment]
It wouldn't be necessary to rescan the TB folders, but I don't think that takes any noticeable time. Clearing the hash table could be sped up a bit by doing it multithreaded (as in Cfish), but it's not really worth the trouble (unless it is done anyway for NUMA-related reasons).

It seems that the Fritz GUI issues a ucinewgame before each position in a test suite (let's hope it's not doing that during game play). But the TT clearing delay can be avoided by setting the hashtable to a reasonable size. For a 1-hour search that does benefit from a 32 GB hash table, the few seconds of delay don't matter. So in my humble opinion there is no bug and not even an issue.

**Comment by vondele** [comment]
Actually hash is cleared multi-threaded already.

**Comment by lex312** [comment]
I tried a match Stockfish vs LC0.
+4 seconds per move
Looks like the Fritz GUI gives always +10 seconds to both when a match starts. = (+14 seconds)
Stockfish wasn't ready to move and lost.

Logfile Stockfish:
[logfile.txt](https://github.com/official-stockfish/Stockfish/files/5251651/logfile.txt)

Logfile LC0:
[logfile2.txt](https://github.com/official-stockfish/Stockfish/files/5251650/logfile2.txt)

**Comment by syzygy1** [comment]
@vondele You're right. Then they must be equally fast already.

**Comment by lex312** [comment]
I tried a second match Stockfish vs LC0.
+20 seconds per move.
Stockfish wasn't ready to move and lost.
Stockfish started to calculate after 19 seconds, when I saw it correctly.

Logfile Stockfish:
[logfile.txt](https://github.com/official-stockfish/Stockfish/files/5251657/logfile.txt)

**Comment by lex312** [comment]
I tried a third match Stockfish vs LC0.
+30 seconds per move.
Stockfish started to calculate after 19 seconds, when I saw it correctly.

Logfile Stockfish:
[logfile.txt](https://github.com/official-stockfish/Stockfish/files/5251669/logfile.txt)

**Comment by syzygy1** [comment]
If this were a problem with Stockfish, it would have been fixed a long time ago. You can ask Chessbase for help with Fritz.

**Comment by vondele** [comment]
I agree, will close now.

**Comment by MichaelB7** [comment]
@lex312 can you share more info about your Hardware and OS - Windows Version  -  total Ram , CPU type and whether you are using HD or SSD. Your log file indicates something is amiss as your nps is really low for using 8 threads.  Your hash full is at 29 after 29 seconds - that is too low.  Generally speaking , ideal hashfull would be at about 650 at the time the move is made.

**Comment by lex312** [comment]
> @lex312 can you share more info about your Hardware and OS - Windows Version - total Ram , CPU type and whether you are using HD or SSD. Your log file indicates something is amiss as your nps is really low for using 8 threads. Your hash full is at 29 after 29 seconds - that is too low. Generally speaking , ideal hashfull would be at about 650 at the time the move is made.

Windows 8.1
CPU: i7 3930k
64 GB RAM
SSD of course
2x RTX 2080 ti
Power supply: Corsair AX1600i
