### ISSUE TITLE
Blunder late game in 8 piece ending

### ISSUE THREAD

**Issue by tdh1967** [official-stockfish/Stockfish#3134]
I had read on the discord that someone there had experienced StockFish (release just prior to today, Sept. 17) had lost in drawn endgame. 
In an overnight match, my Sept. 8 release of Stockfish lost one game and it was in a drawn 8 piece ending.  I have 8 GB RAM and was using 1.5MB for hash.  I also have six-man syzygy database. I was running the latest default net in SF. 

The game is below. If this is just a matter of not going deep enough, is it possible the net is just slowing it down too much for this time control on my machine?  It appears it only went 8 ply but I cannot see this being too fast of a time control in this position for SF even on this older machine.  

The losing move is 89.......Rh3+

[Event "DESKTOP-4PV8R7E, Blitz 1m+3s"]
[Site "DESKTOP-4PV8R7E"]
[Date "2020.09.16"]
[Round "1"]
[White "New Engine"]
[Black "Stockfish 080920"]
[Result "1-0"]
[ECO "C26"]
[Annotator "-0.22;-0.33"]
[PlyCount "185"]
[TimeControl "60+3"]

{Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz 2394 MHz W=19.7 plies; 1,043kN/s;
109,052 TBAs B=20.0 plies; 1,153kN/s; 113,683 TBAs; Goi.ctg} 1. Nc3 {0.01/0 2
White last book move} Nf6 {B 0} 2. e4 {0.01/0 1} e5 {B 0} 3. Bd3 {0.01/0 1} Bc5
{B 0} 4. Nf3 {0.01/0 1} O-O {B 0} 5. Bc4 {0.01/0 1} d6 {B 0} 6. O-O {0.01/0 1}
Re8 {B 0 Black last book move} 7. a4 {-0.22/29 22} c6 {-0.33/27 21} 8. d3 {
-0.32/24 5} h6 {-0.22/24 2} 9. h3 {-0.32/24 5} Bb6 {-0.16/25 10 (Nbd7)} 10. Re1
{-0.25/26 10} a5 {-0.15/25 8} 11. Bd2 {-0.20/26 8 (Ba2)} Bc5 {-0.21/25 6} 12.
Re2 {-0.13/25 3} Nbd7 {-0.25/24 6 (Be6)} 13. Be3 {-0.15/25 2} b6 {-0.21/23 2}
14. d4 {-0.11/26 7} Bb4 {-0.33/22 3} 15. Bd3 {-0.23/25 5 (Nd2)} exd4 {-0.28/26
7 (Bb7)} 16. Bxd4 {-0.33/24 4} Ne5 {-0.24/27 9 (Nc5)} 17. Nxe5 {-0.24/25 3}
dxe5 {-0.25/28 2} 18. Be3 {-0.37/27 2} Be6 {-0.34/28 6} 19. Rd2 {-0.45/26 3}
Nd7 {-0.26/27 2} 20. Bc4 {-0.21/28 6} Bxc4 {-0.25/27 3} 21. Rxd7 {-0.11/26 1}
Qb8 {-0.16/29 3} 22. Qh5 {-0.10/30 3} Be6 {-0.09/29 6 (Re7)} 23. Rd3 {-0.10/31
2} Bc4 {-0.09/28 2} 24. Rd7 {-0.10/34 2} Bxc3 {-0.25/32 8 (Re7)} 25. bxc3 {
0.00/27 2} Ra7 {-0.21/29 2} 26. Rd2 {-0.19/28 8} Rae7 {-0.32/30 3} 27. Rad1 {
-0.15/25 2} Re6 {-0.33/28 3} 28. Kh2 {-0.21/27 2} c5 {-0.17/28 4} 29. g4 {
0.00/29 9 (f3)} Qa8 {0.00/27 7} 30. g5 {0.00/23 2 (f3)} Qxe4 {-0.28/28 3} 31.
gxh6 {-0.03/25 5} Rg6 {-0.30/27 2} 32. Rg1 {-0.06/24 4} Rxg1 {-0.20/28 3 (Bd5)}
33. Kxg1 {-0.18/25 4} g6 {-0.28/31 2} 34. Qg4 {-0.31/27 5} Bd5 {-0.25/25 2} 35.
Qxe4 {-0.23/26 4} Bxe4 {-0.16/24 3} 36. Rd6 {-0.19/22 2} Bxc2 {-0.23/26 6} 37.
Rxb6 {-0.19/24 3} Ra8 {-0.23/27 2} 38. Bxc5 {-0.12/22 2} Bxa4 {-0.20/25 3} 39.
Rb7 {-0.14/23 4} Bc2 {-0.24/27 5} 40. h7+ {-0.13/22 4} Kg7 {-0.24/24 2} 41. Bd6
{-0.20/23 3} a4 {-0.24/24 2} 42. Bxe5+ {-0.22/24 9} Kxh7 {-0.32/24 2} 43. c4 {
-0.22/23 2} a3 {-0.26/23 3} 44. Rxf7+ {-0.20/22 2} Kg8 {-0.25/23 4} 45. Rg7+ {
-0.19/24 5} Kf8 {-0.22/21 3} 46. Kh2 {-0.21/22 4 (Ba1)} Ra5 {-0.26/23 3 (a2)}
47. Ba1 {-0.17/23 10} a2 {-0.21/20 4} 48. h4 {-0.23/20 2} Ke8 {-0.26/20 5} 49.
Kg3 {-0.22/19 3} Kd8 {-0.18/35 7 (Bd3)} 50. Rb7 {-0.18/16 1 (Kf4)} Bd3 {
-0.26/17 4} 51. Rb5 {-0.23/16 3} Ra3 {-0.25/15 2} 52. Rc5 {-0.26/16 9 (Rd5+)}
Bxc4+ {-0.20/16 9} 53. Kg4 {-0.15/15 1} Bd3 {-0.20/14 3} 54. f3 {-0.06/13 1 
(Kg5)} Bf5+ {-0.20/13 5 (Ke7)} 55. Kg5 {-0.17/14 2 (Kg3)} Bb1 {-0.26/12 2} 56.
Kg4 {-0.23/14 4} Bf5+ {-0.20/13 3 (Rd3)} 57. Kf4 {-0.16/15 1} Ra4+ {-0.22/15 2
(Bb1)} 58. Kg5 {-0.13/17 1} Bb1 {-0.21/17 2} 59. h5 {-0.21/16 2} gxh5 {-0.19/
19 3} 60. Kxh5 {-0.22/16 2} Rf4 {-0.23/19 2} 61. Rc3 {-0.23/15 1} Kd7 {-0.20/
16 2} 62. Kg5 {-0.23/15 5} Rf5+ {-0.21/21 5} 63. Kg4 {-0.20/16 4} Rb5 {-0.19/
15 4 (Ra5)} 64. Kf4 {-0.15/20 3} Bh7 {-0.13/14 5 (Bf5)} 65. Ra3 {-0.21/13 3}
Bg8 {-0.24/13 1} 66. Bd4 {-0.27/12 3 (Ke4)} Bc4 {-0.15/13 11 (Rb1)} 67. Ra4 {
-0.13/16 4 (Ke4)} Bb3 {-0.05/13 4} 68. Ra6 {-0.10/12 1} Kc7 {-0.04/13 0 (Rh5)}
69. Ke3 {-0.14/13 2} Bc4 {-0.08/13 4 (Rh5)} 70. Ra4 {-0.13/14 3} Bb3 {-0.04/13
1} 71. Ra6 {-0.12/13 3 (Ra3)} Kb7 {-0.13/14 5 (Kb8)} 72. Ra3 {-0.15/14 5 (Ra7+)
} Bg8 {-0.12/14 2 (Bc4)} 73. Ra7+ {-0.19/12 1} Kb8 {-0.10/17 1} 74. f4 {
-0.11/15 4 (Ra6)} Rh5 {-0.10/12 2} 75. Kd2 {0.00/11 2 (Ra6)} Bd5 {-0.09/11 4 
(Rh2+)} 76. Ke3 {-0.06/14 5 (Kc2)} Rh3+ {-0.14/12 3} 77. Kd2 {-0.06/17 1} Bg8 {
-0.10/13 7} 78. f5 {0.00/16 7 (Kc2)} Bc4 {0.00/11 1} 79. Kc2 {-0.03/14 1} Rh2+
{-0.13/12 4 (Rh4)} 80. Kc3 {0.00/13 2} Bd5 {-0.06/12 1 (Bg8)} 81. f6 {0.00/14
4 (Ra5)} Rh4 {-0.05/12 2} 82. Ra5 {0.00/17 8} Kb7 {0.00/15 5} 83. Kd3 {0.00/15
1} Kc6 {0.00/15 3} 84. Rc5+ {0.00/12 2} Kd6 {0.00/16 6} 85. Ra5 {0.00/14 2} Bb3
{0.00/13 2} 86. Ke3 {0.00/14 2 (Kc3)} Kc6 {0.00/13 1} 87. Ra6+ {0.00/17 1 
(Rc5+)} Kb5 {-0.05/11 1 (Kd7)} 88. Rb6+ {0.00/18 2} Kc4 {0.00/12 1 (Ka5)} 89.
f7 {0.00/11 4 (Bb2)} Rh3+ {0.00/8 4} 90. Kf2 {4.98/13 5 (Kf4)} Rh2+ {9.42/9 10
(Kxd4)} 91. Kg3 {10.88/11 4} Rh8 {40.49/10 5 (Rh1)} 92. Bxh8 {100.00/10 1} Kd3
{152.64/12 2 (Bd1)} 93. Rxb3+ {100.00/13 1} 1-0

**Comment by Sopel97** [comment]
this depth looks like you don't have the syzygi on SSD

**Comment by MichaelB7** [comment]
With a three second increment , depth should be way higher - the most common reason for such low depth is that the machine was running low on memory and it was swapping to the disk or the syzygy tbs were on HDD and ponder was on. Anyway , for whatever reason , the depth is too low in an unnatural manner - something went wrong. It is not a bug. Either user  error or computer  malfunction.

**Comment by tdh1967** [comment]
They databases are on C: drive but no, I don't have have an SSD drive.  Maybe nothing is out of the ordinary under the circumstances but I never saw this shallow of depth in games this speed before NNUE.  It may just be this machine is too ancient to run SF with NNUE and 6 man syzygy this fast and not have this happen from time to time.  I don't remember this ever happening prior to NNUE.

**Comment by vondele** [comment]
I also believe this is a local issue, and the low depth is the reason, probably caused by something else (also possible: other processes, such as windows update, running at the same time). Almost certainly not due to NNUE.

**Comment by tdh1967** [comment]
Thank for the responses.  I'll make changes to cut down on disk I/O. Ponder was off but on this old machine, any processes in background can bog it down apparently.  I don't know what they were but I will eliminate for the future until I get a newer computer.

Thanks again.
