### ISSUE TITLE
Linux significantly stronger than Windows?

### ISSUE THREAD

**Issue by Torom** [official-stockfish/Stockfish#3135]
Hi,

I did a few tests and wanted to ask if the results were as expected. I used the latest development builds from [here](https://abrok.eu/stockfish/). I ran bench first directly on Windows, than with the Linux binary in WSL 2 and lastly directly on Linux. I used the bmi2 build for my Skylake Intel i7 6700K.

Windows 10:

```
.\stockfish_20091717_x64_bmi2.exe bench

...

===========================
Total time (ms) : 2531
Nodes searched  : 3856086
Nodes/second    : 1523542
```

WSL 2 Ubuntu 20.04:

```
$ ./stockfish_20091717_x64_bmi2 bench

...

===========================
Total time (ms) : 1999
Nodes searched  : 3856086
Nodes/second    : 1929007
```

Linux Manjaro:
```

$ ./stockfish_20091717_x64_bmi2 bench

...

===========================
Total time (ms) : 1859
Nodes searched  : 3856086
Nodes/second    : 2074279
```

I´m pretty suprised that WSL 2 is faster than the native Windows binary, as it is just a virtualized Linux kernel for Windows. Are these results as expected?

**Comment by MichaelB7** [comment]
Yes it is.  If you set Linux to use HugePages , it will be even faster.

**Comment by vondele** [comment]
I would say the difference is larger than it should be, I believe abrok uses an older compiler to cross-compile from linux to windows. If one builds the code from sources on windows with a modern toolchain the difference should be much smaller (https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows)

**Comment by Torom** [comment]
> 
> 
> Yes it is. If you set Linux to use HugePages , it will be even faster.

Large Pages on Windows should be enabled. And Huge Pages on Linux should be enabled by default? I followed [this](https://github.com/official-stockfish/Stockfish#large-pages).


> 
> 
> I would say the difference is larger than it should be, I believe abrok uses an older compiler to cross-compile from linux to windows. If one builds the code from sources on windows with a modern toolchain the difference should be much smaller (https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows)

No it didn´t change much:

```
.\stockfish_x86-64-bmi2.exe compiler

Compiled by g++ (GNUC) 10.2.0 on MinGW64
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 10.2.0
```
```

.\stockfish_x86-64-bmi2.exe bench

...

===========================
Total time (ms) : 2516
Nodes searched  : 3856086
Nodes/second    : 1532625
```

**Comment by vondele** [comment]
Interesting.. Did you do a profile-build  `make clean && make -j ARCH=x86-64-bmi2 profile-build ... ` ?

**Comment by Torom** [comment]
> 
> 
> Interesting.. Did you do a profile-build `make clean && make -j ARCH=x86-64-bmi2 profile-build ... ` ?

Ehm, not sure, I used [this script](https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows#building-stockfish). Can you tell me how to do it properly?

**Comment by vondele** [comment]
that's a profile-build ... so, yes a large difference remains.

**Comment by gvreuls** [comment]
Windows console output is notoriously slow, how do times between Windows and Linux match up if you do
``.\stockfish.exe bench > NUL`` on Windows and
``./stockfish bench > /dev/null`` on Linux?

**Comment by Torom** [comment]
> Windows console output is notoriously slow, how do times between Windows and Linux match up if you do
> `.\stockfish.exe bench > NUL` on Windows and
> `./stockfish bench > /dev/null` on Linux?

That helped a bit. Btw, Large Pages on Windows is enabled. Is there a info string for Huge Pages on Linux, too?

Windows 10:

```
> .\stockfish_x86-64-bmi2.exe bench | Out-Null

...

===========================
Total time (ms) : 2050
Nodes searched  : 3856086
Nodes/second    : 1881017
```

WSL 2 Ubuntu 20.04:

```
$ ./stockfish_20091717_x64_bmi2 bench > /dev/null

...

===========================
Total time (ms) : 1864
Nodes searched  : 3856086
Nodes/second    : 2068715
```

Linux Manjaro:

```
$ ./stockfish_20091717_x64_bmi2 bench > /dev/null

...

===========================
Total time (ms) : 1792
Nodes searched  : 3856086
Nodes/second    : 2151833
```

**Comment by vondele** [comment]
Linux huge pages have no info string, it depends on the kernel settings, typically they are available
```
cat cat /sys/kernel/mm/transparent_hugepage/enabled
```
should be always or madvise.

**Comment by Torom** [comment]
Excuse me, but I have one more question. I have found out that my self compiled version is slower then the abrok version. Then I checked the compiler outputs:

self compiled:

```
> .\stockfish_x86-64-bmi2.exe compiler
Stockfish 240920 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 10.2.0 on MinGW64
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 10.2.0
```

abrok:

```
> .\stockfish_20092110_x64_bmi2.exe compiler
Stockfish 210920 by the Stockfish developers (see AUTHORS file)
info string Hash table allocation: Windows large pages used.

Compiled by g++ (GNUC) 7.3.0 on MinGW64
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 7.3-posix 20180312
```

Does this mean that my self compiled version isn't using large pages? But why?

**Comment by vondele** [comment]
interesting, not sure why it is not printing that line.

**Comment by Torom** [comment]
It looks like it is not only the line that is not printed.

self compiled:

```
> .\stockfish_x86-64-bmi2.exe bench | Out-Null

...

===========================
Total time (ms) : 2020
Nodes searched  : 3856086
Nodes/second    : 1908953
```

abrok:

```
> .\stockfish_20092110_x64_bmi2.exe bench | Out-Null

...

===========================
Total time (ms) : 1927
Nodes searched  : 3973739
Nodes/second    : 2062137
```

**Comment by syzygy1** [comment]
So you shouldn't try to compare two different versions.
The info string line is no longer printed since a patch of "Sep 25, 2020" but if we take into account time zones that may have been Sep 24, 2020 for you.
NNUE weights are in large pages since a patch of "Sep 21, 2020", which explains the 22 MB difference.

In general, basically any change in Stockfish can have a big effect on bench nps.

**Comment by syzygy1** [comment]
Hmmm, the older abrok version should be using 16 MB and your newer self-compiled version should be using 38 MB. I am guessing you erroneously switched them when writing your comment.

**Comment by Torom** [comment]
You're right. I don't switched them when writing the comment, but I failed to compile a new version. For some reason Unzip did not overwrite the source files. Both versions now use 38 MB of large pages. The performance still differs by about 2-3 %.
Thanks for your help.

self compiled:

```
> .\stockfish_x86-64-bmi2.exe compiler
Stockfish 270920 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 10.2.0 on MinGW64
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 10.2.0

> .\stockfish_x86-64-bmi2.exe bench | Out-Null

...

===========================
Total time (ms) : 2034
Nodes searched  : 3943952
Nodes/second    : 1939012
```

abrok:

```
> .\stockfish_20092708_x64_bmi2.exe compiler
Stockfish 270920 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 7.3.0 on MinGW64
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 7.3-posix 20180312

> .\stockfish_20092708_x64_bmi2.exe bench | Out-Null

...

===========================
Total time (ms) : 1975
Nodes searched  : 3943952
Nodes/second    : 1996937
```
