### ISSUE TITLE
Idea: Principal Component Analysis

### ISSUE THREAD

**Issue by jtseng20** [official-stockfish/Stockfish#3136]
Hi all,

I have an idea about using Principal Component analysis to reduce the dimensionality of the NNUE input space. 

For those not immediately familiar with PCA, the central idea is to attempt to express complicated, _n_ dimension datasets by transforming the basis vectors such that only the first _k_/_n_ of them alone are enough to represent the vast majority of the variance in the original dataset.

The current state of things is that the NNUE inputs are extremely bloated, and very probably extremely redundant. I believe that there is potential room for growth both in training and gameplay implementation if the dimensionality of the input space could be diminished from 40-some thousand to a few hundred. A reduction in dimensionality would at the very least provide: a smaller network, and interesting ideas for how to train them (reduce, train, expand? or vice versa). The incremental nature of current NNUE probably makes it such that a smaller network would not much improve play speed, but training is where the potential lies, I think.

Are there any devs who are interested in this idea?

**Comment by ddugovic** [comment]
This idea sounds sufficiently complex that discussion on https://groups.google.com/d/forum/fishcooking seems more likely to draw interest than filing an issue here, I think.

**Comment by adentong** [comment]
Maybe also try discord. People are pretty active there, including vondele.

**Comment by vondele** [comment]
There hasn't been much discussion on this issue, so I'll close it. 

As with most of these ideas, it is best to try a few patches in this direction.

The idea of tuning a subset of parameters has been tried in a recent PR https://github.com/official-stockfish/Stockfish/pull/3181 based on SVD, but not completely in the way suggested here.
