### ISSUE TITLE
Typos in readme.md

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#3137]
@Vondele — evaluations  is misspelled. Also, I believe **"millions"** should be **"billions"** or change **"of millions of positions"** to **"on more than a billion positions"**  I believe @nodchip or @sergiovieri  can confirm this is true.

Both approaches assign a value to a position that is used in alpha-beta (PVS) search to find the best move. The classical evaluation computes this value as a function of various chess concepts, handcrafted by experts, tested and tuned using fishtest. The NNUE evaluation computes this value with a neural network based on basic inputs (e.g. piece positions only). The network is optimized and trained on the **evaluations** of **billions** of positions at moderate search depth.

**Comment by nodchip** [comment]
It is believed that the number of the training data is at least 10 times of the number of the network parameters.  In the case of halfkp256x2-32-32, the number of the network parameters is about 10 millions.  The number of the positions should be 100 millions.

**Comment by vondele** [comment]
I'll fix the eval.. typo in a next commit. I prefer to keep millions rather than billions, as the latter might be an exaggeration at times, and might be confusing for some non-native speakers (some languages use 'billion' for 'trillion').
