### ISSUE TITLE
Tablebase-related PV Bug [Resolved: Not a stockfish bug]

### ISSUE THREAD

**Issue by ProteinGolem** [official-stockfish/Stockfish#3138]
![image](https://user-images.githubusercontent.com/68743991/93689594-1c03a880-fa9e-11ea-88e0-045e9b73a934.png)

Move 54 in this game;

If this is a bug, it is shared by both Lc0 and Stockfish. Kf1 is the suggestion as you can see in the PVs, but easily and obviously loses to 54... Bg7 or 54... Bd6 . Why are the PVs reported so obviously wrong? I think the CCCC GUI reports these things directly after a move is made, but this one in particular concerns me that resources are being wasted.

```[Event "No-Castle II (5|2)"]
[Site "Chess.com"]
[Date "2020.09.19"]
[Round "126"]
[White "Lc0 CPU"]
[Black "Stockfish"]
[Result "1/2-1/2"]
[ECO "A05"]
[GameDuration "00:12:17"]
[GameEndTime "2020-09-19T14:28:02.204 PDT"]
[GameStartTime "2020-09-19T14:15:44.936 PDT"]
[Opening "Reti Opening"]
[PlyCount "117"]
[Termination "adjudication"]
[TimeControl "300+2"]

1. Nf3 Nf6 2. Nc3 Nc6 3. Rg1 Rg8 4. Rb1 Rb8 5. Rh1 Rh8 6. Ng1 Ra8 7. Ra1 Nb8 8.
Nb1 Ng8 9. e4 c5 10. Nf3 d6 11. d4 cxd4 12. Nxd4 Nf6 13. Nc3 a6 14. Be2 Nc6 15.
f4 e5 16. Nxc6 bxc6 17. Qd3 h5 18. h3 Rb8 19. Rf1 exf4 20. Bxf4 Rxb2 21. Rd1 Qa5
22. Qc4 c5 23. Qd3 Be7 24. Rf2 Be6 25. Kf1 c4 26. Qd4 Rxc2 27. Rf3 Qc5 28. Qxc5
dxc5 29. Rb1 g5 30. Rb8+ Kd7 31. Rxh8 gxf4 32. Bd1 Rb2 33. Ba4+ Kc7 34. Rh6 Kd6
35. Rxf4 Ke5 36. Rf2 Rxf2+ 37. Kxf2 Nxe4+ 38. Nxe4 Kxe4 39. Rxh5 Kd3 40. Ke1 Kc3
41. Kd1 Kb2 42. Re5 Bf8 43. Re2+ Ka3 44. Bc2 Bg7 45. g4 c3 46. g5 Bxh3 47. Re7
Be6 48. g6 Kxa2 49. gxf7 Bg4+ 50. Ke1 Kb2 51. Bd3 c2 52. Bxc2 Kxc2 53. Re5 Bxe5
54. f8=Q Bd4 55. Qg8 Bc3+ 56. Kf2 Bd1 57. Qa2+ Kc1 58. Ke3 c4 59. Qxc4 1/2-1/2

**Comment by MichaelB7** [comment]
It would be helpful if you could  post the game in the correct format.   Not all the move numbers were captured correctly in the game posted.

**Comment by lonfom169** [comment]
This is likely a CCC GUI bug. It doesn't show promotion type of moves in the PV.

**Comment by ProteinGolem** [comment]
OK that's probably true. The CCCC GUI is probably flawed, but I wasn't sure. I edited the game such that it would post the numbers correctly.

**Comment by vondele** [comment]
so please close the bug if you think it is GUI related.
