### ISSUE TITLE
Discussion and ideas for elo compression

### ISSUE THREAD

**Issue by NKONSTANTAKIS** [official-stockfish/Stockfish#3141]
The high chess quality compresses elo significantly. This is a serious hindrance for all aspects.

Now that the NNUE eval is tuned externally, gone is the huge hurdle of mistuning with a weird high spread book like drawkiller, whose use imo will be a tremendous asset not only regarding drawrate, noise and increasing framework efficiency, but also for fine tuning the search for strategically rich & difficult positions. As more and more positions seem to be not challenging for current SF esp. at high TCs.

If there are worries about negative effects of overfitting search to book, this can be verified with non regression tests.

I think it will be silly to not at least experiment towards expanded elo solutions, because at our level normal chess has almost become trivial to draw. Especially at TCEC one can easily see the value and need of Jeroen's sufi selections. For us the challenge is to make it wide enough to serve as main book.

Another idea is to use a sequential VLTC fixed test of such a (small) ultra high spread book in addition to our normal LTC, whose current (and inevitably ever increasing) quality & insensitivity promotes a TC reduction (in unison with the other test)

So the LTC could be 30", run after the mandatory fixed elo spread VLTC test, which could in fact even act as a 2nd filter or in place of the STC filter. In this case, by using 5-10K VLTC games at x4 spread, we achieve much better economy and differentiation power than a typical LTC, so if we are picky about its filtering, we could even increase the LTC confidence.

Maybe it makes more sense though to actually use LTC as a 2nd filter, and VLTC elo spread as a decider for midrange performance. In this way LTC result would be 3-way: fail, tiebreak, pass. So it can resolve sooner, resulting into resource economy & quality via shared and widely applicable confidence.

All in all so many interesting possibilies for helpin the elo compression issue. This is for brainstorming & to begin discussion. It felt more appropriate to do here than in forum which seems dead, or discord which is chaotic.

**Comment by NKONSTANTAKIS** [comment]
A logical 1st step would be to tune search at an extremely high resolution book and see if its also good for the generic one.

My feeling is that good search is good search, overfitting only minimaly to book. If this proves true then we can safely abuse borderline positions, for huge resource economy potential. Those can be channeled at higher TC, more confidence/lower target elo, or just higher pace.

**Comment by NKONSTANTAKIS** [comment]
A simple method would be to just remove all positions which produce >99% draws or something.

What does the 1% offer to the resolution anyway, as it will also include a random element.

**Comment by vondele** [comment]
since there hasn't been much discussion, I'll close the issue. 

I think best would be to start from an analysis of the games played on fishtest with the current book, and present the data. For example, when I did this analysis, none of the positions had >99% draw rate. To detect 99% drawrate, you also need about 100 games per opening at least (probably many more), so to analyze the  150k openings in our default book you need to analyze 15M games.

**Comment by NKONSTANTAKIS** [comment]
Ok, 99% was just a number. The idea is to just trimm the least resolving part.

**Comment by vondele** [comment]
my point remains more or less the same. To trim the least resolving part, one needs to be able to find it based on large amounts of data. All data I have seen so far points at the fact that no 'least resolving part' can be identified in the book we currently use.

**Comment by NKONSTANTAKIS** [comment]
Alright, I trust you on these stuff. To me it seems like something will be needed to keep progressing, as both the compression and the chess level narrow the margins for improvement. So expressing ideas, for their value and viability to be judged by the technically adapt.
