### ISSUE TITLE
Book code

### ISSUE THREAD

**Issue by syzygy1** [official-stockfish/Stockfish#3145]
Just wondering... what is the current thinking about book code in Stockfish?

As not everybody might remember, SF used to include book code, but at some point it was removed: f4dcec0b942703cf0e9bad1da7e64dfa252e915d

However, it seems this would be a feature that would be appreciated by many (Cerebellum) users. Apparently, GUI book code is not a full replacement.

**Comment by MichaelB7** [comment]
Fritz is not compatible with polyglot books ( like cerebellum )  unless the engine can handle it. So very desirable for those users who play engine in engine on playchess.com and want to use cerebellum.

**Comment by vondele** [comment]
So, not so much feedback on this issue, I'm personally not particularly excited by the idea.

**Comment by syzygy1** [comment]
Fine with me. Just thought of asking because of some suggestion I read somewhere that there are attempts at "forking the community". One of the reasons for the existence of forks that are actually used is that the official branch lacks functionality that some people need.
