### ISSUE TITLE
Record low draw ratio on fishtest

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/Stockfish#3148]
The draw ratio on fistest at LTC is very consistently around 89%. However currently there are some patches running with a drastically lower draw ratio,

https://tests.stockfishchess.org/html/live_elo.html?5f6c40b5c7759d4ee307d04e   (73.2%)
https://tests.stockfishchess.org/html/live_elo.html?5f679bfbded68c240be70890    (73.4%)
https://tests.stockfishchess.org/html/live_elo.html?5f6a188ff16c15f24f9e947e       (73.5%)

I don't know what this means. I thought it was kind of interesting. 

The title is of course a joke and I will take this issue down in a couple of days.

**Comment by vdbergh** [comment]
Mystery solved: the mentioned tests have NNUE=False.

Note that with a draw ratio of 73.5% the worst case expected number of games is 270K (rather than around 100K when it is 90%).

So if there are many tests with NNUE=False then it makes sense to adjust the SPRT bounds appropriately.

**Comment by Viceroy-Sam** [comment]
If the draw rate was 99.999% the draws would have no meaning. So shouldn't the draws be removed completely? It's the win/lose that is required. then you won't require any different bounds based on draw rate.

**Comment by vondele** [comment]
ah, right, for tests of the classical eval (NNUE=false), the current SPRT bounds lead to a large expected number of games. Kind of explains the observed 300K games.

**Comment by zz4032** [comment]
The previously used BayesElo bounds didn't require an adjustment, correct? Isn't that an advantage compared to having LogisticElo in SPRT tests?

**Comment by MJZ1977** [comment]
We can set different bounds for LTC with classical eval.
