### ISSUE TITLE
debug.txt question about nnue (in latest developper SF)

### ISSUE THREAD

**Issue by hpoiters** [official-stockfish/Stockfish#3151]
I can't find a more suited forum for questions about SF, so I hope you will help me out. See a few lines from debug.txt. 
Question is: Is this only telling that nnue is enabled, or also that nnue is really working and helping find opening moves?

(if you don't want me here asking questions, please tell me where to go)

<< info string Found 1511 tablebases
>> setoption name EvalFile value P:\NNUE\nn.nnue
>> isready
<< readyok
>> position startpos
>> go wtime 302000 btime 302000
<< info string NNUE evaluation using P:\NNUE\nn.nnue enabled
<< info depth 1 seldepth 1 multipv 1 score cp 12 nodes 203 nps 203000 tbhits 0 time 1 pv e2e4
<< info depth 2 seldepth 2 multipv 1 score cp 42 nodes 682 nps 682000 tbhits 0 time 1 pv e2e4 a7a6
<< info depth 3 seldepth 3 multipv 1 score cp -5 nodes 2122 nps 2122000 tbhits 0 time 1 pv d2d3 e7e6 e2e4
<< info depth 4 seldepth 4 multipv 1 score cp 23 nodes 3343 nps 1671500 tbhits 0 time 2 pv b1c3 e7e5 e2e4

**Comment by vondele** [comment]
It is enabled and it is using it in search, i.e. to find the opening moves. 
Forum: https://groups.google.com/forum/#!forum/fishcooking
Discord: https://discord.gg/nv8gDtt
