### ISSUE TITLE
Stockfish app on Iphone

### ISSUE THREAD

**Issue by iankushnow** [official-stockfish/Stockfish#3174]
I was using Stockfish app on Iphone and use chess.com app to study my games after recent ios updates I am not able to copy my games and study.
Any plan to update IOS app ?

**Comment by vondele** [comment]
The iphone app suggested from https://stockfishchess.org/download/ is 
https://apps.apple.com/us/app/stockfish/id801463932?ls=1&mt=12 
however, we don't directly maintain the app, that's independent
