### ISSUE TITLE
Idea: Weighted average of previous evaluations

### ISSUE THREAD

**Issue by evangambit** [official-stockfish/Stockfish#3178]
Hi all, first post here, so feel free to close if this is inappropriate.

I just downloaded 800 games (500k positions) with participant ELOs over 2000 and had stockfish analyze them all at depth=10, multipv=256 (data: https://www.kaggle.com/datasnaek/chess).  Then I ran a linear regression model using each variation's score at depths 1, 2, ..., 9 to predict the score at depth=10.

It seems to me that, in a platonically ideal chess engine, the score at depth 9 should be strictly more useful for predicting the score at depth 10 than the scores at earlier depths.  In other words, the linear regression model shouldn't be able to do better than:

score@10 = score@9 * 1 + score@8 * 0 + score@7 * 0 + ... + score@1 * 0

The idea here is that all information available at depth=8 is also available when we evaluate at depth=9, so our evaluations at depth=9 should be strictly more predictive of the score at depth=10.  Whether this is a feasible/practical property for a real-life min-max algorithm is questionable, but bear with me.

Instead I got:

```
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.997
Model:                            OLS   Adj. R-squared (uncentered):              0.997
Method:                 Least Squares   F-statistic:                          1.628e+07
Date:                Sun, 11 Oct 2020   Prob (F-statistic):                        0.00
Time:                        11:34:11   Log-Likelihood:                     -5.6660e+05
No. Observations:              499827   AIC:                                  1.133e+06
Df Residuals:                  499818   BIC:                                  1.133e+06
Df Model:                           9                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0384      0.002     22.494      0.000       0.035       0.042
x1             0.2597      0.013     19.850      0.000       0.234       0.285
x2            -0.0123      0.013     -0.971      0.332      -0.037       0.012
x3             0.0689      0.011      6.335      0.000       0.048       0.090
x4            -0.0608      0.010     -6.199      0.000      -0.080      -0.042
x5             0.0207      0.007      2.955      0.003       0.007       0.034
x6            -0.0190      0.006     -3.186      0.001      -0.031      -0.007
x7             0.1554      0.005     33.158      0.000       0.146       0.165
x8             0.1485      0.002     60.420      0.000       0.144       0.153
x9             0.4354      0.002    235.358      0.000       0.432       0.439
==============================================================================
Omnibus:                   512853.134   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       8499759109.425
Skew:                           3.495   Prob(JB):                         0.00
Kurtosis:                     641.812   Cond. No.                         709.
==============================================================================
```

Ideally, the evaluation function at depth=9 should approximate the evaluations we get at depth=10 as much as possible.  This suggests a plausible route for improvement: when evaluating at depth=9, you should compute a weighted average of (1) the way score is currently computed and (2) the scores we computed at earlier depths.  Even something like `score9 = score9 * 0.75 + score8 * 0.25` could be noticeable.

**Comment by Hanamuke** [comment]
This is interesting. How did treat the score relative to the color ? I find it surprising that the coefficient for depth 8 is not negative. Maybe it would be interesting the keep only positions with a small enough evaluation. From a practical standpoint, it would probably be more useful to use only a few thousands positions but at depth 20, and only with the last 4 depth maybe.

**Comment by ProteinGolem** [comment]
Should the inclusion of parent nodes in the calculation be dependent on NNUE usage in the child node?

However, I see that storing information about whether NNUE was used in the parent node could be problematic in terms of data storage/memory, so that probably doesn't matter as much.

**Comment by xoto10** [comment]
> Even something like score9 = score9 * 0.75 + score8 * 0.25 could be noticeable.

Interesting idea. It makes sense to me that this could help, the reported eval might change by e.g. 1 cp per extra depth on average (say, 50cp at depth 10 to 10cp at depth 50) but there will often be fairly large changes up/down within that trend. This suggests to me that averaging in a small element of the previous depth eval could be useful.
 
But ... I've tried a few tests along these lines, and didn't get anything to pass both stc and ltc. e.g. https://tests.stockfishchess.org/tests/view/5f95813a48915d46ca1aff9d I suspect there is something here, but perhaps it isn't enough to pass fishtest, I don't know. Reading this thread, I see

> ... that will weight the averages more heavily if the difference between the parent node and the child evaluations are small?

I might try some ideas like that, it seems reasonable to ignore the previous depth if the eval change is large ...

**Comment by vondele** [comment]
Thanks for the idea. It is definitely worth exploring in the form of patches, and I think @xoto10 has down it by now. 

I'll close the issue. Feel free to try patches on fishtest.
