### ISSUE TITLE
Where is the Stockfish compile from 20-10-11??

### ISSUE THREAD

**Issue by lex312** [official-stockfish/Stockfish#3182]
https://abrok.eu/stockfish/
https://tests.stockfishchess.org/tests?page=6
https://tests.stockfishchess.org/tests/view/5f832f498ea73fb8ddf83ddb
https://github.com/unaiic/Stockfish/compare/767b4f4fbe...24d33a2114

**Comment by unaiic** [comment]
It hasn't been merged yet. Here is the open PR: #3179

**Comment by vondele** [comment]
PR has been merged
