### ISSUE TITLE
Stale code in clipped_relu.h

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#3190]
I noticed that the code inside this for loop
```C++
for (IndexType i = kStart; i < kInputDimensions; ++i) {
        output[i] = static_cast<OutputType>(
            std::max(0, std::min(127, input[i] >> kWeightScaleBits)));
}
```
on line 153 in clipped_relu.h never executes during bench.  Can/should it be removed?

**Comment by mega-optimus** [comment]
It seems to be activate when not using  AVX2 nor SSE2 nor MMX, e.g. when using NEON or NONE.

**Comment by mstembera** [comment]
@mega-optimus You are correct.  Thank you.  I wonder if it could/should be moved inside the above define along with setting kStart to  0 ?  As in
```C++
  #else
      constexpr IndexType kStart = 0;
      for (IndexType i = kStart; i < kInputDimensions; ++i) {
        output[i] = static_cast<OutputType>(
            std::max(0, std::min(127, input[i] >> kWeightScaleBits)));
      }
  #endif
```

**Comment by mega-optimus** [comment]
The case of using NEON also needs to loop from kInputDimensions/2 to kInputDimensions, you need to cover that as well.

**Comment by mstembera** [comment]
@mega-optimus   Makes sense.  We should keep support for other net sizes.  Thanks again.
