### ISSUE TITLE
Crash on aquarium gui

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#3200]
Bullet (1 minute/game). 
After a number of games played (70 more or less), Stockfish clock continues working at the end of the game:
the clock goes to negative values and the next game doesn't start.

**Comment by amchess** [comment]
Also in tournament mode there is the same problem.

**Comment by lex312** [comment]
> Bullet (1 minute/game).
> After a number of games played (70 more or less), Stockfish clock continues working at the end of the game:
> the clock goes to negative values and the next game doesn't start.

This is the same problem -> https://github.com/syzygy1/Cfish/issues/161

**Comment by vondele** [comment]
which version have you tested in particular?

**Comment by amchess** [comment]
the latest, but I suspects there is always this problem.

**Comment by snicolet** [comment]
@amchess 
Do you have an update on this issue?

**Comment by amchess** [comment]
> @amchess
> Do you have an update on this issue?

No. I don't have latest Aquarium 2021, but I think the problem is always in.

**Comment by vondele** [comment]
I believe this is a problem with Aquarium, not stockfish. Will close the issue.
