### ISSUE TITLE
New interface  https://tests.stockfishchess.org/tests

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#3205]
![ssd](https://user-images.githubusercontent.com/51216501/97610983-a38df100-1a26-11eb-868a-169e1e2de538.PNG)

What is it?
Who is it for?

My eyes hurt after a few seconds of being on this page!

**Comment by Marat-Ka** [comment]
Please return to the old style!

**Comment by joergoster** [comment]
See https://github.com/glinscott/fishtest/pull/806

**Comment by Marat-Ka** [comment]
It hurts me to look at it, literally. My eyes hurt, and therefore it is bad for me to read such a design.

**Comment by joergoster** [comment]
Sigh.
You can switch between this dark mode and the default light mode by clicking on the sun or moon icon on the left ...

**Comment by Marat-Ka** [comment]
Thanks!

**Comment by vondele** [comment]
yes, night mode is for those who like it and it can be easily toggled with the sun/moon icons on the left.
