### ISSUE TITLE
Chess960: illegal castling move in info line

### ISSUE THREAD

**Issue by bend86** [official-stockfish/Stockfish#3206]
In the following Chess960 FEN, you can see king castling is not possible.
However, one info line contains the move "c8g8" (king castling), which is illegal

info depth 12 seldepth 18 multipv 3 score cp 431 nodes 104380 nps 682222 tbhits 0 time 153 pv d6g3 d7d5 d1e3 b6b7 g3e5 f7f5 c1h1 d8e6 b1e1 f8g7 e5g7 b7g7 b2b4 c8g8

Here are the commands to reproduce. You can see the UCI_Chess960 option is enabled.

The version of stockfished use is the latest downloadable: stockfish_20090216_x64_bmi2

ucinewgame
setoption name Use NNUE value false
setoption name MultiPV value 3
setoption name Threads value 1
setoption name Hash value 2048
setoption name UCI_Chess960 value true
position fen q1kn1br1/3p1p1p/1rpB2p1/1p6/p7/P4P2/BPPP2PP/QRKN3R w KQq - 1 13
go nodes 500000

Thank you very much.

**Comment by vondele** [comment]
are the castling right correctly encoded in the FEN, compatible with the positions of the rooks? Too me things don't look consistent.

**Comment by bend86** [comment]
Dear,

Here is the entire pgn in which the position has been taken (after 12... Rb6).
If you see anything strange, thank you for telling me.

[Fen "qrknnbbr/pppppppp/8/8/8/8/PPPPPPPP/QRKNNBBR w KQkq - 0 1"]
[Variant "Chess960"]

1. e4 e5 2. Bc4 c6 3. a3 Nd6 4. Ba2 Nxe4 5. f3 Nd6 6. Nd3 a6 7. Nxe5 g6 8. Ng4
b5 9. Nf6 a5 10. Bc5 a4 11. Nxg8 Rxg8 12. Bxd6 Rb6 13. Bxf8 Rxf8 14. Nf2 Re8 15.
Ne4 Qa5 16. Nd6+ Kc7 17. Nxe8+ Kc8 18. O-O Qxd2 19. Rf2 Qe3 20. Re1 Qc5 21. b4
Qd6 22. Nxd6+

Thank you

**Comment by MichaelB7** [comment]
@bend86  , you are correct, that castling would not be valid, since rook already moved, but I cannot reproduce and you not using the latest available , you are using a version from Sep 02 2020.

Use this pgn with the latest exe available and see if you can reproduce after move 12. Rxg8.  Use just one thread.
```
[Event "?"]
[Site "?"]
[Date "?"]
[Round "-"]
[White "?"]
[Black "?"]
[Result "*"]
[Variant "fischerandom"]
[FEN "qrknnbbr/pppppppp/8/8/8/8/PPPPPPPP/QRKNNBBR w HBhb - 0 1"]
[SetUp "1"]

1. e4 e5 2. Bc4 c6 3. a3 Nd6 4. Ba2 Nxe4 5. f3 Nd6 6. Nd3 a6 7. Nxe5 g6 8.
Ng4 b5 9. Nf6 a5 10. Bc5 a4 11. Nxg8 Rxg8 12. Bxd6 Rb6 13. Bg3 d5 14. Ne3
Rb7 15. Be5 f5 16. O-O Ne6 17. Rbe1 Bg7 18. Bxg7 Rbxg7 19. b4
*
```

**Comment by syzygy1** [comment]
How can both white and black still castle with their rooks in different files?

**Comment by bend86** [comment]
@syzygy1 Good comment.

After testing, the right fen should be q1kn1br1/3p1p1p/1rpB2p1/1p6/p7/P4P2/BPPP2PP/QRKN3R w KQ - 1 13

So, is it possible that Stockfish ignores castling indications here (KQq) because of fen inconsistency ? 

Thank you for help

**Comment by syzygy1** [comment]
Hmmm, it does look like it should work. The SF code doesn't seem to care about the white and black rooks that can still castle being in the same file.

But actually there is no problem. c8g8 seems perfectly legal in that position.

**Comment by syzygy1** [comment]
OK, now I see what the problem is. King-side castling is not included in the fen. However, queen-side castling is included and there is no queen-side rook. Stockfish looks for the queen-side rook starting from A8, so it finds the rook on G8. So c8g8 in this case is 0-0-0 :)

So the problem is the illegal fen, incorrectly specifying that black can castle on the queen side.

**Comment by ddugovic** [comment]
Can (for debug builds) we add an assert w/respect to illegal castling rights?

**Comment by syzygy1** [comment]
We could, but we probably don't want to add asserts just to check that the input is valid.
