### ISSUE TITLE
Negative SPCC

### ISSUE THREAD

**Issue by JojoM-sf** [official-stockfish/Stockfish#3208]
See [SPCC](https://www.sp-cc.de), showing -6 Elo for 281020 towards 221020. Maybe it's time to schedule a regression test?

**Comment by vondele** [comment]
note that the results at SPCC have +- 8 Elo error, so a difference of 6 is maybe not significant. There have been only 4 Elo gainers since the last RT, and fishtest is rather busy, it is probably a bit too soon.

**Comment by JojoM-sf** [comment]
So ... let us have trust in the SPCC error bar. Later it might be more difficult to pinpoint a possible false-positive patch, though.

**Comment by JojoM-sf** [comment]
Two workers (#136, #141) stuck, apparently. Otherwise, we can rest assured there has been no regression. Thanks, Joost.

**Comment by vondele** [comment]
I've filed an issue to see what's the cause of those two workers (https://github.com/glinscott/fishtest/issues/851) otherwise, I think this is resolved.
