### ISSUE TITLE
"go movetime <x>" command is buggy.

### ISSUE THREAD

**Issue by schristy189** [official-stockfish/Stockfish#3215]
The UCI specification states that the "go movetime <x>" command will search for a move for exactly x milliseconds. The following command specifies 2000ms, but in reality Stockfish only takes 174ms to terminate.

```
$ time echo "position fen 3Q4/5q1k/4ppp1/2Kp1N1B/RR6/3P1r2/4nP1b/3b4 w - -
go movetime 2000" | ./stockfish_20090216_x64_bmi2
Stockfish 12 by the Stockfish developers (see AUTHORS file)
info string NNUE evaluation using nn-82215d0fd0df.nnue enabled
bestmove d3d4

real    0m0.174s
user    0m0.134s
sys     0m0.041s
```

**Comment by vondele** [comment]
not really, after your echo command has sent the command, it terminates, and this closes stdin to stockfish, which interprets that as equivalent to sending a 'quit'. Try this instead, the ucinewgame makes it wait till search finishes:

```echo -e "position fen 3Q4/5q1k/4ppp1/2Kp1N1B/RR6/3P1r2/4nP1b/3b4 w - -\ngo movetime 2000\nucinewgame" | ./stockfish```

**Comment by schristy189** [comment]
Thanks!
