### ISSUE TITLE
Assert in SMP code

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#322]
Assert in idle_loop():

assert(Threads.size() > 2);

Steps to reproduce: Compile with debug on, set threads to 2, run 'go infinite', wait about 5 minutes.

**Comment by guanecko** [comment]
This assert was reintroduced in Pull Request #260 (see link below)

https://github.com/official-stockfish/Stockfish/pull/260

**Comment by zamar** [comment]
I'm not able to reproduce this with my quad, running in two threads mode now for 15 minutes... So it seems to happen very intermittenly...

Technically it's possible that:

- thread1 & thread2 are searching at the same split point
- thread1finishes searching in splitpoint and sets allSlavesSearching = false in idle_loop()
- Immediately after this OS terminates thread1 execution for a very long time, and starts executing thread2
- thread2 is now eligible to split() and it does the whole split operation.
- execution of thread1is resumed, and now latejoin is evaluated in idle_loop. thread1 can now legally latejoin and assert fires.

So there is a legal extremely rare way that this can happen... And it's likely dependent on hardware that you are running. I think that in fact this is most likely to occur on 1CPU machine...

So technically the assert is incorrect. There is an SMP race that triggers it...

**Comment by braich** [comment]
Another scenario that is possible:
1. thread1 finishes work with its splitpoint and ready to search for another splitpoint to make late join.
2. OS [suspend thread1](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1650).
3. thread2 enters split() for its own splitpoint and [set sp.allSlavesSearching to true](https://github.com/official-stockfish/Stockfish/blob/master/src/thread.cpp#L165). thread1.searching is false now so thread2 even can add thread1 to its slaves;
4. OS [suspends thread2](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1608), before it [set sp.allSlavesSearching to false](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1644).
5. OS resumes thread1.
6. thread1 finds spinpoint of thread2, checks that [allSlavesSearching is set to true ](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1663), assert fires.

**Comment by zamar** [comment]
@mcostalba:

I think that we have two ways forward from here.

1. I'm not able to reproduce the problem. But if I could, I'd replace that assert() with code that prints the full split point stack of both threads. That should shed more light in the situation about what's actually happening.

2. The second option is simply to remove the assert straight away, because there is a proven SMP "race" that triggers it.

You found the problem and currently you are the only person who can reproduce it, so it's up to you to decide which route to take...

**Comment by braich** [comment]
@zamar 
I can reproduce it too.

**Comment by mcostalba** [comment]
I didn't had the time to look at this properly, I will do in the next days,
please be patient. Thanks.

**Comment by braich** [comment]
Another scenario that is possible:
1. thread1 finishes work with its splitpoint and ready to search for another splitpoint to make late join.
2. OS [suspend thread1](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1650).
3. thread2 enters split() for its own splitpoint and [set sp.allSlavesSearching to true](https://github.com/official-stockfish/Stockfish/blob/master/src/thread.cpp#L165). thread1.searching is false now so thread2 even [can add thread1 to its slaves](https://github.com/official-stockfish/Stockfish/blob/master/src/thread.cpp#L172-L187);
4. thread2 is about to add thread1 to its slaves but OS [suspends thread2](https://github.com/official-stockfish/Stockfish/blob/master/src/thread.cpp#L177) 
5. OS resumes thread1.
6. thread1 finds splitpoint of thread2, checks that [allSlavesSearching is set to true](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1663).  thread2 was suspended before [it set thread1.searching](https://github.com/official-stockfish/Stockfish/blob/master/src/thread.cpp#L183)  to true so [thread1.can_join(sp) is also true ](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1665) and assert fires.

**Comment by braich** [comment]
To the removing of assert i would add check for searching==false [along with bestSp!=nullptr](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1685) (While we were trying to find the best splitpoint for late join another thread can make us slave).

**Comment by mcostalba** [comment]
@braich you have no clear idea of what a lock means.

@zamar   I will prints the full split point stack of both threads, I guess your interpretation is correct, but I am curious to verify it.

**Comment by braich** [comment]
@mcostalba Thread2 after setting [sp.allSlavesSearching to true] (https://github.com/official-stockfish/Stockfish/blob/6c040c821a50475840607ef5f11c270ee21d61da/src/thread.cpp#L165) needs [some time](https://github.com/official-stockfish/Stockfish/blob/6c040c821a50475840607ef5f11c270ee21d61da/src/thread.cpp#L166-L182) to get to the point where it [sets thread1 searching to true] (https://github.com/official-stockfish/Stockfish/blob/6c040c821a50475840607ef5f11c270ee21d61da/src/thread.cpp#L183).
During this time OS can suspend Thread2.
Thread1 does not check if [thread2 splitpoint has already locked](https://github.com/official-stockfish/Stockfish/blob/6c040c821a50475840607ef5f11c270ee21d61da/src/search.cpp#L1662-L1666), so if OS has suspended only thread2 thread1 [begins searching for the best splitpoint for the late join](https://github.com/official-stockfish/Stockfish/blob/6c040c821a50475840607ef5f11c270ee21d61da/src/search.cpp#L1668-L1683).

**Comment by braich** [comment]
It seems that assertion triggers on Windows more often (or only on Windows). To make it occurs more often this [Makefile](https://github.com/braich/Stockfish/blob/debug-assertion/src/Makefile) can be used to compile Stockfish with mingw-w64. In my computer (two core AMD CPU) created executable generates assertion after one or two benchmark commands:
bench 16 2 1000 default time

**Comment by braich** [comment]
Some info from gdb:
(gdb) info threads
  Id   Target Id         Frame
\* 4    Thread 4332.0x7cc Thread::idle_loop (this=0x377fd0) at search.cpp:1657
  3    Thread 4332.0x1024 0x0000000000419c0d in (anonymous namespace)::insertion_sort (begin=0x2db7a10, end=0x2db7a38) at movepick.cpp:46
  2    Thread 4332.0x40c 0x00007ffc6e4511fa in ntdll!ZwWaitForMultipleObjects
    () from C:\WINDOWS\SYSTEM32\ntdll.dll
  1    Thread 4332.0x314 0x00007ffc6e4511fa in ntdll!ZwWaitForMultipleObjects
    () from C:\WINDOWS\SYSTEM32\ntdll.dll

As I write above searching is already true:
(gdb) p searching
$1 = true

**Comment by ajithcj** [comment]
@mcostalba, I hit this assert when I was trying some experiments at splitdepth 2.
This scenario can realistically happen as Joona explained.  What do we gain by keeping this assert?

**Comment by mcostalba** [comment]
Yes your analysis seems sound.

**Comment by braich** [comment]
After recent source code changes if Stockfish is compiled with [this Makefile](https://github.com/braich/Stockfish/blob/debug-assertion/src/Makefile) assertion occurs even more often but, as I wrote above, on Windows only (on Linux under Wine all seems fine).

**Comment by braich** [comment]
Lazy SMP patch [eliminates assert](https://github.com/official-stockfish/Stockfish/commit/ecc5ff6693f116f4a8ae5f5080252f29b279c0a1#diff-71c8faa29f847041392f6e81e16bd9e6L1673) so issue must be closed.

**Comment by mcostalba** [comment]
Close becuase it is obsoleted out by lazy SMP.
