### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#3228]
I have noticed people making references to SF development discussions on Discord.  Does it make sense to use yet another place besides GitHub and FishCooking?  The more places we have the harder and more disjoint it gets to follow everything.  If so what is better about Discord?   Also https://stockfishchess.org/get-involved/ mentions nothing about it.

**Comment by vondele** [comment]
I was initially hesitant to use it, but it has an advantage for interactive exchange. The disadvantage is that it is more volatile, less structured, and higher volume... which is a consequence of the former. It is the forum where the SF NNUE development nucleated, with lots of open questions and ideas being discussed.  

I guess it is a bottom-up thing, people moved there because it seems to work for them. The link is mentioned in our https://github.com/official-stockfish/Stockfish/issues/2345 : https://discord.gg/nv8gDtt

**Comment by mstembera** [comment]
I agree with your characterization.  I'm not a fan because it's more like a chat which has a poor signal to noise ratio
and is hard to keep up with.  I would think that if one wanted to get regular SF devs involved such discussions would happen here but of course people can do whatever they want.  BTW if you google Stockfish Discord you don't find it.  You get http://talkchess.com/forum3/viewtopic.php?t=74353

**Comment by NightlyKing** [comment]
It isn't a replacement for either github or google groups. It provides a - imho - fun and in a good way informal setting for computer chess fans to hang out. It certainly has its advantages of being able to get responses very quickly which does help sometimes (e.g. the py-torch trainer).
I think it is a good place for people who need help to set up chess engines or want to start testing as they usually don't have to wait hours for a response.
And there is no A.R.B. chess system spam like in Fishcooking :P

**Comment by MichaelB7** [comment]
> 
> And there is no A.R.B. chess system spam like in Fishcooking :P

Shhhh.... don't say that too loudly. ....😉

**Comment by mstembera** [comment]
Thanks to everyone for their consideration.

**Comment by TARBCS** [comment]
Stockfish 15 NNUE Plays ? The A.R.B Chess System

https://www.youtube.com/watch?v=NKK1WbinfNk


Stockfish 15 NNUE Plays The (A.R.B.C.S) - Kings & Pawns Game - A.R.B :)

https://www.youtube.com/watch?v=aFNvSLIzdDU


The A.R.B Chess System Winning The ChessWorld.net Tournament 311824

https://www.youtube.com/watch?v=pVTBgfxqQ_s

https://groups.google.com/g/fishcooking/c/wf5TzAxVufM
