### ISSUE TITLE
Best Nets for Stockfish

### ISSUE THREAD

**Issue by SFisGOD** [official-stockfish/Stockfish#3239]
Collection of best nets for Stockfish depending on your needs
| Net | Specialization| Details | Download link |
| --- | --- | --- | --- |
| nn-c3ca321c51c9.nnue | Best for noob_3moves book | Variety of opening positions | https://tests.stockfishchess.org/api/nn/nn-c3ca321c51c9.nnue |
| nn-7b23f384897e.nnue | SALC positions | Short And Long Castling or positions where the kings are on opposite flanks | https://tests.stockfishchess.org/api/nn/nn-7b23f384897e.nnue |
| nn-8458321fcd1f.nnue | Endgames | Positions with 8 or less non-pawn pieces  | https://tests.stockfishchess.org/api/nn/nn-8458321fcd1f.nnue |

**Comment by SFisGOD** [comment]
| Net | Latest Test |
| --- | --- |
| `nn-7b23f384897e.nnue` | https://tests.stockfishchess.org/tests/view/5fbbcd7267cbf42301d6b175 |
| `nn-8458321fcd1f.nnue` | https://tests.stockfishchess.org/tests/view/5fbe14ae67cbf42301d6b296 |

**Comment by DavidLee-stockfish** [comment]
can you teach me how to train strongest net?

**Comment by vondele** [comment]
I propose you move the content of the issue elsewhere. Maybe the wiki? Note that this gets outdated quickly. For example is this still the case after the merge of the new default net? 

I'll close the issue.

**Comment by SFisGOD** [comment]
@vondele Thanks. I'll move it to the wiki :)

**Comment by SFisGOD** [comment]
Created a new wiki page here https://github.com/glinscott/fishtest/wiki/Best-Nets-for-Stockfish

**Comment by MichaelB7** [comment]
@SFisGOD  Thank you Jonathan.
