### ISSUE TITLE
Binary for macOS UCI engine

### ISSUE THREAD

**Issue by brianerdelyi** [official-stockfish/Stockfish#3251]
Is it possible to download the binary for Stockfish 12 UCI engine for macOS (M1).

**Comment by MichaelB7** [comment]
Are the new machines are not backward compatible , or are you are looking for an optimized version for the m1.
Probably best bet in either case is to compile yourself. Clang should work.  Grab the free app Xcode from app store and you should be in business.  It is much easier than what people think.

**Comment by brianerdelyi** [comment]
Preferably optimised for M1 but would be willing to try non universal binary and run through Rosetta2.  Perhaps I should look into compiling it, however, why doesn't the project provide a binary of just the UCI engine?  Unsure how to compile (but I'd rather not install development tools).

**Comment by MichaelB7** [comment]
Very few people ( if any)  involved in this project have an mM1 machine - so like most early adopters, you will be on your own for a bit with open source software. Eventually somebody will grab sn M1 and it will be easier to get an optimized binary.

**Comment by brianerdelyi** [comment]
Thanks.  I'd be happy with a Stockfish 12 binary compiled for intel.  Perhaps if someone can guide me on compiling a binary for M1/ARM I can contribute the binary to the project.

**Comment by MichaelB7** [comment]
Anyone who can compile for iOS should be able to help you out.   That's actually not too common either, but there are few people here.  You can try contacting the developer for the Smallchess app on iOS , he uses Stockfish for his app,

>https://stockfishchess.org/download/
>The easiest way to get started is with the Stockfish app:
>If you want the engine only, you can get it through Homebrew: brew install stockfish

**Comment by brianerdelyi** [comment]
FYI, compiling couldn't be easier.  I downloaded source and did 'make help'.  'apple-silicon' is an available architecture.  'make build ARCH=apple-silicon' did the trick.  Added the engine to my gut and it's working fine.

I am curious if there are other options I should be considering when compiling.  Also unsure how to enable NNUE.

Curious, is it possible to compile older engines to apple-silicon architecture or must support for the architecture dependent on the source code and not the platform it is compiled on?

**Comment by vondele** [comment]
you might want to try `make -j profile-build ARCH=apple-silicon` but that's it. NNUE is automatically enabled by default. If you have been able to build, you have NNUE.

**Comment by vondele** [comment]
It should be possible to get older versions to work as well, but it probably requires some tinkering with the Makefile (copy right compiler flags, etc.).

**Comment by brianerdelyi** [comment]
@vondele thanks for the patience.  I'm unsure what -j profile-build does.  how is that from just specifying 'build'.  

I'm interested in compiling older engines to use ARCH-apple-silicon.  This requires modifying the 
makefile?

**Comment by brianerdelyi** [comment]
@vondele is it as simple as adding the apple-silicon option in the makefile with this?

`ifeq ($(ARCH),apple-silicon)
	arch = arm64
	prefetch = yes
	popcnt = yes
	neon = yes
endif`

**Comment by vondele** [comment]
`profile-build` will make a better optimized binary (using profile guided optimization PGO). `-j` will just make your build faster (parallel build) without influencing the end result.

That might be the Makefile change needed, probably also with the changes needed to enable arm64, but there could be surprising... just try.

**Comment by brianerdelyi** [comment]
I've never compiled anything before but looking through the Stockfish 12 MAKEFILE I see the following:

```
ifeq ($(ARCH),apple-silicon)
	arch = arm64
	prefetch = yes
	popcnt = yes
	neon = yes
endif
```

As I understand it, this sets compile parameters (prefetch, popcnt and neon) supported when specifying 'apple-silicon' as the architecture.  This may also require I modify the low-level configuration settings for prefetch, popcnt and neon?  The Stockfish 12 MAKEFILE also includes the following:

```
### 3.5 prefetch
ifeq ($(prefetch),yes)
	ifeq ($(sse),yes)
		CXXFLAGS += -msse
	endif
else
	CXXFLAGS += -DNO_PREFETCH
endif

### 3.6 popcnt
ifeq ($(popcnt),yes)
	ifeq ($(arch),$(filter $(arch),ppc64 armv7 armv8 arm64))
		CXXFLAGS += -DUSE_POPCNT
	else ifeq ($(comp),icc)
		CXXFLAGS += -msse3 -DUSE_POPCNT
	else
		CXXFLAGS += -msse3 -mpopcnt -DUSE_POPCNT
	endif
endif

ifeq ($(neon),yes)
	CXXFLAGS += -DUSE_NEON
	ifeq ($(KERNEL),Linux)
	ifneq ($(COMP),ndk)
	ifneq ($(arch),armv8)
		CXXFLAGS += -mfpu=neon
	endif
	endif
	endif
endif
```

If I wanted to compile an older engine, I would have to review the MAKEFILE for that version and determine if it supported the Lowe level configuration options?  If yes, I would make have to make necessary changes?  I think the most likely changes will be adding the 'apple-silicon' section and modifying the popcnt configuration.  prefetch and neon parameters doesn't appear to require any specific conditional checks related to ARM64.

Thank you for your patience.  I know it's probably pointless to compile older versions to apple-silicon.

**Comment by vondele** [comment]
probably pointless yes ;-), but should be quite easy. Note that SF 11 etc was before NNUE so things like neon were not yet important. I suggest you first try it out, downloading sources for SF 11 and compile with `make -j ARCH=generic-64 profile-build`, that likely just works. After that you see if you can add other options maybe simply with `CXXFLAGS="-DUSE_POPCNT" make -j ARCH=generic-64 profile-build` and see where that gets you.

**Comment by brianerdelyi** [comment]
Compiling with ARCH=generic-64 will create for Intel though?  This would then require Rosetta2 during execution on Apple Silicon?  I did compile previous versions successfully, but I assume it is not for Apple Silicon.

**Comment by vondele** [comment]
I meant `general-64` that should generate code for whatever the compiler emits by default, and I'm rather sure that will be apple silicon.

**Comment by brianerdelyi** [comment]
@vondele thanks again :). Anyway I can tell after compilation if it was compiled for apple silicon?

**Comment by brianerdelyi** [comment]
When I add my compiled SF 12 engine to my chess gui it is displayed as Stockfish 02120.  Where does it get this from?  How can I change it?

**Comment by vondele** [comment]
`const string engine_info(bool to_uci)` will pick the compilation date, unless you compile the commit that corresponds to a release.

**Comment by brianerdelyi** [comment]
I thought I downloaded the commit that corresponds to a release.  I have found it in misc.cpp and see where I can modify if I want.  :). I think I should close this issue.  Is there a preferred forum for discussing the source?  Is the project interested in hosting the binary for Apple Silicon?  Otherwise, I'll host in my own repository.  I'm happy to compile and provide binaries for the Apple Silicon version (though, I should figure out how code signing works).

**Comment by microsmeta** [comment]
> Is it possible to download the binary for Stockfish 12 UCI engine for macOS (M1).

Hi Brian, Thank you for having compiled and shared with me Stockfish 12 native for Apple M1. Here you find Stockfish 13 and  other strong engines (thanks to MikeB) compiled by Acepoint_de https://acepoint.de/some-chess-stuff-for-apples-m1/
