### ISSUE TITLE
loading pgn with comments then saving corrupts pgn file

### ISSUE THREAD

**Issue by abulka** [official-stockfish/Stockfish#3264]
Loading a pgn with comments into stockfish then saving it corrupts the pgn file, because the resulting pgn file is saved with `{` and `}` characters removed. 

# Repro

e.g. open this file in stockfish

```
[Event "vs Computer"]
[Site "Chess.com"]
[Date "2020.12.14"]
[Round "?"]
[White "test"]
[Black "Jimmy"]
[Result "*"]
[TimeControl "-"]

1. e3 e5 {a test comment} 2. f4 Qf6 {another test comment} 3. d4 exf4 *
```

then immediately save, which results in a corrupt pgn with the `{` characters around comments removed.

```
[Result "*"]
[Date "2020.12.14"]
[Round "?"]
[TimeControl "-"]
[Event "vs Computer"]
[Black "Jimmy"]
[Site "Chess.com"]
[White "test"]

1. e3 e5 a test comment 2. f4 Qf6 another test comment 3. d4 exf4 *
```

# version

```
Mac Mojave (Stockfish installed via AppStore)
Version 2.3 (32)
```

**Comment by vondele** [comment]
This is a problem with the App or GUI you use, not directly related to the chess engine itself. You should file this issue with the project that develops the app (those apps are independent of this project).

**Comment by abulka** [comment]
Ok I understand. 

I've emailed https://daylen.com/ who seems to be the author of Stockfish on Mac https://stockfishchess.org/about/
