### ISSUE TITLE
SF doesn't avoid 3-fold:

### ISSUE THREAD

**Issue by Firebrandx** [official-stockfish/Stockfish#3277]
I noticed while testing the latest dev builds, Stockfish-NNUE doesn't differentiate 3-fold from other 0.00 lines. Suggestion is to avoid the 3-fold draw when alternative 0.00 lines keep the game alive until a 50-move draw rule kicks in. If at some point during evaluation the alternatives fail away from 0.00, then allow 3-fold to occur.

Testing parameters are with contempt turned off.

**Comment by syzygy1** [comment]
This is not an issue.

**Comment by snicolet** [comment]
The behavior you describe is implemented with contempt and classical eval, so you can use that if you wish. 
Closing
