### ISSUE TITLE
The engine crashes without a network file, Use NNUE = false

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#3280]
Hi!
I assembled the engine with the option
["Use NNUE"] << Option (false, on_use_NNUE);

The "bench" command crashes the engine if there is no network file.

Position: 2/47 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)
info string ERROR: If the UCI option "Use NNUE" is set to true, network evaluation parameters compatible with the engine must be available.
info string ERROR: The option is set to true, but the network file ./Eval/nn.nnue was not loaded successfully.

info string ERROR: The UCI option EvalFile might need to specify the full path, including the directory name, to the network file.
info string ERROR: The default net can be downloaded from: https://tests.stockfishchess.org/api/nn/./Eval/nn.nnue
info string ERROR: The engine will be terminated now.

**Comment by Marat-Ka** [comment]
Next, I returned the network file back.
Launched the bench.
The engine speed is about the same as when using the network.
Bench: 4194835 (i.e. the same as when using the network, which is not possible with a handwritten score).

Perhaps I am doing something wrong, or is this an engine problem?

**Comment by niklasf** [comment]
Some bench positions are hardcoded to use/require NNUE. `bench` is not a standard UCI command and mostly intended for use during development, so I think that's fine.

**Comment by syzygy1** [comment]
You can do `bench 16 1 13 default depth classical` if you insist on benching without NNUE.

**Comment by Marat-Ka** [comment]
thx, it works!
