### ISSUE TITLE
Make clean should remove Windows build files

### ISSUE THREAD

**Issue by johnsonr** [official-stockfish/Stockfish#3291]
Make clean should be really clean on all platforms.

Per discussion concerning .gitignore:

@johnsonr those are the files that appeared on my windows build and that `.gitignore`:

- src/-lstdc++.res
- src/stockfish.exe
- src/stockfish.exe.lto_wrapper_args
- src/stockfish.exe.ltrans.out

you can simply change `src/stockfish` to `src/stockfish*` and add `src/-lstdc++.res`

_Originally posted by @BM123499 in https://github.com/official-stockfish/Stockfish/issues/3286#issuecomment-756526562_

**Comment by BM123499** [comment]
From that list, it removes only `src/stockfish.exe`.

**Comment by snicolet** [comment]
This has been solved partially by adding these files in .gitignore  in https://github.com/official-stockfish/Stockfish/commit/b7f643fe391d00fd9088587e8ef0ca520fa1480f
but I agree that `make clean`could remove these files too

**Comment by snicolet** [comment]
Fixed in https://github.com/official-stockfish/Stockfish/commit/4445965f9714402050119f9e6a76c6a8fc4f8d9a, closing the issue. Thanks!
