### ISSUE TITLE
32-bit AMD Athlon: Stockfish crash; Illegal instruction

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#3308]
Hi,

I tried to run Stockfish (v12 and also older v9) on my old 32-bit AMD Athlon system, on top of Windows XP and also Debian Linux 10, 32-bit, but SF crashes at start saying "Illegal instruction".

So is it asm-optimized or compiler generates wrong code ? What gives ? Any ideas ?

18.Jan.2021.

**Comment by vondele** [comment]
you need to use a version compiled for your architecture. If you compiled yourself try to compile for basic architectures such as x86-32 or x86-64 and if that works try something more advanced.

**Comment by Technologov** [comment]
I compiled for x86-32 and still getting this error

**Comment by vondele** [comment]
can you try `general-32` or `ARCH=x86-32 sse=no`

**Comment by Technologov** [comment]
Thanks, this solved the problem ! Maybe we should ship 32-bit binaries without SSE ? (for old computers)
Why do we need SSE in the 1st place ? SSE, I thought, is FPU-only, while SF is all about integers, right ?

**Comment by Technologov** [comment]
There doesn't seem to be much of a difference anyway due to SSE:
athlon-64-3000+: AMD Athlon(tm) 64 Processor 3000+ @ 2.00 GHz = Nodes/second    : 429700
athlon-1000: AMD Athlon(tm) processor, 1000 MHz = Nodes/second    : 199985

(I know that theoretically SSE can speed-up by a factor of 4x an optimized FPU code)

**Comment by ddobbelaere** [comment]
> Why do we need SSE in the 1st place ? SSE, I thought, is FPU-only, while SF is all about integers, right ?

Not according to https://en.m.wikipedia.org/wiki/Streaming_SIMD_Extensions, where also integer and bit instructions are listed, amongst others.

Before dropping sse, maybe quantify the impact better? From the data you give, what lets you conclude its impact is negligible?

**Comment by Technologov** [comment]
>Before dropping sse, maybe quantify the impact better? From the data you give, what lets you conclude its impact is negligible?
A 2 GHz AMD Athlon should deliver double the performance or 400k NPS. Athlon 64 is faster by design, per MHz, so it can deliver it's 430k NPS easily (I think I should disable SSE there too)...

**Comment by joergoster** [comment]
Tbh, I wouldn't even care for 32-bit support anymore. It is just so outdated. I'm using 64-bit OS for almost 20 years now ...

**Comment by vondele** [comment]
The SSE is useful for NNUE, so relevant from SF12 onwards.

**Comment by Torom** [comment]
On my modern system, general-32 is significantly faster than x86-32.

```
./pyshbench ../stockfish-git_general-32 ../stockfish-git_x86-32 20

Result of  20 runs
==================
base (...t_general-32) =     864877  +/- 6565
test (...h-git_x86-32) =     742994  +/- 4744
diff                   =    -121883  +/- 5446

speedup        = -0.1409
P(speedup > 0) =  0.0000

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

**Comment by Technologov** [comment]
Since we provide 32-bit binaries, I kindly ask you to provide those without SSE, so any i586/i686 machine could run it.

**Comment by syzygy1** [comment]
If general-32 is faster, your compiler might be auto-vectorizing the code for your modern cpu.

**Comment by syzygy1** [comment]
SSE adds some integer instructions that MMX lacks. The MMX path can do without SSE, but SF's Makefile doesn't support MMX without SSE.

**Comment by syzygy1** [comment]
Correction: adding sse=no does the trick, as pointed out by @vondele

**Comment by snicolet** [comment]
There have been two suggested workarounds:
```
make -j build ARCH=general-32  sse=no
```
or 
```
make -j build ARCH=x86-32  sse=no
```

So I'll close this issue for now.
