### ISSUE TITLE
`constexpr` can be added to template if-statements

### ISSUE THREAD

**Issue by Aryan1508** [official-stockfish/Stockfish#3309]
For example in `movegen.cpp`
```c++
 template<GenType Type, Direction D>
  ExtMove* make_promotions(ExtMove* moveList, Square to, Square ksq) {

    if (Type == CAPTURES || Type == EVASIONS || Type == NON_EVASIONS)
    {
        //...
    }

    if (Type == QUIETS || Type == EVASIONS || Type == NON_EVASIONS)
    {
      //...
    }

    return moveList;
  }
```

Here both the if statements can be written as `if constexpr` to ensure that only a single branch of code is instantiated during the compile time. This is also applicable to many other scenarios where templates are being compared in if-statements. Using `if constexpr` will reduce the size.

**Comment by BM123499** [comment]
if I'm not wrong, the optimization compiles those `if` as `if constexpr`, but there is no harm to help the compiler to do it.

**Comment by Aryan1508** [comment]
> if I'm not wrong, the optimization compiles those `if` as `if constexpr`, but there is no harm to help the compiler to do it.

Yes, a good compiler **might** do that. There are cases where it will refactor it into something like `if (true) ` where you won't receive the 100% advantage of templates. Adding the `constexpr` ensures that only a single branch is instantiated

**Comment by BM123499** [comment]
@Aryan1508 check #3301
