### ISSUE TITLE
Same Colored Bishops with all Connected pawns (both NNUE and HCE)

### ISSUE THREAD

**Issue by ProteinGolem** [official-stockfish/Stockfish#3316]
This issue originates from analysis of a position appearing in TCEC. This issue is meant to be specific positions with opposing connected pawns, not positions with passed pawns.

![image](https://user-images.githubusercontent.com/68743991/105435648-bed65a00-5c2b-11eb-9a2f-cf1c61c0a7fe.png)
![image](https://user-images.githubusercontent.com/68743991/105435670-c8f85880-5c2b-11eb-96b6-8e874aa02428.png)

Same Colored Bishops:
https://lichess.org/analysis/8/5kp1/7p/b6P/5KP1/5P2/5B2/8_w_-_-_0_1
https://lichess.org/analysis/8/4kp2/2b3p1/6P1/4KP2/4P3/4B3/8_w_-_-_0_1
https://lichess.org/analysis/8/3kp3/1b3p2/5P2/3KP3/3P4/3B4/8_w_-_-_0_1
(all of these, lc0 thinks are drawn.)

Komodo Dragon at lower depths appears to have a lower evaluation than Stockfish... For whatever reason. 

Compare to OCB:
https://lichess.org/analysis/8/3kpB2/1b3p2/5P2/3KP3/3P4/8/8_w_-_-_0_1

Compare to 4 vs 3 pawns, a more complicated endgame:
https://lichess.org/analysis/8/4kpp1/7p/b6P/5KP1/4PP2/5B2/8_w_-_-_0_1
1 node lc0 gives Kf5 with eval of +4.76, while stockfish takes a while for evaluations to climb from around +2 to +4
Same position, without a clear King infiltration advantage:
https://lichess.org/analysis/8/4kpp1/7p/b6P/6P1/4PP2/5B2/7K_w_-_-_0_1
lc0 (without value repair) using deep search says Kg2 with an eval of +0.89, while stockfish climbs to +1.7. Based upon lc0 evaluations I'm guessing that one is much more drawish.
lc0 J94-100 with value repair (trained off positions where searched evaluations differ from 1-node evaluations) says +0.35.

Solutions to this problem could involve:
- Multipliers which modulate output from HCE and/or NNUE evaluations in endgames for minor pieces which are able to defend connected pawns which also oppose enemy pawns
- Specialized NNUE for same colored bishop endgames
- Increase relative importance of king infiltration/advancement based upon number of pawns in endgames
- New cases for search in which endgames which appear to be futile with same colored bishops
- Implementation of value repair for endgames, where endgames with outcomes/searched evaluations which don't match NNUE expectation get put as a starting position in the training data set.
- Train off game result in endgames rather than training off evaluation

**Comment by dsmsgms** [comment]
Latest stockfish dev (tested at 3B nodes) gives depressed evals for such endgames (4x cp for 3P v 2P and ~100 cp for 4P v 3P). This seems to be due to latest Stephane's patch, and it is worth considering whether 50 move rule eval decay should be even more aggressive for endgame positions.

**Comment by ProteinGolem** [comment]
Closing this issue in favor of a different issue which has a promising idea that potentially could solve this one. #3449
