### ISSUE TITLE
weird bishop and rook attacks code

### ISSUE THREAD

**Issue by ANDREMIV** [official-stockfish/Stockfish#3326]
Hello, I don't understand the code in evaluate.cpp line 400.
why :
b = Pt == BISHOP ? attacks_bb<BISHOP>(s, pos.pieces() ^ pos.pieces(QUEEN))
          : Pt ==   ROOK ? attacks_bb<  ROOK>(s, pos.pieces() ^ pos.pieces(QUEEN) ^ pos.pieces(Us, ROOK))
                         : attacks_bb<Pt>(s, pos.pieces());
instead of
b = attacks_bb<Pt>(s, pos.pieces());

Can someone explain me the point of removing the queens from the occupied squares in the bishop bb atttacks for example ?

**Comment by BM123499** [comment]
It's removed just to see the mobility and board control. I believe it's heuristic. But it's not used for move generation.

**Comment by ANDREMIV** [comment]
Ok thanks it makes sense
