### ISSUE TITLE
Using Github with passwords is deprecated

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#3332]
Hi all,

I have received the following email from Github, warning about the future deprecation of access with passwords for the git operations in August 2021.

>Hi @snicolet,
>You recently used a password to access the repository at snicolet/Stockfish with git using git/2.13.5 (Apple Git-94). Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
>Thanks, The GitHub Team

Since I suppose that all of us use command-line git commands to keep our master branch in synch with the stockfish-official master branch, we should probably all begin to switch to token authorizations right now, to avoid bad surprises in the summer. 

There is some documentation there: 
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by ppigazzini** [comment]
Some config tricks to simplify the token/ssh login:
https://github.com/glinscott/fishtest/issues/881#issuecomment-771551522

**Comment by MichaelB7** [comment]
Also this may be helpful for some ...https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by snicolet** [comment]
Somewhat related: I recently got an error about an outdated SSL certificate on my old MacBook with MacOX 10.9.

```
fatal: unable to access 'https://github.com/snicolet/Stockfish.git/': SSL certificate problem: Invalid certificate chain
```

The fix I used was somewhat brutal, but it did the trick to access the Stockfish git repo:

```
git config --global http.sslVerify false
```

**Comment by vondele** [comment]
probably not the recommended way to fix this however, it is basically disabling part of the security offered by https.

**Comment by snicolet** [comment]
Stefan had a small, temporary issue with his token after the switch to Github Actions to replace Travis, maybe his solution can help others in similar situations:
https://github.com/official-stockfish/Stockfish/issues/3567

**Comment by TheYoBots** [comment]
Using Github with passwords through command line has been depreciated since 13th Aug 2021.

**Comment by vondele** [comment]
closing this now, as this is now deprecated since quite a long time. Most devs will have adjusted their workflows.
