### ISSUE TITLE
Is contempt not used with NNUE?

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/Stockfish#3339]
Grepping the source, it seems to me that contempt is only used for the classical eval now.
Is this correct? If so shouldn't this be made clearer? A priori a user would expect it to be always used.

**Comment by ssj100** [comment]
That is correct.  Ever since NNUE implementation, Contempt has never affected it.  However, given hybrid obviously uses classical eval, Contempt still affects that, and therefore it affects default SF (as default SF is hybrid).
