### ISSUE TITLE
Switch default compiler to Clang

### ISSUE THREAD

**Issue by gcp** [official-stockfish/Stockfish#3341]
I remember the Makefile or some documentation saying that Stockfish prefers gcc with the specific flags in the Makefile. In any case, currently the default is gcc: https://github.com/official-stockfish/Stockfish/blob/master/src/Makefile#L303

However, at least on my main workstation (a Haswell), Clang has been consistently faster for Stockfish now. This might've changed around the NNUE stuff, or due to recent Clang updates, not sure, but Clang is about 7-8% faster.

I wonder if:
a) Other people on other hardware can compare gcc9/10 vs clang11/12 and see what produces faster binaries to confirm I'm not imagining this or my hardware is the exception.
b) If it's faster for most people, whether we could consider switching the default? I think LLVM is used by a lot of stuff now so asking for Clang on Linux distros is not disruptive.
c) If it's faster on the TCEC/CCC hardware, maybe those should get different binaries?
d) If we should do some work to get a Clang compile going on Windows. This seems tricky with mingw, though, so maybe a non-mingw version is a first step.

**Comment by gcp** [comment]
As for (d), I only found #1358.

**Comment by Torom** [comment]
On my system a clang build is 2~3 % slower.

```
./stockfish-git compiler 
Stockfish 090221 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 10.2.0 on Linux
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 10.2.0

./stockfish-git_clang compiler
Stockfish 090221 by the Stockfish developers (see AUTHORS file)

Compiled by clang++ 11.0.1 on Linux
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: Clang 11.0.1

./pyshbench ../stockfish-git ../stockfish-git_clang 100
==================
base (...tockfish-git) =    2184064  +/- 6591
test (...sh-git_clang) =    2130868  +/- 3807
diff                   =     -53196  +/- 8002

speedup        = -0.0244
P(speedup > 0) =  0.0000

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

**Comment by gcp** [comment]
``
Result of 100 runs
==================
base (...ockfish_gcc9) =    1845945  +/- 14086
test (...fish_clang12) =    1867970  +/- 13434
diff                   =     +22024  +/- 4256

speedup        = +0.0119
P(speedup > 0) =  1.0000

CPU: 4 x Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
Hyperthreading: on 
``

I seem to have a local patch that changes the ``-flto-thin`` override for Clang in the Makefile back to to ``-flto``. Thin-LTO was supposed to be an improvement, but if you look at the benchmarks http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html notice that it is actually slower for chess and go engines.

Does your result flip around with regular LTO?

**Comment by gcp** [comment]
On Zen 1 I see no difference:

```
Result of 100 runs
==================
base (...ockfish_gcc9) =    1511804  +/- 3785
test (...ang12fulllto) =    1511122  +/- 3790
diff                   =       -682  +/- 4658

speedup        = -0.0005
P(speedup > 0) =  0.3872

CPU: 8 x AMD Ryzen 7 1700 Eight-Core Processor
Hyperthreading: on 
```

But also here regular LTO is faster:

```
Result of 100 runs
==================
base (...ang12thinlto) =    1515230  +/- 2664
test (...ang12fulllto) =    1526217  +/- 2881
diff                   =     +10987  +/- 3202

speedup        = +0.0073
P(speedup > 0) =  1.0000

CPU: 8 x AMD Ryzen 7 1700 Eight-Core Processor
Hyperthreading: on 
```

**Comment by Torom** [comment]
`-flto` is still slower than gcc:

```
./pyshbench ../stockfish-git ../stockfish-git_clang_flto 100
==================
base (...tockfish-git) =    2186091  +/- 5677
test (...t_clang_flto) =    2162191  +/- 3980
diff                   =     -23901  +/- 7884

speedup        = -0.0109
P(speedup > 0) =  0.0000

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

but definitely faster than `-flto=thin`:

```
./pyshbench ../stockfish-git_clang ../stockfish-git_clang_flto 100
==================
base (...sh-git_clang) =    2121055  +/- 5148
test (...t_clang_flto) =    2161406  +/- 4471
diff                   =     +40351  +/- 7771

speedup        = +0.0190
P(speedup > 0) =  1.0000

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```

**Comment by gcp** [comment]
Ivy Bridge, gcc 10 vs clang-11, clearly favors gcc

```
Result of 100 runs
==================
base (...ckfish_gcc10) =    1769288  +/- 464
test (...fish_clang11) =    1701570  +/- 400
diff                   =     -67718  +/- 583

speedup        = -0.0383
P(speedup > 0) =  0.0000

CPU: 4 x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
Hyperthreading: on 
```

**Comment by gcp** [comment]
Okay, I guess my main desktop is actually the exception here, and for most machines gcc is as good or may be significantly better.

I'll prepare a pull request to fix the LTO default, I think we've confirmed that's a universal gain.

**Comment by Torom** [comment]
One more `-flto` vs. `-flto=thin` clang10:

```
./pyshbench ../stockfish_clang_thin ../stockfish_clang_lto 100
==================
base (...h_clang_thin) =    2052135  +/- 501
test (...sh_clang_lto) =    2073530  +/- 629
diff                   =     +21395  +/- 704

speedup        = +0.0104
P(speedup > 0) =  1.0000

CPU: 24 x Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Hyperthreading: on
```

gcc 9.3.0 vs. clang 10:

```
./pyshbench ../stockfish_gcc ../stockfish_clang_lto 100
==================
base (...tockfish_gcc) =    2137430  +/- 521
test (...sh_clang_lto) =    2074978  +/- 408
diff                   =     -62453  +/- 696

speedup        = -0.0292
P(speedup > 0) =  0.0000

CPU: 24 x Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Hyperthreading: on
```

**Comment by Torom** [comment]
After your two clang paches, clang is almost as strong as gcc on my system. Very impressive.

gcc 10.2.0 vs. clang 11.0.1:
```
./pyshbench ../stockfish-git ../stockfish-git_clang 100
==================
base (...tockfish-git) =    2186535  +/- 5842
test (...sh-git_clang) =    2175076  +/- 4119
diff                   =     -11460  +/- 8120

speedup        = -0.0052
P(speedup > 0) =  0.0029

CPU: 4 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Hyperthreading: on
```
