### ISSUE TITLE
"bench" is IO limited

### ISSUE THREAD

**Issue by gcp** [official-stockfish/Stockfish#3344]
STR:

1) On a Windows machine, launch the stockfish.exe executable, either by clicking in Explorer or launching from cmd.exe (Command Prompt)
2) Type "bench".
3) Launch the same executable from a mingw shell (e.g. mingw64.exe)
4) Type "bench".

Observe results from 2 and 4 are not within run error, on Windows 10 I see 16% difference.

**Comment by Torom** [comment]
This is a known issue. You have to pipe stdout to null:

windows cmd:
`.\stockfish.exe bench > NUL`

powershell:
`.\stockfish.exe bench | Out-Null`

linux:
`./stockfish bench > /dev/null`

**Comment by gcp** [comment]
Yes, but it's annoying ``bench`` can't do this itself. Maybe it's hard to fix in the general structure of Stockfish, but it would be nice if it would be quiet by default.

**Comment by Sopel97** [comment]
The output could be supressed by setting `Limits.silent = true` for each search within bench

**Comment by vondele** [comment]
I don't think we should fix this. Bench resembles standard search, and the IO is part of it. Practically, one can redirect to a file, most overhead is due to the terminal being slow.
