### ISSUE TITLE
Adding a stockfish namespace for all symbols.

### ISSUE THREAD

**Issue by jblespiau** [official-stockfish/Stockfish#3350]
While including this project into another project, it's easy to get namespace pollution and it's even possible to have conflicts.

Do you think it would be possible to add a namespace for all files?

I acknowledge it can break the build for people who linked to it, so it may be something to do with a major update, but in the long run, I think it would make the code simpler to use by others.

What do you think?

**Comment by ddobbelaere** [comment]
Please keep in mind that deepmind/open_spiel is licensed under Apache Version 2.0, whereas Stockfish under GPLv3. According to http://www.apache.org/licenses/GPL-compatibility.html it's a one-way street.

Simply stated, you cannot use Stockfish code in a project with the less restrictive Apache Version 2.0 license, as this would, amongst others I guess, not enforce derived projects to disclose the full source...
