### ISSUE TITLE
Minimum qsearch depth

### ISSUE THREAD

**Issue by ddugovic** [official-stockfish/Stockfish#3353]
Is there a minimum (most negative) qsearch depth cap?  I can't imagine a legal position which could cause infinite recursion and I expect this issue will be closed (not a bug).

Discovered while debugging https://github.com/ddugovic/Stockfish/issues/588

**Comment by vondele** [comment]
The movepicker somehow limits this via
DEPTH_QS_RECAPTURES = -5
but checks are exceptions.

**Comment by vondele** [comment]
and obviously, we have MAX_PLY

**Comment by ddugovic** [comment]
I see; OK, it is implausible that a position with many consecutive checks would trigger infinite looping in a real game.
