### ISSUE TITLE
Use UCI_Elo

### ISSUE THREAD

**Issue by ScarecrowY** [official-stockfish/Stockfish#3358]
Hi, I was using python-chess to get a move from stockfish 12. However, the python-chess library doesn't provide an option to limit the engine's strength to a specific Elo rating. I know stockfish itself has options ```UCI_LimitStrength``` and ```UCI_Elo``` to achieve such purpose. I wonder if there is any python library that utilizes these options? Or how should I achieve my purpose? Thank you so much!

**Comment by CnGRepo** [comment]
I have never used python-chess till now. But looking at the documentation its seems you can set options with the configure command like this par example:

`await engine.configure({"UCI_elo": 3500})`

Look at this link here https://python-chess.readthedocs.io/en/latest/engine.html#options

**Comment by ScarecrowY** [comment]
Thanks for your answer! I wonder if the UCI_Elo and UCI_LimitStrength options are new to Stockfish 12? Our project is currently using Stockfish 9.

**Comment by TonHaver** [comment]
Both are available since Stockfish 11

**Comment by ScarecrowY** [comment]
thanks!  do I have to first set UCI_LimitStrength to true to use the UCI_Elo option, or I can directly use UCI_Elo?

**Comment by TonHaver** [comment]
UCI protocol is here: http://wbec-ridderkerk.nl/html/UCIProtocol.html

It has:
```
*  = UCI_LimitStrength, type check, should be false by default,
			The engine is able to limit its strength to a specific Elo number,
		   This should always be implemented together with "UCI_Elo".
*  = UCI_Elo, type spin
			The engine can limit its strength in Elo within this interval.
			If UCI_LimitStrength is set to false, this value should be ignored.
			If UCI_LimitStrength is set to true, the engine should play with this specific strength.
		   This should always be implemented together with "UCI_LimitStrength".
```

**Comment by ScarecrowY** [comment]
Sorry for bothering again. May I ask what does ```await``` do? Is it necessary to use it?

**Comment by tillchess** [comment]
> thanks! do I have to first set UCI_LimitStrength to true to use the UCI_Elo option, or I can directly use UCI_Elo?

UCI_LimitStrength needs to be "true" , if you like to use UCI_Elo

**Comment by TonHaver** [comment]
> Sorry for bothering again. May I ask what does `await` do? Is it necessary to use it?

I think you'd better look that up in python docs, but I would guess it's the way to start a subroutine and wait until that's finished before continuing

**Comment by jamesbraza** [comment]
To configure ELO using [`chess`](https://pypi.org/project/chess/):

```python
ENGINE_PATH = "/opt/homebrew/bin/stockfish"  # Install via homebrew on macOS
ENGINE_ELO: int = 1600  # Class B's lower bound

engine = chess.engine.SimpleEngine.popen_uci(ENGINE_PATH)
engine.configure({"UCI_LimitStrength": True, "UCI_Elo": ENGINE_ELO})
```

No need for the `await`, `chess==1.9.4` will block until completion.
