### ISSUE TITLE
Stochfish 13 caused an exception, game stopped

### ISSUE THREAD

**Issue by shadizahran** [official-stockfish/Stockfish#3364]
When using Stockfish 13 with NNUE net more than 20MB in size the engine fails to start. It will give the error msg " Stockfish 13 caused an exception, game stopped". 

I downloaded the NNUE net from 
https://tests.stockfishchess.org/nns

I tried several Neural Nets with 40MB size but same results. Only nets with 20MB size is working perfect. 

Net example: 
nn-36ae649bc733.nnue
https://tests.stockfishchess.org/api/nn/nn-36ae649bc733.nnue

I am using Fritz 17 GUI and chessbase 15!

I downloaded the Neural net then saved it in the same destination folder of Stockfish 13 then updated the engine parameters with the Neural net name.
![1613825161170-1653586049](https://user-images.githubusercontent.com/75981230/108595798-ce63d280-7392-11eb-90b5-65ed2d8103fb.jpg)

I hope you find a solution to this serious issue!!

**Comment by vondele** [comment]
not unexpected. Use the binary only with the default net corresponding with the binary, there is no guarantee that other nets work with a given binary. In particular, the NNUE nets you download from the above URL correspond to all nets that have been tested on fishtest, including new architectures that are not compatible with the master branch. If you want to try out these different nets, you need to build the sources that correspond to that particular net architecture (which one can find by clicking on the first test link).
