### ISSUE TITLE
probable error stockfish 13

### ISSUE THREAD

**Issue by laripette** [official-stockfish/Stockfish#3366]
Hello,
I made a game with stockfish 13
I limited the elo to 1960.

At one point in the game, it kept going around in circles.
Is that normal?
[Stockfish13.zip](https://github.com/official-stockfish/Stockfish/files/6039180/Stockfish13.zip)

here is the part in pgn with its file in attachment

[Event "Événement local"]
[Site "Site local"]
[Date "2021.02.24"]
[Round "1"]
[White "picsou"]
[Black "Stockfish 13"]
[Result "*"]
[PlyCount "158"]
[Termination "abandoned"]
[ECO "C78"]
[Opening "Ruy Lopez"]
[Variation "Morphy Defense, Arkhangelsk Variation"]

1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O b5 6. Bb3 Bb7 7. Re1 Bc5 8. c3
Ba7 9. d4 O-O 10. d5 Na5 11. Bg5 d6 12. Nbd2 Nxb3 13. axb3 Bb6 14. Nf1 h6 15.
Bh4 a5 16. Qd3 g5 17. Bg3 b4 18. Ne3 Kh7 19. Nc4 bxc3 20. bxc3 Ba6 21. Nfd2 Nd7
22. Qf3 Qf6 23. Nxb6 Qxf3 24. Nxf3 cxb6 25. c4 a4 26. Rxa4 Nc5 27. Ra3 Bb7 28.
Rxa8 Rxa8 29. h4 f6 30. b4 Nd3 31. Re3 Nc1 32. b5 Kg7 33. Kf1 Ra2 34. Ke1 Ne2
35. Rxe2 Ra1+ 36. Kd2 Ra2+ 37. Ke3 Ra3+ 38. Kd2 Ra2+ 39. Kd3 Ra3+ 40. Kc2 Ra2+
41. Kd1 Ra1+ 42. Kc2 Ra2+ 43. Kd1 Ra1+ 44. Kd2 Ra2+ 45. Kd3 Ra3+ 46. Kc2 Ra2+
47. Kd1 Ra1+ 48. Kd2 Ra2+ 49. Ke3 Ra3+ 50. Kd2 Ra2+ 51. Kd1 Ra1+ 52. Kc2 Ra2+
53. Kd3 Ra3+ 54. Kd2 Ra2+ 55. Kd1 Ra1+ 56. Kc2 Ra2+ 57. Kd3 Ra3+ 58. Kd2 Ra2+
59. Ke3 Ra3+ 60. Kd2 Ra2+ 61. Kd1 Ra1+ 62. Kc2 Ra2+ 63. Kd3 Ra3+ 64. Kc2 Ra2+
65. Kd3 Ra3+ 66. Kd2 Ra2+ 67. Ke3 Ra3+ 68. Kd2 Ra2+ 69. Kd3 Ra3+ 70. Kd2 Ra2+
71. Ke1 Ra1+ 72. Kd2 Ra2+ 73. Ke3 Ra3+ 74. Kd2 Ra2+ 75. Kd1 Ra1+ 76. Kd2 Ra2+
77. Kd3 Ra3+ 78. Kd2 Ra2+ 79. Ke1 Ra1+ *

**Comment by Torom** [comment]
The GUI you are using should have stopped the game after move 44. ... Ra2+. Because of a triple repetition. This is no Stockfish error.

**Comment by laripette** [comment]
I use pychess under linux.

It's a pity that stockfish does rehearsals.
He hadn't lost the game.

**Comment by vondele** [comment]
I guess the engine went for a three-fold because that was the best move in the position. I agree, probably a GUI or driver issue, not a stockfish bug.
