### ISSUE TITLE
Strange behavior after a game is considered a draw my the 50 move rule

### ISSUE THREAD

**Issue by PhilippSchindler** [official-stockfish/Stockfish#3374]
I have been running a few tests Stockfish 13 vs Stockfish 13 (stockfish_13_linux_x64_avx2). Below you find a game from yesterdays self play which should definitely be a draw but the black stockfish made a blunder in move 100 and lost the game. I added the PGN below. 

```
[Event "Engine Match (Stockfish 13 Selfplay, classical time controls)"]
[Site ""]
[Date "2021-02-26"]
[Round ""]
[White "stockfish_13_linux_x64_avx2 (ryzen 3950x, 32GB)"]
[Black "stockfish_13_linux_x64_avx2 (ryzen 3950x, 32GB)"]
[Result "1-0"]

1. d4 Nf6 2. c4 e6 3. Nf3 d5 4. Nc3 Bb4 5. Bg5 h6 6. Bxf6 Qxf6 7. Qb3 c5 8. cxd5 exd5 9. e3 O-O 10. dxc5 Bxc3+ 11. Qxc3 Qxc3+ 12. bxc3 Nd7 13. c4 dxc4 14. Bxc4 Nxc5 15. Ke2 Bd7 16. Rhc1 Rac8 17. Nd4 a6 18. Rc2 Ne6 19. Nxe6 Bxe6 20. Rac1 Bxc4+ 21. Rxc4 Rxc4 22. Rxc4 a5 23. Rc5 b6 24. Rb5 Rc8 25. Rxb6 Rc2+ 26. Kf3 Rxa2 27. g4 Kf8 28. h4 a4 29. g5 hxg5 30. hxg5 Ke7 31. e4 Rc2 32. Rb7+ Kd6 33. Ra7 Rc3+ 34. Kg4 a3 35. f4 g6 36. f5 Rb3 37. Rxf7 gxf5+ 38. Rxf5 Rb2 39. Ra5 Rg2+ 40. Kf3 Ra2 41. e5+ Ke6 42. g6 Ra1 43. g7 Kf7 44. g8=Q+ Kxg8 45. e6 Kf8 46. Kg2 Ke7 47. Ra6 a2 48. Kh2 Rb1 49. Rxa2 Kxe6 50. Kg2 Rb6 51. Kh3 Rb3+ 52. Kg4 Rb4+ 53. Kg3 Kf6 54. Kg2 Rb1 55. Ra4 Rb8 56. Kf1 Rb1+ 57. Kf2 Kf7 58. Ra7+ Ke8 59. Ra3 Ke7 60. Ra7+ Kf8 61. Ra8+ Kf7 62. Ra7+ Kg6 63. Ra6+ Kf5 64. Ra5+ Kf4 65. Ra4+ Kg5 66. Ra2 Rb3 67. Ra5+ Kf6 68. Rd5 Rb2+ 69. Kg3 Rb3+ 70. Kf2 Rc3 71. Rd2 Rc6 72. Kg2 Rc7 73. Rf2+ Kg7 74. Rf4 Rb7 75. Kg3 Kh6 76. Kg2 Kg5 77. Rf3 Rb2+ 78. Rf2 Rb4 79. Rc2 Ra4 80. Rd2 Rg4+ 81. Kf1 Rf4+ 82. Ke2 Ra4 83. Rd5+ Kg4 84. Rd6 Rc4 85. Kd2 Rc7 86. Rg6+ Kf3 87. Rg1 Rd7+ 88. Kc1 Ra7 89. Rg6 Ra1+ 90. Kb2 Rd1 91. Ka2 Kf4 92. Rf6+ Kg5 93. Rf8 Rd6 94. Rf3 Re6 95. Ka3 Ra6+ 96. Kb2 Rb6+ 97. Rb3 Rh6 98. Re3 Rh2+ 99. Ka1 Kh6 100. Re1 Rh1 101. Rxh1+ Kg5 102. Rf1 Kg4 103. Kb2 Kg5 104. Kc3 Kg4 105. Kd3 Kg5 106. Ke4 Kg6 107. Ke5 Kg5 108. Rg1+ Kh4 109. Kf4 Kh5 110. Rg2 Kh6 111. Kf5 Kh7 112. Kf6 Kh8 113. Kf7 Kh7 114. Rh2# 1-0
```

Why this has happend?
In this game there are move than 50 moves without a capture. So when the black side plays Rh1 in move 100 a draw can be claimed. However, I still find it strange that stockfish plays a blunder (Rh1) at this stage of the game. Why not play another other suitable move? For example, there are now many games known which cannot be decided within 50 moves (although the example is not one of them) and so making deeper analysis of such positions possible (without restriction to the 50 move rule) seems reasonable to me.

**Comment by BM123499** [comment]
@PhilippSchindler I believe that searching after 50-moves rule are considered undefined behavior. Because there are condition to return draw if there are more than 100 half-moves without a pawn move or capture. It can play completely at random, but it's not its fault. 50-moves rule is automatically claimed, GUI should have stopped when it was achieved. It is more a issue on GUI than  issue in Stockfish.

And on the code, Evaluation is scaled with 50-moves rule, if it got more than it, the evaluation will be multiplied by a negative value. In summary, it was not designed to support moves beyond 50-moves rule.

**Comment by syzygy1** [comment]
Stockfish assumes that the 50-move rule is enforced by the GUI. This is by design and not a bug.

If you want something else, you need to modify the Stockfish source code (or find someone to do it for you).

**Comment by vondele** [comment]
so not a bug, rather expected behavior, the GUI needs to adjudicate a 50-move draw.
