### ISSUE TITLE
Big negative 'Winnable' score

### ISSUE THREAD

**Issue by joergoster** [official-stockfish/Stockfish#3375]
For this position
`1n2k1n1/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1`
which is won for White, static eval gives a large negative 'Winnable' score.
This looks wrong to me.

```
position fen 1n2k1n1/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
d

 +---+---+---+---+---+---+---+---+
 |   | n |   |   | k |   | n |   | 8
 +---+---+---+---+---+---+---+---+
 | p | p | p | p | p | p | p | p | 7
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 6
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 5
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 4
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 3
 +---+---+---+---+---+---+---+---+
 | P | P | P | P | P | P | P | P | 2
 +---+---+---+---+---+---+---+---+
 | R | N | B | Q | K | B | N | R | 1
 +---+---+---+---+---+---+---+---+
   a   b   c   d   e   f   g   h

Fen: 1n2k1n1/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
Key: 8BECA86F2D7616C2
Checkers: 
eval
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled

     Term    |    White    |    Black    |    Total   
             |   MG    EG  |   MG    EG  |   MG    EG 
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | 32.07 34.50
   Imbalance |  ----  ---- |  ----  ---- |  1.85  1.79
       Pawns |  0.38 -0.08 |  0.38 -0.08 |  0.00  0.00
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Winnable |  ----  ---- |  ----  ---- |  0.00 -11.78
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | 33.91 24.51

Classical evaluation: 29.52 (white side)

NNUE evaluation:      14.98 (white side)

Final evaluation:     29.52 (white side)

```

**Comment by BM123499** [comment]
@joergoster I believe winnable is just to reference the loss because of `ScaleFactor`.
If you see the code, Winnable = `eg * ScaleFactor(sf) / SCALE_FACTOR_NORMAL - eg_value(score))`, which means it's like `eg * (sf - 1)`.
I believe sf is in range [0, 64]/64. So Winnable will be mostly negative (or zero).
So, why is this big? it's not because of subtracting the score value per se, but score value is very big. So just looking to Winnable can be misleading.
Sf is used for endgame only, it can help deciding which endgame is more favorable to win. And this position is more likely a middle-game, so it won't (or poorly) affect the final result.

For reference. On this position, sf = 43/64 . Lines:
https://github.com/official-stockfish/Stockfish/blob/0f3f5d85fb5c9f75199f27fbf7a725ff3e8bb4dc/src/evaluate.cpp#L933-L935

**Comment by BM123499** [comment]
In summary, the endgame winnable value is just display a "correction", so the true value endgame eval is displayed in the end (total). I believe that's doing separately to make debug life easier to know where the value is changing.

**Comment by joergoster** [comment]
@BM123499 I know this, of course. ;-)

Do you think it makes sense to apply such a big negative endgame score in a totally won position, or to compute a `ScaleFactor` at all in such positions?
It's something like a mate in 18, btw. If at all, we should apply a big positive score here.

**Comment by BM123499** [comment]
Well... it's not apply a big negative value, but multiply the score by a value less than 1 (which means it will be negative).  It's as big as the endgame eval. And it's only applied on Classical Eval. It will not flip the signal of the result, but reduce it to a scale, as I said, it's only to pick a favorable endgame. The bigger the scale, the more liked it will choose that endgame.

**Comment by BM123499** [comment]
I increase the difference between score, and see below:
As a example, here:
```
position fen 4k3/7p/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
eval
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled

     Term    |    White    |    Black    |    Total
             |   MG    EG  |   MG    EG  |   MG    EG
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | 43.32 49.16
   Imbalance |  ----  ---- |  ----  ---- |  3.28  2.85
       Pawns |  0.55 -0.11 | -0.01 -0.07 |  0.57 -0.04
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Winnable |  ----  ---- |  ----  ---- |  0.00 -21.90
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | 47.17 30.07

Classical evaluation: 36.75 (white side)

NNUE evaluation:      13.95 (white side)

Final evaluation:     36.75 (white side)
```

**Comment by BM123499** [comment]
Even "worse" Winnable:

```
position fen 7k/7p/8/8/8/8/RRRRRRRR/RRRQKRRR w KQ - 0 1
eval
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled

     Term    |    White    |    Black    |    Total
             |   MG    EG  |   MG    EG  |   MG    EG
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | 96.19 104.56
   Imbalance |  ----  ---- |  ----  ---- |  4.58  4.71
       Pawns |  0.00  0.00 | -0.08 -0.19 |  0.08  0.19
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Winnable |  ----  ---- |  ----  ---- | -0.57 -53.44
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | 100.28 56.02

Classical evaluation: 100.37 (white side)

NNUE evaluation:      13.54 (white side)

Final evaluation:     100.37 (white side)
```

**Comment by BM123499** [comment]
Winnable will be negative if sf is less than 1, but as I said it's a trick for endgames, on the start of a game it's much less impacting. I believe SF did this because some endgames are drawish even though it has better evaluation, so scaling solves problems like this. It's a trick, `Winnable` there is just subtracting endgame eval (with scaling) from endgame eval (without scaling). So if scaling is less than 1, the value in `Winnable` will be negative. Plus, if endgame eval is bigger, `Winnable` is also bigger. So this position that are shown in this issue has a big Value for endgames. That's why Winnable has a big negative value.

**Comment by BM123499** [comment]
And all it's referencing White side, if we flip the side, it will be the opposite:

```
position fen rrrqkrrr/rrrrrrrr/8/8/8/8/7P/7K b kq - 0 1
eval
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled

     Term    |    White    |    Black    |    Total
             |   MG    EG  |   MG    EG  |   MG    EG
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | -96.19 -104.56
   Imbalance |  ----  ---- |  ----  ---- | -4.58 -4.71
       Pawns | -0.08 -0.19 |  0.00  0.00 | -0.08 -0.19
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Winnable |  ----  ---- |  ----  ---- |  0.57 53.44
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | -100.28 -56.02

Classical evaluation: -100.37 (white side)

NNUE evaluation:      -13.46 (white side)

Final evaluation:     -100.37 (white side)
```

**Comment by BM123499** [comment]
On the latest Winnable is positive. because it's adjusting the endgame value to real endgame value, and endgame is a big negative value, so it will make it smaller negative value, so it will have to be positive.

**Comment by BM123499** [comment]
`Winnable` is not a measure to know if a side is winning or not, but an adjust to pick the best favorable win. And the way SF does is scaling the endgame value between [0, 1].  On the last position, if `ScalingFactor` were 0.75, `Winnable` would be -27.37. and it would still be a big negative number. If `ScalingFactor` were 0.9, `Winnable` would be -10.44 and still a big negative number. It's just a point of view. The bigger the number, the bigger will be the difference when multiplied by another number.

So don't worry that it won't say that blacking is winning if endgame eval (without `ScalingFactor) says that white is winning.

**Comment by MichaelB7** [comment]
It is definitely mislabeled.  maybe it should be labeled  "Scaling adjustment"?  and a note "Used to pick most favorable win"

**Comment by xoto10** [comment]
I combined the old initiative() and scale_factor() functions in an effort to encourage work on any overlapping factors in those functions and called the new function winnable(). So this factor includes initiative and scale_factor adjustments which both try to optimise sf's chances of winning (aiming for a winning position if possible / avoiding a drawing one, obv opposite if losing).

I wasn't particularly happy with that name and expected some debate on it, but it stuck. Anyway, the name of the function doesn't have to be used in the "eval" output, if we can decide on better text to output we can use that and just put it into the small changes PR.
How about "Win Scaling"?

**Comment by Lolligerhans** [comment]
IMHO adjusting terms to be more intuitive in positions with **30 pawns material imbalance** is rather useless.

Note that since the merge this function also includes "**complexity**" which clamps MG and EG values into some a range [-complex, complex]. This will also have a net-negative impact, especially when complexity is low, and is quite **different to a scaling**.

The problem arises from the fact that the bonus is applied as a scaling. But for outputting, an explicit effort is made to retrieve the  score difference instead. **Outputting the scale factor** in the first place will resolve this problem, independent of naming.

`Winnable |              0.75 %       |  0.57 53.44`

One could even show the scaling **graphically**

```
     Term    |    White    |    Black    |    Total
             |   MG    EG  |   MG    EG  |   MG    EG
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | -96.19 -104.56
   Imbalance |  ----  ---- |  ----  ---- | -4.58 -4.71
       Pawns | -0.08 -0.19 |  0.00  0.00 | -0.08 -0.19
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 ------------+-------------+-------------+------------
             | 0           1           2 |  0.57 53.44
    Winnable |         ^                 |  = 75%
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | -100.28 -56.02
```

**Comment by xoto10** [comment]
As @Lolligerhans noted:

> Note that since the merge this function also includes "complexity" which clamps MG and EG values into some a range [-complex, complex]. This will also have a net-negative impact, especially when complexity is low, **and is quite different to a scaling**.

My with the change was to combine the complexity and scale_factor calculations to look for benefits, so the end result is calculated using addition _and_ scaling. Of course, we can present this output how we want, it doesn't have to match the internal code, so we could present it as a difference, or as a scaling factor.

A problem with the graphical scaling Loll illustrated above is that in theory the mg value can change (via complexity) as well as the eg value. 

We could output the total before the winnable function, then the winnable adjustments might make more sense. e.g. Using an extreme example from above, and the label "Draw / Win" to try and emphasise the purpose of this adjustment, we could have:

```
position fen 7k/7p/8/8/8/8/RRRRRRRR/RRRQKRRR w KQ - 0 1
eval
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled

     Term    |    White    |    Black    |    Total
             |   MG    EG  |   MG    EG  |   MG    EG
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | 96.19 104.56
   Imbalance |  ----  ---- |  ----  ---- |  4.58  4.71
       Pawns |  0.00  0.00 | -0.08 -0.19 |  0.08  0.19
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 ------------+-------------+-------------+------------
    SubTotal |  ----  ---- |  ----  ---- | 100.85 109.46
    Draw/Win |  ----  ---- |  ----  ---- | -0.57 -53.44
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | 100.28 56.02

```

In theory, the winnable adjustment can increase the valuation, but in practice I think this is very rare, so the adjustment is usually towards zero, the interesting thing is how big the adjustment is, e.g. only shaving 5% off the valuation indicating good winning chances, or slashing 75% off indicating a large risk of a draw.

Another example:
```
position fen 1n2k1n1/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQ - 0 1
eval
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled
     Term    |    White    |    Black    |    Total
             |   MG    EG  |   MG    EG  |   MG    EG
 ------------+-------------+-------------+------------
    Material |  ----  ---- |  ----  ---- | 32.07 34.50
   Imbalance |  ----  ---- |  ----  ---- |  1.85  1.79
       Pawns |  0.38 -0.08 |  0.38 -0.08 |  0.00  0.00
     Knights |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
    Mobility |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 King safety |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
     Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
      Passed |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
 ------------+-------------+-------------+------------
    SubTotal |  ----  ---- |  ----  ---- | 33.91 36.29
    Draw/Win |  ----  ---- |  ----  ---- |  0.00 -11.78
 ------------+-------------+-------------+------------
       Total |  ----  ---- |  ----  ---- | 33.91 24.51
```
Many ways to display equivalent data, and people will have different preferences, but if we can find something people think is more intuitive, let's do it.

**Comment by Lolligerhans** [comment]
Clarification: I meant to only show the actual `scaling factor` as percentage of the default 64 and the `complexity` adjustment regularly. That was misrepresented in my diagram later. So basically treat them individually like they are interpreted rather than insisting on a single combined representation.

**Comment by xoto10** [comment]
Sure. We can make various suggestions and hopefully we'll find something people are happy with.

My view is that the winnable calculation could get arbitrarily complicated in the future, and we should just display the adjustment that is calculated. King Safety has a very complicated calculation, but we don't attempt to list the details, we just display the end result. I admit that in this case, there is a case for displaying it as a scaling factor rather than as the usual difference - I'm happy to go with whatever maintainers / users prefer.
