### ISSUE TITLE
Found Mistake of Stockfish 13 while playing English opening

### ISSUE THREAD

**Issue by Matrix07** [official-stockfish/Stockfish#3376]
[Matrix07 English opening.zip](https://github.com/official-stockfish/Stockfish/files/6056398/Matrix07.English.opening.zip)
While playing English opening Stockfish 13 miscalculate 

r1b1k2r/pppp1ppp/8/4P1B1/1bP1q3/2N3P1/PP2QP1P/R3KB1R b KQkq - 0 11

Here is the position ,Stockfish 13 in black loose after black Queen hits the Rook on h1.
![Screenshot_20210227-191028](https://user-images.githubusercontent.com/79755166/109390287-ba8e1280-7936-11eb-9b61-4b804c7ce6bc.png)

**Comment by Sopel97** [comment]
```
info depth 26 seldepth 50 multipv 1 score cp 44 nodes 9307709 nps 190528 hashfull 1000 tbhits 0 time 48852 pv b4c3 b2c3 e4h1 g5f6 e8f8 e1c1 h1c6 f6d8 b7b6 e2d2 d7d6 e5d6 c6d6 d8c7 d6d2 d1d2 c8e6 c7d6 f8g8 c4c5 b6c5 d6c5 f7f6 f1g2 a8c8 g2b7 c8c5 d2d8 g8f7 d8h8
```
not an issue

**Comment by Matrix07** [comment]
Stockfish 13 lost

**Comment by Matrix07** [comment]
@sopel97

Stockfish 13 lost. 

 @Corteum9000 
 [Event "IndianDon"]
 [Site ""]
 [Date "2021.02.25"]
 [Round "5"]
 [White "Matrix07"]
 [Black "Stockfish 13"]
 [Result "1-0"]
 [TimeControl "15+1"]

1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. e4 Bc5 5. Nxe5 Nxe5 6. d4 Bb4 7. dxe5 Nxe4 8.
Qf3 Qh4 9. g3 Ng5 10. Qe2 Qe4 11. Bxg5 Bxc3+ 12. bxc3 Qxh1 13. f3 b6 14. O-O-O
Bb7 15. Bg2 Qxh2 16. Qd2 O-O 17. Bh4 Bxf3 18. Bxf3 Qxd2+ 19. Rxd2 Rae8 20. Rd5
f6 21. exf6 Re3 22. Bg4 Rxc3+ 23. Kd2 Rxc4 24. Bd1 Rxh4 25. gxh4 d6 26. Bb3 Kh8
27. Rd4 Rxf6 28. Re4 h5 29. Re7 Kh7 30. Ke3 c6 31. Rxa7 Kh6 32. Ra8 d5 33. Rb8
b5 34. Kd4 Rf4+ 35. Kc5 Rxh4 36. Kxc6 b4 37. Bxd5 g5 38. Kc5 Rh2 39. Kxb4 Rb2+
40. Bb3 g4 41. a4 Rb1 42. a5 Ra1 43. Rg8 Kh7 44. Kb5 Rc1 45. a6 Ra1 46. Bd5
Rb1+ 47. Kc6 Rc1+ 48. Kb7 Rb1+ 49. Kc6 Ra1 50. Kb7 Rb1+ 51. Ka8 Rb5 52. Bf7 Kh6
53. a7 Rb2 54. Bd5 Rb4 55. Bc6 Rb2 56. Bb7 Kh7 57. Rd8 g3 58. Kb8 Ra2 59. a8=Q
Rxa8+ 60. Kxa8 Kg7 61. Rd3 h4 62. Rd4 h3 63. Rg4+ Kf6 64. Rxg3 h2 65. Rh3 Ke5
66. Rh4 h1=R 67. Bxh1 Kf5 68. Bf3 Kg5 69. Ra4 Kf5 70. Bh1 Ke5 71. Kb7 Kf5 72.
Kc6 Kg6 73. Kd7 Kf5 74. Ke7 Ke5 75. Bf3 Kf5 76. Re4 Kg6 77. Ke6 Kg5 78. Rg4+
Kh6 79. Kf6 Kh7 80. Bd5 Kh8 81. Rh4+ 1-0

**Comment by Matrix07** [comment]
[Uploading Matrix07 English opening.zip…]()

**Comment by Matrix07** [comment]
@sopel97 
b4 c3 is not a legal move , I think u get wrong position

**Comment by Torom** [comment]
b4c3 is legal, this is the 11. ... Bxc3+ move from your PGN. Your screenshot does not show the move that was actually played.

However, Stockfish really seems to have some problems understanding the position ~~with relatively few nodes~~. In a short analysis with 50M nodes per move (probably more than his smartphone ever reaches) Stockfish is surprised by 10. Qe2. Going back from there, 8. ... Qh4 is already a mistake. 8. ... Nxc3 would probably be 0.0, while 8. ... Qh4 is rated +1.25 (white POV, and going backwards). But 8. ... Qh4 is the move Stockfish wants to play, even after a longer search on my system:

`info depth 45 seldepth 48 multipv 1 score cp 0 nodes 1084219901 nps 8416745 hashfull 1000 tbhits 0 time 128817 pv d8h4 g2g3 e4g5 f3d5 h4e4 e1d1 b4c3 b2c3 d7d6 f1d3 e4f3 d5f3 g5f3 e5d6 c7d6 c1f4 c8g4 d3e2 f3e5 f4e5 g4e2 d1e2 d6e5 h1d1 a8c8 d1d5 c8c4 d5e5 e8d7 a1d1 d7c8 e5e7 c4c7 e7c7 c8c7 d1d4 h8e8 e2d3 e8e7 d4g4 f7f6 h2h4 h7h5 g4e4 e7d7 e4d4 d7e7`

. 10. Qe2 is the move Stockfish misses.
Interestingly, the size of the hash has a big influence on whether the right move is found, the first search I did was with 512 MB hash, this one is with 16 GB:

`
info depth 39 seldepth 52 multipv 1 score cp 0 nodes 751042731 nps 8622961 hashfull 360 tbhits 0 time 87098 pv e4c3 b2c3 b4a5 f1e2 d7d6 f3g3 e8g8 c1h6 a5c3 g3c3 g7h6 a1d1 d8g5 e5d6 f8e8 e1g1 e8e2 d6d7 c8d7 d1d7 a8e8 c3f3 e8e7 d7c7 e7c7 f3e2 g5f4 e2b2 c7c4 b2b7 g8g7 b7a7 c4a4 a7d7 a4a2 d7d1 f4e4 h2h3 e4c4 d1e1 c4c5 e1e3 c5e3 f2e3`

**Comment by Matrix07** [comment]
@Torom Yes,  I played Qe2 manually to see how Stockfish respond , while Stockfish suggested to go for Qd5 for white on 10th. Move

**Comment by Batu-64** [comment]
**The 32-bit engine is not installed in Windows XP.** 
![12](https://user-images.githubusercontent.com/46775864/109471275-9b4fcc00-7a81-11eb-8db8-184541f5bf17.png)

**Comment by ststockfish** [comment]
Could you tell me the best setting method for DroidFish?

**Comment by vondele** [comment]
I'll close this, as poor moves on individual positions are not bugs. As the engine improves they will become more and more rare.
