### ISSUE TITLE
32 bit engine not compatible with Windows XP

### ISSUE THREAD

**Issue by Batu-64** [official-stockfish/Stockfish#3379]
![12](https://user-images.githubusercontent.com/46775864/109472705-87a56500-7a83-11eb-9813-defa9aba0ec7.png)
Please do not neglect XP users. Thanks.

**Comment by mega-optimus** [comment]
Looks like missing some dependent library.

**Comment by Batu-64** [comment]
All versions of the .Net Framework and Visual C ++ are already installed. 
![1](https://user-images.githubusercontent.com/46775864/109670062-cf131a80-7b83-11eb-9f70-0abe3226284f.jpg)

**Comment by Batu-64** [comment]
All versions of Net Framework and Visual C ++ were preinstalled.
![123](https://user-images.githubusercontent.com/46775864/109685514-61bab600-7b92-11eb-9c60-5833966431f1.jpg)

**Comment by mega-optimus** [comment]
I installed XP on a virtual machine and tried out the 32 bit exe, it shows the error "The procedure entry point GetLargePageMinimum could not be located in the dynamic link library KERNEL32.dll". It appears that the [GetLargePageMinimum()](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-getlargepageminimum) function is only available for Vista and above.

**Comment by acdemiralp** [comment]
Philosophically related: http://lkml.iu.edu/hypermail/linux/kernel/2005.3/08168.html

**Comment by noobpwnftw** [comment]
https://github.com/official-stockfish/Stockfish/pull/3380

Hope this solves the issue.

**Comment by Batu-64** [comment]
I just wanted to report the bug. I have no software development or programming knowledge. I hope the problem will be solved.  I wish you good works.
