### ISSUE TITLE
Cannot have contempt off as default in CB13 with SF13

### ISSUE THREAD

**Issue by GunnarAndersen** [official-stockfish/Stockfish#3381]
Hi, 

For some reason it is not possible for me to turn contempt off when using SF13. I was able to get this to work with SF12 as well as SF11, I am wondering if it is not allowed to turn contempt off?

Here is how I am attempting to turn contempt off using CB13 as my interface: 
From the home pane, I go to "Add Kibitzer" and select SF13. From there, I go to "Advanced" and then I go to "Engine Parameters", Analysis contempt is set to "Both" so I set it to "Off" Instead. From there I either click "OK" or "Save" and save it as an engine parameter- however it does not keep this setting at all, and when I am analyzing I find that it contempt is definitely on. One thing I have been able to do is save this as a parameter and load it into SF13, but I was wondering if there is a way to have Contempt Analysis Off as the default?

**Comment by Sopel97** [comment]
You need to change it in the code and recompile.

**Comment by vondele** [comment]
This really is a GUI issue, but of course one can work around by changing the code. This is not something we should change in the code IMO.
