### ISSUE TITLE
min value of UCI_Elo

### ISSUE THREAD

**Issue by ScarecrowY** [official-stockfish/Stockfish#3387]
When I am using the python-chess library, I got an error of ```chess.engine.EngineError: expected value for option 'UCI_Elo' to be at least 1350```. May I ask why the min value is set as 1350? I thought a beginner's rating could be lower than that...

**Comment by vondele** [comment]
At the TC where UCI_Elo is calibrated, the weakest level of play reachable is 1350...

**Comment by ScarecrowY** [comment]
Sorry I am not familiar with this... What is TC? May I ask where I could read the relevant material?

**Comment by vondele** [comment]
TC = time control. 

The pull request had some discussion, should be #2225

**Comment by ScarecrowY** [comment]
Is the rating in Stockfish different than other Elo rating systems? From what I searched, a novice's elo could be lower than 1000...

**Comment by vondele** [comment]
well the conditions of a match affect the computed Elo difference. What I'm saying is that probably SF is stronger than beginners even at its 'Skill Level' corresponding to worst play. 

One could make SF weaker, by giving it much less time than the human.

**Comment by ScarecrowY** [comment]
Yeah I was thinking the engine could match with any rating... Thanks for your explanation!
