### ISSUE TITLE
Skill level and time per move.

### ISSUE THREAD

**Issue by 9acca9** [official-stockfish/Stockfish#3401]
Hello.
I would like to ask if someone could explain to me how the question about the "skill level" option is. If I set the "thought" time of stockfish to 5 seconds per move ... it varies that it also indicates skill level = 1 or 20 ????
Won't it always be a relatively bad play (if you run on a basic computer)? or does the skill level option still have any relevance?
Thanks

**Comment by gvreuls** [comment]
The [Readme.md](https://github.com/official-stockfish/Stockfish#skill-level) document covers this quite well. the skill level is independent of the thinking time. If you set a skill level other than 20, stockfish doesn't just search for the best move but also for the second best move, 3rd best move and 4th best move, and if you set MultiPV to a number higher than 4 even for worse moves. The lower you set the skill level, the higher the chance stockfish will pick a move other than the best move from the results of those 4 or more simultaneous searches.

**Comment by vondele** [comment]
very high skill levels needs some minimum time (enough to reach depth 20 or so), but for the lower ones the time per move has almost no effect.
