### ISSUE TITLE
Compiling with embedded net fails for ARCH=x86-32

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#3409]
I have tried this on my system (gcc-10 on Mac, but may well be the same on other OS):

```
make clean
make build ARCH=x86-32
```

Compilation fails with the following error for evaluate.cpp:

```
/var/folders/74/v0ky243d0fldg6cfzmy359wm0000gn/T//ccGLlABN.s:13:7: error: Section too large, can't encode r_address (0x140c7f0) into 24 bits of scattered relocation entry.
.long _gEmbeddedNNUEEnd - _gEmbeddedNNUEData
      ^
make[1]: *** [evaluate.o] Error 1
make: *** [build] Error 2
```

The problem seems to be that the size of the embedded net is too large to be calculated by the assembly magic code of incbin/incbin.h, for the versions of ints and longs used by the 32bits arch of that gcc compiler.

**Comment by snicolet** [comment]
As this is not a very important issue, it may be sufficient to advise people still compiling for 32bits not to embed the net in the binary, using the NNUE_EMBEDDING_OFF compile flag in evaluate.cpp

Stockfish would still be usable with NNUE, if the net is located in the same directory as the engine.

**Comment by Fanael** [comment]
Seems like an issue with Mach-O, not stockfish, as NNUE embedding works fine on ELF or PE/COFF platforms with 32-bit targets.

**Comment by snicolet** [comment]
Probably an issue with Mach-o, so closing
