### ISSUE TITLE
Feature request: Lower ELO rating

### ISSUE THREAD

**Issue by mickkn** [official-stockfish/Stockfish#3410]
Hi, would it be possible to lower the min. value for UCI_Elo?

Down to something like 600, beginner/kids level. Maybe lower.

**Comment by laripette** [comment]
Hello,

you have this very weak engine for beginners.
https://sourceforge.net/projects/belofte/files/dist/

or if not you have this site:
https://www.chess.com/fr/play/computer

**Comment by mickkn** [comment]
Thanks for the reply, wasn't clear enough :) I need it on my Raspberry Pi Zero W driven chessboard project. Found the Minic engine, which seems to be optioned to play very week.
