### ISSUE TITLE
Affine transform saturation happy path optimization considered harmful.

### ISSUE THREAD

**Issue by Sopel97** [official-stockfish/Stockfish#3431]
The net from this test https://tests.stockfishchess.org/tests/view/607850758141753378960762 is significantly slower than it should be. It has 8*3 layers in total, and I found that it has a good amount of entries in the canSaturate16 array (https://github.com/official-stockfish/Stockfish/blob/a7ab92ec25c91e8413630c52cfc2db6b4ecacf0c/src/nnue/layers/affine_transform.h#L444-L458). My net is of a weird architecture and it allowed me to effectively test 8 different networks (all coming from one) to look at the correlation between the canSaturate16.count and the speed. These are my findings:

![obraz](https://user-images.githubusercontent.com/8037982/114928588-0f2c1500-9e33-11eb-8328-ea048c3a5430.png)

First column is the canSaturate16.count, second is the speed on my i7-920 from bench (note that I disabled hybrid eval for this), third is speed from 10M node search from startpos. There is 8 rows, corresponding to 8 different nets. The 3x3 matrix below is the correlation matrix. (bench speeds are somewhat noisy because just one run and windows console)

It's really sad that optimisations have potential to prevent innovation by pessimizing new networks randomly. This was hard to narrow down and I wonder how many other quirks there are that I have not yet found. I suggest the change that introduced it to either be reverted, or a fallback to the old way of doing the affine transform is added when the canSaturate16.count crosses a certain threshold (it's already very visible with 1%, probably would have to be less than 0.2%).

PS. For comparison, the `canSaturate16.count` is 1 for the whole master network.

**Comment by Sopel97** [comment]
I *think* this is correct https://tests.stockfishchess.org/tests/view/607ae013162adf76afa5b87d, and doesn't look much worse.

**Comment by MichaelB7** [comment]
I agree with @Sopel97 concerns and using his suggested patch showed no slowdown on my custom 96 position bench, it was actually a tad faster, but not statistically significant

no patch
```
=================================
Total time (ms) : 523523
Nodes searched  : 1424521485

Nodes/second    : 2721029
```

patch
```
=================================
Total time (ms) : 523095
Nodes searched  : 1424521485

Nodes/second    : 2723255

**Comment by snicolet** [comment]
Has this issue been solved by https://github.com/official-stockfish/Stockfish/commit/b748b46714d5f8e0acca0a042ede1fc95e4f5190 ?

**Comment by Sopel97** [comment]
No, this is not solvable without impacting the speed of the current master on some CPUs. The only way to fix it is to revert the optimization when the need arises (i.e. a new net that's good enough to beat master).

**Comment by snicolet** [comment]
@Sopel97 I would like to close this issue, if possible. Is it still relevant after the net architecture change?

**Comment by Sopel97** [comment]
This code was removed. Can be closed, at least for now
