### ISSUE TITLE
Learning the CLI Options

### ISSUE THREAD

**Issue by michaeleisel** [official-stockfish/Stockfish#3446]
I'm trying to learn the usage of the CLI tool, and can't find any obvious resources to help me. If I try `./stockfish`, `./stockfish --help`, or `./stockfish help`, I don't get anything. I don't see a man page. I don't see any links to any usage guides in the readme or on stockfishchess.org . Can anyone point to where I can learn the usage? And maybe it'd help others in the future to share this resource better?

**Comment by vondele** [comment]
stockfish implements the UCI protocol http://wbec-ridderkerk.nl/html/UCIProtocol.html those are the commands that can be used with the engine.

**Comment by michaeleisel** [comment]
Got it. I think it would be helpful to explain that explicitly somewhere. "UCI" is mentioned repeatedly, but the significance of UCI is not. In any case, this solves things for me 👍

**Comment by MichaelB7** [comment]
Just FYI, when something is mentioned repeatedly, it usually means it is important. Repetition was  often used in the  classical languages to signal importance.   Greek, Hebrew, Latin etc.
