### ISSUE TITLE
not able to compile stockfish 

### ISSUE THREAD

**Issue by chessinfo99** [official-stockfish/Stockfish#3448]
i tried to compile stockfish for the 5th time and it gave me an error , can someone help me?

**Comment by vondele** [comment]
you'll need to share the error, otherwise that will be difficult. Similarly, some information on the OS will be needed (windows, linux, etc).

**Comment by chessinfo99** [comment]
oh.ok

**Comment by chessinfo99** [comment]
s\Github\Stockfish\Source-c>make profile-build ARCH=x86-64 COMP=mingw
'make' is not recognized as an internal or external command,
operable program or batch file. this is the error i get every time i try to compile it :(

**Comment by chessinfo99** [comment]
i tried it again but it says the same

**Comment by eikoemrich** [comment]
thats powershell ; try first cmd and then the make....
Eiko

**Comment by gvreuls** [comment]
- Did you install MSYS2? If you didn't, you need to install MSYS2 as described [here](https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows). 
- After installing MSYS2 you need to run MSYS2 shell to compile stockfish
- If you don't want to use the MSYS2 shell but the Windows shell (CMD) instead you need to add the MSYS2 directories to your path so Windows can find ``make`` and the other MSYSY2 applications, in general:
``SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%``

**Comment by chessinfo99** [comment]
i have downloaded MSYS2

**Comment by chessinfo99** [comment]
i have downloaded MSYS2

**Comment by chessinfo99** [comment]
> thats powershell ; try first cmd and then the make....
> Eiko

i tried it on command prompt , i dont use powershell

**Comment by gvreuls** [comment]
Please be more specific, we can't help you if you don't tell us what you did. In what directory did you install MSYS2?

As I wrote before, if you want to use the Windows command prompt/shell you need to tell Windows where the MSYS2 programs are by setting your ``PATH``. So if you installed MSYS2 in the ``C:\msys64`` directory as the installer suggests, you need to start the Windows command prompt and on the prompt you first type:
``SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%``
and then try
``make profile-build ARCH=x86-64 COMP=mingw``

If this works you can put both lines in a .bat file so you can start that batch file instead of typing the commands every time.

If this doesn't work, you installed MSYS2 to a different directory and you should use that directory instead of ``C:\msys64`` in the set command above.

**Comment by chessinfo99** [comment]
i tried it on msys2 after watching a vid , it says make help : command not found

**Comment by chessinfo99** [comment]
> Please be more specific, we can't help you if you don't tell us what you did. In what directory did you install MSYS2?
> 
> As I wrote before, if you want to use the Windows command prompt/shell you need to tell Windows where the MSYS2 programs are by setting your `PATH`. So if you installed MSYS2 in the `C:\msys64` directory as the installer suggests, you need to start the Windows command prompt and on the prompt you first type:
> `SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%`
> and then try
> `make profile-build ARCH=x86-64 COMP=mingw`
> 
> If this works you can put both lines in a .bat file so you can start that batch file instead of typing the commands every time.
> 
> If this doesn't work, you installed MSYS2 to a different directory and you should use that directory instead of `C:\msys64` in the set command above.

i tried it again but it says the same  ,   i installed msys2 in windows c folder https://imgur.com/7CXzRqf see this image , this is what i get everytime :(

**Comment by joergoster** [comment]
@chessinfo99 You must open a msys2 terminal first.
Start -> MSYS2 64bit -> MSYS2 MinGW 64-bit

**Comment by chessinfo99** [comment]
oh.ok.

**Comment by chessinfo99** [comment]
i've opened it

**Comment by joergoster** [comment]
Navigate to the folder with the source files, and try to compile. Good luck.

P.S. There is a script available on the internet which will modify the registry and allows you to open a msys2 shell from every location.

**Comment by chessinfo99** [comment]
oh. , thnx 😄

**Comment by chessinfo99** [comment]
i tried it but again it says the same thing , i followed every step but.... 😢 😭

**Comment by chessinfo99** [comment]
😃 i tried it and now it's done :) but i've not got the exe file yet 😭

**Comment by MichaelB7** [comment]
You need to crawl before you walk.  You will be better serve going to Msys2 to ask for help and doing some basics, like compiing "Hello World".
Once you can compile "Hello World" we will be able to help you.

**Comment by chessinfo99** [comment]
well nvm , thnx to all of them who helped me :) i was able to compile them 😄   , one of my friend said that  after stockfish is compiled  nnue is disabled by default , is it?
