### ISSUE TITLE
VNNI builds slowdown

### ISSUE THREAD

**Issue by JavaMast** [official-stockfish/Stockfish#3457]
**CPU: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz**

Worker started in C:\Users\User\Downloads\worker-setup-master\worker-setup-master\worker ...

Memory: 34189570048
Found g++ version 10.3
Worker version 98 connecting to [url]https://tests.stockfishchess.org:443[/url]
UUID: 83ad22f3-18b0-4319-8f2a-1903da5c48f9
Start heartbeat
Fetch task...
API call rate limits: {'limit': 60, 'remaining': 60, 'reset': 1620402920, 'used': 0, 'resource': 'core'}
Worker version checked successfully in 0.200622s
Task requested in 0.464726s
Build uses default net:  nn-62ef826d1a6d.nnue
Available Makefile architecture targets:  ['x86-64-vnni512', 'x86-64-vnni256', 'x86-64-avx512', 'x86-64-bmi2', 'x86-64-avx2', 'x86-64-sse41-popcnt', 'x86-64-modern', 'x86-64-ssse3', 'x86-64-sse3-popcnt', 'x86-64', 'x86-32-sse41-popcnt', 'x86-32-sse2', 'x86-32', 'ppc-64', 'ppc-32', 'armv7', 'armv7-neon', 'armv8', 'apple-silicon', 'general-64', 'general-32']
Available g++/cpu properties:  {'flags': ['-m128bit-long-double', '-m64', '-m80387', '-mabm', '-maccumulate-outgoing-args', '-madx', '-maes', '-malign-double', '-malign-stringops', '-mavx', '-mavx2', '-mavx256-split-unaligned-load', '-mavx256-split-unaligned-store', '-mavx512bitalg', '-mavx512bw', '-mavx512cd', '-mavx512dq', '-mavx512f', '-mavx512ifma', '-mavx512vbmi', '-mavx512vbmi2', '-mavx512vl', '-mavx512vnni', '-mavx512vpopcntdq', '-mbmi', '-mbmi2', '-mclflushopt', '-mcx16', '-mf16c', '-mfancy-math-387', '-mfentry', '-mfma', '-mfp-ret-in-387', '-mfsgsbase', '-mfxsr', '-mgfni', '-mhard-float', '-mhle', '-mieee-fp', '-mlong-double-80', '-mlzcnt', '-mmmx', '-mmovbe', '-mms-bitfields', '-mpclmul', '-mpe-aligned-commons', '-mpopcnt', '-mprfchw', '-mpush-args', '-mrdpid', '-mrdrnd', '-mrdseed', '-mred-zone', '-msahf', '-msha', '-msse', '-msse2', '-msse3', '-msse4', '-msse4.1', '-msse4.2', '-mssse3', '-mstack-arg-probe', '-mstackrealign', '-mvaes', '-mvpclmulqdq', '-mvzeroupper', '-mxsave', '-mxsavec', '-mxsaveopt', '-mxsaves'], 'arch': 'icelake-client'}
**Determined the best architecture to be  x86-64-vnni256**

But AVX512 is the fastest on my PC. 
Even BMI2 faster than vnni256

![Screenshot_90](https://user-images.githubusercontent.com/42765009/117478998-7b98c080-af68-11eb-9856-728b831f5c60.png)
![Screenshot_91](https://user-images.githubusercontent.com/42765009/117479001-7c315700-af68-11eb-8c41-738506b31c47.png)

**Comment by JavaMast** [comment]
@snicolet 
After "New NNUE architecture and net" https://github.com/official-stockfish/Stockfish/commit/e8d64af1230fdac65bb0da246df3e7abe82e0838 -vnni builds became even more slower

![Screenshot_112](https://user-images.githubusercontent.com/42765009/120472158-3cfef600-c3ae-11eb-8821-093711eae62c.png)
![Screenshot_113](https://user-images.githubusercontent.com/42765009/120472180-40927d00-c3ae-11eb-855b-4fdf64c810ec.png)

 Intel Core i5-11400F

**Comment by snicolet** [comment]
It is difficult to compare speed between compiles if the runs you use do not give the same signature. Better not to use multiple threads for your second bench command.

**Comment by JavaMast** [comment]
The second bench run is just "bonus", ignore it.

**Comment by JavaMast** [comment]
@snicolet  
This slowdown was introduced with "Affine transform refactoring." https://github.com/official-stockfish/Stockfish/commit/23c385ec36f9d5a9514ec5b0811ec99d08b45e90 @MaximMolchanov

![Screenshot_123](https://user-images.githubusercontent.com/42765009/121399622-47496300-c95f-11eb-928d-f89564e96d8d.png)

1-4 before this commit
5-8 after

**Comment by Sopel97** [comment]
The issue is probably cased by the current affine transform code requiring more memory operations compared to computation when using VNNI compared to AVX2/AVX512. The commit in question pretty much traded hadds for more memory operations, which probably was not a good tradeoff for VNNI

**Comment by JavaMast** [comment]
Looks like it fixed after https://github.com/official-stockfish/Stockfish/commit/d61d38586ee35fd4d93445eb547e4af27cc86e6b

https://github.com/official-stockfish/Stockfish/pull/3663#issuecomment-900516544
