### ISSUE TITLE
build  .so  failure   on android  studio 

### ISSUE THREAD

**Issue by shoulderdh** [official-stockfish/Stockfish#3465]
i can't build  .so   on android  studio  ,   ndk-build ;    the log is like this:

`Android NDK:   stockfish/nn-62ef826d1a6d.nnue    
[arm64-v8a] Compile++      : aa <= benchmark.cpp
[arm64-v8a] Compile++      : aa <= bitbase.cpp
[arm64-v8a] Compile++      : aa <= bitboard.cpp
[arm64-v8a] Compile++      : aa <= endgame.cpp
[arm64-v8a] Compile++      : aa <= evaluate.cpp
<inline asm>:6:9: error: Could not find incbin file 'nn-62ef826d1a6d.nnue'
.incbin "nn-62ef826d1a6d.nnue"
        ^
1 error generated.
`

and  i have  download  nn-62ef826d1a6d.nnue  file  put the  lib,   
![image](https://user-images.githubusercontent.com/14287365/118259100-51547f00-b4e3-11eb-8ff8-b738cfbaaa5d.png)

help me ,thank you very much.

**Comment by MichaelB7** [comment]
If you are stuck, simply turn embedding off and copy the nnue file to the device.  Not sure why it is not working for you though.  My guess is that it is a path issue of some sort.

**Comment by snicolet** [comment]
@shoulderdh Any update on this issue? Did you manage to compile?

**Comment by shoulderdh** [comment]
i can't   success.  Did anyone import it successfully?

**Comment by shoulderdh** [comment]
> @shoulderdh Any update on this issue? Did you manage to compile?

i really want android  simple

**Comment by ppigazzini** [comment]
The wiki has now the instruction to build Stockfish for Android with NDK:

https://github.com/glinscott/fishtest/wiki/Cross-compiling-Stockfish-for-Android-on-Windows-and-Linux

You can try also the script to cross compile with Zig:

https://github.com/glinscott/fishtest/wiki/Advanced-topics#cross-compilation-for-all-platform-using-zig-toolchain

**Comment by vondele** [comment]
I'll close it for now, the instructions are good to build a binary for android. Right now, stockfish can't be complied in a .so (shared library).
