### ISSUE TITLE
Can't Compile Stockfish

### ISSUE THREAD

**Issue by galacticue06** [official-stockfish/Stockfish#3469]
> Step 1/4. Building instrumented executable ...
> make ARCH=x86-64 COMP=mingw gcc-profile-make
> make[1]: Entering directory '/C/Users/****/Desktop/Stockfish-master/src'
> make ARCH=x86-64 COMP=mingw \
> EXTRACXXFLAGS='-fprofile-generate' \
> EXTRALDFLAGS='-lgcov' \
> all
> make[2]: Entering directory '/C/Users/****/Desktop/Stockfish-master/src'
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2   -c -o benchmark.o benchmark.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2   -c -o bitbase.o bitbase.cpp
> make[2]: g++: No such file or directory
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSE2 -msse2   -c -o bitboard.o bitboard.cpp
> make[2]: g++: No such file or directory
> make[2]: *** [<builtin>: benchmark.o] Error 127
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [<builtin>: bitbase.o] Error 127
> make[2]: g++: No such file or directory
> make[2]: *** [<builtin>: bitboard.o] Error 127
> make[2]: Leaving directory '/C/Users/****/Desktop/Stockfish-master/src'
> make[1]: *** [Makefile:880: gcc-profile-make] Error 2
> make[1]: Leaving directory '/C/Users/****/Desktop/Stockfish-master/src'
> make: *** [Makefile:740: profile-build] Error 2
> Makefile.sh: line 38: strip: command not found
> mv: cannot stat 'stockfish.exe': No such file or directory
> make: g++: No such file or directory
> make: g++: No such file or directory
>

I'm pretty sure that I'm following building steps as I'm supposed to but I get this error no matter what. I have tried compiling it with gcc too, but it says that gcc is not recognised as a command, even if I have installed it.

I'm using Windows 8.1 OEM version(64-bit) and MSYS2

Thanks in advance.

**Comment by MichaelB7** [comment]
You need to select  a build option, do "make clean , then "make help"  to see examples.   and then try a build using one of the examples.  As far not being to use gcc, that may be a Msys2 installation issue.  Msys2 site for adding gcc.  You may want to go into your "C:\Msys2" folder and if you see a shortcut  named "mingw-64" try it with with that as your terminal.  Type gcc --version on the command line to check if gcc is installed first.  If not installed, go to Msys2  for help and add all the appropriate gcc packages.     

Example:
`
$ gcc --version
gcc.exe (Rev11, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by galacticue06** [comment]
Thanks for your helps. It turns out that the issue I was facing with was caused by a 3rd party installation of MinGW. Deleted the MinGW and MSYS2 installation and reinstalled MSYS2. Issue seems to be solved
