### ISSUE TITLE
Problem compiling Stockfish 13 in Xcode Version 12.5 (12E262)

### ISSUE THREAD

**Issue by koaliemobile** [official-stockfish/Stockfish#3471]
Hello,

I am trying to integrate Stockfish-sf_13 into swift Xcode Project.
I have included all of stockfish 13 files into the project which also includes the `nn-62ef826d1a6d.nnue` file.
When I try to compile the project, I get this error: `Could not find incbin file 'nn-62ef826d1a6d.nnues' <inline asm>`
I also have my C++ Language Dialect in Xcode set to: c++ 17[-std=c++17]

Could someone please help me figure out this problem?

Thanks in advance

**Comment by gvreuls** [comment]
Did you try [these instructions](https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-macOS)?

**Comment by toludev** [comment]
@gvreuls I believe those instructions are for MacOS. I am trying to build for mobile iOS...

**Comment by snicolet** [comment]
Can you share your code? Thanks

**Comment by tillchess** [comment]
You need to put the nn-62ef826d1a6d.nnue file in the same directory like the source files. Don't add it to the project as a resource.

**Comment by bluepixelservices** [comment]
@tillchess

**Comment by tillchess** [comment]
@bluepixelservices is it on the same directory level like your *.xcodeproj file? 
Maybe in your case it should be in another directory...depends on your project structure on your hard-disk

**Comment by bluepixelservices** [comment]
@tillchess  we have put the file at the same directory as you suggest.
![image](https://user-images.githubusercontent.com/68892016/150085428-b01f1f6e-101d-4a9b-9a19-f0337af4b1ee.png)

**Comment by tillchess** [comment]
@bluepixelservices Post the error you see in Xcode or your project

**Comment by vondele** [comment]
I'll close the issue. Generally compiling with clang or gcc on macos with the provided makefile is no problem. For help building in other ways, feel free to discuss on our discord server.
