### ISSUE TITLE
Shift from Travis CI to GitHub CI Pipeline

### ISSUE THREAD

**Issue by TheYoBots** [official-stockfish/Stockfish#3487]
![433E6D83-82AB-4CDD-8124-5FCF24B36E54](https://user-images.githubusercontent.com/73843275/119168807-ef65bd80-ba7e-11eb-9652-676387855bb0.jpeg)

This is what I see on https://travis-ci.org/ (when signed out), it might be better to shift from Travis CI to GitHub CI Pipelines or anything else before Travis CI shuts down. See https://github.com/actions for GitHub CI Pipelines.

Or if I’m right to continue there requires a slight payment charge.

**Comment by vondele** [comment]
I agree we should eventually move to actions.

**Comment by snicolet** [comment]
There is an example using GitHub actions for stockfish here: https://github.com/official-stockfish/Stockfish/issues/2958

**Comment by vondele** [comment]
so travis now lists this `We're pushing back the shutdown date to June 15th`, which is very soon, meaning we will soon be without CI unless somebody can do (or help) with the migration.

**Comment by noobpwnftw** [comment]
https://www.travis-ci.com/plans
Doesn't it have a free plan we can use?

**Comment by vondele** [comment]
that would be another option to migrate to travis-ci.com, and we should be eligible for a free plan. We could look into that if we don't have an alternative GitHub actions setup.

**Comment by ddobbelaere** [comment]
Seems the migration is nothing more than a few steps (famous last words, I know) from a user that has administrator access to GitHub/Travis CI. See https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

No code changes (e.g. in .travis.yml) are involved.

**Comment by ianfab** [comment]
> Seems the migration is nothing more than a few clicks (famous last words, I know) from a user that has administrator access to Travis CI (and possibly also GitHub if access via "GitHub Apps" for Travis CI has not been enabled yet). See https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#the-migration-steps
> 
> No code changes (e.g. in .travis.yml) are involved.

I tried that out on my account and the migration seems to work smoothly in just a few minutes. However, Travis CI no longer has guaranteed free builds, you just get an initial amount of free credits and when they are used up you need to beg them for more OSS credits. So the migration can just buy some time for the switch to Github actions to avoid being temporarily without CI.

**Comment by ianfab** [comment]
Looks like the free credits are used up now: https://travis-ci.com/github/official-stockfish/Stockfish
> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

**Comment by snicolet** [comment]
This issue can be closed, obsoleted by https://github.com/official-stockfish/Stockfish/pull/3563

**Comment by TheYoBots** [comment]
Looking at the title, wasn’t it just a basic workflow? If that’s the case, I think it would be better to keep this open till a complete workflow has been implemented.

**Comment by vondele** [comment]
what makes a workflow complete, do you have suggestions? It does replace more or less what we had with travis.

There are many things we could do, probably best as separate issues, IMO.
