### ISSUE TITLE
Lazy NNUE eval doesn't respect "adjusted" parameter.

### ISSUE THREAD

**Issue by Sopel97** [official-stockfish/Stockfish#3495]
With the introduction of "entertainment" a `adjusted` parameter was added to the [nnue] evaluate function. The purpose is to keep the pure nnue eval pure. However the laziness doesn't respect this parameter. https://github.com/official-stockfish/Stockfish/blob/a2f01c07eb91524fc372bd82d6513ab058d3e043/src/nnue/nnue_feature_transformer.h#L187

**Comment by vondele** [comment]
this was fixed
