### ISSUE TITLE
Should "glinscott/nnue-pytorch" be moved to "official-stockfish/trainer"?

### ISSUE THREAD

**Issue by NightlyKing** [official-stockfish/Stockfish#3509]
Recently, the data generation code, that is part of nodchips repo, was ported to the "tools" branch of official-stockfish. Imho, it makes sense to have the trainer where the data generation is since those work as a unit. Also, I would rename it from "nnue-pytorch" to "trainer" or "nnue-training" to make it easy for "really new blood" to find all necessary parts to train new nets.

**Comment by Dboingue** [comment]
From a documentation point of view, I might help avoiding duplication of efforts. At least mine trying to get a global big picture of the relationship between optimized parameters in SF executable in relation to all matters of training and testing (NNue first, but also SF+NNue, and NNue off).   But also for those contributing to the documentation effort whoever they are and whatever level of expression.  If might also help contributors to code.  Unless "code is documentation" is a real thing.  Even programmers need to know where they are putting their feet into.... right?  Avoiding duplication and divergence of terminology that may be confusing (some divergence is unavoidable, but those that create confusion like  "optimization", training, testing, data generation.  self-play.  now that NNets are in the picture those terms should be confronted. At least for us outsiders looking in.

**Comment by vondele** [comment]
I think it is fine to keep it where it is right now... finding the repo is not the largest challenge in training a net :-)

Just for the record https://github.com/glinscott/nnue-pytorch/

**Comment by dav1312** [comment]
The repository is now in the organization https://github.com/official-stockfish/nnue-pytorch
