### ISSUE TITLE
compilation problem for os X gcc

### ISSUE THREAD

**Issue by MehdiMhalla** [official-stockfish/Stockfish#351]
Just to say that profile build failed with   gcc48 and gcc49 and gcc51  (osX 10.10.3)
for both build and profile-build

 the reason was g++: error: unrecognized command line option '-Wl'

PS: with clang only build worked (as usual)

Here is the message starting from the warning (same for the 3 gcc):

syzygy/tbprobe.cpp: In function 'probe_ab(Position&, int, int, int*)':
syzygy/tbprobe.cpp:206:14: warning: array subscript is above array bounds [-Warray-bounds]
         p[i++] = pop_lsb(&bb) ^ mirror;
              ^
syzygy/tbprobe.cpp:206:14: warning: array subscript is above array bounds [-Warray-bounds]
syzygy/tbprobe.cpp: In function 'Tablebases::probe_dtz(Position&, int*)':
syzygy/tbprobe.cpp:316:14: warning: array subscript is above array bounds [-Warray-bounds]
         p[i++] = pop_lsb(&bb) ^ mirror;
              ^
syzygy/tbprobe.cpp:316:14: warning: array subscript is above array bounds [-Warray-bounds]
g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o -lgcov -Wl -arch x86_64 -mmacosx-version-min=10.9 -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-generate -pedantic -Wno-long-long -Wextra -Wshadow -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -DUSE_BSFQ -flto
g++: error: unrecognized command line option '-Wl'
make[2]: *** [stockfish] Error 1
make[1]: *** [gcc-profile-make] Error 2
make: *** [profile-build] Error 2

**Comment by braich** [comment]
Remove [these lines](https://github.com/official-stockfish/Stockfish/blob/578b21bbeedc41b6e0d1b2df46887b1636a78e2b/src/Makefile#L157-L158) and rebuild.
[This commit](https://github.com/official-stockfish/Stockfish/commit/8fcaa78a042edd3f2ad1971e2e861aebab1379a4) seems to be the cause of the problem. 
-Wl Option is used [to pass options to the linker](https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gcc/Link-Options.html#index-Wl-1240) from gcc command line. From [this conversation](https://github.com/official-stockfish/Stockfish/pull/275) it is clear that --no-as-needed linker option must be removed for gcc compile in Darwin. So if no options must be passed to the linker then no need in -Wl option

**Comment by zamar** [comment]
Someone please verify that the fix suggested by braich fixes the problem for MacOSX and open a pull request.

**Comment by MehdiMhalla** [comment]
thx alot braich it (removing the else lines) indeed fixed the old error now it compiles for gcc48 
(there is a problem with gcc5 but it is a new error and much less relevant as now there is a way to have a profile build)
PS: for the gcc5 error it is
it goes over the complete bench however in the creation of exe step :
 Total time (ms) : 37097
Nodes searched  : 62254458
Nodes/second    : 1678153

Step 3/4. Building final executable ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make ARCH=x86-64-modern COMP=gcc gcc-profile-use
/Applications/Xcode.app/Contents/Developer/usr/bin/make ARCH=x86-64-modern COMP=gcc \
	EXTRACXXFLAGS='-fprofile-use -fno-peel-loops -fno-tracer' \
	EXTRALDFLAGS='-lgcov' \
	all
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wno-long-long -Wextra -Wshadow -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -DUSE_BSFQ -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o benchmark.o benchmark.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wno-long-long -Wextra -Wshadow -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -DUSE_BSFQ -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o bitbase.o bitbase.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wno-long-long -Wextra -Wshadow -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -DUSE_BSFQ -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o bitboard.o bitboard.cpp
g++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wno-long-long -Wextra -Wshadow -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -DUSE_BSFQ -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o endgame.o endgame.cpp
:492:FATAL:Symbol ___cold_sect_of_operator() already defined.
make[2]: *** [endgame.o] Error 1
make[1]: *** [gcc-profile-use] Error 2
make: *** [profile-build] Error 2
