### ISSUE TITLE
This FEN appears to crash the engine (not an issue: the FEN is illegal)

### ISSUE THREAD

**Issue by VanceAk** [official-stockfish/Stockfish#3519]
The following position:

2b1k1nB/1p3p1p/n4b2/1NPp4/P7/8/2r1PPPP/R3KBNR b KQk - 0 14

appears to crash the engine regularly on Windows. 

From stockfish_13_win_x64_bmi2.exe back to stockfish_8_x64.exe included.

**Comment by Fanael** [comment]
This FEN is illegal: black has no kingside rook to castle with, but the FEN specifies that black can still castle kingside. [Stockfish is not supposed to be fed illegal FENs](https://github.com/glinscott/fishtest/wiki/Fishtest-faq#why-does-sf-crash-on-incorrect-fen-or-fens-of-illegal-positions).

**Comment by VanceAk** [comment]
Thanks for checking this Fanael.  You are right. Thanks for checking.

**Comment by VanceAk** [comment]
not an issue: the FEN is illegal
