### ISSUE TITLE
the engine doesn't respond with bestmove

### ISSUE THREAD

**Issue by voyag** [official-stockfish/Stockfish#3532]
With the current development version, from console with the following commands the engine stall and doesn't respond with bestmove
`
setoption name Hash value 4
setoption name Contempt value 0
ucinewgame
position fen 8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 37 130
go depth 10
`

**Comment by locutus2** [comment]
Have you first insert the uci command?. SF responds then with the know options and uciok.
Second you have to insert the commands always in a separate line:

```
uci
setoption name Hash value 4
setoption name Contempt value 0
ucinewgame
position fen 8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 37 130
go depth 10
```

Then it works. Tested with the current master 'Reduce in LMR reduction on PvNode' (self compiled).
Here my output:

```
info string NNUE evaluation using nn-7e66505906a6.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp 119 nodes 23 nps 23000 tbhits 0 time 1 pv c3b4
info depth 2 seldepth 2 multipv 1 score cp 84 nodes 121 nps 60500 tbhits 0 time 2 pv c3b3 b7a8
info depth 3 seldepth 3 multipv 1 score cp 116 nodes 225 nps 112500 tbhits 0 time 2 pv g1b6 b7a8 c3b4
info depth 4 seldepth 4 multipv 1 score cp 125 nodes 298 nps 149000 tbhits 0 time 2 pv c3b3 b7a8 g1d4
info depth 5 seldepth 5 multipv 1 score cp 97 nodes 974 nps 487000 tbhits 0 time 2 pv g1b6 b7a8 c3d3 a8b7 b6e3
info depth 6 seldepth 6 multipv 1 score cp 132 nodes 1441 nps 480333 tbhits 0 time 3 pv g1c5 b7a8 c3d4 a8b7
info depth 7 seldepth 7 multipv 1 score cp 144 nodes 1834 nps 611333 tbhits 0 time 3 pv g1c5 b7a8 c3d4 a8b7 d4d5 b7a8
info depth 8 seldepth 10 multipv 1 score cp 425 nodes 3095 nps 773750 tbhits 0 time 4 pv g1b6 b7a8 c3d4 a8b7 d4c5 b7a8
info depth 9 seldepth 10 multipv 1 score cp 289 nodes 32586 nps 1629300 tbhits 0 time 20 pv g1c5 b7a8 c3d3 a8b7 d3e4 b7a8 e4f5 a8b7
info depth 10 seldepth 12 multipv 1 score cp 363 nodes 32739 nps 1636950 tbhits 0 time 20 pv g1c5 b7a8 c3d3 a8b7 d3e4 b7a8 e4f5
bestmove g1c5 ponder b7a8
```

**Comment by voyag** [comment]
Sure the version is changed, try those commands with the version: Makefile: Extend sanitize support

**Comment by snicolet** [comment]
@voyag I can't reproduce the problem on my Mac.

Could you please show us the `make` command you have used, and then the output of `./stockfish compiler` for your version? Thanks!

**Comment by voyag** [comment]
I have used this version from abrok: https://abrok.eu/stockfish/builds/3802cdf9b69dd0a8256dbed7c25141ac5757d151/linux64avx2/stockfish_21060511_x64_avx2.zip

**Comment by snicolet** [comment]
OK. Could you try the output of `./stockfish compiler`? Just to be sure that stockfish executable launches at all

**Comment by voyag** [comment]
Stockfish 050621 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 7.5.0 on Linux
Compilation settings include:  64bit AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 7.5.0

**Comment by locutus2** [comment]
I have compiled the same version by myself and i get a result but it stucks at depth 9 and we never reach depth 10 (at least not in the time i waited).

```
info string NNUE evaluation using nn-7e66505906a6.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp 119 nodes 23 nps 11500 tbhits 0 time 2 pv c3b4
info depth 2 seldepth 2 multipv 1 score cp 84 nodes 121 nps 60500 tbhits 0 time 2 pv c3b3 b7a8
info depth 3 seldepth 3 multipv 1 score cp 116 nodes 225 nps 112500 tbhits 0 time 2 pv g1b6 b7a8 c3b4
info depth 4 seldepth 4 multipv 1 score cp 125 nodes 298 nps 149000 tbhits 0 time 2 pv c3b3 b7a8 g1d4
info depth 5 seldepth 5 multipv 1 score cp 97 nodes 868 nps 289333 tbhits 0 time 3 pv g1b6 b7a8 c3d3 a8b7 b6e3
info depth 6 seldepth 6 multipv 1 score cp 132 nodes 1485 nps 495000 tbhits 0 time 3 pv g1c5 b7a8 c3d4 a8b7
info depth 7 seldepth 7 multipv 1 score cp 144 nodes 1965 nps 655000 tbhits 0 time 3 pv g1c5 b7a8 c3d4 a8b7 d4d5 b7a8
info depth 8 seldepth 10 multipv 1 score cp 425 nodes 3343 nps 835750 tbhits 0 time 4 pv g1b6 b7a8 c3d4 a8b7 d4c5 b7a8 c5c6
info depth 9 seldepth 10 multipv 1 score cp 330 nodes 57567 nps 1857000 tbhits 0 time 31 pv c3d3 b7a8 g1b6 a8b7 d3e4 b7a8 e4d4 a8b7
```

Stockfish 080621 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 9.2.1 on Linux
Compilation settings include:  64bit AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 9.2.1 20191102

The same holds for the bmi2 compile.

**Comment by snicolet** [comment]
Some remarks:
- we are very near the 50 moves limit
- the position is a draw because of the bad bishop (in fact I think it would still be a draw if we removed the black pawn, added as many white pawns as we want on the 'a' column and as many white bishops on black squares as we want on the board)

So this is a difficult position for SF, she is searching and searching and hitting draws by 50 moves rule all over the place. But in fact everything is fine, as the move she will eventually output after the `stop` keyword by the GUI is a draw anyway.

Depending on the exact version and the exact hash amount the command `go infinite` will appear to "be stuck" at different depth:

```
./stockfish
position fen 8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 37 130
go infinite
```

**Comment by vondele** [comment]
would be interesting to see how long we need to reach depth 10 on that position. Eventually there should be some output. I wonder if we have some extensions that are not limited one way or another.

**Comment by locutus2** [comment]
I have done more degugging and the search goes for root depth 10 at least to depth 144. ANd the reason is the singular extension. I try here to restrict this: https://tests.stockfishchess.org/tests/view/60bfb0b1457376eb8bcaa88c
With this patch we reach at least depth 34.

**Comment by locutus2** [comment]
Here constrain the extension=2 case to captures/promotions: https://tests.stockfishchess.org/tests/view/60bfb3b6457376eb8bcaa895.

Here we reach around depth 24.

**Comment by snicolet** [comment]
Do you think it would be possible to compare somehow the current level reached in search (as given by `A = ss->ply`) and the nominal root depth we asked for (as given in `B = rootDepth`), to prevent singular extensions when `A - B > 30` (say) or `A > 2B`?

**Comment by locutus2** [comment]
@snicolet 
Yes, but i think comparing ss->ply + depth (estimated length of current variant) to root depth is better. Here my first try: https://tests.stockfishchess.org/tests/view/60bfb906457376eb8bcaa89a

Here we reach around depth 18.

**Comment by joergoster** [comment]
`2 * rootDepth` is probably too strict. I'd also recommend to test as some kind of bugfix, no?

**Comment by snicolet** [comment]
In this position every move by Black is probably singular, because Black has only the a8 and b7 squares to hold the draw.

So Black takes the extension at every node in line 1073 of search.cpp (and probably even the double extension, hence the search explosion):
```
   if (value < singularBeta)
          {
              extension = 1;
              singularQuietLMR = !ttCapture;
              if (!PvNode && value < singularBeta - 93)
                  extension = 2;
          }
```

I think I will play with the idea to take the extensions with probability 50% (something like that), and see what happens.

**Comment by snicolet** [comment]
What happens is that the bench goes from `5530620` to `3478751`, it is funny, at least :-)

https://tests.stockfishchess.org/tests/view/60bfc823457376eb8bcaa8a6

**Comment by jhellis3** [comment]
In Crystal, I added the condition: && depth < rootDepth - ss->ply.  YMMV.

**Comment by joergoster** [comment]
Another possibility is to keep track of the total extension of a subtree and stop allowing to extend further at some point.
Btw, are we sure this is the only problem here?

**Comment by jhellis3** [comment]
Most likely, yes.  +2 extensions are really dangerous.  TBH, I was surprised when this made it in without comment.  I had to do something about it in Crystal because the combo of the +2 here and on game cycles was preventing bench from completing.

**Comment by vondele** [comment]
since this doesn't appear to be a problem with SF13, do we know which recent commit has triggered this?

I've started to more tests:
remove extension by 2: https://tests.stockfishchess.org/tests/view/60c0599d457376eb8bcaa93b
limit extension by 2 by 50mc: https://tests.stockfishchess.org/tests/view/60c05a58457376eb8bcaa93d

**Comment by joergoster** [comment]
It's also worth noting that even when reaching higher depths SF doesn't give drawish scores.
For example:

> info depth 32 seldepth 55 multipv 1 score cp 165 nodes 2060966860 nps 2129018 hashfull 732 tbhits 0 time 968036 pv c3b3 b7a8 b3a2 a8b7 g1f2 b7a8 f2d4 a8b7 a2b1 b7a8 b1c1 a8b7 c1d1 b7a8 d4b6 a8b7 b6e3 b7a8 d1c2 a8b7 e3g1 b7a8 c2b3 a8b7 b3b4 b7a8 g1c5 a8b7 b4a5 b7a8 a5b5 a8b7 b5b4 b7a8 b4c3 a8b7 c5f2 b7a8 c3d2 a8b7 f2d4 b7a8 d4b6 a8b7 d2d3 b7a8 d3e2 a8b7 b6d4 b7a8 d4e3 a8b7

Older versions have no problem. (Stockfish 6)

> info depth 34 seldepth 47 multipv 1 score cp 6 nodes 43689402 nps 4018524 tbhits 0 time 10872 pv c3d3 b7a8 g1c5 a8b7 d3e4 b7a8 e4f5 a8b7 f5g5 b7a8 g5h6 a8b7 h6g7 b7a8 c5d4 a8b7 g7g8 b7a8 g8h7 a8b7 d4c5 b7a8 c5e3 a8b7 a7a8r b7a8 h7h6 a8b7 h6g5 b7a8 e3c5 a8b7 c5f2 b7a8 g5f4 a8b7 f2g3 b7a8 f4e3 a8b7 g3e5 b7a8 e3e4 a8b7 e5d4 b7a8 a3a4

**Comment by vondele** [comment]
sf 6 switches at 21 from 215 to 6, sf 7 - sf11 have a bit unstable eval, last high eval is 350 at depth 13 for sf11.  I would see this as a independent issue, seems like nnue doesn't know this endgame, and we don't switch to classical?

**Comment by Sopel97** [comment]
This might not be an issue for play, where the search is cut by maximum allowed time, but is an issue for analysis. Perhaps a fix could be applied only to infinite analysis, where the user relies on periodic updates.

**Comment by ddobbelaere** [comment]
Interesting position. As a human you can quickly *proof* it's a draw with perfect play as follows: without the black pawn on b5 it's a well-known draw (wrong colored bishop, doesn't matter there are two h pawns). The only thing white can try is to force black to play b4, in an attempt to transform the pawn on a3 into a b pawn, but this is only possible after trapping the black king in the corner with e.g. Kb6 (for white), but then after b4 axb4 is stalemate again.

https://github.com/official-stockfish/Stockfish/commit/4c0299832555c3e35eb1f8779bedf7d1d2819cf1 might be part of the separate issue why we don't switch to classical in some lines, but I agree it's a separate issue.

**Comment by vondele** [comment]
I'm currently testing at LTC (after passed STC) https://tests.stockfishchess.org/tests/view/60c07eac457376eb8bcaa965 which make sure extensions terminate. It fixes the testcase, even if it is still a bit slower. It does appear to gain a little Elo. While search during game play will terminate, if this continues for a few moves, one will run out of time quickly.

**Comment by joergoster** [comment]
With classical eval:

> ucinewgame
> position fen 8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 37 130
> go infinite
> info string classical evaluation enabled
> info depth 1 seldepth 1 multipv 1 score cp 0 nodes 23 nps 23000 tbhits 0 time 1 pv a3a4
> info depth 2 seldepth 2 multipv 1 score cp 0 nodes 90 nps 90000 tbhits 0 time 1 pv a3a4 b5a4
> info depth 3 seldepth 3 multipv 1 score cp 0 nodes 163 nps 163000 tbhits 0 time 1 pv a3a4 b5a4 a7a8r b7a8
> info depth 4 seldepth 4 multipv 1 score cp 0 nodes 259 nps 259000 tbhits 0 time 1 pv a3a4 b5a4 a7a8r b7a8
> info depth 5 seldepth 5 multipv 1 score cp 0 nodes 481 nps 481000 tbhits 0 time 1 pv a3a4 b5a4 a7a8r b7a8 g1a7
> info depth 6 seldepth 6 multipv 1 score cp 0 nodes 1146 nps 1146000 tbhits 0 time 1 pv a3a4 b5a4 a7a8r b7a8 g1a7 a8a7
> info depth 7 seldepth 7 multipv 1 score cp 0 nodes 2404 nps 1202000 tbhits 0 time 2 pv c3d2 b7a8 g1f2 a8b7 f2g1
> info depth 8 seldepth 8 multipv 1 score cp 348 nodes 3995 nps 1331666 tbhits 0 time 3 pv c3b3 b7a8 b3b4 a8b7 b4a5 b7a8
> info depth 9 seldepth 10 multipv 1 score cp 0 nodes 14551 nps 1616777 tbhits 0 time 9 pv g1f2 b7a8 c3b3 a8b7 b3c2 b7a8 c2b3
> info depth 10 seldepth 12 multipv 1 score cp 265 nodes 16280 nps 1628000 tbhits 0 time 10 pv c3b3 b7a8 b3b4 a8b7 b4a5 b7a8 g1f2 a8b7
> info depth 11 seldepth 12 multipv 1 score cp 321 nodes 18487 nps 1680636 tbhits 0 time 11 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8 d3c3 a8b7
> info depth 12 seldepth 14 multipv 1 score cp 338 nodes 25623 nps 1708200 tbhits 0 time 15 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8 d3c3 a8b7 c3b4 b7a8 b4a5 a8b7 a7a8r b7a8
> info depth 13 seldepth 19 multipv 1 score cp 0 nodes 255775 nps 2204956 tbhits 0 time 116 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 14 seldepth 21 multipv 1 score cp 0 nodes 283412 nps 2214156 tbhits 0 time 128 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 15 seldepth 22 multipv 1 score cp 0 nodes 323385 nps 2185033 tbhits 0 time 148 pv c3d2 b7a8 d2d3 a8b7
> info depth 16 seldepth 22 multipv 1 score cp 0 nodes 393703 nps 2175154 tbhits 0 time 181 pv c3d2 b7a8 d2d3 a8b7
> info depth 17 seldepth 22 multipv 1 score cp 0 nodes 440405 nps 2180222 tbhits 0 time 202 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 18 seldepth 22 multipv 1 score cp 0 nodes 560009 nps 2187535 tbhits 0 time 256 pv c3d2 b7a8 d2d3 a8b7
> info depth 19 seldepth 22 multipv 1 score cp 0 nodes 708696 nps 2207775 tbhits 0 time 321 pv c3d2 b7a8 d2d3 a8b7
> info depth 20 seldepth 22 multipv 1 score cp 0 nodes 880566 nps 2212477 tbhits 0 time 398 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 21 seldepth 22 multipv 1 score cp 0 nodes 1099129 nps 2229470 tbhits 0 time 493 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 22 seldepth 22 multipv 1 score cp 0 nodes 1310578 nps 2232671 tbhits 0 time 587 pv c3d2 b7a8 d2d3 a8b7
> info depth 23 seldepth 22 multipv 1 score cp 0 nodes 1562939 nps 2252073 tbhits 0 time 694 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 24 seldepth 22 multipv 1 score cp 0 nodes 1878747 nps 2255398 tbhits 0 time 833 pv c3d2 b7a8 d2d3 a8b7
> info depth 25 seldepth 22 multipv 1 score cp 0 nodes 2224426 nps 2267508 tbhits 0 time 981 pv c3d2 b7a8 d2d3 a8b7
> info depth 26 seldepth 22 multipv 1 score cp 0 nodes 2572300 nps 2268342 hashfull 268 tbhits 0 time 1134 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8
> info depth 27 seldepth 22 multipv 1 score cp 0 nodes 3197379 nps 2275714 hashfull 323 tbhits 0 time 1405 pv c3d2 b7a8 d2d3 a8b7 g1f2 b7a8

As you can see classical eval does know it's a draw almost immediately. And because of this, search doesn't go into this pathological behaviour. Again, search and eval are much more connected than one might think. ;-)

I have no doubt, though, that in some way or another we must guard against doing too many extensions at once.

**Comment by vondele** [comment]
The test here passed STC and LTC, and improves the situation (in particular the testcase above): https://tests.stockfishchess.org/tests/view/60c07eac457376eb8bcaa965 

However, it is still not fully fixed, a related testcase takes very long to complete depth 25. 

Maybe there are better alternatives?

**Comment by joergoster** [comment]
@vondele How is my cap_ext patch (see fishtest) doing on that related testcase?

**Comment by vondele** [comment]
let me first paste the testcase:
```
uci
setoption name Hash value 4
setoption name Contempt value 0
ucinewgame
position fen 8/Pk6/8/1p6/8/P1K5/8/6B1 w - - 0 130
go depth 25
```

**Comment by vondele** [comment]
@joergoster passes with your branch.

**Comment by vondele** [comment]
Another attempt https://tests.stockfishchess.org/tests/view/60c13161457376eb8bcaaa0f

**Comment by joergoster** [comment]
Great! Thanks for testing.

**Comment by locutus2** [comment]
Try to tackle this by excluding endgames from big extension (The problem should be there more lilkely).
https://tests.stockfishchess.org/tests/view/60c13ab1457376eb8bcaaa1b

**Comment by vondele** [comment]
The following fix passed testing, and should be a robust way to avoid the explosion. https://tests.stockfishchess.org/tests/view/60c196fb457376eb8bcaaa6b I'll make a PR.
