### ISSUE TITLE
Segmentation fault with specific FEN.

### ISSUE THREAD

**Issue by ZakisM** [official-stockfish/Stockfish#3533]
Running these commands on Stockfish 13 on Windows 10:

1. position fen rnk2bnr/p3p2p/5p2/1BQP2pP/3PP3/5PB1/PP5P/RN2K1NR w
2. go nodes 100

Results in a crash:

position fen rnk2bnr/p3p2p/5p2/1BQP2pP/3PP3/5PB1/PP5P/RN2K1NR w
go nodes 100
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled
Segmentation fault

**Comment by BM123499** [comment]
@ZakisM the fen is incomplete, fi you check https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation , you can see it's missing Castling Rights, En Passant Square, Halfmove clock and Fullmove number.
So, it means the FEN is invalid, we don't validate FEN in Stockfish, we assume it's always correct.

**Comment by ZakisM** [comment]
@BM123499 ah I see that makes sense if you don't validate the FEN, i was assuming you were making assumptions about the FEN as the above one works if you change the colour from white to black, i.e:

position fen rnk2bnr/p3p2p/5p2/1BQP2pP/3PP3/5PB1/PP5P/RN2K1NR b

Actually works without the Castling Rights, En Passant Square etc...

**Comment by Sopel97** [comment]
Stockfish requires the FENs to be correct and represent legal chess960 positions only. Otherwise the behaviour is undefined.
