### ISSUE TITLE
Default value of UCI Options

### ISSUE THREAD

**Issue by TheYoBots** [official-stockfish/Stockfish#3539]
Could the default values for the UCI Options documented here https://github.com/official-stockfish/Stockfish#the-uci-protocol-and-available-options be mentioned (where relevant).

**Comment by gvreuls** [comment]
Have you tried running ``stockfish uci`` from the command line?

**Comment by TheYoBots** [comment]
Yes I do try that and it does work. It would just be great if it is documented too.

**Comment by snicolet** [comment]
I have opened a pull request there, opinions welcomed: https://github.com/official-stockfish/Stockfish/pull/3540

**Comment by TheYoBots** [comment]
Thanks for https://github.com/official-stockfish/Stockfish/commit/7819412002374fac5ebf7bec1e49a25481f1c42b
