### ISSUE TITLE
Chess960 FEN parsing

### ISSUE THREAD

**Issue by matthewlai** [official-stockfish/Stockfish#356]
In position.cpp, void Position::set(const string& fenStr, bool isChess960, Thread* th):

There is no checking for colour of the rook when finding rsq for castling.

for (rsq = relative_square(c, SQ_A1); type_of(piece_on(rsq)) != ROOK; ++rsq) {}

In some positions, it may pick up an opponent rook:
4k3/pppppppp/8/8/8/8/PPPPPPPP/rR2K3 w Q - 0 1

**Comment by mcostalba** [comment]
Bug confirmed. Pull request open:

https://github.com/official-stockfish/Stockfish/pull/357

Thanks for reporting: very old and subtle bug, good catch!

**Comment by matthewlai** [comment]
Thanks!

**Comment by mcostalba** [comment]
Fix applied.
