### ISSUE TITLE
Problem with commit 'Add basic github workflow'

### ISSUE THREAD

**Issue by locutus2** [official-stockfish/Stockfish#3567]
I have updated my local master but can't push to github with following error message:
` ! [remote rejected]     master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/stockfish.yml` without `workflow` scope)`

Someone knows waht to do? Have some security settings in github to be done?

**Comment by vondele** [comment]
https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on

**Comment by locutus2** [comment]
@vondele 
Thanks, but i don't want to change my personal token (i have to bring it to several devices) now. I have simply used password autehtification and its works. After this personal token has worked again

**Comment by vondele** [comment]
OK, that might be needed whenever there is a change to the workflows, I don't quite know.

**Comment by locutus2** [comment]
I have found out that its not nessary to create a new token like it mentioned in the link. At least i have tried the Update token button!

**Comment by vondele** [comment]
I assume this is fixed by now.
