### ISSUE TITLE
Build error on OSX introduced in 2e745956c0478627c4822104fc48a079c2f15e77

### ISSUE THREAD

**Issue by yuzisee** [official-stockfish/Stockfish#3573]
Details: https://github.com/official-stockfish/Stockfish/commit/2e745956c0478627c4822104fc48a079c2f15e77#r52432951

Solution:
According to https://stackoverflow.com/questions/56978365/how-to-fix-error-call-to-abs-is-ambiguous we need to include `<cmath>`

The following one-line change works for me on OSX, but I'll leave it up to the project maintainers as to how you want to handle this!

    diff --git a/src/nnue/evaluate_nnue.cpp b/src/nnue/evaluate_nnue.cpp
    index a918b925..e0ac4bfd 100644
    --- a/src/nnue/evaluate_nnue.cpp
    +++ b/src/nnue/evaluate_nnue.cpp
    @@ -23,6 +23,7 @@
     #include <sstream>
     #include <iomanip>
     #include <fstream>
    +#include <cmath>
     
     #include "../evaluate.h"
     #include "../position.h"

**Comment by vondele** [comment]
thanks, yes either cmath or cstdlib must be included, thanks for the fix.

**Comment by snicolet** [comment]
@yuzisee
Could you test another fix, removing the two castings to (double) and (int) in the offending lines?

```
int cp = std::abs(100 * v / PawnValueEg);
```
