### ISSUE TITLE
Some UCI options disappeared with the latest dev release

### ISSUE THREAD

**Issue by karolm2** [official-stockfish/Stockfish#3581]
In the latest dev version (Detect fortresses a little bit quicker) there are no Contempt and Analysis_Contempt options anymore.

**Comment by vondele** [comment]
yes, contempt thas been removed. See https://github.com/official-stockfish/Stockfish/commit/ed436a36bade82422753f8be9c16d790232e9c91

**Comment by karolm2** [comment]
OK, I just missed that one.
