### ISSUE TITLE
Automate code formatting

### ISSUE THREAD

**Issue by lucasart** [official-stockfish/Stockfish#3608]
Quick example to show what you get with reasonable defaults:
```
$ cat .clang-format 
BasedOnStyle: LLVM
ColumnLimit: '100'
IndentPPDirectives: BeforeHash
IndentWidth: 4
$ find . \( -name "*.cpp" -o -name "*.h" \) -exec clang-format -i {} \;
```
Feel free to experiment: https://clang.llvm.org/docs/ClangFormat.html

**Comment by XInTheDark** [comment]
I agree that we should use an auto-formatter for Stockfish. It's already implemented in Fishtest, and has been beneficial for maintaining a consistent code style. Adding this to Stockfish will definitely make the code much cleaner and readable. That being said, the auto-formatter might break some formatting details, such as [this](https://github.com/official-stockfish/Stockfish/blob/master/src/material.cpp#L35), perhaps. 

Formatting is just about some minor details, though, so it's not that important.

**Comment by vondele** [comment]
I just tried this again, and it appears to lead to a broken compilation (using clang-format 14).

**Comment by Disservin** [comment]
> find . \( -name "*.cpp" -o -name "*.h" \) -exec clang-format -i {} \;

Adding 
`#include "../position.h"` to `nnue_feature_transformer.h` fixes it for me.

**Comment by vondele** [comment]
still change it doesn't leave the code invariant, but I agree it makes sense to add that.

**Comment by Yery** [comment]
Perhaps an alternative to clang-format is "astyle" https://astyle.sourceforge.net/  (it is over 25 years old, but still regularly updated and improved!).
