### ISSUE TITLE
Problem at android device

### ISSUE THREAD

**Issue by fuyaka0** [official-stockfish/Stockfish#3611]
I have sf13 version on my tablet. I downloaded latest version which contains armv8 folder. When I try to add this file to analyze this pro app it says you already have this engine. I removed sf13 and added sf14, it shows sf13 installed rather than sf14

**Comment by FredFerguson01** [comment]
The problem is with Analyse This application, not with stockfish. You should talk to their customer support.

**Comment by vondele** [comment]
I also believe this is not a stockfish issue, but a problem with the app.
