### ISSUE TITLE
Illegal moves emitted when pondering is on?

### ISSUE THREAD

**Issue by mlang** [official-stockfish/Stockfish#3613]
I am having trouble running stockfish in ponder mode.
I first tried it with my own implementation of a UCI selfplay program.
It works for a while, then fails to parse moves it sees in the pv.
I originally thought I have a subtle bug in my implementation, and
didn't follow up.  But recently, I tried cutechess-cli, which
also has support for putting the engines in ponder mode.
Strangely, that doesnt work either.  It starts a game, then crashes
with a invalid move message.  So I am suspecting there might
be a problem in stockfish ponder pv emission?
I haven't isolated a testcase yet, so I am basically asking here
if ponder mode is being actively used/tested?
I am guessing it has something to do with stop vs ponderhit,
either on the client side or in stockfish itself.
This would explain why it seemingly works for a while, then stops.

**Comment by vondele** [comment]
ponder is a bit less well tested, so definitely worth investigating. cutechess can save the logs, that would help to analyse the problem. One thing that could trigger this would be illegal starting fens, that's something to check.

**Comment by joergoster** [comment]
Hmm, no problems here.
Just a snippet from a debug output where you can see cutechess-cli is sending 'go ponder ...' command:

> 16370 <SF-Master-PB(0): info depth 24 seldepth 30 multipv 1 score cp 29 nodes 2017605 nps 688132 hashfull 117 tbhits 0 time 2932 pv f1d3 d7d5 g1f3 b8d7 e1g1 f8e7 b1d2 c8b7 f3e5 e8g8 e5d7 f6d7 d2f3 c5c4 d3c2 d7f6 f3e5 a6a5 a2a3 b5b4 a3b4 a5b4 a1a8 d8a8 c3b4 a8a2 d1d2
> 16370 <SF-Master-PB(0): bestmove f1d3 ponder d7d5
> 16370 >SF-Master(1): position fen rnbqkb1r/p1ppppp1/5n1p/1p6/3P4/2P1B3/PP2PPPP/RN1QKBNR w KQkq - 0 1 moves e3f4 e7e6 e2e3 a7a6 h2h3 c7c5 f1d3
> 16370 >SF-Master(1): isready
> 16370 >SF-Master-PB(0): position fen rnbqkb1r/p1ppppp1/5n1p/1p6/3P4/2P1B3/PP2PPPP/RN1QKBNR w KQkq - 0 1 moves e3f4 e7e6 e2e3 a7a6 h2h3 c7c5 f1d3 d7d5
> 16370 >SF-Master-PB(0): isready
> 16370 <SF-Master-PB(0): readyok
> 16370 >SF-Master-PB(0): go ponder wtime 83847 btime 86413 winc 900 binc 900
> 16371 <SF-Master(1): readyok
> 16371 >SF-Master(1): go wtime 83847 btime 86413 winc 900 binc 900

Looks ok. I'm not aware anything about ponder mode has been changed during the last months or even years ...

**Comment by vondele** [comment]
I ran about 4000 games with ponder on, and I could not see any illegal move message. The code is unlikely to be wrong. Please reopen if you see this issue reappear.
