### ISSUE TITLE
Stockfish 13 release in download archive?

### ISSUE THREAD

**Issue by brendanlong** [official-stockfish/Stockfish#3620]
I'm not sure if this is the right place to ask, but can you add Stockfish 13 to the archive of old downloads in Dropbox? I need that version for an experiment but can't find any downloads for it.

**Comment by ppigazzini** [comment]
@brendanlong you find Stockfish 13 links at the bottom of this page:
https://abrok.eu/stockfish/?page=5

```
Author: Joost VandeVondele
Date: Thu Feb 18 22:14:55 2021 +0100
Timestamp: 1613682895

Stockfish 13

Official release version of Stockfish 13

Bench: 3766422

-----

It is our pleasure to release Stockfish 13 to chess fans worldwide.
As usual, downloads are freely available at
...
```

**Comment by daylen** [comment]
Should be available now: https://www.dropbox.com/sh/75gzfgu7qo94pvh/AAB0vCuaC3EAD0PHKR1nqX7Ja/Stockfish%2013?dl=0&subfolder_nav_tracking=1

**Comment by vondele** [comment]
Thanks for fixing this.
