### ISSUE TITLE
Fishtest queue

### ISSUE THREAD

**Issue by Vizvezdenec** [official-stockfish/Stockfish#3624]
I recently decided to check our pending tests and witnessed this thing - 
https://cdn.discordapp.com/attachments/813919248455827515/868265875713687583/unknown.png  
All stopped tests are against master that is 2 rounds of commits behind and they are piling up with prio -1 doing nothing.  
I think this is a pretty bad habit because it makes fishtest look like extremely busy - in reality most of this things will need retesting because master they are testing against is like dozen commits behind.  
I suggest that devs shouldn't be doing this - either let test run fully or stop it, don't put it in a queue which will 99,99% never finish because fishtest is really busy now w/o noob fleet.
@SFisGOD @snicolet @candirufish @pb00068
I'm not flaming you or anything - but this piling up is discouraging other people from trying any sort of ideas. Like I look at fishtest, see 20 tasks running and 50 tasks pending and think to myself "wow, this is some load, I probably will try smth when it clears" - while in reality half of this 50 tasks are > 10 days old and quarter is 1 week old with negative elo.
I don't think it's a good habit but people have started to develop it lately for w/e reason.

**Comment by xoto10** [comment]
fwiw (just my opinion), I think setting a lower throughput is often better than a lower priority. This way resources get diverted to more important jobs, but a little work will still be done on the low throughput job, so it will finish eventually

**Comment by SFisGOD** [comment]
@Vizvezdenec I sometimes use the paused tests section to serve as depository for reference patches, to remind me what I'm working on and so that I don't have to browse my history. And personally, I don't consider the paused section anymore as part of the load. I only consider the number of active tests.

@xoto10 I think fewer active tests is much better if we are worried about discouraging other people.

**Comment by xoto10** [comment]
@SFisGOD 
You have a point there, but sometimes I think discouraging other people from creating yet more tests is the goal ! :-)

**Comment by pb00068** [comment]
> most of this things will need retesting because master they are testing against is like dozen commits behind.

Like it was already said multiple times, STC is just some kind of garbage filter, LTC is the proper challenging test.
So if a STC is behind some commits to master when it passes, there I see no problem in running the LTC rebased to master.
like I did with https://tests.stockfishchess.org/tests/view/60ffac2f96b86d98abf6a749
Being modest by giving precedence to the rest of testers is in my opinion a noble gesture.
