### ISSUE TITLE
SF resigned..?

### ISSUE THREAD

**Issue by DaniSpringer** [official-stockfish/Stockfish#3625]
https://lichess.org/SRcyNO0a

**Comment by Collineli** [comment]
Stockfish on lichess always resignes at move 151. Official stockfish doesn't do that.

**Comment by vondele** [comment]
in fact stockfish, as an UCI engine, can't even resign. So, I think it would be appropriate to file this as an issue with Lichess, even though probably it is by design. https://github.com/ornicar/lila/issues

**Comment by DaniSpringer** [comment]
https://lichess.org/9m68Abkl Confirmed that it’s move 151
