### ISSUE TITLE
"jobserver is not available" warning with GCC 11

### ISSUE THREAD

**Issue by NightlyKing** [official-stockfish/Stockfish#3656]
I recently switched to Manjaro (Arch based distro) and now I get this error when doing a LTO compile of Stockfish:  
`lto-wrapper: Warnung: jobserver is not available: »--jobserver-auth=« is not present in »MAKEFLAGS«` (system language is German hence "Warnung")
Kernel version is 5.13.8-1
GCC version is GCC 11.1.0

It doesn't seem to be part of the compiler output since I ran `make profile-build ARCH=x86-64-avx2 -j | cat > compiler_output.log` and the error doesn't get written to the file (just like the Stockfish bench output, which is actually correct in spite of the error). The warning happens every single time as well. It seems to be independent of the chosen instruction set, too. Curiously enough, it doesn't happen if `-j` is replaced with something like `-j2`. So it seems to be a problem with using a decent amount of threads. I've looked around and it looks like there were similar bugs in the past (version 4.7 if I remember correctly) so I find it weird coming up again. I'm uncertain whether this is caused by Stockfish or if it's purely a problem of the compiler (or possibly both?).

**Comment by vondele** [comment]
what happens with `make -j20 ...`

**Comment by NightlyKing** [comment]
My current PC only has 4 cores/8 threads (an accident forced to switch to an older CPU). But I guess I can try either way.

**Comment by vondele** [comment]
yes, or maybe just figure out if the number there matters, and if so at what value.

**Comment by NightlyKing** [comment]
I tested up to -j500 (which is overkill) and yet the warning wasn't triggered. I'm only able to trigger it with using -j (which is the most convenient option).

**Comment by vondele** [comment]
so, I suspect that this is a kind of security related issue to avoid fork bombs, but I'm not sure. The warning is probably harmless.

**Comment by ppigazzini** [comment]
Some info:
https://patchwork.ozlabs.org/project/gcc/patch/11dc797e-6931-ee22-0d24-f24334fc57f8@suse.cz/
https://www.gnu.org/software/make/manual/html_node/Job-Slots.html
https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html#POSIX-Jobserver

**Comment by ppigazzini** [comment]
> so, I suspect that this is a kind of security related issue to avoid fork bombs, but I'm not sure. The warning is probably harmless.

I agree with the fork bombs hypothesis.
There are some reports of irresponsive systems simply with `make -j`

From `man make` :
> If the -j option is given without an argument, make will not limit the  number  of  jobs that can run simultaneously.
> When make invokes a sub-make, all instances of make will coordinate to run the specified number of jobs at a time; see the section PARALLEL MAKE AND THE JOBSERVER for details.

And the option `-l`:
>       -l [load], --load-average[=load]
>            Specifies that no new jobs (commands) should be started if there are others jobs running and the load average is at least load (a floating-point number).  With no argument, removes a previous load limit.

**Comment by vondele** [comment]
lto=auto was tried a while ago, but caused issues: https://github.com/official-stockfish/Stockfish/commit/77cf5704b6deda52171dafeb2fae370273ebd797

**Comment by NightlyKing** [comment]
I think I'll close this issue. It's fairly easy to work around it by using -jx where x is some number > 1 and < inf. Moreover, using -j only causes a small delay without causing a broken binary.
