### ISSUE TITLE
make doesn't respect newly added files without make clean

### ISSUE THREAD

**Issue by Sopel97** [official-stockfish/Stockfish#3658]
Makes abrok break every time a new .cpp file is added, and users also were confused by it.

Caused by some .depend thingy. 

```
1:14 PM] vondele: This could be a partial fix:
diff --git a/src/Makefile b/src/Makefile
index c1dab86ba..2d33418e1 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -912,7 +912,7 @@ icc-profile-use:
        EXTRACXXFLAGS='-prof_use -prof_dir ./profdir' \
        all
 
-.depend:
+.depend: Makefile
        -@$(CXX) $(DEPENDFLAGS) -MM $(SRCS) > $@ 2> /dev/null
 
 -include .depend

3:20 PM] vondele: I think the only real fix is to have a dependency on $(SRCS) otherwise code can be miscompiled in principle.
```

also https://stackoverflow.com/a/30142139/3763139 may be of help

**Comment by vondele** [comment]
good to have an issue, but I don't think the above diff is not good enough, a more thorough fix is the PR above.

The disadvantage is somewhat slower compile times (1s overhead), which we can only get rid off by having a .dep file per source file, IMO.

**Comment by Sopel97** [comment]
Having one .dep file per source shouldn't be an issue, all build artifacts could be placed in a separate "build" directory. I think the so post I linked above has a solution of this kind.
