### ISSUE TITLE
Very strange stockfish issue.

### ISSUE THREAD

**Issue by Kr3m** [official-stockfish/Stockfish#3660]
Why is stockfish moving the rook to E1 here?  I'm not sure how to post images, but this seems specific to Stockfish 14 and not 13 since the reddit bot posted a lichess link that seems to use the correct move.  Here's a link to the issue in more detail:

[https://www.reddit.com/r/chess/comments/p54zz3/strange_stockfish_issue/](url)

**Comment by dav1312** [comment]
It is able to find it for me. Both the latest version and SF14
![image](https://user-images.githubusercontent.com/63931154/129501090-3bf44ab4-d387-4e95-8658-9f4c3031a156.png)

**Comment by JackWright347** [comment]
I can't reproduce the problem with Stockfish 14 (stockfish_14_x64_bmi2.exe) on my computer.
I assume FEN:  `2b3rk/1q3p1p/p1p1pPpQ/4N3/2pP4/2P1p1P1/1P4PK/5R2 w - - 0 24`
Re1 is the best move only in the first millisecond, already in the 2ms the best move is Rf4
and after 15 seconds Stockfish says that Rf4 leads to checkmate in 7.

Also, after 15 seconds Stockfish 14 finds out that Rh1 is checkmate in 3: Rh1 e2 Qxh7+ Kxh7 Kg1#.
How much time did you give it to think?

**Comment by Kr3m** [comment]
I used Chess Arena with Stockfish 14 as the frontend GUI.  If I select move now, it makes the incorrect move.  If I select analysis and then select move now, it makes the correct move.  I'm wondering why using move now without clicking analysis first results in a less precise calculation.  Does move now use a more limited depth?  It also seems for some reason that Stockfish 13 is able to find the correct move at a lesser depth than Stockfish 14, and makes the correct move using move now without hitting analysis first.

**Comment by Kr3m** [comment]
> 
> 
> I can't reproduce the reported Re1 issue with Stockfish 14 (stockfish_14_x64_bmi2.exe) on my computer. How much time did you give it to think?
> 
> I assume FEN: `2b3rk/1q3p1p/p1p1pPpQ/4N3/2pP4/2P1p1P1/1P4PK/5R2 w - - 0 1`
> Re1 is the best move only in the first millisecond, already in the 2ms the best move is Rf4 and after 15 seconds Stockfish says that Rf4 leads to mate in 6. Also, after 15 seconds Stockfish finds out that Rh1 is mate in 3: `Rh1 e2 Qxh7+ Kxh7 Kg1#`.
> 
> If anything, the bug would be that Stockfish finds the longer 'mate in 6' before the shorter 'mate in 3' (and skips Rf3 'mate in 5' and g4 'mate in 5')
> 
> By the way, searching for the FEN I found this bug report from May 28, 2020: [ornicar/lila#6716](https://github.com/ornicar/lila/issues/6716)

**Comment by dav1312** [comment]
> If I select move now, it makes the incorrect move.

If you select `Move Now!` and the level is too low like for example only `1 Second` the engine probably doesn't have enough time to think and it will make the wrong move. Just give him more time.
![image](https://user-images.githubusercontent.com/63931154/129560175-b3749d6b-cedf-4d3f-877e-ccb89c8373d3.png)

**Comment by Kr3m** [comment]
I don't even have an option in my levels menu for 1 second, 18 half moves, or 3 seconds.  It's currently set to tournament mode in 5 minutes.  Though, thank you for pointing that out.  That helps clarify some things, but it's still confusing as to why Stockfish 13 doesn't require as much time.
