### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#3672]
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

followed README instructions.
First, get error in evaluate.h:
fatal error: optional: No such file or directory
Replaced on experimental/optional.
Now get a whole bunch of errors, starting with:
[build-errs.txt](https://github.com/official-stockfish/Stockfish/files/7028352/build-errs.txt)

**Comment by vondele** [comment]
you need a more recent gcc, install at least gcc 7.5 (but more recent better) to have support for the needed C++11 features.

**Comment by ab-chesspad** [comment]
the req should be mentioned anyway
