### ISSUE TITLE
No macOS x64-avx2 development builds on abrok.eu/stockfish

### ISSUE THREAD

**Issue by PedanticHacker** [official-stockfish/Stockfish#3673]
Why aren't there any development builds of the Stockfish chess engine for the macOS operating system on the https://abrok.eu/stockfish web page?

I find that strange. Anyway, do you guys know where can I find such binaries (development builds)? I can't compile on my own, too complicated for me. I need a x64-avx2 build for the macOS operating system, if such builds even exists (couldn't find any on my own). If you guys know where could I find such builds (preferably the x64-avx2 build), please respond with a link or something. Thanks.

**Comment by Sopel97** [comment]
Apple makes it impossible to cross-compile for apple.

**Comment by PedanticHacker** [comment]
> Out of curiosity, How do you intend to test your GUI for Mac if you don't have access to MacOS??
Well, I'm relying on the fact that the PyQt6 GUI framework is cross-compatible. It would be nice if someone with a MacBook tests my chess GUI app that there are no issues on the macOS operating system, but until that happens, I really can't be certain if my app works on macOS at all.

Niklas Fiekas (@niklasf on GitHub) gave me this link: https://github.com/niklasf/Stockfish/releases/tag/fishnet-20200613

Following that link takes you to a Stockfish binary downloads page, and the top link there is a direct download of an OS X x86-64 Stockfish binary file. I have integrated it in my GUI, but I'm not sure if it works at all.
