### ISSUE TITLE
Test with high residual

### ISSUE THREAD

**Issue by vdbergh** [official-stockfish/Stockfish#3684]
Can an approver please purge this test 

https://tests.stockfishchess.org/tests/view/612836d662d20cf82b5ad1b1

It is a retest with the noob book but it has tasks with an extremely high residual (6.671).

PS. The test was not done by me so I cannot do the purging myself.

**Comment by vondele** [comment]
I purged it

**Comment by vdbergh** [comment]
Thanks!
