### ISSUE TITLE
SF on linux SCID error: the analysis engine terminated without and exit code:""

### ISSUE THREAD

**Issue by Xyndrirth** [official-stockfish/Stockfish#3686]
hi,
above is the error when i try to launch sf on SCID, any help would be appreciated.

**Comment by Xyndrirth** [comment]
yes i have been running sf13 before then i deleted all the files and downloaded the sf14, however i just checked all processes running in the background i dont see anywhere sf

**Comment by vondele** [comment]
another reason might be that the GUI has stored the wrong value for the UCI option 'EvalFile' (i.e. leftover from sf13). Try setting that to the default value.

**Comment by Xyndrirth** [comment]
i have finally solved the issue, i was supposed to download sf for 64 bit, i downloaded sf version that doesn't  correspond with my machine, thank you for trying to help.
