### ISSUE TITLE
Score alignment between chess engine and gui

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#3689]
If you launch Stockfish in infinite analysis on the initial position,
the provided score stabilizes around 30 cp.
This is inconsistent with the convention, used by most common gui, of matching score and informer symbols:

- score > 139 => great advantage
- 70<=score<=139 =>advantage
- 26<=score<=69 =>little advantage
- 0<=score<=25 => even position

Chess is a balanced game and, at the beginning, the score cannot be 0 just because White has the trait advantage.
I propose, therefore, to modify the score sent by the engine to the gui.
This is, for the most part, no functional change in Stockfish, but, in Shashchess, it is crucial to increase the strength of the game.
I propose, then, to eliminate the "trend" (old dynamic contempt), since it is only used in the classic rating function, that is very rarely. In this way, in the non-nue version, on the initial position, the score is about 15cp.
Just modify the line in evaluate.cpp that returns the nnue score as follows:
return nnue => return (nnue/2);
The purpose of this is to make not only Stockfish extremely strong, but also as useful as possible to the real player.

**Comment by dsmsgms** [comment]
It is quite likely this loses elo

**Comment by amchess** [comment]
No. I tested a lot.

**Comment by robbai** [comment]
This would not be a non-functional change, the magnitude of the evaluation is important for a lot of Stockfish's search heuristics

**Comment by amchess** [comment]
They are not a lot at all and they worked for classi al e al. The goal Is to align nnue eval to It without the trend.

**Comment by QxC4eva** [comment]
If this is about changing the score sent to the GUI, which is purely aesthetical, I can agree. Stockfish evaluation is roughly double compared to other engines which makes it somewhat harder to interpret. Halving it puts it more in line to Lc0, Komodo and others. It's not that big of a deal either way.
Any internal modifications to the score will need to go through elo gaining bounds on fishtest.

**Comment by amchess** [comment]
Only esthetical it's a risk because classical eval without trend Is aligned with lc0, Komodo, etc, as you tell...

**Comment by robbai** [comment]
@QxC4eva amchess is suggesting that only the NNUE-returned evaluation should be visually rescaled (i.e. centipawn conversion), which to my knowledge is not doable without also affecting classical-returned evaluation.

**Comment by amchess** [comment]
I'm testing this try:
[https://github.com/amchess/Stockfish/commit/7b3a92de10eac75395e2a7fa515ad9358f7c1ca3](https://github.com/amchess/Stockfish/commit/7b3a92de10eac75395e2a7fa515ad9358f7c1ca3)

**Comment by vondele** [comment]
closing this issue. all evaluations terms kept in the code contribute to the playing strength at this point. If not, they can be simplified away after the corresponding tests on fishtest.
