### ISSUE TITLE
Stockfish 14 incorrect in puzzle?

### ISSUE THREAD

**Issue by munseym** [official-stockfish/Stockfish#3712]
My first time filing an issue, forgive me if I get this wrong.  This is for Stockfish in the browser.  Take the url https://lichess.org/analysis/n1rb4/1p3p1p/1p6/1R5K/8/p3p1PN/1PP1R3/N6k_w_-_-_0_1#0

In Firefox Version 78.11.0esr (64-bit) (a very old version) the browser loads Stockfish 10+WASM (I'm guessing intentionally an old version of Stockfish due to compatibility issues).  This correctly shows Mate in 5.

However, in Chrome Version 93.0.4577.82 it loads Stockfish 14+NNUE.  Here it incorrectly shows Mate in 6.  Oddly enough, after playing the first move, 1. b4, it then correctly shows Mate in 4 from there.

**Comment by TopoIogist** [comment]
Stockfish will not always find the shortest mate right away, especially if there are many pieces on the board. This is well known. In this case the move it finds right away is also completely winning.
See also issue #3029
