### ISSUE TITLE
go movetime 0 never stops

### ISSUE THREAD

**Issue by sallyx** [official-stockfish/Stockfish#3720]
movetime <x> shoud play x miliseconds, in this case 0. 

So, it shoud return result immediatelly. It work like that in previous stockfish versions and works like that in other uci engines.

The current version never stops (until you call stop).

**Comment by vondele** [comment]
makes little sense to me. If there is no search, there is no bestmove, so `go movetime 0` is pretty meaningless. It acts as a simple `go`

**Comment by sallyx** [comment]
There might be search in the past. 
But I am just saying it worked like that before, all other engines i tried works like that.
Btw, go movetime -1 returns best move imediatelly.

**Comment by vondele** [comment]
well, it by checking all criteria that are enabled (i.e. non-zero), so `go depth 10 movetime 10` works as well (i.e. what is reached first terminates search). `go movetime -1` enables it and terminates it as soon as it is checked.

**Comment by sallyx** [comment]
I would expect that criteria is enabled by stating them in the go command, not by their (zero) values. It is also inconsistent, if you say that movetime 0 => no search no result, but movetime -1 => result. And it is also inconsitent with all othrer uci engines, which is my bigest concern.  I am not saying that your interpreatation is wrong, It just brings more chaos in the world.

**Comment by vondele** [comment]
closing, no consensus on the interpretation of this corner case.
