### ISSUE TITLE
Segmentation fault on ppc64le

### ISSUE THREAD

**Issue by mgiessing** [official-stockfish/Stockfish#3721]
Hi, when I compile stockfish for Power CPU architecture I get a Segmentation fault error - is it supported for P9 systems?

To replicate:

```
dnf groupinstall -y "Development Tools"
git clone https://github.com/official-stockfish/Stockfish.git
cd Stockfish/
git checkout sf_14
cd src/
make net
make build ARCH=ppc-64
```

Everything gets compiled fine, but when I try to execute the binary I get a Segmentation fault error:

```
[root@p1323-met1 src]# ./stockfish --version
Segmentation fault (core dumped)
```

Here some system info
```
[root@p1323-met1 src]# uname -a
Linux p9 4.18.0-240.el8.ppc64le #1 SMP Wed Sep 23 05:08:15 EDT 2020 ppc64le ppc64le ppc64le GNU/Linux

[root@p1323-met1 src]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
[...]
```

Anything I'm missing here...?
Thanks!

**Comment by vondele** [comment]
apart from the fact that `--version` is not a supported command line argument, the code is supposed to work on ppc-64. Not sure devs have access to it, so we might not be able to reproduce. Can you get a stack trace? Compile as
`make clean && make -j ARCH=ppc-64 optimize=no debug=yes build`
and run under gdb as `gdb ./stockfish` (and issue `run` and `bt`).

**Comment by mgiessing** [comment]
Setting `optimize=no` did the trick. Not sure why with `optimization=yes` it throws errors.

```
[root@p1323-met1 src]# make clean && make build ARCH=ppc-64 optimize=no -j$(nproc --all)
```

```
[root@p1323-met1 src]# ./stockfish compiler
Stockfish 14 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 8.4.1 on Linux
Compilation settings include:  64bit POPCNT
__VERSION__ macro expands to: 8.4.1 20200928 (Red Hat 8.4.1-1)
```

Is optimization enabling CPU intrinsics for better performance such as AVX for Intel CPUs or VSX for Power CPUs etc.?

**Comment by vondele** [comment]
on some architectures it does, there should be very few optimizations enabled on ppc-64

**Comment by mgiessing** [comment]
Perfect- I might check with gdb what causes the issue with enabled optimization, but for the moment I close this issue, as sf14 can be compiled :)

Thanks!
