### ISSUE TITLE
bench go crashes

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#3725]
bench go
libc++abi: terminating with uncaught exception of type std::invalid_argument: stof: no conversion
Abort trap: 6

**Comment by MichaelB7** [comment]
"bench go" is not the command... just use "bench" or see the readme. It crashes becase "go" is not valid option to use with bench.

**Comment by ab-chesspad** [comment]
Same old story again.
Do you really think that your software is allowed to crash in every situation that it does not like??
If "bench go" not a valid command, SF is supposed to say so, not crash.

**Comment by MichaelB7** [comment]
whatever ...

**Comment by vondele** [comment]
indeed, old story, we do not sanitize the input, but expect it to be conforming to the specs.
