### ISSUE TITLE
Less ELO with threads for new network architecture

### ISSUE THREAD

**Issue by JavaMast** [official-stockfish/Stockfish#3727]
I found that current network architecture makes threads almost useless
Just +4 ELO

**Ryzen 3900X @3.8 GHz
concurrency 1
TC: 12s+0.12s
book: 8moves_v3.pgn
Stockfish_x64_310821_ssse_24_threads hash 256 MB (~1.5 times faster)
Stockfish_x64_310821_ssse_12_cores hash 128 MB**

 PLAYER      :  RATING  ERROR  PLAYED   (%)    W     D    L  D(%)  CFS(%)
   1 Stockfish_x64_310821_ssse_24_threads    :    3202      2    1262  50.6   50  1176   36  93.2      97
   2 Stockfish_x64_310821_ssse_12_cores      :    3198      2    1262  49.4   36  1176   50  93.2     ---

White advantage = 16.68 +/- 2.79
Draw rate (equal opponents) = 95.09 % +/- 0.74

===============

**Core i5-11400f
concurrency 1
TC: 10s+0.1s
book: 8moves_v3.pgn
Stockfish_x64_310821_ssse_12_threads hash 256 MB ( ~1.3 times faster)
Stockfish_x64_310821_ssse_6_cores hash 128 MB**

PLAYER                                  :  RATING  ERROR  PLAYED   (%)    W     D    L  D(%)  CFS(%)
   1 Stockfish_x64_310821_ssse_12_threads    :    3202      3    1173  50.5   56  1072   45  91.4      88
   2 Stockfish_x64_310821_ssse_6_cores       :    3198      3    1173  49.5   45  1072   56  91.4     ---

White advantage = 20.04 +/- 2.97
Draw rate (equal opponents) = 93.45 % +/- 0.86

=========================
**+16 ELO for 20 MB network**

**Ryzen 3900X @3.8 GHz
concurrency 1
TC: 12s+0.12s
book: 8moves_v3.pgn
Stockfish_x64_170521_ssse_24_threads hash 256 MB
Stockfish_x64_170521_ssse_12_cores hash 128 MB**

PLAYER                                  :  RATING  ERROR  PLAYED   (%)    W     D    L  D(%)  CFS(%)
   1 Stockfish_x64_170521_ssse_24_threads    :    3208      3    1348  52.2   84  1238   26  91.8     100
   2 Stockfish_x64_170521_ssse_12_cores      :    3192      3    1348  47.8   26  1238   84  91.8     ---

White advantage = 20.34 +/- 2.35
Draw rate (equal opponents) = 95.00 % +/- 0.71

**Comment by Sopel97** [comment]
hyperthreading has always had small/no gains

**Comment by JavaMast** [comment]
> hyperthreading has always had small/no gains

It was ~26 ELO before NNUE
392 threads vs 196 cores in test by **noobpwnftw**

**Comment by JavaMast** [comment]
BTW: cores doubling also gives less ELO now

**Comment by mstembera** [comment]
It was about 8 elo when NNUE was first introduced.
https://tests.stockfishchess.org/tests/view/5f34a3039e5f2effc089da81

**Comment by lucasart** [comment]
Draw rate also increses. That's because level of play increases, which compresses elo. You can't compare elo variations between different levels, without taking draw rate compression into account.

**Comment by vondele** [comment]
we have a quite steady increase in strength, and NN arch updates are carefully tested to increase strength. Precise gains will depend on usage (like hyperthreading, or cooling solutions of the PC).
