### ISSUE TITLE
make -j build ARCH=x86-32 crashes

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#3728]
running on Mac OSX 11.6
<inline asm>:13:7: error: Section too large, can't encode r_address (0x2cd2ea0) into 24 bits of scattered relocation entry.
...
...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [stockfish] Error 1
make: *** [build] Error 2

**Comment by Sopel97** [comment]
https://groups.google.com/g/llvm-dev/c/HXd-w4JZNtk/m/qCibLLxfBQAJ

**Comment by vondele** [comment]
so not really a SF bug, but toolchain? building x86-32 works fine on linux.
