### ISSUE TITLE
Stockfish reports number of nodes over the limit

### ISSUE THREAD

**Issue by nguyenpham** [official-stockfish/Stockfish#3732]
The timer for UCI engines could be a node limit. Based on the test of Uri Blass (at http://talkchess.com/forum3/viewtopic.php?f=6&t=78326) I am a little bit concerned about the number of nodes SF reported. They all are over what the user wanted and commanded.

Below is my simple test with SF 14:

```
go nodes 50000
info string NNUE evaluation using nn-3475407dc199.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp 41 nodes 24 nps 24000 tbhits 0 time 1 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 43 nodes 53 nps 53000 tbhits 0 time 1 pv e2e4 e7e6
info depth 3 seldepth 3 multipv 1 score cp 50 nodes 93 nps 93000 tbhits 0 time 1 pv e2e4 e7e6 d2d4 d7d5
info depth 4 seldepth 4 multipv 1 score cp 50 nodes 140 nps 70000 tbhits 0 time 2 pv e2e4 e7e6 d2d4 d7d5
info depth 5 seldepth 5 multipv 1 score cp 87 nodes 189 nps 94500 tbhits 0 time 2 pv e2e4 e7e6 d2d4
info depth 6 seldepth 6 multipv 1 score cp 49 nodes 469 nps 234500 tbhits 0 time 2 pv e2e4 e7e6 d2d4 d7d5 b1c3 g8f6
info depth 7 seldepth 7 multipv 1 score cp 65 nodes 1039 nps 346333 tbhits 0 time 3 pv e2e4 e7e6 d2d4 d7d5 b1c3 d5e4 c3e4
info depth 8 seldepth 9 multipv 1 score cp 38 nodes 3302 nps 660400 tbhits 0 time 5 pv e2e4 e7e6 d2d4 d7d5 b1c3 f8b4 e4e5 c7c5 g1f3
info depth 9 seldepth 13 multipv 1 score cp 57 nodes 7608 nps 634000 tbhits 0 time 12 pv e2e4 e7e6 d2d4 d7d5 b1c3 g8f6 e4e5 f6d7
info depth 10 seldepth 11 multipv 1 score cp 28 nodes 11441 nps 673000 tbhits 0 time 17 pv e2e4 e7e5 g1f3 g8f6 b1c3 b8c6 f1c4 f8b4 e1g1 e8g8 d2d4 e5d4 f3d4 c6d4 d1d4
info depth 11 seldepth 15 multipv 1 score cp 39 nodes 24808 nps 775250 tbhits 0 time 32 pv g1f3 g8f6 d2d4 e7e6 c2c4 d7d5 b1c3 f8e7 c1f4 e8g8
info depth 12 seldepth 16 multipv 1 score cp 47 nodes 50047 nps 807209 tbhits 0 time 62 pv e2e4
bestmove e2e4 ponder e7e6
```

The last depth SF reports 50047 nodes, more than the limit of 50000.

It is not a big deal but if anyone could:
- confirm if the number of nodes reported in the last iteration is the total searched nodes so far (from depth 0) or only from the last iteration? (ambiguous to me)
- check if there is any bug on the node counter
- explain why the total is over the limit
- correct (if not so hard) thus SF looks not cheating ;)

Perhaps an explanation is enough!

**Comment by vondele** [comment]
yes, nodes, like time, are only checked with a finite resolution, you can expect it to exceed the maximum by up to a few hundred nodes, which is less than 1ms worth of computation. This is by design.
