### ISSUE TITLE
"Worlds fastest Chess movegen"

### ISSUE THREAD

**Issue by NightlyKing** [official-stockfish/Stockfish#3733]
Some people in the Stockfish discord stumbled into a reddit thread with a new move generator written in C++ which only uses the CPU. First tests show a speedup of 5x or more over our move generator.
Given that around 30% (if I recall correctly) of all time is spent generating moves, this immense speedup could give us quite some elo.

Note: I haven't looked at the code and thus can't say if it is clean nor if there are any new dependencies. I just thought it'd be nice to have it here: https://github.com/Gigantua/Gigantua/tree/main/Gigantua

Maybe some movegen wizard will look through the code and see possible speedups for SF :)

**Comment by Gigantua** [comment]
My Article explains the 3 main ideas:
https://www.codeproject.com/Articles/5313417/Worlds-Fastest-Bitboard-Chess-Movegenerator

Greetings - Daniel

**Comment by mega-optimus** [comment]
The approach seems to rely on the assumption that the root position is fixed.  It may be useful for perft calculation (if we always calculate from the new game position), but it is essentially off loading perft to compile time. It is not likely useful for chess engines.

**Comment by vondele** [comment]
I'll close this, so far no tests of these ideas in SF as far as I know.
