### ISSUE TITLE
Use SpaCy 3.2 when running Stockfish on Apple devices

### ISSUE THREAD

**Issue by lex312** [official-stockfish/Stockfish#3788]
https://spacy.io/usage/v3-2

It can make Stockfish up to 8 times faster on the M1, M1 Pro and M1 Max.

**Comment by vondele** [comment]
I guess that link bases on https://github.com/explosion/thinc-apple-ops  and https://gist.github.com/dougallj/7a75a3be1ec69ca550e7c36dc75e0d6f 

now, that's far from a patch that makes SF 8x faster. ...

**Comment by vondele** [comment]
meanwhile some optimization for ARM has been done, obviously nothing close to 8x.
