### ISSUE TITLE
[Code Analysis] Caller failing to hold lock before calling function

### ISSUE THREAD

**Issue by calcitem** [official-stockfish/Stockfish#3790]
Visual Studio 2022 Code Analysis reports:

Warning	C26110	Caller failing to hold lock '`operator<<'::`2'::m' before calling function 'std::_Mutex_base::unlock'.
Warning	C26115	Failing to release lock '`operator<<'::`2'::m' in function 'operator<<'.	
Warning	C26117	Releasing unheld lock '`operator<<'::`2'::m' in function 'operator<<'.	

misc.cpp

```c++
/// Used to serialize access to std::cout to avoid multiple threads writing at
/// the same time.

std::ostream& operator<<(std::ostream& os, SyncCout sc) {

  static std::mutex m;

  if (sc == IO_LOCK)
      m.lock();    // Warning C26110

  if (sc == IO_UNLOCK)
      m.unlock();    // Warning C26115 & C26117

  return os;
}
```

See:
https://docs.microsoft.com/en-us/cpp/code-quality/c26110?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26110)%26rd%3Dtrue&view=msvc-170
https://docs.microsoft.com/en-us/cpp/code-quality/c26115?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26115)%26rd%3Dtrue&view=msvc-170
https://docs.microsoft.com/en-us/cpp/code-quality/c26117?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26117)%26rd%3Dtrue&view=msvc-170

**Comment by gvreuls** [comment]
If this was a local mutex the errors would make sense, so it looks like Visual Studio Code Analysis doesn't understand that this is a static mutex which keeps its state between calls to the << operator.

**Comment by vondele** [comment]
yes, agreed, this is not an issue in the code
