### ISSUE TITLE
search issues in a position(evals stuck for 50+ depths)

### ISSUE THREAD

**Issue by derpwaffle21** [official-stockfish/Stockfish#3815]
8/6B1/8/3q4/6PK/6QP/p3k3/1b6 w - - 0 1

in this position the latest stockfish dev(from November 28) eval hits 10+ at depth 25 and shows absolutely no progress for several depths(up to 100+)

Stockfish 281121 by the Stockfish developers (see AUTHORS file)
position fen 8/6B1/8/3q4/6PK/6QP/p3k3/1b6 w - - 0 1
go infinite
info string NNUE evaluation using nn-3678835b1d3d.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp 15 nodes 160 nps 160000 tbhits 0 time 1 pv g3f4
info depth 2 seldepth 2 multipv 1 score cp 76 nodes 255 nps 127500 tbhits 0 time 2 pv g3f4 a2a1q
info depth 3 seldepth 3 multipv 1 score cp 76 nodes 366 nps 183000 tbhits 0 time 2 pv g3f4 a2a1q g7a1
info depth 4 seldepth 4 multipv 1 score cp 59 nodes 979 nps 489500 tbhits 0 time 2 pv g3f4 d5b3 f4h2 e2f3
info depth 5 seldepth 5 multipv 1 score cp 14 nodes 3261 nps 1087000 tbhits 0 time 3 pv g3f4 d5e4 f4f6 a2a1r f6a1 e4h7 h4g3
info depth 6 seldepth 7 multipv 1 score cp 24 nodes 4339 nps 1084750 tbhits 0 time 4 pv g3h2 e2e1 h2g3 e1d1
info depth 7 seldepth 7 multipv 1 score cp 33 nodes 17703 nps 1609363 tbhits 0 time 11 pv g7f6 d5c6 g3e5 c6e4 e5b5 e2d1
info depth 8 seldepth 9 multipv 1 score cp 25 nodes 29250 nps 1720588 tbhits 0 time 17 pv g3e5 d5e4 e5e4 b1e4 h4g3 e2e3 h3h4 e4f3
info depth 9 seldepth 10 multipv 1 score cp 47 nodes 37557 nps 1877850 tbhits 0 time 20 pv g3e5 d5e5 g7e5 e2f3 h4g5 a2a1r e5a1 f3g3 h3h4
info depth 10 seldepth 13 multipv 1 score cp 43 nodes 67739 nps 1992323 tbhits 0 time 34 pv g3e5 b1e4 e5d5 e4d5 h4g5 e2f3 h3h4 f3e2 g7e5
info depth 11 seldepth 13 multipv 1 score cp 54 nodes 74917 nps 2081027 tbhits 0 time 36 pv g3e5 b1e4 e5d5 e4d5 h4g3 e2e3 h3h4 d5c4 h4h5 c4e2 h5h6
info depth 12 seldepth 16 multipv 1 score cp 111 nodes 94865 nps 2258690 tbhits 0 time 42 pv g3e5 d5e4 h4g5 e2f3 e5e4 b1e4 h3h4 f3g3
info depth 13 seldepth 14 multipv 1 score cp 156 nodes 133433 nps 2566019 tbhits 0 time 52 pv g3e5 b1e4 e5d5 e4d5 h4g5 e2f3 h3h4 d5e6 h4h5
info depth 14 seldepth 18 multipv 1 score cp 210 nodes 230014 nps 2987194 tbhits 0 time 77 pv g3e5 d5e5 g7e5 e2f2 h4g5 f2f3 h3h4 f3g2 h4h5 g2f3 h5h6 b1h7 e5a1 f3g3 a1b2 g3f3 b2e5
info depth 15 seldepth 17 multipv 1 score cp 228 nodes 275114 nps 3091168 tbhits 0 time 89 pv g3e5 d5e5 g7e5 e2f2 h4g5 f2f3 h3h4 f3g2 h4h5 g2f3 h5h6 b1h7 e5a1 f3g3 a1b2 g3f3 b2e5
info depth 16 seldepth 31 multipv 1 score cp 284 nodes 393742 nps 3308756 tbhits 0 time 119 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e4 h4h5 e4f3 a1f6 b1h7 f6e5 f3g2 e5a1 g2g3 h5h6
info depth 17 seldepth 25 multipv 1 score cp 324 nodes 488798 nps 3442239 tbhits 0 time 142 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 h4h5 b1d3 g5h6 d3e2 g4g5 e6f5 g5g6 e2f3 g6g7 f3d5 h6h7 f5g5 h5h6
info depth 18 seldepth 28 multipv 1 score cp 362 nodes 651599 nps 3541298 tbhits 0 time 184 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1c2 h4h5 c2d1 g4g5 e6f5 g5g6 d1e2 g6g7 e2c4 h6h7 f5g5 h5h6
info depth 19 seldepth 28 multipv 1 score cp 437 nodes 921645 nps 3686580 tbhits 0 time 250 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1c2 h4h5 c2d1 g4g5 e6f5 g5g6 f5g4 g6g7 d1b3 h6g6 b3c2 g6f6 c2h7 h5h6
info depth 20 seldepth 32 multipv 1 score cp 500 nodes 1359921 nps 3756687 tbhits 0 time 362 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 h4h5 b1c2 g5h6 c2d1 g4g5 e6f5 g5g6 f5g4 g6g7 d1b3 h6g6 b3c2 g6f6 c2h7 h5h6 g4h4
info depth 21 seldepth 34 multipv 1 score cp 625 nodes 2393488 nps 3817365 tbhits 0 time 627 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e4 h4h5 e4f3 h5h6 b1c2 g5h5 f3f4 g4g5 c2e4 g5g6 e4f3 h5h4 f3e4 h6h7 e4g6
info depth 22 seldepth 34 multipv 1 score cp 684 nodes 4946650 nps 3605430 hashfull 642 tbhits 0 time 1372 pv g3e5 d5e5 g7e5 a2a1b e5a1 e2e3 h4g5 e3e4 h3h4 e4d5 g5f6 d5e4 a1e5 e4f3 f6g5 f3e4 e5b2 e4d5 h4h5 d5e6 g5h6 b1d3 h6g7 d3e2
info depth 23 seldepth 42 multipv 1 score cp 759 nodes 6113777 nps 3579494 hashfull 760 tbhits 0 time 1708 pv g3e5 d5e5 g7e5 a2a1b e5a1 e2e3 h4g5 e3e4 h3h4 e4d5 g5f6 d5e4 a1e5 e4f3 f6g5 f3e4 e5b2 e4d5
info depth 24 seldepth 24 multipv 1 score cp 759 nodes 6324032 nps 3580992 hashfull 772 tbhits 0 time 1766 pv g3e5 d5e5 g7e5 e2f3 h4g5 f3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4
info depth 25 seldepth 16 multipv 1 score cp 759 nodes 6402835 nps 3577002 hashfull 777 tbhits 0 time 1790 pv g3e5 d5e5 g7e5 e2f3 h4g5 f3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3e2 g4g5 e6f5
info depth 26 seldepth 17 multipv 1 score cp 759 nodes 6481955 nps 3573293 hashfull 781 tbhits 0 time 1814 pv g3e5 d5e5 g7e5 e2f3 h4g5 f3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3e2 g4g5 e6f5 g5g6
info depth 27 seldepth 17 multipv 1 score cp 759 nodes 6553110 nps 3571177 hashfull 784 tbhits 0 time 1835 pv g3e5 d5e5 g7e5 e2f3 h4g5 f3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3e2 g4g5 e6f5 g5g6
info depth 28 seldepth 17 multipv 1 score cp 759 nodes 6649171 nps 3565239 hashfull 789 tbhits 0 time 1865 pv g3e5 d5e5 g7e5 e2f3 h4g5 f3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3e2 g4g5 e6f5 g5g6
info depth 29 seldepth 26 multipv 1 score cp 759 nodes 6747188 nps 3554893 hashfull 795 tbhits 0 time 1898 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4 h6h7 e6d7 g7h6 g4e6
info depth 30 seldepth 17 multipv 1 score cp 759 nodes 6847064 nps 3551381 hashfull 799 tbhits 0 time 1928 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6
info depth 31 seldepth 18 multipv 1 score cp 759 nodes 6943755 nps 3544540 hashfull 804 tbhits 0 time 1959 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4
info depth 32 seldepth 18 multipv 1 score cp 759 nodes 7030152 nps 3538073 hashfull 808 tbhits 0 time 1987 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4
info depth 33 seldepth 19 multipv 1 score cp 759 nodes 7180758 nps 3528628 hashfull 818 tbhits 0 time 2035 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4 h6h7
info depth 34 seldepth 18 multipv 1 score cp 759 nodes 7397677 nps 3517678 hashfull 833 tbhits 0 time 2103 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4
info depth 35 seldepth 31 multipv 1 score cp 759 nodes 7940135 nps 3493240 hashfull 871 tbhits 0 time 2273 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4
info depth 36 seldepth 18 multipv 1 score cp 759 nodes 8129282 nps 3481491 hashfull 880 tbhits 0 time 2335 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2 h5h6 e2g4
info depth 37 seldepth 16 multipv 1 score cp 759 nodes 8407223 nps 3458339 hashfull 893 tbhits 0 time 2431 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3c4 h6g7 c4e2
info depth 38 seldepth 24 multipv 1 score cp 759 nodes 8961112 nps 3437327 hashfull 913 tbhits 0 time 2607 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d5e6 g5h6 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4 h6h7
info depth 39 seldepth 18 multipv 1 score cp 759 nodes 9176383 nps 3425301 hashfull 922 tbhits 0 time 2679 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d3c2 g5h6 d5e4 g4g5 e4f5 g5g6 c2d3
info depth 40 seldepth 21 multipv 1 score cp 759 nodes 9479027 nps 3410948 hashfull 931 tbhits 0 time 2779 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d3c2 g5h6 d5e4 g4g5 e4f5 g5g6 c2d3 g6g7 d3c4 h6h7
info depth 41 seldepth 26 multipv 1 score cp 759 nodes 10151294 nps 3393946 hashfull 950 tbhits 0 time 2991 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 b1d3 h3h4 e4d5 h4h5 d3c2 g5h6 d5e4 g4g5 e4f5 g5g6 f5f4
info depth 42 seldepth 23 multipv 1 score cp 759 nodes 10577697 nps 3370840 hashfull 959 tbhits 0 time 3138 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4 h6h7 f5g5 h5h6
info depth 43 seldepth 16 multipv 1 score cp 759 nodes 11019215 nps 3346254 hashfull 965 tbhits 0 time 3293 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5
info depth 44 seldepth 23 multipv 1 score cp 759 nodes 11465188 nps 3313638 hashfull 971 tbhits 0 time 3460 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4 h6h7 f5g5 h5h6
info depth 45 seldepth 17 multipv 1 score cp 759 nodes 11972127 nps 3280933 hashfull 976 tbhits 0 time 3649 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6
info depth 46 seldepth 22 multipv 1 score cp 759 nodes 12920496 nps 3250439 hashfull 988 tbhits 0 time 3975 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4 h6h7 f5g5
info depth 47 seldepth 17 multipv 1 score cp 759 nodes 13644482 nps 3211977 hashfull 992 tbhits 0 time 4248 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6
info depth 48 seldepth 20 multipv 1 score cp 759 nodes 14170371 nps 3185784 hashfull 993 tbhits 0 time 4448 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4
info depth 49 seldepth 18 multipv 1 score cp 759 nodes 15468117 nps 3152255 hashfull 997 tbhits 0 time 4907 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3
info depth 50 seldepth 18 multipv 1 score cp 759 nodes 16115288 nps 3126753 hashfull 998 tbhits 0 time 5154 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3
info depth 51 seldepth 19 multipv 1 score cp 759 nodes 16800025 nps 3110539 hashfull 999 tbhits 0 time 5401 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7
info depth 52 seldepth 17 multipv 1 score cp 759 nodes 19103123 nps 3048208 hashfull 999 tbhits 0 time 6267 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6
info depth 53 seldepth 20 multipv 1 score cp 759 nodes 20214311 nps 2996488 hashfull 1000 tbhits 0 time 6746 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3 g6g7 d3c4
info depth 54 seldepth 18 multipv 1 score cp 759 nodes 21882222 nps 2962260 hashfull 1000 tbhits 0 time 7387 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3
info depth 55 seldepth 18 multipv 1 score cp 759 nodes 23390937 nps 2943366 hashfull 1000 tbhits 0 time 7947 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 d3e2 g4g5 e6f5 g5g6 e2d3
info depth 56 seldepth 21 multipv 1 score cp 759 nodes 26540655 nps 2908246 hashfull 1000 tbhits 0 time 9126 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7 d3c4 h6h7
info depth 57 seldepth 19 multipv 1 score cp 759 nodes 28287158 nps 2874419 hashfull 1000 tbhits 0 time 9841 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7
info depth 58 seldepth 18 multipv 1 score cp 759 nodes 30176626 nps 2861157 hashfull 1000 tbhits 0 time 10547 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5
info depth 59 seldepth 20 multipv 1 score cp 759 nodes 31950543 nps 2831741 hashfull 1000 tbhits 0 time 11283 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7
info depth 60 seldepth 18 multipv 1 score cp 759 nodes 35318038 nps 2795254 hashfull 1000 tbhits 0 time 12635 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5
info depth 61 seldepth 19 multipv 1 score cp 759 nodes 38042702 nps 2782322 hashfull 1000 tbhits 0 time 13673 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7
info depth 62 seldepth 26 multipv 1 score cp 759 nodes 40242977 nps 2767361 hashfull 1000 tbhits 0 time 14542 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7 d3c4 h6h7 f5g5 h5h6 g5h5 a1f6 a2a1r
info depth 63 seldepth 19 multipv 1 score cp 759 nodes 43701350 nps 2762236 hashfull 1000 tbhits 0 time 15821 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7
info depth 64 seldepth 22 multipv 1 score cp 759 nodes 47382630 nps 2756566 hashfull 1000 tbhits 0 time 17189 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 g5h6 b1d3 h4h5 e6f7 g4g5 f7e6 g5g6 e6f5 g6g7 d3c4 h6h7 f5g5
info depth 65 seldepth 21 multipv 1 score cp 759 nodes 51532224 nps 2751907 hashfull 1000 tbhits 0 time 18726 pv g3e5 d5e5 g7e5 e2e3 h4g5 e3e4 e5a1 e4d5 h3h4 d5e6 h4h5 b1d3 g5h6 e6f7 g4g5 d3c2 g5g6 f7g8 h6g5 c2b1 a1b2

after testing many sf dev versions, i've found out that stockfish_21092323 has this same problem while stockfish_21092119 resolves its way up to a tb win without much problem

i would assume that the "Detect search explosions" patch(https://github.com/official-stockfish/Stockfish/pull/3714) caused this problem

and since this a unfavorable behaviour in high-depth analysis or in engine tournaments, i hope this can be fixed soon

**Comment by Vinvin20** [comment]
This kind of issue reminds me it would be interesting to set some positions as a sanity check for each new version.
A collection of 20 to 50 special positions to check the search (mainly tree explosion at a depth) and to check the solution is found (to see of something is not broken).

**Comment by Sopel97** [comment]
There does indeed appear there to be a correlation between stuck evals and `seldepth < depth`

**Comment by vondele** [comment]
I think that "makes sense". A lot of extensions on the PV line result in search finding something that fails low/high, which results in another line becoming PV, being extended, and failing low/high, and so on.
