### ISSUE TITLE
Increase bench problem size

### ISSUE THREAD

**Issue by Gigantua** [official-stockfish/Stockfish#3832]
The bench command runs in 1.5 seconds on modern processors. 
I recommend increasing that again to something that needs 30 seconds at least. 
With 1.5s you get the most insane singlethread turbo thats not indicative of actual nps that will be achieved. 

Is about ./Stockfish bench

**Comment by Gigantua** [comment]
Its not even so much about turbo as it is about statistical nps fluctuations that 1.5s is waaaay to fast. 
The standard deviation is too high!

**Comment by BM123499** [comment]
My computer takes about 7s when I use battery save mode, so I would like not to increase time spent that much.

**Comment by Sopel97** [comment]
I don't see a problem. You can run whatever depth bench you want.

**Comment by robbai** [comment]
Bench is not used as a measure of NPS

**Comment by Gigantua** [comment]
> Bench is not used as a measure of NPS

Total time (ms) : 1600
Nodes searched  : 4749514
Nodes/second    : 2968446

So what does Nodes/second mean for you?

**Comment by Gigantua** [comment]
Ah this can be closed: i didnt see that bench had parameters:
./stockfish bench 128 32 25 default depth

Total time (ms) : 34905
Nodes searched  : 1800109102
Nodes/second    : 51571668
