### ISSUE TITLE
How can open-source version of 4playerchess.com be designed with Stockfish?

### ISSUE THREAD

**Issue by PrasadNR** [official-stockfish/Stockfish#3844]
### Discussed in https://github.com/official-stockfish/Stockfish/discussions/3843

<div type='discussions-op-text'>

<sup>Originally posted by **PrasadNR** December 11, 2021</sup>
I am not sure if this has to be started from "scratch" with reinforcement deep-learning or min-max alpha-beta search-tree pruning or other algorithms.

I am also not sure if Stockfish can be modified slightly (in order to accommodate for additional 4 x 8 x 3 cells given that Stockfish works for 8 x 8 cells from what I know).</div>

**Comment by vondele** [comment]
not an issue
