### ISSUE TITLE
What are the hardware limits for Stockfish?

### ISSUE THREAD

**Issue by curiosport** [official-stockfish/Stockfish#3861]
Up to how many cores can Stockfish handle? and also up to how much RAM can it handle?

And finally, what is the maximum possible size a hash can be?

**Comment by vondele** [comment]
the largest hash size supported is 33554432MB, the non-cluster version has a limit of 512 threads, but that's a cosmetic thing on the input level, more is no problem. AFAIK, the cluster version has been run with 65536 threads.

**Comment by curiosport** [comment]
When you say "non-cluster version" you mean a version that everyone must compile by himself? because I have never seen in the download section a non-cluster version. And out of curiosity is the "run with 65536 threads" plays available?

If I used a 32TB hash, Stockfish will occupy exactly 32TB or how much more?

**Comment by Sopel97** [comment]
> When you say "cluster version" you mean a version that everyone must compile by himself?
Yes, https://github.com/official-stockfish/Stockfish/tree/cluster

> And out of curiosity is the "run with 65536 threads" plays available?
It was a bench run http://ipmanchess.yolasite.com/amd--intel-chess-bench-stockfish.php

> If I used a 32TB hash, Stockfish will occupy exactly 32TB or how much more?
Negligibly more

**Comment by curiosport** [comment]
> Negligibly more

I imagine that will vary depending on the number of threads you are going to use. Is there a formula for calculating the exact amount of RAM needed given the hash size and number of threads?

**Comment by vondele** [comment]
it is a few MB (10-20?) per thread, and about 70MB for the process (including the net9
