### ISSUE TITLE
Possible divide by zero error

### ISSUE THREAD

**Issue by FireFather** [official-stockfish/Stockfish#3880]
search.cpp

```
72		Depth reduction(bool i, Depth d, int mn, Value delta, Value rootDelta) {
73		int r = Reductions[d] * Reductions[mn];
74		return (r + 1358 - int(delta) * 1024 / int(rootDelta)) / 1024 + (!i && r > 904);
75		}
```
dividing by rootDelta -> need to be certain it's not 0

```
678		else
679		thisThread->rootDelta = beta - alpha;
```

if alpha and beta are equal (as in a null-window search), the call to
reduction(bool i, Depth d, int mn, Value delta, Value rootDelta) will crash

```
1074	// Reduced depth of the next LMR search
1075	int lmrDepth = std::max(newDepth - reduction(improving, depth, moveCount, delta, thisThread->rootDelta), 0);
```

Possible fix:

```
72		Depth reduction(bool i, Depth d, int mn, Value delta, Value rootDelta) {
73		int r = Reductions[d] * Reductions[mn];
74		if (rootDelta != 0)
75			return (r + 1358 - int(delta) * 1024 / int(rootDelta)) / 1024 + (!i && r > 904);
76		else  // avoid divide by zero error
77			return (r + 1358 - int(delta) * 1024) / 1024 + (!i && r > 904);
78		}
```

There may be a more elegant way, for ex: check & bound the value of rootDelta before calling 
Depth reduction(bool i, Depth d, int mn, Value delta, Value rootDelta)

**Comment by vondele** [comment]
beta should always be larger than alpha? 
https://github.com/official-stockfish/Stockfish/blob/0b41887527f1d7264ee5644dfa53e00ab64441b1/src/search.cpp#L1397

**Comment by Sopel97** [comment]
if it doesn't crash then it means it's never 0

**Comment by vondele** [comment]
null window means alpha == beta - 1 (https://www.chessprogramming.org/Null_Window)

**Comment by FireFather** [comment]
> if it doesn't crash then it means it's never 0

I compiled SF dev in x64 Debug (via MSVS), ran it for a while and it crashed indicting a divide by zero error

**Comment by Sopel97** [comment]
No, MSVC is just not supported because it miscompiles Stockfish.

**Comment by FireFather** [comment]
Anyway, please do what you think is best, and thanks for all the effort you guys put in!

**Comment by joergoster** [comment]
> https://en.wikipedia.org/wiki/Alpha%E2%80%93beta_pruning
> 
> "In the extreme case, the search is performed with alpha and beta equal; a technique known as zero-window search, null-window search, or scout search."

Wikipedia is wrong on this.
Like @vondele already mentioned, a zero-window is alpha = beta-1.
There is no other value possible inside this window, hence _zero-window_.

**Comment by FireFather** [comment]
"There is no other value possible inside this window, hence zero-window."

Thanks Joerg, yes that does make sense.  One would really have to examine SF exact alpha-beta aspiration implementation very closely, or do some tests, to determine if alpha can ever be equal to beta.  The current assert doesn't prevent that.

I do know that Stockfish does crash occasionally...but i's pretty rare.

Thanks!

**Comment by FireFather** [comment]
> No, MSVC is just not supported because it miscompiles Stockfish.
?
Microsoft (and Intel) compiler work just fine. I and many others have been using it for many years.
I have never had an issue, other than the MS compile is not as fast as minGW for ex.

**Comment by mstembera** [comment]
MSVC used to be supported as far back as I can remember.  For example see here https://groups.google.com/g/fishcooking/c/AuK998d71Z4/m/oBWelHPeMs0J when it was considered a show stopper by the past maintainers.
It is no longer "officially" supported or rather "tested" because Appveyor no longer runs on new PR's.  I can sympathize with this decision because our current maintainers don't use Windows.  Fixes for bugs under MSVC are still allowed however.  See https://github.com/official-stockfish/Stockfish/pull/3797#issuecomment-978865572   Given the huge number of devs using MSVC relative to the number of SF devs I would bet that if we get errors under MSVC we will learn something of interest about SF code.   I definitely care because the day SF doesn't compile under MSVC I will effectively be frozen out of contributing to SF.

**Comment by mega-optimus** [comment]
> > https://en.wikipedia.org/wiki/Alpha%E2%80%93beta_pruning
> > "In the extreme case, the search is performed with alpha and beta equal; a technique known as zero-window search, null-window search, or scout search."
> 
> @FireFather Wikipedia is possibly wrong on this. Like @vondele already mentioned, a zero-window is alpha = beta-1. Using integers, there is no other value possible inside this window, hence _zero-window_.

Since the windows is (alpha, beta) with alpha & beta **excluded**, if alpha == beta, then the window would be zero, is that correct?

**Comment by vondele** [comment]
so, no bug, I'll close the issue.
