### ISSUE TITLE
Stockfish gives +80.7 when it is draw - Evaluation wrong on endings of bishop and rock pawn

### ISSUE THREAD

**Issue by manuelgarciaortega** [official-stockfish/Stockfish#3894]
It would be nice to teach/add this type of position inside of the module, i can not believe that at this point it is not implemented yet. Position attached in the screenshot is draw and normal player will see it in seconds, but one of the best modules after minutes and even more doesn't see that it is draw.

![imagen](https://user-images.githubusercontent.com/351563/150193687-6eb20f1e-287d-4823-b005-d7eed073289d.png)

**Comment by manuelgarciaortega** [comment]
SAME HERE, where MONEY was ....

![imagen](https://user-images.githubusercontent.com/351563/150199019-b0bc6e79-c5ab-48db-ba38-78325e066f29.png)

**Comment by vondele** [comment]
There will always be positions that are wrongly evaluated, especially constructed ones. Not much we can do to fix particular positions, but fortunately, the number of them gets smaller over time.

**Comment by manuelgarciaortega** [comment]
> There will always be positions that are wrongly evaluated, especially constructed ones. Not much we can do to fix particular positions, but fortunately, the number of them gets smaller over time.

Well, if a game played last year between Jones and Nakamura brings to a position especially constructed, I am not sure which type the position we expect to evaluate.

**Comment by vondele** [comment]
I was referring to the position in your first comment https://github.com/official-stockfish/Stockfish/issues/3894#issue-1108436452

I'm not sure what the other position is. `8/8/2B5/7p/6p1/2K1k1P1/7P/8 w - - 0 1` is a white win ?

**Comment by Vizvezdenec** [comment]
1st position is artificial and is completely useless.  
7 bishops of the same color isn't smth sf is designed to evaluate any sort of decently because this position will never happen in 10^50 real games.

**Comment by manuelgarciaortega** [comment]
> I was referring to the position in your first comment [#3894 (comment)](https://github.com/official-stockfish/Stockfish/issues/3894#issue-1108436452)
> 
> I'm not sure what the other position is. `8/8/2B5/7p/6p1/2K1k1P1/7P/8 w - - 0 1` is a white win ?

No, both positions are draw.

**Comment by vondele** [comment]
OK, second position with black to move is a draw. SF eval at d28 is -224,

**Comment by manuelgarciaortega** [comment]
> 1st position is artificial and is completely useless. 7 bishops of the same color isn't smth sf is designed to evaluate any sort of decently because this position will never happen in 10^50 real games.

This one was to bring/ask about basic chess knowledge, but I agree with you that it is useless in real life, unless it is used to check chess evaluation.

**Comment by manuelgarciaortega** [comment]
Anyway, MANY THANKS!! for great Stockfish!!! I use it almost everyday.

**Comment by Vizvezdenec** [comment]
Stockfish is not about basic chess knowledge but about analysing and playing as good of chess as possible. Correctly evaluating positions with 8 bishops of the same color is smth we can bother as soon as we will play perfect moves in every sort of realistic positions.
We are close but still not quite there :)

**Comment by manuelgarciaortega** [comment]
> Stockfish is not about basic chess knowledge but about analysing and playing as good of chess as possible. Correctly evaluating positions with 8 bishops of the same color is smth we can bother as soon as we will play perfect moves in every sort of realistic positions. We are close but still not quite there :)

8/8/2B5/7p/6p1/2K1k1P1/7P/8 w - - 0 1

**Comment by aga-mp** [comment]
latest dev gives 0 for the second position if black to move?

![image](https://user-images.githubusercontent.com/2290607/154860930-f0777899-2512-46b5-92e4-62ef989571f9.png)
