### ISSUE TITLE
Latest changes to Makefile result in stockfish faulting on Windows 10 19044.1466

### ISSUE THREAD

**Issue by jackL999** [official-stockfish/Stockfish#3897]
The changes in Makefile as given in commit 67062637f4 cause stockfish to crash on Windows 10 when the executable is compiled with x86_64-w64-mingw32-g++ on Arch Linux gcc 11.2.0 ,
`Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: /build/mingw-w64-gcc/src/gcc/configure --prefix=/usr --libexecdir=/usr/lib --target=x86_64-w64-mingw32 --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,lto,c++,ada,objc,obj-c++,fortran --enable-shared --enable-static --enable-threads=posix --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --with-system-zlib --enable-cloog-backend=isl --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (GCC)`

or with x86_64-w64-mingw32-g++ on Windows

**Comment by vondele** [comment]
can you post your exact `make` command line?

**Comment by jackL999** [comment]
I have tried several make commands and they all result in an executable that crashes due to an access violation. The one I have used dozens of times, including on the version before the latest commit always worked without a problem.

'make -j8 profile-build ARCH=x86-64-bmi2 COMP=mingw CPPFLAGS="-DNNUE_EMBEDDING_OFF -march=haswell"`
 But even the much simpler command doesn't work
`make build ARCH=x86-64-bmi2 COMP=mingw`

Comparing compilations from the previous Makefile to the new one in commit 6706263 everything is the same except the new commit adds  -flto=auto   which causes the executable to crash.

**Comment by vondele** [comment]
can you test what happens for you if you replace `-flto=auto` with `-flto` in the Makefile?

**Comment by ppigazzini** [comment]
Please let me know the version of your `x86_64-w64-mingw32-g++` on Windows, the latest one provided by msys2 and cygwin are working fine for me.

**Comment by jackL999** [comment]
I did get the Makefile given in commit 6706263 to work when using Ubuntu mingw-w64 gcc version 9.3, but not Arch Linux's 11.2 version. 
`x86_64-w64-mingw32-c++-posix -v
Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-c++-posix
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --enable-threads=posix --program-suffix=-posix --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes --enable-dependency-tracking
Thread model: posix
gcc version 9.3-posix 20200320 (GCC)`

The Makefile also works after I upgraded my Windows based mingw-w64 to the one from WinLibs.com (gcc 11.2)

**Comment by ppigazzini** [comment]
This should be solved.
