### ISSUE TITLE
Stockfish suggests draw move (due to 50 move rule) where WDL=2

### ISSUE THREAD

**Issue by MinetaS** [official-stockfish/Stockfish#3902]
~Example: 2KB4/k5n1/p7/8/8/8/8/4N3 w - -~
~There are 5 pieces (KBNvKNP), and according to the syzygy tablebase, white wins in 99 ply (which not violates 50 move rule)~

~I'm currently using ac07bd334b62 network, allocated 4GB for hash table and have 3,4,5-piece syzygy tablebases.~

~Input:~
~`position fen 2KB4/k5n1/p7/8/8/8/8/4N3 w - - 0 1 moves d8a5 g7e8 c8d7 e8f6 d7c7 f6d5 c7c6 d5f4 e1c2 f4e6 c6d7 e6f4 d7c7 f4d5 c7c6 d5e7 c6d6 e7g6 d6c7 g6f4 a5b6 a7a8 c7c8 f4d5 b6c5 d5c3 c2a3 c3b5 a3c4 b5a7 c8d7 a7b5 c4a5 a8b8 c5g1 b5a3`~

~Result: g1d4 (DTZ 65), but supposed to be g1h2 / Bh2+ (DTZ 61) otherwise it will go over 50 moves.~

~Please let me know if there are any flaws in my setup or me doing something wrong.~

Didn't add 6 piece tablebases, sorry for the confusion.

**Comment by Torom** [comment]
You give Stockfish moves after the FEN. Therefore, this is the position Stockfish assumes:

```
 +---+---+---+---+---+---+---+---+
 |   | k |   |   |   |   |   |   | 8
 +---+---+---+---+---+---+---+---+
 |   |   |   | K |   |   |   |   | 7
 +---+---+---+---+---+---+---+---+
 | p |   |   |   |   |   |   |   | 6
 +---+---+---+---+---+---+---+---+
 | N |   |   |   |   |   |   |   | 5
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 4
 +---+---+---+---+---+---+---+---+
 | n |   |   |   |   |   |   |   | 3
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 2
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   | B |   | 1
 +---+---+---+---+---+---+---+---+
   a   b   c   d   e   f   g   h

Fen: 1k6/3K4/p7/N7/8/n7/8/6B1 w - - 36 19
Key: ACC274D79683D2A9
Checkers: 
Tablebases WDL:  Win (Success)
Tablebases DTZ:   62 (Success)
```

If you just pass `position fen 2KB4/k5n1/p7/8/8/8/8/4N3 w - - 0 1`, Stockfish will assume the right position and want to play `Ba5` immediately:

```
info depth 1 seldepth 1 multipv 1 score cp 15265 nodes 1 nps 500 tbhits 13 time 2 pv d8a5
bestmove d8a5
```

**Comment by MinetaS** [comment]
Sorry, I didn't include 6-piece tablebases into the engine. Took a wrong sample.

Btw, SF fails to search beyond 50 move rule but I heard this is intended, so closing the issue by now.

**Comment by Torom** [comment]
Stockfish can ignore the 50 move rule with this UCI option:

[Syzygy50MoveRule](https://github.com/official-stockfish/Stockfish#syzygy50moverule)

"Disable to let fifty-move rule draws detected by Syzygy tablebase probes count as wins or losses. This is useful for ICCF correspondence games."
