### ISSUE TITLE
Makefile : please make it work on AMD Athlon

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#3904]
[stockfish-on-AMD-Athlon.patch.txt](https://github.com/official-stockfish/Stockfish/files/7930030/stockfish-on-AMD-Athlon.patch.txt)

Please remove SSE=yes requirements from Makefile for 32-bit PC (I'm using AMD Athlon as my legacy gaming PC -- both for old 3D shooters and for old Chess engines).
But SF14.1 doesn't run on it, because for Windows it was compiled for 32-bit SSE architecture. (which only appeared on AMD Athlon XP and AMD Athlon 64) 
(on Windows I use official 32-bit release builds, and on Linux I had to compile myself, since we don't provide 32-bit package)
and I had to modify Makefile to remove SSE=yes to SSE=no for 32-bit PC

**Comment by ppigazzini** [comment]
You can set the variables from the command line without editing the Makefile, eg
```bash
make -j profile-build ARCH=x86-32 COMP=gcc sse=no
```
