### ISSUE TITLE
RADAR_PRE_LEAK_64 log entries

### ISSUE THREAD

**Issue by TommyGH** [official-stockfish/Stockfish#3919]
I've noticed several informational RADAR_PRE_LEAK_64 log entries in my Windows 10 Event Viewer over the past few months for various versions of Stockfish.  I obtain the executables from ABROK.

Are these just "noise" entries? Or should something be investigated?

Stockfish executables are from:

29 January 22
13 January 22
22 December 21
23 November 21
28 October 21

=====

Fault bucket 1520434802498810544, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: stockfish_22012908_x64_bmi2.exe
P2: 0.0.0.0
P3: 10.0.19043.2.0.0

=====

Fault bucket 2053320932486755223, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: stockfish_22011322_x64_bmi2.exe
P2: 0.0.0.0
P3: 10.0.19043.2.0.0

=====

Fault bucket 1920664636496305473, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: stockfish_21122211_x64_bmi2.exe
P2: 0.0.0.0
P3: 10.0.19043.2.0.0

=====

Fault bucket 1181786493749808939, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: stockfish_21112321_x64_bmi2.exe
P2: 0.0.0.0
P3: 10.0.19043.2.0.0

=====

Fault bucket 2237508002621416747, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: stockfish_21102807_x64_bmi2.exe
P2: 0.0.0.0
P3: 10.0.19043.2.0.0

=====

**Comment by ppigazzini** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/radarpreleak64/a534e186-65ab-42c9-97e2-b654a713f0db
>RADAR is Microsoft's Memory Leak Detector so that error indicates an App/program is not properly handling memory. Check-in TaskManager and/or use Process Explorer from SysInternals. It is often a game though the error issued is just informative and a report was sent to Microsoft. So you really do not need to do anything.

https://answers.microsoft.com/en-us/windows/forum/all/radarpreleak/372855fb-1285-4f99-a352-4fd517e9b680
> Radar_Pre_Leak is technical nomenclature that means the OS has detected (Radar) a process that is not handling it routines in a manner that it thinks is efficient (Pre) and as a result it may begin to exhaust memory resources (Leak), i.e. it is a resource hog. It is entirely informational event, though, and does not mean it is necessarily running outside its bounds or has exhausted the limits of Windows memory management.

**Comment by vondele** [comment]
Thanks for the report, but I don't think these warnings are something we need to consider, they are probably false positives. We have observed no similar issues in this regard.
