### ISSUE TITLE
Link time optimisation works on mingw

### ISSUE THREAD

**Issue by braich** [official-stockfish/Stockfish#392]
In [Makefile](https://github.com/official-stockfish/Stockfish/blob/master/src/Makefile#L305) lto is turned off for mingw. But while using mingw compiler on Ubuntu 15.04 lto can be turned on. See, for example, http://abrok.eu/stockfish/

**Comment by lucasart** [comment]
You're right, but you're talking about the Linux cross compiler.

COMP=mingw is for Windows users, using gcc within a mingw command line environment.

Perhaps -flto works there too. I don't know, and I can't be bothered to install Wine to find out.

@mcostalba: you have Windows with MinGW, right? Can you confirm whether flto works there or not?

**Comment by mcostalba** [comment]
Last time I tried it didn't, I will do test again...

**Comment by braich** [comment]
@mcostalba last time I tried it works for x86-32 and doesn't work for x86-64-modern on Windows.
@lucasart current Makefile works fine without any modification for the mingw cross compile on Ubuntu.
So i propose to make a decision about -flto with help of UNAME variable.

**Comment by mcostalba** [comment]
I confirm it does not work for me: application crashes at startup.

This is my g++ -v

Reading specs from c:/gcc-win-builds/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/specs
COLLECT_GCC=c:\gcc-win-builds\bin\g++.exe
COLLECT_LTO_WRAPPER=c:/gcc-win-builds/bin/../libexec/gcc/x86_64-w64-mingw32/4.8.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-4.8.3/configure --prefix=/opt/windows_64 --with-sysroot=/opt/windows_64 --libdir=/opt/windows_64/lib64 --mandir=/opt/windows_64/man --infodir=/opt/windows_64/info --enable-shared --disable-bootstrap --disable-multilib --enable-threads=posix --enable-languages=c,c++ --enable-checking=release --enable-libgomp --with-system-zlib --with-python-dir=/lib64/python2.7/site-packages --disable-libunwind-exceptions --enable-__cxa_atexit --enable-libssp --with-gnu-ld --verbose --enable-java-home --with-java-home=/opt/windows_64/lib64/jvm/jre --with-jvm-root-dir=/opt/windows_64/lib64/jvm --with-jvm-jar-dir=/opt/windows_64/lib64/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar='/home/adrien/projects/win-builds-1.5/slackware64-current/d/gcc/antlr-*.jar' --disable-java-awt --disable-gtktest --build=x86_64-slackware-linux --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32
Thread model: posix
gcc version 4.8.3 (GCC)

**Comment by braich** [comment]
I've just compared performance of -flto enabled cross-compiled mingw32-w64 executable from Ubuntu and compiled without -flto in Windows. Strangely enough but cross-compiled with -flto is about 10% slower. Can anyone confirm this?
my Ubuntu g++ -v
```
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/4.9-posix/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --libexecdir='/usr/lib/gcc-mingw-w64' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++ --enable-lto --with-plugin-ld --enable-threads=posix --program-suffix=-posix --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld
Thread model: posix
gcc version 4.9.2 (GCC) 
```
My Windows g++ -v
```
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=c:/Program\ Files/mingw-w64/x86_64-4.9.2-release-posix-seh-rt_v4-rev2/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.2/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw492/x86_64-492-posix-seh-rt_v4-rev2/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --with-cloog=/c/mingw492/prerequisites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x86_64-posix-seh-rev2, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw492/x86_64-492-posix-seh-rt_v4-rev2/mingw64/opt/include -I/c/mingw492/prerequisites/x86_64-zlib-static/include -I/c/mingw492/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw492/x86_64-492-posix-seh-rt_v4-rev2/mingw64/opt/include -I/c/mingw492/prerequisites/x86_64-zlib-static/include -I/c/mingw492/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw492/x86_64-492-posix-seh-rt_v4-rev2/mingw64/opt/lib -L/c/mingw492/prerequisites/x86_64-zlib-static/lib -L/c/mingw492/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.2 (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 

```

**Comment by braich** [comment]
@mcostalba -flto is worked on Windows. It seems that there is a problem with -static option. To compile a working -flto enabled executable I've [removed -static from Makefile](https://github.com/braich/Stockfish/commit/71806dbd67bddd036bcdec3903e4022ba16316b0). 
Resulting executable is more than 5% faster (nonprofile build) but requires  three dlls
```
libwinpthread-1.dll
libstdc++-6.dll
libgcc_s_seh-1.dll
```

**Comment by lucasart** [comment]
@braich: try to exppain to the average wimdows user, that to make it work they need to copy some dll in an obscure system folder… to do that properly, we need to package sf into an executable, that will install and register the dll, to allow isentropic uninstallation.

people are welcome to compile like you did, modifying the makefile, but the default makefile should provide recipies that work out of the box.

**Comment by braich** [comment]
@lucasart you are right. Those dlls make things more complicated.
@all It seems to me that after Lazy SMP patch gcc with -flto option generates slower executable. This is not only for mingw. Native Linux builds are affected too. I've tested:
Archlinux 2015.09.01  gcc 5.2.0
Ubuntu 15.04 gcc 4.9.2
Ubuntu 15.04 gcc 4.9.2 mingw-w64
Windows 8.1 gcc 4.9.2 mingw-w64
Windows 8.1 gcc 5.2.0 mingw-w64

**Comment by braich** [comment]
Though it is possible to compile Stockfish on mingw with LTO there are some problems. 
1. LTO compiled executable needs additional DLLs, making it more difficult do distribute Stockfish binaries.
2. LTO compiled executable is slower than non-LTO.
So the issue is closed.
