### ISSUE TITLE
Help: How I can create a shared library (.so) from the precompiled stockfish binary

### ISSUE THREAD

**Issue by pavanjoshi914** [official-stockfish/Stockfish#3933]
I am trying to test stockfish in an Android device with CPU ```arm64-v8a```. To do so I have downloaded armv8 precompiled android binary of stockfish.

I am using Unity as a framework and am willing to test stockfish as a native plugin in form of the shared library.

can I use stockfish binary, just by changing its extension to .so ``` stockfish.android.armv8.so``` or any additional steps have to be performed to create a shared library from the precompiled stockfish binaries

**Comment by vondele** [comment]
you can't turn a binary into a .so as far as I know. Will need quite some work on the code to compile SF as a shared library. There are other issues on this topic.

**Comment by ETHybridCLR** [comment]
untiy  Android C# code:
![image](https://user-images.githubusercontent.com/8703667/226092809-c0e61741-6816-42b7-872d-34a5aa8ac636.png)
![image](https://user-images.githubusercontent.com/8703667/226092854-c8e63cd8-0057-4060-9204-83328bf15fbd.png)

who knows how to solve it，thx
