### ISSUE TITLE
Stockfish performance with Ryzen 3990x

### ISSUE THREAD

**Issue by YBacquet** [official-stockfish/Stockfish#3936]
Hello,

   I tried to use Stockfish 14.1 with several configurations.
With a Ryzen 3970x ( 32 cores ) configured to use 28 cores, I get around 30M N/s - 32M N/s .
With another computer, using a 3990x ( 64 cores ) configured to use 58 cores, same other parameters, I get around 30M N/s - 32M N/s too, no performance increased. If I change the hashtable size from 2048 Mb to 256 Mb, I get around 58M N/s - 60M N/s but over time, the node per sec is decreasing and the analysis depth is increasing slowly. It's pretty obvious 256Mb for the hashtable size is too low.
If I'm using an older version of Stockfish, I get the same results.

It looks like I don't get better performance if I'm using 30 cores or 60 . Does anyone can explain me what's going on ? I don't understand if I'm using wrong parameters or if there's a physical problem.

Thanks.

**Comment by Sopel97** [comment]
are all memory channels populated?

**Comment by YBacquet** [comment]
> are all memory channels populated?

Thank you for replying.
There's 1 of 8 slots used by a 32Go RAM .

**Comment by Sopel97** [comment]
3990x supports 4-channel memory, so to get good results you will need at least 4 memory sticks

**Comment by mstembera** [comment]
@YBacquet This is a known but not well diagnosed issue.  See https://github.com/official-stockfish/Stockfish/pull/3288
Before adding the memory sticks could you try adding
```C++
if ((tte[i].genBound8 & GENERATION_MASK) != generation8 && tte[i].depth8)
```
in tt.cpp on line 127 right above 
```C++
tte[i].genBound8 = uint8_t(generation8 | (tte[i].genBound8 & (GENERATION_DELTA - 1))); // Refresh
```
and report back either way whether it fixes your slowdown or not?

**Comment by YBacquet** [comment]
@mstembera Thank you for your help. 
I tried to compile a version with your modification but sadly I failed to compile it.
I got some error coming, NOT due to the modification. I got the same error even with a fresh download of the stockfish sources so I couldn't try it.
![stockfish-compilation](https://user-images.githubusercontent.com/62267313/154285314-2bff20fd-5e2a-4ab9-b75d-afcc9bd7acc6.jpg)
This is a bit out of topic, so I will investigate by myself to understand it ( I'm more used to web technologies and didn't do c++ since like 2 decades ) but of course some help would be very appreciated.

I will try a config with 4 * 8 Go memory sticks anyway, as soon as I can, probably friday. Many parameters are involved and I have to check everything.

**Comment by pschneider1968** [comment]
The Makefile says that for an LTO build, GCC needs to be 10.1 or higher. So, what is the output of
`which g++`
and
`g++ --version`  ?

Does it make a difference when you try to build with
`make -j profile-build ARCH=x86-64-bmi2 COMP=mingw` ?

**Comment by Sopel97** [comment]
I've been getting
```
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:12: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans3.ltrans.o] Error 1 (ignored)
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:9: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans2.ltrans.o] Error 1 (ignored)
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:18: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans5.ltrans.o] Error 1 (ignored)
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:21: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans6.ltrans.o] Error 1 (ignored)
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:6: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans1.ltrans.o] Error 1 (ignored)
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:15: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans4.ltrans.o] Error 1 (ignored)
make[2]: [C:\Programy\msys2\tmp\ccx1PtAn.mk:3: C:\Programy\msys2\tmp\stockfish.exe.O04FSG.ltrans0.ltrans.o] Error 1 (ignored)
make[1]: Leaving directory '/c/dev/stockfish-master/src'
```
after each build recently. Might be related.

**Comment by YBacquet** [comment]
@pschneider1968 @bftjoe I did a new install of MSYS, following the instructions given and I was able to build a new exe with the condition given by mstembera . I will try this build another day as I don't have access on the concerned machine atm .
Thanks a lot for helping me so fast. I will put my new performance results when it's done.

**Comment by pschneider1968** [comment]
Yeah, I was guessing that your environment was messed up someway, or you were not using the correct MSYS2 launcher.

Because, in your first screenshot, it said: Kernel:'MSYS_NT-10.0-19043' - that indicates you didn't use the MINGW64 launcher, but the MSYS2 launcher. The pure MSYS2 launcher normally does NOT have any compiler in its PATH. So I wonder where your g++ and as and ld and headers/libs are actually pulled in from? Also, g++ should be in /mingw64/bin/g++ (not in /user/bin as your wrote, and also not in /usr/bin)

You need to use the MINGW64 launcher, where `uname -a` (=Kernel) : 'MINGW64_NT-10.0-19044' then. This sets the environment + PATH so you can use the MINGW gcc compiler toolchain, from below /mingw64

In your new installation, it should be setup this way...

**Comment by Technologov** [comment]
I tested SF 14.1 and SF 14.0 and I get around 146 million NPS on my AMD Threadripper 3990X (running Debian Linux 11) -- and much lower on Windows (under half performance)

**Comment by dav1312** [comment]
http://ipmanchess.yolasite.com/amd--intel-chess-bench-stockfish.php
<html>
<body>

Nodes/second | CPU / Memory | Cores/Threads | Extension | Member | OS
-- | -- | -- | -- | -- | --
112.428.605 | AMD Ryzen Threadripper PRO 3990X @2.6Ghz ddr4 3200 CL22 | 128threads | avx2 | noobpwnftw | W11
80.676.124 | AMD Ryzen Threadripper 3970X @3.7Ghz ddr4 3200 CL24 | 64threads | avx2+LP | SuperChess | W10

</body>
</html>

**Comment by Ipmanchess** [comment]
@Technologov would like to have the log from your SF 14.1 if you have used: **bench 1024 128 26 default depth nnue**

**Comment by noobpwnftw** [comment]
Old version does not work properly under newer Windows due to NUMA API change, so half performance is probably about right.

**Comment by Technologov** [comment]
alexey@threadripper3990:~$ ./stockfish_14.1_linux_x64_avx2 bench 1024 128 26 default depth nnue > sf_14.1_threadripper_3990x_debian11.log
===========================
Total time (ms) : 64546
Nodes searched  : 9396609141
Nodes/second    : 145580038
[sf_14.1_threadripper_3990x_debian11.log](https://github.com/official-stockfish/Stockfish/files/8093335/sf_14.1_threadripper_3990x_debian11.log)

**Comment by Ipmanchess** [comment]
Thank you very much.. your bench will be added to list!

**Comment by vondele** [comment]
Thanks all for providing the numbers. I'll close this, this probably is not directly a SF issue.

**Comment by YBacquet** [comment]
After using 4 x 8Go RAM instead of 1 x 32Go RAM, I get 64M nodes/s .
I tried to modify the tt.cpp file as suggested before by mstembera and it didn't change anything.

**Comment by vondele** [comment]
OK, thanks for reporting back. Seems like populating all memory channels is indeed the key. We have observed that before on similar architectures.

**Comment by mstembera** [comment]
Yes thank you for reporting!  Just to note when this issue was reported in the past on the CCC machine Komodo wasn't experiencing the same slowdown as SF.  It means that maybe in the future a software solution will still be possible but I currently don't have any suggestions on what else to try.
