### ISSUE TITLE
Stockfish14.1 not wanting to win against Komodo 10 64-bit

### ISSUE THREAD

**Issue by CavanLeoJacobs** [official-stockfish/Stockfish#3945]
Stockfish14.1 plays very well, so good it even looks like a cake walk. But look what happens when Stockfish14.1 plays on move 80.
Stockfish14.1 is playing the black side.  
...80 a1B+?????? it shows a1Q+ is the best move AND the most natural AND the fastest checkmate.
It even draws a winning game/position (Stockfish14.1 had a Queen ,Bishop and a Rook up)
Here is the game. I can understand it needs to play with 0.1 min but it was not about the time that it played a1B+???????? 
Please fix this. This is very very sad. 

[Event "DESKTOP-DPE1FGP, Blitz 0.1min"]
[Site "DESKTOP-DPE1FGP"]
[Date "2022.02.25"]
[Round "2"]
[White "Komodo 10 64-bit"]
[Black "Stockfish 14.1"]
[Result "1/2-1/2"]
[ECO "B13"]
[Annotator "0.29;0.37"]
[PlyCount "311"]
[TimeControl "6"]

{Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz 2195 MHz W=9.8 plies; 929kN/s B=16.
9 plies; 2 221kN/s} 
1. d4 {0.29/14 0 Both last book move} Nf6 {0.37/16 0} 2.
Nc3 {0.32/13 0 (Nf3)} d5 {-0.18/14 0} 3. Bf4 {0.24/13 0 (Bg5)} c5 {-0.03/18 1 
(Bf5)} 4. e3 {0.46/12 0} cxd4 {0.07/17 0} 5. exd4 {0.49/13 0} Bg4 {-0.05/15 0 
(Qb6)} 6. f3 {0.46/13 0} Bd7 {-0.04/17 0} 7. Nb5 {0.32/14 0} Bxb5 {0.06/17 0}
8. Bxb5+ {0.29/15 0} Nc6 {0.00/18 0} 9. c3 {0.31/15 0} e6 {-0.03/17 0} 10. Qa4
{0.24/15 0 (Ne2)} Qd7 {-0.24/15 0} 11. Nh3 {0.36/15 0 (Qc2)} Bd6 {-0.16/15 0 
(a6)} 12. Bxd6 {0.33/15 0 (Bd3)} Qxd6 {-0.17/15 0} 13. O-O {0.18/16 0 (Nf2)}
O-O {-0.37/16 0} 14. Nf2 {0.22/15 0} a6 {-0.20/17 0} 15. Bd3 {0.21/14 0 (Bxc6)}
b5 {-0.41/17 0} 16. Qb3 {0.16/13 0 (Qc2)} b4 {-0.81/17 0 (e5)} 17. Rac1 {
0.27/11 0 (Ng4)} h5 {-0.98/14 0 (Rfc8)} 18. Rfe1 {0.37/12 0} bxc3 {-0.92/14 0 
(Rfb8)} 19. bxc3 {0.27/12 0} Rfc8 {-1.00/14 0} 20. Rb1 {0.16/11 0 (Bf1)} Na5 {
-1.18/17 0} 21. Qa4 {0.04/13 0 (Qc2)} Nc4 {-1.24/15 0 (Qc7)} 22. Rb7 {0.02/14
0 (Qd1)} a5 {-1.40/17 1 (Qa3)} 23. Nh3 {0.08/13 0} Qd8 {-1.57/15 0 (Qa3)} 24.
Qc2 {-0.03/13 0 (Rc1)} Nd6 {-1.59/15 0 (Rc7)} 25. Rb3 {0.00/12 0 (Rbb1)} a4 {
-1.58/15 0 (Rc6)} 26. Rb4 {0.21/12 0} Qc7 {-1.64/16 0 (Nd7)} 27. Rc1 {0.10/13 0
} a3 {-1.38/16 0 (Nc4)} 28. Qb3 {0.00/14 0 (Nf2)} h4 {-1.78/16 1} 29. Rc2 {
0.00/15 0 (Qd1)} Nc4 {-2.09/15 0} 30. Rb7 {-0.14/13 0 (Qb1)} Qd8 {-2.29/14 0}
31. Rb4 {-0.32/14 0 (Qb1)} Nb2 {-2.35/14 0 (Rab8)} 32. Bb5 {-0.29/13 0 (Bf1)}
Ne8 {-3.00/12 0 (Qc7)} 33. Bf1 {-0.66/13 0 (Rc1)} Nd6 {-3.17/14 0} 34. Rc1 {
-0.54/14 0} Nf5 {-3.36/14 0 (Ndc4)} 35. Bb5 {-0.61/14 0 (Be2)} Qd6 {-3.29/15 0}
36. f4 {-0.57/12 0 (Re1)} g6 {-3.51/12 0 (Rab8)} 37. Kh1 {-0.58/12 0 (Rf1)}
Rcb8 {-3.73/12 0 (Ne3)} 38. Rf1 {-0.66/13 0 (Kg1)} Rb6 {-4.11/16 0 (Nc4)} 39.
Kg1 {-0.59/10 0 (Re1)} Nc4 {-4.70/14 0 (Ne3)} 40. Bxc4 {-0.83/13 0} dxc4 {
-5.42/14 0} 41. Qxc4 {-2.28/14 0} Ne3 {-6.87/15 0} 42. Qc5 {-2.97/15 0} Qxc5 {
-6.76/16 0} 43. dxc5 {-3.11/16 0} Rxb4 {-6.90/14 0} 44. cxb4 {-3.12/16 0} Nxf1
{-7.00/18 0} 45. Kxf1 {-3.20/16 0} Rb8 {-7.23/15 0} 46. Ke2 {-3.28/16 0} Rxb4 {
-7.06/13 0} 47. Kd3 {-3.33/16 0} Kf8 {-7.14/16 0 (Rb5)} 48. Ng5 {-3.59/11 0 
(Kc3)} Ke7 {-7.18/15 0} 49. c6 {-4.17/11 0} Rb6 {-7.23/13 0 (Rxf4)} 50. c7 {
-3.75/12 0 (Nf3)} Rc6 {-7.53/14 0} 51. Nf3 {-3.66/14 0} h3 {-7.53/15 0 (Rxc7)}
52. gxh3 {-3.53/13 0} Rxc7 {-7.01/13 0} 53. Ne1 {-3.68/13 0 (Ne5)} Ra7 {
-7.48/15 0 (Rb7)} 54. Ke3 {-3.79/12 0 (Nc2)} Ra4 {-7.69/15 0 (Rb7)} 55. Nd3 {
-4.29/13 0 (Nc2)} Rc4 {-7.76/10 0} 56. Kd2 {-4.31/13 0 (h4)} f6 {-7.89/12 0 
(Kf6)} 57. h4 {-4.48/14 0} Kf7 {-7.91/11 0 (Kd6)} 58. Kd1 {-4.47/15 0 (Ne5+)}
Kg7 {-7.84/11 0 (Kf8)} 59. h5 {-4.78/12 0 (Kd2)} gxh5 {-7.90/10 0} 60. Kd2 {
-4.76/13 0 (Ne1)} Kf7 {-8.04/12 0 (Kg6)} 61. f5 {-5.11/13 0} exf5 {-8.41/12 0}
62. h3 {-5.66/14 0 (Ne1)} Kg6 {-8.61/11 0 (Ke7)} 63. Ne1 {-4.48/7 0} f4 {
-8.42/12 0 (Rd4+)} 64. Kd3 {-4.62/8 0 (Nc2)} Rc7 {-8.32/11 0 (Rb4)} 65. Nf3 {
-5.32/7 0 (Ke4)} Re7 {-8.59/12 0} 66. Nh4+ {-5.01/7 0} Kg5 {-8.96/13 0} 67.
Nf3+ {-5.52/7 0} Kh6 {-9.07/12 0} 68. Nd2 {-5.81/8 0 (Kc4)} Re3+ {-9.08/11 0}
69. Kd4 {-6.26/8 0} Rxh3 {-9.37/11 0} 70. Ke4 {-6.66/9 0 (Ne4)} Kg5 {-9.69/11 0
} 71. Kd4 {-7.14/9 0 (Nf1)} Kf5 {-9.69/12 0 (Re3)} 72. Nc4 {-6.26/7 0 (Kc4)}
Kg4 {-10.30/12 0 (h4)} 73. Nd6 {-7.21/8 0 (Ke4)} Rh2 {-10.70/11 0} 74. Ne4 {
-7.43/8 0 (Ne8)} f5 {-11.64/11 0 (Kf5)} 75. Nf6+ {-7.11/5 0 (Kc3)} Kg5 {
-11.76/12 0} 76. Nh7+ {-9.34/8 0} Kh6 {-13.09/11 0} 77. Nf6 {-9.91/9 0} Rxa2 {
-13.46/11 0} 78. Kc3 {-11.13/9 0 (Nd5)} Rh2 {-15.99/14 0 (f3)} 79. Kd4 {
-12.50/7 0 (Nd5)} a2 {-15.75/1 0} 80. Ke5 {-13.88/7 0 (Ng8+)} a1=B+ {-56.99/1
0 (a1Q+)} 81. Kxf4 {-7.04/6 0 (Kxf5)} Bxf6 {-59.87/1 0} 82. Kxf5 {-7.14/6 0}
Bc3 {-59.27/1 0 (Rf2+)} 83. Ke4 {-8.45/8 0} h4 {-59.69/1 0} 84. Kd3 {-9.07/9 0
(Kd5)} Bd2 {-58.48/1 0 (Rd2+)} 85. Ke4 {-21.58/8 0 (Kc4)} h3 {-59.69/1 0} 86.
Ke5 {-23.09/8 0 (Kd5)} Kg5 {-58.59/1 0 (Re2+)} 87. Kd6 {-25.08/9 0 (Kd4)} Kf4 {
-57.47/1 0 (Re2)} 88. Kd7 {-24.52/8 0 (Kc5)} Ke5 {-56.33/1 0 (Re2)} 89. Kc7 {
-25.01/9 0 (Kd8)} Bc1 {-55.20/1 0 (Rg2)} 90. Kd7 {-24.25/6 0} Kf4 {-55.56/1 0 
(Rc2)} 91. Kd6 {-24.92/8 0 (Kd8)} Bd2 {-56.78/1 0 (Rd2+)} 92. Kd5 {-25.08/9 0 
(Kd7)} Re2 {-9.27/1 0 (Rg2)} 93. Kc4 {-25.08/7 0} h2 {-59.77/1 0} 94. Kd3 {
-25.29/9 0} Re3+ {-67.16/1 0 (Rg2)} 95. Kd4 {-25.29/7 0 (Kxd2)} h1=Q {-70.99/1
0} 96. Kc5 {-25.29/6 0 (Kc4)} Re4 {-70.98/1 0 (Re2)} 97. Kd6 {-25.38/7 0} Re5 {
-71.07/1 0 (Re2)} 98. Kc7 {-25.41/3 0 (Kd7)} Bc1 {-66.84/1 0 (Re2)} 99. Kd6 {
-#4/6 0 (Kd8)} Bd2 {-70.32/1 0 (Qd5+)} 100. Kc7 {-#5/7 0} Qe4 {-66.84/1 0 (Re2)
} 101. Kb6 {-#4/4 0} Bc1 {-62.49/1 0 (Re6+)} 102. Kc7 {-#5/4 0} Bb2 {-61.15/1
0 (Re7+)} 103. Kb6 {-#4/4 0} Ba1 {-59.65/1 0 (Re6+)} 104. Kc7 {-25.38/4 0} Bb2
{-61.15/1 0 (Re7+)} 105. Kd6 {-#4/5 0} Qc6+ {-58.86/1 0 (Re6+)} 106. Kxc6 {
-11.62/5 0} Ba1 {-58.26/1 0 (Bd4)} 107. Kd6 {-11.57/7 0} Bb2 {-57.10/1 0 (Bc3)}
108. Kc6 {-11.66/7 0 (Kd7)} Ba1 {-58.26/1 0 (Bd4)} 109. Kd6 {-11.74/8 0 (Kb6)}
Re1 {-57.10/1 0 (Ke4)} 110. Kd5 {-11.76/8 0} Rh1 {-5.97/1 0 (Rd1+)} 111. Ke6 {
-11.76/6 0 (Kc6)} Rh5 {-5.80/1 0 (Ke4)} 112. Kd6 {-11.80/8 0 (Kd7)} Ra5 {
-57.10/1 0 (Bd4)} 113. Kc6 {-11.80/8 0} Ke5 {-6.06/1 0 (Bd4)} 114. Kb6 {
-11.80/6 0 (Kb7)} Ra3 {-5.58/1 0 (Bc3)} 115. Kc5 {-11.65/5 0 (Kb5)} Ra2 {
-6.03/1 0 (Bd4+)} 116. Kb4 {-11.76/7 0 (Kc4)} Rh2 {-5.50/1 0 (Bd4)} 117. Kc4 {
-11.80/7 0} Ke4 {-5.35/1 0} 118. Kc5 {-11.80/7 0 (Kb3)} Ke5 {-5.67/1 0 (Be5)}
119. Kc4 {-11.89/8 0 (Kc6)} Ra2 {-4.87/1 0 (Bb2)} 120. Kb3 {-11.91/9 0} Ra6 {
-4.10/1 0 (Rd2)} 121. Kc4 {-11.91/7 0} Rg6 {-4.25/1 0 (Bd4)} 122. Kc5 {-11.95/
8 0} Rd6 {-5.41/1 0 (Bd4+)} 123. Kc4 {-11.95/8 0} Rg6 {-4.25/1 0 (Bd4)} 124.
Kb5 {-11.95/8 0} Re6 {-4.53/1 0 (Kd5)} 125. Kb4 {-11.93/7 0} Rh6 {-4.31/1 0 
(Bd4)} 126. Kb5 {-11.99/10 0} Re6 {-4.24/1 0 (Kd5)} 127. Kb4 {-12.13/9 0 (Kc4)}
Rh6 {-4.31/1 0 (Bd4)} 128. Kb5 {-11.99/6 0} Rh4 {-4.19/1 0 (Kd5)} 129. Kc6 {
-11.89/7 0} Rh3 {-4.04/1 0 (Bd4)} 130. Kc5 {-11.89/8 0} Rh4 {-3.80/1 0 (Bd4+)}
131. Kc6 {-11.99/9 0 (Kb6)} Rh3 {-4.04/1 0 (Bd4)} 132. Kc7 {-11.99/9 0 (Kb5)}
Rh2 {-3.32/1 0 (Bd4)} 133. Kb6 {-12.07/9 0} Rc2 {-3.00/1 0 (Kd5)} 134. Kb5 {
-12.07/7 0} Kd4 {-2.93/1 0 (Kd5)} 135. Kb4 {-12.07/6 0} Rf2 {-3.23/1 0 (Bc3+)}
136. Kb5 {-12.37/9 0 (Kb3)} Rd2 {-2.94/1 0 (Kd5)} 137. Kc6 {-11.79/7 0} Ke5 {
-2.78/1 0 (Kc4)} 138. Kc5 {-12.07/7 0} Rd6 {-2.82/1 0 (Bd4+)} 139. Kb4 {
-12.13/6 0 (Kb5)} Rd8 {-2.27/1 0 (Rb6+)} 140. Kc5 {-12.07/8 0 (Kb3)} Rd1 {
-2.53/1 0 (Bd4+)} 141. Kb5 {-12.05/8 0} Rd8 {-2.13/1 0 (Kd5)} 142. Kc6 {
-12.07/9 0} Re8 {-2.08/1 0 (Rd6+)} 143. Kc7 {-12.07/10 0 (Kd7)} Kd5 {-1.83/1 0
(Bd4)} 144. Kd7 {-12.07/6 0} Re4 {-1.53/1 0 (Rh8)} 145. Kc7 {-11.99/6 0} Rd4 {
-1.98/1 0 (Be5+)} 146. Kd7 {-12.07/8 0 (Kb6)} Rh4 {-1.26/1 0} 147. Kc7 {
-#26/9 0} Rg4 {-1.51/1 0 (Bd4)} 148. Kb6 {-12.13/7 0} Rd4 {-1.10/1 0 (Bd4+)}
149. Kb5 {-12.37/9 0} Rh4 {-0.99/1 0} 150. Kb6 {-12.37/7 0} Rd4 {-0.80/1 0 
(Rh2)} 151. Kb5 {-12.37/9 0 (Ka5)} Rh4 {-0.99/1 0 (Rd2)} 152. Kb6 {-12.37/7 0 
(Ka5)} Re4 {-0.75/1 0 (Rh2)} 153. Kc7 {-11.77/7 0} Rd4 {-0.47/1 0 (Bd4)} 154.
Kd7 {-9.01/4 0 (Kb6)} Bb2 {-0.15/1 0 (Rg4)} 155. Ke7 {0.00/12 0} Ba1 {0.00/245
0 (Rf4)} 156. Kf7 {0.00/18 0 Draw accepted} 1/2-1/2

**Comment by dav1312** [comment]
It was a depth 1 move `a1=B+ {-56.99/1 0 (a1Q+)}` and its still a forced checkmate in 9 instead of 6 moves
What was the time control exactly? 6 seconds without increments?

**Comment by CavanLeoJacobs** [comment]
no increments just 6 seconds for both sides 
But I don't think time the problem even if it does not see checkmate it has no reason to promote a Bishop with check

**Comment by Sopel97** [comment]
The engine played with no time and was forced to give out a move immediately. Stockfish is not made to play anything even remotely correct in such situations. Your setup is the problem here, give engines some time.

**Comment by CavanLeoJacobs** [comment]
Ok I see your mean 
thanks for showing me

**Comment by vondele** [comment]
closing as resolved, just a depth 1 move as a result of having no time.
