### ISSUE TITLE
Invite Stockfish to participate in a chess engine tournament

### ISSUE THREAD

**Issue by PabloDaniel0** [official-stockfish/Stockfish#3956]
Hi, I am organizing a chess engine tournament, called OSCET, the aim of the tournament is to have the strongest open source engines compete in the tournament, to highlight its importance, I would like to invite Stockfish to participate in the tournament, details are here:
https://sites.google.com/view/oscet/take-part
**Registration form:**
https://forms.gle/xE51X3S7bkuCQihB6
**Discord:**
https://discord.com/invite/e8H5QfdttV

**Comment by movepicker** [comment]
you can make tournament between all chess engine via Lichess bot :

https://lichess.org/@/thibault/blog/how-to-create-a-lichess-bot/FuKyvDuB

**Comment by vondele** [comment]
you're of course free to run SF in tournaments, but we usually don't register for such events (quite a few people organize this for their entertainment).
