### ISSUE TITLE
Information request: testing evaluation.

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#3961]
I have a question:
let's say I want to modify stockfish evaluation function (the static one not NNUE),
What is the best way to test it?
Obviously I would test it with a tournament of let's say 10000 matches between the unmodified version and my modified version, but I wonder what is the best way to test it... PLIES=1 to 10? or there is something else I have to disable other than NNUE?

**Comment by Disservin** [comment]
Similar to fishtest, you chose a short time control and long time control and let it play. It might be that in short time control your evaluation tweaks are better but lose elo in long time control. Doing 10000 of long time control matches on your own pc is probably going to take quite a while ...

**Comment by vondele** [comment]
as the previous comment, best is to adopt a similar protocol as on fishtest, our standard testing starting with STC (10+0.1s) is pretty reasonable in most cases, with exceptions.
