### ISSUE TITLE
Perhaps this is nothing... but stockfish lost against berserk...

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#3962]
Perhaps this is nothing and I am far from being even a bad chess player (probably my ELO would be negative).
But as a computer enthusiast I was checking out some engines.
So I took the latest version of Stokfish and the latest of berserk.
Usually I don't even understand what they really do... but in this case I see an obvious error.
Perhaps this can interest you more than me.

I set the engines at maximum strenght and using 3 cores of my notebook.
Berserk won with white and that can even be ok for a single match,

Perhaps this game will be useful to you to understand what happened.
https://lichess.org/rImqMlia

**Comment by movepicker** [comment]
you can download Leela Chess Zero , it is a Artificial intelligence chess and very strong like Google Alpha Zero 

https://lczero.org/play/download/

**Comment by vondele** [comment]
single losses happen, the progress we make is measured on average over a large number of games
