### ISSUE TITLE
Different behaviour if the same executable runs on windows WSL or a real ubuntu machine.

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#3965]
As a test, I compiled stockfish in ubuntu 20.04 in windows WSL.

The result of bench 16 12 (I have 4 cores with HT.. so 8 virtual cpu, but 12 gives the best result)
I get: 
Total time (ms) : 39443
Nodes searched  : 333450988
Nodes/second    : 8453996

If I do the same with the same version compiled using MSYS2/MINGW:
Total time (ms) : 6199
Nodes searched  : 40027741
Nodes/second    : 6457128

I don't quite understand 2 things:
1) why the bench takes less time with the same parameter in the second case?
2) why the bench is way slower?

Note:
My WSL is type 1. Not the virtualized type 2.

**Comment by Zibri** [comment]
[StockfishWSL.zip](https://github.com/official-stockfish/Stockfish/files/8311289/StockfishWSL.zip)
I created a fake "stockfishWSL.exe" program that runs stockfish installed in the WSL linux environment (if it's in the path... so if it's installed in /usr/local/bin/   it works as is.)
In this way, stockfishWSL.exe can be placed in the engines directory of pychess or cutechess under windows and it will execute the WSL version of stockfish, which is way faster for some reason.

**Comment by Zibri** [comment]
On another PC:

Stockfish compiled in MSYS2 as: 
make -j profile-build ARCH=x86-64-bmi2 COMP=mingw
===========================
Total time (ms) : 5587
Nodes searched  : 40698776
Nodes/second    : 7284549

Stockfish compiled on WSL Ubuntu 20.04 as:
make -j profile-build ARCH=x86-64-bmi2 COMP=gcc COMPCXX=g++-9
===========================
Total time (ms) : 37860
Nodes searched  : 330620249
Nodes/second    : 8732705

I also wonder why the 2 versions search a different number of nodes even if the bench command is always the same:
bench 16 12

**Comment by Sopel97** [comment]
Could you specify the compiler versions in both setups, and runs without a console (forward to file)?

**Comment by Sopel97** [comment]
the effects might be wildly upredictable and OS dependent if you oversubscribe threads

**Comment by movepicker** [comment]
you can download Leela Chess Zero , it is a Artificial intelligence chess and very strong like Google Alpha Zero

https://lczero.org/play/download/

**Comment by vondele** [comment]
@movepicker please refrain from posting to several issues, it doesn't add any value.

**Comment by Zibri** [comment]
> the effects might be wildly upredictable and OS dependent if you oversubscribe threads. Also just the nature of multithreaded search not being deterministic can produce such differences.

True, but if I don't it is significantlty (20%-30%) slower on both OS...

**Comment by movepicker** [comment]
> @movepicker please refrain from posting to several issues, it doesn't add any value.

Ok I Thought This is not an important issue

**Comment by vondele** [comment]
the issue has been answered, the precise node count on bench is not reproducible when threading. 

One the speed difference, I don't have a good answer, but we have seen before that timings on windows and linux are not the same. This could be due to differences in the toolchain used to compile or the OS, not something we can easily resolve.
