### ISSUE TITLE
Stockfish 190322 not able to find mate in 1 ????!!!!

### ISSUE THREAD

**Issue by mkd** [official-stockfish/Stockfish#3969]
I was debugging my own engine with a really simple KQK mate in 1: 

4k3/2Q5/5K2/8/8/8/8/8 w - - 0 1

Obviously, the mate in 1 is delivered with Qe7 (c7e7). But surprisingly, Stockfish cannot find it at any depth. NNUE misbehavior?

Here's the output of the latest Stockfish (190322), using go depth 1, depth 2, depth 3... depth 30:
go depth 1
info string NNUE evaluation using nn-6877cd24400e.nnue enabled
info depth 1 seldepth 1 multipv 1 score mate 1 nodes 29 nps 14500 tbhits 0 time 2 pv c7c8
bestmove c7c8

go depth 3
info string NNUE evaluation using nn-6877cd24400e.nnue enabled
info depth 1 seldepth 1 multipv 1 score mate 1 nodes 29 nps 29000 tbhits 0 time 1 pv c7c8
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 58 nps 58000 tbhits 0 time 1 pv c7c8
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 87 nps 87000 tbhits 0 time 1 pv c7c8
bestmove c7c8

go depth 30
info depth 30 seldepth 2 multipv 1 score mate 1 nodes 870 nps 290000 tbhits 0 time 3 pv c7c8
bestmove c7c8

**Comment by mkd** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by mkd** [comment]
I am really sorry for this novice mistake. Should have looked much better at the output. My apologies 🙈

**Comment by vondele** [comment]
np
