### ISSUE TITLE
How long would it take to understand all the Stockfish code?

### ISSUE THREAD

**Issue by curiosport** [official-stockfish/Stockfish#3976]
As far as I see Stockfish has 20,000 lines of code, based on my experience it is not much work to read that amount, but to understand it?  how long would you consider it would take an average C++ programmer?

**Comment by vdbergh** [comment]
Not an issue.

**Comment by vondele** [comment]
we have a discord chat where these things can be discussed. There will not be a quantitative answer, as it depends on 'average' and 'understand', which can mean different things to different people.
