### ISSUE TITLE
Multi Threads bestmove Problem

### ISSUE THREAD

**Issue by movepicker** [official-stockfish/Stockfish#3987]
Hello , when I increase thread the result best move changed

when number of thread was little the result best move is false

for example :

`setoption name Threads value 8`

`go depth 10`

**bestmove a2a4**

`setoption name Threads value 32`

`go depth 10`

**bestmove d2d4**

it is not important number of computer thread!!

but it is important `setoption name Threads value`

How can solve this problem ?

**Comment by vondele** [comment]
If more threads are used for the search a better result is obtained, and so the bestmove can change, this is expected behavior. Adding more threads doesn't reach the same answer faster, it finds a better move in (roughly) the same time.

**Comment by movepicker** [comment]
How can we have a absolute bestmove result ? (without change)

do we must set threads number to max **∞**  ?!  but this is impossible !!! 

`setoption name Threads value 512`

is there any other way to have absolute result ?

I remember in stockfish old version we had absolute bestmove and adding threads only make faster and not change result

**Comment by dav1312** [comment]
Chess is not a solved game, you can't get the "absolute" best move

**Comment by movepicker** [comment]
i know but i want to  have a absolute bestmove result for low depth 

`setoption name Threads value 512`

`go depth 10`

but i dont have 512 core system for do this and it is impossible !!!

i remember in stockfish old version (stockfish 5) we had absolute bestmove result  perhaps more time ....

**Comment by vondele** [comment]
no, there is no way to get the absolute bestmove for a given depth (like a no-pruning minimax result).
