### ISSUE TITLE
Stockfish Maximun elo configuration.

### ISSUE THREAD

**Issue by StockAbo** [official-stockfish/Stockfish#3988]
Hi,
I know that stockfish has about 3600 elo points but the maximum elo configuration I can put with arena is 2850 elo points. Someone can help me to put it with more elo? It is possible? Thanks!

**Comment by Sopel97** [comment]
This setting is an optional limit. Just don't use it.

**Comment by StockAbo** [comment]
Thank you, I will do it and tell you.

**Comment by StockAbo** [comment]
> This setting is an optional limit. Just don't use it. UCI_LimitStrength should be 0.

Sorry but I don´t know how to do it. Could you be more specific? Do you recommend any gui? 
Thank you

**Comment by dav1312** [comment]
To get the maximum amount of elo, ignore that setting
e.g in Arena
![image](https://user-images.githubusercontent.com/63931154/163991235-59b8a684-a4ca-4f69-84c3-e0fdccea208e.png)

**Comment by StockAbo** [comment]
> To get the maximum amount of elo, ignore that setting
> e.g in Arena
> ![image](https://user-images.githubusercontent.com/63931154/163991235-59b8a684-a4ca-4f69-84c3-e0fdccea208e.png)
> 

Hi, 
If you put that option, elo is 2850 points, is the same that if you click down and mark 2850 elo. Stockfish has about 3600 elo points. What I want to do is put elo in 3000 points, 3100 points... But that option doesn't exist. 
Thanks anyway.

**Comment by StockAbo** [comment]
I don't know if the problem is cause of the GUI or if the engine is limited by programmers to 2850 elo points. Can anyone help me? Maybe using another GUI? I use Linux, maybe it is interesting.

Thnx.

**Comment by vondele** [comment]
What people are saying is that even if you only see 2850 in that box, this doesn't influence playing strength, if you don't enable the option to actually limit the playing strength. By default, SF will play at full strength (which is way stronger than this 2850).

For example, in the xboard GUI:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/4202567/164011844-357c8d4b-b2d5-4447-8d4b-21049bd3c978.png">
The tick box UCI_LimitStrength is not ticked, so the value 1350 doesn't matter.

**Comment by StockAbo** [comment]
> What people are saying is that even if you only see 2850 in that box, this doesn't influence playing strength, if you don't enable the option to actually limit the playing strength. By default, SF will play at full strength (which is way stronger than this 2850).
> 
> For example, in the xboard GUI:
> <img width="351" alt="image" src="https://user-images.githubusercontent.com/4202567/164011844-357c8d4b-b2d5-4447-8d4b-21049bd3c978.png">
> The tick box UCI_LimitStrength is not ticked, so the value 1350 doesn't matter.

Sure not man. If I put 2850 against that full strength you say, they draw. Imposible if one of them has about 3600 elo points.
Maybe I am doing something wrong? 
Another question, can I limit strength to, for example, 3100? Do you recommend using another GUI?

Thanks.

**Comment by StockAbo** [comment]
Sure I must be doing something wrong. Do you have any manual or link for a right stockfish configuration?
Do you recommend me some GUI?

Thanks you all.

**Comment by Sopel97** [comment]
Just don't touch anything else than threads and hash. Leave everything else at defaults.

**Comment by StockAbo** [comment]
> Just don't touch anything else than threads and hash. Leave everything else at defaults.

Thank you man but I have always done that and they draw. That's why I have this doubt. Maybe I should change threads and hash?
