### ISSUE TITLE
compile stockfish15 via visual studio

### ISSUE THREAD

**Issue by movepicker** [official-stockfish/Stockfish#3991]
Hello , i imported stockfish 15 project in visual studio 2019 , but could not compile it because too many error 

how can compile this project with visual studio ?

please help , thank you

**Comment by dav1312** [comment]
https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows#can-i-use-microsoft-visual-studio-to-build-stockfish

**Comment by Sopel97** [comment]
we no longer officially support MSVC so you're on your own and we cannot guarantee that the compiled binary will produce correct results

**Comment by MichaelB7** [comment]
Install Mysys2, google it , it's free, easy to install,  the learning curve is pretty quick.  If you have any questions post here in ssues and I or someone will help. Start a new thread so the title is appropriate for the topic.  I don't mind helping - but you will earn the most satisfaction figuring out on your own it will also stick better.

**Comment by MichaelB7** [comment]
Also you can now close this issue since if you do have any further questions, you should start a new thread.

**Comment by mstembera** [comment]
If you post what your actual errors are there may be suggestions on how to fix them.  I am able to compile using MSVC.

**Comment by mstembera** [comment]
BTW I don't use MSVC because I want its binaries but because I find it much easier to develop and especially debug in its environment.

**Comment by movepicker** [comment]
in other version of stockfish , such as stockfish 11 & stockfish 12  it was easy compile project , just import and build  and no need add setting or do work  .... Now I have visual studio 2019  , do it necessary to install visual studio 2022 for compile  stockfish 15 easily ? 

I want to focus only stockfish code **not spend many times just for  compile  project!!!**
