### ISSUE TITLE
EXE file too small

### ISSUE THREAD

**Issue by perfectN00b** [official-stockfish/Stockfish#3996]
I don't know if I'm in the right place here.... I am a beginner and I am experimenting with Stockfish in Visual Studio 2022. When I compile it, the EXE is very small, compared to the official release (46 MB). What am I doing wrong?

**Comment by vondele** [comment]
it is recommended to use a toolchain based on gcc or clang, also on windows. https://github.com/glinscott/fishtest/wiki/Building-stockfish-on-Windows 

I assume the NNUE net is not embedded in the binary in your case.

**Comment by perfectN00b** [comment]
Thank you for the quick reply. That will be it. I'll have to read up on it. Can I get back to you here if I have any more questions?

**Comment by vondele** [comment]
if things are not really issues, best is to join the discussion on discord where there is a help channel of a sf-dev channel https://discord.gg/KnMNfDtk
