### ISSUE TITLE
Permanent brain problem

### ISSUE THREAD

**Issue by movepicker** [official-stockfish/Stockfish#4001]
Hi , I Test Ponder Mode in Fix Depth 

**Test 1**

`go ponder depth 10 `
after 3 seconds
`ponderhit `
this result was :
`bestmove c2c4 ponder a7a6`

**Test 2**
`go ponder depth 10 `
after 300 seconds
`ponderhit `
this result was :
`bestmove c2c4 ponder a7a6`

after compare this 2 test ,  find that stockfish not use time for search new nodes in fix depth 
this is a big problem because pc show **CPU** are using by **STOCKFISH** program  but not do anything 
 what doing exactly in this time ?

**Comment by vondele** [comment]
waiting on the ponderhit command. Simply don't limit the ponder with depth. Just write
`go ponder`

**Comment by Sopel97** [comment]
That's expected, because you're doing two different things.

**Comment by vondele** [comment]
so, not an issue
