### ISSUE TITLE
How can we change default nnue and books of stockfish for our compilr

### ISSUE THREAD

**Issue by HeroRebor** [official-stockfish/Stockfish#4002]
I recently compiled a stockfish and I want to change the default nnue amd add more books
Is there any way to do so ?
And does anyone know how to create your own nnue

**Comment by vdbergh** [comment]
Not an issue.

**Comment by vondele** [comment]
To train own NNUE nets have a look at the docs https://github.com/glinscott/nnue-pytorch/wiki/Basic-training-procedure
This is quite an effort, count on a few days at least if you're already experienced with these tools.
Otherwise, I don't think this is SF issue described here.
