### ISSUE TITLE
In one position Stockfish stops showing analysis

### ISSUE THREAD

**Issue by malaschitz** [official-stockfish/Stockfish#4014]
In one position Stockfish stops showing analysis

For weeks, the program I use to generate library openings has been working for me. In one specific position it stopped working. This is the most recently published program Stockfish 15. Tested on both windows and mac os.

Scenario:
Run stockfish and execute the commands:

```
setoption name MultiPV value 12

position fen r2qkbnr/pppb1p2/8/3PB2p/8/2N2Q2/PPP3PP/R4RK1 b kq - 0 1 moves

go infinite
```

The program stops outputting analysis when it reaches depth 29 and node count 738,276,465

After the stop command is entered, a dump is made and it can be seen that stockfish continued to run and the number of nodes grew.

**Comment by dav1312** [comment]
Probably related issue: #3911

**Comment by malaschitz** [comment]
Thanks
