### ISSUE TITLE
Stockfish for ESP32 and other microcontrollers

### ISSUE THREAD

**Issue by vovagorodok** [official-stockfish/Stockfish#4017]
There is any possibility to use Stockfish engine for non Windows/Linux/Mac operation systems like FreeRTOS? \
Cheap hardware that I'm trying to use `ESP32-WROOM-32D DevKitc`: 2x240MHz CPU, 320KB RAM, 4MB Flash \
320KB RAM enough for such engines?  \
Software possibilities that I have here: gcc with std=c++2a and almost full STL with dynamic allocation and threads (Newlib) \
As I correctly understand engine works like separate process. Can it be used as library instead?

During compilation there are some errors like:
```
Scanning dependencies...
Dependency Graph
|-- <NimBLE-Arduino> 1.3.8
|-- <StepperDriver> 1.3.1
|-- <Stockfish>
Building in release mode
Compiling .pio/build/esp32dev/lib9bb/Stockfish/evaluate.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/benchmark.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/bitbase.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/bitboard.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/endgame.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/evaluate.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/main.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/material.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/misc.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/movegen.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/movepick.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/nnue/evaluate_nnue.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/nnue/features/half_ka_v2_hm.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/pawns.cpp.o
Compiling .pio/build/esp32dev/lib9bb/Stockfish/syzygy/tbprobe.cpp.o
lib/Stockfish/src/syzygy/tbprobe.cpp:43:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
          ^~~~~~~~~~~~
compilation terminated.
*** [.pio/build/esp32dev/lib9bb/Stockfish/syzygy/tbprobe.cpp.o] Error 1
/tmp/ccF0Jfjj.s: Assembler messages:
/tmp/ccF0Jfjj.s:10: Error: file not found: nn-d0b74ce1e5eb.nnue
*** [.pio/build/esp32dev/lib9bb/Stockfish/evaluate.cpp.o] Error 1
```
Looks that compilation is for `#ifndef _WIN32` systems (linux/mac?). Should I enable additional flags to avoid that?

Thanks!

**Comment by vondele** [comment]
it is not possible to run with 320KB RAM, a single process SF roughly needs 80MB, which includes 40MB for the neural net, and 40MB other data structures. The deep recursion we use also needs large stack frames, around 8MB.

OS dependencies should be quite minimal, but new OSes might require some work.

**Comment by vovagorodok** [comment]
Looks that neural net gets a lot resources. Can it be compiled without nnue support?

**Comment by vovagorodok** [comment]
Compilation successes for `SF11` with removed `syzygy/tbprobe`. But as You say it takes a lot of memory at the end. There is any place where I can try optimize it, some unimportant lookup tables or structures?

Or it's mission impossible for such case as Stockfish with less than 320KB RAM?

**Comment by Sopel97** [comment]
Move generation takes close to 1MB

**Comment by vondele** [comment]
> Or it's mission impossible for such case as Stockfish with less than 320KB RAM?

I'm afraid it is. There are other chess programs that are designed to be small, but obviously at less playing strength.

**Comment by vovagorodok** [comment]
Understand. I'm tried other. Look that [floyd](https://github.com/kervinck/floyd), [sayuri](https://github.com/MetalPhaeton/sayuri) and [Minic](https://github.com/tryingsomestuff/Minic) has the same issue wit memory usage, `PicChess` is to weak. Know You some interesting smaller and relatively strong C/C++ engines?

**Comment by Sopel97** [comment]
last time I was looking for one I got https://github.com/TerjeKir/weiss working on a 32MB win95 machine

**Comment by vovagorodok** [comment]
Thanks @Sopel97, I'll check possibility of `Weiss` or `Ethereal`. Currently, I'm trying to compile/fix `Minic`. Will see.

Lest close issue.

Thanks guys!
