### ISSUE TITLE
May need to "define" PieceSquareIndex and KingBuckets in nnue/features/half_ka_v2_hm.cpp

### ISSUE THREAD

**Issue by KWRegan** [official-stockfish/Stockfish#4024]
In the file nnue/features/half_ka_v2_hm.cpp, in order to work for more compilers (such as mine), you may need to insert the lines:

constexpr IndexType HalfKAv2_hm::PieceSquareIndex[COLOR_NB][PIECE_NB];
constexpr int HalfKAv2_hm::KingBuckets[64];

The reference that led me to this: [https://stackoverflow.com/questions/801 ... texpr-char](https://stackoverflow.com/questions/8016780/undefined-reference-to-static-constexpr-char)

**Comment by Sopel97** [comment]
Which compiler produces an error while compiling stockfish, and what is the error? I don't see the issue right now, especially because we require C++17 anyway.

**Comment by vondele** [comment]
since we don't know which compiler leads to this, I'll close the issue. If we have more info, please reopen
