### ISSUE TITLE
Detach the fork

### ISSUE THREAD

**Issue by kevinji** [official-stockfish/Stockfish#4030]
Since this repo is now the official Stockfish repo, the repo owners could consider [detaching this fork](https://support.github.com/request/fork) as it will make contributions correctly show up on commit authors' profiles—see [the issue described here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork).

**Comment by kevinji** [comment]
@vondele are you the right person to look at this?

**Comment by ppigazzini** [comment]
From https://github.com/official-stockfish/Stockfish/issues/2345 @snicolet seems to have more power :)

```
GitHub account
https://github.com/official-stockfish
Type: Organization, GitHub Team for Open Source
Owners: @glinscott @mcostalba @zamar @snicolet

Github repository (official-stockfish)
https://github.com/official-stockfish/Stockfish
Owners: @glinscott @mcostalba @zamar @snicolet @vondele
Team "Maintainers": @locutus2 @snicolet @vondele
Owners and Maintainers have "Admin" permission level on the repos
```

**Comment by vondele** [comment]
I have created an issue with github support to start to detach.

**Comment by kevinji** [comment]
Looks like it's been done, thanks!

**Comment by snicolet** [comment]
I'm all in favor of transferring more rights and permissions to Joost and Pascale, of course.
