### ISSUE TITLE
empty string type options should have the value "<empty>"

### ISSUE THREAD

**Issue by Dickby** [official-stockfish/Stockfish#4033]
Not that important, 
but shouldn't be the default value of the option `Debug Log File` be "\<empty\> "?

**Comment by Dickby** [comment]
Got it!
Thanks

**Comment by Dickby** [comment]
I think it should be \<empty\> .
it says in the uci protocol that empty strings should have that value.
btw. it wasn't empty on the stable release commit either.

**Comment by dav1312** [comment]
> 		* string
>			a text field that has a string as a value,
>			an empty string has the value ""

**Comment by Dickby** [comment]
@dav1312  I assume you meant "\<empty\>" ?

**Comment by vondele** [comment]
no, the above is a quote from the UCI protocol (http://wbec-ridderkerk.nl/html/UCIProtocol.html), but either way, I think the current state is fine.
