### ISSUE TITLE
change multi-threading algorithm

### ISSUE THREAD

**Issue by movepicker** [official-stockfish/Stockfish#4035]
hi 

I want to change multi-threading algorithm from **Lazy SMP** to **Young Brothers Wait Concept** 

Because in Lazy SMP by Adding more threads not faster in answer search

--------------------------

 _Adding more threads doesn't reach the same answer faster, it finds a better move in (roughly) the same time._

_Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/3987#issuecomment-1102488855_

------------------------

how can change algorithm ?

**Comment by noobpwnftw** [comment]
YBWC is even worse.

**Comment by Disservin** [comment]
dont change, the idea is not to get a faster search, the idea is to get a better move which is just better. Lazy SMP performans much better than YBWC and also scales better with more threads. Stockfish used to have YBWC but made the change quite some time ago.

**Comment by mhouppin** [comment]
https://github.com/official-stockfish/Stockfish/commit/ecc5ff6693f116f4a8ae5f5080252f29b279c0a1

Unless you find a way to get back the +45 Elo the simple switch to Lazy SMP brought at 20 threads in 2015 (which I honestly doubt), YBWC will not come back in SF's code anytime soon.

If you meant to have your own implementation of YBWC on a fork, you can check the implementation from Crafty here (which looks well documented): https://github.com/MichaelB7/Crafty/blob/5501aa243bcb5fcf170791dd240017675960d152/src/search.c#L764

**Comment by vdbergh** [comment]
@movepicker Please stop trolling the issue tracker.

**Comment by Disservin** [comment]
> >
> thanks @mhouppin its very useful code , I believe That by adding more thread it must faster search Time , in stockfish old version by YBWC it was fast search & little increase node but in newer version Lazy SMP it much increase nodes & little fast
> 

In lazy smp each thread is started a bit different and they explore different searchtrees thus you get more nodes searched, but with a bigger searchtree the chance of missing a bestmove because of pruning is reduced thus with lazy you will get a better move in roughly the same time.

**Comment by joergoster** [comment]
It would be a nice challenge to develop an engine (well, mainly the search) with _YBWC_ and to take care to always have enough work available for all threads. That means less pruning and reductions overall in SMP mode. No trivial task probably ...
