### ISSUE TITLE
Multi-Threading Overdone Depth

### ISSUE THREAD

**Issue by timo-boll** [official-stockfish/Stockfish#4079]
<img width="334" alt="Fischer" src="https://user-images.githubusercontent.com/107503345/173939838-77954d57-468f-41bf-9030-b75afcd25617.png">

Hi Every One , This Game Is From Grand Master **Robert James Fischer**

https://lichess.org/QoOqsLxX

At This Position Exist Combination (Rxf8+) But Need At Least 8 Ply To See This Combination

`go depth 8`
`info depth 8 seldepth 8 multipv 1 score cp 335 nodes 3266 nps 408250 tbhits 0 time 8 pv f1f8 b4f8 d4a4 e8d8 a4b3 f8e7`
`bestmove f1f8 ponder b4f8`

Can Amateur Chess Player To See This Move ?  Absolutely No

Well , We Imagine An Amateur Chess Player Only See 2 Ply 

`go depth 2`
`info depth 2 seldepth 2 multipv 1 score cp 549 nodes 146 nps 73000 tbhits 0 time 2 pv d4e5 a6a5`
`bestmove d4e5 ponder a6a5`

All Thing Is Ok , But .......

But We Add Multi-Threading !!!

`setoption name threads value 16`
`go depth 2`
`info depth 2 seldepth 2 multipv 1 score cp 765 nodes 705171 nps 7051710 tbhits 0 time 100 pv f1f8 b4f8`
`bestmove f1f8 ponder b4f8`

Multi-Thread Overdone Depth , We Search Only Depth 2 But gives a Deth 8 Result !!!!!

Is There No Set Range for Depth?

How Real Is Our Search With Each Thread    ?

**Comment by dubslow** [comment]
`depth` is only a iterative loop counter. it has little to do with how many plies deep the search is

**Comment by vondele** [comment]
The implementation searches until the master thread reaches depth 2, but other threads are free to search deeper during that time. That's a reasonable implementation, not a bug.
