### ISSUE TITLE
Stockfish does not see the right move

### ISSUE THREAD

**Issue by braich** [official-stockfish/Stockfish#408]
rn3k1r/p2nqpp1/b1p1p2p/3pP3/1p1P1N2/3B2Q1/PPP1NPP1/2KR3R w - - 2 15
In this position the latest Stockfish with 5-men syzygy bases does not see the right move: Ng6+

**Comment by mcostalba** [comment]
This is not an issue. Please don't open an issue if you are not a developer.

**Comment by braich** [comment]
@mcostalba 
Why not? In this postilion Stockfish analysis is wrong. By the way, this position is from this game: http://tcec.chessdom.com/archive.php?se=8&st=1a&ga=46

**Comment by mcostalba** [comment]
@braich this is for developers not for users. Issues are about specifc code, not SF behaviour in games.

Behaviour in games is very statistically based because the way SF search is strongly statistically based, in some position SF will see the move in others will not, this is _absolutely_ normal and always will be like this. What is important is that on average SF sees more times the good move than it misses it.

**Comment by braich** [comment]
@mcostalba 

I think that this is rather strange to change position evaluation from 0.0:
Analysis by Stockfish 220815 64 POPCNT:
15.Kc1-b1 c6-c5 16.Nf4-h5 Qe7-g5 17.Qg3xg5 h6xg5 18.Nh5-f6 Rh8xh1 19.Rd1xh1 Nd7xf6 20.e5xf6 Kf8-g8 21.Bd3-h7+ Kg8-f8 22.Bh7-d3 
=  (0.00)    Depth: 36/45   00:33:44  1725MN, tb=7

to 0.83:
rn3k1r/p2nqpp1/b1p1p1Np/3pP3/1p1P4/3B2Q1/PPP1NPP1/2KR3R b - - 0 1
Analysis by Stockfish 220815 64 POPCNT:
15...f7xg6 16.Ne2-f4 Kf8-g8 17.Nf4xg6 Qe7-f7 18.Ng6xh8 Kg8xh8 19.Bd3-g6 Qf7-e7 20.Rh1-h4 Nd7-f8 21.Rh4-f4 Nb8-d7 22.Rf4-f7 Qe7-g5+ 23.Qg3xg5 h6xg5 24.Bg6-h5 Nd7-b6 25.Rf7-c7 g7-g6 26.Bh5-g4 Ba6-b5 27.b2-b3 Kh8-g8 28.Kc1-d2 a7-a5 29.Rc7-e7 Nb6-c8 30.Bg4xe6+ Nf8xe6 31.Re7xe6 Kg8-f7 32.Re6-f6+ Kf7-g7 33.Rd1-a1 a5-a4 34.Ra1-h1 Nc8-e7 35.g2-g4 Ra8-a7 36.Rf6-d6 Ne7-c8 37.Rd6-d8 Nc8-e7 38.f2-f3 a4xb3 
+/-  (0.83)    Depth: 37/64   00:06:21  366MN, tb=24

in one (not the first line) move.

**Comment by braich** [comment]
@mcostalba But, again, if you do not bother, no problem.
