### ISSUE TITLE
Output word `none` if no checkers exist in a position

### ISSUE THREAD

**Issue by PedanticHacker** [official-stockfish/Stockfish#4084]
In `src/position.cpp` in line 73 we have this code:
```
<< std::setfill(' ') << std::dec << "\nCheckers: ";
```
If using the custom `d` command and the current position has no checkers, the output looks like this:
`Checkers: `

It would be better if this is:
`Checkers: none`

**Comment by PedanticHacker** [comment]
@vondele, once PR #4085 gets merged, please close this issue.

**Comment by johndoknjas** [comment]
@vondele Good point I hadn't considered that.

**Comment by Joachim26** [comment]
@johndoknjas, your reputation is already gone.

**Comment by PedanticHacker** [comment]
@vondele, what I find problematic is the fact that a professional programmer would consider to rely on a string literal to base their parsing algorithm. Personally, I wouldn't rely on a string literal as the most reliable piece of information, because a string could change and then the parsing algorithm breaks.

Since the integer `0` is equivalent to the Boolean value `false` in C++ (as is in many other programming languages as well), whereas the `space` string character in C++ is **not** `false`, I'd return the integer `0` if there are no checkers present in a chessboard position. But by having a `0` as the output value (when there are no checkers), you can convert the output to a Boolean value in your parsing algorithm and then parse based on this information.

So, if the output would either be `Checkers: 1`, `Checkers: 2`, `Checkers: 0`, or whatever, you could use Boolean logic to perform parsing in your script.

I was wrong about having `none` as the output when there are no checkers. Can you please consider of having `0` as the output? Thanks.

**Comment by Disservin** [comment]
@PedanticHacker This doesnt change the reasoning from @vondele on why this is a bad change... and afterall when you parse Stockfish output it's always gonna be a string anyway. 
It doesn't matter if you have
`const hasCheckers = stockfishCheckersOutput.trim().length > 0`
or 
`const hasCheckers = Boolean(stockfishCheckersOutput)`
(js example)

Point being you anyway need some code which converts str -> bool and the current output is not difficult to parse.

**Comment by Disservin** [comment]
Regardless of that scripts shouldn’t really rely on Stockfish’s d command as it is an internal one and not defined by uci.

**Comment by Sopel97** [comment]
The output is a list of squares. An empty list is empty. Neither `none` nor `0` is an empty list.

**Comment by PedanticHacker** [comment]
Well, my main reason to nag here after this issue report has already been closed is that `Checkers: ` (in case no checkers exist) looks very strange, almost like a bug.

It'd be a welcome change to at least tell the user somehow that no checkers were found in a chessboard position, like `Checkers: none`, `Checkers: [ ]`, `Checkers: 0`, perhaps even `No checkers`.

I'm quite certain that no one relies on the string literal `Checkers: ` to determine that no checkers exist in a given chessboard position. It seems kinda far fetched, don't you think?

If we'll get any complaint, we can always revert the commit.

**Comment by Sopel97** [comment]
how about we wait for a complaint about the current behaviour

**Comment by Sopel97** [comment]
how about we wait for a complaint about the current behaviour
