### ISSUE TITLE
What am I doing wrong when compiling Stockfish?????

### ISSUE THREAD

**Issue by Chess321** [official-stockfish/Stockfish#4093]
I have a MacBook Pro 16-inch M1 MAX, 8+2 CPU cores, 32 GPU cores, 64 GB RAM.
+ BanksiaGUI v0.54 for macOS.

I tried:
**Terminal + HomeBrew** 
brew unlink stockfish
brew install stockfish --HEAD 

---------------------------------------------

I also tried:
**Terminal + Github Stockfish Source Code**
https://github.com/official-stockfish/Stockfish

cd /Users/me/Stockfish-master/src

make clean

make -j profile-build COMP=clang ARCH=apple-silicon

./stockfish

---------------------------------------------

(brew install stockfish --HEAD = 4 Mn/s)
(make build = 5 Mn/s)
(make -j profile-build ARCH=apple-silicon = 9 Mn/s)
(make profile-build COMP=clang ARCH=apple-silicon = 9 Mn/s)
**(make -j profile-build COMP=clang ARCH=apple-silicon = 9.3 Mn/s)**

How do other people get 13.5 Mn/s on the basic M1 with only 4+4 CPU cores? 
How do other people get more than 20 Mn/s with the M1 MAX?

**Comment by Disservin** [comment]
I don’t think you have done something wrong. Are you comparing nps with the same number of threads and the same position ?

**Comment by Chess321** [comment]
Yes.
Chess start position and 10 (8) cores.

**Comment by vondele** [comment]
people probably test nps with our bench, not from the startpos. The numbers can be quite different since the bench contains endgames etc.

**Comment by Chess321** [comment]
@vondele 
Those were from the start position.
How can I do the bench?

**Comment by Chess321** [comment]
./stockfish bench 16 10 13 default depth mixed

Total time (ms) : 1207
Nodes searched  : 26201973
Nodes/second    : 21708345

**Comment by dubslow** [comment]
That's 21.7 Mnps, seems comparable to your claim of others getting 20 Mnps on the same hardware as you

**Comment by vondele** [comment]
so, issue solved
