### ISSUE TITLE
Stockfish compile (make help) doesn't support Arm64EC

### ISSUE THREAD

**Issue by Chess321** [official-stockfish/Stockfish#4099]
It's not possible to create a compile when running Windows 11 ARM with help of Parallels Desktop 17 on a MacBook Pro M1 MAX.

**Comment by vondele** [comment]
for a good bug report, please include exactly which commands you executed, and what the output of those commands were (i.e. error messages). Explain why it is not possible for you right now.

**Comment by Chess321** [comment]
I can compile Stockfish on macOS with terminal and I can use it with BanksiaGUI on macOS.

But when I try to use this Stockfish on Windows 11 ARM (Parallels Desktop) with ChessBase or ChessOK Aquarium, it shows no UCI Engine detected.
Probably because the compiled Stockfish has no: .exe

When I try to compile Stockfish with cmd.exe directly on Windows 11 ARM (Parallels Desktop), I was using: 
... src
make -j profile-build COMP=clang ARCH=apple-silicon
But make isn't available.

**Comment by vondele** [comment]
If make is not available you'll need to install the full toolchain (mingw etc) for windows on ARM.

**Comment by ppigazzini** [comment]
What about using WSL2 on Windows 11 for ARM?
https://www.thomasmaurer.ch/2019/12/how-to-install-wsl-2-on-windows-10-on-arm/

**Comment by vondele** [comment]
not an SF issue, needs the required build tools to be installed one way or another.
