### ISSUE TITLE
stockfish 15 has stopped working

### ISSUE THREAD

**Issue by wal-ly** [official-stockfish/Stockfish#4102]
here's a picture of the problem:

https://gyazo.com/59dacc00b91af8305b4f3c0f1afd73e5

i tried reinstalling it but instantly crashes on open

**Comment by vondele** [comment]
have you tried with the popcount binary? https://stockfishchess.org/files/stockfish_15_win_x64_popcnt.zip

**Comment by Sopel97** [comment]
1. where do you have the executable from
2. what is your cpu

**Comment by PedanticHacker** [comment]
@wal-ly, if your CPU is old enough, it might not support the CPU instructions for which Stockfish binaries are compiled.

**POPCNT CPU instruction**
POPCNT is available in AMD's Jaguar and Piledriver processors and newer ones, and in Intel's processors based on the Haswell microarchitecture and newer ones.

**AVX2 CPU instruction set**
And as for Stockfish binaries compiled for processors supporting the AVX2 CPU instruction set, here's a list of processors that support it, listing Intel ones and AMD ones:

**Intel**
- Haswell processors (only Core and Xeon branded), Q2 2013
- Haswell E processors, Q3 2014
- Broadwell processors, Q4 2014
- Broadwell E processors, Q3 2016
- Skylake processors, Q3 2015
- Kaby Lake processors, Q3 2016 (ULV mobile) / Q1 2017 (desktop/mobile)
- Skylake-X processors, Q2 2017
- Coffee Lake processors, Q4 2017
- Cannon Lake processors, Q2 2018
- Cascade Lake processors, Q2 2019
 Ice Lake processors, Q3 2019
- Comet Lake processors, Q3 2019
- Tiger Lake (Core, Pentium and Celeron branded) processors, Q3 2020
- Rocket Lake processors, Q1 2021
- Alder Lake (Xeon, Core, Pentium and Celeron branded) processors, Q4 2021. Supported both in Golden Cove P-cores and Gracemont microarchitecture E-cores.

**AMD**
- Excavator processor and newer, Q2 2015
- Zen processors, Q1 2017
- Zen+ processors, Q2 2018
- Zen 2 processors, Q3 2019
- Zen 3 processors, Q4 2020

Please check which processor you have and report back to us.

**Comment by wal-ly** [comment]
> @wal-ly, if your CPU is old enough, it might not support the CPU instructions for which Stockfish binaries are compiled.
> 
> ### POPCNT CPU instruction
> POPCNT is available in AMD's Jaguar and Piledriver processors and newer ones, and in Intel's processors based on the Haswell microarchitecture and newer ones.
> 
> ### AVX2 CPU instruction set
> And as for Stockfish binaries compiled for processors supporting the AVX2 CPU instruction set, take a look at the list of processors that support it.
> 
> #### Intel
> * Haswell processors (only Core and Xeon branded), Q2 2013
> * Haswell E processors, Q3 2014
> * Broadwell processors, Q4 2014
> * Broadwell E processors, Q3 2016
> * Skylake processors, Q3 2015
> * Kaby Lake processors, Q3 2016 (ULV mobile) / Q1 2017 (desktop/mobile)
> * Skylake-X processors, Q2 2017
> * Coffee Lake processors, Q4 2017
> * Cannon Lake processors, Q2 2018
> * Cascade Lake processors, Q2 2019
>   Ice Lake processors, Q3 2019
> * Comet Lake processors, Q3 2019
> * Tiger Lake (Core, Pentium and Celeron branded) processors, Q3 2020
> * Rocket Lake processors, Q1 2021
> * Alder Lake (Xeon, Core, Pentium and Celeron branded) processors, Q4 2021. Supported both in Golden Cove P-cores and Gracemont microarchitecture E-cores.
> 
> #### AMD
> * Excavator processor and newer, Q2 2015
> * Zen processors, Q1 2017
> * Zen+ processors, Q2 2018
> * Zen 2 processors, Q3 2019
> * Zen 3 processors, Q4 2020
> 
> Please check which processor you have and report back to us.

I have a Tiger Lake processor, pentium.

**Comment by PedanticHacker** [comment]
Are you trying to run 64-bit Stockfish on a 32-bit operating system?

**Comment by vondele** [comment]
I'll assume this has been resolved by now, please reopen if this is not the case.
