### ISSUE TITLE
compile stockfish with older C/C++ compiler

### ISSUE THREAD

**Issue by helge-larsson** [official-stockfish/Stockfish#4106]
why C++17 requirement? why not accept older o newer C++ or even C compiler? 
If use of icc gcc clang or other should easier finds bugs with correct input test data ie regressions and bottomneck testing.
I had an antix linux but was not able to compile standard C++.. i had compiled years ago?
I dont like or trust systemd or pulseaudio.
Is reverse recording to KISS (search kiss) keep it simple stupid, ie its easy to make an overcomplicated and too much dependency solutions than a simple and easy one. 
Same should also bee on stockfish.

**Comment by Sopel97** [comment]
C++17 is well supported by all 3 (4) major compilers. See https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features, https://en.cppreference.com/w/cpp/compiler_support/17. It is trivial to install a compiler that supports C++17 enough to compile Stockfish. If you think C++17 requirement is unnecessary then please create a pull request that reduces that requirement while not harming code readability and maintainability.

**Comment by Delphi-Coder** [comment]
Have you ever tried CFish? (stockfish C port). I think it has clear and readable code, also easier to compile.
https://github.com/syzygy1/Cfish

**Comment by vondele** [comment]
C++17 is indeed required by choice, not an issue.
