### ISSUE TITLE
Stockfish cause Chessmaster GUI to crash

### ISSUE THREAD

**Issue by Delphi-Coder** [official-stockfish/Stockfish#4111]
Stockfish + Polyglot collapsing chessmaster GUI on endgames. I didn't faced this problem on old versions (V1.8 V2 for example). All other UCI engines works fine.

PS: As a guess it probably caused by the kind of score report.
score cp mate 2
instead of
score cp 9998

**Comment by rainydew** [comment]
should be score mate 2 instead of score cp mate 2?

**Comment by Disservin** [comment]
stockfish should be reporting `score mate 2` at all times when it finds mate in 2. `score cp 9998` is still no mate score and I guess could happen in positions with a lot of material advantage? `score cp mate 2` is definitely wrong. If you can reproduce the problem on certain positions paste the fen.

**Comment by Disservin** [comment]
Could be just you using too many system resources and thus GUI crashes.

**Comment by vondele** [comment]
probably a GUI issue, not a SF issue.
