### ISSUE TITLE
Stockfish15 is not working in colab, but 14 works

### ISSUE THREAD

**Issue by woosungchu** [official-stockfish/Stockfish#4118]
Stockfish15 is not working in colab, but 14 works

```
def stockfish(board, depth):
  with chess.engine.SimpleEngine.popen_uci('/content/drive/MyDrive/coding/stockfish/stockfish_14_x64') as sf:
    result = sf.analyse(board, chess.engine.Limit(depth=depth))
    score = result['score'].white().score()
    return score
```

./stockfish_15_x64: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./stockfish_15_x64)
./stockfish_15_x64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./stockfish_15_x64)
./stockfish_15_x64: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./stockfish_15_x64)
./stockfish_15_x64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./stockfish_15_x64)

like https://github.com/official-stockfish/Stockfish/issues/4026 

**use the other version of stockfish - it will works**
https://www.dropbox.com/sh/75gzfgu7qo94pvh/NlXX-QLGu6

**Comment by dubslow** [comment]
not just like #4026 but in fact an identical duplicate, pls post this comment to that thread

**Comment by vondele** [comment]
yes, related to running a binary compiled on a new linux distro on an older one. Duplicated of the other issue.
