### ISSUE TITLE
stockfish is too aggressive

### ISSUE THREAD

**Issue by nekohacker591** [official-stockfish/Stockfish#4120]
in more detailed explaination
basically i have been noticing that stockfish as been making some mistakes such as giving peices when there is a better move
for example it will give a rook or horse when there is a better option that would take a few more moves
the problem is that stockfish rushs for the best result and will give up pieces to get it faster
basicly the fix here to balance offence and defence more 

another example is that stockfish will give up tons of pieces just to take the queen 
and it usually ends up trading making the sacrifice not worth it

in close games such as a rush to get a pawn across the board stockfish ignored the chance to take the last pawn and black got their queen and white ended up checkmating with 2 queens stockfish won but could have taken the pawn that was 2 spaces from the pawn

things to be added should be:
 better prioritizing
 offence and defence switch
 chances of winning if it is lower it will go more in defence
 at start of game stockfish should do 30% defence and 70% offence
 not make its life goal to take the queen

**Comment by vondele** [comment]
not an actionable issue.
