### ISSUE TITLE
Error with stockfish when building a unity project for WebGl

### ISSUE THREAD

**Issue by Swiftl3lad** [official-stockfish/Stockfish#4124]
I have integrated stockfish to my unity chess game and in playmode it works fine, but when I try to build for WebGl i get the folowing errors:

![image](https://user-images.githubusercontent.com/110762561/183281996-259d4f2c-ed79-4dfa-aec8-87fe76968a6a.png)

and the details of one of them:

![image](https://user-images.githubusercontent.com/110762561/183282007-ce9731b9-1b11-4199-9d09-716f1bea90a8.png)

I found something about the error "no template named 'optional' in namespace 'std'" from "bool save_eval(const std::optionalstd::string& filename);" here https://github.com/pistacheio/pistache/issues/905 but I don't know how to solve it using unity and rider as IDE and especially that the game works in playmode.

I tried building for Windows instead of WebGl and for windows the build works but I don't have the plugin there. But after I copied it from the project and added it in the Plugins folder in the build it worked and I could play the game with the bot.

The issue is that I want to make a WebGl build and its not working. I think I'm missing something but don't know what.

Someone told me that it might not be compatible with webgl since is running an exe file

Does anyone have an idea on how can I solve it?

**Comment by vondele** [comment]
you need to enable support for C++17 in the compiler.

**Comment by Swiftl3lad** [comment]
And how can I do it? I can't seem to find how can I add C++17 to the unity compiler.

**Comment by vondele** [comment]
since this is not SF related, will close this now, I hope you could solve this issue.

**Comment by ETHybridCLR** [comment]
> 
Is it solved？Can you share how to solve it？ thank you
