### ISSUE TITLE
How

### ISSUE THREAD

**Issue by FatFritz2** [official-stockfish/Stockfish#4137]
I am wondering how to make Stockfish move faster (In the UCI_Options) (Trying to make it move like 1 move per second, immediately, i mean)
Please help

**Comment by Disservin** [comment]
What do you mean ? This isn’t an issue but you can send go movetime 1000 and it will search for 1 second

**Comment by FatFritz2** [comment]
how to set it ?
I mean is how to config stockfish to make it move immediately

**Comment by Disservin** [comment]
Stockfish doesn’t move thats a gui feature. In the end stockfish can only analyze one position and give a bestmove the gui will play that move on a chess board.

**Comment by FatFritz2** [comment]
OK Fine
