### ISSUE TITLE
https://tests.stockfishchess.org/api/nn/nn-ad9b42354671.nnue is returning 500

### ISSUE THREAD

**Issue by jpulgarin** [official-stockfish/Stockfish#4140]
I'm unable to build from source because downloading the evaluation network file is currently failing:

```
[~/Downloads/Stockfish-master/src]% curl -skL https://tests.stockfishchess.org/api/nn/nn-ad9b42354671.nnue
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)%  
```

**Comment by jpulgarin** [comment]
cc: @glinscott

**Comment by peregrineshahin** [comment]
Please try to bypass the API call by changing 
`https://tests.stockfishchess.org/api/nn/nn-ad9b42354671.nnue`
to
`https://data.stockfishchess.org/nn/nn-ad9b42354671.nnue`
as Fishtest domain now is currently down
or use the DEV Domain API
`https://dfts-0.pigazzini.it/api/nn/nn-ad9b42354671.nnue`

**Comment by jpulgarin** [comment]
Thanks for the file, @peregrineshahin.
