### ISSUE TITLE
Cluster of two Hp proliant gen 8  e5 2680 v2 ( 20-40 x2 with cluster)

### ISSUE THREAD

**Issue by jordiqui** [official-stockfish/Stockfish#4141]
I am not a programmer but I have two hp proliant gen 8 servers with two xeon each server and 196 ram installed both with windows server 2022 destkop experience datacenter. I have noticed that there are no cluster versions of stockfish or if there are, they are private. Can someone help me to make stockfish use the cluster that I have mentioned?

**Comment by NightlyKing** [comment]
There is a cluster branch in this very repository. Switch to it and follow its README.md.
The cluster version of SF makes use of MPI.

**Comment by jordiqui** [comment]
Thanks. If I have installed the microsoft MPI, etc. I go to the repository to see if I can find what you tell me. Thanks again.

**Comment by vondele** [comment]
A good starting point is here https://github.com/glinscott/fishtest/wiki/Fishtest-faq#is-there-a-cluster-version-of-stockfish

There is also some more info here, that can help solve some of the practical aspects of setting up a small cluster: https://mattplayschess.com/cluster-overview/
