### ISSUE TITLE
Optimism may make the displayed evaluation less accurate

### ISSUE THREAD

**Issue by atumanian** [official-stockfish/Stockfish#4142]
I open this issue after [this thread](https://groups.google.com/g/fishcooking/c/4MUM9zMA1p8) on FishCooking.
Recently a concept of optimism was introduced into the evaluation of positions with [this commit](https://github.com/official-stockfish/Stockfish/pull/3797). In my opinion, the request was commited prematurely. The patch failed the STC test and passed only the LTC. But more importantly, it significantly changes the displayed evaluations and makes the evaluation of all positions during a search dependent on the previous score. This may be not much of an issue in the engine playing mode but seriously affects the analysis mode. In analysis, we need evaluations to represent win/draw/loss chances as accurately as possible.
Moreover, is there any theory that explains why the evaluation function should depend on the score obtained during the previous search iteration? This seems illogical to me. The evaluation function is expected to be an estimate of the expected result of the game played starting from the input position. Obviously, this expected result doesn't depend on the result of the previous iterations of the search.
I don't understand why the engine should play more risky. Playing risky isn't always a good thing.
Another concern: if the NNUE is trained using the displayed evaluations by Stockfish (currently I don't know if is does), this can distort the logic of the cooperation between the search and evaluation modules even more.
My suggestions are as follows:
- if the optimism doesn't provide a significant elo gain (around more than 3 elo), we should remove it entirely from the evaluation function.
- If it does, we should run some tests to understand why it works and maybe replace it with something simpler or more comprehensible.
- If someone really wants the engine to play more risky, but such a style doesn't make analysis better, a UCI option can be added to turn the optimism on or off; the default for analysis should be off.

P.S. Changes like this, which affect the scaling of evaluation, in my opinion, must be tested without automatic adjudication based on eval. Otherwise it's difficult to tell whether the effect is due to a change in strength or a change of the chance of incorrect adjudication. It is another methodological mistake to commit patches like this while it hasn't been tested with eval-based adjudication disabled.

**Comment by atumanian** [comment]
Here is the current code ([evaluate.cpp](https://github.com/official-stockfish/Stockfish/blob/master/src/evaluate.cpp), lines 1051-1092)
```
Value Eval::evaluate(const Position& pos, int* complexity) {

  Value v;
  Color stm = pos.side_to_move();
  Value psq = pos.psq_eg_stm();

  // Deciding between classical and NNUE eval: for high PSQ imbalance we use classical,
  // but we switch to NNUE during long shuffling or with high material on the board.
  bool useClassical = !useNNUE ||
                      ((pos.count<ALL_PIECES>() > 7)
                       && abs(psq) * 5 > (856 + pos.non_pawn_material() / 64) * (10 + pos.rule50_count()));

  if (useClassical)
      v = Evaluation<NO_TRACE>(pos).value();
  else
  {
      int nnueComplexity;
      int scale = 1064 + 106 * pos.non_pawn_material() / 5120;
      Value optimism = pos.this_thread()->optimism[stm];

      Value nnue = NNUE::evaluate(pos, true, &nnueComplexity);
      // Blend nnue complexity with (semi)classical complexity
      nnueComplexity = (104 * nnueComplexity + 131 * abs(nnue - psq)) / 256;
      if (complexity) // Return hybrid NNUE complexity to caller
          *complexity = nnueComplexity;

      optimism = optimism * (269 + nnueComplexity) / 256;
      v = (nnue * scale + optimism * (scale - 754)) / 1024;
  }

  // Damp down the evaluation linearly when shuffling
  v = v * (195 - pos.rule50_count()) / 211;

  // Guarantee evaluation does not hit the tablebase range
  v = std::clamp(v, VALUE_TB_LOSS_IN_MAX_PLY + 1, VALUE_TB_WIN_IN_MAX_PLY - 1);

  // When not using NNUE, return classical complexity to caller
  if (complexity && (!useNNUE || useClassical))
      *complexity = abs(v - psq);

  return v;
}
```
As we can see, the Eval::evaluate function uses the `optimism` variable, which is set from `Value optimism = pos.this_thread()->optimism[stm];` The latter is set before the start of a search iteration ([search.cpp](https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp), lines 353-368)

```
if (rootDepth >= 4)
          {
              Value prev = rootMoves[pvIdx].averageScore;
              delta = Value(16) + int(prev) * prev / 19178;
              alpha = std::max(prev - delta,-VALUE_INFINITE);
              beta  = std::min(prev + delta, VALUE_INFINITE);

              // Adjust trend and optimism based on root move's previousScore
              int tr = sigmoid(prev, 3, 8, 90, 125, 1);
              trend = (us == WHITE ?  make_score(tr, tr / 2)
                                   : -make_score(tr, tr / 2));

              int opt = sigmoid(prev, 8, 17, 144, 13966, 183);
              optimism[ us] = Value(opt);
              optimism[~us] = -optimism[us];
          }
```

**Comment by atumanian** [comment]
See this my analysis [in this post](https://github.com/official-stockfish/Stockfish/discussions/4150), which clearly shows the problem with the current version of Stockfish. The prediction function of the game result from eval if shifted to the positive direction of eval.

**Comment by atumanian** [comment]
See [this question](https://chess.stackexchange.com/questions/20120/engine-evaluating-changing-after-making-move-suggested-by-engine) on StackOverflow to understand why the issue is important. It was asked 4 years ago, when Stockfish had a non-zero default value of contempt. Now the contempt setting is no longer present, but the problem is the same.

**Comment by atumanian** [comment]
The recent commit seem to have made the relationship more symmetric, but, unfortunately, is [still asymmetric](https://github.com/official-stockfish/Stockfish/discussions/4150#discussioncomment-3691498). Does anybody understand the reason for this?
![stats-master-dc0c441b7c](https://user-images.githubusercontent.com/22194068/191294570-9fb55b7e-6d72-4dda-b3f0-57dce7775cda.svg)
I want to run 100000 games with the version without optimism vs itself to see if it is the optimism which really breaks the symmetry.

**Comment by peregrineshahin** [comment]
Keep in mind that black evaluation is more likely to get dampened more as black is the player who plays last

```
// Damp down the evaluation linearly when shuffling
  v = v * (195 - pos.rule50_count()) / 211;
```
As we go by plies, the eval might be assymitric because of the dampening

**Comment by atumanian** [comment]
@peregrineshahin 
Thank you for the idea. But I don't understand why the 50-move rule dampening affects more black than white. The counter is reset at a capture or a pawn move. It doesn't matter which side made this move - always 100 plies are played before a draw is stated.

**Comment by peregrineshahin** [comment]
You are correct, white can make a move to reset the counter so black eval would be the highest of its "correct" eval, I think what I should've said is that some player after the counter reset is getting a higher eval than usual, and some player after no pawn push and a capture is getting an eval lower than usual
Which still makes eval dependent on previous moves

**Comment by atumanian** [comment]
I've [tested](https://github.com/official-stockfish/Stockfish/discussions/4150#discussioncomment-3779781) the version without optimism against itself. The results show that the prediction function isn't more symmetric than in the master (with optimism). However, the prediction is still better without optimism for some reason (as the MSD shows), but it is another issue.
The function is more symmetric after the patch linked to this issue. It isn't symmetric yet, but optimism isn't the fault. I think there's no point in removing optimism or making it optional if it makes the engine stronger. We still need explanation why optimism works, but it isn't the main point of the issue. Therefore, it's time to close the present issue.

#### master dc0c441b7c
Sample size: 25035456
Mean square deviation: 0.02468199903687199
MSD (symmetric model): 0.02487485145483554

#### optimism ac8fe925d5
Sample size: 25035456
Mean square deviation: 0.02316805140737958
MSD (symmetric model): 0.02336837764508815

The graph shows the prediction function of the version with optimism removed (ac8fe925d5) along with its symmetric reflection.

![stats-optimism](https://user-images.githubusercontent.com/22194068/193431814-3a146470-79b5-446f-b889-08ca3d01975e.svg)

**Comment by atumanian** [comment]
@peregrineshahin
Sorry, I still don't understand how this depends of whether the player is white or black. The played who reset the counter may be white or black and the player who displays the eval may be white or black, either the same player as the former or his opponent.

**Comment by atumanian** [comment]
However, the MSD is significantly lower in the version without optimism, which is unusual and indicates the eval may be still more accurate without optimism. Should we reopen the issue?

**Comment by atumanian** [comment]
Here is a [direct match](https://tests.stockfishchess.org/tests/view/633e09c6fb7ccb2ea9bd76bd) between the version without optimism and the master:
```
Elo: -2.12 +-1.1 (95%) LOS: 0.0%
Total: 100000 W: 26128 L: 26738 D: 47134
```
As the [regression analysis](https://github.com/official-stockfish/Stockfish/discussions/4150#discussioncomment-3826831) shows, optimism significantly changes the shape of the prediction function. The MSD is lower in the master (both in the asymmetric and symmetric models), which means the master better predicts the game result.
![stats-optimism-100000](https://user-images.githubusercontent.com/22194068/194681444-5f08ffd3-cc6b-4fff-aa12-d74aabb579fb.svg)
Should we test it also at the LTC?

**Comment by snicolet** [comment]
closing, as the graphs are no longer correct after the recent changes in evaluate.cpp
