### ISSUE TITLE
cant build stockfish

### ISSUE THREAD

**Issue by snoopchallenge** [official-stockfish/Stockfish#4144]
/tmp/ccFjh4E8.s:6: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccFjh4E8.s:6: Error: junk at end of line, first unrecognized character is `g'
/tmp/ccFjh4E8.s:11: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccFjh4E8.s:11: Error: junk at end of line, first unrecognized character is `g'
/tmp/ccFjh4E8.s:16: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/tmp/ccFjh4E8.s:16: Error: junk at end of line, first unrecognized character is `g'
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:930: stockfish.exe] Error 1
make[1]: Leaving directory '/home/S/stockfish/src'
make: *** [Makefile:797: build] Error 2

I am using cygwin with g++ 11.3.0 and target x86-64-avx2

**Comment by vondele** [comment]
so, that's a problem with the compiler toolchain in cygwin. 
you might want to follow the instructions here https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows
probably as a workaround you can compile with `make -j ARCH=x86-64-avx2 profile-build optimize=no` but that will disable some of the compiler optimizations.
