### ISSUE TITLE
Meaning of centipawn eval and inflation over time

### ISSUE THREAD

**Issue by zz4032** [official-stockfish/Stockfish#4155]
There seems to be no clear definition of what CP eval values describe in absolute measurement. The popular understanding is that e.g. a position 100 centipawn worse is equal of being down a pawn, however the value of a pawn itself can be different depending on the position.
I tried to neutralize the position factor by 1) running Stockfish on a number of random (human) positions, 2) removing a random piece and 3) comparing the eval difference with commonly assumed piece values.

Results after evaluations on 1750*2 positions:
![Screenshot from 2022-09-04 12-46-38](https://user-images.githubusercontent.com/11909324/188309565-e8964019-8741-44f2-b142-650071c46a11.png)
What can be seen is
- difference in eval is in general higher than expected
- a visible trend of evals getting higher throughout SF development

What do you think about these results? I would prefer an engine to show correlated eval output following the approach above, also not changing with new engine versions. This could be easily achieved with scaling.

**Comment by atumanian** [comment]
Thank you! In my opinion, it's an excellent idea to calibrate displayed evaluations based on statistics.

**Comment by zz4032** [comment]
One more graph with a random piece **added** on a random square.
2480*2 positions:
![Screenshot from 2022-09-05 07-26-00](https://user-images.githubusercontent.com/11909324/188366670-8970e63b-8e19-4d6c-8a38-6f2fb60409e4.png)
I think both cases should be considered equally (averaged).

**Comment by 12345ieee** [comment]
This is a trend in most engines, which got accentuated when machine learning entered the field.

An ideal engine outputs 255/0/-255 only, corresponding to W/D/L with perfect play.
As engines progress, they can see more and more that an extra piece doesn't just contribute its material to the position, but it also improves positional aspects and makes winning easier and more likely, hence its effect compounds and the evaluation goes up.

I'm sure you could force the curve down by rescaling, but I personally see it as a good thing that the engine evaluates a no-compensation knight loss as a -7, the same way grandmasters would tell you the game is lost even though "it's not that bad" material-wise.

Ultimately, the idea of evaluations as centipawns was birthed from the human knowledge era, now that we are in the machine tuning idea it might more productive to think of evaluations as representing a likelihood of victory and think directly in terms of predicted WDL percentages.

**Comment by zz4032** [comment]
Yes, CP eval is becoming more a more a mixture of material (the actual purpose of CP eval) and score prediction being 0 or inf.

My approach described above would mean to recalibrate and let each engine show 300cp (on average) for a knight loss. Instead of CP eval climbing with each release, the winning chances would change with new versions for positions with the same CP eval. This would keep evals consistent and users will learn which eval is generally won for humans or a specific engine version.

WDL has the same issue being drawrate (strength) dependent, with WDL values changing in a similar way with each SF version as well.

**Comment by RogerThiede** [comment]
> What can be seen is a visible trend of evals getting higher throughout SF development
> What do you think about these results?

I feel this is expected behavior.  The idea that a pawn is 100cp and minor pieces around 300cp is just an *initial scaling factor* to assist NN's in my view.  If anything, a depth of 1 is the closest we'll ever reach for cp eval correlating with piece material, and the only reason it's even that at all is because we chose to implement this scaling factor for training purposes for humans to interpret the results.

> I would prefer an engine to show correlated eval output following the approach above, also not changing with new engine versions.

I'm beginning to grasp your preference, but also I feel this is the exact objective opposite goal of what machine learning _should_ achieve.  Over time, newer engine versions/neural networks should scale the eval output towards -♾️, 0, or +♾️ since all games are either forced losses, draws, or forced wins.

I interpret the single evaluation of a chess neural network (which can be extended to Stockfish classical evaluation,) as a 3D plane of your move against all possible opponent responses with valleys and mountains representing statistical likelihood of losing or winning with perfect play towards reaching a forced loss or forced win.  I do not interpret the cp evaluation as a correlation of piece material.

**Comment by zz4032** [comment]
> If I introduced a new chess game to you called Chess Material where the goal was to obtain the most amount of chess material value, wouldn't the best engine show correlated eval output to the approach you're suggesting? Such an engine objectively couldn't be the best engine for both games of Chess Material and Chess with Checkmates, and yet we're playing Chess with Checkmates.

Yes, a materialistic and weak engine would give an accurate CP value in every position but it's not about a better or worse correlation in this case.

> I do not interpret the cp evaluation as a correlation of piece material.

Well, that answers my question if that's the common opinion. I guess in this case to avoid confusion CP eval should be replaced with WDL.

**Comment by RogerThiede** [comment]
@zz4032, are you familiar with the `eval` command?  I think that probably has more of what you’re looking for; the engine's evaluation of material, imbalance, and relative value of each piece.

**Comment by vondele** [comment]
There has been some discussion on this topic in the past months, I think several things are going on at the same time.

1) The  engine is becoming stronger and stronger, evals tend to become decisive (win, draw, loss) quite quickly.
2) There is no real 'anchor' of the eval, the internal NN eval is no longer bound to our PawnValueEg, it just does what it need to do, namely order positions. Larger eval is better position, and it separates winning from drawing positions quite accurately.

The 'inflation'  can be seen in the analysis that leads to the WDL model (enabled with UCI_ShowWDL), where the last calibration showed a clear shift, i.e. 50% win rate moved to higher eval values (see or most recent update to he model https://github.com/official-stockfish/Stockfish/pull/4115).

The question is thus how to define eval in way that is meaningful (and stable) for end users. What I could imagine is to have it tied to the measured or modeled win-rate. For example 100cp implies 50% win-rate (or something similar as derived from the classical eval). To do this calibration becomes however tricky as the calibration itself depends on the evals being shown (i.e. needs some self-consistency).

In this sense, looking directly at the computed WDL numbers make maybe more sense, at least calibrating those is somewhat easier, as it is direct.

Ultimately, engines are not there to compute eval, but to compute best moves and PVs...

**Comment by RogerThiede** [comment]
This old post may be relevant for readers: https://lczero.org/blog/2020/04/wdl-head/

**Comment by Craftyawesome** [comment]
Since I haven't seen it noted in this issue, a shifting eval will hurt databases that store evals like chessdb (or lichess if they eventually update or allow recording evals with external engine). So I'm tempted to argue to standardize 50% win rate to something and keep it there. Either ~130cp like SF14 and 15, or 100cp for one last change to get a nice number.

Best moves and PVs are the most important, but it would be nice to get consistency in evals.

**Comment by RogerThiede** [comment]
> a shifting eval will hurt databases that store evals ... but it would be nice to get consistency in evals.

> Over time, newer engine versions/neural networks should scale the eval output towards -♾️, 0, or +♾️ since all games are either forced losses, draws, or forced wins.

At some point in the future, there will be only three evals, and the only way to reach that is by continually shifting evals towards those three values.

**Comment by Craftyawesome** [comment]
> > a shifting eval will hurt databases that store evals ... but it would be nice to get consistency in evals.
> 
> > Over time, newer engine versions/neural networks should scale the eval output towards -♾️, 0, or +♾️ since all games are either forced losses, draws, or forced wins.
> 
> At some point in the future, there will be only three evals, and the only way to reach that is by continually shifting evals towards those three values.

Maybe? But for the remotely near future there are tons of positions that SF won't be confident in a draw or a win. You can standardize 50% win chance to something.

**Comment by vondele** [comment]
I'll keep this open for https://github.com/official-stockfish/Stockfish/pull/4216
