### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by FatFritz2** [official-stockfish/Stockfish#4156]
I am wanting to have more Nps for stockfish.
Can I set more Threads or more Hash to get more Nodes ?

**Comment by Technologov** [comment]
Well magician Houdini has the trick to get more nodes :) Just ask him how ;)

**Comment by FatFritz2** [comment]
Uh Idk who is Houdini ?
Please help ?

**Comment by Disservin** [comment]
1. buy a better cpu
2. use more threads 

idk what effect hash has on nps just do 1&2

**Comment by dav1312** [comment]
This is the third time that you do this, **_please stop_**

![image](https://user-images.githubusercontent.com/63931154/188662168-7822d002-26cb-4391-873d-b1f6789f63ea.png)
