### ISSUE TITLE
Stockfish doesn't recognize the transposition and rates PV's differently

### ISSUE THREAD

**Issue by RogerThiede** [official-stockfish/Stockfish#4166]
Did Stockfish miss identifying the transposition between the following two PV's?  The hash is not full, and yet the lines diverge at ply 25 even though both lines should theoretically be equivalent.  As far as I can tell, multipv 2 could follow the same line as multipv 1 did and reach cp 93, yet it doesn't display like that.  Would this be a bug?

**info depth 70 seldepth** 88 multipv 1 score cp 93 wdl 169 829 2 **nodes 10328639573768 nps 46749714 hashfull 999 tbhits 84407033 time 220934816 pv** c1e3 g8f6 h2h3 **c8d7 g2g4 h7h6 d1d2 c6d4 d2d4 f8e7 e1c1 d7c6 h1g1 d8b6 d4d2 b6a5 f1c4 a7a6 c4b3 a5c7 f2f3 e8c8 d2f2 f6d7** c1b1 e7f6 a2a3 d7c5 c3e2 c8b8 d1d2 g7g5 e2c1 d8d7 g1d1 h8c8 c1d3 c6b5 d3c5 d6c5 d2d7 b5d7 c2c3 c5c4 e3b6 c7c6 b3a2 d7e8 b1a1 f6e5 a2b1 f7f6 h3h4 e5c7 b6e3 c8d8 d1d8 c7d8 f3f4 e6e5 f4g5 f6g5
**info depth 70 seldepth** 77 multipv 2 score cp 84 wdl 139 859 2 **nodes 10328639573768 nps 46749714 hashfull 999 tbhits 84407033 time 220934816 pv** h2h3 g8f6 c1e3 **c8d7 g2g4 h7h6 d1d2 c6d4 d2d4 f8e7 e1c1 d7c6 h1g1 d8b6 d4d2 b6a5 f1c4 a7a6 c4b3 a5c7 f2f3 e8c8 d2f2 f6d7** a2a3 e7f6 c3e2 d7c5 c1b1 c8b8 d1d2 g7g5 e2c1 d8d7 g1d1 h8c8 c1d3 c6b5 b3c4 c5d3 c4d3 c7c6 d3b5 c6b5 e3a7 b8a8 a7d4 f6e5 d4e5 b5e5 d2d3 a8b8 h3h4 c8c6 c2c3 d7d8 d3d4 d8e8 b1a2 e8d8 d1h1 c6c8 f2d2 d8d7 d2e3

**Comment by bftjoe** [comment]
Hash is definitely full, hashfull is 999/1000

**Comment by MaiaChess** [comment]
> info depth 70 seldepth 88 multipv 1 score cp 93 wdl 169 829 2 nodes 10328639573768 nps 46749714 hashfull 999

46 Million Node Per Second Speed !!!!

What is your CPU ?

**Comment by vondele** [comment]
not a bug, repeated searches (like here for multipv 2, that transposes) don't need to return the same result.
