### ISSUE TITLE
Reliability of SF output PV leaf

### ISSUE THREAD

**Issue by Dboingue** [official-stockfish/Stockfish#4167]
I thought I would ask the horse's mouth.  What is the current reliability of command line SF output for best PV.
Can one count on the leaf of that PV to be the position where the value attributed to leftmost node and root position score was obtained via a full evaluation of its position information (possibly contained in the hash paired with the score value)?

Sub-question.. Would using the SF evaluation web guide, with same NNue weight data. or at least without NNue, applied to the FEN of that leaf, give the same score.  or at least if one were to have many root positions very diverse, would the root scores and PV leaf web guide scores correlate (in any type of correlation test, be it ranking)?

Finally, if the interior nodes (i mean not root, not leftmost, and not leaf) are difficult to assess as reliable, would the leaf at least be ensured to have been kept until such output, and would it even be possible for SF to output that FEN (or hash) independently of the interior nodes?

Does this set of questions compute.. Choose the ones that contain the other.. if everything is full reliable at any input depth, then i guess some of those questions are moot..

**Comment by vdbergh** [comment]
Not an issue.

**Comment by Dboingue** [comment]
Where can we ask such questions then?  Oh mighty judge of what could an 
issue be?

Le 14/09/2022 à 21:23, vdbergh a écrit :

**Comment by dubslow** [comment]
stockfish discord is the place https://discord.gg/mFfRm7Wh 

on github, an "issue" is a bug or problem in the executable, not questions about chess engine theory (questions about chess engine theory are welcomed on the discord)

**Comment by Dboingue** [comment]
ok thanks.  so no documentation issues? =-O   I will copy paste over 
there.. (hope it does not get lost, in some scroll buffer:-D).

Le 14/09/2022 à 23:20, dubslow a écrit :

**Comment by vondele** [comment]
not an issue. The reliability of the PV goes down as you move down the line. That's the expected behaviour. The final score can be the evaluation of a leaf node, but this is not the case (cutoffs, TT use etc) might influence the final eval

**Comment by Dboingue** [comment]
Thank you for this summary answer, I did not expect it.  And I follow up 
with more...

Is there anyway given the command parameters to get a sense of where we 
might be quantitatively in that qualitative relationship?

is there any way to find out which case given an output.. or is there a 
debug mode that would allow such analysis, such as printing out node 
type per score attributed to PV root, for the leaf offered as output.

If the full length PV, is indeed a leaf, should I expect  the SF web 
guide evaluation parameters to be such as to give the latest SF 
evaluation function of the exact full leaf position? or which version of 
SF has the web guide be fixed to..

If such end-point were at least kept up to date, or with specified 
versions of the parameter set, then one could have a check point to test 
whether an output PV, proposed leaf for the best one, is indeed a leaf 
evaluation.. There would not be a need for a analytical debug version 
(to be differentiated with a tounrament performance debug version).  
Although, for engine analysis sake (analysis of the engine, not analysis 
with the engine, although one could help support the other), it might be 
good to have more access to internals, to let people do satistics, and 
possibly help the SF contributor community... and, most important for 
me, the chess engine user community.

I thank you in advance for further precisions about leaf evaluations. (I 
also have heard that the command line has some settings to mimic a leaf 
evaluation, but it is not clear whether it would be the same, in the 
case of a PV actual leaf, I guess similar quesiton there as for the web 
guide, which i would prefer to work with, as user, it gives more 
components of the evaluation function as a vector.

That's it.. the extent of my user end need for using SF engine as chess 
analytical tool. (I do have other questions, like the relationship 
between depth and hash table size that would be conservative enough to 
ensure preservation of leaf evaluations hashes, if those are the 
problem, though, maybe i'll try my luck on discord for those, as it may 
be based on misconception of mine about the nature of non-leaf 
evaluations attributed to root score..., for now i will accept not all 
are leaf eval, but please let me know by answering above if there is 
hope to find out for those that are leaf eval, and hence usable as score 
interpretation using web guide on such leaf, instead of receiving a root 
score from above).

Le 15/09/2022 à 07:49, Joost VandeVondele a écrit :

**Comment by bftjoe** [comment]
PV is not reliable for any alpha beta engine,  beyond maybe 1 or 2 half moves. You will have to set the position you want to analyze as the root position or use a non alpha beta engine to get the answers that you seek.

**Comment by Dboingue** [comment]
I think we should be careful with definitions.  I mean that i could 
relie on the root score value to be coming from the static evaluation 
(or full) evaluation of the apparent leaf output of the best PV by SF 
command line.  Not whether it was the best chess.  or not whether the 
interior nodes of that best PV were the actual best variations.. I just 
wanted internal reliability with what SF is outputting.. so i could link 
a root score with a position informatin i could look at and also use the 
SF web guide to get the various position information components that can 
be obtained there.. I do not really vare about the interior nodes.. One 
answer already given here was that with large input depth, the score 
attributed to root position might not always be that of a full 
evaluation of the leaf of the output PV... which leaves some questions 
about what is that PV being output... But for those that are really leaf 
evaluation being min-maxed ground backward, I would have liked the peek, 
and assurance by SF devs.  that either or both the command line static 
evala mode and or the SF web guide would correspond to something.

I any case, beside constructing a quantitative relationship  between 
root scores (for say some big position dataset, why not some subsamble 
from NNue training set), one could test the FEN of last PV node under 
those functions i just pointed.. and look for relationship.... that 
would be reverse "engineering" somehow. I thought best ask first.  It 
might save some time, or could be reinventing the wheel.. must already 
have been done somewhere.. some statistics about such firmly held notion 
that you repeat here.

What you are describing seems to be more about chess "accuracy" as one 
updates the root.... what engine do in tournaments for example... I am 
more intersted by single root search by engine... and internals.  so 
that when used to score a position through commandline or any gui, a 
chess user, could get the most interpretable output.  Just dismissing 
some of the output on the basis that this is not what engine are paid 
for in tournaments, does not change the fact that humans are going to 
analysis a position using such tool.

I don't know about chess, but in any other measurement task involving 
instruments, there are issues of calibration and range of validity of 
the instrument measures. One can then be aware of the limitations and 
how to actually interpret the measure with respect to the phenomena 
being measured.

having access to the static evaluation function input from whatever 
depth from root search tree, seems to me a crucial piece of information 
for interpreting root score for chess users.  That tournaments are still 
only making competitions between engines about speed of computation, now 
that engine have beaten humans on such calculation grounds

Before one can make such statement about non-alpha-beta engine as you 
did, there ought to be some external measure system to support that. one 
could be that tournament start thinking about that  as possible goal for 
competition.. humans don't. but engine could. just a lack of 
imagination, or just tradition momemtum.

Also, not my point here, althoug, I think once people would have the 
correct and full human readable input and ouput picture about AB 
engines, your statement might start to be more approachable.  I am not 
saying that it is not true...   The problem is that AB engine get their 
full position information input from deep in the tree, while probably 
oyu are refering to engine which do not discrimiante by position depth 
or otherwise for which position full information will be used as input.

One advantage though of the AB engine, is that both the classical static 
evaluation and the NNue input vector are hand-crafted in relation to 
things that can be visible and learnable by humans at the positions 
where they are selectively been used..   While that static funciton may 
not be as reliable early like non AB engine. It still has some interest 
from a human point of view.. I am not saying that the same could not be 
done with non AB engine full evaluation functions.. But that there too, 
the tournament immutable dogmas are not stimulating human analysis 
potential of any engine.

Le 15/09/2022 à 23:50, Joseph Huang a écrit :
