### ISSUE TITLE
Linux install instructions when selecting CPU

### ISSUE THREAD

**Issue by jxu** [official-stockfish/Stockfish#4169]
Assuming this is the right place for issues on installation from https://stockfishchess.org/download/linux/

Instead of recommending "pick the first binary that doesn't crash", what about suggesting `grep <flag> /proc/cpuinfo`?

**Comment by dav1312** [comment]
Please use https://github.com/official-stockfish/Stockfish/discussions for non-issues

**Comment by jxu** [comment]
non-issue as in it's not an issue, or not an issue about stockfish the program?

**Comment by jxu** [comment]
I found the obscure repo for stockfish-web

**Comment by dav1312** [comment]
> non-issue as in it's not an issue, or not an issue about stockfish the program?

Not an issue about Stockfish the program, but a topic for discussion.

**Comment by dav1312** [comment]
> I found the obscure repo for stockfish-web

Okay(?)
