### ISSUE TITLE
Feature request on android: AI

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#4172]
I notice that a while ago QUALCOMM introduced an AI engine widely used now in all Snapdragon family...
I think, from what I read so far, that stockfish would make a big leap in performance if it would utilize that.

https://developer.qualcomm.com/qualcomm-robotics-rb5-kit/software-reference-manual/machine-learning/snpe

**Comment by vondele** [comment]
no an issue, but of course patches would be appreciated.
