### ISSUE TITLE
Cross compiling from linux...

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#4179]
`$ make -j profile-build ARCH=armv8 COMP=aarch64-linux-android-gcc COMPCXX=aarch64-linux-android-g++
`Default net: nn-ad9b42354671.nnue
nn-ad9b42354671.nnue available.
Network validated

Config:
debug: 'no'
sanitize: 'none'
optimize: 'yes'
arch: 'armv8'
bits: '64'
kernel: 'Linux'
os: 'GNU/Linux'
prefetch: 'yes'
popcnt: 'yes'
pext: 'no'
sse: 'no'
mmx: 'no'
sse2: 'no'
ssse3: 'no'
sse41: 'no'
avx2: 'no'
avxvnni: 'no'
avx512: 'no'
vnni256: 'no'
vnni512: 'no'
neon: 'yes'
arm_version: '8'

Flags:
CXX: aarch64-linux-android-g++
CXXFLAGS:  -Wall -Wcast-qual -fno-exceptions -std=c++17  -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_POPCNT -DUSE_NEON=8
LDFLAGS:   -lpthread

**Testing config sanity. If this fails, try 'make help' ...

make: *** [Makefile:934: config-sanity] Error 1**

**Comment by vondele** [comment]
maybe `make -j profile-build ARCH=armv8 COMP=gcc COMPCXX=aarch64-linux-android-g++` ?

**Comment by Zibri** [comment]
same.
I ended up compiling it from WSL but using the windows binaries of the ndk...
[stockfish-armv8-270922.zip](https://github.com/official-stockfish/Stockfish/files/9652034/stockfish-armv8-270922.zip)
Here is the result... perfectly working.

**Comment by Zibri** [comment]
I did this:

- I compiled the latest stockfish for android ARM64 v8: [Stockfish for android ARM64 v8](https://github.com/official-stockfish/Stockfish/files/9652034/stockfish-armv8-270922.zip)
- I put the executable in /data/local/tmp/
- I ran it with: nc -L -p 50000 stockfish &
- from "Chess for android" I just added a network engine pointing at 127.0.0.1 port 50000 and it works perfectly.

**Comment by Zibri** [comment]
Latest compile for ARM64:
[stockfish-armv8-280922.zip](https://github.com/official-stockfish/Stockfish/files/9661138/stockfish-armv8-280922.zip)

**Comment by abdulbadii** [comment]
you incorrectly read instruction on `make help`?
```
Supported compilers:

gcc                     > Gnu compiler (default)
mingw                   > Gnu compiler with MinGW under Windows
clang                   > LLVM Clang compiler
icc                     > Intel compiler
ndk                     > Google NDK to cross-compile for Android
```
try install ndk and/or clang correctly and
... `COMP=ndk` ...
instead

or i think `COMP=clang `should work too

**Comment by vondele** [comment]
It looks like this issue can be closed.

**Comment by ppigazzini** [comment]
> 

Check this wiki section:
https://github.com/glinscott/fishtest/wiki/Advanced-topics#cross-compilation-for-all-platform-using-zig-toolchain

On WSL there is not `snap`, simply download zig and add it to the PATH.

```bash
# Use a clean Ubuntu to cross compile
# a static build for armv8 and armv7 on Linux/Android

# one time configuration
sudo apt update && sudo apt install -y make git
sudo snap install zig --classic --edge
sudo apt install -y qemu-user

# armv8 static build with musl libc
git clone https://github.com/official-stockfish/Stockfish.git
cd Stockfish/src
make -j build ARCH=armv8 COMP=gcc CXX="zig c++ -target aarch64-linux-musl"

# test: qemu's magic at work
qemu-aarch64 stockfish compiler
qemu-aarch64 stockfish bench

# armv7 static build with musl libc
# comment out "-latomic" flag in Makefile
make clean
make -j build ARCH=armv7 COMP=gcc CXX="zig c++ -target arm-linux-musleabihf"

# test: qemu's magic at work
qemu-arm stockfish compiler
qemu-arm stockfish bench
```
