### ISSUE TITLE
How exactly is NNUE utilization in alpha beta program

### ISSUE THREAD

**Issue by abdulbadii** [official-stockfish/Stockfish#4180]
So sorry if not proper place for the asking but on fishcooking google forum seem not get attention

How exactly is NNUE working mechanism in an alpha beta program, here specific is Stockfish
Is the NNUE 100% replaces evaluation or no i.e by some percentage in proportion to the ordinary evaluation?
If no, how is its working mechanism explanation, and relioably in proportion by how many percent

Thanks much for useful reply in advance

**Comment by Disservin** [comment]
Hi, for questions like these I think its better to either create a discussion on github or join discord and ask there. 
NNUE replaced HCE (Hand crafted evaluation) later it was found that switching to hce in some positions gains elo so right now theres a hybrid approach but lets continue this on discord.
