### ISSUE TITLE
Why does the "non-interactive" go behave differently ?

### ISSUE THREAD

**Issue by justUmen** [official-stockfish/Stockfish#4184]
Hi all,
I've just started to try to use stockfish a few minutes ago.
But I'm already confused about its behavior.

I can set `position fen`, `eval` and `go` (or `go movetime 5000`) as expected.

But if I do this :
`echo -e "position fen r2q3r/4nkpp/p1pbbp2/1pp1p3/4P3/P4N2/NPPP1PPP/R1B2KQR w - b6 0 12\neval\ngo movetime 5000" | ./stockfish`  

It is totally ignoring the go analysis and gives me a terrible move. `bestmove b2b3`
Is that a normal behavior, or is it only on my end ?

**Comment by vondele** [comment]
your end, but a tricky thing. After the echo sends the comment it disconnects from stdin which the engine interprets as a request to quit. So, essentially you don't search for 5000ms. 
This can be tricked by adding `ucinewgame` to the end, which waits for search completion, the proper solution would actually be to look at the engine output and wait for bestmove before closing stdin.

`echo -e "position fen r2q3r/4nkpp/p1pbbp2/1pp1p3/4P3/P4N2/NPPP1PPP/R1B2KQR w - b6 0 12\neval\ngo movetime 5000\nucinewgame" | ./stockfish`
