### ISSUE TITLE
Losses on time when testing with adjudication=OFF

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#4192]
In the following run of 40.000 STC games between SF-13 and a patch for SF-16-dev, there are at least two different workers posting batches with many losses on time. For instance, the fourth worker posted a batch with 217 losses on time for 932 games.

https://tests.stockfishchess.org/tests/view/6346c3d94bc7650f075471ce   (test)
https://tests.stockfishchess.org/api/pgn/6346c3d94bc7650f075471ce-3.pgn   (PGN file for fourth worker)
https://tests.stockfishchess.org/api/pgn/6346c3d94bc7650f075471ce-3.pgn  (another PGN with time losses)
 
Looking at the games in these PGN files, the time losses are both by SF 13 and by the patch, and happen very late in the games, (sometimes as late as after the engine announce mate in 5 moves: the engine is winning but loses on time).

One thing which is "special" in this test is that I disabled adjudication. So MAYBE we have a bug in time management in master for very long games, which we don't observe in normal fishtest tests because we usually run with adjudication=ON .

Ideas on theories to explain the situation, and how to proceed to avoid the time loses, would be welcome.

**Comment by bftjoe** [comment]
Maybe just run all new tests with =OFF for now and see what happens?

**Comment by snicolet** [comment]
In case the PGN file with the time losses disappears from the fishtest database, I have copied it here: http://cassio.free.fr/divers/6346c3d94bc7650f075471ce-3.pgn

**Comment by snicolet** [comment]
yes, stooping the run with the time losses and starting a new one with adjudication=ON is probably a good idea to get a comparison

**Comment by peregrineshahin** [comment]
https://github.com/glinscott/fishtest/pull/1435
I think we have an open PR draft for loosening the adjudication bounds in fishtest, I'm all in for removing it completely which may in return help us detect with more samples such an issue in SF time management or workers in general.

**Comment by snicolet** [comment]
Question: why don't we use a clamp in line 476 of search, to ensure that the variable `complexPosition` stay positive?
```
double complexPosition = std::min(1.0 + (complexity - 261) / 1738.7, 1.5);
double totalTime = Time.optimum() * fallingEval * reduction * bestMoveInstability * complexPosition;
```
The current code is not very robust if for some reason complexity is negative in some scenarios, as this gives a negative `totalTime` ?

**Comment by snicolet** [comment]
So, comparison run of 40.000 games against SF13 and adjudication=ON ended with time loses also, both for the patch and for SF13: 

https://tests.stockfishchess.org/tests/view/6346fbfc4bc7650f075479f2

**Comment by peregrineshahin** [comment]
Running these two lines at line 461 search.cpp before using time management (as it can't be tested with bench) at in both master and your recent PR https://github.com/official-stockfish/Stockfish/pull/4195, running `./stockfish bench` I got this interesting data:

with master:
running
```
      int testComplexity = mainThread->complexityAverage.value();
      dbg_mean_of(1.0 + (testComplexity - 261) / 1738.7 < 1);
```
Total 598 Mean 0.67893

===========================
Total time (ms) : 5194
Nodes searched  : 4156027
Nodes/second    : 800159

running
```
      int testComplexity = mainThread->complexityAverage.value();
      dbg_mean_of(1.0 + (testComplexity - 261) / 1738.7 < 0.9);
```
Total 598 Mean 0

===========================
Total time (ms) : 5715
Nodes searched  : 4156027
Nodes/second    : 727213

now with the tweak of the new complixity:
running
```
      int testComplexity = mainThread->complexityAverage.value();
      dbg_mean_of(1.0 + (testComplexity - 261) / 1738.7 < 0.9);
```
Total 598 Mean 0.00167224

===========================
Total time (ms) : 6040
Nodes searched  : 4633960
Nodes/second    : 767211

those were with normal `bench`, now running bench to 30 I haven't got a value < 0 thus I think we still don't get negative time!
I don't know if we already can get to that negative time but IMO yeah it doesn't look safe.

**Comment by dubslow** [comment]
> The current code is not very robust if for some reason `complexity` is negative in some scenarios, as this gives a negative `totalTime` ?
>

It was changed from clamp to min because, at least as of a month ago, it was provable that complexity is always positive (only ever assigned from `abs` return values). If that has changed in this patch, then that line ought to also be changed.

That said, time losses are common on certain users' setups. Cutechess issues definitely contribute, and in at least one case NUMA problems stacked on the cutechess issues to cause consistent numbers like that. A priori, I think it's unlikely to be a stockfish problem

**Comment by snicolet** [comment]
@peregrineshshin 
Indeed I think we could add some clamping and/or asserts in that part of the code, just to be on the safe side. I'll try to propose a PR.
