### ISSUE TITLE
Usage of sdot/udot in ARM 

### ISSUE THREAD

**Issue by Developer-Ecosystem-Engineering** [official-stockfish/Stockfish#4193]
Modern ARM processors, including Apple silicon, support _sdot/udot_ instructions which could improve many of your [NNUE operations](https://github.com/official-stockfish/Stockfish/blob/e639c4557786513018f625ff96f04b63157a85c1/src/nnue/layers/affine_transform.h#L127),  also overriding Simd::neon_m128_add_dpbusd_epi32x2 could help.

Information about these instructions and their use can be read about in more detail [here](https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/exploring-the-arm-dot-product-instructions).
We think you’d see about a 10% improvement leveraging these capabilities in Stockfish.

**Comment by Sopel97** [comment]
Thanks, this indeed appears to be useful. After some searching I found the relevant intrinsics, however I'm unable to get them to work https://godbolt.org/z/j8faff6xM. I'm also not sure if we have any developers who have both the required expertise and access to the needed hardware, so a PR would be the most welcome.

**Comment by Developer-Ecosystem-Engineering** [comment]
Hi @Sopel97,

The compiler needs to be told to use dotprod. Here is one such [example](https://github.com/pytorch/pytorch/blob/8a45ef23f564cc092fa0805ea6c0f8f73eed209c/third_party/xnnpack.buck.bzl#L1398) in another project.

**Comment by Sopel97** [comment]
I see, didn't know about the `+dotproduct` march. Working example https://godbolt.org/z/sfKnnE5E3.

**Comment by vondele** [comment]
maybe @domschl , who added the original NEON code in (https://github.com/official-stockfish/Stockfish/pull/2825/commits/c402fe7d26c910ea43bd538ef3c07b25fed3ba67), can help with this?

**Comment by Chess321** [comment]
Look what I found here: 
https://forums.macrumors.com/threads/macbook-pro-m1-max-m1-ultra-m2-usage-of-sdot-udot-in-arm.2371421/?post=31789556#post-31789556

I think it will be better to solve it fast and ask here:
https://discord.com/channels/332309672486895637/724838104225284128
r/Apple
Apple
-macos
-xcode

**Comment by vondele** [comment]
see the link provided in the initial comment. Basically, NNUE inference code is a matrix vector product, which can be done using dot products.
