### ISSUE TITLE
Small typo in README

### ISSUE THREAD

**Issue by Clausable** [official-stockfish/Stockfish#4207]
I'm extremely new to this, so please forgive my unhelpfulness.

There is a small typo in the recent update made to README that I've recently noticed, where at the end of the first paragraph of the Overview, it ends with "Read the documentation for your GUI of choice for **informationabout** how to use Stockfish with it.", which is clearly incorrect.

**Comment by Disservin** [comment]
Do you know how ? If so you can make a pull request with a correction ; )
