### ISSUE TITLE
Stinkfish - an option to play the worst possible move

### ISSUE THREAD

**Issue by pgalbraith** [official-stockfish/Stockfish#4209]
I'd love to see this option, for fun obviously.  The suggested option name is shamelessly lifted from this reddit post:

https://www.reddit.com/r/chess/comments/ob74em/i_created_a_slightly_modified_version_of/

See also, the forked implementation from the above poster:

https://github.com/rotolonico/Badfish

I'd love to see this as a UCI boolean option in the regular builds :-)

**Comment by vdbergh** [comment]
Stockfish is not a toy. It is a program designed to play the best possible chess. Feel free to make forks with whatever gimmicks you want.
