### ISSUE TITLE
Debug commands to probe tablebases

### ISSUE THREAD

**Issue by niklasf** [official-stockfish/Stockfish#421]
Would you accept patches adding a command to probe the tablebases for debugging or adding some output to `d`?

**Comment by mcostalba** [comment]
Who is supposed to _debug_ TB?

Currently this branch is largely unmaintained.

I suggest to fork your branch if you are interested in working on that code
and eventually come back with some pull request if you find some issue.

**Comment by niklasf** [comment]
Thanks for the fast response.
