### ISSUE TITLE
Stockfish crashes when loading fen

### ISSUE THREAD

**Issue by xeenoon** [official-stockfish/Stockfish#4224]
### Describe the issue

If you paste this FEN into stockfish (percectly valid): rnbqkbnr/pppppppp/8/8/8/N2NNNNN/PPPPPPPP/RNBQKBNR w KQkq - 0 1

It just crashes

![image](https://user-images.githubusercontent.com/92002241/200205458-7cb551e8-2609-4055-af21-e474c03544c2.png)

Stockfish suggests the move e4, before just crashing.

![image](https://user-images.githubusercontent.com/92002241/200205522-02b46a7d-7c91-4c5e-9810-3ddf8d5352d5.png)

### Expected behavior

Stockfish should suggest a move, or send SOMETHING to the chess GUI telling it that the position is unanalyzeable

### Steps to reproduce

position fen rnbqkbnr/pppppppp/8/8/8/N2NNNNN/PPPPPPPP/RNBQKBNR w KQkq - 0 1
go infinite

### Anything else?

Just wrap main function in a try-catch statement

If you get to catch, just return "Cannot analyse position"

### Operating system

Windows

### Stockfish version

Stockfish 15

**Comment by vondele** [comment]
with more than 32 pieces, this is not a valid fen. This is up to the GUI to reject it. The standard protocol to communicate between GUI and engine (UCI) doens't allow for sending error messages.
