### ISSUE TITLE
Chessbase Let's Check reports New Engine on Development Versions

### ISSUE THREAD

**Issue by gregfreeze** [official-stockfish/Stockfish#4225]
### Describe the issue

https://github.com/official-stockfish/Stockfish/pull/4220 changed the pattern for development versions that is returned to Let's Check from Chessbase. Now, a development version comes back as "New Engine" rather than the actual build. The pattern supported by Chessbsase is "Stockfish NNNNNN" for development builds. Perhaps better for this change is "Stockfish YYMMDD" to get the sort order in a better format for picking engines.

![image](https://user-images.githubusercontent.com/117674178/200378893-81c27dcf-4fa4-4f1b-b1a6-4da2d573c773.png)

### Expected behavior

I've tried to get Chessbase to support a product that they own (i.e., Dragon), but after a year, they still haven't taken the time to make this happen.

### Steps to reproduce

With a ChessBase product, create a UCI engine using a build on or after Nov 7, 2022. Make the new UCI engine active. With a user with a ChessBase account with Live Book access, watch how the name is formed when a position is studied long enough to leave a Let's Check trail.

### Operating system

Windows

### Stockfish version

Stockfish dev-20221107-nogit

**Comment by Sopel97** [comment]
Stockfish conforms to the UCI protocol, which specifies that the engine should provide its name when ran. Stockfish does so correctly, for example reporting `id name Stockfish dev-20221107-b3f068cc7`. If chessbase is doing anything other than displaying this name then it's an issue with chessbase.

**Comment by peregrineshahin** [comment]
The output they show as the engine name is not cleanly extracted from the engine name even before the PR, the script/code they have that parse the name and manipulate it to look like that format is done by their side and is now outdated. I don't see how this is a Stockfish issue.

**Comment by vondele** [comment]
I agree this is a GUI problem. Unfortunate, but the format we have now is pretty useful in general.
