### ISSUE TITLE
[tools] gather_statistics incorrectly counts castling moves as captures

### ISSUE THREAD

**Issue by linrock** [official-stockfish/Stockfish#4282]
### Describe the issue

When running `stockfish gather_statistics ...` from the tools branch, the # of captures reported in "Number of moves by type" is incorrect, as castling moves incorrectly count towards captures.

The bug is here. The target square is always empty while castling in standard chess games. So castling moves are double-counted as captures:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/208617/207093529-a6731fcd-7afe-4884-8cbe-072313815692.png">

### Expected behavior

The # of captures should not count # castling moves in "Number of moves by type"

### Steps to reproduce

Use any binpack file with zero captures and at least a few castling moves. Use `stockfish gather_statistics` to gather stats and see that # of captures counts the castling moves.

### Operating system

All

### Stockfish version

Stockfish tools branch

**Comment by Disservin** [comment]
Castling is encoded as king captures rook so to square is always occupied, && type_of(move) != CASTLING

**Comment by vondele** [comment]
fixed with the merge
