### ISSUE TITLE
Stockfish 15 1 Critical Blunder

### ISSUE THREAD

**Issue by lHenryZl** [official-stockfish/Stockfish#4289]
### Describe the issue

![Stockfish 15 1 Critical Blunder](https://user-images.githubusercontent.com/106044981/208326709-f16ef9b0-cb8f-405f-a359-a98306bacb50.png)
Hi Stockfish developers, I have recently noticed that Stockfish will make some blunders such as sacrificing the rook. According to the uploaded picture, there is no timing issues, and stockfish 15.1 just can stop giving up its rook. 

### Expected behavior

Stockfish's end game skills should be enhanced especially when the game should be a draw. 

### Steps to reproduce

![Stockfish 15 1 Critical Blunder](https://user-images.githubusercontent.com/106044981/208326709-f16ef9b0-cb8f-405f-a359-a98306bacb50.png)
The issue can be reproduced by the PGN in the uploaded picture. 

### Operating system

All

### Stockfish version

Stockfish 15.1

**Comment by Sopel97** [comment]
Can't replicate. Please post the full PGN in text form.

**Comment by lHenryZl** [comment]
#This is the first PGN: 
[Event "banksia game"]
[Site "*"]
[Date "2022.12.19"]
[Round "*"]
[White "Lc0 v0.29.0"]
[Black "Stockfish 15.1"]
[Result "*"]
[TimeControl "99/1200+1"]
[Time "09:57:08"]
[Termination "*"]
[SetUp "1"]
[ECO "D45"]
[Opening "QGD semi-Slav"]

1.d4 {+0.14/8 27205 10633 320/460/220}  d5 {+0.23/35 58349 77404482 3/970/27}  2.c4 {+0.14/10 7213 9623 319/465/216}  c6 {+0.25/31 9129 23310601 2/969/29} 
3.Nc3 {+0.16/10 36005 11219 330/455/215}  Nf6 {+0.22/31 1493 49296512 3/973/24}  4.Nf3 {+0.15/10 24157 8657 327/457/216}  e6 {+0.25/30 15225 22517965 2/971/27} 
5.e3 {+0.16/10 13409 7940 320/476/204}  Nbd7 {+0.19/29 15669 22013474 3/977/20}  6.Qc2 {+0.16/10 18829 10708 320/474/206}  Bd6 {+0.18/27 10 27995720 3/979/18; D45: QGD semi-Slav, Stoltz variation} 
7.Bd3 {+0.14/13 21999 9769 312/478/210}  dxc4 {+0.19/32 45988 89581456 2/980/18}  8.Bxc4 {+0.16/10 15730 7804 326/461/213}  O-O {+0.23/31 54421 79069849 2/976/22} 
9.O-O {+0.14/10 10000 11062 318/469/213}  a6 {+0.19/29 5248 24388437 2/981/17}  10.e4 {+0.14/9 79896 13027 324/456/220}  e5 {+0.16/34 30659 127195217 3/983/14} 
11.h3 {+0.11/11 17807 11833 310/463/227}  b5 {+0.02/31 22258 34751426 5/988/7}  12.Bb3 {+0.13/11 18025 8163 318/457/225}  c5 {+0.06/36 25773 53792342 4/988/8} 
13.dxc5 {+0.08/13 9272 6536 288/487/225}  Nxc5 {+0.12/31 1967 14093754 3/986/11}  14.Bg5 {+0.09/12 40791 10825 278/511/211}  Nxb3 {+0.00/36 11804 19943864 5/990/5} 
15.axb3 {+0.06/11 35058 11225 272/501/227}  Bb7 {+0.00/31 13734 14942462 5/990/5}  16.Rfd1 {+0.04/11 4213 7429 266/501/233}  h6 {+0.00/38 11447 17833605 5/990/5} 
17.Bh4 {+0.03/11 5697 6582 259/509/232}  Re8 {+0.00/37 10882 18580385 5/990/5}  18.Qe2 {+0.02/11 41250 11637 236/544/220}  g5 {-0.14/31 13775 21687111 11/987/2} 
19.Bg3 {-0.06/12 28380 6721 196/561/243}  Qe7 {+0.00/43 22427 55866494 5/990/5}  20.h4 {-0.04/13 8496 11697 122/727/151}  b4 {+0.00/41 6858 17093852 5/990/5} 
21.hxg5 {-0.04/12 11092 15563 97/772/131}  hxg5 {+0.00/43 4616 18512473 5/990/5}  22.Qd2 {-0.03/13 11098 20092 100/779/121}  bxc3 {+0.00/45 10663 22208829 5/991/4} 
23.Qxg5+ {-0.03/11 21768 35208 90/797/113}  Kh7 {+0.00/47 18278 42109682 5/991/4}  24.Qh4+ {-0.02/13 74325 106439 114/753/133}  Kg7 {+0.00/51 21894 30459177 4/992/4} 
25.Qg5+ {-0.02/14 804 46063 95/794/111}  Kh8 {+0.00/51 21745 28960691 4/992/4}  26.Qh6+ {+0.00/21 9776 14940 191/620/189}  Kg8 {+0.00/53 18802 29022190 4/992/4} 
27.Bh4 {+0.00/16 8682 19123 194/614/192}  Ng4 {-0.06/35 16698 18800975 6/991/3}  28.Qh5 {+0.00/18 5156 20418 183/631/186}  Qe6 {-0.03/36 13648 19292844 5/991/4} 
29.Ng5 {+0.00/16 3015 20744 178/648/174}  Nf6 {-0.06/34 14609 19611899 6/991/3}  30.Qf3 {+0.00/17 4321 20233 166/675/159}  Bxe4 {-0.05/36 11135 20528532 6/991/3} 
31.Nxe4 {-0.01/17 105023 36833 138/713/149}  Nxe4 {+0.00/44 18 105614692 4/992/4}  32.Qxe4 {-0.01/16 2801 21252 134/724/142}  cxb2 {+0.00/48 12903 17386817 4/992/4} 
33.Rab1 {+0.00/14 25201 26385 131/734/135}  Rab8 {+0.00/44 11 25754050 4/992/4}  34.Rxb2 {-0.01/12 5326 16017 115/759/126}  Rb4 {-0.04/35 8145 18078902 5/992/3} 
35.Qe3 {+0.00/10 18205 19129 111/772/117}  Qg6 {-0.07/31 13099 15478366 6/991/3}  36.Qg5 {-0.01/8 69819 12374 83/823/94}  Re6 {+0.00/38 10 69918860 4/992/4} 
37.Rbd2 {-0.06/8 67986 13682 94/767/139}  Bc5 {+0.00/45 28 73860681 4/992/4}  38.Rd5 {-0.07/9 23981 5161 72/803/125}  Bb6 {+0.00/42 15452 17206142 4/992/4} 
39.Qxg6+ {-0.09/12 7441 3268 53/825/122}  Rxg6 {-0.05/32 13205 15490201 6/991/3}  40.Bd8 {-0.05/9 12648 5154 64/830/106}  Rbg4 {+0.00/44 665 16339576 4/992/4} 
41.Bxb6 {-0.18/14 47297 12176 25/819/156}  Rxg2+ {+0.00/58 15993 22236744 4/992/4}  42.Kf1 {-0.20/15 1542 8902 19/816/165}  Rg1+ {+0.00/60 23105 35361490 5/991/4} 
43.Ke2 {-0.23/1 568 13922 15/810/175}  Rxd1 {+0.00/65 13883 24904360 5/991/4}  44.Kxd1 {-0.23/12 2451 17531 8/823/169}  Rxb6 {+0.00/67 12776 24864123 5/991/4} 
45.Rxe5 {-0.23/10 3349 20324 5/830/165}  Rxb3 {+0.00/67 9158 22180389 5/990/5}  46.Ra5 {-0.24/8 15866 25003 4/825/171}  Rb1+ {+0.00/64 31 30082372 5/990/5} 
47.Ke2 {-0.19/8 73711 37877 4/858/138}  Rb2+ {+0.00/65 67 147260550 5/990/5}  48.Ke3 {-0.12/6 30327 10309 4/903/93}  Rb3+ {+0.00/67 12329 29526377 5/990/5} 
49.Ke4 {-0.10/6 14018 5839 6/917/77}  Rb4+ {+0.00/70 11867 28366412 5/990/5}  50.Ke3 {-0.10/6 11876 4592 5/917/78}  Rb3+ {+0.00/72 20028 35178049 5/990/5} 
51.Ke4 {-0.10/6 11926 6359 6/916/78}  f5+ {+0.00/74 11672 21280651 5/990/5}  52.Kf4 {+0.00/4 10732 1256 2/989/9}  Rb4+ {+0.00/72 971 22068429 5/990/5} 
53.Kg5 {-0.01/4 10408 1181 2/988/10}  Rg4+ {+0.00/87 12725 19565219 5/990/5}  54.Kh5 {+0.01/4 9210 1628 14/981/5}  Rg2 {+0.00/83 13388 23345248 5/990/5} 
55.Rxa6 {+0.03/4 7625 1528 30/968/2}  Rh2+ {+0.00/113 12998 22673485 5/990/5}  56.Kg6 {+0.00/4 7406 2716 6/993/1}  Rg2+ {+0.00/184 6308 27559624 5/990/5} 
57.Kh6 {+0.02/4 6983 2264 19/979/2}  Rxf2 {+0.00/141 16711 29751014 5/990/5}  58.Kg6 {+0.00/4 5783 1164 1/999/0}  Kf8 {+0.00/56 43698 112286764 6/988/6} 
59.Kf6 {+0.00/4 5223 4254 1/997/2}  Ke8 {+0.00/58 14168 36346380 6/988/6}  60.Ra1 {+0.00/4 4897 2115 1/999/0}  f4 {+0.00/57 14647 32424765 6/988/6} 
61.Kf5 {+0.00/4 4231 722 0/1000/0}  f3 {+0.00/58 16175 38220781 6/988/6}  62.Kf4 {+0.00/4 3862 610 0/1000/0}  Kf7 {+0.00/59 14631 32590205 6/988/6} 
63.Rb1 {+0.00/3 3644 561 0/1000/0}  Kg7 {+0.00/59 15501 40280626 6/988/6}  64.Ke4 {+0.00/4 3200 584 0/1000/0}  Ra2 {+0.00/51 14746 42271726 6/988/6} 
65.Kxf3 {+0.00/4 2926 759 0/1000/0}  Kf6 {+0.00/50 9119 34863231 6/988/6}  66.Kf4 {+0.00/3 2692 314 0/1000/0}  Ra4+ {+0.00/48 11803 25890787 6/988/6} 
67.Kf3 {+0.00/4 2441 262 0/1000/0}  Ra2 {+0.00/53 14563 30621105 6/988/6}  68.Ke3 {+0.00/3 2277 310 0/1000/0}  Ra3+ {+0.00/48 12637 27178688 7/986/7} 
69.Ke4 {+0.00/3 2117 237 0/1000/0}  Ra4+ {+0.00/42 12076 23249721 7/986/7}  70.Ke3 {+0.00/4 1983 200 0/1000/0}  Ra3+ {+0.00/45 13192 34091295 7/986/7} 
71.Kd4 {+0.00/4 1812 337 0/1000/0}  Ra4+ {+0.00/45 11955 30559419 7/986/7}  72.Ke3 {+0.00/4 1724 268 0/1000/0}  Ke5 {+0.00/55 64300 118589768 7/986/7} 
73.Rb6 {+0.00/4 1652 1000 7/993/0}  Ra1 {+0.00/44 10564 20122054 7/986/7}  74.Rb8 {+0.00/3 1532 264 0/1000/0}  Rg1 {+0.00/46 10041 21977240 7/986/7} 
75.Kf2 {+0.00/3 1448 171 0/1000/0}  Ra1 {+0.00/42 9553 22521877 7/986/7}  76.Ke2 {+0.00/3 1285 279 0/1000/0}  Kd6 {+0.00/45 10975 26313904 7/986/7} 
77.Kd2 {+0.00/3 1369 229 0/1000/0}  Ra7 {+0.00/43 10006 23286694 7/986/7}  78.Rb2 {+0.00/3 1307 202 0/1000/0}  Ra1 {+0.00/42 8121 18012527 7/986/7} 
79.Kc3 {+0.00/3 1290 100 0/1000/0}  Ra3+ {+0.00/47 9840 16403338 8/984/8}  80.Kd2 {+0.00/3 1248 104 0/1000/0}  Kd5 {+0.00/43 10863 18345969 8/984/8} 
81.Rb1 {+0.00/3 1217 132 0/1000/0}  Kc4 {+0.00/44 11485 18672489 8/984/8}  82.Rc1+ {+0.00/3 1187 133 0/1000/0}  Kd4 {+0.00/47 12625 22285864 8/984/8} 
83.Rc8 {+0.00/4 1159 503 0/1000/0}  Rg3 {+0.00/48 11592 19155720 8/984/8}  84.Kc2 {+0.00/3 1143 227 0/1000/0}  Rg1 {+0.00/46 7510 15628839 8/984/8} 
85.Kb3 {+0.00/3 1131 131 0/1000/0}  Rb1+ {+0.00/51 9106 15241022 8/984/8}  86.Ka2 {+0.00/4 823 108 0/1000/0}  Rb7 {+0.00/50 10731 25511965 8/984/8} 
87.Ka1 {+0.00/4 1114 385 0/1000/0}  Rf7 {+0.00/45 9455 20892854 8/984/8}  88.Kb2 {+0.00/3 1106 243 0/1000/0}  Rf1 {+0.00/51 8926 20561203 8/984/8} 
89.Ka2 {+0.00/3 1097 198 0/1000/0}  Kd3 {+0.00/42 8862 18152215 8/984/8}  90.Kb2 {+0.00/3 1075 177 0/1000/0}  Rf2+ {+0.00/43 8599 20755139 8/984/8} 
91.Kb3 {+0.00/5 604 142 0/1000/0}  Rf1 {+0.00/42 7086 11641806 8/984/8}  92.Rg8 {+0.00/3 1137 117 0/1000/0}  Rf6 {+0.00/41 7561 11718368 8/984/8} 
93.Rd8+ {+0.00/3 1161 93 0/1000/0}  Ke2 {+0.00/40 6850 10613009 8/984/8}  94.Kc4 {+0.00/5 672 264 0/1000/0}  Rc6+ {+0.00/38 6369 9720675 8/984/8} 
95.Kb4 {+0.00/3 1251 103 0/1000/0}  Rb6+ {+0.00/39 4598 10096207 8/984/8}  96.Kc4 {+0.00/3 1193 88 0/1000/0}  Rb1 {+0.00/37 6486 10343213 8/984/8} 
97.Ra8 {+0.00/3 562 74 0/1000/0}  Kd1 {+0.00/38 4702 7414953 8/984/8}  98.Kc3 {+0.04/3 1487 103 35/965/0}  Rb7 {+0.00/31 2328 4260425 8/984/8} 
99.Rd8+ {+0.00/3 1513 123 1/999/0}  Kc1 {+0.00/33 1640 3131570 8/984/8}  100.Rh8 {+0.00/1 479 64 2/998/0}  Rc7+ {+0.00/42 47963 67533511 8/984/8} 
101.Kb3 {+0.00/6 112725 36775 4/996/0}  Rb7+ {+0.00/57 35721 80733647 8/984/8}  102.Kc3 {+0.00/5 100038 25915 6/993/1}  Rc7+ {+0.00/62 30 203084215 8/984/8} 
103.Kd3 {+0.00/5 96978 29529 3/996/1}  Kb2 {+0.00/51 34287 57592888 8/984/8}  104.Rb8+ {+0.00/5 82995 31244 1/999/0}  Kc1 {+0.00/51 35386 74562954 8/984/8} 
105.Rd8 {+0.00/5 74771 26998 4/996/0}  Rb7 {+0.00/52 33346 72153329 8/984/8}  106.Kc3 {+0.00/5 67260 17897 6/990/4}  Rc7+ {+0.00/50 31417 55855389 8/984/8} 
107.Kb4 {+0.00/5 60805 19541 2/998/0}  Rc2 {+0.00/57 18 139301400 8/984/8}  108.Rh8 {+0.00/5 57038 14501 5/995/0}  Rb2+ {+0.00/53 31591 70364388 8/984/8} 
109.Kc3 {+0.02/5 47139 10531 16/984/0}  Rc2+ {+0.00/56 30821 54681118 8/984/8}  110.Kb3 {+0.01/5 65123 17175 9/990/1}  Rc6 {+0.00/59 31808 70286098 8/984/8} 
111.Rf8 {+0.01/5 39082 11370 10/990/0}  Kd1 {+0.00/59 27688 61535726 7/986/7}  112.Rg8 {+0.01/4 35844 9659 9/991/0}  Rb6+ {+0.00/140 39737 102400873 7/986/7} 
113.Kc3 {+0.00/5 202653 10032028 7/987/6}  Rb5 {+0.00/166 101022 361173029 7/986/7}  114.Rd8+ {+0.00/2 39882 15461350 0/1000/0}  Ke1  115.Rd7 Rb1  116.Ra7 Ra1??



#And here is another critical one, Stockfish 15.1 let Lc0 checkmate. 
[Event "banksia game"]
[Site "*"]
[Date "2022.12.19"]
[Round "*"]
[White "Lc0 v0.29.0"]
[Black "Stockfish 15.1"]
[Result "*"]
[TimeControl "99/1200+1"]
[Time "09:57:08"]
[Termination "*"]
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 8"]
[SetUp "1"]
[ECO "D45"]
[Opening "QGD semi-Slav"]

1.d4 {+0.14/8 27205 10633 320/460/220}  d5 {+0.23/35 58349 77404482 3/970/27}  2.c4 {+0.14/10 7213 9623 319/465/216}  c6 {+0.25/31 9129 23310601 2/969/29} 
3.Nc3 {+0.16/10 36005 11219 330/455/215}  Nf6 {+0.22/31 1493 49296512 3/973/24}  4.Nf3 {+0.15/10 24157 8657 327/457/216}  e6 {+0.25/30 15225 22517965 2/971/27} 
5.e3 {+0.16/10 13409 7940 320/476/204}  Nbd7 {+0.19/29 15669 22013474 3/977/20}  6.Qc2 {+0.16/10 18829 10708 320/474/206}  Bd6 {+0.18/27 10 27995720 3/979/18; D45: QGD semi-Slav, Stoltz variation} 
7.Bd3 {+0.14/13 21999 9769 312/478/210}  dxc4 {+0.19/32 45988 89581456 2/980/18}  8.Bxc4 {+0.16/10 15730 7804 326/461/213}  O-O {+0.23/31 54421 79069849 2/976/22} 
9.O-O {+0.14/10 10000 11062 318/469/213}  a6 {+0.19/29 5248 24388437 2/981/17}  10.e4 {+0.14/9 79896 13027 324/456/220}  e5 {+0.16/34 30659 127195217 3/983/14} 
11.h3 {+0.11/11 17807 11833 310/463/227}  b5 {+0.02/31 22258 34751426 5/988/7}  12.Bb3 {+0.13/11 18025 8163 318/457/225}  c5 {+0.06/36 25773 53792342 4/988/8} 
13.dxc5 {+0.08/13 9272 6536 288/487/225}  Nxc5 {+0.12/31 1967 14093754 3/986/11}  14.Bg5 {+0.09/12 40791 10825 278/511/211}  Nxb3 {+0.00/36 11804 19943864 5/990/5} 
15.axb3 {+0.06/11 35058 11225 272/501/227}  Bb7 {+0.00/31 13734 14942462 5/990/5}  16.Rfd1 {+0.04/11 4213 7429 266/501/233}  h6 {+0.00/38 11447 17833605 5/990/5} 
17.Bh4 {+0.03/11 5697 6582 259/509/232}  Re8 {+0.00/37 10882 18580385 5/990/5}  18.Qe2 {+0.02/11 41250 11637 236/544/220}  g5 {-0.14/31 13775 21687111 11/987/2} 
19.Bg3 {-0.06/12 28380 6721 196/561/243}  Qe7 {+0.00/43 22427 55866494 5/990/5}  20.h4 {-0.04/13 8496 11697 122/727/151}  b4 {+0.00/41 6858 17093852 5/990/5} 
21.hxg5 {-0.04/12 11092 15563 97/772/131}  hxg5 {+0.00/43 4616 18512473 5/990/5}  22.Qd2 {-0.03/13 11098 20092 100/779/121}  bxc3 {+0.00/45 10663 22208829 5/991/4} 
23.Qxg5+ {-0.03/11 21768 35208 90/797/113}  Kh7 {+0.00/47 18278 42109682 5/991/4}  24.Qh4+ {-0.02/13 74325 106439 114/753/133}  Kg7 {+0.00/51 21894 30459177 4/992/4} 
25.Qg5+ {-0.02/14 804 46063 95/794/111}  Kh8 {+0.00/51 21745 28960691 4/992/4}  26.Qh6+ {+0.00/21 9776 14940 191/620/189}  Kg8 {+0.00/53 18802 29022190 4/992/4} 
27.Bh4 {+0.00/16 8682 19123 194/614/192}  Ng4 {-0.06/35 16698 18800975 6/991/3}  28.Qh5 {+0.00/18 5156 20418 183/631/186}  Qe6 {-0.03/36 13648 19292844 5/991/4} 
29.Ng5 {+0.00/16 3015 20744 178/648/174}  Nf6 {-0.06/34 14609 19611899 6/991/3}  30.Qf3 {+0.00/17 4321 20233 166/675/159}  Bxe4 {-0.05/36 11135 20528532 6/991/3} 
31.Nxe4 {-0.01/17 105023 36833 138/713/149}  Nxe4 {+0.00/44 18 105614692 4/992/4}  32.Qxe4 {-0.01/16 2801 21252 134/724/142}  cxb2 {+0.00/48 12903 17386817 4/992/4} 
33.Rab1 {+0.00/14 25201 26385 131/734/135}  Rab8 {+0.00/44 11 25754050 4/992/4}  34.Rxb2 {-0.01/12 5326 16017 115/759/126}  Rb4 {-0.04/35 8145 18078902 5/992/3} 
35.Qe3 {+0.00/10 18205 19129 111/772/117}  Qg6 {-0.07/31 13099 15478366 6/991/3}  36.Qg5 {-0.01/8 69819 12374 83/823/94}  Re6 {+0.00/38 10 69918860 4/992/4} 
37.Rbd2 {-0.06/8 67986 13682 94/767/139}  Bc5 {+0.00/45 28 73860681 4/992/4}  38.Rd5 {-0.07/9 23981 5161 72/803/125}  Bb6 {+0.00/42 15452 17206142 4/992/4} 
39.Qxg6+ {-0.09/12 7441 3268 53/825/122}  Rxg6 {-0.05/32 13205 15490201 6/991/3}  40.Bd8 {-0.05/9 12648 5154 64/830/106}  Rbg4 {+0.00/44 665 16339576 4/992/4} 
41.Bxb6 {-0.18/14 47297 12176 25/819/156}  Rxg2+ {+0.00/58 15993 22236744 4/992/4}  42.Kf1 {-0.20/15 1542 8902 19/816/165}  Rg1+ {+0.00/60 23105 35361490 5/991/4} 
43.Ke2 {-0.23/1 568 13922 15/810/175}  Rxd1 {+0.00/65 13883 24904360 5/991/4}  44.Kxd1 {-0.23/12 2451 17531 8/823/169}  Rxb6 {+0.00/67 12776 24864123 5/991/4} 
45.Rxe5 {-0.23/10 3349 20324 5/830/165}  Rxb3 {+0.00/67 9158 22180389 5/990/5}  46.Ra5 {-0.24/8 15866 25003 4/825/171}  Rb1+ {+0.00/64 31 30082372 5/990/5} 
47.Ke2 {-0.19/8 73711 37877 4/858/138}  Rb2+ {+0.00/65 67 147260550 5/990/5}  48.Ke3 {-0.12/6 30327 10309 4/903/93}  Rb3+ {+0.00/67 12329 29526377 5/990/5} 
49.Ke4 {-0.10/6 14018 5839 6/917/77}  Rb4+ {+0.00/70 11867 28366412 5/990/5}  50.Ke3 {-0.10/6 11876 4592 5/917/78}  Rb3+ {+0.00/72 20028 35178049 5/990/5} 
51.Ke4 {-0.10/6 11926 6359 6/916/78}  f5+ {+0.00/74 11672 21280651 5/990/5}  52.Kf4 {+0.00/4 10732 1256 2/989/9}  Rb4+ {+0.00/72 971 22068429 5/990/5} 
53.Kg5 {-0.01/4 10408 1181 2/988/10}  Rg4+ {+0.00/87 12725 19565219 5/990/5}  54.Kh5 {+0.01/4 9210 1628 14/981/5}  Rg2 {+0.00/83 13388 23345248 5/990/5} 
55.Rxa6 {+0.03/4 7625 1528 30/968/2}  Rh2+ {+0.00/113 12998 22673485 5/990/5}  56.Kg6 {+0.00/4 7406 2716 6/993/1}  Rg2+ {+0.00/184 6308 27559624 5/990/5} 
57.Kh6 {+0.02/4 6983 2264 19/979/2}  Rxf2 {+0.00/141 16711 29751014 5/990/5}  58.Kg6 {+0.00/4 5783 1164 1/999/0}  Kf8 {+0.00/56 43698 112286764 6/988/6} 
59.Kf6 {+0.00/4 5223 4254 1/997/2}  Ke8 {+0.00/58 14168 36346380 6/988/6}  60.Ra1 {+0.00/4 4897 2115 1/999/0}  f4 {+0.00/57 14647 32424765 6/988/6} 
61.Kf5 {+0.00/4 4231 722 0/1000/0}  f3 {+0.00/58 16175 38220781 6/988/6}  62.Kf4 {+0.00/4 3862 610 0/1000/0}  Kf7 {+0.00/59 14631 32590205 6/988/6} 
63.Rb1 {+0.00/3 3644 561 0/1000/0}  Kg7 {+0.00/59 15501 40280626 6/988/6}  64.Ke4 {+0.00/4 3200 584 0/1000/0}  Ra2 {+0.00/51 14746 42271726 6/988/6} 
65.Kxf3 {+0.00/4 2926 759 0/1000/0}  Kf6 {+0.00/50 9119 34863231 6/988/6}  66.Kf4 {+0.00/3 2692 314 0/1000/0}  Ra4+ {+0.00/48 11803 25890787 6/988/6} 
67.Kf3 {+0.00/4 2441 262 0/1000/0}  Ra2 {+0.00/53 14563 30621105 6/988/6}  68.Ke3 {+0.00/3 2277 310 0/1000/0}  Ra3+ {+0.00/48 12637 27178688 7/986/7} 
69.Ke4 {+0.00/3 2117 237 0/1000/0}  Ra4+ {+0.00/42 12076 23249721 7/986/7}  70.Ke3 {+0.00/4 1983 200 0/1000/0}  Ra3+ {+0.00/45 13192 34091295 7/986/7} 
71.Kd4 {+0.00/4 1812 337 0/1000/0}  Ra4+ {+0.00/45 11955 30559419 7/986/7}  72.Ke3 {+0.00/4 1724 268 0/1000/0}  Ke5 {+0.00/55 64300 118589768 7/986/7} 
73.Rb6 {+0.00/4 1652 1000 7/993/0}  Ra1 {+0.00/44 10564 20122054 7/986/7}  74.Rb8 {+0.00/3 1532 264 0/1000/0}  Rg1 {+0.00/46 10041 21977240 7/986/7} 
75.Kf2 {+0.00/3 1448 171 0/1000/0}  Ra1 {+0.00/42 9553 22521877 7/986/7}  76.Ke2 {+0.00/3 1285 279 0/1000/0}  Kd6 {+0.00/45 10975 26313904 7/986/7} 
77.Kd2 {+0.00/3 1369 229 0/1000/0}  Ra7 {+0.00/43 10006 23286694 7/986/7}  78.Rb2 {+0.00/3 1307 202 0/1000/0}  Ra1 {+0.00/42 8121 18012527 7/986/7} 
79.Kc3 {+0.00/3 1290 100 0/1000/0}  Ra3+ {+0.00/47 9840 16403338 8/984/8}  80.Kd2 {+0.00/3 1248 104 0/1000/0}  Kd5 {+0.00/43 10863 18345969 8/984/8} 
81.Rb1 {+0.00/3 1217 132 0/1000/0}  Kc4 {+0.00/44 11485 18672489 8/984/8}  82.Rc1+ {+0.00/3 1187 133 0/1000/0}  Kd4 {+0.00/47 12625 22285864 8/984/8} 
83.Rc8 {+0.00/4 1159 503 0/1000/0}  Rg3 {+0.00/48 11592 19155720 8/984/8}  84.Kc2 {+0.00/3 1143 227 0/1000/0}  Rg1 {+0.00/46 7510 15628839 8/984/8} 
85.Kb3 {+0.00/3 1131 131 0/1000/0}  Rb1+ {+0.00/51 9106 15241022 8/984/8}  86.Ka2 {+0.00/4 823 108 0/1000/0}  Rb7 {+0.00/50 10731 25511965 8/984/8} 
87.Ka1 {+0.00/4 1114 385 0/1000/0}  Rf7 {+0.00/45 9455 20892854 8/984/8}  88.Kb2 {+0.00/3 1106 243 0/1000/0}  Rf1 {+0.00/51 8926 20561203 8/984/8} 
89.Ka2 {+0.00/3 1097 198 0/1000/0}  Kd3 {+0.00/42 8862 18152215 8/984/8}  90.Kb2 {+0.00/3 1075 177 0/1000/0}  Rf2+ {+0.00/43 8599 20755139 8/984/8} 
91.Kb3 {+0.00/5 604 142 0/1000/0}  Rf1 {+0.00/42 7086 11641806 8/984/8}  92.Rg8 {+0.00/3 1137 117 0/1000/0}  Rf6 {+0.00/41 7561 11718368 8/984/8} 
93.Rd8+ {+0.00/3 1161 93 0/1000/0}  Ke2 {+0.00/40 6850 10613009 8/984/8}  94.Kc4 {+0.00/5 672 264 0/1000/0}  Rc6+ {+0.00/38 6369 9720675 8/984/8} 
95.Kb4 {+0.00/3 1251 103 0/1000/0}  Rb6+ {+0.00/39 4598 10096207 8/984/8}  96.Kc4 {+0.00/3 1193 88 0/1000/0}  Rb1 {+0.00/37 6486 10343213 8/984/8} 
97.Ra8 {+0.00/3 562 74 0/1000/0}  Kd1 {+0.00/38 4702 7414953 8/984/8}  98.Kc3 {+0.04/3 1487 103 35/965/0}  Rb7 {+0.00/31 2328 4260425 8/984/8} 
99.Rd8+ {+0.00/3 1513 123 1/999/0}  Kc1 {+0.00/33 1640 3131570 8/984/8}  100.Rh8 {+0.00/1 479 64 2/998/0}  Rc7+ {+0.00/42 47963 67533511 8/984/8} 
101.Kb3 {+0.00/6 112725 36775 4/996/0}  Rb7+ {+0.00/57 35721 80733647 8/984/8}  102.Kc3 {+0.00/5 100038 25915 6/993/1}  Rc7+ {+0.00/62 30 203084215 8/984/8} 
103.Kd3 {+0.00/5 96978 29529 3/996/1}  Kb2 {+0.00/51 34287 57592888 8/984/8}  104.Rb8+ {+0.00/5 82995 31244 1/999/0}  Kc1 {+0.00/51 35386 74562954 8/984/8} 
105.Rd8 {+0.00/5 74771 26998 4/996/0}  Rb7 {+0.00/52 33346 72153329 8/984/8}  106.Kc3 {+0.00/5 67260 17897 6/990/4}  Rc7+ {+0.00/50 31417 55855389 8/984/8} 
107.Kb4 {+0.00/5 60805 19541 2/998/0}  Rc2 {+0.00/57 18 139301400 8/984/8}  108.Rh8 {+0.00/5 57038 14501 5/995/0}  Rb2+ {+0.00/53 31591 70364388 8/984/8} 
109.Kc3 {+0.02/5 47139 10531 16/984/0}  Rc2+ {+0.00/56 30821 54681118 8/984/8}  110.Kb3 {+0.01/5 65123 17175 9/990/1}  Rc6 {+0.00/59 31808 70286098 8/984/8} 
111.Rf8 {+0.01/5 39082 11370 10/990/0}  Kd1 {+0.00/59 27688 61535726 7/986/7}  112.Rg8 {+0.01/4 35844 9659 9/991/0}  Rb6+ {+0.00/140 39737 102400873 7/986/7} 
113.Kc3 {+0.00/5 202653 10032028 7/987/6}  Rb5 {+0.00/166 101022 361173029 7/986/7}  114.Rd8+ {+0.00/2 39882 15461350 0/1000/0}  Kc1 {+0.00/245 10 51708 7/986/7} 
115.Rg8 {+0.00/2 18648 6799689 0/1000/0}  Rb1?? {+0.00/245 73 31360 7/986/7}  116.Rg1# {M+1/1 10 17 1000/0/0}
