### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [official-stockfish/Stockfish#4296]
### Describe the issue

[Some return values are not checked](https://github.com/official-stockfish/Stockfish/blob/90cf8e7d2bde9e480aac4b119ce130e09dd2be39/src/thread_win32_osx.h#L52 "Update candidate: Constructor for NativeThread") so far.

### Expected behavior

I would appreciate if a bit more error detection and corresponding exception handling will be performed.

### Steps to reproduce

Please take another look at implementation details.
* pthread_attr_init
* pthread_create

### Operating system

Windows

### Stockfish version

90cf8e7d2bde9e480aac4b119ce130e09dd2be39

**Comment by Sopel97** [comment]
No real issue presented.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by Sopel97** [comment]
Please present a realistic scenario in which any of these calls fail. Otherwise it's like arguing fclose should have the return value checked.

**Comment by elfring** [comment]
:thought_balloon: It is just safer to [handle also “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?

**Comment by Sopel97** [comment]
Writing handling for an exceptional case indicates to the future developers that it can happen. If it cannot happen then it's just code obfuscation.

**Comment by elfring** [comment]
:thought_balloon: How much do code reviewers and software developers care for [advices from secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/ERR00-C.+Adopt+and+implement+a+consistent+and+comprehensive+error-handling+policy "Adopt and implement a consistent and comprehensive error-handling policy")?

**Comment by Sopel97** [comment]
Not much, stockfish is not a security risk.

**Comment by dubslow** [comment]
> Otherwise it's like arguing fclose should have the return value checked.

which is absolutely a true statement

> Not much, stockfish is not a security risk.

that's a bold assertion, one never knows where seemingly-harmless software can find itself

**Comment by XInTheDark** [comment]
> 💭 How much do code reviewers and software developers care for [advices from secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/ERR00-C.+Adopt+and+implement+a+consistent+and+comprehensive+error-handling+policy)?

These guidelines are to ensure that a _system_ is "secure" and "survivable", and that the system can deliver services. Stockfish is only a command-line program, not a system; nor does it need to deliver any services besides playing chess. This issue does not pose a major security risk either. So this issue isn't that urgent right now I guess.

**Comment by noobpwnftw** [comment]
Your system is not "secure" and "survivable" if such trivial thread creations can fail. Go fix those instead.

**Comment by vondele** [comment]
closing this in line with the comments.
