### ISSUE TITLE
changed nnue file format?

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#4300]
### Describe the issue

Some time ago my fork was using nn-13406b1dcbe0.nnue successfully.
Now when I try to load this file, evaluate_nnue.cpp read_parameters returns false.
Has something been changed? No compatibility with the older files?

### Expected behavior

successful load and use of the older nnue file.

### Steps to reproduce

setoption name evalfile value /data/user/0/com.ab.droid.chesspad/files/nnue/nn-13406b1dcbe0.nnue

### Operating system

MacOS

### Stockfish version

c620886181b5c0fb4a0c067b4173143a81819199

**Comment by vondele** [comment]
nn-13406b1dcbe0.nnue is a network from master of 21-09-13, and is not compatible with the current net architecture. We don't have backwards compatibility for old architectures. It is strongly recommended to use the default network with SF.
