### ISSUE TITLE
Test x86-64-modern build fails on Mac OSX 12 for my fork

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#4303]
### Describe the issue

I believe there is some problem related to Apple chip. This build is successful on:
Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Dual-Core Intel Core i5

System Version:	macOS 11.7 (20G817)
  Kernel Version:	Darwin 20.6.0

this build fails on:
Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Chip:	Apple M1

System Version:	macOS 12.0.1 (21A559)
  Kernel Version:	Darwin 21.1.0

### Expected behavior

build should be successful on both systems

### Steps to reproduce

run 
make -j2 ARCH=x86-64-modern build
on both systems

### Anything else?

this build is for my fork https://github.com/ab-chesspad/Stockfish that is synched with the latest official-stockfish
compiler error:
endgame.cpp:46:8: error: unused function 'verify_material' [-Werror,-Wunused-function]
  bool verify_material(const Position& pos, Color c, Value npm, int pawnsCnt) {
       ^
1 error generated.

### Operating system

MacOS

### Stockfish version

ec89560a476e639e1c2f187d097e3e11fad2e178

**Comment by PGG106** [comment]
in a non debug version of the current stockfish repo the ifndef at line 47 of endgame.cpp will not be triggered and the function will not be defined, you removed the preprocessor instruction and have it so that verify_material is always declared, the error you get is because the function is declared but unused because you also deleted all the asserts that used it, in short this is an error you introduced and that isn't present in vanilla SF, possible solutions include removing the method from your fork if you don't plan on using it or restoring the ifndef that was present before

**Comment by PGG106** [comment]
relevant [line]( https://github.com/official-stockfish/Stockfish/compare/master...ab-chesspad:Stockfish:master#diff-e8b060968a397044202540c611939e4c3c0df2963d1ffb5ac32e42c520e907eeL47) that shows what you did to make so that the function is always defined

**Comment by ab-chesspad** [comment]
thank you

**Comment by XInTheDark** [comment]
> ### Describe the issue
> I believe there is some problem related to Apple chip. This build is successful on: Model Name: MacBook Air Model Identifier: MacBookAir6,2 Processor Name: Dual-Core Intel Core i5
> 
> System Version: macOS 11.7 (20G817) Kernel Version: Darwin 20.6.0
> 
> this build fails on: Model Name: MacBook Air Model Identifier: MacBookAir10,1 Chip: Apple M1
> 
> System Version: macOS 12.0.1 (21A559) Kernel Version: Darwin 21.1.0
> 
> ### Expected behavior
> build should be successful on both systems
> 
> ### Steps to reproduce
> run make -j2 ARCH=x86-64-modern build on both systems
> 
> ### Anything else?
> this build is for my fork https://github.com/ab-chesspad/Stockfish that is synched with the latest official-stockfish compiler error: endgame.cpp:46:8: error: unused function 'verify_material' [-Werror,-Wunused-function] bool verify_material(const Position& pos, Color c, Value npm, int pawnsCnt) { ^ 1 error generated.
> 
> ### Operating system
> MacOS
> 
> ### Stockfish version
> [ec89560](https://github.com/official-stockfish/Stockfish/commit/ec89560a476e639e1c2f187d097e3e11fad2e178)

If you're using the M1 chip, why don't you use the `apple-silicon` arch?

e.g. 
```
make build ARCH=apple-silicon
```

**Comment by ab-chesspad** [comment]
I was trying to reproduce the error on the testbed, build for MacOS 12, but my Intel-chip Mac only upgrades to 11.7.
So it raises the question, how v. 12 was installed on the machine with Intel chip?

**Comment by XInTheDark** [comment]
> I was trying to reproduce the error on the testbed, build for MacOS 12, but my Intel-chip Mac only upgrades to 11.7.
> So it raises the question, how v. 12 was installed on the machine with Intel chip?

Your intel Mac is too old.

macOS Monterey (12) does support Intel Macs released recently.
