### ISSUE TITLE
Just a thought about speed...

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#4310]
### Describe the issue

I am wondering which is the most called part of code called and I was thinking if it might be useful to ptimize it in pure assembly (perhaps starting with X86_64 and ARM32/64.
![output](https://user-images.githubusercontent.com/855176/209672776-b62f8aac-13c5-4347-bf01-4816fc9aae24.svg)
From this graph the most called functions obviously are the search and evaluate functions.
Did anyone experiment on this?

### Expected behavior

.

### Steps to reproduce

```
sudo apt install valgrind
pip install gprof2dot


cd Stockfish/src
rm callgrind.out.*
valgrind --tool=callgrind ./stockfish bench 16 2 10 default depth &>/dev/null
gprof2dot -f callgrind callgrind.out.* | dot -Tsvg -o output.svg
```

### Operating system

All

### Stockfish version

any

**Comment by vondele** [comment]
Thanks for the suggestion, obviously Stockfish speed has been considered in detail. We avoid assembly if possible. However, some parts have intrinsic-based optimization. Using valgrind with callgrind is quite nice as a tool though. 

For best results consider compiling SF as:
`CXXFLAGS="-fno-inline-functions" make -j ARCH=x86-64-avx2 debug=yes lto=no profile-build`
and run data collections as:
`valgrind --tool=callgrind ./stockfish bench 16 1 13 default depth NNUE &>/dev/null`

For me this yields

![output](https://user-images.githubusercontent.com/4202567/210166496-ce29b938-4ead-4e22-9fc4-abf2e35d7b34.svg)
