### ISSUE TITLE
to_sq(MOVE_NULL) used in search

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#4333]
### Describe the issue

On lines 609 and 1505 in search.spp we call to_sq((ss-1)->currentMove); when sometimes (ss-1)->currentMove is MOVE_NULL.  This actually returns a "valid" square SQ_B1 which we then proceed to use as if everything was ok.  I made a couple of attempts to fix it:
https://tests.stockfishchess.org/tests/view/63b5208dadb7a412a0eb5aea
https://tests.stockfishchess.org/tests/view/63b67d06acc7bf149841729e
but both failed.  Some additional discussion here:
https://github.com/mstembera/Stockfish/commit/d370cbdcf90d05ef8fd4c087683a344c2061002a
I hope someone with a better understanding of search can write a patch that fixes it properly.

### Expected behavior

No calls to to_sq(MOVE_NULL).

### Steps to reproduce

Run SF.

### Operating system

All

### Stockfish version

9fe9ff00823a0d1e989fcfc45410396e94345987

**Comment by Vizvezdenec** [comment]
https://tests.stockfishchess.org/tests/view/6405e3162644b62c33937b9d
Trying this type of fix, let me see how it goes...

**Comment by dav1312** [comment]
> [tests.stockfishchess.org/tests/view/6405e3162644b62c33937b9d](https://tests.stockfishchess.org/tests/view/6405e3162644b62c33937b9d) Trying this type of fix, let me see how it goes...

Passed non-regression
