### ISSUE TITLE
libstdc++-6.dll problem

### ISSUE THREAD

**Issue by LovelyChess** [official-stockfish/Stockfish#4364]
### Describe the issue

I want to build Stockfish from source... After building Stockfish, this error is displayed.

`The code execution cannot proceed because libstdc++-6.dll was not found`

### Expected behavior

_No description provided._

### Steps to reproduce

```
cd src
make help
make build ARCH=x86-64-modern
```

### Operating system

Windows 8

### Stockfish version

Stockfish 14

**Comment by Craftyawesome** [comment]
Yes, this happened with older SF versions. Either compile the latest version, copy the dlls that it asks for and put it in the same directory, or maybe try using the current makefile.

**Comment by LovelyChess** [comment]
I added `COMP=mingw` to solve this problem, but the file size is bigger than default compiled Stockfish, 
How can I compile with small size like default?

**Comment by MinetaS** [comment]
The only supported compilers on Windows are gcc (`COMP=mingw`) and clang (`COMP=clang`).
Unlike Windows, Linux already has `PATH` environment variable so that libraries are linked at default.
Thus setting `COMP=gcc` implies that you're on Linux and won't import default libc data/functions.

https://github.com/official-stockfish/Stockfish/blob/e4e61cd9cc953e6bc17070da84639d53b7514709/src/Makefile#L393-L395

This is why file size is usually larger on Windows.

You can still reduce size of the executable by adding `-DNNUE_EMBEDDING_OFF` to `CXXFLAGS`.
But then you have to provide the default network file manually to use NNUE.

**Comment by LovelyChess** [comment]
@MinetaS Thanks but problem not solved ...

I compiled via `COMP=mingw` & my compiled size is about 50MB but default compiled Stockfish is about 47MB 

How do I compile with small size like default?

**Comment by MinetaS** [comment]
I said "default" gcc is a wrong option on Windows and should not be used.

Try this:
```
make build ARCH=x86-64-modern COMP=mingw ENV_CXXFLAGS="-DNNUE_EMBEDDING_OFF"
```

The result executable is sized around 3MB.

**Comment by LovelyChess** [comment]
> The result executable is sized around 3MB.

NNUE is about 47MB + 3MB = 50MB

But `stockfish_14_x64.exe` is about 47MB. I downloaded from [stockfishchess.org](https://stockfishchess.org/download/)

**Comment by LovelyChess** [comment]
@MinetaS Do you understand what I mean?

**Comment by MinetaS** [comment]
Sorry, I misunderstood.

It seems that the default binary is stripped. I tried `strip stockfish.exe` and file size is now 48MB.
Slightly larger than stockfish_14_x64.exe, but this should be an answer.

**Comment by LovelyChess** [comment]
Thanks .... This may be an answer, but I tried `strip stockfish.exe` for `COMP=gcc` and file size is now 46MB.

I know `COMP=gcc` is not an option on Windows, but I believe for `COMP=mingw` file size should be 47MB with `strip`

**Comment by Craftyawesome** [comment]
AFAIK official releases are profile-build and not build.
But you are unlikely to get an exact perfect identical file. There are multiple valid ways to convert the C++ to machine code.

**Comment by vondele** [comment]
The original problem has been addressed, this kind of errors is almost always a problem with the setup of the toolchain, not issues of stockfish itself.
