### ISSUE TITLE
In TB score reported without TB

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#4413]
### Describe the issue

With this position `position fen 8/8/8/5N2/8/p7/8/2NK3k w - - 0 1` and without TB, SF eventually produces:

`info depth 54 seldepth 101 multipv 1 score cp 20000 nodes 61933448 nps 2412302 hashfull 1000 tbhits 0 time 25674 pv c1a2 ...`

i.e. a score that we currently use for being in TB.

The origin is code in `Value value_from_tt(Value v, int ply, int r50c)` where very deep mates (beyond the 50 move rule) get returned as `VALUE_MATE_IN_MAX_PLY - 1` i.e. our TB score at root.

### Expected behavior

probably a different evaluation. The question is if returning instead `VALUE_TB_WIN_IN_MAX_PLY - 1` makes sense. If this affects mate finding, for example in the presence of TB, and if TB scores might need consideration as well.

### Steps to reproduce

```
position fen 8/8/8/5N2/8/p7/8/2NK3k w - - 0 1
go infinite
```

### Anything else?

see also https://discord.com/channels/435943710472011776/813919952713154590/1079472900865794170 

### Operating system

All

### Stockfish version

master

**Comment by KomodoChess** [comment]
Not an issue . This is due to https://github.com/official-stockfish/Stockfish/pull/4401 

```diff
---  int scale = 1076 + 96 * pos.non_pawn_material() / 5120;
+++  int scale = 1001 + 5 * pos.count<PAWN>() + 61 * pos.non_pawn_material() / 4096;
```

Thanks @linrock  , **[Introduce nnue pawn scaling with lower lazy thresholds](https://github.com/official-stockfish/Stockfish/pull/4401)** make Stockfish very strong , 

This is the final position that White is clearly winning
```
8/8/8/8/8/pk1K1N2/N7/8 b - - 53 27
go infinite
```
