### ISSUE TITLE
Adding CITATION.cff to repo

### ISSUE THREAD

**Issue by jamesbraza** [official-stockfish/Stockfish#4419]
### Describe the issue

Can you add a `CITATION.cff` file to the repo root, to make it easy to cite Stockfish, for academic papers? 🤓 

You can read about [`CITATION.cff` here](https://citation-file-format.github.io/) and use https://bit.ly/cffinit to easily generate a `CITATION.cff` file.

Simply adding it to the repo root adds this menu to the right panel:

![image](https://user-images.githubusercontent.com/8990777/222656267-b6a4bbd0-92ad-4549-80d6-d1d64f0f1c66.png)

### Expected behavior

n/a

### Steps to reproduce

n/a

### Anything else?

n/a

### Operating system

All

### Stockfish version

n/a

**Comment by vdbergh** [comment]
To see if this is useful, I was wondering in what context one would refer to Stockfish in a publication. It could be something like this
```
All our experiments were performed using the very strong chess engine "Stockfish" [5].
```
So yes, it seems to reasonable to have a standard way of citing Stockfish, even though Stockfish itself is not a publication (not in a standard sense anyway).

**Comment by jamesbraza** [comment]
Yeah you're right, simply to have a citation corresponding with the Stockfish engine's first mention in the paper.

 I am doing some reinforcement learning, and want to use Stockfish (specifying Elo) as a benchmark.  That way, I can get a rough idea of my model's Elo, as a function of training and also model architecture(s).

In the 2017 paper [Who is the Master?](https://content.iospress.com/articles/icga-journal/icg0012), they used Stockfish 6, but never properly cited Stockfish imo.  Directly integrating with `CITATION.cff` makes citing Stockfish easy.

**Comment by vondele** [comment]
I think that's a reasonable thing to do. I have added a first try, comments welcome.
