### ISSUE TITLE
Skill Level 1 to 19 are all the same thing

### ISSUE THREAD

**Issue by sana2024** [official-stockfish/Stockfish#4431]
### Describe the issue

i'm working on using stockfish as a AI in my chess game where players have the option to choose which level they are at before starting, beginner, intermediate and advanced and for that i tried to randomly pick a skill from 1 to 3 for beginner and 10 o 12 for intermediate and 18 to 20 for advanced, but after testing and testing the only to skill level that are not the same are 1 and 20 everything else is the same ????

for more detail, i have created a space in huggingface for each skill level, and by using chess library i generate a fen based on that skill and then i used the URL of the fen in my unity project if that makes sense

any help is much appreciated.

### Expected behavior

skill level 1 to 19 producing different fen string 

### Steps to reproduce

improve the skill levels 

### Operating system

All

### Stockfish version

stockfish version 14

**Comment by RogerThiede** [comment]
What are your steps to reproduce?
When you follow those steps, what is the expected output and what is the observed output?

**Comment by tonyzhigit** [comment]
It still isn't solved in Stockfish 16.
### How to reproduce
1. Open engine,
2. Type `setoption name Skill Level value 0`,
3. Open chess GUI

*Expected result*: Playing the worst calculated move possible.
*Observed result*: Playing as same as default settings(20).
### Operating System
Windows 11 21H2 Build 20000.2124
### Installed Version
Stockfish 16 AVX2

**Comment by Sopel97** [comment]
see `UCI_LimitStrength` at https://github.com/official-stockfish/Stockfish/wiki/Commands#setoption

**Comment by Craftyawesome** [comment]
> 1. Open engine,
> 2. Type `setoption name Skill Level value 0`,
> 3. Open chess GUI

Options aren't saved across processes like that. Set skill level using the GUI, or continue typing in uci commands without restarting SF.
