### ISSUE TITLE
False mate in 1 announcement

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#4456]
### Describe the issue

In this game @ TCEC https://tcec-chess.com/#div=p&game=53&season=24 SF reported M1 on its last move which is clearly wrong.

### Expected behavior

Report correct score.

### Steps to reproduce

See last SF move in game https://tcec-chess.com/#div=p&game=53&season=24

### Operating system

All

### Stockfish version

dev-20230308-39da50ed

**Comment by Craftyawesome** [comment]
Gui is converting TB scores to mate scores. See https://discord.com/channels/435943710472011776/735707599353151579/1085244800468525089

**Comment by vondele** [comment]
yes, not an SF issue, rather a problem with the TCEC cutechess version. The logs show the right output from SF.

**Comment by mstembera** [comment]
Got it.  Thanks.
