### ISSUE TITLE
perft does not show elapsed time

### ISSUE THREAD

**Issue by octopus-prime** [official-stockfish/Stockfish#4480]
### Describe the issue

When running perft the output is, e.g.
`Nodes searched: 3195901860`

No elapsed time...

### Expected behavior

The output should show elapsed time too.

### Steps to reproduce

`go perft 7`

### Operating system

All

### Stockfish version

Stockfish 15.1

**Comment by octopus-prime** [comment]
The performance (in N/s) would be nice too!

**Comment by Disservin** [comment]
This is not an issue and it already exists. `.\stockfish.exe bench 0 1 7 current perft`

**Comment by octopus-prime** [comment]
Thanks!

**Comment by octopus-prime** [comment]
Very impressive speed! Wow!!
