### ISSUE TITLE
gcc 9 bug

### ISSUE THREAD

**Issue by maximmasiutin** [official-stockfish/Stockfish#4532]
### Describe the issue

gcc 9 is used in the Github CI pipeline to check pull requests.

There is a bug in gcc 9 reported at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90129 that was fixed in later version but also affects code at https://github.com/official-stockfish/Stockfish/actions/runs/4714157796/jobs/8360329017?pr=4528 

nnue/../nnue/layers/simd.h: In function ‘Stockfish::Simd::m512_combine_m128x4(long long __vector(2), long long __vector(2), long long __vector(2), long long __vector(2))’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h:2097:1: error: inlining failed in call to always_inline ‘_mm512_insertf32x8(float __vector(16), float __vector(8), int)’: target specific option mismatch
 2097 | _mm512_insertf32x8 (__m512 __A, __m256 __B, const int __imm)
      | ^~~~~~~~~~~~~~~~~~
In file included from nnue/../nnue/layers/affine_transform.h:28,
                 from nnue/../nnue/nnue_architecture.h:30,
                 from nnue/../nnue/nnue_accumulator.h:24,
                 from nnue/../position.h:32,
                 from nnue/evaluate_nnue.cpp:29:

This bug does not happen with clang or later gcc. How would you precommend to proceed? There are fistest workers using very old version of gcc, but at fishtest, avx512 is diabled.

### Expected behavior

Compile without error as later gcc do or clang do.

### Steps to reproduce

Try using _mm512_insertf32x8 intrinsic with -mavx512dq gcc option.

### Operating system

Linux

### Stockfish version

Stockfish dev

P.S. I refer to https://github.com/official-stockfish/Stockfish/pull/4528

**Comment by Disservin** [comment]
This shouldn’t be issue since it’s only an issue of your other pr imo.

**Comment by maximmasiutin** [comment]
This intrinsic makes Elo gain. Should I put IFDEF GCC? Or abandon the PR? But it makes Elo gain and speedup.

**Comment by maximmasiutin** [comment]
This intrinsic allows to make one 512-bit memory load and then split to four 128-bit registers instead of four 128-bit memory loads and vice versa - combine four 128-bit registers to one 512-bit registers and make one 512-bit memory store. This approach is faster on AMD with 256 memory load/store units, and even faster on Intel with 512-bit memory load/store units. 

If we can avoid this gcc 9 bug either by IFDEF GCC (to make this approach work only under GCC 10+ or clang) we can make further speedups on different places of Stockfish.

**Comment by Disservin** [comment]
It’s part of the other pr. This is currently not an issue in stockfish. It’s only an issue in your pr, where you should propose a solution

**Comment by dubslow** [comment]
Tbh I'm with maxim here. If a compiler bug can cause PRs to get false CI results, that is a problem for the project as a whole, not merely any such PR.

**Comment by Disservin** [comment]
There are probably many more compiler bugs out there, should we create an issue for all possible ones and fix what we don’t have currently ?

**Comment by bftjoe** [comment]
Maybe update CI to not use an ancient version of gcc?

**Comment by vondele** [comment]
any compiler has plenty of code generation bugs. gcc 9 is still pretty widely used, it is good to have it part of the CI. It would be an issue if we run into the bug with the master version of SF. If there is a bug in a widely used compiler we can have a workaround for that in the code, there are other examples in SF that have such workarounds. Of course, the fewer such workarounds needed, the better.

see types.h near line 60.

**Comment by dubslow** [comment]
@Disservin come now dont be silly, only compiler bugs which are directly proven to cause issues, such as this case.

vondele has the right of it. Do a standard cost-benefit analysis. In this case, the PR's purported claim of few-or-several-percent speedup on certain arches may well be worth the cost of either adding a workaround or removing the version from the CI.

**Comment by Disservin** [comment]
@dubslow The proposed PR introduces such a gcc bug, it currently doesnt exist to my understanding in master.  
So I dont see why there should be an issue for a compiler bug for code that currently doesnt exist in master.  
It's the PR's job to come up with a solution. 

And simply removing the used version aint it, as vondele said.

**Comment by TheBlackPlague** [comment]
> @dubslow The proposed PR introduces such a gcc bug, it currently doesnt exist to my understanding in master. So I dont see why there should be an issue for a compiler bug for code that currently doesnt exist in master. It's the PR's job to come up with a solution.
> 
> And simply removing the used version aint it, as vondele said.

With Disservin here. The PR should include the solution. It can edit CIs as well. ;)
