### ISSUE TITLE
Invalid benchmark parameters are not reported as invalid

### ISSUE THREAD

**Issue by maximmasiutin** [official-stockfish/Stockfish#4543]
### Describe the issue

I can use the following parameters but Stockfish will not report them as invalid:

```
Stockfish.exe bench 16 1 2000 file.fen horsie dorsie
```

### Expected behavior

It should report that a parameter is invalid and exit with an error code.

Here, the parameters `horsie` as a limit type and `dorsie` as eval type are invalid, but Stockfish will run with these parameters with unexpected results.

### Steps to reproduce

Run with invalid parameters, such as:

```
Stockfish.exe bench 16 1 2000 file.fen horsie dorsie
```

The file file.fen should contain a valid position, for example:
```
nnnnknnn/8/8/8/8/8/8/NNNNKNNN w - - 0 1
```

### Anything else?

Fixed by #4544

### Operating system

All

### Stockfish version

Stockfish 15.1

**Comment by Disservin** [comment]
Since @snicolet closed the related pr, I will close this as not planned. This kind of validation is generally not done (we also dont really validate uci parameters).
