### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DaniSpringer** [official-stockfish/Stockfish#4549]
### Describe the issue

Putting aside how ludicrous this all is...

Setting the PGN to:

```
[Variant "From Position"]
[FEN "rRrRrRRK/RrRrrRrR/rrRrRrRR/rRrRrRrr/RRrRrRrR/rrRrRrRr/rRrRrRrR/krrRRrRr w - - 0 1"]
```

Then turning analysis ON
Then making a move
Causes the app to immediately crash, every time.

### Expected behavior

don't crash

### Steps to reproduce

see above

### Anything else?

macOS Ventura 13.3.1 (22E261)
Chip: Apple M1
Model: 2020, MacBook Air
RAM: 8 GB
Stockfish app: Version 2.3.5 (39)
Stockfish app settings:
Threads: 2
Hash MB: 512
Skill level: 20

### Operating system

MacOS

### Stockfish version

2.3.5 (39)

**Comment by vondele** [comment]
https://github.com/official-stockfish/Stockfish/wiki/Stockfish-FAQ#stockfish-crashed

**Comment by Craftyawesome** [comment]
NNUE cannot handle more than 32 pieces at all. Turn it off and it will probably work (although IIRC there are some illegal positions that will still crash)

**Comment by Disservin** [comment]
> Putting aside how ludicrous this all is...

What is this supposed to mean?!

also:
A) you opened an issue about a third party app, not our problem…
B) see the link posted above

**Comment by DaniSpringer** [comment]
> NNUE cannot handle more than 32 pieces at all. Turn it off and it will probably work (although IIRC there are some illegal positions that will still crash)

Ah, so basically it crashes because it's a "Fairy" position, and not reachable in standard chess? That makes sense. Thank you!

**Comment by dubslow** [comment]
I fully agree that it is completely ludicrous. Crashing is never acceptable, no matter the complaints about how difficult error validation may or may not be, or how crappy UCI is. Crashing is simply rude, and worse, potentially abusable. (Admittedly a chess engine isn't high on the list of attack vectors, but it's the principle of the thing.)

Crashing is not acceptable behavior, bar none, no ifs ands or buts. And yet here we are...

**Comment by DaniSpringer** [comment]
> No the stockfish app in the App Store is developed by an individual person

Ah, thanks!

**Comment by DaniSpringer** [comment]
> I fully agree that it is completely ludicrous. Crashing is never acceptable, no matter the complaints about how difficult error validation may or may not be, or how crappy UCI is. Crashing is simply rude, and worse, potentially abusable. (Admittedly a chess engine isn't high on the list of attack vectors, but it's the principle of the thing.)
> 
> Crashing is not acceptable behavior, bar none, no ifs ands or buts. And yet here we are...

**Ohhhhhh, now I get what happened.** @Disservin 

My original comment might be interpreted so say "crashing is ludicrous".

No! That is not at all what I meant.

What I did mean is: putting aside how ludicrous it is of someone to want to analyze such a position.

Ah, misunderstandings... Don't we all love when they happen...

**Comment by dubslow** [comment]
Oh. lol. well, i still find this crashing thing to be ridiculous, but yes i'm willing to agree that your OP position is also a bit ludicrous :laughing:

**Comment by dav1312** [comment]
Since this wasn't posted yet, this is the repo of the mac app: https://github.com/daylen/stockfish-mac
