### ISSUE TITLE
Incorrect fen printed

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#4561]
### Describe the issue

ep field of fen printed is incorrect.

### Expected behavior

correct fen printed

### Steps to reproduce

```
$ ./stockfish
Stockfish dev-20230507-65e21505 by the Stockfish developers (see AUTHORS file)
position startpos moves e2e4
d

 +---+---+---+---+---+---+---+---+
 | r | n | b | q | k | b | n | r | 8
 +---+---+---+---+---+---+---+---+
 | p | p | p | p | p | p | p | p | 7
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 6
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 5
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | P |   |   |   | 4
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 3
 +---+---+---+---+---+---+---+---+
 | P | P | P | P |   | P | P | P | 2
 +---+---+---+---+---+---+---+---+
 | R | N | B | Q | K | B | N | R | 1
 +---+---+---+---+---+---+---+---+
   a   b   c   d   e   f   g   h

Fen: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
Key: B46022469E3DD31B
Checkers: 


```

### Operating system

All

### Stockfish version

master

**Comment by dav1312** [comment]
I thought this was the expected behavior, doing just like X-FEN does and don't show the ep field if there is no ep possible in that position.
```
Stockfish dev-20230507-65e21505 by the Stockfish developers (see AUTHORS file)
position startpos moves e2e4 d7d5 e4e5 f7f5
d

 +---+---+---+---+---+---+---+---+
 | r | n | b | q | k | b | n | r | 8
 +---+---+---+---+---+---+---+---+
 | p | p | p |   | p |   | p | p | 7
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 6
 +---+---+---+---+---+---+---+---+
 |   |   |   | p | P | p |   |   | 5
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 4
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 3
 +---+---+---+---+---+---+---+---+
 | P | P | P | P |   | P | P | P | 2
 +---+---+---+---+---+---+---+---+
 | R | N | B | Q | K | B | N | R | 1
 +---+---+---+---+---+---+---+---+
   a   b   c   d   e   f   g   h

Fen: rnbqkbnr/ppp1p1pp/8/3pPp2/8/8/PPPP1PPP/RNBQKBNR w KQkq f6 0 3
Key: ADE7FE481DD0D8FA
Checkers:
```

**Comment by vondele** [comment]
ah, right....

**Comment by vondele** [comment]
(confused by a GUI outputting a different fen).

**Comment by Disservin** [comment]
I think that was the old rule for fen annotations and the new one is here (who even makes these idk?) <https://github.com/fsmosca/PGN-Standard/blob/61a82dab3ff62d79dea82c15a8cc773f80f3a91e/PGN-Standard.txt#LL2101C1-L2101C1> states: 
> An en passant target square is given if and only if the last move was a pawn
advance of two squares and the active color has a legal en passant capture
move.

citing from wikipedia
> old version of the standard is the one most commonly used

**Comment by dubslow** [comment]
en passant is basically "do whatever so long as you never forget it when a legal ep capture exists", and probably there are at least 4 different variations of that in the wild (including the two most common standards that diss mentions)
