### ISSUE TITLE
`gcc-profile-use` reduce `perft` but increase `bench` 

### ISSUE THREAD

**Issue by penguingim1** [official-stockfish/Stockfish#4569]
### Describe the issue

_After I compiled Stockfish via_ `profile-build`_, I found that perft speed is too low._

_It happens due to the_  `EXTRACXXFLAGS='-fprofile-use=profdir -fno-peel-loops -fno-tracer' ` _in gcc-profile-use_.

### Expected behavior

**`profile-build`  perft speed  ⩾ `build` perft speed**

### Steps to reproduce

`bench 0 1 7 current perft`

### Operating system

All

### Stockfish version

All

**Comment by Sopel97** [comment]
This is not unexpected. `perft` is not profiled as it's merely a debugging device. Not an issue.

**Comment by bftjoe** [comment]
Are you an alt account of someone who was already banned here? Why are you pretending to be GM Andrew Tang?

**Comment by penguingim1** [comment]
This is my speed test before & after `gcc-profile-use`


**Bench  : 1587920
Perft    : 203840655**

**Bench  : 1698933
Perft    : 192540644**

**Comment by penguingim1** [comment]
I close this issue because it doesn't matter to anyone
