### ISSUE TITLE
Stockfish didn't show in chess ranking 

### ISSUE THREAD

**Issue by penguingim1** [official-stockfish/Stockfish#4570]
### Describe the issue

Maybe this is not technical issue but I saw CCRL ranking list today and I couldn't find Stockfish in the main list.

https://ccrl.chessdom.com/ccrl/4040/index.html

![alt text](https://api.pikwy.com/web/646331739c6100003c43cbbe.jpg)

### Expected behavior

Stockfish should be first chess ranking.

### Steps to reproduce

Open browser and go to this URL https://ccrl.chessdom.com/ccrl/4040/index.html 

### Operating system

All

### Stockfish version

Stockfish 15.1

**Comment by penguingim1** [comment]
I close this thread now but we need to know that why stockfish rating dropped. 

Also I congratulate to @amchess  creators of ShashChess.

**Comment by cj5716** [comment]
> I close this thread now but we need to know that why stockfish rating dropped.
@penguingim1, this is due to Shashchess being based on latest dev of SF, while the Stockfish 15.1 on CCRL is not latest dev and hence weaker.

**Comment by penguingim1** [comment]
@cj5716 Thank you very much.

I though this is due to **Alexander Shashin's theory**.

But why in blitz rating stockfish 15.1 is rank number 1 ?

https://ccrl.chessdom.com/ccrl/404/

**Comment by SzotsGabor** [comment]
I'm not sure I understand what you want from me. In my opinion you have received satisfactory replies to your question. You might also look at this thread: https://talkchess.com/forum3/viewtopic.php?f=2&t=82044&sid=44a1d212f48a62594b15da617914c470

Also, you can see that the probability of ShashChess being stronger is 64 %. The difference is only 6 Elo points and look at the error margins.
