### ISSUE TITLE
Stockfish engine with nn-fab1ed1ddcfb.nnue failed to start with Fritz 18 interface 25-05-2023

### ISSUE THREAD

**Issue by shadizahran** [official-stockfish/Stockfish#4588]
### Describe the issue

when using Stockfish  engine releases with NNUE nn-fab1ed1ddcfb.nnue on Fritz 18 interface the Stockfish engine fail to start with the below error message 

----------------------------------------
"Stockfish dev-20230525-cedd73f4" caused an exception.
This is a problem in the engine.

Win 10.0 x64
3983 MB
Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
N=1/P=1/C=2/L=4/G=1
Intel(R) HD Graphics 4000
Intel(R) HD Graphics 4000
Intel(R) HD Graphics 4000
-----------------------------------------

**Comment by locutus2** [comment]
This is a new net which was tested at 2023-05-25 here https://tests.stockfishchess.org/tests/view/646ee89268661bfd9843239f

As you see in the code diff this net has also different architecture which does not run with current SF.

`constexpr IndexType TransformedFeatureDimensions = 1024;`
changed to
`constexpr IndexType TransformedFeatureDimensions = 1536;`

So the size of the first hidden layer has been increased.

**Comment by vondele** [comment]
So not an SF issue. Only the default net is guaranteed to work with the engine. Otherwise it's expert use only... At their own risk.

**Comment by shadizahran** [comment]
I hope SF get updated to be able to use that type of net architecture

thanks dears
