### ISSUE TITLE
SF crash

### ISSUE THREAD

**Issue by threeCheck** [official-stockfish/Stockfish#4621]
### Describe the issue

![woochess](https://github.com/official-stockfish/Stockfish/assets/136608638/e628a6f9-e80c-4c19-8524-a1b6ebf700f2)

### Expected behavior

don't crash

### Steps to reproduce

```
position fen 2r3rk/6p1/3pPpqp/pp1N1P2/3b1P1R/Pp3Q1K/7P/8 w - - 0 42
go depth 33
```

### Operating system

All

### Stockfish version

Latest

**Comment by vondele** [comment]
No crashes here. Can you provide more information. 
1) the version: `./stockfish --version`
2) if this only happens for this fen.

**Comment by threeCheck** [comment]
I use Stockfish 15.

Stockfish 15 by the Stockfish developers (see AUTHORS file)
position fen 2r3rk/6p1/3pPpqp/pp1N1P2/3b1P1R/Pp3Q1K/7P/8 w - - 0 42
go depth 33
info string NNUE evaluation using nn-6877cd24400e.nnue enabled

**Comment by vondele** [comment]
Ah, that position in the king's gambit line was fixed shortly after.
