### ISSUE TITLE
build with gcc on mac hits abs error

### ISSUE THREAD

**Issue by atalkingegg** [official-stockfish/Stockfish#4707]
### Describe the issue

The error: 
nnue/evaluate_nnue.cpp:254:26: error: call to 'abs' is ambiguous
    const double pawns = std::abs(0.01 * UCI::to_cp(v));

The fix:
--- nnue/evaluate_nnue.cpp.orig	2023-07-23 18:29:52.000000000 -0700
+++ nnue/evaluate_nnue.cpp	2023-07-23 18:33:52.000000000 -0700
@@ -24,6 +24,7 @@
 #include <set>
 #include <sstream>
 #include <string_view>
+#include <cmath>
 
 #include "../evaluate.h"
 #include "../position.h"
@@ -251,7 +252,7 @@
 
   // format_cp_aligned_dot() converts a Value into pawns, always keeping two decimals.
   static void format_cp_aligned_dot(Value v, std::stringstream &stream) {
-    const double pawns = std::abs(0.01 * UCI::to_cp(v));
+    const double pawns = std::abs(0.01 * static_cast<double>(UCI::to_cp(v)));
 
     stream << (v < 0 ? '-' : v > 0 ? '+' : ' ')
            << std::setiosflags(std::ios::fixed)

### Expected behavior

stockfish builds.

### Steps to reproduce

cd stockfish/src
make build ARCH=x86-64-sse41-popcnt

MacOS X 10.13.6, XCode 10.1, gcc = "Apple LLVM version 10.0.0 (clang-1000.11.45.5)", stockfish latest git pull

commit 76e1e8fd39a08c0586259a76c880c3267cb85f62

### Operating system

MacOS

### Stockfish version

Stockfish origin/master

**Comment by UniQP** [comment]
1. Can you share the compile command as well (so we know the used compiler flags)?
2. There seems to be some code missing in your proposed changes. Can you surround the code by single (or triple) backticks?
3. Does adding a `#include <cstdlib>` in `nnue/evaluate_nnue.cpp` fixes the error?
4. Independent of the error: Are you using x86-based or arm-based hardware? In latter case, you should consider using a different architecture (`ARCH=apple-silicon`).

**Comment by snicolet** [comment]
@atalkingegg 
Thanks for the report!

Does it remove the compile error if you change line 254 of evaluate_nnue.cpp to the following?
```
    const double pawns = std::abs(double(0.01) * UCI::to_cp(v));
```

**Comment by atalkingegg** [comment]
For some reason the original post removed the important part of the patch, include cmath with the appropriate cpp punctuation around it.
I pulled that include out, and replaced 254 with snicolet's line, and no it still gets that original error.
I then added the include cstdlib line that UniQP suggested, and it still has the same error.
To UniQP's question, "make build ARCH=x86-64-sse41-popcnt", and yes it's an intel based mac.
It also works with snicolet's version const double pawns line and the original version include cmath (not including cstdlib)

Hopefully this all gets through the filter and is understandable.
Thanks!

**Comment by atalkingegg** [comment]
I just tried the original version of line 254, and only the new include cmath, and it also works. That would be the minimal fix for this issue.

**Comment by UniQP** [comment]
I would still be interested in the compiler command for `nnue/evaluate_nnue.cpp` as I could not reproduce the problem.

**Comment by snicolet** [comment]
> I just tried the original version of line 254, and only the new include cmath, and it also works. That would be the minimal fix for this issue.

If you have a github account, could you open a pull request with this minimal fix? thanks :-)

**Comment by snicolet** [comment]
@atalkingegg Can you confirm the 3c0e86a91e48baea273306e45fb6cf13a59373cf fixed the issue for your compilation problem? :-)
