### ISSUE TITLE
How does ELO relate to Skill Level?

### ISSUE THREAD

**Issue by arikanev** [official-stockfish/Stockfish#4717]
### Describe the issue

I am wondering how ELO directly relates to the Skill level. I noticed that setting an ELO of 4000 gives considerably weaker results than a skill level of 20. Is there a function that describes their relationship to one another?

### Expected behavior

Setting ELO to 4000 gives weaker plays than setting Skill to 20.

### Steps to reproduce

stockfish.set_skill_level(20)
vs
stockfish.set_elo_rating(4000)

stockfish.get_best_move() is better for set_skill_level(20) than set_elo_rating(4000)

### Operating system

All

### Stockfish version

Stockfish 14

**Comment by Disservin** [comment]
Hi,

there's actually no difference between setting it to 4000 and 20. They get internally converted to the same skill level. The elo was last adjusted using the Chess Engine [Stash](https://github.com/mhouppin/stash-bot). 

UCI Elo will be converted using the function implemented here https://github.com/vondele/Stockfish/blob/master/src/search.cpp#L99.

See:
https://github.com/vondele/Stockfish/commit/a08b8d4e9711c20acedbfe17d618c3c384b339ec

**Comment by piquan** [comment]
The Elo -> skill conversion function has moved.  In case somebody else comes looking, here's a permalink to the function, as it stands as of this writing.

https://github.com/vondele/Stockfish/blob/b55217fd02d8e5bc0754e5f27bc84df7b01479a6/src/search.h#L184
