### ISSUE TITLE
No Stockfish builds on the releases page

### ISSUE THREAD

**Issue by Coolchessguykevin** [official-stockfish/Stockfish#4784]
### Describe the issue

Dear developers,

There are no assets builds in the latest developer Stockfish release (https://github.com/official-stockfish/Stockfish/releases). Please correct.

Regards, Ivan.

### Expected behavior

Stockfish builds on the pre-releases page to be appear.

### Steps to reproduce

https://github.com/official-stockfish/Stockfish/releases has no assets builds.

### Anything else?

No.

### Operating system

All

### Stockfish version

Stockfish dev-20230911-3f7fb5ac

**Comment by vondele** [comment]
we had an issue in the CI, they are being regenerated right now.
