### ISSUE TITLE
Default Posted versions on stockfishchess.org

### ISSUE THREAD

**Issue by mjdomeik** [official-stockfish/Stockfish#4831]
### Describe the issue

Apologies if this is not the place to post, but it was suggested. If not, could you kindly point me in the right direction?
For Stockfish Windows and Linux downloads, I would like executables that took advantage of newer instructions to be the 'default'. Currently, the defaults are AVX2 and POPCNT. Could you post by default a 'faster' version specifically the x86-64-avxvnni version?

### Expected behavior

Either instead of AVX2 or in addition, we'd see the x86-64-avxvnni version available for Windows and Linux.

### Steps to reproduce

Navigate in a browser to: https://stockfishchess.org/download/

### Anything else?

Operating system is Windows and Linux.

### Operating system

Windows

### Stockfish version

Stockfish 16

**Comment by Disservin** [comment]
Hi, 

The downloads from the website links to our Github releases, so you will only be able to download what's available under https://github.com/official-stockfish/Stockfish/releases/tag/sf_16.   

Our prerelease distributes vnni see https://github.com/official-stockfish/Stockfish/releases/tag/stockfish-dev-20231021-8366ec48.
We do not plan on adding additional binaries to the release, see https://github.com/official-stockfish/Stockfish/discussions/4655.
