### ISSUE TITLE
Stockfish for Apple Silicon

### ISSUE THREAD

**Issue by pachnes** [official-stockfish/Stockfish#4839]
### Describe the issue

Please publish a Apple Silicon version of Stockfish every time, you publish a release at abrok.

### Expected behavior

./.

### Steps to reproduce

./.

### Anything else?

./.

### Operating system

MacOS

### Stockfish version

Stockfish 17 Beta

**Comment by vondele** [comment]
For release binaries please see https://github.com/official-stockfish/Stockfish/releases

Unfortunately, no apple silicon hardware is available to us to run github actions on, and so no such binaries can be created at this point.

**Comment by Disservin** [comment]
Abrok is a "third party" distributor. We have no influence over what abrok releases and what not.

**Comment by vondele** [comment]
you should be able to install the corresponding binary yourself with

brew --HEAD install stockfish

https://formulae.brew.sh/formula/stockfish
