### ISSUE TITLE
Nnue Embedding Off

### ISSUE THREAD

**Issue by Negatil07** [official-stockfish/Stockfish#4860]
### Describe the issue

After compiling engine "DNNUE_EMBEDDING_OFF"
the "Use Nnue" disappeared on engine settings.

### Expected behavior

`![Screenshot_20231104-154425](https://github.com/official-stockfish/Stockfish/assets/97826921/8c5ecf6c-9e5f-4144-98fd-ead626f32b6c)`

`![Screenshot_20231104-154442](https://github.com/official-stockfish/Stockfish/assets/97826921/6cdda69a-6731-470a-a872-423270db6529)`

### Steps to reproduce

none

### Anything else?

none

### Operating system

Android

### Stockfish version

Stockfish 16 dev latest

**Comment by vondele** [comment]
The 'Use NNUE' option has been removed from the current development version, it is now always using NNUE.

**Comment by Negatil07** [comment]
Without "Use Nnue" option the default is Use Nnue was disabled. How to enabled the "Use Nnue" if there no option?

**Comment by Negatil07** [comment]
How to enabled the disabled UseNnue if it remove the option? It says UseNnue was disabled.

**Comment by vondele** [comment]
I am not sure I understand your question at this point. However, even if the option 'Use NNUE' is now no longer shown/exposed by the engine. It is always implicitly set to true.

**Comment by Negatil07** [comment]
thanks
