### ISSUE TITLE
Adjust strength

### ISSUE THREAD

**Issue by Asmodisx** [official-stockfish/Stockfish#4878]
### Describe the issue

Does not work very well, I think.

https://ibb.co/3MqSH1V

Elo was "1880" with Droidfish

### Expected behavior

Playing strength is not adjustable. 

### Steps to reproduce

Does not make any mistakes with lower Elo rating.

### Operating system

Android

### Stockfish version

Stockfish 15

**Comment by reggie1337** [comment]
Are you asking for something like a scalable elo? Is there something definitive to "doesn't work very well i think"?

**Comment by Asmodisx** [comment]
As shown the adjustment of strength does not work very well with Droidfish.Maybe 97 percent accuracy meams 1900 Elo, but I don't believe that. As a human player you don't want to play against a Computer 3500 Elo. This does not make any sense. Do you play chess yourself?

**Comment by Disservin** [comment]
Hard to judge what exactly droidfish is doing. The UCI elo strength levels were also made to match other uci engines playing at that elo, not exactly humans playing at that elo.

**Comment by Asmodisx** [comment]
Of course Droidfish use the UCI interface. You're too stupid for chess so you cannot fix anything. Your engine is full of bugs and not adjustable. This is a problem of free software like GNU or Linzx. Only crap from anonymous cocksuckers.

**Comment by Asmodisx** [comment]
Of course Droidfish use the UCI interface. You're too stupid for chess so you cannot fix anything. Your engine is full of bugs and not adjustable. This is a problem of free software like GNU or Linzx. Only crap from anonymous gays

**Comment by Asmodisx** [comment]
Nice typing mistake guy gay 😉 gay guys

It's not true that the strongest engine is the best. Playing strength is not importent.. Winning against LCZERO? Who cares? Most games end in a draw. 

More importent is usability for humana and bug fixes. No human can beat Stockfish or reach a draw. With my best chess I can reach a draw against 2400 (UCI). 

Hierarchy is a big problem in free software world. Like Linux or Stallman's crap. 😉
