### ISSUE TITLE
Stockfish.exe crash in command prompt.

### ISSUE THREAD

**Issue by LightningThunder1** [official-stockfish/Stockfish#4902]
### Describe the issue

Stockfish on command prompt keeps crashing after tying 'position fen' twice in a row. This never happens when I mistype something..

### Expected behavior

The exactly same thing any other time where you mistype, it goes to the next line. 

### Steps to reproduce

Exactly what I entered on the command line output below in bold.
**position fen position fen rnbq1bnr/pp2p1p1/3p4/kPpP2pB/N3P2p/5Q2/P1P2PPP/R3K1NR w KQ c6 0 1**

### Anything else?

Assertion failed: pieceCount[make_piece(c, Pt)] == 1, file src\position.h, line 253.
abort() has been called.

> Stockfish.exe!Position::square<6>(Color c) Line 253

> Stockfish.exe!_wassert(const wchar_t * expression, const wchar_t * file_name, unsigned int line_number) Line 444

> Stockfish.exe!common_assert<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number, void * const return_address) Line 420

> Stockfish.exe!common_assert_to_stderr<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 179

> Stockfish.exe!common_assert_to_stderr_direct(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) Line 161

> Stockfish.exe!abort() Line 61

### Operating system

Windows

### Stockfish version

stockfish_23120210_x64_bmi2

**Comment by Disservin** [comment]
A) for some reason you happen to have debug version of stockfish 
B) this is kinda expected behavior we don’t validate the user input so in this case it probably thinks position fen is the fen and crashes somewhere

**Comment by LightningThunder1** [comment]
Oh, this actually happened for the normal version as well (https://abrok.eu/stockfish/)

**Comment by Disservin** [comment]
With a) I just meant that you are running a slower version of stockfish.

**Comment by Disservin** [comment]
Consider downloading stockfish from the official release https://github.com/official-stockfish/Stockfish/releases. (Won’t fix this ofc)
