### ISSUE TITLE
Slowdown?

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#4911]
### Describe the issue

Newest version vs 2019 version seems twice as slow.

```
$ ./stockfish-mingw-bmi2-old.exe   2>&1 bench |grep -F -e "Nodes/" -e by
Stockfish 190322 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 1215565

Zibri@ZibriN MINGW64 ~/Stockfish/src
$ ./stockfish   2>&1 bench |grep -F -e "Nodes/" -e by
Stockfish dev-20231204-7a8bcfc2 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 564859

```

### Expected behavior

I understand that as the complexity grows the speed will decrease... but it seems a little too much...

### Steps to reproduce

$ ./stockfish-mingw-bmi2-old.exe   2>&1 bench |grep -F -e "Nodes/" -e by
Stockfish 190322 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 1215565

Zibri@ZibriN MINGW64 ~/Stockfish/src
$ ./stockfish   2>&1 bench |grep -F -e "Nodes/" -e by
Stockfish dev-20231204-7a8bcfc2 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 564859

### Operating system

All

### Stockfish version

multiple

**Comment by Zibri** [comment]
If this is true, on a slow/normal computer and in a very quick game I wonder ,,,

**Comment by peregrineshahin** [comment]
nodes per seconds (NPS) is not a metric for strength. this is the result of slowness in the evaluation function due to adapting much larger sizes for L1 in NNUE  and dropping the Hand Crafted Evaluation (HCE) in newer versions.

**Comment by Zibri** [comment]
So, how to determine the speed of a stockfish version against another?

```
# ./stockfish16 2>&1 bench |grep -F -e "Nodes/" -e by
Stockfish dev-20231204-7a8bcfc2 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 740705

runneradmin@fv-az1564-735 MINGW64 /home/Stockfish/src
# ./stockfish15 2>&1 bench |grep -F -e "Nodes/" -e by
Stockfish 15 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 1669011

Stockfish 14 by the Stockfish developers (see AUTHORS file)
Nodes/second    : 1948115
```

please explain me this.

**Comment by PGG106** [comment]
you don't need to measure the "speed of a stockfish version against another", the speed of each version if fixed and a property of the engine itself.
The main point is that speed doesn't correlate with stregth, yes the newer versions are slower, they are also stronger because that speed penalty was a trade-off for having a bigger nnue.

**Comment by peregrineshahin** [comment]
In case you are wondering about strength, then to decide that we use statistical methods such as SPRT testing https://en.wikipedia.org/wiki/Sequential_probability_ratio_test, you can have a deeper look here 
https://github.com/official-stockfish/fishtest/wiki
and check active or finished tests here:
https://tests.stockfishchess.org/tests

**Comment by Zibri** [comment]
@peregrineshahin 
the reason I am asking is because I wish to study stockfish source and see if some parts can be optimized for speed.
So I am searching for a method to measure the engine speed to check if any modification influences the speed positively or negatively.

**Comment by PGG106** [comment]
As long as your change is purely related to speed and doesn't functionally affect how the engine works, you can just compare the measured speed of the engine before and after the change.
I'm pretty sure there's a script somewhere that allows you to get higher accuracy compared to simply running bench 5 times or so for both versions

**Comment by ppigazzini** [comment]
Wiki link about how to measure a Stockfish speedup
https://github.com/official-stockfish/Stockfish/wiki/Advanced-topics#measure-the-speed-of-stockfish

This is useful only to compare 2 Stockfish versions or with non functional changes or compiled in different ways (flags, compilers etc.)

**Comment by peregrineshahin** [comment]
In such case running the `bench` command will run Stockfish to a fixed depth and obtain a deterministic `nodes searched` with 1 thread which is the default. Now to make sure that the two versions are functionally the same, you need to run the two versions first with the bench command to see if they have the same `nodes searched` and then you can proceed with the speedup testing. you might need to run the script from above with at least 50 run to avoid some noise in the measurement. You should also submit an STC test afterwards for your change at https://tests.stockfishchess.org/tests to see if the change is worth submitting a PR for in terms of Elo. Thanks!

> @peregrineshahin the reason I am asking is because I wish to study stockfish source and see if some parts can be optimized for speed. So I am searching for a method to measure the engine speed to check if any modification influences the speed positively or negatively.

**Comment by Zibri** [comment]
>  The main point is that speed doesn't correlate with strength, yes the newer versions are slower, they are also stronger because that speed penalty was a trade-off for having a bigger nnue.

How can you say that speed does not correlate with strenght?
Imagine I set stockfish to a big depth in a timed game.
The faster it runs the deeper it can analyze in the same time frame.
Am I wrong? And if I am... why?

**Comment by cj5716** [comment]
no, but the speed is compensated with better accuracy and thus stronger play

**Comment by PGG106** [comment]
You are wrong because your reasoning only works when thinking about the same version of stockfish, if you compare stockfish 16 with a version of stockfish 16 that is magically 20% faster, of course you'll notice that the faster version is stronger.
Where this comparison breaks is when you start comparing different stockfish versions, SF 16 is slower than sf 14 but it's still stronger, that's because speed as an absolute value doesn't predict strength.
Your issue opens talking about SF from years ago to current SF,  that's exactly the scenario where nps are completely meaningless

**Comment by Zibri** [comment]
ok.. got it. The problem is that if I run the same version in bench mode 10 times I get different results, even at maximum priority.
that's also because the cpu heats up, but the weird thing is that it happens even before the cpu hits the thermal limit.
I wish there was a better way to measure it... if it's 20% is quite obvious.. but if it's 5% or 10% (which I consider good anyways) it's difficult to tell.

**Comment by PGG106** [comment]
ppigazzini's comment has a useful link that will take you to a page where better methods are outlined

**Comment by Zibri** [comment]
> ppigazzini's comment has a useful link that will take you to a page where better methods are outlined

Yep, I saw it but they all use "stockfish bench XX YY".

**Comment by Craftyawesome** [comment]
Yes, but you can configure how many times it runs to reduce any noise.
