### ISSUE TITLE
How to disable NNUE in SF16?

### ISSUE THREAD

**Issue by Zibri** [official-stockfish/Stockfish#4924]
### Describe the issue

I know I can disable embedding, but how to disable NNUE completely in stockfish 16?

### Expected behavior

To have a compile time option to disable NNUE completely and have only the classic evaluation.

### Steps to reproduce

see above

### Operating system

All

### Stockfish version

Stockfish 16

**Comment by Disservin** [comment]
Classical was removed.

**Comment by Disservin** [comment]
If you actually meant Stockfish 16 and not the dev version you can disable it with
`setoption name Use NNUE value false`

**Comment by dav1312** [comment]
> To have a compile time option to disable NNUE completely and have only the classic evaluation.

If you only care about HCE then you just use https://github.com/official-stockfish/Stockfish/releases/tag/SF_classical

**Comment by Zibri** [comment]
> If you actually meant Stockfish 16 and not the dev version you can disable it with `setoption name Use NNUE value false` but it's not compile time.

Yes, sorry, I was meaning the DEV version...
