### ISSUE TITLE
Bug during compiling on GitHub

### ISSUE THREAD

**Issue by BestV-Fish** [official-stockfish/Stockfish#4939]
### Describe the issue

I've forked the stockfish repository to make experiments on the pieces value on the types.h file. I've only changed this part of the code :     // In the code, we make the assumption that these values
    // are such that non_pawn_material() can be used to uniquely
    // identify the material on the board.
    PawnValue   = 200,
    KnightValue = 900,
    BishopValue = 800,
    RookValue   = 1700,
    QueenValue  = 3500,
};

Here is my change
When i compil it via GitHub actions, an error occured
What is the problem?

### Expected behavior

Stockfish is compiled and the .exe are available

### Steps to reproduce

GitHub actions

### Operating system

Windows

### Stockfish version

27122023

**Comment by peregrineshahin** [comment]
Not an issue, You need to provide in the commit message a bench signature for each commit you make unless it's a non-functional change.
https://github.com/BestV-Fish/Stockfish/actions/runs/7341006279/job/19987955239
check the error here, there is a mismatch between the last bench signature obtained and the new one.

to get the new bench signature you can run `./stockfish.exe bench` and take the nodes searched for the signature..
take our last commit for an example https://github.com/official-stockfish/Stockfish/commit/fbdf5d94a9a42acb92720a5896b16c92931ec3de
it has `Bench: 1312822` on the last line.

**Comment by Disservin** [comment]
This is not an issue with this stockfish. Please refrain from opening issues on here because something fails on your personal fork.

**Comment by BestV-Fish** [comment]
Okay sorry
Thanks @peregrineshahin
