### ISSUE TITLE
Stockfish_wrong_analysis

### ISSUE THREAD

**Issue by Ehsan-ML79** [official-stockfish/Stockfish#4973]
### Describe the issue

I've faced 2 weird issues in newer versions of SF. 1- in older version of that it could partially true evaluating at opening around +0.08 or sth like this (with deep analyzing) but now it couldn't answer true eval even you let it to deep analyzing (seems got worse and buggy in newer version)
It analyzed that if you play french defence you got evaluating around +0.4! or if you play Sicilian got more than +0.28 means if you play black you have no chance to win! while you must get around 0 eval and draw position!!
2-until I saw this site "https://groups.google.com/g/fishcooking/c/vLl0QVUvMQ0" that was written in 2015 about stockfish's weaknesses and wrong evaluation that still remains and wasn't fixed!!!

### Expected behavior

in first issue I expected SF to reach a draw position even after half an hour nothing changed!
Second everything is explained on that site for example Rxf5 exf5 then Qxh mate in 6 but it evaluating opposite advantages( black side -1.8)in this FEN:
4rb2/1p1q1ppk/p1n1p2p/2p1Pn2/3PNR2/2P2K2/P2QBP2/6R1 w - - 0 1
(The interesting thing is that 2011 Houdini was able to detect RIGHT move!)

### Steps to reproduce

in all recent version SF113 ,14.1 ,16 even SF-20240107-7c!!

### Operating system

All

### Stockfish version

SF 16

**Comment by dav1312** [comment]
> in older version of that it could partially true evaluating at opening around +0.08 or sth like this (with deep analyzing) but now it couldn't answer true eval even you let it to deep analyzing (seems got worse and buggy in newer version)

Here you have an example of "very deep analyzing" from November by Vondele with an eval of +0.11

```
info depth 76 seldepth 99 multipv 1 score cp 11 nodes 5255389383962 nps 68060811 hashfull 1000 tbhits 0 time 77216085 pv g1f3 g8f6 d2d4 d7d5 c2c4 e7e6 g2g3 f8e7 f1g2 e8g8 e1g1 d5c4 d1c2 a7a6 a2a4 c8d7 c2c4 d7c6 c1g5 b8d7 b1c3 h7h6 g5f6 d7f6 f1d1 a6a5 a1c1 e7b4 f3e5 c6g2 g1g2 c7c6 e2e3 d8e7 h2h4 b4d6 c3b1 e7c7 e5d3 e6e5 d4e5 d6e5 b1d2 f8e8 d3e5 c7e5 c4c2 e5d5 d2f3 d5e6 c2c4 e6e7 c4c5 e7c7 c1c4 a8d8 d1d8 e8d8 c5a7 d8d3 b2b4 a5b4 c4b4 d3d7 a4a5 c7c8 f3e5 c6c5 b4c4 d7d5 a5a6 d5e5 a6b7 c8c6 g2g1 f6d7 b7b8q d7b8 a7b8 e5e8 c4c5 e8b8 c5c6 h6h5 c6c5 g7g6 c5a5 b8e8
```

> It analyzed that if you play french defence you got evaluating around +0.4! or if you play Sicilian got more than +0.28 means if you play black you have no chance to win! while you must get around 0 eval and draw position!!

In engine games black indeed has almost no chance to win with those evals (0.1%), but white isn't winning either (5-6%), there is a 94% chance of drawing.

> wrong evaluation that still remains and wasn't fixed!!!

Specific positions are not "fixed". Progress is made for general chess play and sometimes that helps solve puzzles.

Stockfish finds Rxf5 in 15 seconds
```
Stockfish dev-20240108-6deb8872 by the Stockfish developers (see AUTHORS file)
position fen 4rb2/1p1q1ppk/p1n1p2p/2p1Pn2/3PNR2/2P2K2/P2QBP2/6R1 w - - 0 1
go infinite
...
info depth 28 seldepth 54 multipv 1 score cp -192 lowerbound nodes 10276245 nps 694481 hashfull 1000 tbhits 0 time 14797 pv f4f5
...
info depth 28 seldepth 54 multipv 1 score cp 204 nodes 10415314 nps 692231 hashfull 1000 tbhits 0 time 15046 pv f4f5 c6d4 c3d4 e6f5 d2h6 h7h6 g1h1 h6g6 f3f4 d7c6 e2h5 g6h7 h5f7 c6h6 h1h6 h7h6 f7e8 f5e4 d4d5 b7b5 d5d6 c5c4 e8f7 e4e3 f4e3 h6g5 f2f4 g5f5
```

**Comment by Ehsan-ML79** [comment]
> Here you have an example of "very deep analyzing" from November by Vondele with an eval of +0.11
> 
Ye fair enough that was real deep analyzing but it should faster to reach this result (as older versions) shouldn't it?
  
> Specific positions are not "fixed". Progress is made for general chess play and sometimes that helps solve puzzles.
> 
> Stockfish finds Rxf5 in 15 seconds

 I installed that version Stockfish dev-20240108-6deb8872 but it find after about 3 mins (after clear cache and hash)
It's just an example the matter is this isn't fake or artificial position these positions happen during a real game and unavoidable so SF must be able to solve it quick unless it could another lost with WHITE side against lc0!
I just want to figure out this issue ? What's problem out there ?!
Is it related to cut-off alpha beta, feature amounts,horizon affect, heuristic eval function or nnue layers...
I'm just guessing

**Comment by vondele** [comment]
All plausible guesses, but no real issue, the engine is tested rigorously for improvements using fishtest. 

If you would like to improve the chess engine, contribute patches following these guidelines: https://github.com/official-stockfish/fishtest/wiki/Creating-my-first-test
