### ISSUE TITLE
Go depth command output depth begins from zero

### ISSUE THREAD

**Issue by PavelChess** [official-stockfish/Stockfish#5019]
### Describe the issue

Output depth begins from zero, for example at latest version:

go depth 3
info string NNUE evaluation using nn-baff1ede1f90.nnue
info string NNUE evaluation using nn-baff1edbea57.nnue
info depth 0 seldepth 2 multipv 1 score cp -4 nodes 20 nps 10000 hashfull 0 tbhits 0 time 2 pv d2d4
info depth 1 seldepth 2 multipv 1 score cp 18 nodes 44 nps 22000 hashfull 0 tbhits 0 time 2 pv a2a3
info depth 2 seldepth 2 multipv 1 score cp 61 nodes 69 nps 34500 hashfull 0 tbhits 0 time 2 pv d2d4

### Expected behavior

Version from Date: Mon Jan 8 18:34:36 2024 +0100 correctly begins output depth from 1.

### Steps to reproduce

go depth 3

### Operating system

Windows

### Stockfish version

Stockfish16 / fcbb02ff

**Comment by Disservin** [comment]
Thanks for reporting this… will fix that soon
