### ISSUE TITLE
Strange behavior on PV = 1

### ISSUE THREAD

**Issue by Gravitar64** [official-stockfish/Stockfish#5022]
### Describe the issue

When Stockfish analysis a position with pv=1, in some positions it can't find the best move in 15 Minutes. If I switch to pv=2, the best move will be found in seconds.

### Expected behavior

PV=1 should be show the best move

### Steps to reproduce

I.E. this position FEN: 8/2p5/7p/pP2k1pP/5pP1/8/1P2PPK1/8 w - - 0 1
Best move is f2-f3. Stockfish 16 shows Kg2-f3 on depth 56/95 after 2 Min, 17 Sec. on PV=1
On PV=2, it shows f2-f3 after 0 Min, 0 Sec on depth 13/17!!!!

Another Example: FEN r2qr2k/pbp3pp/1p2Bb2/2p5/2P2P2/3R2P1/PP2Q1NP/5RK1 b - - 0 1 
Best move is Qd8xd3. Stockfish 16 shows Bf6-d4+ on depth 41/65 after 1:49 on PV=1
On PV=2, it shows Qd8xd3 after 0:01 on depth 22/36!!!!

### Operating system

All

### Stockfish version

Stockfish 16 avx2

**Comment by dav1312** [comment]
> PV=1 should be show the best move

This is hard to do considering chess hasn't been solved yet, but Stockfish actually tries its best to show the best move.

1 line and 2 or more lines are intrinsically different. When you enable multiple lines, Stockfish is not just showing some hidden stats that were available before, it is actually spliting its resources between those lines. You are asking it to search for the best move _and_ search for the second best move, this can sometimes lead to finding a hidden gem, but most of them time it won't. 

Using just 1 line is overall the strongest option for the same amount of time: https://github.com/official-stockfish/Stockfish/wiki/Stockfish-FAQ#multipv

**Comment by Disservin** [comment]
@dav1312 assessment is overall right
