### ISSUE TITLE
Checkmate blunder at relatively high depth

### ISSUE THREAD

**Issue by PavelChess** [official-stockfish/Stockfish#5024]
### Describe the issue

1. d4 Nf6 2. c4 e6 3. Nf3 Bb4+ 4. Nbd2 O-O 5. a3 Be7 6. g3 d5 7. Bg2 b6 8. b3 c5 9. Bb2 Bb7 10. O-O Nbd7 11. cxd5 exd5 12. e3 Rc8 13. Qe2 Re8 14. Rfc1 Bd6 15. dxc5 bxc5 16. b4 c4 17. Qd1 Bc7 18. Nb1 a5 19. Nc3 axb4 20. axb4 Bd6 21. Rcb1 Ne5 22. Ra7 Qb6 23. Ra2 Nd3 24. Na4 Qd8 25. Bd4 Qe7 26. Ne1 Ne5 27. Nc3 h5 28. Nb5 Bb8 29. Bh3 h4 30. Bxc8 Bxc8 31. Nc3 Bg4 32. f3 Bf5 33. Rba1 Qxb4 34. Ng2 h3 35. Nf4 Qb3 36. Kf2 Qb7 37. Ra6 Rc8 38. Rb6 Qe7 39. Ra2 Bc7 40. Rb5 Qe8 41. Rc5 Ned7 42. Rxc7 Rxc7 43. g4 Be6 44. g5 Nh7 45. Nb5 Rc6 46. Qa1 c3 47. Bxc3 Qe7 48. Bxg7 Qxg5 49. Ra8+ Ndf8 50. Nd4 Rc8 51. Ndxe6 Rc2+ 52. Kf1 Qg3 53. hxg3 0-1

51th move Ndxe6 is grave blunder in won position.
I tried latest version from 26 january: at depth 28:
...
info depth 28 currmove a1c1 currmovenumber 47
info depth 27 seldepth 51 multipv 1 score cp 291 nodes 3309202 nps 423279 hashfull 21 tbhits 0 time 7818 pv d4e6 c8c2 f2f1 g5h4 a1e1 h4e1 f1e1 f7e6 g7f8 h7f8 f4e6 g8f7 e6f8 c2h2 f8d7 h2c2 d7e5 f7g7 a8a7 g7g8 e5g4 h3h2 g4h2 c2h2 a7a5 d5d4 e3d4 g8f7 a5e5 f7f6 e5e2 h2h4 e2d2 f6f5 e1e2 f5f4 e2d3 h4h1 d4d5 f4e5 d3e3 e5d6 f3f4 h1h3 e3e4 h3h8 e4f3 h8f8
bestmove d4e6 ponder c8c2

SF need at least depth 29 to see that it loses, and then it chooses right move Rxc8,

### Expected behavior

SF should see at lower depth that opponent mates by force, because this was a position that opponent every move threatens mate in 1 or gives a check.

### Steps to reproduce

setoption name hash value 1024
position fen R1r2nk1/5pBn/4b3/3p2q1/3N1N2/4PP1p/5K1P/Q7 w - - 0 51
go depth 28

### Operating system

Windows

### Stockfish version

Stockfish16 / fcbb02ff

**Comment by joergoster** [comment]
Nd4xe6 leads to a forced loss (White will get mated). SF takes some time to realize this and switch to a better move. No real issue, although I don't like it takes that long.
