### ISSUE TITLE
Smaller net in the UCI options

### ISSUE THREAD

**Issue by archimedeschess** [official-stockfish/Stockfish#5033]
### Describe the issue

In the non-embedded version, both networks are not integrated. While you can select the larger network in the UCI options, you cannot do this for the smaller network, with the result, that Stockfish crashes on Android without the smaller net. For this reason, the smaller network must be copied to the log directory of DroidFish. A non-embedded version makes no sense under Android in this way.

### Expected behavior

Making the smaller network also selectable in the UCI options would help.

### Steps to reproduce

As described above.

### Operating system

Android

### Stockfish version

Stockfish 240203

**Comment by peregrineshahin** [comment]
There are plans to do that:
https://github.com/official-stockfish/Stockfish/blob/ededadcd6f7fbb9eb122f5fe336025cc4b11753b/src/evaluate.cpp#L154
Although it was temporary left out until this PR from the Stockfish Testing Framework Project (Fishtest) gets merged:
https://github.com/official-stockfish/fishtest/pull/1870

**Comment by Disservin** [comment]
This has been implemented. Smallnet is currently a uci option.
