### ISSUE TITLE
Stockfish 15.1 crashes for: position fen 3qk1nb/1p3p2/p1r1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 w Qk - 0 15

### ISSUE THREAD

**Issue by Mercutio1243** [official-stockfish/Stockfish#5071]
### Describe the issue

I am using stockfish_15.1_win_x64 from the official website. When running stockfish-windows-2022-x86-64.exe and prompting the commands:

> position fen 3qk1nb/1p3p2/p1r1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 w Qk - 0 15
> go movetime infinite

The exe crashes instantaneously. Similarly, my flutter app running with a flutter implementation of Stockfish 15.1 (https://pub.dev/packages/stockfish) crashes with an error pointing to the engine.

Other positions run through as expected.

### Expected behavior

Stockfish calculates position and does not crash

### Steps to reproduce

See above

### Operating system

All

### Stockfish version

Stockfish 15.1

**Comment by Disservin** [comment]
Your fen isn't a valid FEN. `position fen 3qk1nb/1p3p2/p1r1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 w Qk - 0 15` Black cannot castle king side.

**Comment by Mercutio1243** [comment]
Thank you, this is a good pointer! 

Why is Stockfish then accepting the following fen:
position fen 2rqk1nb/1p3p2/p1B1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 b Qk - 0 14

**Comment by Disservin** [comment]
Probably because the king is in check and chess rules say we cant castle, so we dont try to generate the move and after the king moves we clear all castling squares for the king.

**Comment by PGG106** [comment]
How the engine reacts to illegal fens should be considered undefined behaviour, you can't rely on the engine consistently saving itself from a crash.
If you want fen validation your best bet currently it to validate the fen before passing it to sf.

**Comment by Mercutio1243** [comment]
Ok, thank you! In summary, the error seems to be with the generation of the fens (not your problem). 

For future, all the previous fens from that game that I am using were also faulty but did not result in an error. But again, not your issue as PGG106 is pointing out (but maybe interesting for someone else at some point)
```
rnbqk1nr/ppp1ppb1/6p1/3p4/8/2N5/PPPPPPP1/R1BQKBNR w KQkq - 0 5 -- here still okay
rnbqk1nR/ppp1ppb1/6p1/3p4/8/2N5/PPPPPPP1/R1BQKBN1 b Qkq - 0 5 -- here the rook gets taken but castling rights are preserved for black
rnbqk1nb/ppp1pp2/6p1/3p4/8/2N5/PPPPPPP1/R1BQKBN1 w Qkq - 0 6
rnbqk1nb/ppp1pp2/6p1/3p4/8/2N1P3/PPPP1PP1/R1BQKBN1 b Qkq - 0 6
rnbqk1nb/pp2pp2/6p1/2pp4/8/2N1P3/PPPP1PP1/R1BQKBN1 w Qkq c6 0 7
rnbqk1nb/pp2pp2/6p1/2pp4/8/2N1PN2/PPPP1PP1/R1BQKB2 b Qkq - 1 7
r1bqk1nb/pp2pp2/2n3p1/2pp4/8/2N1PN2/PPPP1PP1/R1BQKB2 w Qkq - 2 8
r1bqk1nb/pp2pp2/2n3p1/2pp4/3P4/2N1PN2/PPP2PP1/R1BQKB2 b Qkq d3 0 8
r2qk1nb/pp2pp2/2n3p1/2pp4/3P2b1/2N1PN2/PPP2PP1/R1BQKB2 w Qkq - 1 9
r2qk1nb/pp2pp2/2n3p1/1Bpp4/3P2b1/2N1PN2/PPP2PP1/R1BQK3 b Qkq - 2 9
r2qk1nb/pp2pp2/2n3p1/1B1p4/3p2b1/2N1PN2/PPP2PP1/R1BQK3 w Qkq - 0 10
r2qk1nb/pp2pp2/2n3p1/1B1p4/3P2b1/2N2N2/PPP2PP1/R1BQK3 b Qkq - 0 10
2rqk1nb/pp2pp2/2n3p1/1B1p4/3P2b1/2N2N2/PPP2PP1/R1BQK3 w Qk - 1 11
2rqk1nb/pp2pp2/2n3p1/1B1p4/3P2b1/2N1BN2/PPP2PP1/R2QK3 b Qk - 2 11
2rqk1nb/pp3p2/2n1p1p1/1B1p4/3P2b1/2N1BN2/PPP2PP1/R2QK3 w Qk - 0 12
2rqk1nb/pp3p2/2n1p1p1/1B1p4/3P2b1/2N1BN2/PPPQ1PP1/R3K3 b Qk - 1 12
2rqk1nb/pp3p2/2n1p1p1/1B1p4/3P4/2N1Bb2/PPPQ1PP1/R3K3 w Qk - 0 13
2rqk1nb/pp3p2/2n1p1p1/1B1p4/3P4/2N1BP2/PPPQ1P2/R3K3 b Qk - 0 13
2rqk1nb/1p3p2/p1n1p1p1/1B1p4/3P4/2N1BP2/PPPQ1P2/R3K3 w Qk - 0 14
2rqk1nb/1p3p2/p1B1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 b Qk - 0 14
3qk1nb/1p3p2/p1r1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 w Qk - 0 15 -- here stockfish 15.1 crashes
```
