### ISSUE TITLE
Not an issue. Just need help from professionals.

### ISSUE THREAD

**Issue by AlexB123** [official-stockfish/Stockfish#5080]
### Describe the issue

Hello SF team! I have a problem with adding support for polyglot (.bin) books in the current Stockfish. Before it was easy, was needed just a few tiny changes in code, specifically in Makefile, main.cpp, search.cpp and ucioption.cpp, also need to add 2 extra files polybook.cpp and polybook.h (like in old Brainfish). Anyway, as I was saying everything was fine until this patch "Refactor global variables" https://github.com/official-stockfish/Stockfish/commit/a10791095150bf7c020b92be0f55566fe34e9bf2
Since my programming knowledge is "non-existent", can someone help me please?
Below is the source code of the SF polyglot 080124 "Update default main net to nn-baff1edbea57.nnue" (with changes in files that I mentioned above, polybook.cpp and polybook.h included, perhaps they will need some changes too). Also there is original code of the same SF 080124 (for comparison, just in case). Please take a look in the code and tell me what kind of changes it need.
Thank you in advance.
Regards.
[SF-Polyglot-080124-Update default main net to nn-baff1edbea57.nnue.zip](https://github.com/official-stockfish/Stockfish/files/14445626/SF-Polyglot-080124-Update.default.main.net.to.nn-baff1edbea57.nnue.zip)

### Expected behavior

Hope you'll help me.

### Steps to reproduce

*

### Anything else?

No.

### Operating system

All

### Stockfish version

Stockfish 16.1

**Comment by Disservin** [comment]
If it is not an issue why do you open an issue? 
Just use the discussion place.

**Comment by AlexB123** [comment]
> If it is not an issue why do you open an issue? Just use the discussion place.

Thanks.
