### ISSUE TITLE
Javascript engine blunders directly after 50 move draw rule

### ISSUE THREAD

**Issue by JMA1972** [official-stockfish/Stockfish#5109]
### Describe the issue

![image](https://github.com/official-stockfish/Stockfish/assets/92122854/e8f37425-58ab-4d45-8344-8f9a3fd7348c)
In the first move after a game would be draw due to the 50 moves rule Stockfish gives just away a piece and that with the seemingly depth 99.

### Expected behavior

Any move that doesn't lose the knight immediately.

### Steps to reproduce

Sorry, lichess doesn't allow saving a game analysis as pgn. You have to make the move from the screenshot manually.

### Operating system

All

### Stockfish version

Stockfish 16 NNUE

**Comment by PGG106** [comment]
The game is already a draw (due to the 50mr), all the moves are the same, the game is over , the result is a draw, there isn't a best move, there isn't a bad move, it's a draw.
Stockfish does not handle illegal positions and playing a position where a game is over is definitely illegal

**Comment by PGG106** [comment]
Also In the future when talking about a position please include a fen for it

**Comment by JMA1972** [comment]
Thats correct in a game but not in an analysis

**Comment by PGG106** [comment]
That's how engines work, a position where a game ended is a position where the game ended, the engine will just see the game is over (and is a draw) and return any move because any move has the same result (the game is a draw).
If you want to avoid this just lower the 50mr counter manually, this is intended behaviour and the fen itself is illegal.

**Comment by Craftyawesome** [comment]
Well, the fen isn't illegal in typical chess because 50 move rule has to be claimed and it isn't forced until 75. But the engine saying the best move is to claim 50 mr is also expected.

**Comment by PGG106** [comment]
Well engines can't strictly claim a 50mr draw (aside from displaying a fat 0 as the score), any decent gui will do to for them, the underlying assumption is that a draw will always be claimed, it's indeed behaviour, no one uses the 75mr stuff.

**Comment by Craftyawesome** [comment]
Yes, the "claim" is indeed displaying 0, single move pv, fast depth, etc, rather than something explicitly told to the UI.
