### ISSUE TITLE
Stockfish release 16.1 for vnni256 not working.

### ISSUE THREAD

**Issue by R-Goc** [official-stockfish/Stockfish#5110]
### Describe the issue

The engine doesn't launch. The hardware is supported. When clicking launch engine it will appear at the bottom in arena but will not use any memory or show any lines. 

### Expected behavior

The engine starting and working.

### Steps to reproduce

Download the engine vnni256 version from https://stockfishchess.org/download/windows/ and run it from a chess GUI(I'm using arena).

### Anything else?

The system is running windows 11. The cpu is a intel core ultra 7 155H. 

### Operating system

All

### Stockfish version

Stockfish 16.1

**Comment by PGG106** [comment]
What happens if you open the binary directly from terminal and type go?
Where did you download the binary from?
What's your CPU?

**Comment by Disservin** [comment]
@PGG106 we resolved it over discord already

**Comment by PGG106** [comment]
Yeah I noticed, my bad
