### ISSUE TITLE
The windows VNNI binary does not work.

### ISSUE THREAD

**Issue by Kothric** [official-stockfish/Stockfish#5136]
### Describe the issue

The windows VNNI binary does not work, My cpu is 13600KF, should support the instructions.

> G:\Chess\stockfish>stockfish-windows-x86-64-vnni512.exe
> 
> G:\Chess\stockfish>

### Expected behavior

Expect print the version info at least.

like the avx2 version :

> G:\Chess\stockfish-avx2>stockfish-windows-x86-64-avx2.exe
> Stockfish 16.1 by the Stockfish developers (see AUTHORS file)

### Steps to reproduce

Download the binary, decompress, and running it.

### Operating system

Windows

### Stockfish version

16.1

**Comment by AndyGrant** [comment]
I don't see any mention of VNNI support for that processor.

https://ark.intel.com/content/www/us/en/ark/products/230494/intel-core-i5-13600kf-processor-24m-cache-up-to-5-10-ghz.html ?

**Comment by Kothric** [comment]
Not sure if below page is correct that mentioned Raptor lake support it.

https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX-VNNI

> CPUs with AVX-VNNI
> Intel
> Alder Lake processors, Q4 2021
> Raptor Lake processors, Q4 2022
> Sapphire Rapids processors, Q1 2023
> Meteor Lake processors
> Emerald Rapids processors
> Arrow Lake processors
> Lunar Lake processors
> AMD
> Zen 5 processors,[36] 2024

**Comment by Kothric** [comment]
> I don't see any mention of VNNI support for that processor.
> 
> https://ark.intel.com/content/www/us/en/ark/products/230494/intel-core-i5-13600kf-processor-24m-cache-up-to-5-10-ghz.html ?

Actually , from the page , it seems support the VNNI:
![image](https://github.com/official-stockfish/Stockfish/assets/95487387/b388b520-5f87-4b95-9ffc-d41bb70a24ea)

**Comment by AndyGrant** [comment]
Then you might have a genuine issue. You have AVX-VNNI support according to what I read quickly, but I don't believe you have full AVX-512 support. It might be the case that Stockfish assumes that VNNI is a superset of AVX-512.

**Comment by vondele** [comment]
The binary tested is vnni512 it requires support for : ` CXXFLAGS += -mavx512f -mavx512bw -mavx512vnni -mavx512dq -mavx512vl -mprefer-vector-width=512` it could be the op needs to pick avxvnni `CXXFLAGS += -mavxvnni`

**Comment by vondele** [comment]
anyway, I see we don't build that as part of the assets provided in the release, so that might have to be added for the future. Providing binaries for every variation of processors is a bit tedious there are many flavors (a 2019 image https://twitter.com/InstLatX64/status/1114141314441011200 )

**Comment by Kothric** [comment]
Thanks, that make sense 13600KF does not support full avx512-vnni.
Currently the best usable one for my cpu is bmi2.

**Comment by Disservin** [comment]
I think we might need to put out some more information regarding these binaries, there was a similar confusion here https://github.com/official-stockfish/Stockfish/issues/5110

**Comment by vondele** [comment]
In principle running the `scripts/get_native_properties.sh` we can get which binary should be used. Pasquale had a version that also worked on windows for the downloader.

**Comment by Disservin** [comment]
I'll close this since it is directly to the users cpu and not to binary (stockfish) itself.
We might need to help the user more in the future to select the right binary.
