### ISSUE TITLE
Stockfish > 16 ignores setoption after go

### ISSUE THREAD

**Issue by cernst72** [official-stockfish/Stockfish#5137]
### Describe the issue

After Stockfish 15.1 changing MultiPv of a running analysis seems to be broken. When starting an infinite analysis with `go` and then pasting `setoption name MultiPv value 5` the input is ignored. This worked up to Stockfish 15.1.

Step 1: Launch Stockfish 15.1
```
uci
position r1bq1rk1/pp3ppp/2pbp3/3n4/3P1P2/P1N1PN2/1P1Q1PBP/2R2RK1 b - - 0 17
setoption name MultiPv value 5
go 3600000
```
Step 2
Wait a little and paste
```
setoption name MultiPv value 2
```
Step 3
Wait a little and paste
```
stop
```
Result: Stockfish 15.1 starts with 5 pvs, then continues with 2 pvs and stops.
This is the expected behavior and can be observed with other uci engines too (lc0, dragon).

When entering the same sequence for Stockfish 16 and 16.1 the command after step 2 will be ignored, Stockfish will continue with 5 pvs.
Even stop and quit will be ignored, after setoption has been entered (but not before).

### Expected behavior

Accept setoption and stop on the console while running go.

### Steps to reproduce

```
uci
position r1bq1rk1/pp3ppp/2pbp3/3n4/3P1P2/P1N1PN2/1P1Q1PBP/2R2RK1 b - - 0 17
setoption name MultiPv value 5
go 3600000
setoption name MultiPv value 2
stop
```
Result: Stockfish 16.1 does not reduce MultiPv to 2 and does not stop.

### Operating system

Linux

### Stockfish version

Stockfish 16.1

**Comment by Disservin** [comment]
I don't understand your reproduction are trying to modify the options while a search is ongoing?

**Comment by Disservin** [comment]
This behaviour isn't really something one should do/rely on.

https://backscattering.de/chess/uci/ 
> One string will be sent for each parameter and this will only be sent when the engine is waiting

The engine isn't really in a waiting state after you wrote `go ...`,
but the behavior was indeed changed (unintentionally) ... this was not there before https://github.com/official-stockfish/Stockfish/blob/master/src/uci.cpp#L314.

**Comment by Disservin** [comment]
That behaviour was even (more or less) present before for the options `Hash` and `Clear`, so right now it is arguably more consistent.

**Comment by cernst72** [comment]
> I don't understand your reproduction are trying to modify the options while a search is ongoing?

Yes, this is indeed what I want to. It worked up to SF 15.1 and it still does work in Dragon and LC0.
Can the `wait_for_search_finished()` statement explain why no further uci commands (like stop or quit) are executed after once setoption has been called?

**Comment by Disservin** [comment]
> Can the wait_for_search_finished() statement explain why no further uci commands (like stop or quit) are executed after once setoption has been called?

Well yes that’s why I posted it.. 
And there is no expected behavior according to the uci protocol really, every engine is free to interpret this like it wants to.

**Comment by cernst72** [comment]
Agree. This "expectation" cannot be derived from the uci protocol.
As a user I like the feature to adjust the pv, which is present in former Stockfish versions and other engines, very much and would be glad if it could be maintained by Stockfish again.

**Comment by vondele** [comment]
I don't think we should do this, consider it was working by accident, now it is consistent with e.g. Hash as pointed out.

**Comment by Disservin** [comment]
Yeah.. I think the blocking stdin is not ideal, we should probably ignore the setoptions all while searching, instead of stopping search.

**Comment by vondele** [comment]
it is just a mistake of the user / GUI to send setoption if the search is ongoing. The search is ongoing if it has been started with a go, for as long as bestmove hasn't been returned.

**Comment by locutus2** [comment]
@RogerThiede 
From your link you can also read in the setoption chapter that a setoption will be sent only when the egnine is waiting as @vondele  mentionend already.

![grafik](https://github.com/official-stockfish/Stockfish/assets/953505/45f48729-d38a-436b-8651-a7d2c136cf7c)

**Comment by locutus2** [comment]
Sorry, removed post because i haven't overlooked Disservin citation of UCI specs

**Comment by locutus2** [comment]
I'am personnaly have no preference between old and new behavior, but technically SF implements the UCI protocol more correct.

**Comment by cernst72** [comment]
As a user I still want to be able to interact with a very long (> 1 h) search like letting it run with multiple pv for a few minutes then narrowing the search to the top 1 or 2 pvs.

I understand that you don't want to support `go, setoption, setoption ...`.
But, as [RogerThiede](https://github.com/official-stockfish/Stockfish/issues/5137#issuecomment-2025827843) and Disservin pointed out, the way you do this is not conforming to the protocol either.
Of course, once a user has understood his "mistake" (calling `setoption` after `go`) he will probably not try it again, so not much worry.
(But still, why do you need to block yourself and your users, instead of being generous and allowing users to play with `setoption` and see what they get?  Yes, because the protocol says so.)

The alternative way, `position, go, stop, setoption, go`, is not easy going with Stockfish 16.1 too: The second `go` does not resume from your position, but the search starts over from startpos.
So you more or less have to start from scratch after stop. 

Can you recommend a way to reduce the pv of a long-running search?

**Comment by Sopel97** [comment]
https://xkcd.com/1172/

**Comment by Disservin** [comment]
Wdym the second go doesn’t resume from your position? It should (but can’t test right now).

Which gui are you evening using ? We had a look at a few GUIs and they all anyway send stop before iirc.

Why would you want to reduce the pv? Or do you mean multiPV?

I think what you even did in the past never even really worked. I think the setting for the multipv is saved after starting the search and only the output you get is read dynamically from the options. Which means multipv was still running with the same setting as it did before only what you visually see has changed.

**Comment by cernst72** [comment]
> Wdym the second go doesn’t resume from your position? It should (but can’t test right now).
Oh, yes it does. I tested on the console, but made a mistake when entering the position command (omitting "fen"). Sorry for this confusion.
I begin to understand, that I will have to adjust my workflow. So feel free to close this issue.

**Comment by cernst72** [comment]
Yes. I should stop() before calling setoption(). Thank you, Disservin, for looking at it!
