### ISSUE TITLE
False evaluations for positions with multiple knights

### ISSUE THREAD

**Issue by Kad314-777** [official-stockfish/Stockfish#5140]
### Describe the issue

After very quickly searching to depth 245, Stockfish dev-20240322-d99f8950 gives an evaluation of 0.00 in several positions with king vs king and 3 or more knights.

### Expected behavior

Stockfish should find the checkmate before reaching depth 245.

### Steps to reproduce

Example FEN positions:
1. "2k5/2N5/N2N2N1/2N1N3/8/8/8/4K3 b - - 117 14" (should be mate in two plies)
2. "8/3k4/8/8/4N3/5N2/6N1/7K b - - 117 14" (should be mate in 15)

### Operating system

Windows

### Stockfish version

Stockfish dev-20240322-d99f8950

**Comment by dav1312** [comment]
The problem is the 50mr counter is at 117 thus the positions are draws

**Comment by Kad314-777** [comment]
My bad, I did not start a new game in Arena before setting up those positions. Thank you for your reply.
