### ISSUE TITLE
Clang is faster on AARCH64, than GCC.  Stockfish is around 4 times slower when compiling with GCC 

### ISSUE THREAD

**Issue by beansofhell** [official-stockfish/Stockfish#5152]
### Describe the issue

I am an arch user. I am using Fishtest. to contibute on https://tests.stockfishchess.org/contributors

my username is 
Orikeshetisrael 

when using CLANG. its much faster running.. 

(also tell me how to send an actual report )

### Expected behavior

To be exaclly the same as GCC.. 

its very off that LLVM would be much faster for arm64. atleast put a minor notice in the documentation even tho , no one ever read those 

### Steps to reproduce

---- non, within compiling

### Anything else?

AARCH CLANG LLVM 

### Operating system

Linux

### Stockfish version

DEV version / whatever is running on fishtest

**Comment by beansofhell** [comment]
Could be an issue with me , I didnt removed the idea, that fishtest was running a smaller NN. but I am pretty sure this is whats going on here... again I am using ARM64 , on Oracle Cloud, VM, Arm - Ampere cpus .. 4-vCPUs

**Comment by beansofhell** [comment]
fyi 
![image](https://github.com/official-stockfish/Stockfish/assets/126506518/05e12c81-a937-4759-8701-44fc62d3305a)

I am using 4cores and check how fast it is

**Comment by Disservin** [comment]
provide some actual benchmarks.. 
```
Steps to reproduce
``` 

here you would post your compilation command..

**Comment by vondele** [comment]
No difference for me:
```
$ uname -m && ./stockfish bench 2>&1 | tail -n 4 && ./stockfish.clang bench 2>&1 | tail -n 4
aarch64
===========================
Total time (ms) : 1650
Nodes searched  : 1759189
Nodes/second    : 1066175
===========================
Total time (ms) : 1647
Nodes searched  : 1759189
Nodes/second    : 1068117
```

**Comment by Torom** [comment]
Since 5001d49, gcc is faster for me on aarch64 again, which hasn't been the case for a long time.
However, it is known that clang produces faster binaries on some hardware.

**Comment by vondele** [comment]
a few percent might be, but not a 4x slowdown.

**Comment by Disservin** [comment]
Closing since the issue lacks valuable information about compiler versions and how the performance was being compared.
