### ISSUE TITLE
Issue with the benchmark

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#5156]
### Describe the issue

I ran the benchmark of Stockfish 16 and Stockfish 16.1.
Result:
Stockfish 16: 1536 nps
Stockfish 16.1: 872 nps
Why such a steep drop in speed?

### Expected behavior

Not this behavior

### Steps to reproduce

.\Stockfish16 bench
.\Stockfish16.1 bench

### Operating system

All

### Stockfish version

Stockfish 16/16.1

**Comment by dav1312** [comment]
The NNUE architecture changed, the net is bigger and thus slower. This is not an issue.

**Comment by Disservin** [comment]
Speed changes mostly due to different network sizes..
```
16:     1823913
16.1:   1210743
master: 1096393
```

**Comment by amchess** [comment]
No: imho, the problem isn't the network size.
I think the refactoring with the worker isn't no funcitonal changes.
For example, in position.cpp there are the following lines:
```
        // Update material hash key and prefetch access to materialTable
        k ^= Zobrist::psq[captured][capsq];
        st->materialKey ^= Zobrist::psq[captured][pieceCount[captured]];
```
but the materialTable has been deleted and there is no prefetch.

**Comment by Disservin** [comment]
> No: imho, the problem isn't the network size. I think the refactoring with the worker isn't no funcitonal changes. For example, in position.cpp there are the following lines:
> 
> ```
>         // Update material hash key and prefetch access to materialTable
>         k ^= Zobrist::psq[captured][capsq];
>         st->materialKey ^= Zobrist::psq[captured][pieceCount[captured]];
> ```
> 
> but the materialTable has been deleted and there is no prefetch.

?? Just the comment is outdated... so what `k` and `materialKey` are still both used..

**Comment by Disservin** [comment]
```
Sf 16:      
 L1:  1536, nn-5af11540bbfe.nnue
 nps: 1823913

Sf 16.1:
 L1:  2560, nn-b1a57edbea57.nnue
 nps: 1210743 

(with smaller network)
Sf 16.1:
 L1: 1536, nn-5af11540bbfe.nnue
 nps: 1472458

master: 1096393
```

Sf 16, still used a mixed of classical and main net, where the classical part is probably giving the other additional speedup.

Sf 16.1 uses the main net and the small net, with classical completely removed...

**Comment by PGG106** [comment]
pointing out that this issue was duplicated in #5157

**Comment by Vizvezdenec** [comment]
issue is that you are a complete fucking idiot that never bothered to understand anything, period

**Comment by WampServer** [comment]
@Vizvezdenec Using profanity, verbally attacking or insulting someone might give you a warning or even a temporary block - please be nice and polite.

**Comment by peregrineshahin** [comment]
IMO we should block the both trolls @WampServer and @amchess from this Repo.
