### ISSUE TITLE
Broken cross compiling to 32-bit on 64-bit host

### ISSUE THREAD

**Issue by braich** [official-stockfish/Stockfish#516]
Under 64-bit OS 64-bit compiler creates a working executable when make is invoked with ARCH=x86-32. But this executable is working only under 64-bit OS and not working under 32-bit OS.

**Comment by mstembera** [comment]
This has been the case for a long time for me as well.  Even before
https://github.com/official-stockfish/Stockfish/pull/511
which is unrelated but offers a clue that we should be invoking a different compiler binary depending on whether we are building 32 or 64 bit binaries.

**Comment by zamar** [comment]
I don't think that we've ever really supported cross-compiles in our Makefile.

And I'm not sure that we even should... It can easily create a big mess.

The only exception is Linux->Windows cross-compile, because this is a very common use-case.

**Comment by zamar** [comment]
We do not provide support for out of the box cross-compiling. Thus nothing is broken.

People can hack the Makefile privately as much as they please. But this is not something that will go into main branch UNLESS someone finds really nice, cute and generic solution (but it's unlikely to happen).

Thus I'm closing this issue.
