### ISSUE TITLE
issue when running the .exe of version 16.1 on Windows.

### ISSUE THREAD

**Issue by 420Avila** [official-stockfish/Stockfish#5179]
### Describe the issue

I'm having trouble running the Excel. It results in a command prompt with the following line:
![imagen](https://github.com/official-stockfish/Stockfish/assets/108857178/6b4473bf-d9a7-476e-aa05-5f7dc2cd146c)

### Expected behavior

I searched on the internet on this site: https://lichess.org/forum/general-chess-discussion/stockfish-151 and followed the instructions, but unfortunately, I didn't get positive results. Could you please help me? Or could it be a problem with my computer? Thank you.

### Steps to reproduce

Stockfish 16.1 by the Stockfish developers (see AUTHORS file)

### Operating system

Windows

### Stockfish version

Stockfish 16.1

**Comment by Disservin** [comment]
https://github.com/official-stockfish/Stockfish/wiki/Stockfish-FAQ#executing-stockfish-opens-a-cmd-window
