### ISSUE TITLE
Faulty analysis - too big change of position value

### ISSUE THREAD

**Issue by hpojak** [official-stockfish/Stockfish#5208]
### Describe the issue

After a while, Stockfish suggests 33. Bf8 as the best move for black (evalued about -3).
If black moves Bf8, Stockfish suggests 34. e5 as the best move for white (evalued about +0).
So at once, the value changes 3 units.
If black instead chooses the second best move 33. Ra2, then the value of white's best
move is close to -3.

### Expected behavior

The value of the best move should not change drastically, as much as 3 units.
If the first move suggestion is correct, than the value of the best move for white should be
about -3.
Or at least I believe so, but I'm not a Stockfish expert.

### Steps to reproduce

PGN notation follows:

1.e4 e5 2.f4 exf4 3.Nf3 g5 4.Bc4 g4 5.O-O gxf3 6.Qxf3 Qf6
7.d3 Nc6 8.Bxf4 d6 9.Nc3 Nge7 10.Nb5 Kd8 11.d4 Ng6 12.Qg3 Nxf4 13.Rxf4
Qg6 14.Qf2 Be7 15.Bxf7 Qh6 16.h4 Rf8 17.Rf1 Bd7 18.a4 a6 19.Nc3 Qg7 20.Ne2
Kc8 21.c3 Nd8 22.Bc4 Rxf4 23.Nxf4 b5 24.axb5 axb5 25.Be2 c6 26.Nd3 Qg6
27.Bf3 Kc7 28.Qe1 Qg7 29.Kh1 Nf7 30.g3 Nh6 31.Nf4 Ng4 32.Rg1 Qg8 33.Qe2 1-0

### Anything else?

Using scid as frontend.
Using NNUE nn-5af11540bbfe.nnue.
Hash memory 30, threads 9.
Sorry I can't get the exact version of Stockfish, but it was probably the latest available on Jan 30, 2024.

### Operating system

Linux

### Stockfish version

Version 16, stockfish-ubuntu-x86-64-avx2, downloaded Jan 30, 2024

**Comment by R-Goc** [comment]
Can't replicate on Windows x86-64-bmi2, current stockfish version dev-20240501-be142337 (Evalfile nn-ae6a388e4a1a.nnue and nn-baff1ede1f90.nnue). 
Steps taken:
position fen r4bq1/2kb3p/2pp4/1p2P3/3P1NnP/2P2BP1/1P2Q3/6RK b - - 0 34
setoption name Threads value 8
setoption name Hash value 8096
go depth 40

output:
info depth 40 seldepth 73 multipv 1 score cp 389 nodes 1974145516 nps 4732039 hashfull 841 tbhits 0 time 417187 pv d6e5 d4e5 a8e8 g1d1 g4e5 e2e3 g8a2 e3d4 c7c8 f3e4 a2c4 d1a1 c4d4 c3d4 e5g6 f4g6 h7g6 e4g6 e8d8 g6e4 c8c7 d4d5 c6d5 e4d5 f8g7 a1c1 c7d6 c1d1 g7b2 d5f3 d6c7 h1g2 b5b4 g3g4 b2h8 d1c1 c7d6 c1d1 d6e7 d1e1 d7e6 g4g5 h8c3 e1e3 d8d2 e3e2 d2e2 f3e2 e6d5 g2h3 b4b3
bestmove d6e5 ponder d4e5

Eval has an upward trend with depth.
Please provide the depth you reached or number of nodes.

**Comment by hpojak** [comment]
Unfortunately I can't replicate the error myself, neither via scid, nor stockfish/UCI.
There is a risk that a bug resides within scid, instead. But I can't tell.
