### ISSUE TITLE
Disappointed with the project

### ISSUE THREAD

**Issue by ghost** [official-stockfish/Stockfish#5222]
### Describe the issue

The Stockfish project had always been an interesting project, with programmers and chess enthusiasts working together. Even the rivalry with Lc0, especially at the start, was intense and rewarding.
However, in recent years, with the adoption of NNUE and governing changes, the project has experienced an unprecedented downfall I couldn't even imagine. Former and respected members and contributors of the project, and even creators, were being ignored and left aside. Their opinions were not taken into account, and only "the experts" in the field of AI had any voice. This is not only disappointing, but also pathetic.
I think former mantainers did a great job. Even @snicolet and @vondele did a great job. @Disservin however is not a good fit at all. All the fast changes and bugs introduced show his ineptitude. Such a big project cannot be lead by childish people who see Stockfish as a simple piece of software they can change at their will. This is a historic project, and an amazing piece of software and research.
It is an insult to the project to be in this state. Latest changes are also depressing. Many simplifications made by a bunch of users, and some stupid changes which don't make any sense.
I thought this was a friendly project, which is also not. Many rude answers, disrespectful treat towards people, and lack of help for new developers.
Stockfish is getting abandoned, and it shouldn't be that way. I could say I'm sorry, but I am not. I think this is what you deserve. You destroyed a beautiful project which will never recover from such detrimental state. Its end is near, just as happened with the Komodo team. In the old days this wouldn't happen. Those were great times. The community was fair, enthusiastic and friendly, far away from what it is now.
I really hope other projects like Torch or Lc0 catch up. Or newer projects like Obsidian. I want to see Stockfish destroyed. Its original purpose was nice, now it's become a rotten place. Again, this is pathetic.
I hope you will realize soon. It would be better for you. You then wonder why less people contribute. Here is the answer.
You're welcome

### Expected behavior

The old days were good

### Steps to reproduce

This is pathetic

### Operating system

Other or N/A

### Stockfish version

Stockfish

**Comment by Disservin** [comment]
https://github.com/official-stockfish/Stockfish/compare/sf_16...sf_16.1 in the last minor release 56 different contributors contributed to the project according to Github. Clearly not dying in my eyes.
