### ISSUE TITLE
Castling doesn't work in non-standard positions (Stockfish macOS application)

### ISSUE THREAD

**Issue by Python3-8** [official-stockfish/Stockfish#5294]
### Describe the issue

I'm not sure if this is a bug or if it was intended. I'm using the macOS app and loaded this position:
![image](https://github.com/official-stockfish/Stockfish/assets/66139317/8e8511ef-f7eb-4007-b208-5e97d44a399e)
```fen
k6r/8/8/8/8/8/8/K6R w Kk - 0 1
```
In this position both sides have kingside castling rights but it's not a _standard_ position where the kings are on e1 and e8, and the rooks on h1 and h8. Now, as expected, when I click on the white king on a1, the squares a2, b2, b1 get highlighted along with g1 because it can castle:
![image](https://github.com/official-stockfish/Stockfish/assets/66139317/a2e72c7f-660a-431c-b9d9-c0fa9fca14e1)
As expected, when I then click on a2, b2, or b1 the king moves there. However when I click on g1 nothing happens and the king just gets unselected.

Here's a video of this behavior:
https://github.com/official-stockfish/Stockfish/assets/66139317/96389cd3-f192-4052-9dd5-a04fd539a731

### Expected behavior

What I expect is for the white king to move to g1, and the white rook to f1.

### Steps to reproduce

Copy this FEN string:
```fen
k6r/8/8/8/8/8/8/K6R w Kk - 0 1
```
And select File > New from Clipboard (or press ⇧⌘N) on the Stockfish macOS app.
Trying to castle as white will reproduce this behavior.

### Operating system

MacOS

### Stockfish version

Stockfish 16.1

**Comment by Disservin** [comment]
This isn’t the correct repository for the macos app, which is also kot officially maintained by us.

**Comment by Disservin** [comment]
See https://github.com/daylen/stockfish-mac
