### ISSUE TITLE
Stockfish bug in version:  May 30 14:34:24 2024 +0200 Timestamp: 1717072464

### ISSUE THREAD

**Issue by tdh1967** [official-stockfish/Stockfish#5318]
### Describe the issue

I've downloaded hundreds of the pre-releases and this version is only the second time I've experienced that the UCI Stockfish cannot be created in the chessbase/fritz interface.  There is an issue preventing it.  There is no reported error, it just doesn't work.  

### Expected behavior

I expected to create the UCI engine it in the same manner of steps as hundreds of previous pre-release versions of Stockfish, in the Chessbase/Fritz interface. 

### Steps to reproduce

Check with anyone else you know that uses Fritz interface to create a UCI and they can verify this.   The UCI of this latest version, (timestamp 1717072464) cannot be created.

### Anything else?

N/A

### Operating system

Windows

### Stockfish version

Pre-release: Thu May 30 14:34:24 2024 +0200 Timestamp: 1717072464

**Comment by vondele** [comment]
did you happen to install a linux binary from abrok ? 

If so, please install a windows pre-release from https://github.com/official-stockfish/Stockfish/releases instead.

**Comment by tdh1967** [comment]
That did work.  Thank you.  I had gotten the file from: https://abrok.eu/stockfish/

**Comment by dav1312** [comment]
Abrok is currently broken and is not producing Windows binaries so you probably downloaded Linux binaries by mistake.

> [!NOTE]
> Abrok is a 3rd party so we can't guarantee the safety, reliability, and availability of those binaries because are not responsable for them. That is why we recommend downloading from the [official GitHub releases](https://github.com/official-stockfish/Stockfish/releases).
