### ISSUE TITLE
Abrok Windows buildbot has broken since a169c78b6d3b082068deb49a39aaa1fd75464c7f

### ISSUE THREAD

**Issue by ofry** [official-stockfish/Stockfish#5320]
### Describe the issue

Abrok Windows buildbot https://www.abrok.eu/stockfish/ has broken since a169c78b6d3b082068deb49a39aaa1fd75464c7f

### Expected behavior

Windows versions should be built.

### Steps to reproduce

1. Go to https://www.abrok.eu/stockfish/
2. See list of available versions.

Now only Linux versions built fine on this buildbot.

### Operating system

Windows

### Stockfish version

a169c78b6d3b082068deb49a39aaa1fd75464c7f

**Comment by vondele** [comment]
please install a windows pre-release from https://github.com/official-stockfish/Stockfish/releases instead.

**Comment by dav1312** [comment]
> [!NOTE]
> Abrok is a 3rd party so we can't guarantee the safety, reliability, and availability of those binaries because are not responsable for them. That is why we recommend downloading from the [official GitHub releases](https://github.com/official-stockfish/Stockfish/releases).

**Comment by Disservin** [comment]
@ofry  latest windows versions are back but please for the future refer to  https://github.com/official-stockfish/Stockfish/releases, thanks.
