### ISSUE TITLE
TranspositionTable::resize slow

### ISSUE THREAD

**Issue by jdp1024** [official-stockfish/Stockfish#5350]
### Describe the issue

It takes `TranspositionTable::resize` several seconds to finish.

### Expected behavior

Less time.

### Steps to reproduce

```
setoption name NumaPolicy value system
setoption name Threads value 256
setoption name Hash value 40000
```

It takes 6 seconds on a dual EPYC 7763 system running Windows 11.

### Anything else?

`TranspositionTable::resize` allocates memory for the cluster on large pages. It calls `make_unique_large_page` which calls `memory_allocator` which initializes the allocated memory in a sequential way by

```
    for (size_t i = 0; i < num; ++i)
        new (raw_memory + array_offset + i * sizeof(ElementType)) ElementType();
```

but the memory should be cleared later by the threaded `TranspositionTable::clear` function.

A temporary fix to test:

```
// Allocates memory for an array of unknown bound and places it there with placement new.
template<typename T, typename ALLOC_FUNC>
inline std::enable_if_t<std::is_array_v<T>, std::remove_extent_t<T>*>
memory_allocator2(ALLOC_FUNC alloc_func, size_t num) {
    using ElementType = std::remove_extent_t<T>;

    const size_t array_offset = std::max(sizeof(size_t), alignof(ElementType));

    // save the array size in the memory location
    char* raw_memory =
      reinterpret_cast<char*>(alloc_func(array_offset + num * sizeof(ElementType)));
    ASSERT_ALIGNED(raw_memory, alignof(T));

    new (raw_memory) size_t(num);

    // ------------------------- relinquo ;)
    //for (size_t i = 0; i < num; ++i)
    //    new (raw_memory + array_offset + i * sizeof(ElementType)) ElementType();

    // Need to return the pointer at the start of the array so that the indexing in unique_ptr<T[]> works
    return reinterpret_cast<ElementType*>(raw_memory + array_offset);
}

// make_unique_large_page for arrays of unknown bound
template<typename T>
std::enable_if_t<std::is_array_v<T>, LargePagePtr<T>> make_unique_large_page2(size_t num) {
    using ElementType = std::remove_extent_t<T>;

    static_assert(alignof(ElementType) <= 4096,
                  "aligned_large_pages_alloc() may fail for such a big alignment requirement of T");

    ElementType* memory = memory_allocator2<T>(aligned_large_pages_alloc, num);

    auto r = LargePagePtr<T>(memory);
    return r;
}

// Sets the size of the transposition table,
// measured in megabytes. Transposition table consists
// of clusters and each cluster consists of ClusterSize number of TTEntry.
void TranspositionTable::resize(size_t mbSize, ThreadPool& threads) {
    clusterCount = mbSize * 1024 * 1024 / sizeof(Cluster);

    table = make_unique_large_page2<Cluster[]>(clusterCount);

    if (!table)
    {
        std::cerr << "Failed to allocate " << mbSize << "MB for transposition table." << std::endl;
        exit(EXIT_FAILURE);
    }

    clear(threads);
}
```

It removes the memory initialization part. After it, `setoption name Hash value 40000` takes less than 1 second.

### Operating system

All

### Stockfish version

00a28ae325688346e63a452b2050bd1491085359

**Comment by vondele** [comment]
https://github.com/official-stockfish/Stockfish/commit/7f09d06b834a5aaedbc78c5161ba91a8d6761421 

Can you verify this fixes it for you?

**Comment by Disservin** [comment]
Sorry for all the noise recently.. we are also looking at a way how we can restore the old behaviour for CB without requiring you to hack the dll.  

The mentioned commit from vondele should fix this issue.

If anything else comes (hopefully not) feel free to reopen/make a new issue.

**Comment by jdp1024** [comment]
> [7f09d06](https://github.com/official-stockfish/Stockfish/commit/7f09d06b834a5aaedbc78c5161ba91a8d6761421)
> 
> Can you verify this fixes it for you?

It works for me.

**Comment by jdp1024** [comment]
> Sorry for all the noise recently.. we are also looking at a way how we can restore the old behaviour for CB without requiring you to hack the dll.
> 
> The mentioned commit from vondele should fix this issue.
> 
> If anything else comes (hopefully not) feel free to reopen/make a new issue.

About `TranspositionTable::resize` again: if `setoption name Hash value xxxxx` is called for multiple times with the same value (this is what CB does), what is the expected result? Is it necessary to reallocate the memory and clear it for multiple times?

**Comment by Disservin** [comment]
> > Sorry for all the noise recently.. we are also looking at a way how we can restore the old behaviour for CB without requiring you to hack the dll.
> > The mentioned commit from vondele should fix this issue.
> > If anything else comes (hopefully not) feel free to reopen/make a new issue.
> 
> About `TranspositionTable::resize` again: if `setoption name Hash value xxxxx` is called for multiple times with the same value (this is what CB does), what is the expected result? Is it necessary to reallocate the memory and clear it for multiple times?

Mh expected result is a vague term.. in the code we want to ensure that each thread zeros its part of the TT on the according thread because of the numa first touch policy.. which is something I overlooked when writing my earlier patch.

The behaviour always has been that the TT will be freed and reallocated whenever the hash or the threads option are set.

If you want to make this a bit smarter, then I think one could skip this for the case where the Threads haven't changed and the Hash hasn't changed.

**Comment by Disservin** [comment]
Can you post everything which CB sends to stockfish when the engine starts ? Would be useful to have that

**Comment by jdp1024** [comment]
> Can you post everything which CB sends to stockfish when the engine starts ? Would be useful to have that

I record `cmd` in `UCIEngine::loop`.

The main engine:

```
uci
setoption name Hash value 410
isready
setoption name NumaPolicy value system
setoption name Threads value 145
setoption name MultiPV value 6
position startpos
go infinite
stop
quit
```

The buddy engine:

```
uci
setoption name Hash value 102
isready
setoption name NumaPolicy value system
setoption name Threads value 35
quit
```

__Sometimes__ (not every time) `setoption name Hash value XXX` will be received 2 times.

**Comment by Sopel97** [comment]
the hash will be reallocated 3 times here, because CB's order of applying options is bad. The order should be NumaPolicy -> Threads -> Hash. Setting NumaPolicy reallocates threads, and reallocating threads reallocates hash. This is to ensure that threads are new and bound to the correct processors, and to ensure the TT is spread out evenly over all processors actually being used, respectively. This cannot be postponed until after the search starts due to how UCI works. I'd suggest filing a support ticket at CB.

**Comment by Disservin** [comment]
Yeah it is a bit sad that uci has no way of sending multiple commands together, then we could filter out the duplicated parts..

**Comment by Disservin** [comment]
What I think is possible is to specify the uci options as cli arguments when starting the engine, then we could actually remove the redundant reallocations… but this isn’t so user friendly

**Comment by jdp1024** [comment]
> the hash will be reallocated 3 times here, because CB's order of applying options is bad. The order should be NumaPolicy -> Threads -> Hash. Setting NumaPolicy reallocates threads, and reallocating threads reallocates hash. This is to ensure that threads are new and bound to the correct processors, and to ensure the TT is spread out evenly over all processors actually being used, respectively. This cannot be postponed until after the search starts due to how UCI engines are expected to work. I'd suggest filing a support ticket at CB.

I don't think they care to solve it. I have reported 20+ problems, for most of them I didn't even receive a reply.

For the order of UCI commands, I guess that they think the `setoption` commands can be regarded as a whole, they become effective when `go` is executed, the order doesn't matter.

**Comment by Disservin** [comment]
would be rather foolish to think that because the engine would always loose with short time controls in that case because it needs to initialize the TT … :p

**Comment by Sopel97** [comment]
they don't even use isready correctly so...
