### ISSUE TITLE
Maybe? Perft NPS report issue.

### ISSUE THREAD

**Issue by PikaCat-OuO** [official-stockfish/Stockfish#5351]
### Describe the issue

The node count may not be correct.
Wrong code suspicion in:
https://github.com/official-stockfish/Stockfish/blob/ba06671aa9df5c0a3fa5f1fa2ce17ea4aa742b7a/src/uci.cpp#L299

The `nodes` in this line should be `nodesSearched`? Otherwise only the nodes of the last position get reported.

### Expected behavior

Report correct node count.

### Steps to reproduce

```bench 16 1 5 default perft```

### Operating system

All

### Stockfish version

ba06671aa9df5c0a3fa5f1fa2ce17ea4aa742b7a

**Comment by Disservin** [comment]
fixed by https://github.com/official-stockfish/Stockfish/commit/4f53560d248195b172ac97d7c74e6bcfc65fe6fd
