### ISSUE TITLE
Bench inconsistency

### ISSUE THREAD

**Issue by PikaCat-OuO** [official-stockfish/Stockfish#5376]
### Describe the issue

When running the stockfish binary with two consecutive `bench` command. The nodes searched is different.
This seems to be consistent before.
Commit d1a71fdaa7cc7d749495bbf5d63919a4a0b42303 probably causes this unexpected behavior.

### Expected behavior

Consistent bench.

### Steps to reproduce

```
Stockfish dev-20240605-5688b188 by the Stockfish developers (see AUTHORS file)
bench 16 1 15
...
===========================
Total time (ms) : 2678
Nodes searched  : 2964957
Nodes/second    : 1107153

bench 16 1 15
...
===========================
Total time (ms) : 5535
Nodes searched  : 3089159
Nodes/second    : 558113
```

### Operating system

All

### Stockfish version

5688b188cc8560e107815c83a7084220fddebdb9

**Comment by Disservin** [comment]
Do you rely on this behavior ? Meaning writing bench in the engine directly via stdin? Writing bench multiple times via stdin has some weird consequences, where I am currently considering to remove that functionality altogether and only allowing it to be run from the cli.

**Comment by vondele** [comment]
We use bench from the stdin also in fishtest, and I think it is common usage (I use that regularly as well). What is less common is running it multiple times.

**Comment by peregrineshahin** [comment]
The patch mentioned writes on old entries instead of empty ones based on generation key.. this must be related.
We do search_clear in ucinewgame which clears the hash so what is that is not reset to default state also?
generation8?

**Comment by Disservin** [comment]
Mh okay, then maybe we should exist immediately? Bench has the problem that it currently isn’t well splitted, I.e after running multithreaded bench you will have multiple threads still set afterwards or chess960 be enabled…

**Comment by vondele** [comment]
I don't think we should exit.... we could of course easily fix the chess960 one if that's the one that is causing problems. I don't think bench should 'promise' not to alter the settings, but I think it should set the settings it expects. (i.e. cli behavior, it could set all options back to default).

**Comment by PikaCat-OuO** [comment]
> Do you rely on this behavior ? Meaning writing bench in the engine directly via stdin? Writing bench multiple times via stdin has some weird consequences, where I am currently considering to remove that functionality altogether and only allowing it to be run from the cli.

I'm not rely on it, just observed this behavior and don't know if it's intended or something breaks.

**Comment by cj5716** [comment]
The issue was that generation8 was not being reset on ucinewgame. This should be fixed in the PR

**Comment by vondele** [comment]
OK, that's actually a serious bug.
