### ISSUE TITLE
Crash with Chesspartner

### ISSUE THREAD

**Issue by samerhello** [official-stockfish/Stockfish#5393]
### Describe the issue

i noticed problem when i import uci developer stocfish engine to chesspartner software since (Joost VandeVondele time stamp 1717103245) version can i tell you please

### Expected behavior

please fix

### Steps to reproduce

(Joost VandeVondele time stamp 1717103245)

### Anything else?

(Joost VandeVondele time stamp 1717103245)

### Operating system

Windows

### Stockfish version

123456sagh

**Comment by Disservin** [comment]
@samerhello Please provide more information on what is not working.. what windows version are you using?

fyi @vondele I think the referenced commit is likely https://github.com/official-stockfish/Stockfish/commit/54e74919d478def20cb103d1e9677a696073c92f, timestamp 1717098168, since the next commit is at 1717117262

**Comment by samerhello** [comment]
ok , i am using windows 10 x64 , and software chesspartner 6.0.1 to use
developer chess stockfish engine , but when i used the version that i
attached a picture about it , the software stoped and shut down if you want
more i can send gif about that

**Comment by samerhello** [comment]
i do not know anything about programming , i just want new (exe) developer
version that do not make this problem , i am very happy to deal with those
strongest developer

**Comment by samerhello** [comment]
![2024-06-15_11-09-36](https://github.com/official-stockfish/Stockfish/assets/138357603/5011b94f-95a5-4a42-949b-def3d6a56b9e)

**Comment by vondele** [comment]
Have you tried using that stockfish exe with a different GUI, it would be good to know if this only happens under chesspartner. For a list of GUIs please see https://github.com/official-stockfish/Stockfish/wiki/Download-and-usage#download-a-chess-gui

**Comment by samerhello** [comment]
ok but chesspartner is only pc version that simple for my pc and i use it
since 2004 , and to fix what happened(  if i show you on video ) is easy
than to search for other software   and the calculation of it is very
clear   , and you are profissional and to fix programming developer version
is easy to you , and chesspartner not only gui is program to easy put
position and other

**Comment by vondele** [comment]
Can you check if our latest update works for you, it contains a fix that might help certain GUIs:

https://github.com/official-stockfish/Stockfish/releases/tag/stockfish-dev-20240615-2046c92a

**Comment by samerhello** [comment]
ok the last one working is (  Author: Disservin  :  Date: Tue May 28
18:31:06 2024 +0200 ,  Timestamp: 1716913866 ) and after that all
developers do not have ( exe ) only bmi2 no exe till the version that have
exe i have this problem from it and i told what version specifications ,
and i will check latest update , thank you professional for your polite

**Comment by vondele** [comment]
OK, be sure to download a windows binary that will have the .exe suffix, without .exe you probably have a linux binary.

**Comment by samerhello** [comment]
before at the same specifications it is work

**Comment by samerhello** [comment]
i can not replace any window or format pc ,  before i asked the same
question and same problem a many years ago and you fixed it , if you want i
will send gif about this , but after i try what you told me about

**Comment by samerhello** [comment]
i mean your message
Can you check if our latest update works for you, it contains a fix that
might help certain GUIs:
https://github.com/official-stockfish/Stockfish/releases/tag/

1:48 PM (10 hours ago)

**Comment by samerhello** [comment]
Hello,
We have become accustomed to your constant responsiveness and your continuous efforts to ensure that development versions are compatible with all programs. Therefore, I will resend my question to you in a clearer way, including a GIF clip that illustrates the issue. What happened is : that the last version that worked for me was version (Author : Disservin , Tue May 28 timestamp 1716913866) , but unfortunately when version (Author : Joost VandeVondele , Tue May 30 , Timestamp : 1717103245) was released, the problem shown in the attached GIF occurred and has persisted to this day. So please, please, please fix this, because I am used to your site and if the problem continues I will stop downloading any new versions and will stay on version (tue may 28)
I have always appreciated your responsiveness and cooperation in the past, and I hope you will continue to do so.
Thank you,
Note1 : Attached is a GIF clip that illustrates the issue.
note 2 : 
(please when i check if your latest update works for me , https://github.com/official-stockfish/Stockfish/releases/tag/ ) there is no webpage and 404 error 
![Animation](https://github.com/official-stockfish/Stockfish/assets/138357603/80b438cf-7b9d-40e6-b14d-6d1008aca3a1)

**Comment by Disservin** [comment]
@samerhello for me it isn't clear if you have a system which supports bmi2? Also gifs are awful, I can't fast forward...
Anyway did you try a non bmi2 version from here https://github.com/official-stockfish/Stockfish/releases ? Click on assets and choose a version from there.

**Comment by samerhello** [comment]
To desservin ,  i said my system was working very good without any discussion about  bmi2

**Comment by Viren6** [comment]
The commit may prevent you from using the incorrect binary for your system. In this case, the only solution is to use the correct binary

**Comment by samerhello** [comment]
to Viren6 ok but what happened between first version that i explained in jif tha working , and the second that stops

**Comment by samerhello** [comment]
i tried  download from  https://github.com/official-stockfish/Stockfish/releases ( same problem )

**Comment by samerhello** [comment]
to disservin , this [stockfish-windows-x86-64-avx2.zip](https://github.com/official-stockfish/Stockfish/releases/download/stockfish-dev-20240615-2046c92a/stockfish-windows-x86-64-avx2.zip) and the cpu is tha same from 2019 and everything was work good  , please see carefully gif to release new developer version to site (https://abrok.eu/stockfish/) that is working , i said yor version ((Author : Disservin , Tue May 28 timestamp 1716913866 ) was working good with all downloads kinds , but after that , the version (Author : Joost VandeVondele , Tue May 30 , Timestamp : 1717103245 ) have problem to me  

please see carefully gif , and release new developer version to site (https://abrok.eu/stockfish/) that is working 
i know you can make it

**Comment by samerhello** [comment]
i suffered from same problem a years ago and dr vondele solve it , but returned the problem again in new versions

**Comment by samerhello** [comment]
i hope developer version compatible for any condisions

**Comment by samerhello** [comment]
to disservin : Because the site only takes GIFs, I had to upload a bad type of video, which is GIFs

**Comment by Viren6** [comment]
Hm you should try another GUI. Just as a test, not to permanently use. It will help the devs isolate the issue

**Comment by samerhello** [comment]
Unfortunately , no hope , still not working in chess partner software , no hope to use any development version after 28/5/2024 version , i hope new stockfish 17 not include this bug

**Comment by Disservin** [comment]
@samerhello We have no control over https://abrok.eu/stockfish/, it is not from us. We can't fix binaries that they upload, they are created differently than the official ones.

> to disservin , this [stockfish-windows-x86-64-avx2.zip](https://github.com/official-stockfish/Stockfish/releases/download/stockfish-dev-20240615-2046c92a/stockfish-windows-x86-64-avx2.zip) and the cpu is tha same from 2019 and everything was work good , please see carefully gif to release new developer version to site (https://abrok.eu/stockfish/) that is working , i said yor version ((Author : Disservin , Tue May 28 timestamp 1716913866 ) was working good with all downloads kinds , but after that , the version (Author : Joost VandeVondele , Tue May 30 , Timestamp : 1717103245 ) have problem to me

- I am not sure if I understand your correctly.. does the version here https://github.com/official-stockfish/Stockfish/releases work ?
- Have you tried another GUI, even temporarily, the more you can help use the faster this will get resolved..

**Comment by vondele** [comment]
I have one suspicion what this could be, the `info` lines that are printed early on, as a reply to uci, that mess up the old GUI. I think the only way to see if that fixes the problem would be to build a windows binary with that removed, upload here, and as samerhello to test:

```diff
diff --git a/src/uci.cpp b/src/uci.cpp
index 4bc358d8a..001a7fd4e 100644
--- a/src/uci.cpp
+++ b/src/uci.cpp
@@ -108,10 +108,10 @@ void UCIEngine::loop() {
             sync_cout << "id name " << engine_info(true) << "\n"
                       << engine.get_options() << sync_endl;
 
+            sync_cout << "uciok" << sync_endl;
+
             print_info_string(engine.numa_config_information_as_string());
             print_info_string(engine.thread_binding_information_as_string());
-
-            sync_cout << "uciok" << sync_endl;
         }
 
         else if (token == "setoption")
```

While I can compile windows binaries, the binary does no longer work under wine, so can't test. Maybe somebody can provide such a binary?

**Comment by Disservin** [comment]
> While I can compile windows binaries, the binary does no longer work under wine, so can't test. Maybe somebody can provide such a binary?

you could use your fork for that ^^ just remove `official-stockfish/Stockfish` from the https://github.com/official-stockfish/Stockfish/blob/master/.github/workflows/stockfish.yml
to get the binaries as artificats after a push to your master branch

**Comment by vondele** [comment]
OK, will do.

**Comment by samerhello** [comment]
ok thank all for you in Follow your interest in the subject , hope to see new developer version working for me please

**Comment by vondele** [comment]
@samerhello can you try this binary in your GUI

https://github.com/vondele/Stockfish/releases/download/stockfish-dev-20240623-91c3bb62/stockfish-windows-x86-64-avx2.zip 

let us know if if works or fails.

**Comment by samerhello** [comment]
yes yes it worked thank you very much   , and hope to make this changes in
new development versions in (https://abrok.eu/stockfish/) you are
professionals , thank you and i respect you very much

**Comment by samerhello** [comment]
and also thank you dr vondele

**Comment by samerhello** [comment]
thank you all

**Comment by samerhello** [comment]
pro desservin give his toutches with dr vondele , bye

**Comment by samerhello** [comment]
very thank to dr vondele

**Comment by samerhello** [comment]
and very thank to stockfish and developers
