### ISSUE TITLE
SF compiled under Win10 by mingw64 doesn't install and doesnt work at Fritz 9

### ISSUE THREAD

**Issue by PavelChess** [official-stockfish/Stockfish#5396]
### Describe the issue

I have compiled latest source without any modifications under Win10 by mingw64, and the compile didn't work at Fritz 9.

When I tried to install it, the GUI got frozen.

I have compiled .uci file from my older compile and edited it for matching new one. When I tried to switch to the buggy compile I got error 1141.

Abrok versions can be installed, and they work.
Also my compile that doesnt work at Fritz 9, it works at Fritz 13.

### Expected behavior

Whe compie should work without problems. My previous compiles were of verion fo June 1st, and they worked.

### Steps to reproduce

Compile latest source at Win10 by mingw64
Try to install and run it at Fritz 9 or 8 or 7

### Operating system

Windows

### Stockfish version

2046c92a

**Comment by vondele** [comment]
@PavelChess can you test if these binaries work under Fritz 9:

https://github.com/vondele/Stockfish/releases/tag/stockfish-dev-20240623-91c3bb62

**Comment by PavelChess** [comment]
> @PavelChess can you test if these binaries work under Fritz 9:
> 
> https://github.com/vondele/Stockfish/releases/tag/stockfish-dev-20240623-91c3bb62

The test was successful!

I tested included exe, and then compiled sources on my computer under Win10 with mingw64, and they both worked.

By the way, there is another issue of Stockfish under Fritz 9 (that exist only there at older Fritz, but not in later and not at other UCI GUIs), that exists already some years: SF uses only 1 MB hash. Windows task manager cannot discover this, but Process Explorer can. Because of this I made for myself compiles with hash size locked on 1024 MB for example.

You can easily find old Fritz GUIs (Fritz 8, Fritz 9, Shredder 6) at abandonware sites and test the solution yourself.
