### ISSUE TITLE
Stockfish is no longer detected correctly in the Aquarium GUI

### ISSUE THREAD

**Issue by Coolchessguykevin** [official-stockfish/Stockfish#5430]
### Describe the issue

Dear developers,

After a series of recent patches, Stockfish stopped being added 
correctly as UCI engine to the Aquarium 2020 GUI. When trying to add an 
executable as a new UCI engine, the GUI freezes badly and cannot 
determine the correct engine UCI name. The GUI displays the exclamation 
mark as an error for a while. After about half a minute of waiting, the 
engine is added with the name of the executable file instead of the 
internal UCI name of the engine, and the UCI parameters are completely 
missing for another twenty seconds, after which they appear. But after 
all this I'm not sure that the engine now works correctly in this chess GUI.

This is observed on three different computers with BMI2, AVX512 and 
popcnt versions.

Please fix this. I only use official compilations from Githab releases page, the EXE 
versions are exactly suitable for my processors.

Best regards,
Ivan.

### Expected behavior

Correctly add Stockfish as new UCI engine to the Aquarium GUI

### Steps to reproduce

Download SF dev version and try to add as new UCI engine to the Aquarium GUI

### Operating system

Windows

### Stockfish version

Stockfish dev-20240701-6138a0fd

**Comment by vondele** [comment]
OK, most likely caused by https://github.com/official-stockfish/Stockfish/commit/5fbfd06171cadf97e6e8173216046b099ebfa43b which also causes python-chess errors/warnings.
