### ISSUE TITLE
Automatically replace "maximmasiutin" to "Maxim Masiutin" in the Top CPU Contributors.txt

### ISSUE THREAD

**Issue by maximmasiutin** [official-stockfish/Stockfish#5438]
### Describe the issue

Can you please automatically replace "maximmasiutin" to "Maxim Masiutin" in the Top CPU Contributors.txt file?

https://github.com/official-stockfish/Stockfish/blob/master/Top%20CPU%20Contributors.txt

You wrote that you have a script that does post-processing of the contributors data before creating the .txt file, such post-processing can, for example, merge contribution amount from various accounts or rename accounts.

There is already an example of a meaningful name with spaces in the file: Thomas A. Anderson 

### Expected behavior

Have "Maxim Masiutin" rather than "maximmasiutin" in the Top CPU Contributors.txt file

### Steps to reproduce

View the https://github.com/official-stockfish/Stockfish/blob/master/Top%20CPU%20Contributors.txt file, search for "maximmasiutin" in this file

### Anything else?

I asked this in Discord a few months ago.

### Operating system

All

### Stockfish version

Any version

**Comment by Disservin** [comment]
Sorry we won't be doing that. We only have made a small change so that we accumulate all of noobs contributions because in the past his username changed and he made significant contributions.

**Comment by maximmasiutin** [comment]
@vondele once wrote that there is already an automated script that does name processing, therefore, adding a few more lines to replace my name should not be problematic. If you could add this script to github or send it to me by email,  I could do the change myself, so it would not take your time. Please consider fulfilling my request. My contributions are not compared to those of noob, but they are steady. Correct recognition is a powerful motivator, and seeing one's name correctly displayed can boost morale and encourage continued, increased contributions. Please help.

**Comment by Disservin** [comment]
The names are taken directly from fishtest, I'm sorry but having manual adjustments for every possible contributor from fishtest is completely unmaintainable.

Here is the script which we use.
https://discord.com/channels/435943710472011776/900771437177094156/1211035576514642031

**Comment by peregrineshahin** [comment]
I thought about adding firstname and lastname in the fishtest schema in the users's profile .. that should fix your problem with more generic change on the script to include a name and a username

**Comment by vdbergh** [comment]
Sounds like a good idea...

**Comment by maximmasiutin** [comment]
> The names are taken directly from fishtest, I'm sorry but having manual adjustments for every possible contributor from fishtest is completely unmaintainable.
> 
> Here is the script which we use. https://discord.com/channels/435943710472011776/900771437177094156/1211035576514642031

I bet I am the first person in many years who asked that, so that the risk of modifying the script "for every possible contributor from fishtest" will hardly materialize. I don't think that it will be an abuse here, I bet. However, you know better and I trust you.

**Comment by peregrineshahin** [comment]
> > The names are taken directly from fishtest, I'm sorry but having manual adjustments for every possible contributor from fishtest is completely unmaintainable.
> > Here is the script which we use. https://discord.com/channels/435943710472011776/900771437177094156/1211035576514642031
> 
> I bet I am the first person in many years who asked that, so that the risk of modifying the script "for every possible contributor from fishtest" will hardly materialize. I don't think that it will be an abuse here, I bet. However, you know better and I trust you.

Having such a feature does not require people to ask for it, sometimes people get encouraged to fill their data correctly after the feature exists, currently the way software development work is that you tell the user what they need and not the opposite. It also aligns automatically with how authors file is filled. And can be used by maintainers to use such name for first contributions without asking them for the name in the PR section.

**Comment by maximmasiutin** [comment]
Please consider using this version which I updated to fulfill this request: https://github.com/maximmasiutin/fishtest-contributors/blob/main/fishtest_contributors.py

You may copy this file to your own repository, be it a separate repository for this script that you may create, or just add it to an existing repository such as the main Stockfish repository, so that you would not need to maintain this file separately.

**Comment by vdbergh** [comment]
A more generic solution is being built here https://github.com/official-stockfish/fishtest/pull/2105 .
