### ISSUE TITLE
Error: variable 'extension' may be  uninitialized in search.cpp:346:29

### ISSUE THREAD

**Issue by maximmasiutin** [official-stockfish/Stockfish#5451]
### Describe the issue

Fishtest with clang 17 or 18 on Mac gives an error: Error: variable 'extension' may be  uninitialized in search.cpp:346:29. 

Since search.cpp is a module from Stockfish, I consider this a Stockfish error.

```
Executing ['make', '-j1',  'profile-build', 'ARCH=native', 'COMP=clang'] failed. Error:  ["search.cpp:1391:104: warning: variable 'extension' may be  uninitialized when used here [-Wconditional-uninitialized]\n", ' 1391 \|                       + 147 * (!(ss - 1)->inCheck && bestValue  <= -(ss - 1)->staticEval - 75)) + 100 * (extension >= 2);\n', '       \|                                                                                                         ^~~~~~~~~\n', "search.cpp:346:29:  note: in instantiation of function template specialization  'Stockfish::Search::Worker::search<Stockfish::Root>' requested  here\n", '  346 \|                 bestValue =  search<Root>(rootPos, ss, alpha, beta, adjustedDepth, false);\n', '       \|                             ^\n', "search.cpp:566:20: note:  initialize the variable 'extension' to silence this warning\n", '  566 \|      Depth extension, newDepth;\n'
```

### Expected behavior

No error is given with clang 17 or 18 on Mac

### Steps to reproduce

Use clang 17 or 18 on Mac and run Fishtest or compile Stockfish with profile build on ARM-based Mac such as Mac Mini M1

### Operating system

MacOS

### Stockfish version

Stockfish 16.1 / 4d6e122

**Comment by MinetaS** [comment]
We don't have the usage of `extension` variable at line 1380. It appears that your source code of Stockfish has been modified.
