### ISSUE TITLE
Empty strings in UCI parameters

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#5473]
### Describe the issue

Empty strings shown `option name Debug Log File type string default`

### Expected behavior

Should be `option name Debug Log File type string default <empty>`

### Steps to reproduce

```./stockfish uci```

### Operating system

All

### Stockfish version

master

**Comment by Andyson007** [comment]
@vondele The issue is resolved now. You should be able to close the issue.

**Comment by vondele** [comment]
thanks for mentioning.

(tip if your commit comment contains `fixes #5473` it will automatically close the corresponding issue on merge).
