### ISSUE TITLE
GUI in Fritz 19 will not allow 24576 MB Hashtable size for stockfish

### ISSUE THREAD

**Issue by wattsgunn** [official-stockfish/Stockfish#5475]
### Describe the issue

Any attempt to allocate more than 18432 MB for Hashtable size simply reverts back to 18432.  Is it the Fritz GUI or this particular version of Stockfish?    (Author: yl25946 Date: Thu Jul 11 07:29:49 2024 +0200 Timestamp: 1720675789 removed second killer move
STC with movepicker rewrite)

### Expected behavior

What is expected is to simply allocate the maximum, in this case, the maximum is clearly displayed as 24576 MB

### Steps to reproduce

n/a

### Anything else?

n/a

### Operating system

Windows

### Stockfish version

Author: yl25946 Date: Thu Jul 11 07:29:49 2024 +0200 Timestamp: 1720675789

**Comment by vondele** [comment]
This is likely a GUI issue. To verify download a previous release of SF and let us know https://stockfishchess.org/download/

**Comment by wattsgunn** [comment]
Agreed; I tested with one of the Fritz 19 engines included with the software and had the same issue.

**Comment by wattsgunn** [comment]
Following comments from chess base support; which, sadly, make sense to my former DBA brain:

The restrictions regarding the hash size also result from the information sent by the operating system to the application. When you start the program/engine, it is initialized and information about the system status, such as available memory, is queried.
 
Based on this information, the value for the hash tables is limited.

**Comment by Disservin** [comment]
So it looks like Fritz limits what you actually set and it isnt related to Stockfish itself. Will close for now

**Comment by wattsgunn** [comment]
No, I believe the OS (Win 10) allocates resources (including RAM) at time of engine IPL

**Comment by wattsgunn** [comment]
which then limits what anything/everyting (including Fritz) can have

**Comment by EarlyEdition** [comment]
Please send a screenshot to help troubleshoot the problem should it recur. Admins analyze it and fix it if needed.

**Comment by wattsgunn** [comment]
Thank you, but this appears to clearly be a Windows issue.
