### ISSUE TITLE
Compiling on ARM

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#550]
I have major compiling issues on ARM/Linux hardware:

 (to compile on ARM Cubietruck / Debian 7:)
A:
yes, the Makefile is for a specific OS, but uses the architecture only. I guess it is a Makefile bug, but I don't know what an acceptable general solution would be (maintainers?). As a workaround add -lpthread to the LDFLAGS in the Makefile (near line 326).

1. add -lpthread to the LDFLAGS
2. change to -mfloat-abi=hard (from softfp)

Please take a look, if compiling for ARM can be fixed / auto-detected anyhow.
NOTE: take care, because changing the Makefile can break Android compilation on ARM.

-Technologov

**Comment by KassiasGrandiel** [comment]
Are you referring to line 335 of the makefile

**Comment by Technologov** [comment]
Your patch will probably break Android,  as I warned before. 
The make system should auto-detect OS type and FPU, and compile accordingly.

**Comment by zamar** [comment]
Thanks for the report!

I wouldn't call this issue as a major issues. You changed two flags and it compiled fine!

- About FPU: Some arm machines have an FPU unit and some don't... We could of course add this as a configurable parameter in Makefile... But I wonder if it is worth it.

- pthread stuff: I'm wondering why we are not linking against pthreads? I would expect this to be necessary on all ARM platforms. But I'm not an expert here. Does anybody have a clue?

What we might consider for SF8 is to separate "general-arm" and "android" compile rules.

**Comment by Technologov** [comment]
I'm not an expert either, but ARM has a wide variety of (incompatible) options.

-lpthread while required on Linux/Glibc, I think is built-in to boinic (Android lib C), which is why not needed there. (without it, it gives me a ton of linker errors in my Linux/ARM combo)

ARM FPU can have many types: -softfp, -hardfp, -soft as well as -VFP16, -VFP32 and other types.
(enter any wrong option and your program will not compile, or crash)
If anyone can give me an Android compiler environment (perhaps a Qemu-ARM VM image), I can attempt to create a makefile to compiles on both. No guarantees thou. (I have never setup Android with NDK)

**Comment by zamar** [comment]
- pthread stuff we can resolve by introducing separate "android" and "general-arm32" targets. We should probably do this.

- FPU stuff is more tricky. The only solution I have in mind is to introduce a flag on the top of Makefile to set FPU type, and maybe default this to "hard" (my understanding is that most modern arm devices have FPU unit, but I might be wrong).

**Comment by zamar** [comment]
@Technologov: Any progress on this one?

The problem with ARM is that compilation options differ from device to device as hardware is different... I'm not aware of good generic way of handling this.

**Comment by Technologov** [comment]
Nope. I didn't write a patch, because I don't have a variety of ARM environments to test on.
It would require at least several Linux-ARM images with different FPUs + Android versions.
Any of my patches can break somebody's else ARM setup.

**Comment by zamar** [comment]
Yes, that's the problem...

**Comment by enricoT** [comment]
here is on raspberry Pi 3 seems faster than no optimize:
ifeq ($(arch),armv7)
                        # https://forums.gentoo.org/viewtopic-t-1039888.html
			# CXXFLAGS += -fno-gcse -mthumb -march=... line changed
                        CXXFLAGS += -fno-gcse -mthumb -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -O2 -pipe 
		LDFLAGS += -lpthread
                endif

Total time (ms) : 67571
Nodes searched  : 9298175
Nodes/second    : 137605

time from stockfish bench is not reasonable cause i have a job that will work on 4 days with all cpu, is to show it works removing -m32 from bits=.. in addiction to change
