### ISSUE TITLE
Website: [ blog ] needs dates

### ISSUE THREAD

**Issue by Technologov** [official-stockfish/Stockfish#552]
Reading blog...
http://blog.stockfishchess.org/

Stockfish 6
Stockfish 6 is now available!

Stockfish 5
Stockfish 5 is now available!

...
But no dates anywhere. (what is "now available?" 2014? 2013 ?)

Please add dates.
Also, if possible, add the major change list, that contribute the most towards ELO gain.

**Comment by mcostalba** [comment]
Closed. His is not a techincal SF issue.

Please write directly to stocfish site web admin.
