### ISSUE TITLE
PGO build run time error

### ISSUE THREAD

**Issue by abdulbadii** [official-stockfish/Stockfish#5528]
### Describe the issue

PGO build running error right on start as it itself informs with messages some of which tells  that;
some nneu file  did not load successfully

which, if its name inspected,  is not the one automatically acquired/downloaded by build system (make)

### Expected behavior

run normally right at start 

### Steps to reproduce

$ make profile-build

(use auto detect machine specs)

### Anything else?

On Msys2/Mingw64

### Operating system

Other or N/A

### Stockfish version

16.1

**Comment by Disservin** [comment]
Can you share the entire output?

**Comment by abdulbadii** [comment]
none in terminal
it's only not-able-copied in  a chess GUI app. output,  simply try so to get it read

**Comment by Disservin** [comment]
@abdulbadii please provide more information.

**Comment by Disservin** [comment]
I think this was probably fixed by https://github.com/official-stockfish/Stockfish/commit/f677aee28baedcab4d3110d0a5c414621ed805c4 ?
