### ISSUE TITLE
Syzygy 5 men missed wins

### ISSUE THREAD

**Issue by PavelChess** [official-stockfish/Stockfish#5533]
### Describe the issue

Stockfish missed tablebase wins for examle:

b7/b2N4/8/5K2/8/2k5/8/8 w - - 0 90
8/8/8/4k3/2p5/K1N5/N7/8 b - - 0 75
Draws by 50 moves rule

8/5b1k/7P/6b1/3NK3/8/8/8 b - - 0 100
Black didn't take pawn a next move. It took it later, and after that made draw by 50 moves rule

GUI: Shredder

### Expected behavior

SF should play tablebase moves that lead to win

### Steps to reproduce

FENs for tests:

b7/b2N4/8/5K2/8/2k5/8/8 w - - 0 90
8/8/8/4k3/2p5/K1N5/N7/8 b - - 0 75
8/5b1k/7P/6b1/3NK3/8/8/8 b - - 0 100

### Operating system

All

### Stockfish version

8d1e414

**Comment by Disservin** [comment]
those positions don't lead to a tb win but to a cursed tb win.. ?

**Comment by dav1312** [comment]
> b7/b2N4/8/5K2/8/2k5/8/8 w - - 0 90

https://lichess.org/analysis/standard/b7/b2N4/8/5K2/8/2k5/8/8_w_-_-_0_90
![image](https://github.com/user-attachments/assets/56fa7373-d46e-466d-9065-31604455131d)

> 8/8/8/4k3/2p5/K1N5/N7/8 b - - 0 75

https://lichess.org/analysis/fromPosition/8/8/8/4k3/2p5/K1N5/N7/8_b_-_-_0_75
![image](https://github.com/user-attachments/assets/215370b4-b798-4347-9438-ba0a2d4ab1e3)

> 8/5b1k/7P/6b1/3NK3/8/8/8 b - - 0 100

https://lichess.org/analysis/fromPosition/8/5b1k/7P/6b1/3NK3/8/8/8_b_-_-_0_100
![image](https://github.com/user-attachments/assets/ca07f2aa-0b95-4c1d-bd08-2f49f107a5a8)
