### ISSUE TITLE
GitHub CI cannot access files outside /src

### ISSUE THREAD

**Issue by MinetaS** [official-stockfish/Stockfish#5564]
### Describe the issue

For some GitHub workflow configurations, CI mounts /src which results in Makefile not able to run scripts that are stored in other directories.

See https://github.com/official-stockfish/Stockfish/actions/runs/10665340654/job/29558499394?pr=5563

https://github.com/official-stockfish/Stockfish/blob/451044202a49fbbbe908b49fab323d70fab333e7/.github/workflows/tests.yml#L170-L180

https://github.com/official-stockfish/Stockfish/blob/451044202a49fbbbe908b49fab323d70fab333e7/.github/workflows/tests.yml#L340-L356

### Expected behavior

Scripts outside /src shall be executed normally.

### Steps to reproduce

Run `$(SHELL) <path-to-scripts-not-in-src>` in Makefile.

### Operating system

All

### Stockfish version

451044202a49fbbbe908b49fab323d70fab333e7

**Comment by Disservin** [comment]
Well the problem is not really anything specific to the CI but that docker only mounts the src to the container https://github.com/official-stockfish/Stockfish/blob/master/.github/workflows/tests.yml#L355
