### ISSUE TITLE
Windows: SF17 doesn't use all cores when run in Chessbase GUI when there is more than 1 prcessor group / logical cores are > 64

### ISSUE THREAD

**Issue by Rechenschieber** [official-stockfish/Stockfish#5572]
### Describe the issue

When run as a command line tool, everything works as expected. But running in a Chessbase GUI (I tested Fritz 16 + 17) SF17 doesn't recognize available processors properly
![SF17CB_Bug](https://github.com/user-attachments/assets/577cff3d-737f-433a-9d53-39b6a1f01623)

### Expected behavior

use all cores

### Steps to reproduce

Create UCI engine in CB GUI + run infinite analysis

### Anything else?

I tried a 64 core Threadripper - same problem. Using the 2x EPYC 9554 I tried different NUMA settings - no impact

### Operating system

Windows

### Stockfish version

Stockfish 17

**Comment by MinetaS** [comment]
Did `setoption name NumaPolicy value hardware` have no effect?

**Comment by Rechenschieber** [comment]
This helps - thank you very much. I had no idea this option exists.
Maybe it should be set by default?

**Comment by MinetaS** [comment]
I don't know much about NUMA stuffs ... maybe there's a reason why it's not default? Maybe @Sopel97 can answer this.

**Comment by Sopel97** [comment]
This is correct behaviour, it adhere's to chessbase's affinity settings. Using `setoption name NumaPolicy value hardware` overrides using parent (chessbase) affinities.

https://github.com/official-stockfish/Stockfish/issues/5307#issuecomment-2145217537

**Comment by vondele** [comment]
let me add a note to the wiki.

**Comment by vondele** [comment]
Done here https://github.com/official-stockfish/Stockfish/wiki/UCI-&-Commands#setoption

**Comment by Rechenschieber** [comment]
>Chessbase calls SetProcessAffinityMask which forcibly sets affinity to only one processor group and we respect this affinity now.
But the screenshot shows the usage of 4 different processor groups.

**Comment by noobpwnftw** [comment]
> > Chessbase calls SetProcessAffinityMask which forcibly sets affinity to only one processor group and we respect this affinity now.
> 
> But the screenshot shows the usage of 4 different processor groups.

Try right chick, group by NUMA domain.

**Comment by Sopel97** [comment]
> > Chessbase calls SetProcessAffinityMask which forcibly sets affinity to only one processor group and we respect this affinity now.
> 
> But the screenshot shows the usage of 4 different processor groups.

4 NUMA nodes that belong to the last processor group. https://learn.microsoft.com/en-us/windows/win32/procthread/processor-groups

**Comment by Rechenschieber** [comment]
I see. Thank you
