### ISSUE TITLE
Unbelievable position and engine analysis issues

### ISSUE THREAD

**Issue by joycooer** [official-stockfish/Stockfish#5573]
### Describe the issue

![sshot-2024-09-07-22-38-53](https://github.com/user-attachments/assets/ae08115a-eccf-43a3-8080-d2838a8529c7)
Consider this game
It is White's turn to play, and White has an advantage
But the engine gives bb5 at the beginning
This is a bad move
Because then Black plays rxd4, White plays bxd4, and Black plays bc4, which will result in a draw
It was not until the engine ran for about 5 minutes and calculated 40 moves that it gave the correct move for this situation, kf6.
So this should be considered a bug, because human players would not play bb5 at the beginning
This is an incredible situation, the engine's logic may be wrong, it can be fixed

### Expected behavior

the correct move for this situation, kf6

### Steps to reproduce

![sshot-2024-09-07-22-38-53](https://github.com/user-attachments/assets/c3731513-1d85-4079-986c-4423358b436b)

### Operating system

Windows

### Stockfish version

stockfish16 stockfish17

**Comment by Sopel97** [comment]
It's expected that some positions require longer analysis. Not an issue.

**Comment by joycooer** [comment]
> It's expected that some positions require longer analysis. Not an issue.

Is there a need for further analysis in this case? It is obvious that bb5 cannot be played, because if bb5 is played, it will definitely lead to a draw. White could have won, but this move led to a draw. The engine did not even consider this situation. Isn't this a bug? The engine should have analyzed that bb5 cannot be played within at least 10 moves, but it still performed more than 40 useless moves of analysis before finding the correct move. What's more terrible is that after playing bb5, the engine did not even find the best move for Black, rxd4, which makes the engine look ridiculous and stupid. I hope the stockfish development team will pay attention to this problem, which means that there must be a logical flaw in the code.

**Comment by Disservin** [comment]
I admit the behavior is weird, Stockfish recommendens bb5 and immediately after playing it, it recognizes it's a draw.
But as Sopel said Stockfish ain't perfect and fixing Stockfish's behaviour for one position is not really something which we can do without hardcoding a solution (which we don't do) and after some more time stockfish figures out that this is leads to a draw anyway

**Comment by vondele** [comment]
not so weird, since the refutation is a piece sac, and the 'solution' is essentially realizing it is a fortress. We have seen this position before.

**Comment by vondele** [comment]
Given the engine  finds it in like 1min on a single core, I don't think we should be too concerned.

**Comment by joycooer** [comment]
![sshot-2024-09-08-22-05-37](https://github.com/user-attachments/assets/be56647a-bd69-4ff7-bc65-a832b3df0163)
This situation comes from a previous engine match. When the match entered the countdown phase, lc0 played bb5 with white, and the game ended in a draw. If stockfish played white, it would probably also be a draw. Is this a common problem among chess engines?

**Comment by Disservin** [comment]
its common for chess engines not to be perfect yes
