### ISSUE TITLE
Can't compiling dev version

### ISSUE THREAD

**Issue by mymoso** [official-stockfish/Stockfish#5581]
### Describe the issue

Forgive me if this is stupid, but I was unable to compile the new development version using the same tools I have always used.

### Expected behavior

I was hoping to get a build for my PC.

### Steps to reproduce

 make profile-build ARCH=x86-64-sse41-popcnt  lto=yes extra=yes native=yes numa=yes embed=yes   -j 12  COMP=mingw
/bin/sh: ../scripts/net.sh: No such file or directory
make: *** [Makefile:922: net] Error 127
make: *** Waiting for unfinished jobs....

### Anything else?

Nope

### Operating system

Windows

### Stockfish version

Last dev version

**Comment by MinetaS** [comment]
Can you check what files are in scripts/ directory?

**Comment by Disservin** [comment]
> Also make sure you're building Stockfish in master branch. I see several options in your command that do not exist in our Makefile configuration (what are those lto, extra, native, numa and embed options?)

I think they did something weird, cfish has those https://github.com/syzygy1/Cfish/blob/master/src/Makefile

**Comment by mymoso** [comment]
OK. I appreciate the answers, but the problem persists.
Could someone help me by providing a command line that works? I use MSYS2 and have never had problems like this, which is obviously related to the latest updates of the dev version.
It seems that the nets are not being downloaded.

**Comment by Disservin** [comment]
> OK. I appreciate the answers, but the problem persists.
> Could someone help me by providing a command line that works? I use MSYS2 and have never had problems like this, which is obviously related to the latest updates of the dev version.
> It seems that the nets are not being downloaded.

@mymoso 
We haven't done anything and you haven't answered our questions. Please answer them.

1. What files are in scripts/ directory?
2. What are those lto, extra, native, numa and embed options? They do not exist in our Makefile.

**Comment by mymoso** [comment]
Ok.
1) Inside the zip file there is a scripts folder, which contains:
get_native_properties.sh
net.sh
2) I have kept these flags since I compiled Cfish, and they have never
caused problems when creating the Stockfish binary.
I am a layman but I do not understand why a process that has worked for
years stops working. The error is not on my side.

Em ter., 10 de set. de 2024 às 12:42, disservin ***@***.***>
escreveu:

**Comment by vondele** [comment]
in which directory do you execute make ? Is it
```
cd Stockfish/src
make -j profile-build
```
or something else?

**Comment by Disservin** [comment]
> Inside the zip file there is a scripts folder, which contains:

Inside a zip file? How does that work?

**Comment by mymoso** [comment]
OK

I'll try to explain my scenario.

When a new version is released, I download the zip file, extract the src
folder and point the compiler to the source address.

In my case:

G:\Chess\BYO Compilations\Stockfish\Official\src

I use the command:

make profile-build ARCH=x86-64-sse41-popcnt lto=yes extra=yes native=yes
numa=yes embed=yes -j 12 COMP=mingw

and I get the binary.

It's always been like this, and with success. So what's in the "scripts"
folder has never been relevant. I only use the src folder.

Em ter., 10 de set. de 2024 às 17:19, disservin ***@***.***>
escreveu:

**Comment by vondele** [comment]
right, and this has changed. Just using the src folder doesn't work any longer. Extract the full zip archive instead.

**Comment by MinetaS** [comment]
scripts directory has been relevant since Stockfish introduced native ARCH detection a year ago.
It just worked because Makefile never validates `ARCH` variable - if the script is missing you get an unoptimized binary.

Please add scripts folder in a directory where src folder is, so that it should look like:
```
.
├── scripts
    ├── get_native_properties.sh
│   └── net.sh
└── src
    ├── Makefile
    ...
```

**Comment by Disservin** [comment]
> It's always been like this, and with success. So what's in the "scripts" folder has never been relevant. I only use the src folder.

We make changes to Stockfish all the time and things change and evolve over time.  

Such manual workflows are prone to errors, especially once we can't anticipate because users have a non standard way of updating their Stockfish.  

The best way to update the Stockfish source this is to use [git](https://git-scm.com/), if you don't know how to use git the next best approach to get a new binary is to download one from https://github.com/official-stockfish/Stockfish/releases, we have prereleases now!  
Which are the latest dev builds. If you persist on compiling on your system please replace the entire content of the Stockfish folder with the new content, not just the `src`directory.

**Comment by mymoso** [comment]
Thank you for your attention.

Now it works and the binary has appeared. Although it is slower than the
one found in your releases.

So I will use your release and learn how to use git.

Greetings from Brazil

Em ter., 10 de set. de 2024 às 17:55, disservin ***@***.***>
escreveu:

**Comment by Disservin** [comment]
> Now it works and the binary has appeared. Although it is slower than the one found in your releases.

Did you also take the `sse41-popcnt` from the releases or a different one?

**Comment by Disservin** [comment]
Glad we got this resolved.

**Comment by mymoso** [comment]
Take the modern version for a PC and AVX2 for another machine

Em ter., 10 de set. de 2024, 18:03, disservin ***@***.***>
escreveu:
