### ISSUE TITLE
Not able to do offline build of stockfish

### ISSUE THREAD

**Issue by Zlopez** [official-stockfish/Stockfish#5593]
### Describe the issue

I'm maintaining https://github.com/flathub/org.gnome.Chess and the stockfish is one of the engines I bundle with it. Till now I used stockfish 10, but it stopped working as the url where it is hosted changed.

So I tried stockfish 17, but inside `flatpak-builder` it doesn't allow you to download any additional files, so it always fails on the `*.nnue` files missing during compilation. Is there a way to build it without internet connection?

### Expected behavior

`make build` will work even without internet connection

### Steps to reproduce

Without internet connection
```
cd src
make -j build
```

### Operating system

All

### Stockfish version

Stockfish 17

**Comment by XInTheDark** [comment]
Are you referring to the behavior where the NNUE file is downloaded during compilation?

you can avoid this by downloading the nets yourself and placing them in the same directory as the engine. this way the compilation will just use the files you downloaded.

**Comment by Zlopez** [comment]
That is exactly what I'm referring to. How does one download them manually or recognize which ones are needed? Are they tied to architecture?

**Comment by Disservin** [comment]
They are tied to the architecture and frequently change. You can in theory download them manually if you do the same steps on your personal machine (the make build) otherwise you need to dig through the files and search for the nnue name and then go to fishtest and manually download them.

**Comment by Disservin** [comment]
You can also download a release and just use that

**Comment by Zlopez** [comment]
> They are tied to the architecture and frequently change. You can in theory download them manually if you do the same steps on your personal machine (the make build) otherwise you need to dig through the files and search for the nnue name and then go to fishtest and manually download them.

That will probably not be possible in the flathub build environment, I will try to look first if there isn't an option to enable the internet connection during compilation in the flatpak builder. Otherwise I will probably stick with the latest I'm able to build without downloading additional files, which is stockfish 11.

Thanks for the help anyway

> You can also download a release and just use that

It's better to build it from source for flatpaks.
