### ISSUE TITLE
Statically link to libstdc++ helps many users on various linux distributions.

### ISSUE THREAD

**Issue by ruffianeo** [official-stockfish/Stockfish#5596]
### Describe the issue

After downloading stockfish 17 avx2 on my debian bullseye system, it won't run, because:
```
./stockfish-17-ubuntu-x86-64-avx2: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./stockfish-17-ubuntu-x86-64-avx2)
./stockfish-17-ubuntu-x86-64-avx2: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./stockfish-17-ubuntu-x86-64-avx2)
```

### Expected behavior

If you opt for statically linked standard libraries (on linux), this would not happen and the program would be usable out of the box on many more systems.

### Steps to reproduce

```
./stockfish-17-ubuntu-x86-64-avx2: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./stockfish-17-ubuntu-x86-64-avx2)
./stockfish-17-ubuntu-x86-64-avx2: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./stockfish-17-ubuntu-x86-64-avx2)
```

### Anything else?

The compiler option you might want to use to fix this is: `-static-libstdc++`.

### Operating system

All

### Stockfish version

Stockfish 17 as of the time of this issue post.

**Comment by Disservin** [comment]
see https://github.com/official-stockfish/Stockfish/issues/4026 for some previous talk about this, there are also some other aspects of why static linking on linux is not recommended.

https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html
Apparently gcc 10 is the default for debian 11.. quite old tbh given that it just became LTS.
`GCC 11.1.0: GLIBCXX_3.4.29, CXXABI_1.3.13` are you able to easily install gcc 11.1?

**Comment by R-Goc** [comment]
Out of curiosity what is stockfish currently linking to on linux? On windows ldd output is:
```
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffcf4510000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffcf3180000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffcf1890000)
```

**Comment by Disservin** [comment]
```
linux-vdso.so.1 (0x00007fff4af3d000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f033e704000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f033e61d000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f033e5fd000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f033e3d4000)
/lib64/ld-linux-x86-64.so.2 (0x00007f03435b0000
```

windows has static linking, due to the nature of libraries generally missing there

**Comment by vondele** [comment]
On linux package maintainers do a fairly good job at tracking the most recent releases.

https://packages.debian.org/search?keywords=stockfish
https://packages.fedoraproject.org/pkgs/stockfish/stockfish/    (already at 17)
https://launchpad.net/ubuntu/+source/stockfish 
...

**Comment by quanvm0501ghcodespacehdfoipgcoi** [comment]
(Just FOUND) How to solve: https://askubuntu.com/questions/1393285/how-to-install-glibcxx-3-4-29-on-ubuntu-20-04
Please add this to the Stockfish manual and credit me.
From the best solution:
Translated into practical steps:
```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt install -y g++-11
```
Then check if the version appears in the list:
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`
Resource: https://lindevs.com/install-g-on-ubuntu
Video (on github codespace): ([music link](https://www.youtube.com/watch?v=YTSc2tI3NFs&ab_channel=9CMedia)
https://drive.google.com/file/d/18FChsM9JO_0uZ3MMAnBHNuNy4qIIJNBQ/view?usp=sharing

**Comment by Disservin** [comment]
This is basic knowledge, also credit you because you took someone elses answer lol?
We currently have the gcc version fixed at gcc-11 for our release builds.
Debia Bullseye is went EOL 4 months ago and Bookworm comes with gcc-12, Ubuntu 20 goes EOL Apr 2025, and Ubuntu 22 will have gcc-11 by default, so not much of an issue soon anymore.
Installing a new GCC version is usually also relatively easy and I don't think we'll statically link for linux in the foreseeable future.

**Comment by R-Goc** [comment]
Annoying part about these old libc versions is they keep the compiler version old. And that potentially makes the final binary slower, and on clang makes the build slower. GCC didn't have big build speed improvements if I remember correctly.

**Comment by Disservin** [comment]
iirc from testing different compilers older versions were actually better at optimizations
