### ISSUE TITLE
Suggestion to Adjust GCC Workarounds in network.cpp for Newer Compiler Versions

### ISSUE THREAD

**Issue by Xenotropy** [official-stockfish/Stockfish#5597]
### Describe the issue

Hello,
I've been reviewing the code in network.cpp and noticed that there are conditional compilation blocks related to manual stack alignment due to issues in older versions of GCC (prior to 9.3). Specifically, these blocks address problems where overaligning stack variables with alignas() didn't work correctly.

Since the issue with alignas() on stack variables has been resolved in GCC 9.3, I think we can adjust the conditional compilation directives to simplify the code for newer GCC versions while maintaining compatibility with older ones.

### Expected behavior

I propose the following changes:

1. Modify the conditional compilation directives to specifically target GCC versions prior to 9.3.

2. Retain the existing workarounds for older GCC versions to ensure compatibility.

3. Simplify the code for newer

Example Replacement:
Replace the existing code:
```
constexpr uint64_t alignment = CacheLineSize;

#if defined(ALIGNAS_ON_STACK_VARIABLES_BROKEN)
    TransformedFeatureType
      transformedFeaturesUnaligned[FeatureTransformer<FTDimensions, nullptr>::BufferSize
                                   + alignment / sizeof(TransformedFeatureType)];

    auto* transformedFeatures = align_ptr_up<alignment>(&transformedFeaturesUnaligned[0]);
#else
    alignas(alignment) TransformedFeatureType
      transformedFeatures[FeatureTransformer<FTDimensions, nullptr>::BufferSize];
#endif

    ASSERT_ALIGNED(transformedFeatures, alignment);
```
With the following (test it yourself, finalize it, etc.):
```
constexpr uint64_t alignment = CacheLineSize;

#if defined(__GNUC__) && (__GNUC__ < 9 || (__GNUC__ == 9 && __GNUC_MINOR__ < 3))
// Existing code with manual stack alignment workarounds
TransformedFeatureType
  transformedFeaturesUnaligned[FeatureTransformer<FTDimensions, nullptr>::BufferSize
                               + alignment / sizeof(TransformedFeatureType)];

auto* transformedFeatures = align_ptr_up<alignment>(&transformedFeaturesUnaligned[0]);
#else
alignas(alignment) TransformedFeatureType
  transformedFeatures[FeatureTransformer<FTDimensions, nullptr>::BufferSize];
#endif

ASSERT_ALIGNED(transformedFeatures, alignment);
```

**Note**: unfortunately, I don't have access to a computer or laptop to compile and test these changes myself. However, I wanted to bring this to your attention in hopes that you might consider reviewing this optimization :)

### Stockfish version

Stockfish 17

**Comment by R-Goc** [comment]
Please use a code block for the code. While I think that running very old versions of distros isn't good, debian 10 which will have commercial support until 2029 has gcc 8.3. There were no stockfish test workers running with gcc 9.2 or lower that I could see when I checked. However breaking compatibility to avoid a few lines of code (less than 20) seems excessive.

**Comment by Sopel97** [comment]
does sf not compile with gcc <9.3 now or what?

**Comment by R-Goc** [comment]
He wants it not to compile to save 16 loc

**Comment by Disservin** [comment]
> debian 10 which will have commercial support until 2029

Well debian 10 is eol and commercial support is a vague term and we should rather go with mainstream lts distros.
Also stockfish doesn’t really target GCC 11, dunno where that came from.

**Comment by R-Goc** [comment]
But is 16 lines of code worth breaking compiler support.

**Comment by Disservin** [comment]
Yeah it is not much and not really worth

**Comment by R-Goc** [comment]
Also it is not like the existing code has any impact on other compilers. It is just an ifdef, and doesn't change the architecture of the code around it to accommodate for it.

**Comment by Disservin** [comment]
I'd just close this for now until we have a more definite answer for what minimum compiler is required for Stockfish.

**Comment by Xenotropy** [comment]
Thanks
