### ISSUE TITLE
abrok.eu (stockfish buildbot) HTTPS certificate is outdated

### ISSUE THREAD

**Issue by ofry** [official-stockfish/Stockfish#5616]
### Describe the issue

https://abrok.eu HTTPS certificate is outdated. Please renew it.

### Expected behavior

HTTPS certificate of https://abrok.eu should be valid.

### Steps to reproduce

Go to https://abrok.eu/stockfish in any browser.

### Operating system

All

### Stockfish version

all

**Comment by dav1312** [comment]
Abrok is a third-party. We have no control over that website or over the binaries that are distributed there.
We recommend downloading from our pre-releases.
You should contact the owner of the website if you have issues with it.

**Comment by ofry** [comment]
I haven't any contact info with owner of this site :(

**Comment by AlexBrunetti** [comment]
> I haven't any contact info with owner of this site :(

https://www.chessprogramming.org/Roman_Korba

Alex

**Comment by ofry** [comment]
@AlexBrunetti Yeah, I saw it. But there are no his contacts, as I see...

**Comment by AlexBrunetti** [comment]
There're two e-mail addresses here: https://disservin.github.io/stockfish-docs/stockfish-wiki/Governance-and-responsibilities.html
Anyway, the site works fine and the certificate is valid :)

Alex
