### ISSUE TITLE
Why does my computer’s 128-thread test run slower than the 64-thread speed?

### ISSUE THREAD

**Issue by Sivous** [official-stockfish/Stockfish#5635]
### Describe the issue

In recent observations, it has been noted that the utilization of Stockfish on Windows 11, version 24H2, does not exhibit a significant performance enhancement from the processor’s hyper-threading capabilities. There is negligible difference in calculation speeds between configurations of 64 threads and 128 threads. Furthermore, Task Manager analysis reveals that the 64-thread setup is not effectively leveraging the full potential of the processor’s physical cores.

- **Windows11 24H2：**

![test02](https://github.com/user-attachments/assets/91bce3ae-205b-4239-9870-63f83aa3ef10)

![64-thread-01](https://github.com/user-attachments/assets/a0e0141b-1263-45ba-a409-9b18ea2f864e)

- **Windows11 23H2：**

![test](https://github.com/user-attachments/assets/20026558-e4b0-4c86-975a-ea40885251c4)

Following the reset of my Windows 11 system to version 23H2, there has been an enhanced utilization of the processor’s physical cores by the 64-thread configuration. Nonetheless, the issue concerning reduced speed under maximum load remains unresolved. Furthermore, it has been observed that the speed with 128 threads is inferior to that of 64 threads. Task Manager data also indicates that the processor frequency during peak load with 128 threads is unexpectedly higher than when operating with 64 threads, a phenomenon observed in both the 24H2 and 23H2 versions of the system.

![af893fee2d28756263fa869391b012bb](https://github.com/user-attachments/assets/c8b3100c-6c39-4841-bf30-65d6e7481855)

![128-thread](https://github.com/user-attachments/assets/7d8a90c0-3f56-4d27-b2f1-d720bf920046)

### Expected behavior

I hope to resolve the issue of not being able to achieve higher full load speeds when using a processor with many cores in the Windows 11 system.

### Steps to reproduce

Launch stockfish_24101214_x64_avx2 on both Windows 11 24H2 and Windows 11 23H2, then enter speedtest 64 16384 and speedtest 128 16384.

### Operating system

Windows

### Stockfish version

stockfish_24101214_x64_avx2

**Comment by Sopel97** [comment]
1. how many active memory channels?
2. is there anything else running on the system? the screenshots from 64 thread runs look a bit abnormal, there seems to be more than 50% utilization
3. I assume the first screenshot is from a 64 thread run? not sure why the processor assignment is so chaotic, though we know already from other tickets that it doesn't really follow the internal numbering

**Comment by Sivous** [comment]
The system has 4 memory channels and is not running any other programs.

**Comment by Sopel97** [comment]
The higher clocks in the 128 thread run suggests it may be heavily memory bound, further exacerbated by larger cache pressure. I don't know what performance to expect on a 3990x so it's hard for me to say what's going on. A test under linux would be a good start, the behaviour there should be more predictable.

**Comment by Sopel97** [comment]
https://www.hwinfo.com/ can provide DRAM Read/Write Bandwidth information from CPU sensors on some systems. May be worth checking if it's available.

**Comment by Sivous** [comment]
But I haven’t noticed any such problems when running Stockfish 16 or earlier versions.

**Comment by Sivous** [comment]
![image](https://github.com/user-attachments/assets/64e7f89c-26db-4eb0-980b-92c517667e68)
![cachemem](https://github.com/user-attachments/assets/65f893d1-9b14-4e6d-844f-0bf999cb6be8)

**Comment by Disservin** [comment]
numa would probably be only problematic here, if the 128 thread run, only used 64 threads, which is not the case I think?

**Comment by Sivous** [comment]
In the Stockfish 15 version, comprehensive testing was conducted using the commands “bench 8196 64 20” and “bench 8196 128 20”, each executed five times. The results indicated that the 64-thread configuration efficiently utilized the physical cores without any异常 in CPU frequency under full load. Additionally, the implementation of hyper-threading contributed to a noticeable increase in processing speed, a feature that is not currently available in the latest version of Stockfish.

### 64thread test：
![image](https://github.com/user-attachments/assets/3e5f72d3-10cc-4f3d-8451-08f726df4506)
![image](https://github.com/user-attachments/assets/2a8b124a-faef-44dd-a8dc-bec073b563f9)
![image](https://github.com/user-attachments/assets/f6ed86a7-a4a7-490a-b6d5-3dc01f014f5c)
![image](https://github.com/user-attachments/assets/c959b7b6-6d5b-48eb-8c55-b7b00589e386)
![image](https://github.com/user-attachments/assets/aa0eb616-9b7b-4f83-a53a-a669d2ce7883)
![image](https://github.com/user-attachments/assets/b78fca9b-d483-463d-843a-5e90c3bda2cd)

### 128thread test：
![image](https://github.com/user-attachments/assets/80a897f4-51a2-4b6e-b3b0-0a4a01e50ee2)
![image](https://github.com/user-attachments/assets/b0041e3a-9366-4f04-a1e6-7b449d56702b)
![image](https://github.com/user-attachments/assets/f2a713c7-56b9-45bd-8650-5fc68f8ee2c1)
![image](https://github.com/user-attachments/assets/3641b03f-479d-4df8-a43e-93a7dba157cf)
![image](https://github.com/user-attachments/assets/ae87029a-ad79-4aca-9f79-d6d35113a051)
![image](https://github.com/user-attachments/assets/c588ad07-d613-4b0a-8caf-c765b1bd190c)

**Comment by Disservin** [comment]
If you repeat the bench you did in stockfish 15 in the latest version, I assume 64 and 128 threads are also close to eachother ?

**Comment by Sopel97** [comment]
regarding hwinfo i was thinking about this readout from the CPU sensors while the engine is running
![image](https://github.com/user-attachments/assets/c0e655e8-8e73-4b9a-8806-ee099efc420e)

if it's similar and high when running both 64 and 128 threads it could be memory bound

stockfish 15 had a much smaller network afaik. i'm not sure if there's a comparable test to be done here.

**Comment by Disservin** [comment]
I guess we can close this as completed then?
