### ISSUE TITLE
keyboard scancodes on Linux and FreeBSD

### ISSUE THREAD

**Issue by vinyatu** [official-stockfish/Stockfish#5656]
### Describe the issue

Pressing keyboard Arrows keys produces keyboard scancodes on Linus and FreeBSD, while on Windows Stokfish behaves as expected. Specifically:
Up arrow: ^[[A
Down arrow: ^[[B
Right arrow: ^[[C
Left arrow: ^[[D

### Expected behavior

Windows treats these keys right:
Up arrow: previous uci command
Down arrow: next uci command
Right arrow: move cursor one character right
Left arrow: move cursor one character left

### Steps to reproduce

run ./stockfish
press arrow keys
result: ^[[A^[[B^[[C^[[D 

### Anything else?

Command history is a useful feature. If not for arrow keys, then how can it be accessed?

### Operating system

Linux

### Stockfish version

Stockfish 17

**Comment by vdbergh** [comment]
Starting SF using rlwrap should work.

**Comment by vinyatu** [comment]
rlwrap seems to work OK, thank you!
