### ISSUE TITLE
Is there a cluster version of the Pikafish?

### ISSUE THREAD

**Issue by pikafish-user** [official-stockfish/Stockfish#5657]
### Describe the issue

The stockfish has  cluster version, but the pikafish (https://github.com/official-pikafish/Pikafish) does not have a cluster version. 

### Expected behavior

Need a cluster version of the latest pikafish

### Steps to reproduce

How to write a cluster version of the current pikafish?

### Operating system

All

### Stockfish version

Pikafish-240917

**Comment by Disservin** [comment]
why are u opening a pikafish issue in stockfish?
