### ISSUE TITLE
Stockfish gives score of 0 when position has many moves (caused by two-fold repetition)

### ISSUE THREAD

**Issue by nmrugg** [official-stockfish/Stockfish#566]
Maybe I'm doing something wrong, but Stockfish occasionally gives me a score of 0 when there are many moves in the `position` command, but if I use the fen from the same position, it finds a simple mate. Here's an example.

```
position startpos moves e2e4 e7e6 d2d4 f7f5 e4f5 d8h4 g1f3 f8b4 c1d2 h4e4 f1e2 c7c5 f5e6 d7e6 c2c3 h7h6 c3b4 e6e5 b1c3 e4g6 f3e5 g6f5 e2g4 g8f6 g4f5 c8f5 g2g4 f5g4 d1g4 f6g4 f2f3 b8c6 f3g4 c6d4 d2e3 a8d8 e3d4 c5d4 a1d1 a7a6 e1g1 h8f8 f1f8 e8f8 c3e2 d4d3 e5d3 b7b6 e2c3 f8e7 d3f4 d8d6 c3d5 e7d7 d5b6 d7c7 b6d5 c7b8 d5e3 d6c6 a2a4 b8c7 e3d5 c7d8 b4b5 c6d6 b5b6 d8d7 a4a5 d7d8 d1d4 h6h5 g4h5 d6h6 d5b4 d8e8 b4a6 e8f8 b6b7 g7g5 b7b8q f8f7 b8b7 f7f6 b7b6 f6e5 d4d5 e5e4 b6h6 e4f4 h6g5 f4e4 g5e5 e4f3 d5d3 f3g4 e5g5 g4g5 g1g2 g5f5 d3e3 f5f4 g2f2 f4g4 e3f3 g4h4 f3f4 h4g5 f2g3 g5h6 f4f5 h6h7 g3g4 h7h8 f5f6 h8h7 g4g5 h7g7 f6f5 g7h7 g5f6 h7g8 f5g5 g8h8 f6f7 h8h7 g5g7 h7h8 g7g6 h8h7 g6f6 h7h8 f6g6 h8h7 g6f6
go depth 10
```

gives the following
```
info depth 1 seldepth 1 multipv 1 score cp 0 nodes 2 nps 1000 tbhits 0 time 2 pv h7h8
info depth 2 seldepth 2 multipv 1 score cp 0 nodes 4 nps 2000 tbhits 0 time 2 pv h7h8
info depth 3 seldepth 2 multipv 1 score cp 0 nodes 6 nps 3000 tbhits 0 time 2 pv h7h8
info depth 4 seldepth 2 multipv 1 score cp 0 nodes 8 nps 4000 tbhits 0 time 2 pv h7h8
info depth 5 seldepth 2 multipv 1 score cp 0 nodes 10 nps 5000 tbhits 0 time 2 pv h7h8
info depth 6 seldepth 2 multipv 1 score cp 0 nodes 12 nps 6000 tbhits 0 time 2 pv h7h8
info depth 7 seldepth 2 multipv 1 score cp 0 nodes 14 nps 7000 tbhits 0 time 2 pv h7h8
info depth 8 seldepth 2 multipv 1 score cp 0 nodes 16 nps 8000 tbhits 0 time 2 pv h7h8
info depth 9 seldepth 2 multipv 1 score cp 0 nodes 18 nps 9000 tbhits 0 time 2 pv h7h8
info depth 10 seldepth 2 multipv 1 score cp 0 nodes 20 nps 10000 tbhits 0 time 2 pv h7h8
bestmove h7h8
```

Whereas

```
position fen 8/5K1k/N4R2/P6P/8/8/1P5P/8 b - - 37 68
go depth 10
```

outputs
```
info depth 1 seldepth 1 multipv 1 score mate -1 nodes 4 nps 4000 tbhits 0 time 1 pv h7h8 f6h6
info depth 2 seldepth 3 multipv 1 score mate -1 nodes 8 nps 8000 tbhits 0 time 1 pv h7h8 f6h6
info depth 3 seldepth 3 multipv 1 score mate -1 nodes 12 nps 12000 tbhits 0 time 1 pv h7h8 f6h6
info depth 4 seldepth 3 multipv 1 score mate -1 nodes 16 nps 16000 tbhits 0 time 1 pv h7h8 f6h6
info depth 5 seldepth 3 multipv 1 score mate -1 nodes 20 nps 20000 tbhits 0 time 1 pv h7h8 f6h6
info depth 6 seldepth 3 multipv 1 score mate -1 nodes 24 nps 24000 tbhits 0 time 1 pv h7h8 f6h6
info depth 7 seldepth 3 multipv 1 score mate -1 nodes 28 nps 28000 tbhits 0 time 1 pv h7h8 f6h6
info depth 8 seldepth 3 multipv 1 score mate -1 nodes 32 nps 32000 tbhits 0 time 1 pv h7h8 f6h6
info depth 9 seldepth 3 multipv 1 score mate -1 nodes 36 nps 36000 tbhits 0 time 1 pv h7h8 f6h6
info depth 10 seldepth 3 multipv 1 score mate -1 nodes 40 nps 40000 tbhits 0 time 1 pv h7h8 f6h6
bestmove h7h8 ponder f6h6
```

even though these positions are the same.

I also noticed that Fruit has this exact same problem; however, the Komodo I tried (an older free version) finds the mate with both commands.

**Comment by nmrugg** [comment]
After through other issues more carefully, I'm guessing this is a duplicate of #501.

**Comment by Rocky640** [comment]
The fen after the given list of move is indeed 
8/5K1k/N4R2/P6P/8/8/1P5P/8 b - - 37 68

The thing is that when you play out the moves, 
the same position occurs twice in the sequence.

After White move 67, there is same position on board than after white move 65,
After White move 68, there is same position on board than after white move 66

However, if after last white move 68. Rf6 and you let Black play the "only move" Kh8, 
then the engine sees 69. Rh6#

Here is the pgn of the game (completely random moves, really)
[2fold.zip](https://github.com/official-stockfish/Stockfish/files/91185/2fold.zip)

This had been discussed many times
https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/2-fold$20draw

**Comment by nmrugg** [comment]
Yeah, it's the two-fold repetition thing. I had no idea. Thanks for explaining that.

The reason why this is a problem is because I'm using Stockfish to evaluate positions. And I need it to work, even for low rated players who might repeat moves. So, if the Stockfish team isn't interested in fixing this, I guess I'll just patch it myself.

**Comment by nabildanial** [comment]
Just FYI, this is probably the best patch for 2 fold move rep fix.

https://github.com/saproj/Stockfish/commit/2620b50974f8c5bf1800e69a3d98a4c2b109d5b5

**Comment by nmrugg** [comment]
Thanks.

**Comment by nabildanial** [comment]
Also another fix attempt with much less lines of codes

https://github.com/promaret/Stockfish/commit/ded8308c894bbcb451e9825c4753912568ea74bd

**Comment by mcostalba** [comment]
I am attempting again with another idea:

http://tests.stockfishchess.org/tests/view/5699f0920ebc594a0871d8c8

**Comment by zamar** [comment]
This is not a real issue, but a design decision. Most chess computers behave this way.

I plan to close this issue soon.

**Comment by nmrugg** [comment]
I understand. I don't know if this is documented anywhere, but that would be nice.

**Comment by zamar** [comment]
Working as specified. Issue closed.
