### ISSUE TITLE
Stockfish 17 app BUG

### ISSUE THREAD

**Issue by akhojast** [official-stockfish/Stockfish#5668]
### Describe the issue

The Stockfish 17 app, version 2.3.8, available on the Apple Store, cannot open PGN files, even those created by this very version! How can I get an earlier version, such as 16.1?

### Expected behavior

The Stockfish 17 app, version 2.3.8, available on the Apple Store, cannot open PGN files, even those created by this very version! How can I get an earlier version, such as 16.1?

### Steps to reproduce

The Stockfish 17 app, version 2.3.8, available on the Apple Store, cannot open PGN files, even those created by this very version! How can I get an earlier version, such as 16.1?

### Anything else?

The Stockfish 17 app, version 2.3.8, available on the Apple Store, cannot open PGN files, even those created by this very version! How can I get an earlier version, such as 16.1?

### Operating system

MacOS

### Stockfish version

Stockfish17

**Comment by Disservin** [comment]
We dont develop the Stockfish App. This is the repository https://github.com/daylen/stockfish-mac.
