### ISSUE TITLE
Issue with opening saved files

### ISSUE THREAD

**Issue by Finbar-Callaghan** [official-stockfish/Stockfish#5671]
### Describe the issue

I have observed that opening past saved files is unsuccessful

### Expected behavior

Saved files should open and present saved games

### Steps to reproduce

Start a new game, do a few moves and then select Save from the menu...
![image](https://github.com/user-attachments/assets/6cc168dd-f7cc-4c01-bc0b-61950cd79b43)
Select the directory folder and propose a name for the test file... and then click on the save button
![image](https://github.com/user-attachments/assets/dc0fc5bc-7061-4436-88e6-2740038c14a1)
Now close the window, and then try to load the recently saved file by selecting Open Recent from the menu options
![image](https://github.com/user-attachments/assets/65e26cfd-fe1d-4dd9-ba89-c38a202395e4)
And the dialog above is the presented to you...

### Anything else?

Just downloaded the latest version of Stockfish Chess yesterday from the App store for my Mac and tried to open last night's game, but without any joy.

### Operating system

MacOS

### Stockfish version

Stockfish Chess (17)

**Comment by Disservin** [comment]
We dont develop the Stockfish App. This is the repository https://github.com/daylen/stockfish-mac.

https://github.com/official-stockfish/Stockfish/issues/5668#issuecomment-2456531959
