### ISSUE TITLE
Is it possible to use AVX2 instruction set on Apple devices? / Windows 11 ARM?

### ISSUE THREAD

**Issue by Chess321** [official-stockfish/Stockfish#5672]
### Describe the issue

No AVX2 is used while compiling.

### Expected behavior

Use also AVX2.

### Steps to reproduce

make -j profile-build  ARCH=apple-silicon COMP=clang
or
make -j profile-build ARCH=apple-silicon COMP=clang CXX=clang++

### Anything else?

https://wccftech.com/apple-game-porting-toolkit-2-supports-avx2-instruction-set/
https://wccftech.com/m4-macbook-pro-models-launching-in-late-2024/

Rosetta 2 x86-Emulation, AVX2, SME | ISA extensions
https://www.cpu-monkey.com/en/compare_cpu-apple_m4_max_16_cpu_40_gpu-vs-intel_core_i9_14900k

https://blogs.windows.com/windows-insider/2024/11/06/announcing-windows-11-insider-preview-build-27744-canary-channel/

https://www.phoronix.com/news/FEX-Emulator-2407
https://www.phoronix.com/news/Box64-0.3-Released

### Operating system

MacOS

### Stockfish version

Stockfish 17

**Comment by MinetaS** [comment]
Like any other ARCH options, `apple-silicon` is merely a preset for which ISA is used and extensions are available for the specific name. To build x86 binary executable, you need to choose one of the x86 presets (i.e. `x86-64-avx2`) or set CXXFLAGS manually.

**Comment by Disservin** [comment]
pretty much answered with https://github.com/official-stockfish/Stockfish/issues/5707
