### ISSUE TITLE
Apparent discrepancy in the reported scores - clarification/ correction requested 

### ISSUE THREAD

**Issue by rpatapa** [official-stockfish/Stockfish#5699]
### Describe the issue

```
1. import chess
2. import chess.engine
3. 
4. # Initialize the board
5. board = chess.Board()
6. 
7. # Path to the Stockfish engine executable
8. engine_path = 'C:/Users/rpratapa/Downloads/stockfish-windows-x86-64-avx2/stockfish/stockfish-windows-x86-64-avx2.exe'
9. 
10. # Initialize the engine
11. with chess.engine.SimpleEngine.popen_uci(engine_path) as engine:
12.     # Analyze the current position
13.     info = engine.analyse(board, chess.engine.Limit(time=2.0))
14.     best_move = info['pv'][0]
15.     best_move_score = info['score'].relative
16. 
17.     # Print the best move and its score
18.     print(f"Best move: {best_move}, Score: {best_move_score}")
19. 
20.     # Simulate the best move on a copy of the board
21.     board_copy = board.copy()
22.     board_copy.push(best_move)
23. 
24.     # Analyze the new position after the best move
25.     new_info = engine.analyse(board_copy, chess.engine.Limit(time=2.0))
26.     new_score = new_info['score'].relative
27. 
28.     # Print the new score
29.     print(f"Score after simulating the best move: {new_score}")
```

The output for the above code is:
```
Best move: e2e4, Score: +25
Score after simulating the best move: -19
```  

### Expected behavior

+25 corresponds to code line 18. This score is for the best move recommended by the engine.
After playing this move ... simulated ofcourse using board.copy(), the score turns negative as reported in code line 29 
-19 corresponds to code line 29. 

Why the best recommended move turned out to be a bad move?
As you can notice, the engine parameters are same for both.

If the give code is executed multiple time, each time, the values change. But in each case, 
- the score in line18 is always positive, and
- the score is line29 is always negative

### run1
Best move: e2e4, Score: +25
Score after simulating the best move: -19

### run2
Best move: e2e4, Score: +22
Score after simulating the best move: -31

### run3
Best move: e2e4, Score: +25
Score after simulating the best move: -20

### run4
Best move: e2e4, Score: +22
Score after simulating the best move: -22

### Steps to reproduce

We run the given code to simulate this. But each time it is executed, as captured for multiple runs, the values change but the highlighted discrepancy remains and consistent. 

### Operating system

Windows

### Stockfish version

stockfish-windows-x86-64-avx2

**Comment by Craftyawesome** [comment]
.relative will give it relative to the side to move. So it says white is slightly better and then says black is slightly worse. Try .white() instead.

As for the variation, limiting by time is not deterministic. And the second search will effectively be deeper than the first.
