### ISSUE TITLE
Running x86 AVX2 binary on Apple Silicon with Rosetta 2 (macOS 15)

### ISSUE THREAD

**Issue by twoplan** [official-stockfish/Stockfish#5707]
### Describe the issue

`zsh: illegal hardware instruction  ./stockfish-macos-x86-64-avx2  compiler`

### Expected behavior

AVX2 binary should run on macOS 15 with Rosetta 2

### Steps to reproduce

Run macOS x86-AVX2 Stockfish 17 in terminal on an Apple Silicon Mac with macOS 15.x
`./stockfish-macos-x86-64-avx2  compiler`

### Anything else?

With Rosetta 2 it should now be possible to use x86 binaries with AVX2 instructions on Apple Silicon macs.

But on an M4 mac running macOS 15.1.1 I get this in the terminal

`zsh: illegal hardware instruction  ./stockfish-macos-x86-64-avx2 compiler`

### Operating system

MacOS

### Stockfish version

official Stockfish 17 x86-AVX2 for macOS

**Comment by Disservin** [comment]
I think this is expected https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment#What-Cant-Be-Translated
AVX2 is not supported ?

**Comment by Disservin** [comment]
> Rosetta translates all x86_64 instructions, but it doesn’t support the execution of some newer instruction sets and processor features, such as AVX, AVX2, and AVX512 vector instructions.

**Comment by Disservin** [comment]
Why are you even doing this ? Does our m1 release not work for your m4?

**Comment by Disservin** [comment]
Ah I see there are some articles about macOS Sequoia's rosetta being able to support avx2, would be good to know if it crashes on an avx2 instruction or something else

**Comment by Disservin** [comment]
Can you run it with lldb and get a stack trace?

**Comment by twoplan** [comment]
```
lldb ./stockfish-macos-x86-64-avx2                        
(lldb) target create "./stockfish-macos-x86-64-avx2"
Current executable set to '/Users/max/Downloads/stockfish/stockfish-macos-x86-64-avx2' (x86_64).
(lldb) run
Process 37175 launched: '/Users/max/Downloads/stockfish/stockfish-macos-x86-64-avx2' (x86_64)
warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not read from the host's in-memory shared cache. This will likely reduce debugging performance.

Process 37175 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x000000010003d831 stockfish-macos-x86-64-avx2`___lldb_unnamed_symbol332 + 3089
stockfish-macos-x86-64-avx2`___lldb_unnamed_symbol332:
->  0x10003d831 <+3089>: blsrq  %rsi, %rsi
    0x10003d836 <+3094>: je     0x10003d7a0    ; <+2944>
    0x10003d83c <+3100>: jmp    0x10003d825    ; <+3077>
    0x10003d83e <+3102>: popq   %rbx
Target 0: (stockfish-macos-x86-64-avx2) stopped.
```

**Comment by Disservin** [comment]
Ah I kinda expected this, we add bmi1 to the compiler flags for avx2 since https://github.com/official-stockfish/Stockfish/pull/4202. Pretty much any platform which has avx2 also has this instruction but since apple is adding translations from x86 to arm they don't..

**Comment by Disservin** [comment]
Since we distribute arm binaries for mac I don't feel like removing this, if you still want to test the speed you can try to remove the -mbmi from the Makefile and recompile and run your test.

**Comment by Disservin** [comment]
Yeah apple's translation isn't the best nor is it even correct, see https://github.com/carsongoodwin32/rosetta2_avx_dive.. 12% slower and wrong result

**Comment by RogerThiede** [comment]
> Yeah apple's translation isn't the best nor is it even correct

I don’t have knowledge if it's different, but it should be pointed out that this reference was analyzing a pre-release (Beta) version of translation.  It would certainly be noteworthy to claim that a final release produces wrong results, but I haven't discovered anyone claiming that yet.

**Comment by mstembera** [comment]
FYI  No idea if this could be related but we currently have a bug making use of random TT data in search.
https://github.com/official-stockfish/Stockfish/issues/5503

**Comment by Disservin** [comment]
not related in any way
