### ISSUE TITLE
Build failure with GCC 15 because of incorrect use of incbin

### ISSUE THREAD

**Issue by thesamesam** [official-stockfish/Stockfish#5714]
### Describe the issue

stockfish currently doesn't build with upcoming GCC 15:
```
$ g++-15 benchmark.ii bitboard.ii evaluate.ii main.ii misc.ii movegen.ii movepick.ii position.ii search.ii thread.ii timeman.ii tt.ii uci.ii ucioption.ii tune.ii tbprobe.ii nnue_misc.ii half_ka_v2_hm.ii network.ii engine.ii score.ii memory.ii -fno-exceptions -DUSE_PTHREADS -DNDEBUG -DIS_64BIT -O1 -o z -march=znver2
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccMaQhJ7.o: warning: relocation against `_ZN12_GLOBAL__N_122gEmbeddedNNUESmallDataE' in read-only section `.text._ZN9Stockfish4Eval4NNUE7NetworkINS1_19NetworkArchitectureILj128ELi15ELi32EEENS1_18FeatureTransformerILj128EXadL_ZNS_9StateInfo16accumulatorSmallEEEEEE13load_internalEv[_ZN9Stockfish4Eval4NNUE7NetworkINS1_19NetworkArchitectureILj128ELi15ELi32EEENS1_18FeatureTransformerILj128EXadL_ZNS_9StateInfo16accumulatorSmallEEEEEE13load_internalEv]'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccMaQhJ7.o: in function `Stockfish::Eval::NNUE::Network<Stockfish::Eval::NNUE::NetworkArchitecture<3072u, 15, 32>, Stockfish::Eval::NNUE::FeatureTransformer<3072u, &Stockfish::StateInfo::accumulatorBig> >::load_internal()':
network.cpp:(.text._ZN9Stockfish4Eval4NNUE7NetworkINS1_19NetworkArchitectureILj3072ELi15ELi32EEENS1_18FeatureTransformerILj3072EXadL_ZNS_9StateInfo14accumulatorBigEEEEEE13load_internalEv[_ZN9Stockfish4Eval4NNUE7NetworkINS1_19NetworkArchitectureILj3072ELi15ELi32EEENS1_18FeatureTransformerILj3072EXadL_ZNS_9StateInfo14accumulatorBigEEEEEE13load_internalEv]+0x30): undefined reference to `(anonymous namespace)::gEmbeddedNNUEBigData'
/usr/lib/gcc/x86_64-pc-linux-gnu/15/../../../../x86_64-pc-linux-gnu/bin/ld: network.cpp:(.text._ZN9Stockfish4Eval4NNUE7NetworkINS1_19NetworkArchitectureILj3072ELi15ELi32EEENS1_18FeatureTransformerILj3072EXadL_ZNS_9StateInfo14accumulatorBigEEEEEE13load_internalEv[_ZN9Stockfish4Eval4NNUE7NetworkINS1_19NetworkArchitectureILj3072ELi15ELi32EEENS1_18FeatureTransformerILj3072EXadL_ZNS_9StateInfo14accumulatorBigEEEEEE13load_internalEv]+0x3a): undefined reference to `(anonymous namespace)::gEmbeddedNNUEBigSize'
[...]
```

I reported this over on the GCC side at https://gcc.gnu.org/PR117133 where the conclusion was that stockfish's use of incbin is unusual and possibly undefined, given that incbin is currently being used in an anonymous namespace.

### Expected behavior

Successful build.	

### Steps to reproduce

Build a snapshot of GCC 15 and then try to use it to build stockfish.

### Anything else?

On the GCC bug, the conclusion was Stockfish should stop using an anonymous namespace w/ incbin, as it's ill-defined.

### Operating system

Linux

### Stockfish version

17

**Comment by thesamesam** [comment]
Jakub on the GCC bug reduced Stockfish's use down to:
```
namespace {
asm (".section .rodata; gEmbeddedNNUEBigData:; .previous");
extern "C" const unsigned char gEmbeddedNNUEBigData[];
};
const unsigned char *p = gEmbeddedNNUEBigData;
int main () {}
```

i.e. Stockfish currently relies on something defined in a anonymous namespace for a global symbol.

**Comment by jakubjelinek** [comment]
Note, with GCC 15 or clang 19 (or later for both) you could use
```c
#ifdef __has_embed
#if __has_embed("filename")
const unsigned char gEmbeddedNNUEBigData[] = {
#embed "filename"
};
const unsigned char* const gEmbeddedNNUEBigEnd  = &gEmbeddedNNUEBigData[sizeof gEmbeddedNNUEBigData];
const unsigned int         gEmbeddedNNUEBigSize      = sizeof(gEmbeddedNNUEBigData);
#endif
#endif
```
Of course, as a fallback it can use .incbin the way it was using if it isn't in an anonymous namespace (you can surely use e.g. .hidden directive for it too if you don't want to export it from the TU).

**Comment by jicama** [comment]
Since incbin creates global symbols (see INCBIN_GLOBAL_LABELS, e.g. https://github.com/graphitemaster/incbin/blob/main/incbin.h#L417) using it in an anonymous namespace doesn't make sense even if it worked.

**Comment by Disservin** [comment]
Thanks, in the past this wasn't in an anonymous namespace.. it was (mistakenly) changed in a recent refactor.

`#embed` macro is nice, unfortunately our workers on our [testing framework](https://tests.stockfishchess.org/tests) rely on older compiler versions, which means we will still need incbin for some time.

I opened a PR which should fix this
