### ISSUE TITLE
Please test new eval in tt.h || d > depth8 - 5 !!!!

### ISSUE THREAD

**Issue by Nikita-Guskov** [official-stockfish/Stockfish#578]
Try this code: || d > depth8 - 5 in 53 article tt.h Local tests was very good!

**Comment by Nikita-Guskov** [comment]
Try this code: || d > depth8 - 5  in 53 article tt.h

**Comment by stockfishdeveloper** [comment]
Why can you not try it yourself? Do you not know how to code? Then why are you suggesting this change? Also, please post your speedup(if any) and if it is a functional change, test it at fishtest before you post here.

**Comment by Nikita-Guskov** [comment]
tests.stockfishchess.org does not work! (20 january 23-30 in Moscow)

**Comment by stockfishdeveloper** [comment]
Yes, the server is down now. Try again later.

**Comment by zamar** [comment]
Closed the issue as a spam.

Please use fishcooking forum for these kind of discussions.
