### ISSUE TITLE
crash on specific position

### ISSUE THREAD

**Issue by trent30** [official-stockfish/Stockfish#613]
Hi,

I use stockfish with scid and I have a crash on specific position, I test it only on stockfish : 

$ stockfish 
Stockfish 261014 64 by Tord Romstad, Marco Costalba and Joona Kiiski
position fen r3rRk1/1ppb2pp/p1p5/2n1q3/3N4/1P4Q1/PBPN2PP/6K1 b KQkq - 0 4
go infinite
info depth 1 seldepth 1 score cp 32 nodes 155 nps 22142 time 7 multipv 1 pv g8f8 d4e6 f8g8 b2e5 c5e6
info depth 2 seldepth 2 score cp 32 nodes 208 nps 29714 time 7 multipv 1 pv g8f8 d4e6 f8g8 b2e5 c5e6
info depth 3 seldepth 3 score cp 32 nodes 281 nps 40142 time 7 multipv 1 pv g8f8 d4e6 f8g8 b2e5 c5e6
info depth 4 seldepth 4 score cp 32 nodes 390 nps 48750 time 8 multipv 1 pv g8f8 d4e6 f8g8 b2e5 c5e6
info depth 5 seldepth 5 score cp 32 nodes 534 nps 66750 time 8 multipv 1 pv g8f8 d4e6 f8g8 b2e5 c5e6
info depth 6 seldepth 8 score cp 779 nodes 4051 nps 337583 time 12 multipv 1 pv g8f8 g3e5 e8e5 g2g4 c5b3 d4b3
info depth 7 seldepth 8 score cp 877 nodes 7420 nps 436470 time 17 multipv 1 pv g8f8 g3e5 e8e5 g2g4 d7g4 h8h7 e5h5 h7g6 c5b3 d4b3 h5h2
info depth 8 seldepth 9 score cp 877 nodes 8635 nps 479722 time 18 multipv 1 pv g8f8 g3e5 e8e5 g2g4 d7g4 h8h7 e5h5 h7g6 c5b3 d4b3 h5h2
info depth 9 seldepth 14 score cp 983 nodes 29470 nps 589400 time 50 multipv 1 pv g8f8 g1f1 e5g3 h2g3 c5b3 d2b3 f8f7 f1g1 g7g6 h8h7
Segmentation fault (core dumped)

**Comment by stockfishdeveloper** [comment]
On Windows 8 there is no problem--it works just fine. What operating system are you on?

**Comment by trent30** [comment]
On Ubuntu 15.10, kernel 4.2.0-34-generic

**Comment by trent30** [comment]
The version provide by ubuntu is old 5.0.dd+git20140823-1 (the same on Debian Jessie), so I just clone the git repo and compile, there is no problem anymore.
Sorry for the disturbance.
