### ISSUE TITLE
Position assessment issue

### ISSUE THREAD

**Issue by Bellatori** [official-stockfish/Stockfish#693]
![position and evaluation](https://cloud.githubusercontent.com/assets/19798698/15857368/f8444ca0-2cb2-11e6-8bff-f35c75917c0b.JPG)
![final gen on position](https://cloud.githubusercontent.com/assets/19798698/15857516/bf5dd69e-2cb3-11e6-86cb-158ae9118a49.JPG)
It is clear that SF gets the evaluation completely wrong. The position after 60. g4 at depth 78 (! 8 core AMD with 32GB RAM running W10) shows 60... hxg4 61. hxg4 at which point Rf1(2) appears to be a theoretical draw (FinalGen) but SF gives an evaluation of +- (5.24)
I am guessing that this is a function of the particular nature of the position but at 78 ply I am somewhat surprised. 

I am only submitting this for anyone's interest. I am constantly amazed by the performance of this program :)

**Comment by Vinvin20** [comment]
This is a case of fortress : https://en.wikipedia.org/wiki/Fortress_%28chess%29#Similar_example
Stockfish handle this quite badly now.
A solution would be to lower the 50 moves rules to 30 moves. For this we need a parameter "Distance to 50 moves draw".

**Comment by Bellatori** [comment]
"Stockfish handle this quite badly now."
Thanks for that. Good to know. 
Jo

**Comment by mcostalba** [comment]
Closed as non issue

Please use issue list only for software bugs, not for reporting sub-optimal play
