### ISSUE TITLE
threads die with time 

### ISSUE THREAD

**Issue by nucler** [official-stockfish/Stockfish#719]
Hi all,
what i'm doing wrong? I'm using:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
CPU(s):                80
Thread(s) per core:    2
Core(s) per socket:    10
CPU socket(s):         4
NUMA node(s):          4
CPU family:            6
Model:                 47
Stepping:              2
CPU MHz:               2261.228
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              24576K

 i compile my SF7 with command:
make build ARCH=x86-64-modern and run it with command:
./stockfish bench 1024 80 30 test.fen > test.log
I see 80 cores start to work and within ~5 min only few left. Why it happens? Any ideas?
Thanks

**Comment by MichaelB7** [comment]
OS system and version?

Have you tried your test at fewer cores - 10, 20, 40  and does it ever run
correctly?

**Comment by nucler** [comment]
Dear Michael, 
Debian 6.0
10,20 i'll try this evening, with 40 effect is similar. Under wine+Arena the precompiled SF7-modern working stable on 64 cores several hours.

**Comment by nucler** [comment]
PS. with SF6 all 80 cores i can run without problems many hours.

**Comment by nucler** [comment]
So with 10 cores after ~1 min only 5 left,about 1- min only single proc worked. Similar picture with 20 cores and 40 cores. With 80 cores the task was solved ~ 1.5 min with about 40 cores worked. The logs are attached.



[coyne_10.txt](https://github.com/official-stockfish/Stockfish/files/347226/coyne_10.txt)
[coyne_20.txt](https://github.com/official-stockfish/Stockfish/files/347229/coyne_20.txt)
[coyne_40.txt](https://github.com/official-stockfish/Stockfish/files/347228/coyne_40.txt)
[coyne_80.txt](https://github.com/official-stockfish/Stockfish/files/347227/coyne_80.txt)

**Comment by nucler** [comment]
with SF6 all 80 proc worked till the end, but % of cpu using was about 20%. 
[coyne_SF6_80.txt](https://github.com/official-stockfish/Stockfish/files/347248/coyne_SF6_80.txt)

**Comment by nucler** [comment]
screen shot of 64 cores SF7: 
![coyne_64_sf7_arena](https://cloud.githubusercontent.com/assets/19924714/16577551/3df8a676-4296-11e6-85fb-03b52328ae36.png)
work under  wine+Arena

**Comment by joergoster** [comment]
From your logs it looks like you're doing a multiPV analysis.
Please use a newer version, as a bug with our SMP implementation and using MultiPV has been fixed on May 14: https://github.com/official-stockfish/Stockfish/commit/0784bd542bf17679febd9d9d87858fd0fd0424f9

Does this solve your problem?

**Comment by nucler** [comment]
Thanks  joergoster, i'll try! 
indeed i have 
499           if (!mainThread)
                 break;

**Comment by nucler** [comment]
hmm.  It looks better, the task was solved with ~3 min with Nodes/second    : 43892658
and 63 cores alive :) 
I'll try to get dev version and compile it, it seems in your search.cpp the line has # 510 and i have #499

**Comment by nucler** [comment]
Ok. i got current version from github/official-stockfish/Stockfish/ and compile it.
some warnings remaining:
syzygy/tbprobe.cpp: In function 'probe_wdl_table(Position&, int*)':
syzygy/tbprobe.cpp:205:14: warning: array subscript is above array bounds [-Warray-bounds]
         p[i++] = pop_lsb(&bb) ^ mirror;
              ^
syzygy/tbprobe.cpp:205:14: warning: array subscript is above array bounds [-Warray-bounds]
syzygy/tbprobe.cpp: In function 'Tablebases::probe_dtz(Position&, int*)':
syzygy/tbprobe.cpp:315:14: warning: array subscript is above array bounds [-Warray-bounds]
         p[i++] = pop_lsb(&bb) ^ mirror;
              ^
syzygy/tbprobe.cpp:315:14: warning: array subscript is above array bounds [-Warray-bounds]
g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o  -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto

the rest looks fine

**Comment by nucler** [comment]
thank you all! Now all 80 cores are alive till the end!
![coyne_80_sf7](https://cloud.githubusercontent.com/assets/19924714/16581517/29b7fbf8-42aa-11e6-9d34-9b338025f801.png)

**Comment by joergoster** [comment]
Glad to hear! The warnings about array bounds is a known problem of gcc, which you can simply ignore.
