### ISSUE TITLE
Windows 32: Profile build broken

### ISSUE THREAD

**Issue by lantonov** [official-stockfish/Stockfish#721]
Profile build broken with 32-bit compiler after commit ec6aab0

Tested with mingw32 gcc 4.7.3 on Windows 8.1 32-bit

Steps to reproduce:

[mingw32-]make clean
[mingw32-]make profile-build debug=yes optimize=yes ARCH=x86-32 COMP=mingw

https://groups.google.com/d/msg/fishcooking/wh1s7-AfZbM/79NkuFCcBwAJ

**Comment by sf-x** [comment]
As a workaround you can add -mstackrealign to CXXFLAGS for x86-32 only.

**Comment by lantonov** [comment]
The problem with profile-builds in Win32 compiles disappeared when including '-mstackrealign' in the compiler flags in Makefile.

**Comment by lantonov** [comment]
The other proposed flag:
-mincoming-stack-boundary=2 -mpreferred-stack-boundary=2
does not work (again error 139 Segmentation fault)

**Comment by lantonov** [comment]
As a confirmation that SSE is involved, I had no problem to profile-build ARCH=general-32 and ARCH=x86-32-old without the additional flag -mstackrealign (these do not use SSE)

**Comment by mcostalba** [comment]
It seems it is a issue with an old version of gcc (4.7.3), newer versions don't seem to crash. Closing now.
