### ISSUE TITLE
Compile on CMD but not Eclipse CDT on the same windows

### ISSUE THREAD

**Issue by iGeek098** [official-stockfish/Stockfish#745]
I tried to compile Stockfish 7 on Eclipse Neon latest but it comes with 80 errors in Bitboards about 40 errors says "bitboard doesn't name a type", also other errors with other variables says "doesn't name a type"

i build it with cmd like this "make profile-build ARCH=x86-64-bmi2 COMP=mingw"
and it worked

the same on Eclipse doesn't work (Target = profile-build , command = 'make ARCH=86-64-bmi2 COMP=mingw'
also 'target = "nothing" ' 'command = make profile-build ARCH=x86-64-bmi2 COMP=mingw' gives the same error

i also disabled error parser and tried again runs make in the console and gives the same errors
![ecl2](https://cloud.githubusercontent.com/assets/11638396/17605401/98626bd2-601a-11e6-8054-e6ef7e55cfb8.png)
![ecl3](https://cloud.githubusercontent.com/assets/11638396/17605402/98711542-601a-11e6-97b4-fd3a1b35e300.png)
![ecl](https://cloud.githubusercontent.com/assets/11638396/17605403/988268b0-601a-11e6-8ff5-3f0a17748278.png)

please help!

**Comment by stockfishdeveloper** [comment]
Please see: http://support.stockfishchess.org/kb/advanced-topics/compiling-stockfish-on-windows
This is not an issue, so please post in the forum if you have further questions: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjQ79LqzLrOAhVL7SYKHUa-CPYQFggeMAA&url=https%3A%2F%2Fgroups.google.com%2Fd%2Fforum%2Ffishcooking&usg=AFQjCNE0WpYwUgCONZ-uMPWEAUR9kKScvg

**Comment by mcostalba** [comment]
This is not a SF issue. I am closing it.

**Comment by iGeek098** [comment]
Sorry

**Comment by iGeek098** [comment]
but please can you help i cant work on the code

**Comment by mcostalba** [comment]
If you need help, post on our forum:

https://groups.google.com/forum/?fromgroups=#!forum/fishcooking

**Comment by iGeek098** [comment]
can you please recommend an IDE, i cant work on the code

**Comment by mcostalba** [comment]
MSVC community edition if you just want to press a button and have the exe
cooked.

But I suggest any editor and an open terminal windows to run the compile
command line (make build ...).

Personally I use qtcreator

**Comment by iGeek098** [comment]
Thanks a lot.

**Comment by iGeek098** [comment]
well thanks,
by the way i could solve the problem with eclipse so for reference (if sb wants to use eclipse):
install cygwin (i dont know if necessary or not)
then with toolchain selector select none
(make sure the default make command is make ARCH=x86-64 COMP=mingw not make -k)
create new make targets with that make config above(i mean arch=... and comp=... targets( "build and clean") 
make the build target you made above (settings 1 target = build ,command =( make ARCH="your arch" COMP=mingw) "untick use builder settings"
you should see build progress in console
after success
make new run config 
select stockfish.exe you just made
tick auto build if you want then click on run it will run in the console

**Comment by iGeek098** [comment]
i made my own build and it was faster 20% than prebuilt or built with cmd
