### ISSUE TITLE
Stockfish not see the checkmate in 4 moves

### ISSUE THREAD

**Issue by sturing** [official-stockfish/Stockfish#766]
In this position:
FEN:8/8/3K4/2pPp3/1pB1Pp2/pn1N1Pp1/k4pP1/5Rb1 w - - 0 5

P.S. This problem occurs not only in Stockfish.

P.P.S. My program (Zevra) and Deep Shredder sees checkmate in 4 moves in this position. Checked gradually starting to increase the depth of search.

**Comment by braich** [comment]
Latest Stockfish does not have such problem.
```
Analysis by Stockfish 260816 64 POPCNT:
5.Na8-b6 Bg1-h2 6.Nb6-a4 Bh2-g1 7.Nd3xc5 Bg1-h2 8.Bc4xb3# 
+-  (#4)    Depth: 89/32   00:00:06  4362kN, tb=15

```
What Stockfish version are you using?

**Comment by sturing** [comment]
Last version. Command: "go depth 20". "go mate 4" worked. score cp 574 (no mate)

`position fen 8/8/3K4/2pPp3/1pB1Pp2/pn1N1Pp1/k4pP1/5Rb1 w - - 0 5`
`go depth 10`
`info depth 1 seldepth 2 multipv 1 score cp 209 nodes 73 nps 18250 tbhits 0 time 4 pv d6e5  `
`info depth 2 seldepth 2 multipv 1 score cp 304 nodes 130 nps 26000 tbhits 0 time 5 pv d6e5 g1h2 d3c1 a2b2 c1b3`
`info depth 3 seldepth 4 multipv 1 score cp 360 nodes 202 nps 40400 tbhits 0 time 5 pv d6e5 g1h2 d3f2`
`info depth 4 seldepth 4 multipv 1 score cp 398 nodes 319 nps 63800 tbhits 0 time 5 pv d6e5 g1h2 e5f4 h2g1`
`info depth 5 seldepth 5 multipv 1 score cp 398 nodes 423 nps 70500 tbhits 0 time 6 pv d6e5 g1h2 e5f4 h2g1 f4g3`
`info depth 6 seldepth 6 multipv 1 score cp 762 nodes 564 nps 94000 tbhits 0 time 6 pv d6e5 g1h2 e5f4 h2g1 f4g3 g1h2 g3h2`
`info depth 7 seldepth 7 multipv 1 score cp 762 nodes 721 nps 103000 tbhits 0 time 7 pv d6e5 g1h2 e5f4 h2g1 f4g3 g1h2 g3h2`
`info depth 8 seldepth 8 multipv 1 score cp 996 nodes 1303 nps 162875 tbhits 0 time 8 pv d6e5 g1h2 e5f4 h2g1 f4g3 g1h2 g3f2 h2g3 f2g3`
`info depth 9 seldepth 10 multipv 1 score cp 564 nodes 2934 nps 293400 tbhits 0 time 10 pv d6e5 g1h2 e5f4 h2g1 f4g3 g1h2 g3f2 h2d6 f2e2 d6c7 d3c1 a2b2 c1b3`
`info depth 10 seldepth 15 multipv 1 score cp 574 nodes 4038 nps 310615 tbhits 0 time 13 pv d6e5 g1h2 e5f4 h2g1 f4g3 g1h2 g3f2 h2d6 f2e2 d6c7 f3f4`
`bestmove d6e5 ponder g1h2``
