### ISSUE TITLE
silence currmove output?

### ISSUE THREAD

**Issue by isaacl** [official-stockfish/Stockfish#857]
What's the feeling about the currmove / currmovenumber output? is it useful enough to enable by default? Could we add an option to disable?

The Time::now() call looks suspicious to me for performance but I guess it's main thread.

**Comment by mcostalba** [comment]
The **feeling** is that this is not the proper place to discuss your topic

**Comment by mcostalba** [comment]
@isaacl We take "Issues" definition quite strictly, in particular we collect here bugs, odd behaviours, platform incompatibilities, etc.

This section is not intended for feature requests, please use the forum for that.
