### ISSUE TITLE
It's gone into a loop...

### ISSUE THREAD

**Issue by JontyFrancis** [official-stockfish/Stockfish#869]
I'm playing a game where (as a learner) I'm following the hints and playing against the computer (Stockfish 6.0) but it keeps making the same two moves (back and forth) over and over in a loop. I'm making the same two moves on my side too. Shouldn't Stockfish move on and try another move? Only one piece on each side has been captured... so it's a full board, more or less. Thanks...

**Comment by stockfishdeveloper** [comment]
Could you elaborate on this?
Show a fen, move list, etc.?

I highly doubt that this is a bug.
I'm guessing you're in a position where the best option for Stockfish is to repeat the position three times

**Comment by JontyFrancis** [comment]
When it repeated the position 3 times, there was a message about that - then it just continued repeating the same move (as did I) - Is it supposed to try a different move after 3 times?  

I've attached a couple of pics - If I make the same move again e3f3 (as hinted) Stockfish moves d8c8 (every time). 

It's my turn to move (white) in the pic.

Thanks again.

![chess](https://cloud.githubusercontent.com/assets/23408415/20233105/5f16f584-a82a-11e6-9dcf-8b69c0f4c1a3.jpg)
![chess2](https://cloud.githubusercontent.com/assets/23408415/20233110/67b4b816-a82a-11e6-825e-d0334ad154f1.jpg)

**Comment by stockfishdeveloper** [comment]
I tried it with the latest version and it does not suggest qf3 nor does it suggest qd8.

What are the external factors?
Clearing the hash table between moves, giving it very little time to think, etc.?

**Comment by JontyFrancis** [comment]
Ok - Thanks - I had it set to 1 second per move - so I just increased it to 10 secs and now it made a different move - so the game is progressing normally. Thanks very much for your help.

**Comment by stockfishdeveloper** [comment]
Sure no problem.
It's extremely rare that anyone finds a bug for a specific FEN.
