### ISSUE TITLE
 i find the engine in IOS system run 10 times slower than which in Andriod system.

### ISSUE THREAD

**Issue by changelee82** [official-stockfish/Stockfish#888]
thank you so much for developing Stockfish for chess fans all over the world, and as a developer, I am one of your big fans :)

there is a question about the Stockfish8 I want to ask:
I load Stockfish8 both in Android and IOS system, and set search depth as 12. Then i find the engine in IOS system run 10 times slower than which in Andriod system.

Could you please tell me What can I do to fix this if you know ? Thanks a lot !

**Comment by stockfishdeveloper** [comment]
Could you provide a log of the engine output?

**Comment by MichaelB7** [comment]
I'm not aware of any depth option in SF8 on IOS.  The only option that could be set to 12 is the skill level

**Comment by MichaelB7** [comment]
Just ran an analysis on the starting position for 60 seconds - it sees 132.5 million nodes in 60 seconds.  I do not believe an android phone would be 10x faster .  Unless your android phone is a 12 core Mac Pro. 😳

**Comment by changelee82** [comment]
Thank you so much for your reply. I have found the solution for the problem. I made a misake to use debug model to compile SF8 instead of release model. 

Again, thank you so mcuh for your help.

**Comment by changelee82** [comment]
Thank you so much for your reply. I have found the solution for the problem. I made a misake to use debug model to compile SF8 instead of release model. 

Again, thank you so much for your help.
