### ISSUE TITLE
Error with sanitize=yes

### ISSUE THREAD

**Issue by MichaelB7** [official-stockfish/Stockfish#892]
run "bench":
Position: 1/42
info depth 1 seldepth 1 multipv 1 score cp 90 nodes 20 nps 20000 tbhits 0 time 1 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 92 nodes 47 nps 47000 tbhits 0 time 1 pv e2e4 b7b6
**types.h:307:1: runtime error: load of value 300, which is not a valid value for type 'Depth'**
info depth 3 seldepth 3 multipv 1 score cp 119 nodes 133 nps 66500 tbhits 0 time 2 pv d2d4 d7d6 e2e4

**Comment by mcostalba** [comment]
I think the bug is in sanitize=yes, there is absolutely no reason why a Depth should be less than 300

**Comment by vondele** [comment]
@MichaelB7 doesn't fail here (nor in travis-ci), so it is at least specific to the version of the compiler you're using. What is your toolchain, and precisely which options did you use for the make command ?

**Comment by vondele** [comment]
OK, self-answering... this happens with clang-3.8:
make clean && make -j COMP=clang ARCH=x86-64 build sanitize=yes debug=yes

The reason is again Depth is an enum with range 128, question is what is storing a value of 300 there (and why doesn't gcc notice this).

**Comment by vondele** [comment]
OK, triggers plenty of times in expressions like, where d is of type Depth:
Value(150 * d / ONE_PLY);
depends thus on the type of 150 * d, and since it is overloaded as T(int(d) * i), I would say that clang is correct.
