### ISSUE TITLE
Feature request: ECMAScript / Javascript version

### ISSUE THREAD

**Issue by jfily** [official-stockfish/Stockfish#912]
Hi,

Is it possible to have a ECMAScript / Javascript version like https://github.com/exoticorn/stockfish-js provided ? (but it's a 3 yo version)

I'd like to include it in a node.js app.

**Comment by mcostalba** [comment]
@jfily this is not a feature but really a parallel project, the best way is to find someone with will and energy to update the repo you pointed above to the latest SF version.

As a side comment, we use "issues" to report bugs and technical issues, not feature requests. There is the forum for that.
