### ISSUE TITLE
Problem analyzing Chess960 position 938 (Segmentation fault: 11)

### ISSUE THREAD

**Issue by anewerla** [official-stockfish/Stockfish#920]
When running Stockfish 8 (connected as UCI engine to ChessX on Mac OS X 10.11.6) to analyze Chess 960 positions with starting position 938 then the analysis stopped with reporting Stockfish error. Executing then Unix executable stockfish-8-64 in the terminal resulted to program stop with error message "Segmentation fault: 11".
The commands given are listed hereafter:

Stockfish : ./stockfish-8-64
Stockfish 8 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
uci
id name Stockfish 8 64
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott

option name Debug Log File type string default 
option name ... (following lines deleted)
option name SyzygyProbeLimit type spin default 6 min 0 max 6
uciok
position fen rkrnbbqn/pppppppp/8/8/8/8/PPPPPPPP/RKRNBBQN w CAca - 0 1 moves e2e4 e7e5
go movetime 10000
info depth 1 seldepth 1 multipv 1 score cp 81 nodes 24 nps 12000 tbhits 0 time 2 pv f2f3
info depth 2 seldepth 2 multipv 1 score cp 63 nodes 56 nps 14000 tbhits 0 time 4 pv f2f3 a7a6
info depth 3 seldepth 3 multipv 1 score cp 95 nodes 143 nps 28600 tbhits 0 time 5 pv h1g3 a7a6 f2f3
info depth 4 seldepth 4 multipv 1 score cp 99 nodes 406 nps 67666 tbhits 0 time 6 pv f1c4 g7g5 f2f3 a7a6
info depth 5 seldepth 5 multipv 1 score cp 49 nodes 985 nps 123125 tbhits 0 time 8 pv f1c4 h8g6 f2f3 d8e6 h1g3
info depth 6 seldepth 6 multipv 1 score cp 4 nodes 3406 nps 227066 tbhits 0 time 15 pv f2f3 h8g6 e1f2 f7f6 h1g3 d8c6
info depth 7 seldepth 7 multipv 1 score cp 34 nodes 5575 nps 309722 tbhits 0 time 18 pv f1c4 h8g6 a2a4 d8e6 h1g3 f7f6 d1c3
info depth 8 seldepth 8 multipv 1 score cp 15 nodes 9458 nps 394083 tbhits 0 time 24 pv f1c4 d8e6 d1e3 h8g6 h1g3 f8c5 a2a4 f7f6
Segmentation fault: 11

**Comment by joergoster** [comment]
Well, you must of course first tell Stockfish that you now want to play/analyze chess960 games ...
The command is
```
setoption name UCI_Chess960 value true
```

**Comment by ddugovic** [comment]
Such information may be worth a mention in the documentation.

**Comment by anewerla** [comment]
Ok, thanks for the hint which indeed resolves the problem. Actually I missed the command  because it's not part of general UCI description I consulted but appears to be Stockfish specific.
However, opposite to the analysis of Chess 960 position 938 there is obviously NO need to declare a Chess 960 position in Stockfish for other start positions and positions resulting therefrom  !  Analyses of e.g. position 573 (as done before writing my earlier issue comment) and several others - again without declaring a Chess 960 game - were completed without problems. 
So only handling start position 938 and positions resulting therefrom (and any other Chess 960 start position maybe still unknown ?) requires the setoption command. Therefore it might be worth to still investigate the problem and not comsidering it resolved due to applying the recommended setoption command.

**Comment by joergoster** [comment]
@ddugovic @anewerla It IS already mentioned. From the UCI specs:
```
Chess960
========

UCI could easily be extended to support Chess960 (also known as Fischer Random Chess).

The engine has to tell the GUI that it is capable of playing Chess960 and the GUI has to tell
the engine that is should play according to the Chess960 rules.
This is done by the special engine option UCI_Chess960. If the engine knows about Chess960
it should send the command 'option name UCI_Chess960 type check default false'
to the GUI at program startup.
Whenever a Chess960 game is played, the GUI should set this engine option to 'true'.
```

**Comment by lantonov** [comment]
There are many more than one position in Chess960 which require special treatment apart from normal chess and the engine needs to know that it plays a different variant. Castling rules differ greatly between normal and Chess960. There are anomalies like cornered bishop, etc.

**Comment by anewerla** [comment]
Ok, understood. So, using the setoption UCI_Chess960 command should be always recommendable and ensure that the Stockfish Chess 960 analysis works fine.
As a consequence of this discussion I will report this problem to the ChessX developers since the problem was initially encountered there. The UCI interface implemented in ChessX might not include this command for passing relevant information to Stockfish. So it should be considered there as well.

**Comment by mcostalba** [comment]
Well, it seems that the issue has been "fixed"...time to close this one now.
