### ISSUE TITLE
wtime btime

### ISSUE THREAD

**Issue by XsupremeX** [official-stockfish/Stockfish#937]
May I make a question?

what code I must add to engine source codes or what line I can modify to make engine play in a specific time and not depending on the GUI like Fritz to set the clock?
I mean is: engine plays for example 1 minute game in every game and not need to set time in the GUI or even engine not follow time in the GUI. Or it is not possible?!?!?

Gracias!

**Comment by Rocky640** [comment]
This issue will be best answered on 
https://groups.google.com/forum/?fromgroups=#!forum/fishcooking
Please close this issue.
