### ISSUE TITLE
Idea: Rework behaviour when mate can't theoretically be avoided

### ISSUE THREAD

**Issue by muja** [official-stockfish/Stockfish#945]
The current stockfish engine when threatened with a mate-in-10 for example, will often sacrifice his Queen in order to prevent a mate-in-9. The thing is: this Queen sacrifice only delays the mate, it does nothing to prevent it. So provided its opponent had missed the mate-in-10, it blundered away its Queen for nothing. This is especially frustrating when analysing your own games and Stockfish presents a Queen sacrifice with almost equal material to delay a complex mate-in-X. (e.g. 1Q5r/3pkppp/4p3/8/1b6/2Nn1P2/1PqP2PP/2B2K1R w - - 0 0). I say delay here because after a Queen sacrifice it's very hard to not lose. I also actually don't think this should fully replace the current behaviour, but it would definitely be a nice addition if it were an option and maybe even the default. İ'm not sure how this would be approached, maybe an approach like in [Chess Surprise Analysis?](https://github.com/CYHSM/chess-surprise-analysis) might be suitable?

What do you think?

**Comment by ddugovic** [comment]
Perhaps the program invoking Stockfish could try re-searching the position with `go depth 9` if it is not satisfied with the best move.

**Comment by mcostalba** [comment]
Closing.
